### ISSUE TITLE
Siegel modular forms M_k(Gamma_0(N)) and M_k(Gamma_0(N),\psi_N) pages, N=3,4

### ISSUE THREAD

**Issue by jshurman** [LMFDB/lmfdb#1005]
The two pairs of URLs are

http://beta.lmfdb.org/ModularForm/GSp/Q/Gamma0_3/
http://beta.lmfdb.org/ModularForm/GSp/Q/Gamma0_3_psi_3/

http://beta.lmfdb.org/ModularForm/GSp/Q/Gamma0_4/
http://beta.lmfdb.org/ModularForm/GSp/Q/Gamma0_4_psi_4/

For both pairs there is vast overlap.  

For N=3, both pages say "with and without character" 

and the first of the two pages defines \psi_3 notwithstanding its nonappearance at the page.  

At one N=3 page the Gamma_0(N) knowl links to an obsolete address twice; at the other it links to an obsolete address once and to nowhere once.  

At the "page with character" for N=3, some knowls open at the bottom of the page, offscreen.

At the "page with character" for N=3, equals signs seem to be missing after A_2 and E_6 and S.

For N=4 the "page without character" says "with and without character" while the "page with character" says nothing about a character at the comparable place.

Suggestion: Merge each pair, adding a toggle switch to the dimension formula table.

**Comment by sanni85** [comment]
Moreover clicking on any of the link at the bottom of the page, for example on X(2Ω) you get on a page which says:

Oops - that should not have happened

**Comment by JohnCremona** [comment]
Is anyone working on this "critical" issue?

**Comment by davidfarmer** [comment]
I don't see the link that leads to "Oops", so I am removing the critical label.

**Comment by sanni85** [comment]
I  have removed/commented all those in pull request #1137 which is already merged (sorry I forgot to comment on here)

**Comment by AndrewVSutherland** [comment]
I am moving all this content into knowls where it can be easily edited.

**Comment by AndrewVSutherland** [comment]
Closed via #1005.  I have done some light editing on what are now knowls and will ask @jshurman to review again and edit them as required.
