### ISSUE TITLE
Siegel modular forms half integral weight page

### ISSUE THREAD

**Issue by jshurman** [LMFDB/lmfdb#1006]
The URL is

 http://beta.lmfdb.org/ModularForm/GSp/Q/Gamma0_4_half/

The page does not indicate that the degree is 2.

Also, it does not point to a knowl for half-integral weight Siegel modular forms; in fact, there may not be such a knowl.

**Comment by davidfarmer** [comment]
This seems easy to fix, but where and how would I indicate that the degree is 2?
(and is that the same as genus 2, meaning these are 4x4 matrices?)

**Comment by jshurman** [comment]
Hi, David,

I hope that you are well.  You wrote,

> This seems easy to fix, but where and how would I indicate that the 
> degree is 2? (and is that the same as genus 2, meaning these are 4x4 
> matrices?)

Several things need to be said here.

(1) Yes, "genus" and "degree" are indeed synonyms.  During my week at 
Durham, I formed the impression that the convention at the Siegel modular 
forms pages of lmfdb was to call it "degree" but to denote it "g". 
"Genus" is probably more established, but that convention quickly leads to 
a bad word-collision with the "number of handles genus" from 
topology/algebraic geometry.

(2) Yes, 4x4 matrices.  As I speculate was once discussed painfully among 
people contributing to lmfdb, some people write (for example) Sp(4,\Z) 
where others write Sp(2,\Z), both of these notations connoting 4x4 
matrices.

(3) Before addressing your question, I have been meaning to suggest that 
if still you are looking for a degree-4 L-function arising from Siegel 
modular forms then this means you need a spinor L-function in degree/genus 
g=2, and the first two interesting such L-functions are:

(a) the spinor L-function of the nonlift eigenform of weight 20 for all of 
Sp(4,\Z), computed by Nils Skoruppa.  For weights lower than 20, all 
Siegel modular forms for Sp(4,\Z) are "banal" [this is Bill Duke's term, 
according to Cris Poor] in the sense that they are lifts from degree 1, so 
the L-functions are just products of quadratic L-functions;

(b) the spinor L-function of the weight 277 Siegel paramodular form that 
Cris Poor and David S. Yuen found, corresponding to an abelian surface 
that Brumer and Kramer posited should be the smallest example of the 
Paramodularity Theorem.  See the M_2(K(p)) Siegel modular forms page at 
lmfdb.  In some sense this one is considerably more interesting than (a), 
but my view here is surely biased.

(4) Your question was how the M_{k-1/2}(Gam_0(4)) page should indicate 
that the degree is 2.  In fact, all the "Browse dimension formulas" 
examples are for degree 2, and the pages for M_{k,j}(Gam_0(2)), 
M_{k,j}(Gam(2)), M_k(Gam_0(3)), M_k(Gam_0(3),\psi_3), M_k(Gam_0(4)), and 
M_k(Gam_0(4),\psi_4) all indicate so in the same fashion, surely following 
a common template.  Only the pages for M_{k,j}(Gam_1(4)) and 
M_{k-1/2}(Gam_0(4)) do not indicate that the degree is 2.  So it seems to 
me that the easiest fix--especially in light of the millions of other 
things that you have to attend to before April is out--would be to modify 
the two anomalous "Browse dimension formulas" pages to report that the 
degree is 2 in the same way that the other six pages already do.

I hope that this is a helpful response.  Please feel invited to follow up 
if necessary.  Thank you for all that you do.

Jerry Shurman

**Comment by jshurman** [comment]
Hi, David,

Two more comments:

(1) The pending Siegel modular forms book [still years away from 
completion] by Cris Poor and David S. Yuen and me will try to establish 
the convention of optionally placing the degree/genus in parentheses as a 
superscript to help the reader.  So, for example, the groups in the 
"Browse dimension formulas" section at lmfdb would be Gamma_0^{(2)}(2), 
etc.  This adds clutter, of course, but the "(2)" superscripts could be 
added at lmfdb to reinforce the degree in the notation.

(2) Because all the "Browse dimension formulas" pages are specific to 
degree 2, at least for now a comment to that effect could be added before 
or after the "For these spaces we provide dimension formulas and some 
additional information" on the wrapper page.  But this could lead to 
trouble later if somebody adds data for a degree/genus other than 2.

Jerry Shurman

**Comment by AndrewVSutherland** [comment]
@jshurman PR #1606 addresses this issue by including the degree in the title of the dimension table browse pages and forms (with a knowl on the word degree that you will be able to edit once the PR has been merged).

More generally, each family now has a degree attribute that can be displayed anywhere we wish.

**Comment by AndrewVSutherland** [comment]
Closed via #1606.
