### ISSUE TITLE
More Siegel modular forms corrections

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1014]
From Jerry Reed via the feedback page:

On http://beta.lmfdb.org/ModularForm/GSp/Q/Sp8Z/

The bottom of the page says, "In weight 16, in addition to these two types of lifts, there are other eigenforms which currently are unknown whether they are some new type of lifts or not."  It should say, "... other eigenforms that have been shown by Ibukiyama to instantiate a conjectural lift from vector-valued Siegel modular forms."  The reference is: Ibukiyama, T. Lifting conjectures from vector valued Siegel modular forms of degree two, Comment. Math. Univ. St. Pauli 61, No. 1, pp. 87–102.

**Comment by adeines** [comment]
This duplicates #1013.
