### ISSUE TITLE
History of GL(2) modular forms

### ISSUE THREAD

**Issue by am-github** [LMFDB/lmfdb#1022]
@davidfarmer Could you please incorporate the knowl
 /mf.gl2.history 
into the modular forms homepage?

**Comment by davidfarmer** [comment]
I linked the mf.gl2.history knowl into
ModularForm/GL2/Q/holomorphic/history
which is at 
url_for("holomorphic_mf_history")

But it still has to be added to the 
info['learnmore']
on the appropriate pages.

**Comment by am-github** [comment]
@fredstro could you add the info['learnmore'] box on the classical mf page and add the link to it?

**Comment by fredstro** [comment]
Ok. I have done it and will make a pull request.
