### ISSUE TITLE
Top knowls for genus 2 isogeny classes

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#1041]
I would like to notate this page:

http://beta.lmfdb.org/Genus2Curve/Q/277/a/

with the fact that this is provably the smallest prime conductor of an abelian surface (by Brumer-Kramer). However, while genus 2 curves currently have top knowls implemented, their isogeny classes do not (and this is really a property of the isogeny class, not the individual curves).

**Comment by jvoight** [comment]
@jwj61 or someone else, can you explain to me how to do this?

**Comment by AndrewVSutherland** [comment]
All you need to do is add

{% set KNOWL_ID = "g2c.%s"|format(data['label']) %}
<h2>{{ KNOWL_INC(KNOWL_ID+'.top',title='') }}</h2>

to the top of isogney_class_g2.html (before the first <h2> that is currently add).

I can do this directly if you like.

**Comment by jvoight** [comment]
If you don't mind, and you've got your hands on this, please just do it (and add Kiran's desired text).

**Comment by AndrewVSutherland** [comment]
Done.  Need to wait for the code to be pushed beta or prod before I can 
actually add the knowl Kiran wants.

**Comment by jvoight** [comment]
Thanks!  I'll leave open for now until push.

**Comment by JohnCremona** [comment]
All merged things are now pushed to beta & prod

**Comment by AndrewVSutherland** [comment]
Fixed
