### ISSUE TITLE
Switch dbport to DEFAULT_DB_PORT

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1048]
In short, any script with:
`from lmfdb.website import dbport`
won't work.

we can fix this issue by replacing that line with:
`from lmfdb.website import DEFAULT_DB_PORT as dbport`

However, do we really need that line?

As many of the scripts use the dbport variable to do:
```
import lmfdb.base as base
....
base._init(dbport, "")
C = base.getDBConnection()
```
when they should only do:
```
import lmfdb.base as base
C = base.getDBConnection()
```

**Comment by JohnCremona** [comment]
These inconsistencies are a relic from the past, and the fact that various
different people have tinkered with the code.  Originally the dbport was
set in stone.

Of course you are free to rewrite in a better way which still works!

**Comment by edgarcosta** [comment]
I can promise you that at the moment those scripts do not work, as there is no `dbport` defined in  `lmfdb.website`.
Other, quick *dirty* fix is to is to define a global variable `dbport` again, but please don't do this.
Since those scripts have been broken for a while, perhaps is just better to leave them broken until they are needed again.

Feel free to close the ticket.
