### ISSUE TITLE
Switch Connection to MongoClient

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1049]
Hi,

I'm aware that we are sticking to pymongo 2.8 because of some old bug, but do we need to stick with the deprecated Connection class?

Best,
Edgar

**Comment by edgarcosta** [comment]
Here is the pull request: #1050

**Comment by jvoight** [comment]
I did a search and I believe that Connection is used in only a few instances--nearly all of the code uses MongoClient.  The few remaining are upload scripts, but they are easily updated.  In fact, probably all of these (that are not upload scripts) should be calling the globally defined connection anyway.  

The #1050 above is not a pull request, it is another issue, and I don't currently see an open pull request.

**Comment by edgarcosta** [comment]
I closed #1050, because I was doing too much at once.

Here is a baby version for this issue: #1059

**Comment by edgarcosta** [comment]
#1059 merged
