### ISSUE TITLE
degree 1 L-functions - Links on graph

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1051]
Many of links in the graph to "associate Dirichlet L-function." in http://beta.lmfdb.org/L/degree1/ are broken.

At the moment, all the ones in the 2nd column, i.e., order 2, are broken.

**Comment by davidfarmer** [comment]
There are some entries in the database that maybe should be different.
The one that is most relevant is:
 u'root_number': u'+*I'
which I think is meant to be a "1"

Other entries which could be different
u'sign_arg': -3.123599698885378e-17
   (I would prefer to see 0)
 u'values': [[1, u'0.62322524014023051339402008025+*I']]
   (I would prefer to see u'0.62322524014023051339402008025' ,
     since I think the "+*I" means "0*I", which is 0)
 u'leading_term': u'0.37369171291254730738158695002+*I',
     (same as previous comment)
 u'coeff_info': [u'x^2 - 1',
                 u'-1.00000000000000 + 1.22464679914735e-16*I',
                 u'\\zeta_{2}'],
    (can we omit the 0 imaginary part?)
 u'a2': [1.0, -2.8163065144692913e-30],
  (again, 0 imaginary part)

With an updated database the page should work properly.

**Comment by jwbober** [comment]
The issues go deeper than just malformed database entries. I removed all of the Dirichlet L-functions from the database and I've reinserting corrected entries now. I should have a PR soon to fix the other issues, but really I'm not quite sure I understand why _all_ L-functions weren't broken.

**Comment by jwbober** [comment]
Fixed by #1099 and updated database entries.
