### ISSUE TITLE
Isogeny class listing by Cremona label is sometimes incorrect

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1060]
The curve listing for isogeny class 50a at

    http://www.lmfdb.org/EllipticCurve/Q/50a

is incorrect.  The curves with LMFDB labels 50.a1 and 50.a3 both show Cremona label 50a1 but 50.a1 should be 50a2.

When fixed reply to enrique.gonzalez.jimenez@uam.es

**Comment by jvoight** [comment]
Yikes!

**Comment by JohnCremona** [comment]
I will fix that. It looks like a one - off glitch in stored data but I'll
also make sure of that.

**Comment by JohnCremona** [comment]
In fact EllipticCurve/50/a is OK.  There is nothing wrong in the data, only the way an isogeny class is created and displayed from a Cremona label.  I do not know whether the URL as reported was entered manually or using url_for() -- it would match the route for the function ec.by_ec_label().  I'll fix it anyway.

**Comment by JohnCremona** [comment]
Fixed by #1067
