### ISSUE TITLE
j-invariant search for elliptic curve over number field broken

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1061]
Reported through feedback page:

Start at http://www.lmfdb.org/EllipticCurve/2.0.3.1/

Enter 0 or 1 for the j-invariant and search again, crash.

When fixed reply to fnajman@math.hr

**Comment by JohnCremona** [comment]
It's just a missing import in search_parsing.py.  PR coming up.

**Comment by JohnCremona** [comment]
Fixed by #1068
