### ISSUE TITLE
Expand search ranges to include infinity

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1062]
Reported through feedback page:  we should expand our search syntax to include infinity (e.g., when searching for number fields by class number, be able to ask for h>=5.

**Comment by JohnCremona** [comment]
It works to put (for example) 100-  in the class number box.  (So I now know that we have 94 fields of class number over a million!)
So the functionality is there, perhaps the instructions could be clearer.

By the way I love the way that the large class groups are shown with (GRH) after them.  Very professional!

**Comment by JohnCremona** [comment]
The e.g. to the right of the class number search box could have examples of this: as well as an individual class number, a finite range such as 12-15,  a list such as 5,7, or an open-ended list such as 1000-.    Right now searching for a short list times out so perhaps not that one, but 1000- is fast enough.

This would perhaps clutter up the search page too much.  Somewhere there is a suggestion of having knowls for standard types of search for this.

**Comment by jwj61** [comment]
It seems that ranges like 10- or 2- work ok.  It is just when you make the database skip around that there are problems, like with 2,5,7 .   Having a knowl for standard search types is a good idea.

**Comment by nmascot** [comment]
The search for all number fields of class number >= 10^6 times out for me (Tested on prod, beta, and master). Am I doing something wrong?

**Comment by JohnCremona** [comment]
I just put 1000000- into the class number box on beta and it came back right away (5571 fields).

**Comment by nmascot** [comment]
Strange. On my time it usually times out, but sometimes succeeds (1 success out of 6 times so far). I wonder whether this could be due to the fact that I'm located far from the UK, and that my internet connection is not very fast (although still decent).

**Comment by AndrewVSutherland** [comment]
The indices that should be there are there.  There is a compound index beginning with class number that mongo db should be able to use to handle this query efficiently, but if I search for fields with class number 1- it times out on both beta.lmfdb.org and www.lmfdb.org.  The fact that 1000000- works on beta but not prod probably has to do with the difference between the database engines (MMAP4 vs Wired Tiger).

**Comment by AndrewVSutherland** [comment]
These searches are all essentially instantaneous on our postgres version of the lmfdb (you can try typing 1000- into the class number box on http://legendre.mit.edu/NumberField/ to see for yourself, this query times out on both www.lmfdb.org and beta.lmfdb.org).  So I'm not sure it makes sense to spend a lot of time trying to figure out how to make this work efficiently on mongo db.

**Comment by nmascot** [comment]
I confirm that from Beirut, these searches work perfectly (and very fast) on http://legendre.mit.edu/NumberField/ .

**Comment by AndrewVSutherland** [comment]
The original issue has been addressed (the search is both possible and instantaneous https://www.lmfdb.org/NumberField/?class_number=5-&search_type=List).
