### ISSUE TITLE
zeros of L-functions, degree 3 and 4

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1072]
Hello,

The page
http://beta.lmfdb.org/L/degree3/
(respectively http://beta.lmfdb.org/L/degree4/)
link to the first zeros of L-functions of degree 3 (resp 4)
http://beta.lmfdb.org/zeros/first/?limit=100&start=0&end=30&degree=3 
(respectively http://beta.lmfdb.org/zeros/first/?limit=100&start=0&end=30&degree=4)
in the sentence "You can also search more complete list of degree \* L-functions".
Once you click that, you get an empty list.

However, it seems that we don't know about any zeros of L-functions of degree 3 and 4, but we do, as the sample table shows...

Perhaps, we should disable the link for 3 and 4? or populate the list? I don't really know what is the solution.

this is related to what Brian mentioned here: #499, maybe a duplicate? I let you decide.

**Comment by davidfarmer** [comment]
We are close to having those L-functions served from the database,
so soon this should work as advertised.

As with some other L-function issues, in about 2 weeks we will need
to disable those features which are not working yet.

**Comment by davidfarmer** [comment]
I am (temporarily) hiding the phrase
"search a more complete list of degree d L-functions, or"
on the degree 2, 3, and 4 browsing pages.

**Comment by edgarcosta** [comment]
Thank you.

I was going to say that the degree 2 seemed to work, however after a closer look, I realized that I always got the same 100 L-functions.

**Comment by JohnCremona** [comment]
Can this be closed yet, or are we just hiding the things which do not yet work?

**Comment by AndrewVSutherland** [comment]
Given that there is currently not an actual problem here, I think we should close this.  If someone wants to create a new feature request issue describing the functionality we would like to add, that would be great, but I think it is confusing to leave this issue open, as it describes a problem you can no longer see.
