### ISSUE TITLE
L function pages for isogeny classes of elliptic curves over Q

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#1075]
Maybe this is a duplicate of a previous issue, but I think we need to address this somehow....

If you search for elliptic curves of given conductor, for example http://beta.lmfdb.org/EllipticCurve/Q/377154/   and then look around on the L function pages for different isogeny classes, you get pages all with the same title, different L functions, and the reference to the isogeny class is only in the related objects box (which can be closed, hence not displayed). I think this is a bit misleading (I was having a mathematical discussion yesterday and we were looking for examples, I was the only one who knew where to look to see the right isogeny class....)

http://beta.lmfdb.org/L/EllipticCurve/Q/377154.f/
http://beta.lmfdb.org/L/EllipticCurve/Q/377154.c/
http://beta.lmfdb.org/L/EllipticCurve/Q/377154.b/

**Comment by AndrewVSutherland** [comment]
I agree.  If you are looking at http://beta.lmfdb.org/L/EllipticCurve/Q/377154.f/, the title of the L-function page it should say (a) "where E is an elliptic curve in isogeny class 377154.f", not (b) "where E is an elliptic curve of conductor 377154".

In fact, f you look at the code (see line 357 of https://github.com/LMFDB/lmfdb/blob/master/lmfdb/lfunctions/Lfunction.p) you will see that the title is initially set to (a), but then updated to (b) on line 379.

Note that if this is changed, both the arithmetic and analytic titles need to change accordingly (see lines 377 and 378).  This is an easy fix, but I won't jump in and do it in case David F wants to chime in and/or is currently modifying this file.

**Comment by JohnCremona** [comment]
I agree that the title should be more specific than just giving the conductor.  But the L-function is associated to the isogeny class so having "L(E,s), where E is the elliptic curve  377154.a1" is a little strange, while "L(E,s), where E is an elliptic curve in isogeny class 377154.a"  is too long?  Or is the last version good?
[I wrote this earlier but never pressed the green button until I saw Drew's comment.]
  We agree -- David?

**Comment by davidfarmer** [comment]
"where E is an elliptic curve in isogeny class 377154.f"  is only 4 characters longer than the current
title, and seems to contain all the right information, so let's do that.  I'll take care of it.

**Comment by JohnCremona** [comment]
Thanks.  I thought it better for you to do it since at the same time there may be other L-function page titles to have similar changes (but I have not looked).

**Comment by JohnCremona** [comment]
I can do this today for elliptic curve L-functions.

**Comment by JohnCremona** [comment]
Trivial change at #1112
