### ISSUE TITLE
Add name of HMF friend

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#1076]
On this page
http://beta.lmfdb.org/L/ModularForm/GL2/TotallyReal/2.2.5.1/holomorphic/2.2.5.1-31.1-a/0/0/
it should say that 2.2.5.1-31.1-a is the friend.

Maybe the base field should also be a friend, as well as the Hecke eigenvalue field.
(The first of those is easy to add because that information is already passed in and used in the title)

**Comment by davidfarmer** [comment]
I'll take care of this.

**Comment by jvoight** [comment]
Fixed in pull request #1121.  I noticed giving the full label is not uniform across all L-function friends, so you may still want to look into this @davidfarmer for other classes.
