### ISSUE TITLE
Search for Q-curves among elliptic curves over NF

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#1081]
I was demonstrating elliptic curves over Q(sqrt(5)) and wanted to show an example of a Q-curve, but this wasn't available as a search parameter (even though it's one of the properties shown in the properties box).

**Comment by JohnCremona** [comment]
This would be easy to add as a search parameter since the Q-curve property is stored in the db.  Similarly CM.

Critical?

**Comment by kedlaya** [comment]
Certainly not 1.0 critical, but a low-hanging fruit for thereafter.

**Comment by JohnCremona** [comment]
This is fixed in PR #1083 which also does a bit more, but nothing at all controversial since I certainly do not want to upset things before 1.0.

**Comment by JohnCremona** [comment]
Still waiting review...

**Comment by jwj61** [comment]
Fixed
