### ISSUE TITLE
Two new test failures in HigherGenusWithAutomorphismsTest

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1086]
Probably trivial, but I have not yet looked:

FAIL: test_search_genus_group (lmfdb.higher_genus_w_automorphisms.test_hgcwa.HigherGenusWithAutomorphismsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lmfdb/lmfdb/lmfdb/higher_genus_w_automorphisms/test_hgcwa.py", line 24, in test_search_genus_group
    assert '2 matches' in L.data
AssertionError

[There are no matches as of today (2016-04-27) but I presume that is a temporary situation.]

======================================================================
FAIL: test_url_label (lmfdb.higher_genus_w_automorphisms.test_hgcwa.HigherGenusWithAutomorphismsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lmfdb/lmfdb/lmfdb/higher_genus_w_automorphisms/test_hgcwa.py", line 13, in test_url_label
    assert '[ 0; 2, 4, 6 ]' in L.data
AssertionError

[There is a Search Input error since "Higher Genus Curve with Automorphism 2.12T13.0.2-4-6 was not found in the database."]

**Comment by jenpaulhus** [comment]
This should be fixed with pull request #1085.

**Comment by JohnCremona** [comment]
Thanks -- I have not had time to test that yet since I have spent all day on other LMFDB-fixing jobs.
