### ISSUE TITLE
L-functions missing for Dirichlet characters of conductor above 999

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1087]
For primitive Dirichlet characters of conductor > 999, clicking on the L-function link in the related objects box causes the following error message to be displayed:

The page you are looking for has produced a server error.
If you want to help improving the page behind "http://www.lmfdb.org/Character/Dirichlet/1000/3", please report that page's URL!
jump back

We should probably either say something friendlier or remove the L-function link from the list of related objects on the page for the Dirichlet character (or generate the L-function page on the fly, if that is feasible).

I realize there are several issues related to degree-1 L-functions currently open, but as far as I can tell, this is not a duplicate.

**Comment by jwbober** [comment]
Now that I might actually have the data format correct, I'm inserting more data, and eventually we should go up to conductor 10000. But yes, whatever the limit of the data is, a server error is not a good response.

We don't want to generate the L-function on the fly, but probably just want a generic page that says something like "we don't have this L-function in the database".

**Comment by jwj61** [comment]
Couldn't we have everything for a Dirichlet L-function except zeros, Z-plot, and particular values?

**Comment by davidfarmer** [comment]
Characters of large conductors seem to work fine now, and I am hiding the links to Dirichlet L-funitons
when the conductor is larger than 9999 (in the next pull request), so I am removing the critical label.

Still need a way to handle the Dirichlet L-function of large conductor.

**Comment by AndrewVSutherland** [comment]
A link to http://www.lmfdb.org/L/Character/Dirichlet/7000/3/ appears on http://www.lmfdb.org/Character/Dirichlet/7000/3/ and produces a server error.

**Comment by AndrewVSutherland** [comment]
The server errors are due to the fact that there simply are not records in the Lfunctions.instances collection for any Dirichlet L-functions of conductor greater than 6461, and they are also missing for several conductors in the interval [6419,6459]; they do appear to be present for all conductors below 6419.

I think the correct fix for this is to make two changes (1) display a reasonable error message when an attempt is made to display a Dirichlet L-function that is not in the database (as in #1537), and (2) add  a function to lfunctions/LfunctionDatabase that the code displaying Dirichlet character pages can call to find out if a specified L-function instance is present and hide the link when it is not.  I will implement these.

**Comment by AndrewVSutherland** [comment]
Fixed via #1667 and #1669
