### ISSUE TITLE
"Orbit" label on HMF pages

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#1089]
http://beta.lmfdb.org/ModularForm/GL2/TotallyReal/4.4.4400.1/holomorphic/4.4.4400.1-500.2-bm

under Form it says label but it means label of the orbit
the same is true for the property box, where the label of the form is not written

I can fix this, but should I? or is it fine as it is?

**Comment by jvoight** [comment]
Yes, we only label forms up to Galois conjugacy.  Do you mean putting a /0 or /1 after to indicate the embedding of the form into the complex numbers?  This is not done for classical modular forms:
  http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/17/8/1/c/

I don't think it would be useful to have separate pages, one for every embedding of the modular form, all containing the same data--except for the extra bit of an embedding.

Please clarify what you have in mind.  Thank you!

**Comment by jvoight** [comment]
If you'd like, we can add friends links, like for classical modular forms, one for each embedding.  That might clarify the fact that we list the Galois orbit only once.

**Comment by sanni85** [comment]
Sorry, let me be more clear.
Instead of label under Form there should be "orbit label" or something like it, since label makes me think to the label of the entire Galois orbit, while you are only showing the label of the orbit. 
In the property box, the same applies.

PS Check the knowl for labels of Hilbert modular forms, I just filled that in.

**Comment by JohnCremona** [comment]
I think "label" is clear enough, and if it is the label of an orbit then
that is OK.
I was looking for Samuele's new knowl, did not find it yet, but I did find
http://www.lmfdb.org/knowledge/show/nf.ideal.label.hmf .

John

**Comment by jvoight** [comment]
Samuele: what is the difference between a label of "the entire Galois orbit" as opposed to a label of the orbit?  Is there another kind of orbit I'm missing?  I think we are unambiguous here.

**Comment by JohnCremona** [comment]
I am also inclined to close this issue.  We have no plans to have d different pages for a Hilbert newform of dimension d, one for each Hecke embedding; the choice of embedding is surely irrelevant, even for the L-functions when they are computed?
One small thing though: in the Properties box of one newform (e.g. Samuele's example above) I think the label should the whole of 4.4.4400.1-500.2-bm and not just bm.  That would be a tiny change to line 419 of hilbert_modular_forms.py which if you agree I caould tag onto PR #1090

**Comment by jvoight** [comment]
@JohnCremona : I agree, the label should be the full label, and we should close this issue.

**Comment by JohnCremona** [comment]
OK, a revised #1090 is on its way.

**Comment by sanni85** [comment]
In the example, if in both places on the page there was:
Label : 4.4.4400.1-500.2-bm
it would be more consistent since that is the label of the Galois orbit and not just bm

**Comment by jvoight** [comment]
@sanni85 Yes, that would be more consistent.

Did this whole issue boil down to whether or not we put the whole label or just the final suffix?  

It's duplicative to repeat the other parts of the label, but let's just do it to be consistent.  

@JohnCremona: this is another tiny change, but I'll wait until #1090 is merged before trying to merge on top of it.

**Comment by jvoight** [comment]
Fixed by editing master.
