### ISSUE TITLE
Degree 1 L function browsing plot

### ISSUE THREAD

**Issue by pdehaye** [LMFDB/lmfdb#112]
The plot is broken at the moment on beta.lmfdb.org
If you slide ot the range 45-50, for instance, you get something in the range 15-20 (it appears)

**Comment by jwbober** [comment]
This is still broken 2 years later.

**Comment by JohnCremona** [comment]
Example of a URL please?

**Comment by jwbober** [comment]
http://beta.lmfdb.org/L/degree1/

**Comment by davidfarmer** [comment]
still broken on chrome, works on firefox

**Comment by edgarcosta** [comment]
Broken on Chrome and Safari. Works on Firefox.
<img width="2560" alt="screen shot 2016-04-07 at 20 16 30" src="https://cloud.githubusercontent.com/assets/322822/14370637/21d29bce-fcfe-11e5-9b09-8b5fa341d38f.png">

**Comment by AndrewVSutherland** [comment]
Confirmed fix now on http://www.lmfdb.org/L/degree1/ works on chrome/safari/firefox,
