### ISSUE TITLE
Coefficient formatting for Maass L-functions

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#1132]
For example:

/L/ModularForm/GL3/Q/Maass/1/1/16.40312_0.171121/-0.4216864/

http://localhost:37777/L/ModularForm/GSp4/Q/Maass/1/1/19.81936_8.531078/2.06692296/
(See coefficient of 11^{-s})

**Comment by AndrewVSutherland** [comment]
So I see the problem on http://www.lmfdb.org/L/ModularForm/GSp4/Q/Maass/1/1/19.81936_8.531078/2.06692296/, you don't like the "+-" in +-0.992304843·11^{-s}.  That's easy to fix.

What about the formatting of http://www.lmfdb.org/L/ModularForm/GL3/Q/Maass/1/1/16.40312_0.171121/-0.4216864/ do you think should change?

**Comment by edgarcosta** [comment]
The "L = 1" and the rest of the terms aren't vertically aligned. I believe this might be an issue in all the Lfunctions

**Comment by davidfarmer** [comment]
The "L=1" is done differently with the L-functions read from the database.

**Comment by AndrewVSutherland** [comment]
Closed via #1745
