### ISSUE TITLE
Link from degree/3 to SL(3,ℤ) Maass form

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1139]
Hello,

The first row in:
http://www.lmfdb.org/L/degree3/
points to:
http://www.lmfdb.org/L/degree3/L/ModularForm/GL3/Q/Maass/1/1/16.40312_0.171121/-0.4216864/
when it should point to:
http://www.lmfdb.org/L/ModularForm/GL3/Q/Maass/1/1/16.40312_0.171121/-0.4216864/

Best,
Edgar

**Comment by davidfarmer** [comment]
Fixed in pull request #1149
