### ISSUE TITLE
top/bottom knowls on ecnf pages

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1147]
Currently we have top/bottom knowls for elliptic curves over Q but not over number fields.

Note that this will not work completely until https://github.com/LMFDB/lmfdb/issues/1140 is fixed, but issue 1140 does not prevent us from putting the links in now.

**Comment by AndrewVSutherland** [comment]
This issue depends on #1333, which is scheduled for Release 1.1.

**Comment by JohnCremona** [comment]
I have just added this (PR in a minute).  Both #1140 and #1333 are fixed.
