### ISSUE TITLE
Analytic_normalization of EC L-functions in the database

### ISSUE THREAD

**Issue by lemurell** [LMFDB/lmfdb#1151]
The field 'analytic_normalization' in the L-functions database for EC over Q is stored as 0.5. Better to have it changed to '1/2'.
(There is a hack in the code that fixes the display.)

**Comment by davidfarmer** [comment]
Jonathan persuaded us that in such a database entry, 0.5 represents
the exact number 1/2.  So the display code has to translate to the
correct representation.

**Comment by JohnCremona** [comment]
Agreed.  That is what is specified in https://github.com/LMFDB/lmfdb-inventory/blob/master/db-Lfunctions.md (after some discussion in Bristol) which I why I wrote the code that way.  For the future one change to line 108 of 
https://github.com/LMFDB/lmfdb/blob/master/lmfdb/elliptic_curves/import_ec_lfunction_data.py
will affect future uploads.

**Comment by lemurell** [comment]
OK, then my hack could be considered "the display code translates to the

correct representation" and the issue could be closed.



________________________________
Från: John Cremona <notifications@github.com>
Skickat: den 3 maj 2016 17:36
Till: LMFDB/lmfdb
Kopia: Stefan Lemurell; Author
Ämne: Re: [LMFDB/lmfdb] Analytic_normalization of EC L-functions in the database (#1151)


Agreed. That is what is specified in https://github.com/LMFDB/lmfdb-inventory/blob/master/db-Lfunctions.md (after some discussion in Bristol) which I why I wrote the code that way. For the future one change to line 108 of
https://github.com/LMFDB/lmfdb/blob/master/lmfdb/elliptic_curves/import_ec_lfunction_data.py
will affect future uploads.

-
