### ISSUE TITLE
Hide most symmetric power L-functions

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#1160]
Elliptic curve have friends links to symmetric power L-functions.

If the conductor is large then none of those links work properly,
and even for smaller conductors the high symmetric powers are broken.

Those links should be hidden.

**Comment by JohnCremona** [comment]
This is rather similar to #578 -- duplicate?

I can do this if someone tells me (1) the formula for the conductor of a symmetric n'th power and (2) an upper bound on what can be computed in (say) 5s.

**Comment by davidfarmer** [comment]
If N is the conductor of the elliptic curve then N^n is the conductor
(in the L-function sense) of its nth symmetric power.  (Maybe it can be
less in some cases.)

And if E/quadratic_field has conductor (maybe I mean norm conductor) N
and the field has discriminant d, then the conductor of its L-function
is d^2 N.

For Hilbert modular forms, I used 40000 as the cutoff of the conductor
for when to show the L-function link, so that probably is equally good
in this case.

For Hilbert modular forms I also decreased the range over which the plot
and zeros are calculated, which I can also do in these cases
(independently of hiding the L-function links).

**Comment by JohnCremona** [comment]
Thanks.  I thought it was N^n but it's nice to have that confirmed.
So we can limit symmetric squares to N=200, cubes to 34 and fourth powers to 14!  I'll do some eperiments to see if I can round those up a bit.  This is just for curves over Q right now.

**Comment by davidfarmer** [comment]
I just submitted a pull request which decreases the computation,
and I checked a couple examples which seemed to be okay.

**Comment by JohnCremona** [comment]
For Sym^2 I tried N=200 (12s), N=300 (17s), N=400 (13s but the Sym^2 conmductor is also 400), N=402 (30s).   Perhaps 300 is OK for this one.
I am also looking into the sympow functino which computes the conductor, but I think the overhead of calling it will waste time.
For Sym^3, conductors to 50 look OK.

**Comment by JohnCremona** [comment]
See pull requeswt #1163
