### ISSUE TITLE
Search and other SMF issues

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#1164]
Search box on this page:
http://localhost:37777/ModularForm/GSp/Q/Sp4Z/
should not show 6+20 as an option
should have a different word than "Find" on the button
should have something different than "arguments ( wt_range )" in front of the box
"New search" should be different, because a new table is being created.  See the classical MFs.
(Also in other places, such as
http://localhost:37777/ModularForm/GSp/Q/Gamma0_4_psi_4/
)

On this page (and others):
http://localhost:37777/ModularForm/GSp/Q/Sp8Z.12_Ikeda/ 
"Hecke eigenform? 	True " should be written in a uniform way with other entries for other objects.
For example, an elliptic curve might have "CM	no".

**Comment by AndrewVSutherland** [comment]
Addressed by #1577.
