### ISSUE TITLE
Avoiding database_names/collection_names

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1170]
Hello,

If possible the actions database_names and collection_names should be avoided in the flask app.  This is because:
0- the code for the web app, should know what it is doing, and what db/collection is trying to use
1- they need to be performed in the primary instance, which can be quite slow
2- they are slow

Should be replaced by a try:
- [x] lmfdb/modular_forms/elliptic_modular_forms/backend/__init__.py 

- [x] lmfdb/modular_forms/elliptic_modular_forms/backend/emf_utils.py 

Out of my league:
- [x] lmfdb/raw.py 

Best,
Edgar

**Comment by fredstro** [comment]
I agree that these calls  should probably be replaced out of principle,
but for the purpose of optimization (user experience )  I don't think
they  are really relevant since they should only be called on module import
(unless something is wrong with the implementation )

Are you saying that a try / except instead of database_names etc. would
really speed anything up significantly? In that case these routines are
badly implemented in mongo/pymongo.

Fredrik

**Comment by edgarcosta** [comment]
Yes it speeds up.

Take for example:
http://localhost:8082/EllipticCurve/Q/375893/a/1

With those calls, time to the first byte: 5.30s, 4.83s, 4.13s, 3.69s, 3.7s, 3.7s
Commenting all those calls out: 4.5s, 3.25s, 3.39s, 3.40s

So even though it caches some of those calls after the 3rd request, it still manages to waste 0.3s there.

Here you can see how expensive those calls are if you are not at warwick:
```
INFO:LMFDB@2016-05-04 18:21:53,975: Command listDatabases with request id 1361286294 started on server (u'warwick.lmfdb.xyz', 37010) 
INFO:LMFDB@2016-05-04 18:21:53,975: Command listDatabases with request id 1361286294 started on server (u'warwick.lmfdb.xyz', 37010) 
INFO:LMFDB@2016-05-04 18:21:54,127: Command listDatabases with request id 1361286294 on server (u'warwick.lmfdb.xyz', 37010) succeeded in 151747 microseconds 
INFO:LMFDB@2016-05-04 18:21:54,127: Command listDatabases with request id 1361286294 on server (u'warwick.lmfdb.xyz', 37010) succeeded in 151747 microseconds 
INFO:LMFDB@2016-05-04 18:21:54,128: Command listCollections with request id 39394527 started on server (u'warwick.lmfdb.xyz', 37010) 
INFO:LMFDB@2016-05-04 18:21:54,128: Command listCollections with request id 39394527 started on server (u'warwick.lmfdb.xyz', 37010) 
INFO:LMFDB@2016-05-04 18:21:54,272: Command listCollections with request id 39394527 on server (u'warwick.lmfdb.xyz', 37010) succeeded in 144335 microseconds 
INFO:LMFDB@2016-05-04 18:21:54,272: Command listCollections with request id 39394527 on server (u'warwick.lmfdb.xyz', 37010) succeeded in 144335 microseconds 


INFO:LMFDB@2016-05-04 18:23:10,079: Command listDatabases with request id 503402572 started on server (u'warwick.lmfdb.xyz', 37010) 
INFO:LMFDB@2016-05-04 18:23:10,079: Command listDatabases with request id 503402572 started on server (u'warwick.lmfdb.xyz', 37010) 
INFO:LMFDB@2016-05-04 18:23:10,330: Command listDatabases with request id 503402572 on server (u'warwick.lmfdb.xyz', 37010) succeeded in 251414 microseconds 
INFO:LMFDB@2016-05-04 18:23:10,331: Command listDatabases with request id 503402572 on server (u'warwick.lmfdb.xyz', 37010) succeeded in 251414 microseconds 
INFO:LMFDB@2016-05-04 18:23:10,331: Command listCollections with request id 736665002 started on server (u'warwick.lmfdb.xyz', 37010) 
INFO:LMFDB@2016-05-04 18:23:10,331: Command listCollections with request id 736665002 started on server (u'warwick.lmfdb.xyz', 37010) 
INFO:LMFDB@2016-05-04 18:23:10,476: Command listCollections with request id 736665002 on server (u'warwick.lmfdb.xyz', 37010) succeeded in 144593 microseconds 
INFO:LMFDB@2016-05-04 18:23:10,476: Command listCollections with request id 736665002 on server (u'warwick.lmfdb.xyz', 37010) succeeded in 144593 microseconds
```

**Comment by edgarcosta** [comment]
See #1174
