### ISSUE TITLE
random Elliptic curve should use random_object_from_collection

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1171]
Hello,

The function `random_curve()` in `mfdb/lmfdb/elliptic_curves/elliptic_curve.py` should use `random_object_from_collection(collection)` from `lmfdb/lmfdb/utils.py` instead.

edit: see #1073 

Best,
Edgar

**Comment by AndrewVSutherland** [comment]
I'm looking at the code now, and it looks to me like it does use random_object_from_collection, see line 113.

**Comment by edgarcosta** [comment]
Apologies for was wasting your time.
I'm going crazy.

Today I saw the old code there again (together with curve_of_the_day) and I was really confused, how come did I miss this one before.
I must have switched the branch on the browser or something like that. I even copied and pasted the old code into my notes, and rechecked it before submitting.... 

I'm really sorry.
