### ISSUE TITLE
lmfdb/lmfdb/elliptic_curves/elliptic_curve.py : todays_curve()

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1172]
Hello,

Instead of loading the whole thing, perhaps we should try:

`db.yourCollection.find().limit(-1).skip(yourRandomNumber).next()`

Best,
Edgar

**Comment by AndrewVSutherland** [comment]
This code is no longer reachable (short of typing in the URL manually).

**Comment by edgarcosta** [comment]
I will close it once I'm at a computer.

Thank you

**Comment by jwj61** [comment]
JEC put it in, but never made it public.  It exists as an insider's easter egg of sorts.
