### ISSUE TITLE
Lfunction_SMF2_scalar_valued instance has no attribute 'orbit'

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1183]
Here are the tracebacks: https://gist.github.com/edgarcosta/fd28b7d59e55cd2aa495c0905c0d91b8

ps: It is a bot clicking on the wrong things.

**Comment by AndrewVSutherland** [comment]
I don't see a way to currently reach any of these pages from www.lmfdb.org (e.g. the page http://lmfdb.org/ModularForm/GSp/Q/Sp4Z.30_Ups/ works and their is no L-function link, the pages listed in the gist all produce internal server errors, but this is true for any URL of the form www.lmfdb.org/L/garbage, and I plan to open a separate issue for this.

Closing (but will reopen if it recurs).
