### ISSUE TITLE
reorganize knowls

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#1198]
**_1 Upvote**_ Introduce a second category for the knowls which are used as top/bottom/formula knowls on specific pages.  These would have a required second field indicating where they live.  Ideally that new field
would be filled automatically when the knowl is created.

This would allow separating the knowledge into two pages, addressing issue #1166 (which I have closed), and issue #1027 (which asks for links to the page where top knowls live).

**Comment by AndrewVSutherland** [comment]
+1

**Comment by AndrewVSutherland** [comment]
This was addressed in PR #2736.  These knowls are now annotations, and can be searched for separately and have home pages with back links to their objects.
