### ISSUE TITLE
3 character tests fail

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1203]
3 tests in lmfdb/characters/test* fail:

http://www.lmfdb.org/Character/Dirichlet/531/40/
http://www.lmfdb.org/Character/Dirichlet/1/1/
http://www.lmfdb.org/Character/Dirichlet/40487/5/

**Comment by jwj61** [comment]
I think it is the trailing slash, so only the test is faulty (clicking on links does not add the final slash).

**Comment by JohnCremona** [comment]
OK, I will change the tests.  I wish people would be more careful about running tests (I am as bad as any).  There must have been a code change which started making this fail.

**Comment by jwj61** [comment]
Actually, it is because someone lowercased the phrase "character group" in the properties box.  Do we want upper or lower case here.

**Comment by davidfarmer** [comment]
No, it is because I lower cased "character group" in the friends.

I will fix now

**Comment by davidfarmer** [comment]
Fixed.  Pull to check.

**Comment by JohnCremona** [comment]
Thanks!
