### ISSUE TITLE
The universe is too big

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1205]
The new and beautiful universe map introduced by pull request #1202 does not display properly on browsers running in full screen mode (as one would certainly do in a presentation running on a projector and many people do as a matter of course).  The text appears below the bottom of the screen where you cannot see it.

This can be fixed (at least on screens with an aspect ratio of 16:9 or narrower) by changing the width attribute in line 104 of universe.html to 72%, but doing so means that the image will be smaller then ideal if you configure your browser window to a narrower aspect ratio, as some do, e.g., when tiling windows side by side.

I think we should make the change above so that the universe map works properly in full screen mode, especially because this is something we will very often want to show when projecting the lmfdb during a presentation or lecture.  This will mean that the universe looks smaller than ideal (but still works) on browser windows that have been configured with a narrower aspect ratio.

I invite people to comment so that we can quickly reach consensus on this issue, as it is likely to impact people making presentations on May 10.

**Comment by davidfarmer** [comment]
Can we make the words along the curved arrows bigger?

**Comment by jvoight** [comment]
<img width="1280" alt="screen shot 2016-05-06 at 4 59 19 pm" src="https://cloud.githubusercontent.com/assets/4120797/15086021/f228f8c2-13ab-11e6-84e1-87421254568f.png">

This worked OK for me, just scrolling down (both Mac laptop and desktop).  I'm happy to not have the banner appear during such a presentation.

**Comment by AndrewVSutherland** [comment]
@jvoight What browser are you running?  On Linux/Windows using either Chrome/Firefox, I see this:

![image](https://cloud.githubusercontent.com/assets/11425002/15086326/e620e574-13ad-11e6-9560-71c98571ef29.png)

**Comment by jvoight** [comment]
I tried it on both Firefox and Chrome.

**Comment by AndrewVSutherland** [comment]
So John, if/when you have a moment, pull the latest code from LMFDB, change line 104 of universe.html from 88% to 72%, and look at http://127.0.0.1:37777/universe and let me know what it looks like.

**Comment by jvoight** [comment]
<img width="1280" alt="screen shot 2016-05-07 at 11 40 38 am" src="https://cloud.githubusercontent.com/assets/4120797/15093031/e26a32d2-1448-11e6-91bb-3cddce83f260.png">

The 72% looks slightly better: it is smaller, but the whole banner now appears.  BUT with the added proviso that line 26 needs to be changed to 35%: the width of the text on the left bleeds into the diagram.  

If you agree, one of us should just make this change directly on the master on github.

**Comment by AndrewVSutherland** [comment]
I agree, please go ahead and make the change (I have my hands full at 
the moment).

**Comment by jvoight** [comment]
Done

**Comment by AndrewVSutherland** [comment]
Much better, thank you!

![image](https://cloud.githubusercontent.com/assets/11425002/15093424/7f65bd02-1455-11e6-850c-0da725518430.png)
