### ISSUE TITLE
Classical modular forms crash

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1207]
ModularForm/GL2/Q/holomorphic/49/8/?group=0
(i.e. enter 49 for level and 8 for weight in the search boxes)
crashes with:
AttributeError: 'str' object has no attribute '__call__'
when evaluating
<td align="left">{{ f.coefficient_field.relative_polynomial_latex('x') }}</td>

**Comment by fredstro** [comment]
I can have a look at it on Monday when 8 will be close to a computer again
but if @sehlen has time to look at it before then that would be good.

Fredrik

**Comment by AndrewVSutherland** [comment]
Fixed by merged pull request #1214.  I will leave this open until the code is pushed and the fix is on lmfdb.org.

**Comment by AndrewVSutherland** [comment]
I am removing the critical tag, as the page no longer crashes on www.lmfdb.org,  But I will leave the issue open, as @fredstro indicates that this crash demonstrates an underlying problem in classical modular forms that is not addressed by pull request https://github.com/LMFDB/lmfdb/pull/1214.
