### ISSUE TITLE
Classical modular forms test_non_triv_character fails

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1215]
The function test_non_triv_character in lmfdb/modular_forms/elliptic_modular_forms/test_emf.py fails at line 77.

**Comment by jvoight** [comment]
Is this critical?

**Comment by AndrewVSutherland** [comment]
I doubt it, I just noticed that it failed when I ran the test script and wanted to flag it.  I haven't looked at it closely.

**Comment by JohnCremona** [comment]
All tests in test_emf pass for me (with PR#1222 on board).

**Comment by AndrewVSutherland** [comment]
Great!

**Comment by AndrewVSutherland** [comment]
Closing.
