### ISSUE TITLE
Should we do more caching?

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1216]
See http://exploreflask.readthedocs.io/en/latest/views.html for some hints about caching which I do not think we currently do (after a quick look through our course code -- correct me if I am wrong).
I noted the comment "You can even cache computationally expensive Jinja2 template snippets." which might be worth doing (or something else) for our notorious sidebar.html which is loaded on every page.

**Comment by davidfarmer** [comment]
Things were very slow when a lot of data was being put into the database.

I know that the cloud version can make more resources available when
the load is heavy, but is there some type of bottleneck in the database
which does not scale?  If so, caching should help with that.

**Comment by JohnCremona** [comment]
That's database caching.  I meant caching of routes to web pages.  The link gives as one example 

"Imagine that an article mentioning our application just appeared on CNN and some other news sites. We’re getting thousands of requests per second. Our homepage makes several trips to the database for each request, so all of this attention is slowing things down to a crawl. How can we speed things up quickly, so all of these visitors don’t miss out on our site?"

**Comment by jvoight** [comment]
I think caching would improve the user experience.  I don't think we'll need it for May 10, because we can scale in the cloud, and I also think we have other things to worry about.  Making this 2.0.

**Comment by edgarcosta** [comment]
What @JohnCremona mentioned is cache in the client, which we could do, but don't need to to do it for May 10.

If you want we can enable google's cache network: https://cloud.google.com/cdn/

**Comment by edgarcosta** [comment]
I think we should close this issue. Here are a couple of reasons:

- Caching wasn't needed in our big release 3 years ago.

- We now have 2 different systems setup, one for running www.lmfdb.org and one for development, thus I don't believe the issue that farmer mentioned previously is relevant anymore.
See: https://github.com/edgarcosta/lmfdb-gce/blob/master/setup/images/transition.svg

- Caching can be quite disruptive when testing data changes and new features. And given that we run LMFDB through gunicorn, we will also observe some incosistecies, as we don't always hit the same gunicorn client.

**Comment by AndrewVSutherland** [comment]
Agreed; with the postgres conversion and the switch to katex we have seen a lot of performance improvements, and I don't think caching in flask is desirable; in general any caching that is taking place in gunicorn threads is problematic and can cause very hard to diagnose bugs (we have previously disabled caching implemented in our own code base for precisely this reason).

If there is a concern about performance, it would be better to frame it as a performance issue (e.g. the average time for query X is Y and we would like it to be less than Z).
