### ISSUE TITLE
L(A, 3/2) never computed; hide

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#1220]
On the genus 2 L-function pages
  http://www.lmfdb.org/L/Genus2Curve/Q/169/a/
L(A, 3/2) is apparently never computed, and it displays ugly.  Can we comment out this line?

**Comment by jvoight** [comment]
Unfortunately, I couldn't easily isolate the relevant line in the L-functions code, so this may be too hard (with small gain) for 1.0.

**Comment by JohnCremona** [comment]
I'll look for it.

**Comment by JohnCremona** [comment]
Check out #1221 on the example above (in both analytic and arithmetic views).

**Comment by jvoight** [comment]
Brilliant, thank you!
