### ISSUE TITLE
Source and extent of data for classical modular forms

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#1224]
These knowls should exist, and acknowledgement given to those who computed the data.

**Comment by AndrewVSutherland** [comment]
There is an extent knowl (but it does not match the data, see #873); only a source knowl needs to be added and linked to in the learnmore box.

**Comment by AndrewVSutherland** [comment]
Addressed by #2717, see http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/Source,
