### ISSUE TITLE
For imprimitive genus 2 L-functions, give links to factors

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#1227]
Not critical.

The genus 2 curve
  http://www.lmfdb.org/Genus2Curve/Q/448/a/448/1
has Jacobian (apparently) isogenous over QQ to the product of 2 elliptic curves.  These curves are listed on the page.  For the L-function
  http://www.lmfdb.org/L/Genus2Curve/Q/448/a/
it now factors as the product of 2 L-functions.  It makes sense to list this information as well, and to link as friends to the L-functions of the factors.  

If there are other models (Artin?) where the L-function is imprimitive, we should be sure to follow the same design.

**Comment by davidfarmer** [comment]
We discussed representing non-primitive L-functions differently in the
database.  I know I wanted to do that, but I can't recall if I lost the
argument, or we just haven't done it yet.

Once we figure out how to do Dedekind zeta functions in the database, the
same approach should work for those genus 2 cases.

**Comment by jvoight** [comment]
Sounds great!  I'll add 2.0 to milestone since it sounds like it is something you've already been thinking about.

**Comment by AndrewVSutherland** [comment]
Addressed by #2717.  See the "Origins of Factors" list on the RHS of http://www.lmfdb.org/L/Genus2Curve/Q/448/a/.
