### ISSUE TITLE
field_pretty

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1228]
When I briefly looked at the code for this morning's bug, I noticed that lmfdb/modular_forms/elliptic_m.../*.py import field_pretty from lmfdb.number_fields.number_field but it is actually in lmfdb.WebNumberField.  If it gets called, it presumably failed.

This is unlikely to be critical for Tuesday, but worth fixing up at some point.

**Comment by jvoight** [comment]
Also on a related note (not 1.0), the current way of displaying forms, e.g.
  http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/17/12/1/?group=0
  http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/17/12/1/b/
leaves much to be desired.  We should think of a better way: for HMFs, it seemed better to put the eigenvalues in a table.  

I think there are probably better ways, and here are two possibilities:
(1) Write in terms of a ZZ-basis of the Hecke ring;
(2) For slightly more 'geometry', generate the Hecke ring by a finite subset of a_2, a_3, a_5, ... and write the Hecke eigenvalues as ZZ-linear combinations of these (small) elements.
This is definitely needed for large dimension Hecke spaces; possible for quadratic (or cyclotomic) Hecke fields, the current way is fine.

**Comment by sehlen** [comment]
@jvoight I don't think this is a related to the original issue at all and it is also more a feature request. I completely agree that there are many things that one would like to see, but we should do things in a certain order and also order issues according to their category. Please open a new issue and make it a feature request so that we don't forget about it when we are done fixing bugs.

**Comment by jvoight** [comment]
OK, opening a new issue.  I don't consider this a "feature request" to have a reasonable way of viewing the eigenvalues, but you guys have a lot on your hands right now, and I agree that it is not critical.

**Comment by AndrewVSutherland** [comment]
This appears to be fixed.  I will be opening a new issue related to displaying fields on modular forms pages, but this specific code issue can be closed.

**Comment by sehlen** [comment]
Oh, indeed, I fixed it last week but forgot about the issue. Sorry.

**Comment by sehlen** [comment]
Oh and let me mention that it always worked. I think that's because the file we imported imported the correct one ;-)
