### ISSUE TITLE
Error parsing "complex numbers" for L/Character/Dirichlet/*/*/

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1229]
***1 Upvote*** Here are some tracebacks:

https://gist.github.com/edgarcosta/c9642a9940b40e3681654e4d319fd47f

**Comment by jwbober** [comment]
Where are you getting these error? Those pages, e.g. www.lmfdb.org/L/Character/Dirichlet/37/25/ seem to work fine.

**Comment by davidfarmer** [comment]
and I tried 
/L/Character/Dirichlet/19/16/
and it also worked fine

**Comment by edgarcosta** [comment]
I looking into the access log and it has to do with downloading the Lcalcfile.
```
130.211.0.250 - - [06/May/2016:21:40:34 +0000] "GET /L/Character/Dirichlet/37/25/?download=lcalcfile HTTP/1.1" 500 10010 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
130.211.1.105 - - [07/May/2016:05:14:31 +0000] "GET /L/Character/Dirichlet/37/25/?download=lcalcfile HTTP/1.1" 500 10010 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
```

**Comment by davidfarmer** [comment]
The lcalc file is a way to download the data for that object.

We now have better ways, so we should consider hiding the lcalc links.
(And then maybe re-implementing them once we completely move
to taking the L-function data from the database.)

**Comment by jvoight** [comment]
+1 for hiding Lcalc files
