### ISSUE TITLE
EllipticCurve/Q/modular_form_display/*

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1230]
Here are some tracebacks:

https://gist.github.com/edgarcosta/c00d5da053a8b525f56b5031af4a24ff

**Comment by jvoight** [comment]
This looks confusion between elliptic curves over QQ and elliptic curves over number fields, because it is trying to format "Elliptic Curve isogeny class %s over Number Field %s"

**Comment by JohnCremona** [comment]
I don't know where that URL came from.  The confusion is that the URL /EllipticCurve/Q/modular_form_display/90.b1/ is being not handled by the ec blueprint with prefix EllipticCurve/Q with 2 other parameters, as it should, but as /EllipticCurve with 3 other parameters.  I am trying to fix it.

**Comment by edgarcosta** [comment]
@JohnCremona probably a web crawler
