### ISSUE TITLE
Increase bitprec of complex embeddings for classical modular forms

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#1231]
The complex embeddings are sometimes quite off because they have not been computed with high enough precision. Example: the 9th Fourier coefficient of http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/71/12/1/b/ is shown to embed as
150126.002923965 with the first embedding but when increasing the bitprec, this value becomes 137788.254781014... The precision for calling complex_embeddings ins sage (at computing time) should be adjusted automatically so that it gives a certain minimal number of correct digits.

**Comment by sehlen** [comment]
I changed the way we compute the embeddings now.
I think this is actually something annoying enough that I consider this a bug in sage because when you use .complex_embedding(prec), then I think sage only uses the precision for the roots of the minimal polynomial of the generator of the field. This way you can lose a lot of precision.

I now use refine_embedding to embed the coefficients essentially into Qbar (rather complex lazy field) and then cast them to ComplexField(53), which is not the best practice but works for now.

There is no code change here, but only in the modforms-db (computational code).

As data is being checked and the embeddings recomputed the embeddings get fixed.

Therefore, I think the issue can be closed.

**Comment by AndrewVSutherland** [comment]
Agree to close, if anyone still has concerns/issues about this, please raise them in https://github.com/LMFDB/lmfdb/issues/1248 so that we can check them in our validation.
