### ISSUE TITLE
Not enough coefficients for: ModularForm/GL2/Q/holomorphic

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1233]
Here are the tracebacks:

https://gist.github.com/edgarcosta/a2577791a590def83b5c7968a847d04a

**Comment by sehlen** [comment]
I think this was only a temporary issue. At least there is now no problem on that page and it seems simply that the variable max_cn was not set, probably due to missing data, but it is now.

**Comment by fredstro** [comment]
It is of course related to missing data but we should still make sure that the cn_max variable is always set.
Maybe use 0 as default value?

**Comment by AndrewVSutherland** [comment]
The page in question (http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/23/9/22/a/) now loads correctly.
