### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#1234]
Line 15 of lmfdb/lfunctions/main.py on master has

from lmfdb.utils import to_dict'
(note the single quote at the end)
which prevents me from running the code locally.

How can anyone be running the code at all, since git blame says it has been like that for 11 hours?

**Comment by JohnCremona** [comment]
Who doesn't git blame say last edited that line?

**Comment by jvoight** [comment]
@jwj61 fixed inline, looks like a stray left accidentally by someone.  I tried to further chase it down, but everyone has been all over that file--I don't think it's worth spending any more time on this.
