### ISSUE TITLE
Display of Hecke eigenvalues of classical modular forms

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#1237]
The current way of displaying forms, e.g.
http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/17/12/1/?group=0
http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/17/12/1/b/
leaves much to be desired. We should think of a better way: for HMFs, it seemed better to put the eigenvalues in a table.

I think there are probably better ways, and here are two possibilities:
(1) Write in terms of a ZZ-basis of the Hecke ring;
(2) For slightly more 'geometry', generate the Hecke ring by a finite subset of a_2, a_3, a_5, ... and write the Hecke eigenvalues as ZZ-linear combinations of these (small) elements.
This is definitely needed for large dimension Hecke spaces; possible for quadratic (or cyclotomic) Hecke fields, the current way is fine.

**Comment by arbooker** [comment]
More generally, beyond some point we should stop displaying exact algebraic numbers and show only embedded data. (Probably this means no longer attempting to sort things into Galois orbits also.) Insisting on exact numbers is a severe limitation; we have millions of modular form L-functions computed but no way to access most of them on the site because of this.

**Comment by AndrewVSutherland** [comment]
See related issue #1385

**Comment by AndrewVSutherland** [comment]
Perhaps this should be merged with #654?

**Comment by AndrewVSutherland** [comment]
I think the immediate issue here has been resolved by the series of recent PRs for classical modular forms (we now simply suppress the display of q-expansions that are too unwieldly to fit on the screen in a reasonable way).  Certainly we need to think about how to handle this issue more generally, especially in cases where we might have only numerical approximations for the q-expansions (per remark https://github.com/LMFDB/lmfdb/issues/1237#issuecomment-217815479).  For that it probably makes sense to create a new issue that we might schedule into a future release.
