### ISSUE TITLE
Arithmetic normalization 

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#1238]
Not 1.0.

From Ralf Schmidt:

I do indeed like the way things are presented on http://www.lmfdb.org/L/Genus2Curve/Q/211318/a/ very much. For one, the bad Euler factors are right there and very explicit. On http://www.lmfdb.org/L/ModularForm/GL2/Q/holomorphic/5/10/1/b/0/, on the other hand, how does the user know that a(5)=5^{-1/2} ? The only way is knowing some general facts, or going to http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/5/10/1/b/ and figuring it out from the coefficient of q^5, which is given as 625.

I think allowing arithmetic normalization solves one of the issues (how one goes from 625 to the Dirichlet coefficient).

**Comment by davidfarmer** [comment]
This will be automatic once we take care issue #439

**Comment by davidfarmer** [comment]
Closing because this is really just issue #439
