### ISSUE TITLE
Is /knowledge supposed to be visible?

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#1239]
Pointed out by Ralf Schmidt: there is no apparent way to navigate to 
  http://www.lmfdb.org/knowledge/
Maybe this is by design?  (If so, close this issue.)

**Comment by AndrewVSutherland** [comment]
This is as designed, you only see the knowledge link if you are logged in, see https://github.com/LMFDB/lmfdb/pull/1167.  To find it scroll down (it's after Groups but before Data).

Closing

**Comment by jvoight** [comment]
Sounds good, and thanks!

**Comment by jvoight** [comment]
Reopening because on
  http://www.lmfdb.org/intro/features
under "Knowledge Database" it says "Through the navigation bar you can access the Knowledge Database, which contains all current knowls."  

So presumably we need to hide this sentence?

**Comment by AndrewVSutherland** [comment]
Yes.

**Comment by jvoight** [comment]
OK, done.  Here is the text that I deleted, so it can be recovered if necessary:

Knowledge Database: Through the navigation bar you can access the Knowledge Database, which contains all current knowls.  The knowls may be searched using knowl IDs, desptiptions, keywords, or hashtags.  The knowls may also be browsed by category or alphabetical order.

**Comment by davidfarmer** [comment]
Maybe it would be good to have the Knowledge link visible on beta, even if you are not logged in?

**Comment by JohnCremona** [comment]
OK, we are reinstating visibility of knowledge on beta even when not logged in.  This will be in the sidebar only, not the top-level home page.

**Comment by JohnCremona** [comment]
See #1254
