### ISSUE TITLE
Missing "histories"

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#1240]
http://www.lmfdb.org/Variety
http://www.lmfdb.org/Field
http://www.lmfdb.org/Representation
http://www.lmfdb.org/Group

I don't know whose ambitious idea it was to write histories on these, but maybe we can just hide them for now?

**Comment by jwj61** [comment]
Yes, those learnmore links should be removed.

I know we shouldn't add things to issues, but when doing that, add Sato-Tate groups to the types of groups on the generic group page referenced above.
