### ISSUE TITLE
Wrong link to modular form from elliptic curve L-function page

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1255]
From http://www.lmfdb.org/EllipticCurve/Q/11/a/ the modular form link is correct, to http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/11/2/1/a/ but from its L-function page http://www.lmfdb.org/L/EllipticCurve/Q/11.a/ the link is to http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/11/2/0/a/ which is wrong (0 should be 1) and also there is a redundant (wrong) link to that modular form's L-function.

**Comment by JohnCremona** [comment]
I am fixing this now.

**Comment by davidfarmer** [comment]
Should add a test for this.
