### ISSUE TITLE
Tests for lcalc files

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#1257]
If we are going to have links to Lcalc files, then we need to have tests for them.

**Comment by edgarcosta** [comment]
I think we should serve the Lcalc files with a disclaimer along the lines:
> Many of the properties of the L-functions are pre-computed and require many more Dirichlet coefficients than the ones stored on our database, hence the ones provided in this Lcalc file. 

One could also add a line saying that these are just meant as mock up examples.

**Comment by davidfarmer** [comment]
Closing, because we don't want any links to lcalc: all the L-function values should be served
from the database.

We could open another issue to eliminate lcalc, but that probably is not necessary because
it should be automatic once all the L-function data is precomputed.

**Comment by davidfarmer** [comment]
Reopening because there should be some discussion about whether lcalc files or an alternative
should be available as a way to download that data.

**Comment by edgarcosta** [comment]
I also think these should be viewed in the same category as the code
snippets.

**Comment by edgarcosta** [comment]
Should we add a disclaimer to the header of the files?

**Comment by AndrewVSutherland** [comment]
At the LMFDB editorial meeting in August we agreed to remove the L-calc links, but this won't happen until after the postgres conversion is complete and the new modular forms code with precomputed L-functions is live.   But I'm happy to leave this issue open until the situation is resolved.  There is certainly fine with adding a disclaimer in the mean time if someone wants to do it.

**Comment by edgarcosta** [comment]
Great. That is what I was hoping for.
I will remove them together with the other changes associated to classical
modular forms.

**Comment by AndrewVSutherland** [comment]
With #2717 merged the postgres version is now running on www.lmfdb.org and L-calc links no longer appear.
