### ISSUE TITLE
Labels for Artin representations

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#127]
The Artin representation (definition) knowl should describe the naming scheme for Artin
representations, or better yet, make a new knowl with that information.

That naming scheme should probably have some discussion, since right now it appears
to just be some numerical order.  When the Artin representation is 1 dimensional, the
label of the Artin representation is (currently) not the same as the label of the corresponding Dirichlet character.

**Comment by jwj61** [comment]
working on this

**Comment by jwj61** [comment]
This is done
