### ISSUE TITLE
Add a page/knowl about the Langlands program

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1272]
possibly with a link to it in the introduction and/or universe pages (suggestion from Terry Tao).

**Comment by JohnCremona** [comment]
A sentence was added and merged, but not yet pushed to the servers since there is still no knowl for Langlands Program.  When there is we can push it.

**Comment by AndrewVSutherland** [comment]
Why does this prevent pushing?  A user who is not logged in will not be 
aware that the knowl does not exist.

**Comment by JohnCremona** [comment]
OK I forgot that, so will push it to the servers.

**Comment by JohnCremona** [comment]
See #2429 .  This was done but the link is broken.  Since that issue is open I think this one can be closed.  It is a trivial fix, so I tagged it "good for a beginner" but that just meant that it was not done so I will do it now.
