### ISSUE TITLE
Replace all "a" links for knowls by proper template code

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#1276]
Use {{ KNOWL ...}}  not < a ... >

**Comment by AndrewVSutherland** [comment]
#1645 removes the last remaining occurrence of "<a knowl..." in any LMFDB html file.

I note that the knowl html tag is used in python code that constructs text to be displayed in templaces (e.g. as in nf_display_knowl in WebNumberField and many of the *_stats.py modules), but I don't we can or should change this (jinja2 has no eval equivalent, and even if it did we would not want to use it).
