### ISSUE TITLE
L-function pages -- some missing knowls

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1278]
At  http://www.lmfdb.org/L/EllipticCurve/Q/11.a/ the knowls for Invariants, weight and analytic rank are missing.

**Comment by AndrewVSutherland** [comment]
Normalization should also have a knowl.

**Comment by AndrewVSutherland** [comment]
@davidfarmer I'd be happy to take a stab at this if you will review to make sure I get it right.  It'd be nice to close this critical issue today.

**Comment by davidfarmer** [comment]
If you make a start, I'll take a look.  I was aware that those knowls were missing, but had missed
the fact that they were marked critical.

The "Invariants" heading can be un-knowled, because each of the invariants has a separate knowl.
(Or just leave it, because regular users can't tell that it is an empty knowl.)

**Comment by JohnCremona** [comment]
I marked it as critical before the release but there were even more
critical issues.

**Comment by AndrewVSutherland** [comment]
knowls for all the items originally listed in this issue now exist (but normalization still needs a knowl).  I'm going to remove the critical flag, but I'll leave the issue open until @davidfarmer reviews what I wrote (and David, if you are motivated to write the normalization knowl, go for it!).

**Comment by AndrewVSutherland** [comment]
I added a knowl for normalization as well.  Once @davidfarmer reviews and the knowl collection in the mongo db for  www.lmfdb.org is updated from beta.lmfdb.org we can close.

**Comment by davidfarmer** [comment]
I have reviewed the new L-function knowls and made some updates,
so this can be closed.

**Comment by AndrewVSutherland** [comment]
Great, thanks David.  They won't be visible on www.lmfdb.org until the knowls collection gets updated, but that's a separate issue that I am pursuing with Edgar.

**Comment by edgarcosta** [comment]
done
