### ISSUE TITLE
first zeros list

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#1280]
I want to work on the first zeros list
zeros/first

Currently there is a sqlite database for that page.  I am hoping to use the information
in the new L-functions database.  I was planning to make a new temporary table,
in mongo,
containing just the information that will be displayed in the zeros search, but I would be
happy to hear any suggestions on how to approach this.

**Comment by jwbober** [comment]
I suggest that you try just running queries on the L function collection.
This is why I included the first few zeros as separate floating point
entries.

**Comment by davidfarmer** [comment]
I m going to take the logic for making the table entries out of the javascript and instead
assemble the table with python.  This seems to be necessary because the Lfunctions table
gives the zero and Lhash (and other stuff), and then you have to look in the instances
table to associate the Lhash to a URL.

**Comment by AndrewVSutherland** [comment]
It looks like nothing has happened with this over the past three years, but it is now subsumed by #3117 so I am going to close it.
