### ISSUE TITLE
Modular form history

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1282]
From Brian:

The history of modular forms

http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/history

is NOT linked from http://www.lmfdb.org/ModularForm/

but is

is linked from individual modular forms pages such as

http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/7/4/1/?group=0

**Comment by jwj61** [comment]
Perhaps this is because the current history is of GL_2 forms, whereas  http://www.lmfdb.org/ModularForm/ is meant to have a history which includes other types of modular forms.

**Comment by edgarcosta** [comment]
I don't think we should link it in http://www.lmfdb.org/ModularForm/, but we should keep displaying it in http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/

@AndrewVSutherland, @jwj61 shall we close this?

I will take care of having it in http://cmfs.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/

**Comment by jwj61** [comment]
I was just acting as typist for Brian, but for my money adding to learn-more-about on the page you suggest is a good idea.  I don't see the harm in doing the same to http://www.lmfdb.org/ModularForm, but I am not wedded to the idea.

**Comment by jvoight** [comment]
We should think hard about what part of the history we want to keep; this is probably best folded into the conversation about CMFs knowls, and their revisions.

**Comment by AndrewVSutherland** [comment]
As of #2717, there are no longer any links to the "history of modular forms" page.
