### ISSUE TITLE
Quotation marks 

### ISSUE THREAD

**Issue by brianconrey** [LMFDB/lmfdb#1285]
The latex use of `` and " don't render correctly. For example see
http://www.lmfdb.org/L/history just below the header Riemann's Memoir.

**Comment by davidfarmer** [comment]
The "correct" LaTeX way is to use single quotes on both ends:
``like this.''

It is relatively easy to convert the correct markup.  But if a document
(like a knowl) is edited by several people, then some may do "this"
and others may do ``that'' and yet others will do ``something else."

It is almost impossible to automatically convert a document which
simultaneously contains all three versions.

Would it be adequate to only support the ``officially correct'' way?

**Comment by brianconrey** [comment]
> Would it be adequate to only support the ``officially correct'' way?

Yes.
