### ISSUE TITLE
basic health check endpoint /alive

### ISSUE THREAD

**Issue by haraldschilly** [LMFDB/lmfdb#1289]
implement a basic self-check endpoint `/alive`, which does do a quick self check and a db query to see if the database works. that test should be **very brief**, and will be queried several times per minute.

if all tests pass, report back a text saying "OK" (with code 200) and if anything fails, report back a 500 ... or even worse, it times out if it's completely broken, etc.

that test will be used for uptime check services, like it is provided by stackdriver.

**Comment by edgarcosta** [comment]
Sarunas, in reply to:
> Having the "/alive" would be really great! However, given that the
> clients freak out whenever they lose the connection to the mongodb, I
said:
In my opinion, this could be one of the high-priority tasks in client
development, i.e. not quitting, just because DB is not reachable.

**Comment by AndrewVSutherland** [comment]
@edgarcosta what exactly needs to be done here?  Would it be enough to just tweak the auto reconnect settings in https://github.com/LMFDB/lmfdb/blob/master/lmfdb/base.py? (see lines 72-103).  It currently it retries 10 times with delay of 1s, which seems way too few (and I don't see why we couldn't just have it retry forever, kill it if you want it dead).

Keep in mind that when you and Sarunas use terms like "client development" most of the lmfdb devs have no idea what you are talking about (from their perspective the lmfdb is a server not client :)), and I'm sure you are not saying that you want the lmfdb application code to actually handle mogno db errors wherever they might occur (there is no need to do that, an individual page request can and should be allowed to fail, you don't want to start wrapping try/excepts around everything).

**Comment by AndrewVSutherland** [comment]
http://www.lmfdb.org/alive now checks that the mongo db connection is up and if so it returns the text "LMFDB!" with status 200; otherwise it fails with status 503.  The URL http://www.lmfdb.org/health does the same thing.
