### ISSUE TITLE
Inconsistent knowl versions

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1295]
If you go to lmfdb.org/news and hit refresh repeatedly you will occasionally see an old version of the knowl:

![image](https://cloud.githubusercontent.com/assets/11425002/15184806/aeaa4576-1764-11e6-8320-ff7d34029694.png)

rather than (what should be) the current version:

![image](https://cloud.githubusercontent.com/assets/11425002/15184857/c9ac13ea-1764-11e6-831a-0d6aaa68c540.png)

I expect this has to do with which server is handling the request.

**Comment by edgarcosta** [comment]
@AndrewVSutherland https://groups.google.com/d/msg/lmdb/ya9_dRU4cFo/AYJA6Un-BAAJ
It's because 1/3 of the reads are being done from a daily snapshot.

**Comment by AndrewVSutherland** [comment]
Is there any way to update that daily snapshot (even just for this 
knowl?)

**Comment by edgarcosta** [comment]
Can you edit without it being in beta?

**Comment by edgarcosta** [comment]
Here is a server reading from last night's snapshot: http://www-central.lmfdb.xyz/news

**Comment by edgarcosta** [comment]
I can put a beta running for you.

**Comment by AndrewVSutherland** [comment]
If I try to save the knowl edit on lmfdb.org I get a server error (I think we disabled this intentionally).

**Comment by edgarcosta** [comment]
http://www-central.lmfdb.xyz:8081/

**Comment by AndrewVSutherland** [comment]
I also get a server error there.

**Comment by edgarcosta** [comment]
Could you edit it from your local LMFDB?
You specifically, can ssh tunnel into it, arb.lmfdb.xyz, just like with warwick.

**Comment by edgarcosta** [comment]
ps: the server is running on the default MongoDB port 27017

**Comment by AndrewVSutherland** [comment]
OK, the plan is to update the snapshot that is being used by http://www-central.lmfdb.xyz/, which will fix the immediate problem (at which point I think we can take off the ciritical tag but still need to figure out a regular automated schedule for updating the snapshots going forward).

**Comment by edgarcosta** [comment]
Snapshot ready.
Creating the disk from the snapshot.

**Comment by edgarcosta** [comment]
done

**Comment by AndrewVSutherland** [comment]
Removed critical label since the immediate problem is solved.  Leaving open until we decide how to deal with this on an ongoing basis (we may decide that we don't want to have the knowls in production update in real time, but even if we do, we presumably want all the servers at  lmfdb.org responding with the same version).

**Comment by JohnCremona** [comment]
See the discussion at #1209

**Comment by edgarcosta** [comment]
Using mongorestore it takes no more than 0.1 seconds to replace the knowledge db.

We should have a crontab doing this on a regular basis. 

ps: In comparison, most of our pages take more than a 0.1s to load.

**Comment by edgarcosta** [comment]
I have a script doing exactly what I said above every 15min.

**Comment by AndrewVSutherland** [comment]
Looks like its working, I'll test it a bit (is it every 15min on the quarter hour?)

**Comment by edgarcosta** [comment]
every quarter, same thing with updating the code

**Comment by AndrewVSutherland** [comment]
Great, it just updated again.  Closing.
