### ISSUE TITLE
twice as many zeroes shown for artin reps

### ISSUE THREAD

**Issue by pdehaye** [LMFDB/lmfdb#130]
For http://beta.lmfdb.org/L/Motives/Hypergeometric/Q/A3_B4_t3.-2/ 
zeros above and below the real line show up, while you only need half of those. I know why and need to remember to fix it.

**Comment by JohnCremona** [comment]
Currently the above URL does not work at all (neither does http://beta.lmfdb.org/L/Motives/Q).   Perhaps the labelling has changed -- I cannot make any sense of it!

**Comment by jwj61** [comment]
New url scheme: http://beta.lmfdb.org/L/Motive/Hypergeometric/Q/A3_B4/t-2.1

**Comment by JohnCremona** [comment]
Thanks!  ANd looking at that page suggests tha someone has fixed it, so can we close this?

**Comment by jwj61** [comment]
Yes, looks like it is fixed.
