### ISSUE TITLE
Missing equality sign, elliptic curves

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#1304]
In the "infinite order Mordell Weil generator and height" of an elliptic curve, equality signs are used everywhere to separate columns but not in this section.  I vote for an equal sign (or approx sign).

**Comment by JohnCremona** [comment]
Fair enough.  There's no equality sign (even approx) since it's a table, not a list of equations (see a renka >1 example).  But I could put in a second column with "=" in the first row and the "approx" symbol in the second.  OK?

**Comment by JohnCremona** [comment]
See #1305

**Comment by AndrewVSutherland** [comment]
Now fixed on prod and beta, closing.
