### ISSUE TITLE
Can't add new accounts

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#1307]
We can't assign new accounts (for editing knowls) because that has to be done on beta, not www.

I think this just involves changing line 28 of lmfdb/users/main.py
from
base_url = "http://www.l-functions.org"
to
base_url = "http://beta.lmfdb.org"

But I didn't want to do that in case it has a bad side-effect.

**Comment by JohnCremona** [comment]
I will make that change and push to beta -- the change cannot be tested locally since clicking on RegisterTokens fails there.

**Comment by JohnCremona** [comment]
I changed the URL in PR #1309, merged and pushed to beta, and tested successfully.
(Anyway, all you had to do was edit the URL which the register tokens command gave you!)
