### ISSUE TITLE
CM set to "only" when browsing Elliptic curves over Q

### ISSUE THREAD

**Issue by lemurell** [LMFDB/lmfdb#1311]
When clicking any of the conductor ranges, torsion or rank numbers under Browse elliptic curves on http://lmfdb.org/EllipticCurve/Q/ the search value for CM on the resulting search page is set to "only". It seems better to have it set to "include". (At least I got confused first after clicking on torsion=16, changing that to 12 and getting zero results.)

**Comment by AndrewVSutherland** [comment]
I expect the same things happening here as with https://github.com/LMFDB/lmfdb/issues/1250 (for elliptic curves over number fields).  I will take a look now.

**Comment by AndrewVSutherland** [comment]
Fixed by pull request https://github.com/LMFDB/lmfdb/pull/1312.  Will close as soon as it has been merged to master/prod/beta.
