### ISSUE TITLE
eta quotient formatting issue

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1331]
From the bug report spreaadsheet:

  In the description of the eta quotient,
  the first term of the product would be
  1-q^{4n} instead of 1-q^{4}n.

Looks like a simple latex formatting issue.

**Comment by AndrewVSutherland** [comment]
Any idea which page this is on?  Does the bug report spreadsheet say?

**Comment by JohnCremona** [comment]
On 13 May 2016 at 14:54, AndrewVSutherland <notifications@github.com> wrote:

> Any idea which page this is on? Does the bug report spreadsheet say?
>

It doesn't say and I have not yet looked.

**Comment by AndrewVSutherland** [comment]
Found it!  It was in the knowl www.lmfdb.org/knowledge/show/mf.48.2.1.a.formulas, now fixed (along with a bunch of other typos I found while searching for it).
