### ISSUE TITLE
Change ideal labels (for conductors and levels) for imaginary quadratic fields

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1333]
At present imaginary quadratic fields have a different way of labelling their ideals, which form part of the labels for elliptic curves, isogeny classes, and (in future) Bianchi modular forms.  See
http://beta.lmfdb.org/knowledge/show/ec.conductor_label

These labels have the form [N,c,d] where N, c, d are positive integers;  and the brackets and commas make for terrible URLS (try http://beta.lmfdb.org/EllipticCurve/2.0.7.1/%5B44%2C8%2C2%5D/a/3)

I want to change [N,c,d] to N.c.d so that the previous URL would become

http://beta.lmfdb.org/EllipticCurve/2.0.7.1/44.8.2/a/3

This is still different from the ideal labels for totally real fields where that ideal 44.8.2 would be 44.i with i an (arbitrary) index , but not so bad.

I want to do this before adding Bianchi modular forms to the LMFDB.  Right now nothing links to or from these Bianchi elliptic curve labels.  I'll just need to update various scripts (including external ones).  I assume there will be no objections!

**Comment by AndrewVSutherland** [comment]
Definitely no objections, this is a good idea.

**Comment by AndrewVSutherland** [comment]
Once this is done we can easily address #1147.

**Comment by JohnCremona** [comment]
This was done ages ago.  Ideal labels used for conductors over IQFs do now all have the form N.c.d where N is the norm.  So I think this can be closed.
