### ISSUE TITLE
Knowl for Satake parameters

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#1337]
The phrase "Satake parameters" on a classical modular form page, e.g., 

http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/8/8/1/a/

should be a knowl.

**Comment by AndrewVSutherland** [comment]
@kedlaya it is a knowl, it just has no content, see:

http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/8/8/1/a/

**Comment by AndrewVSutherland** [comment]
I added some content to the knowl (which can no doubt be improved).
