### ISSUE TITLE
Slashes instead of dots in URL

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#1339]
For example
/ModularForm/GL2/ModL/11.2.9.8.1.1
should be something like
/ModularForm/GL2/ModL/11/2/9/8/1/1

**Comment by AndrewVSutherland** [comment]
Given that mod-ell modular forms is not in beta status yet (it still needs a lot of work), and I don't think it is useful to track issues for it here (but they could certainly be tracked in a development fork).  This is certainly not the only issue that needs to be addressed before mod-ell modular forms is ready for beta, and there will be a comprehensive review of mod-ell modular forms when that time comes.
