### ISSUE TITLE
Learn more about lattices

### ISSUE THREAD

**Issue by brianconrey** [LMFDB/lmfdb#1342]
On the page http://www.lmfdb.org/Lattice/
it would be nice to include a "History of Lattices"
or some at least some explanation of the role of
lattices in the grand scheme of things. Maybe 
how they relate to modular forms and to number fields
and and perhaps some simple examples that 
illustrate these connections.

**Comment by davidfarmer** [comment]
Anna Haensch would be the right person to do this, and also issue #1343

**Comment by annahaensch** [comment]
I just saw this issue, and I am working on that today. I'll comment again when it's done.

**Comment by annahaensch** [comment]
I've built up a knowl called lattice.history giving a brief history and highlighting some of the specific connections between lattices and LMFDB objects as well as some relevant lattice topics of interest.  I'll continue to work on it.  But there is something there now. @sanni85 will add a link to the knowl on the lattice homepage.

**Comment by sanni85** [comment]
Now that the pull request #1485 is merged this issue can be closed after the lattice database is updated on the cloud: the record for the Leech lattice has been changed and the link to it  in lattice.history is broken on the main website.

**Comment by AndrewVSutherland** [comment]
I updated the database and the link now works, closing.
