### ISSUE TITLE
Integral lattice and Gram matrix knowls

### ISSUE THREAD

**Issue by brianconrey** [LMFDB/lmfdb#1343]
I feel like the knowls for "Integral lattice" and "Gram matrix" could use a little amplification.
Suppose I think of lattices as collections of classical lattice points in
R^n. It's not clear to me from the knowls what the bilinear form is.
If it is supposed to be defined in terms of the Gram matrix then
the Gram matrix should be defined without referring to the bilinear
form; otherwise the definition is circular.  Perhaps the Gram matrix could be defined in terms of the inner products of the elements of a basis; then the bilinear form in terms of the Gram matrix.

**Comment by annahaensch** [comment]
I just saw this, and I'm working on it today.

**Comment by annahaensch** [comment]
I edited the knowls for integral lattice and Gram matrix in the beta version.  Please tell me if this sufficiently addresses your concerns.

**Comment by sanni85** [comment]
Also this issue can be closed now.

**Comment by AndrewVSutherland** [comment]
Agreed.
