### ISSUE TITLE
Headers in homepages are now black

### ISSUE THREAD

**Issue by alinabucur** [LMFDB/lmfdb#1345]
**_1 Upvote**_ The headers for the various sections of the homepages of the various objects are now black (unless they are knowls). 

See for instance the word 'structure' in "Mordel Weil Structure" heading on 

http://beta.lmfdb.org/EllipticCurve/Q/81150/m/1

**Comment by JohnCremona** [comment]
Alina, see the discussion at #1306.  This is not a bug, it fixed a bug!

**Comment by JohnCremona** [comment]
Sorry I did not read carefully enough.  I see what you mean.  The knowl part of the title is green and the rest is black and that looks bad.

**Comment by AndrewVSutherland** [comment]
+1 This is not very pretty.  The easiest fix would be to put the whole heading in the knowl title.

**Comment by davidfarmer** [comment]
We can't change every header on every page into a knowl.  I will look into fixing the CSS.

**Comment by AndrewVSutherland** [comment]
@davidfarmer you are right, I was only thinking of the example in this issue (where I would argue that the knowl title really should be "Mordell-Weil structure").

**Comment by JohnCremona** [comment]
I found a typo in style.css for h3 headers ("conent" should be "content") but the offending one here is an h2 which has color:{{color.content_text}}; so that is not it.
If we really want headers to be green since many of the words are knowls then I suppose that should be color.knowl_title_text, and the same for headers h1, h2 and h3.  That's a lot of green!

**Comment by davidlowryduda** [comment]
I notice that this problem has been fixed (I think by #1321 and/or #2127).

So I believe this can be closed.

**Comment by JohnCremona** [comment]
I agree -- the original witness page at http://beta.lmfdb.org/EllipticCurve/Q/81150/m/1 is fine.
