### ISSUE TITLE
colored dots on degree 3 maass forms

### ISSUE THREAD

**Issue by brianconrey** [LMFDB/lmfdb#1352]
http://www.lmfdb.org/L/degree3/MaassForm/

The description of the second plot (level 4) should tell what the colors of the dots mean.

**Comment by AndrewVSutherland** [comment]
@brianconrey it would be helpful if you added a label (or labels) when you create a new issue.

**Comment by davidfarmer** [comment]
Most people cannot add labels. This is a good thing because bad
labels are worse than no labels.  Adding labels is yet another duty of
the people who manage the pull requests.

**Comment by AndrewVSutherland** [comment]
Got it, thanks!

**Comment by AndrewVSutherland** [comment]
I believe the color indicates the sign (blue=1, red=e^{2pi/3}, green=e^{4pi/3}) of the functional equation.

**Comment by AndrewVSutherland** [comment]
The place to fix this is in getOneGraphHtml in lines 143-159 of lmfdb/lfunctions/LfunctionPlot.py

**Comment by AndrewVSutherland** [comment]
This is addressed by PR #1529
