### ISSUE TITLE
Download buttons for elliptic curve search results shouldn't appear when there are too many results

### ISSUE THREAD

**Issue by jwbober** [LMFDB/lmfdb#1361]
e.g., if I go to http://www.lmfdb.org/EllipticCurve/Q/?conductor=100000-379998

and then a download all search results button at the bottom, the server thinks for a long time and then returns an error.

(Actually, it would be nice to find a way to make these links actually work, but that might be asking too much right now.)

**Comment by JohnCremona** [comment]
I thought we had sorted that one but perhaps it was another similar place.
Mass download should definitely be possible.

**Comment by JohnCremona** [comment]
Number fields only offer downloads if there are <= 100,000 results.  Your example (run locally) produces a 50mb file.  Even if the server could produce the file to download quickly the download time could be too great (depending on the users's connection).
I will put in a limit of 100,000 and see how that looks.

**Comment by JohnCremona** [comment]
#1452 fixes this and has been merged to master, not yet to beta/prod.

**Comment by AndrewVSutherland** [comment]
Now fixed on beta/prod.
