### ISSUE TITLE
knowledge.system.{profile, users}

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1373]
Hello,

Should/can we drop these collections?

knowledge.system.profile is empty
and 
knowledge.system.users is an old artifact from mongodb 2.4, I believe:
{ "_id" : ObjectId("4e610f61b1599919e80c5b3d"), "pwd" : "...", "user" : "lmfdb", "readonly" : true }
{ "_id" : ObjectId("4e610f70b1599919e80c5b3e"), "pwd" : "...", "user" : "lmfdb_editor" }
{ "_id" : ObjectId("4e611046b1599919e80c5b3f"), "pwd" : "...", "user" : "lmfdb_website" }

Best,
Edgar

**Comment by JohnCremona** [comment]
No idea.  @haraldschilly , @jwbober ?

**Comment by haraldschilly** [comment]
I don't really know. This could be the storage for the account data for just the knowl and user database. Or are these credentials stored somewhere else now?

**Comment by jwbober** [comment]
Yes, the system.users collection does look old.

The system.profile collection seems to have something to do with mongodb
profiling. I've never used that, but perhaps someone else has.

**Comment by JohnCremona** [comment]
We could try dropping them and restarting mongo;  if something stopped working, restore them.  That would mean being certain that we could restore them. Perhaps just renaming them might be safer.

**Comment by edgarcosta** [comment]
systems.users is no longer used by mongodb
and system.profile is an empty collection... 

One of the spare servers, that Drew and I have been using to run some tests, already doesn't have those two collections.
```
> use knowledge
switched to db knowledge
> show collections
deleted_knowls
history
knowls
meta
system.indexes
```
this server: www-central3.lmfdb.xyz is reading from that spare mongodb server, and I didn't notice anything weird with the knowls (apart from being outdated)

**Comment by edgarcosta** [comment]
Closing and moving it to #1431
