### ISSUE TITLE
Wording on zerostour

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1378]
From the feedback page referring to http://www.lmfdb.org/intro/zetatour

The sentence "This has been verified for every zero ever found." makes little sense, unless you mean that you checked, once you had the zero that indeed Re(z) = 1/2. I'd phrase this as "This is true, so far, for every zero ever found.", but that (and the current version) still raises the question how hard people have been looking for zeroes with a real part unequal to 1/2. Elsewhere you talk about "the first trillion zeroes", but what does that mean "first"? Seems to imply that they only looked for zeroes of the form 1/2 + it, because otherwise you can't trivally speak of "the first". 

Please reply directly to carlo@alinoe.com

**Comment by AndrewVSutherland** [comment]
Fixing this just involves making appropriate edits to the knowl at http://beta.lmfdb.org/intro/zetatour.  Updates made their will automatically appear on www.lmfdb.org on the next quarter hour (+epsilon)

**Comment by davidfarmer** [comment]
I am editing the file and will write to that person.

**Comment by davidfarmer** [comment]
Made changes which now appear on prod, and emailed person.  Closing.
