### ISSUE TITLE
Display partial information on classical modular form pages

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1385]
_Edited per the discussion below_

In cases where the coefficients of the Q-expansion are too large to reasonably display, as on

http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/23/38/1/ http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/23/38/1/a

for example, don't display the q-expansion but just give information about the coefficient field (a link to the field if it is in the LMFDB, and if not, at least its degree and perhaps a defining polynomial for it).

 We can instead provide a link for downloading whatever coefficient data we have available for those who want it.

For cases where we only know the dimensions of the Hecke orbits that make up the decomposition of the space and perhaps some other partial information (e.g. the coefficient field or its degree), we could display this and note that the coefficients are not yet available.  This would be friendlier then a long list of "Hecke orbit space not in database" entries (we currently hide these space to avoid displaying them).

I am marking this as critical because, as it stands, many of the current pages (not just the two examples above) cannot be reasonably rendered and take very long to load.  This is something we could easily fix even before filling out and verifying all the modular form data we would like to have available (see the discussion at https://github.com/LMFDB/lmfdb/issues/1248).

This more flexible approach would also allows us to have modular forms pages in cases where we have only numerical data but still want to include the L-function in the LMFDB (as noted in https://github.com/LMFDB/lmfdb/issues/1237#issuecomment-217815479).

**Comment by sehlen** [comment]
It does not make sense to restrict to a_2 as this might vanish. Moreover,
it might not be of the form alpha where Q(alpha) is the coefficient field
in the data that we computed. We have to distinguish several cases and I
would rather vote for hiding the q-expansion by default in those cases.

**Comment by sehlen** [comment]
But there is another issue with this, namely that pages take long to load
(before they get the chance to render) because the record is large. Please
assign me and I can offer a fix for both issues today or tomorrow for
people to test.

**Comment by AndrewVSutherland** [comment]
@sehlen (https://github.com/LMFDB/lmfdb/issues/1385#issuecomment-219710846) Good point, and I think you are right that we don't want to complicate things.  So for the moment we could just have two cases

- Display everything as we do now (coefficients and information about the coefficient field)
- Display no coefficients (with a download button if they are available) and give information about the coefficient field (dimension and a link to its LMFDB page if there is one or a defining polynomial if not)

Does that sound reasonable? (If so I can amend the issue description)

**Comment by sehlen** [comment]
@AndrewVSutherland  Absolutely, that's exactly what I wanted to (will) do.

**Comment by sehlen** [comment]
See my proposal at https://github.com/LMFDB/lmfdb/issues/1386#issuecomment-220137693 and my branch https://github.com/sehlen/lmfdb/tree/cleanup_bugfix_efficiency for testing this.

**Comment by sehlen** [comment]
Updated, see my pull request https://github.com/LMFDB/lmfdb/pull/1409
