### ISSUE TITLE
Slow elliptic curve search pages due to missing indexes or queries that do not take full advantage of them

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1388]
There are a number of searches on the top level elliptic curves pages that are much slower than the should be, for example if you go to http://www.lmfdb.org/EllipticCurve/Q/ and just click "search" it takes 5-10 seconds; the reason is that there is not an index setup for the sort order used on the display page (FWIW, this exact use case shows up frequently in the google analytics).

Many other basic searches (e.g. rank, or conductor range) could easily be sped up by adding a few indexes (in one or two cases a few tweaks to the query would also help).  Edgar Costa and I are currently investigating.

**Comment by AndrewVSutherland** [comment]
Most of the queries on http://www.lmfdb.org/EllipticCurve/Q/ are sped up substantially by adding an index that caters for the sort used to produced the results page (('conductor', ASCENDING), ('iso_nlabel', ASCENDING), ('lmfdb_number', ASCENDING)).  This speeds up an empty search by a factor of about 30 (and any search with a large list of results is similarly sped up), compare

12.3s http://beta.lmfdb.org/EllipticCurve/Q/?count=100
 6.1s http://www.lmfdb.org/EllipticCurve/Q/?count=100
 0.2s http://www-central3.lmfdb.xyz/EllipticCurve/Q/?count=100

Adding an index on rank speeds up the rank searches, and pull request https://github.com/LMFDB/lmfdb/pull/1389 speeds up searches on torsion structure (and fixes a bug so that you can now search for trivial torsion, not just on the elliptic curve pages, but also on the genus 2 page).

We will try to get these index updates made on www.lmfdb.org and beta.lmfdb.org in an orderly manner (they only take a few minutes, but may block access to the database during this time).

**Comment by JohnCremona** [comment]
Merged to master and about to merge into beta and prod.
Must look at analagous issues for ecnf and genus2 (both making sure that torsion_order is there when torsion_structure is, and that these indices are in).

**Comment by AndrewVSutherland** [comment]
I checked and there isn't much of a performance issue in either case, but no reason not to make the same change, which I will do.

The moral here is to never use an array for a field you want to search on.  Which is silly, because it would be really easy for mongo db to support an efficient index on arrays that just treats them as strings (might not do what you want as far as ordering, but would still be useful).

**Comment by JohnCremona** [comment]
The torsion_structure field is itself stored as a list of strings so that should be changed to a single string.  I can add that to the script I am developing which is already changing ainvs from a list of strings to a single string (with code adjusted so it works ok with both versions).

**Comment by AndrewVSutherland** [comment]
@JohnCremona Good.  I will do the same for genus2 curves.  The irony here is that I original *did* store them as a single string and changed this when David Farmer asked me to do the same for the list of Euler factors (but of course this issue is only relevant when you want to index the entire array as a unit; if we every do want to search on Euler factors at small primes we will want make them separate attributes (or a single string with a regex search, but that will probably be a lot slower).

I just submitted a pull request for the analogous change to ecnf and genus2_curves.

**Comment by AndrewVSutherland** [comment]
The mongo commands

db.curves.createIndex({'conductor':1,'iso_nlabel':1,'lmfdb_number':1})
db.nfcurves.createIndex({'field_label':1,'conductor_norm':1,'conductor_label':1,'iso_nlabel':1,'number':1})

were just executed on atkin.warwick.ac.uk.  The time to display the first 100 of a large set of search results dropped from 5-10s to under 250ms.  Edgar will apply the same updates to www.lmfdb.org later.

**Comment by JohnCremona** [comment]
Excellent.  When I added the iso_nlabel fields to enable sorting (since the letter-based codes give the wrong ordering when sorted lexicographically) I did not make a new index to match.  That was my fault and would have resulted in this slow-down.  Using git blame I see that I did this on Oct 23, 2015.

**Comment by AndrewVSutherland** [comment]
Fixed by PR #1389, closing.
