### ISSUE TITLE
deprecated import in Hilbert modular forms breaks in sage 7.2

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#1393]
the file lmfdb/lmfdb/hilbert_modular_forms/hilbert_modular_form.py has this import:
```
from sage.misc.preparser import preparse
```
This has been deprecated for a while and now in sage 7.2 this file has finally been removed (I am getting annoyed by this, they are so aggressive, but this shows that we should really react fast if we see a deprecation warning).

I didn't change it because I don't know which sage versions people are using and don't want to break anything but I think it should be changed to 
```
  from sage.repl import preparse 
```

**Comment by AndrewVSutherland** [comment]
Already noted in #1332, closing as duplicate (not your fault @sehlen, there are so many open issues it's easy to duplicate).

**Comment by sehlen** [comment]
ooops, sorry, didn't search for the right thing ;-)

**Comment by JohnCremona** [comment]
I'm making a comment on #1332
