### ISSUE TITLE
Documenting and  maintaining index information

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1403]
As we have seen (see issues #1247 and #1388, for example), the presence or absence of indexes can have a huge impact on the performance of the lmfdb, and we have recently added several new indexes that have substantially improved page response times.  It has also become clear that there are indexes currently in place that are out of date and no longer needed, or indexes that we will want to change once we implement some identified changes in how we should store data (e.g. issues with indexing arrayed fields).

We have also seen (e.g. on release day) that the creation of indexes needs to be carefully managed in order to avoid impacting the website,  and we have identified the need to rebuild indexes (at least when there are significant data changes), see issue #1294.

Having all the creation of indexes managed in load scripts is not an ideal approach because (1) not all the load scripts are necessarily in github under LMFDB/lmfdb, and (2) the list of indexes we want may change based on performance monitoring and query optimizations that have nothing to do with the load script, so this is not a great place to maintain them.  **We also do not want to use ensure_index in any lmfdb application code** (see discussion in #1209).

I am about to open an issue in LMFDB/lmfdb-inventory asking everyone to document the indexes they are using in the appropriate .md file, see https://github.com/LMFDB/lmfdb-inventory/blob/master/db-sato_tate_groups.md for an example of what I have in mind.

In addition to documenting the indexes we need/want, we also need a mechanism in place for ensuring that the documented indexes are in place, and for eliminating unnecessary indexes (which, at a minimum take up space, but can also confuse mongo db's query optimizer).

For new additions to the LMFDB, part of the review process should include ensuring that the index inventory is up to date and includes appropriate indexes for optimizing queries (and sort order).

**Comment by JohnCremona** [comment]
People may need to be told how to find out what indices tere are (and how to interpret the output).  It's not enough to look for indexing function in the visible scripts since many will have been done in interactice sessions.
A script I was running to go through ell elliptic curve (/Q) entries and add some fields was so slow earlier today that the db kept on timing out (something about replication ) but now it is going really fast.  This only refeerences the curves collection in elliptic_curves but something has happened!  (Maybe all the re-indexing in other places has now finished...)

**Comment by AndrewVSutherland** [comment]
@JohnCremona Good point.  In pymongo one can use the .index_information() method to get a list of all the indexes currently defined on the collection.  For example if conn is the connection returned by MongoClient you could type

conn.sato_tate_groups.st_groups.index_information()

to see the list of indexes that are now documented in https://github.com/LMFDB/lmfdb-inventory/blob/master/db-sato_tate_groups.md (I still need to do this for the other two collections in sato_tate_groups).  For each collection listed in the inventory of a database there should also be a list of its associated indexes (along with an explanation as to why they are there -- I suspect that in the process of writing this people may find indexes that are not needed (e.g. refer to attribute names that are no longer used), and possibly also identify some missing ones).

A good way to figure out which indexes *should* be there is to search the code for uses of the ".find", ".find_one" and ".sort" methods and in each case think about which index mongo db can use to optimize this operation.

**Comment by AndrewVSutherland** [comment]
I am going to close this issue, as the databases that are still missing index information are identified by per database issues in LMFDB/inventory.
