### ISSUE TITLE
Make very large data files available for download

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#1404]
We have the possibility to download Fourier expansions etc for modular forms but when the download gets too large, I've seen the server time out, probably getting the file from the gridfs file system.
I haven't debugged this carefully and don't have an example at hand right now as I'm working on a lot of stuff at the same time but I wanted to start a discussion how to deal with such data in general.

One idea I had was to store these download files in Google Cloud storage where the users could download them from. I know that this adds an additional "database" but the way this should work is that there are scripts that generate and update the files in GCS (using gsutil) and store the link to the file in the mongodb. I think if we want to allow for very large data downloads, this is the only way to go. Any other ideas?

@jvoight @edgarcosta Would your grant allow for having storage buckets?
They would also be cheaper than disk storage and could be DRA storage as the data will not be accessed very frequently.

**Comment by AndrewVSutherland** [comment]
Provided the cost is reasonable, I like this idea.  It could also greatly reduce the amount of storage needed for the mongo db.  Another plus is that if someone wants to do computations with the data in GCE, access to GCS is very fast (much better than pulling it down to your own machine and then pushing it back up to the Google cloud).

**Comment by edgarcosta** [comment]
What sizes are we talking about? Total and each file size.


The riemann zeta zeros and the class groups of quadratic imaginary fields
are already on standard buckets, 3.3 TB.

I'm unhappy with this solution, specially with respect with class groups of
quadratic imaginary field.
For example, according to google analytics, since the link exists, March
2015, 82 people visited:
http://lmfdb.org/NumberField/QuadraticImaginaryClassGroups
and 3 clicked download.
Is the link hidden? Yes.
Should I move these to nearline storage? Perhaps, at the moment I'm not
confident it justifies the expected cost of $350 per click.

The zeta zeros perform a much better, as out of the ~4.3k hits over the
same time period, 25% of hits were produced by search queries.

ps: I'm aware that google analytics data is not accurate, but gives us a
very good picture.

**Comment by sehlen** [comment]
@edgarcosta I don't know yet. It depends on how far we want to and can push our computations.
But here is an example:
We always compute the modular forms up to the precision that is needed for the L-functions (someone thought about this at some point, not me). Anyway, for the form 92.10.91.c that I just computed, we need 500 coefficients and the total record including all algebraic Fourier coefficients and all embeddings for those coefficients is currently about 1.2GB large. I'm sure we can decrease the file size a bit and have files for the different embeddings etc but the data has to be stored. Right now, we have such data already in mongo but that doesn't make any sense as this record will probably never load in time, even for a download (right?).

But regarding the cost: I think GCS costs less, right? My idea was more to move data **out** of mongo into GCS to make it available and to reduce costs and when we add more data, right away add the large records only to GCS.

But what I would be worried about is that we have to make sure, we keep copies and have a good backup strategy as well as your grant does probably not run forever ;-)

**Comment by edgarcosta** [comment]
Yes, GCS is far less. 0.04  vs {0.026, 0.02, 0.01}

**Comment by jwj61** [comment]
In regard to class group data, it is good to have a backup somewhere, but why not have the download links point to warwick?  I know it is a change in the code for the cloud version, but overall sounds like it would be preferable.

**Comment by sehlen** [comment]
> On May 18, 2016, at 21:33, John Jones <notifications@github.com> wrote:
> 
> In regard to class group data, it is good to have a backup somewhere, but why not have the download links point to warwick? I know it is a change in the code for the cloud version, but overall sounds like it would be preferable.
> 
Speed, for instance. If you’re away from the UK, this can also be slow.
And it won’t be unavailable (although I agree it is not a critical service).

**Comment by JohnCremona** [comment]
Someone with more expertise than me might know how to code a link which results in going to whichever of two urls is fastest.

**Comment by haraldschilly** [comment]
@JohnCremona I just saw this message. what do you consider as "fastest"? For downloading data? In a website, you operate on the layer 7 of the OSI model. You have to be on layer 3/4 to make that decision. So what you have to code is a global load balancer with geographic affinity.

A comment is talking about GCS. That's a global CDN which has this and hence it does it for you. You just have to point the link to the correct storage bucket and path.

**Comment by JohnCremona** [comment]
I think Harald has just proved himself to be "someone with more expertise than me" (not that proof was needed) since I understood only about 10% of his commet!

**Comment by haraldschilly** [comment]
@JohnCremona yes, I figured after pressing comment, this doesn't help you. what I mean is, that just via writing "high level" code in html, you have no proper control. you have to go deeper to do this how it should be done. these are levels 7 (the website application and html/js) vs. levels 3 and 4 (TCP/IP, the backbone of the internet itself)

**Comment by jwj61** [comment]
Back to the comment on class group data, I would hardwire the links to warwick.  These are giant files, and will be downloaded relatively infrequently.  So, I wouldn't worry about the download speed across the Atlantic.

**Comment by edgarcosta** [comment]
@jwj61 regarding the class group data. We can either do that, or just move them to cheaper storage. 
As I agree with you, having backups is a good thing.
The user cost of the cheap storage,is that the user might need to wait 3 seconds before starting to download the file, which I think it is totally okay.

**Comment by jwj61** [comment]
Is the storage cheaper than warwick?  I believe it is backed up in Bristol as well.

**Comment by JohnCremona** [comment]
I also have a separate copy of both class_numbers and zeros on a different machine at Warwick, so if we do ever need to use a backup that one would be closest.

lmfdb@hecke:~/data$ du -sh *
2.1T	class_numbers
1.9T	db
32G	lfunction_plots
4.0K	LICENSE.md
5.8G	riemann
827M	Siegel-Modular-Forms
33G	weight_three_halves
1.3T	zeros
4.0K	zeros2

**Comment by koppi** [comment]
I can highly recommend http://dat-data.com/ for a peer-to-peer data distribution and replication.

**Comment by AndrewVSutherland** [comment]
Related post from lmfdb-support:

> I tried writing a python script to download them in successive blocks using
URLs of the form
http://www.lmfdb.org/zeros/zeta/?limit=1000&N=2001

> This worked for limit as large as 100,000.
> I tried limit=1000000 (the largest I contemplated using, resulting in 1000
> downloaded blocks), but I got this error message from your server:
> 
> hello downloader. you hurt the server :(
>                   get the data here: http://www.lmfdb.org/data/zeros/zeta/
> --
>                   code how to read it is here:
> http://code.google.com/p/lmfdb/source/browse/#hg%2Fzeros%2Fzeta
> 
> I tried to browse the first URL, but the page apparently does not exist.
> 
> Can you advise me how to download the zeros in fairly large blocks (would
> blocks of 100000 be okay?) without hurting the server?
> 
> Thank you so much

We *really* do not want people trying to download a billion zeros via the api interface.

**Comment by edgarcosta** [comment]
Perhaps we should point them to: http://lmfdb.warwick.ac.uk/data/zeros/

**Comment by jwj61** [comment]
Is the file format of .../data/zeros documented somewhere?

**Comment by edgarcosta** [comment]
For http://lmfdb.warwick.ac.uk/data/zeros/zeta/ we have http://lmfdb.warwick.ac.uk/data/zeros/zeta/README.dvi (and the code)

**Comment by JohnCremona** [comment]
There is also now a README.pdf after some user reasonably requested it.

**Comment by edgarcosta** [comment]
I removed the label classical mf as we now allow to download all the data for each newform.
