### ISSUE TITLE
Fix name of space for classical modular forms

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#1405]
Go to http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/7/9/3/
and observe that the character is not mentioned in the name S^new_9(7) ;-)
This is due to some errors in the template and I'm fixing it right now.

**Comment by AndrewVSutherland** [comment]
Fixed by pull request #1409 which is now live on www.lmfdb.org
