### ISSUE TITLE
Plots of modular forms

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#1408]
Once we cleared up the remaining data issues, every modular form should get a Lady Gaga picture.
You can assign me but if anyone has a lot of experience in plotting complex_valued functions and knows tricks, I would be happy to have help. 

We also have to decide then if we want to only show such a plot on the (to be created, see https://github.com/LMFDB/lmfdb/issues/659) page for a modular form with Fourier coefficients embedded into C or/and choose one of them to be the representative of all of them.

**Comment by sehlen** [comment]
What kind of plots would people like? I'm currently still digging into some rather serious sage bugs but when I can finally say that the lower level recomputation works really reliably and we start computing a large range, we could as well compute the plots at the same time. We compute the embeddings of the Fourier coefficients, so we can directly (although sage takes quite some time to produce them but that's not a big problem, I guess) get plots like the three attached ones (delta and 11.10.3.a) from the database. I personally have the impression that complex_plot in the disc model of the hyperbolic plane works best for cusp forms because of the rapid decay. (A bit off-topic but note that I just added a method `value()` to the WebNewForm class which uses the embedding of your choice to compute a complex value at a point. This can be used to produce the plots and we could in fact also give the user the possibility to evaluate a modular form at a point of their choice. We only have to give some error estimates, which should be easy to obtain from the Deligne bounds.)

![delta](https://cloud.githubusercontent.com/assets/2471633/15767033/bf4aaa00-2912-11e6-88ee-ce6e4921e38c.png)
![delta](https://cloud.githubusercontent.com/assets/2471633/15767078/2799fe8a-2913-11e6-8fae-11e78887b781.png)
![11-10-3-a](https://cloud.githubusercontent.com/assets/2471633/15767316/1125e3d8-2915-11e6-8e1a-6188c00b9205.png)

**Comment by AndrewVSutherland** [comment]
Addressed by #2717.  All newform home pages now have a plot in the property box, and the same is true for newspaces where we have computed the trace form (all newspaces of level up to 4000 or where we have newforms).  In both cases the trace form is used to create the plot.
