### ISSUE TITLE
add to HMF search  include/exclude base-change and CM options

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1410]
From sage-support (David Loeffler):
- Could an option be added to the search form at http://beta.lmfdb.org/ModularForm/GL2/TotallyReal/ allowing one to search for examples which are, or are not, base change or CM?

Since both base-change and CM are attributes stored in the
database it will be easy to addthese as options on the search page as
we do for elliptic curves over number fields (with 3 options:
"include", "exclude", "ony" with "include" the default).

**Comment by jvoight** [comment]
Duplicate with #1972, will resolve there.
