### ISSUE TITLE
HMF bug in Sage download code

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1412]
From sage-support (David Loeffler):
-  if you try to download HMF data to Sage, you get an error, because the Sage script that's created contains the lines

hecke_pol = x^2 - x - 1
K.<e> = NumberField(heckePol)

and there is no such variable as "heckePol". Evidently it should be "hecke_pol" in the second line.

**Comment by JohnCremona** [comment]
Fixed in PR #1416

**Comment by JohnCremona** [comment]
Closing since #1416 is merged.

**Comment by jvoight** [comment]
Sorry, you're right, I only tested this for dimension 1.  Thanks for fixing this JC!
