### ISSUE TITLE
Random modular form

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#1434]
Other pages have a link that leads to a random object, modular forms don't but this is a nice feature and they should have it.

(The pull request that will fix this issue is coming very soon ;-)

**Comment by AndrewVSutherland** [comment]
You can now access random modular forms via http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/random.  Once issue #1248 has been addressed we can link this to a button on the main page for classical modular forms (I'll leave the issue open until that happens).

**Comment by AndrewVSutherland** [comment]
Addressed by #2717.  In addition to a random form link, you can also choose random newforms that match specified search criteria (e.g. a random newform with trivial character, or a random CM newform) using the "random form" button on http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/
