### ISSUE TITLE
"No newforms" on Galois conjugate pages

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#1442]
Y'all'll probably fix this in v.1.1, but right now on lmfdb.org, if you go to
   http://lmfdb.org/ModularForm/GL2/Q/holomorphic/32/2/29/
you'll see a page that says it has no newforms in it, but it is conjugate to a space that does have newforms.  This is confusing.

**Comment by AndrewVSutherland** [comment]
@jvoight Thanks for letting us know!.  I'm sure you are just trying to be diplomatic, but this isn't "confusing", it is a mathematical error in the data related to the open critical issue https://github.com/LMFDB/lmfdb/issues/1248 (and this form is within the extent we claim to have, see https://github.com/LMFDB/lmfdb/issues/873).  We are working on getting this (and all other errors in the data) fixed as quickly as possible (the fix will not wait for version 1.1, we will update the data on lmfdb.org whenever we have a new batch of verified data, we have already updated it once to fix a bunch of errors/omissions for the forms with trivial character, we are now working on the forms with non-trivial character).

So great observation (and please be sure to tell us about anything else you spot), but I don't think we should open a new issue for this.  I'll add a note in the two related issues.

**Comment by jvoight** [comment]
OK, thanks for sorting this as appropriate--I wasn't sure if it was included in the sweeping net of other issues.  Is someone keeping a track in the test files of any one of these that is reported, to make sure in the corrected version that they are correct?

**Comment by AndrewVSutherland** [comment]
I have a test script that runs through every space in the database that 
checks basic consistency and that all the pages load without errors, I 
am going to update it to check that the Galois conjugates listed for 
each Hecke orbit all give consistent information (i.e. display a page 
with the correct dimension or say they are conjugate to one that does).

This test script is rerun every time there is a code or data change.
