### ISSUE TITLE
Product L-functions for modular forms

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#1443]
It would be very helpful to list not just the individual L-functions L(f,s) but the product over all Galois conjugates.  In weight 2, these are the L-functions attached to abelian varieties, for example if f has coefficients in a quadratic field, then L(f,s)*L(f^sigma,s) is a degree 4 L-function with L-polynomials having rational coefficients associated to an abelian surface of GL_2-type.  

http://lmfdb.org/ModularForm/GL2/Q/holomorphic/64/2/49/a/

**Comment by JohnCremona** [comment]
I agree 100%.   We do attach d distinct degree 2 L-functions to a Galois orbit of size d by making d different choices of embedding, but we should also attach their product, a degree 2*d L-function independent of any choices.  As @jvoight says these are the ones which arise a lot in arithmetic geometry.

**Comment by edgarcosta** [comment]
We now have the product (for d<= 80) and now are computing the trace hash to match them with elliptic curves and genus 2 curves, e.g.:
* http://cmfs.lmfdb.xyz/L/ModularForm/GL2/Q/holomorphic/13/2/e/a/ and http://cmfs.lmfdb.xyz/L/Genus2Curve/Q/169/a/
* http://cmfs.lmfdb.xyz/L/ModularForm/GL2/Q/holomorphic/23/2/a/a/ and http://cmfs.lmfdb.xyz/L/Genus2Curve/Q/529/a/

(the primitivity and the character are wrongly assigned for the one coming from modular forms, and I'm fixing that right now)

**Comment by AndrewVSutherland** [comment]
Addressed by #2717, see

http://www.lmfdb.org/L/ModularForm/GL2/Q/holomorphic/13/2/e/a/
http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/270/5/g/a/

for example.
