### ISSUE TITLE
Remove obsolete L-function code

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1456]
As noted in https://github.com/LMFDB/lmfdb/issues/1431#issuecomment-221508874, there is some obsolete L-function code that uses the mongo db database Lfunction which we would like to remove (it has been superseded by Lfunctions).

The purpose of this issue is to remove the obsolete code and perform any other associated cleanup/reorganization of the L-function code that is appropriate.  @lemurell has offered to do this.

**Comment by davidlowryduda** [comment]
I think this issue can now be closed.

**Comment by edgarcosta** [comment]
I agree
