### ISSUE TITLE
Problems with elliptic curve bread crumbs

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1472]
If you go to the page http://www.lmfdb.org/EllipticCurve/Q/11/ (which you can reach via http://www.lmfdb.org/EllipticCurve/Q/11/a/1 and clicking on the breakcrumb for 11) and then click the "refine or change search" button you will get a server error (regardless of any search criteria you specify and even if you don't specify any)

The analogous problem does not occur for the ecnf pages, but now there is a different issue.  If you go to the page http://www.lmfdb.org/EllipticCurve/2.2.5.1/76.1/ (which you can reach by clicking on the 76.1 breadcrumb from any of the curves on this page) and type anything into any search box and click "search again" you will see exactly the same results, even if you type in, say conductor norm=77, you will be taken to the page http://www.lmfdb.org/EllipticCurve/2.2.5.1/76.1/?start=0&count=50&field=&conductor_norm=77&include_isogenous=on&include_base_change=on&include_Q_curves=include&include_cm=include&torsion=&torsion_structure=&jinv=, which lists curves of conductor 76.1.  Moreover, despite the URL including the field label 2.2.5.1, the displayed list of curves includes all curves with conductor labelled 76.1, even when it is the label of conductor ideal for a **different field** (e.g. Q(sqrt(17)).  This occurs already on the original breadcrump page http://www.lmfdb.org/EllipticCurve/2.2.5.1/76.1/ and should be fixed (the query needs to set the field label in the URL, as it does on http://www.lmfdb.org/EllipticCurve/2.2.5.1/).

Analogs of both of these problems were present for genus 2 curves and are addressed in PR #1471.  One could easily adapt the solution used there (see the functions by_conductor and by_url_isogony_class_discriminant in LMFDB/lmfdb/genus2_curves/genus2_curve.py) @JohnCremona.

**Comment by AndrewVSutherland** [comment]
Another similar bread crumb problem (this time not an intermediate bread crumb but the last one).  If you go to http://www.lmfdb.org/EllipticCurve/2.0.3.1/%5B2268%2C36%2C18%5D/a/1 and click on the last break crumb you will be taken to http://www.lmfdb.org/EllipticCurve/2.0.3.1/%255B2268%252C36%252C18%255D/a/1.

@JohnCremona I don't think this would be hard to fix -- would you like me to do it?

**Comment by JohnCremona** [comment]
PLease do.  Thanks

**Comment by bryongloden** [comment]
Greetings @AndrewVSutherland! Here to help

**Comment by davidfarmer** [comment]
I have blocked Bryon Gloden from LMFDB, but I did not report
him to the GitHub administrators.

According to GitHub:

Blocking a user prevents the following on all organization repositories:

     opening or commenting on issues or pull requests
     forking repositories
     adding or editing wiki pages

David

**Comment by AndrewVSutherland** [comment]
http://www.lmfdb.org/EllipticCurve/2.2.5.1/?conductor_norm=76 lists elliptic curves of conductor norm 76 over any field, not just 2.2.5.1; I will fix this as well.

**Comment by JohnCremona** [comment]
How does that URL get created?  I fI first search for field 2.2.5.1 and then add the conductor norm an re-search, it is good.

**Comment by AndrewVSutherland** [comment]
@JohnCremona It doesn't get created, but one can type it in.  I found it while testing various error cases.

I'm about to commit a PR and you can see how it all works, I think you'll like it.

**Comment by JohnCremona** [comment]
Thanks -- while not feeling any obligation to manage any manually entered URLs, this one certainly seems sensible.  I'll be able to review your patch!

**Comment by AndrewVSutherland** [comment]
Closed via #1624

**Comment by Athim1978** [comment]
Hey there @davidfarmer of @LMFDB! We know @bryongloden. He says he was trying to help in here  yesterday when he greeted @andrewvsutherland and he says he said he was in here to help. We want to know why’d you block him for offering to help? The public's opinion of you and your organization will be that you’re rude if you're blocking people from helping with your public @GitHub. Please unblock him so he can fork the repository and he'll agree to never comment on another one of your users pull request or issues ever again.
