### ISSUE TITLE
ECNF: sort summary pages

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#1484]
Once on http://lmfdb.org/EllipticCurve/browse/ if you click on any of the options, for example
http://lmfdb.org/EllipticCurve/browse/2/%282%2C0%29/
you get a list of results, indexed by number fields. Should the number fields be ordered also by discriminant?
This is done for Hilbert modular forms e.g. http://lmfdb.org/ModularForm/GL2/TotallyReal/browse/2/

**Comment by JohnCremona** [comment]
Yes of course, and this has been on my list for months.  The imaginary quadratics look even more stupid:  see http://lmfdb.org/EllipticCurve/browse/2/
