### ISSUE TITLE
Browsing Dirichlet character by order produces 502 Server Error (timeout)

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1506]
The page http://www.lmfdb.org/Character/Dirichlet/?ordbrowse=31-40 usually returns a 502 server error (occasionally it will load, but typically takes at least 20 seconds to do so).

**Comment by pascalmolin** [comment]
I have something to merge on this, in the next few days.

2016-06-03 3:16 GMT+02:00 Andrew Sutherland <notifications@github.com>:

**Comment by AndrewVSutherland** [comment]
@pascalmolin Are you still planning to submit a PR on this?

**Comment by pascalmolin** [comment]
yes, I'm on this one now (problems with implementing the next/previous page
for search results)

2016-06-28 22:41 GMT+02:00 Andrew Sutherland <notifications@github.com>:

**Comment by AndrewVSutherland** [comment]
@pascalmolin One issue I ran into is that if I start at http://127.0.0.1:37777/Character/ rather than http://127.0.0.1:37777/Character/Dirichlet (which I did accidentally just by clicking on the Characters link on the sidebar), some of the URL links in your character tables don't work (whereas the do on the production version), e.g. if you go to http://127.0.0.1:37777/Character/?order=5 and click on the first character listed \chi_11(3,\cdot) in the table, you wind up at http://127.0.0.1:37777/Character/11/3 which displays a page not found error.  But if I click on the analgous link on http://www.lmfdb.org/Character/?order=5 I am taken to the correct page http://www.lmfdb.org/Character/Dirichlet/11/3.

Now I don't actually think it is a good thing that the pages www.lmfdb.org/Character/ and www.lmfdb.org/Character/Dirichlet/ both look the same, the former page should either not be titled "Dirichlet Characters" (and have a corresponding breadcrumb trail Characters -> Dirchlet), or it should redirect (with a 301 so the url changes) to www.lmfdb.org/Character/Dirichlet/.

But I notice that the function for render_characterNavigation and render_Dirichletwebpage are actually rather different.  Should we perhaps just have render_characterNavigation do a flask.redirect(url_for(".render_Dirichletwebpage"),301) for the moment (at least until characters besides Dirichlet characters are included)?

**Comment by AndrewVSutherland** [comment]
@pascalmolin In any case, I think you should make sure the urls in the table links you display start with "/Character/Dirichlet/" regardless of how the table was reached.

**Comment by pascalmolin** [comment]
2016-07-01 0:34 GMT+02:00 Andrew Sutherland <notifications@github.com>:

> @pascalmolin <https://github.com/pascalmolin> One issue I ran into is
> that if I start at http://127.0.0.1:37777/Character/ rather than
> http://127.0.0.1:37777/Character/Dirichlet (which I did accidentally just
> by clicking on the Characters link on the sidebar), some of the URL links
> in your character tables don't work (whereas the do on the production
> version),
>
I have tried to solve this issue, but unfortunately I cannot connect to
lmfdb.warwick today, so the commit is not tested at all.

Now I don't actually think it is a good thing that the pages
> www.lmfdb.org/Character/ and www.lmfdb.org/Character/Dirichlet/ both look
> the same, the former page should either not be titled "Dirichlet
> Characters" (and have a corresponding breadcrumb trail Characters ->
> Dirchlet), or it should redirect (with a 301 so the url changes) to
> www.lmfdb.org/Character/Dirichlet/.
>
> I agree, the plan is to have a general landing page on characters, but
since Hecke are currently missing it was decided at some point to redirect
to the same Dirichlet page instead of having an almost empty shell... So I
think the redirection solution is the good one for now.

**Comment by AndrewVSutherland** [comment]
@pascalmolin Thanks for the update, I'll continue reviewing.  lmfdb.warwick is actually up but apparently there is an ip routing problem (people are working to get this fixed now).  I'll test on atkin which still knows how to talk to lmfdb.warwick.

**Comment by AndrewVSutherland** [comment]
Closed via #1630 and #1642 (now live on beta, soon to be on prod).
