### ISSUE TITLE
Sever error on classical modular form pages

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1533]
If you go to the page

http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/20/9/

and click on the link http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/20/9/11 for the Galois orbit of the space with dimension 16 you will see a server error.  Traceback appears below:

> ERROR:lmfdb.base@2016-06-08 11:08:30,431: Exception on /ModularForm/GL2/Q/holomorphic/20/9/11/ [GET] 
> Traceback (most recent call last):
>   File "/home/drew/sage-6.5-x86_64-Linux/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/drew/sage-6.5-x86_64-Linux/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/drew/sage-6.5-x86_64-Linux/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/drew/sage-6.5-x86_64-Linux/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/drew/sage-6.5-x86_64-Linux/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/drew/Dropbox/github/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/views/emf_main.py", line 132, in render_elliptic_modular_forms
>     return render_web_modform_space(*_info)
>   File "/home/drew/Dropbox/github/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/views/emf_render_web_modform_space.py", line 78, in render_web_modform_space
>     return render_template("emf_web_modform_space.html", *_info)
>   File "/home/drew/sage-6.5-x86_64-Linux/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/templating.py", line 128, in render_template
>     context, ctx.app)
>   File "/home/drew/sage-6.5-x86_64-Linux/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/templating.py", line 110, in _render
>     rv = template.render(context)
>   File "/home/drew/sage-6.5-x86_64-Linux/local/lib/python2.7/site-packages/Jinja2-2.5.5-py2.7.egg/jinja2/environment.py", line 891, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "/home/drew/Dropbox/github/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/views/templates/emf_web_modform_space.html", line 12, in top-level template code
>     {% set old_name = "( S_{%s}^{\mathrm{old}}(%s) )"|format(space.weight, space.character.latex_name) %}
>   File "/home/drew/Dropbox/github/lmfdb/lmfdb/templates/homepage.html", line 11, in top-level template code
>     <div class="{{ [L,'nodisplay','code','codebox'] | join(' ')}}">{% for line in lines %}{{prompt}}:&nbsp;{{line}}<br>{% endfor %}</div>
>   File "/home/drew/Dropbox/github/lmfdb/lmfdb/templates/base.html", line 120, in top-level template code
>     {% block body -%}{%- endblock body %}
>   File "/home/drew/Dropbox/github/lmfdb/lmfdb/templates/homepage.html", line 238, in block "body"
>     {% block content -%}
>   File "/home/drew/Dropbox/github/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/views/templates/emf_web_modform_space.html", line 70, in block "content"
>     {% include 'display-list-newforms.html' %}
>   File "/home/drew/Dropbox/github/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/views/templates/display-list-newforms.html", line 55, in top-level template code
>     {% if f.coefficient_field.variable_name().startswith("zeta") %}
> UndefinedError: 'unicode object' has no attribute 'variable_name'

**Comment by AndrewVSutherland** [comment]
The page http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/19/10/4/ has a similar problem.

**Comment by fredstro** [comment]
This seems to be solved as it is not  present on http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/20/9/11/  although it still fails on the production server.

**Comment by edgarcosta** [comment]
They work now:
* http://cmfs.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/20/9/b/
* http://cmfs.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/19/10/e/

**Comment by AndrewVSutherland** [comment]
Addressed by #2713.
