### ISSUE TITLE
sage_eval

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1539]
Hello,

We should a avoid the use of "sage_eval", if not, at least try to sanitize it. Especially, if the functions that use the sage_eval are being used to generate content for the website.

Best,
Edgar

**Comment by edgarcosta** [comment]
@AndrewVSutherland The two occurrences at the moment that the website uses are in the Lfunctions code.

https://github.com/LMFDB/lmfdb/search?utf8=%E2%9C%93&q=sage_eval

**Comment by AndrewVSutherland** [comment]
Agreed, this is a serious security issue (e.v. 

Currently this occurs only in 3 places, see https://github.com/LMFDB/lmfdb/search?utf8=%E2%9C%93&q=sage_eval; I'm guessing all of them can and should be converted to ast.literal_eval (this looks trivial to do in the first two cases, might require some work in the third).

**Comment by JohnCremona** [comment]
Agreed entirely.  We should not ever use eval orsage_eval to convert from a string.  sage_eval calls eval after applying preparsing.  I have used Sage for 9 years and have never ever had need for that function.  Most Sage types can be constructed from strings anyway:

   sage: a = ZZ('-123')
   sage: a, type(a)
   (-123, <type 'sage.rings.integer.Integer'>)

   sage: R = PolynomialRing(QQ,'x')
   sage: a = R('x^3-2*x+1')
   sage: a, type(a)
   (x^3 - 2*x + 1,
    <type 'sage.rings.polynomial.polynomial_rational_flint.Polynomial_rational_flint'>)

**Comment by JohnCremona** [comment]
Sorry the above output of the tye did not appear properly, but the point should be clear.

**Comment by JohnCremona** [comment]
@AndrewVSutherland For the third case, I cannot see any reason for the existence of the p2sage() function.  If you know that s encodes a real, use RR(s).  If complex, use CC(s).  If integers, use ZZ(s).  If a list of reals, use something like [RR(c) for c in s[1:-1].split(",")] .  I do that all the time.  Using eval is lazy -- and certainly dangerous.

There are 206 instances of "eval(" in our code including 55 of " eval(" and we should go through every one of these (some are fine of course).

**Comment by AndrewVSutherland** [comment]
@JohnCremona I agree 100% (I did not write that code).  I'm shocked to find out we have 55 instances of " eval(" (hopefully the other instances of "eval(" are all "literal_eval(", but we should check".

**Comment by JohnCremona** [comment]
We can ignore any magma.eval() and mag.eval() (121 instances I think) all in scripts which are not live website code.  And many others are harmless for similar reasons.  I think that the people using eval() are mainly less experienced with python/Sage.  The main thing to avoid is ever using eval on a string returned from a web page form.

**Comment by AndrewVSutherland** [comment]
All instances of eval and sage_eval in Siegel modular forms are removed in PR #1577 (there were six, including one applied to user input).

**Comment by JohnCremona** [comment]
I'm working on a new version of p2sage which does not use sage_eval: adding a print statement in there to show 'before' and 'after' and running test.sh showed that there are not so many different things to be dealt with.

**Comment by AndrewVSutherland** [comment]
Wonderful, thanks for dealing with this!

**Comment by JohnCremona** [comment]
Almost done, just checking if all still works after removing some of the things I am testing for.

**Comment by JohnCremona** [comment]
Done PR coming up

**Comment by JohnCremona** [comment]
We can close this now, though there are 2 pyflakes things, one already mentioned (a is defined but not used) and the other has a FIXME note attached already.

**Comment by AndrewVSutherland** [comment]
I note that there still are quite a few occurrences of eval.  Most are in import scripts (e.g. import_ec_data.py) that are not part of the site, but we really should check these.  Perhaps this should be a new issue?

**Comment by edgarcosta** [comment]
Close this and keep #1832 open?

**Comment by AndrewVSutherland** [comment]
@edgarcosta This issue was closed 4 days ago.

**Comment by edgarcosta** [comment]
ups, forget that. I clearly didn't sleep enough...
