### ISSUE TITLE
Update Hosting info on acknowledgements page

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1540]
The Hosting section should say something about the cloud now hosting our public site.  The Dartmouth grant is listed, perhaps we should say explicitly that this is what it is paying for.

**Comment by jvoight** [comment]
Right, I had updated the acknowledgements but not the Hosting page.  I'll do it.

**Comment by jvoight** [comment]
@JohnCremona see pull request #1655.  Not sure if the wording is quite right--what kind of acknowledg(e)ment do you want for the Warwick/Bristol servers, given that they still host beta, etc.?

**Comment by AndrewVSutherland** [comment]
@jvoight J.C. is on vacation at present, but #1655 looks fine to me (we can always change it again if need be).

**Comment by JohnCremona** [comment]
Thanks -- current text looks good to me.
