### ISSUE TITLE
genus 2 curves with no real points

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1547]
Some genus 2 curves have no real points. e.g. Genus2Curve/Q/336/a/172032/1 . That's a feature, not a bug; but do we actually want an empty graph?  And should it be indicated on the web page by more than the statement "Locally solvable: no" which could refer to some other completion of Q?

Just a question, I am not proposing a change, only that it should be thought about.

**Comment by AndrewVSutherland** [comment]
For curves that are not locally solvable it would seem reasonable to give a specific prime p <= infty for which C(Q_infty) is empty.

**Comment by nmascot** [comment]
@JohnCremona : Actually this curve does have RR-points; this is detected by my plotting algorithm, and the points get plotted. But the set of these points is so tiny that you can't see them (even though the plotting algorithm has adjusted the min and max values of x and y the best it could). To be precise, there are RR-points exactly for 3.2644.. < abs(x) < 3.2659.. .
When there are no RR-points, the plotting algorithm says so by writing X(RR)=ø (cf. Genus2Curve/Q/644/a/2576/1 for instance).

@AndrewVSutherland : If I'm not wrong, every genus 2 curve is solvable at every finite prime p>7, so the set of p <= infty at which a given curve is not solvable is always finite. So why not display all of them ?

**Comment by AndrewVSutherland** [comment]
@nmascot Agreed.

**Comment by nmascot** [comment]
Just done so in #2071

**Comment by AndrewVSutherland** [comment]
This issue has been addressed (curves with no real points are clearly identified and for curves that are not locally solvable we list all the places that lack local points).
