### ISSUE TITLE
Elliptic curves could/should show Atkin-Lehner eigenvalues (local root numbers)

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1548]
For example http://localhost:37777/EllipticCurve/Q/90/c/2 could show the local root numbers in the Local Data section.  It is +1 or -1 respectively for split and non-split multiplcative reduction, which can be read off instantly (but would still be worth showing since it is hard to remember which is which), and requires more work in the additive case.  Because of the latter it should be stored in the database.  If this had been suggested to me before we made the switch to having local doata stored it would have been trivial to add it.   As it is, it will require adding to the 'local_data' component to the stored data for every curve.

**Comment by JohnCremona** [comment]
See #1574.  All the precomputation has been done and stored in a new collection.  When that has been merged and the collections renamed, this can be closed.

**Comment by AndrewVSutherland** [comment]
As discussed on #1574, the collections have now all been updated.  You should still change the code to actually use the data at some point (not urgent).  Feel free to close or leave this issue open as a reminder as you see fit.

**Comment by JohnCremona** [comment]
Ah, now I see where the confusion is.  The code already uses the new data when it is there!  That code changes was already in #1563 .  So I'll close this.
