### ISSUE TITLE
ecnf twist link broken

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1561]
Dan Yasaki reported this.  Go to any home page of an elliptic curve over a number field, for example http://beta.lmfdb.org/EllipticCurve/4.4.4913.1/169.6/a/2 and click on the Twists link under Related Objects.  It fails since when we do a search for curves with a fixed j-invariant we need to specify the field.
I will fix this.

**Comment by AndrewVSutherland** [comment]
Fixed by #1562
