### ISSUE TITLE
robots.txt broken

### ISSUE THREAD

**Issue by haraldschilly** [LMFDB/lmfdb#1570]
Hi, I just saw a notification, that the robots.txt file is broken. There is a mechanism, that disables indexing the page, if it is hosted somewhere else -- as a result, only the main page should be indexed and not the other ones. The transfer of the lmfdb page must have broken this heuristic, such that http://lmfdb.org/robots.txt is wrong.

Heuristic is here:

https://github.com/LMFDB/lmfdb/blob/master/lmfdb/website.py#L89

**Comment by haraldschilly** [comment]
ok, no, I think it's all fine. This circles back to the question, if there should be www. or not.

i.e. http://www.lmfdb.org/robots.txt is correct!

hence I'm closing it, but since many got this as an email, it's maybe some food for thought about this. (i.e. should be add an automatic redirection to include www. in the url)

**Comment by edgarcosta** [comment]
> should be add an automatic redirection to include www. in the url

where should we do that? code? or gce?

**Comment by haraldschilly** [comment]
if at all, that should be in the code. we also don't have to forget to declare the preferred way in the webmaster tools...

but for now, I wouldn't do anything.
