### ISSUE TITLE
Genus 2 server error on search download

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1572]
From Jen Balakrishnan via the feedback page:

"Clicking the magma/sage/pari links at the bottom of this page:
http://lmfdb.org/Genus2Curve/Q/?analytic_rank=0 (not just analytic rank 0, but also for any analytic rank query)

results in the following message:

The page you are looking for has produced a server error.
If you want to help improving the page behind ""http://lmfdb.org/Genus2Curve/Q/?analytic_rank=0"", please report that page's URL!"

Include @jbalakrishnan (and maybe directly jennifer.balakrishnan@gmail.com) in replies to this issue.

**Comment by AndrewVSutherland** [comment]
I will fix this later today (I want to wrap up a PR I am working on now for Siegel modular forms first).

**Comment by AndrewVSutherland** [comment]
Fixed by #1578

**Comment by AndrewVSutherland** [comment]
And I'll e-mail Jen directly

**Comment by edgarcosta** [comment]
@jbalakrishnan has reported the same issue again, and I have verified it

**Comment by AndrewVSutherland** [comment]
@edgarcosta I just checked this and it works for me (using chrome on ubuntu), can you give more details on how you reproduced it?  I used the query http://www.lmfdb.org/Genus2Curve/Q/?analytic_rank=0&count=50 and clicking any of the magma, sage, pari buttons seems to work fine.

**Comment by JohnCremona** [comment]
Same for me (also chrome ubuntu).  I'll try on a different machine in a while.

**Comment by jbalakrishnan** [comment]
The issue for me (chrome on OS X) is that the downloaded file seems to be
all ~66,000 curves in the database, not the particular list of curves found
by the query.

Jen

**Comment by AndrewVSutherland** [comment]
@jbalakrishnan Thanks, I get the same problem.

**Comment by edgarcosta** [comment]
I also tested it in OSX with Chrome.

**Comment by AndrewVSutherland** [comment]
Fixed by PR #2416.  As  @jbalakrishnan  indicated, the problem is not that the download buttons caused a server error, but that the download results contained all the curves in the database rather than the subset matching the query.  This has been fixed.

**Comment by jbalakrishnan** [comment]
@AndrewVSutherland Thanks!

**Comment by edgarcosta** [comment]
#2416 has been merged
