### ISSUE TITLE
flask.redirect(404) should be flask.abort(404)

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1592]
There are several places in the code (at least 7) where flask.redirect(40) is returned because of an error (usually something cannot be found or there is an invalid argument or request type in the URL).

Returning flask.redirect(404) when something cannot be found is not as useful as instead returning flask.abort(404).  Both display the same page 404.html, but in the former case the URL that caused the problem is no longer visible (and hitting the back button won't help because it won't let you see the problematic URL).  This makes bug reporting and problem resolution more difficult.  Compare:

flask.redirect(404) --> http://www.lmfdb.org/404
flask.abort(404) --> http://www.lmfdb.org/PageNameWithAnEasilyCorrectedTypoInIt

**Comment by edgarcosta** [comment]
Perhaps, we should also try to standardize the usage of 404, 400, and 500.
at the moment, there many pages that throw an internal server error, when they indeed mean 404 or 400.
