### ISSUE TITLE
The meta description is a knowl

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1594]
***1 Upvote*** Hello,

This line:
`
<meta name="description" content="Welcome to the LMFDB, the database of L-functions, modular forms, and related objects. These pages are intended to be a modern handbook including tables, formulas, links, and references for L-functions and their underlying objects.">
`
common to all the webpages, comes from this knowl:

http://beta.lmfdb.org/knowledge/show/intro.description

see: https://github.com/LMFDB/lmfdb/blob/master/lmfdb/base.py#L203

Shouldn't this be hardcoded?

Best,
Edgar

**Comment by AndrewVSutherland** [comment]
+1 Anyone who can log in on beta (which is not secure, we are not even using https) can change our welcome message say whatever they want it to say.  This should definitely be hard-coded.
