### ISSUE TITLE
Isogeny classes elliptic curves

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#1600]
http://www.lmfdb.org/EllipticCurve/Q/91/b/

produces a server error

**Comment by sanni85** [comment]
Sorry, now it works. It was giving Error 502 for a while.

**Comment by JohnCremona** [comment]
Iaccessed the same page at the same time (these curves were referred to in a talk in Warwick by Tim Dokchitser so may have been heavily in demand).

It could be related to the emails I received like this:

 Summary: An uptime check on lmfdb.org is failing

    Uptime check failed

Violation Began: 2016-06-27 16:09:17 UTC
Condition Name: Generic HTTP check on lmfdb.org
View violation details: https://app.google.stackdriver.com/select-customer?customer_id=1118602&next=/violations/91097e02-fdae-45a7-ad70-bc231b7c62ac&utm_source=alerting&utm_medium=email&utm_campaign=notification 

followed soon after by


Summary: The uptime check for lmfdb.org has returned to a normal state

    Uptime check failed -> RESOLVED

Violation Began: 2016-06-27 16:35:00 UTC
Violation Ended: 2016-06-27 16:50:13 UTC
Violation Lasted: 15 minutes

**Comment by AndrewVSutherland** [comment]
This is probably related to work I have been doing to try and diagnose #1599 (which occurs only on www.lmfdb.org not on beta.lmfdb.org).  This put a heavy load on the mongo db server (I just reloaded all the HMFs from warick to the cloud but it's done now).  I'm going to close this issue but please reopen it if the problem recurs
