### ISSUE TITLE
Some ecnf twist links do not work

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1618]
If you go to http://www.lmfdb.org/EllipticCurve/2.2.5.1/31.1/a/1 and click on the twists link under related objects you get a server error on http://www.lmfdb.org/EllipticCurve/?field=2.2.5.1&jinv=-106208%2F31%2Aphi+%2B+51455%2F31
which complains about not being able to convert phi to a rational (presumably this is do to the code expecting the field elements to be expressed in terms of "a" rather than "phi").

**Comment by JohnCremona** [comment]
Yes: for this field the generator is phi and for Q(sqrt(-1)) it is i, otherwise it is a.  While looking nicer this has caused all sorts of annoying issues like this one.  I can fix it.

**Comment by JohnCremona** [comment]
Patch on its way

**Comment by AndrewVSutherland** [comment]
Fixed by #1621
