### ISSUE TITLE
Problems with lcalc downloads for Dirichlet characters

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1619]
I don't see how these are being reached (they are not shown on the L-function pages for Dirichlet character), but we are getting errors in flasklog triggered by robots trying to visit pages like:

http://www.lmfdb.org/L/Character/Dirichlet/103/85/?download=lcalcfile

In fact almost all the Dirichlet lcalc downloads don't work, e.g.

http://www.lmfdb.org/L/Character/Dirichlet/7/2/?download=lcalcfile

produces the same error.

This appears to be caused by createLcalcfile_ver2 in LfunctionLcalc.py trying to convert strings like "$e\left(\frac{2}{3}\right)$" to complex numbers.

**Comment by AndrewVSutherland** [comment]
Robots are still hitting these (a bunch occurred last night, although I do not think they are what caused the outage).

**Comment by edgarcosta** [comment]
I believe that they were reachable at some point, and I guess that
webcrawlers put them on their todo list for later.

**Comment by AndrewVSutherland** [comment]
@AndrewVSutherland I can take a look at this and see if I can at least stop the exceptions from showing up in flasklog.

**Comment by AndrewVSutherland** [comment]
Fixed in PR #1695 (the problem was Dirichlet coeffs specified as strings e(m/n) (in fact as $e\left\frac{m}{n}\right)$.  string2number in Lfunctionutilities.py has been changed to handle these.

**Comment by AndrewVSutherland** [comment]
PR #1736, which fixed #1733 effectively undid #1695 which fixed this issue, which is now happening again.  I will integrate the two fixes and add a test case to make sure this doesn't happen again.
