### ISSUE TITLE
Please update artin rep database in the cloud

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1635]
Please update the cloud database for artin.representations.  I fixed faulty data for 6 artin representations (those with Galois group 12T12) in warwick.  If you like, you can see the difference by comparing beta and the production servers for the L-function plots of the representations.  Here are links to the L-functions on beta.

http://beta.lmfdb.org/L/ArtinRepresentation/2.2e2_3_11e2.12t12.2c1
http://beta.lmfdb.org/L/ArtinRepresentation/2.2e2_3_11e2.12t12.2c2
http://beta.lmfdb.org/L/ArtinRepresentation/2.2e4_11e2.12t12.2c1
http://beta.lmfdb.org/L/ArtinRepresentation/2.2e4_11e2.12t12.2c2
http://beta.lmfdb.org/L/ArtinRepresentation/2.3e3_11e2.12t12.2c1
http://beta.lmfdb.org/L/ArtinRepresentation/2.3e3_11e2.12t12.2c2

**Comment by AndrewVSutherland** [comment]
Done.
