### ISSUE TITLE
search zeros

### ISSUE THREAD

**Issue by pascalmolin** [LMFDB/lmfdb#165]
The zero search replaces the user range by different values
e.g.
http://www.lmfdb.org/zeros/first/?limit=10&start=1.64&end=1.65&degree=1
and
http://www.lmfdb.org/zeros/first/?limit=10&start=1.6&end=1.7&degree=2

**Comment by haraldschilly** [comment]
need to check if it is fixed?

**Comment by davidfarmer** [comment]
seems to work now
