### ISSUE TITLE
Server error on two degree 10 number field pages

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1661]
If you go to http://www.lmfdb.org/NumberField/?degree=10&discriminant=1107649855354064 you will see a link to the number field 10.10.1107649855354064.1 (so this is a valid label).  If you click on the link to go to http://www.lmfdb.org/NumberField/10.10.1107649855354064.1 you get an internal server error. 

The flasklog trace-back appears below:

> Exception on /NumberField/10.10.1107649855354064.1 [GET]
> Traceback (most recent call last):
>   File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/number_fields/number_field.py", line 411, in by_label
>     return render_field_webpage({'label': nf_string_to_label(label)})
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/number_fields/number_field.py", line 389, in render_field_webpage
>     return render_template("number_field.html", properties2=properties2, credit=NF_credit, title=title, bread=bread, code=nf.code, friends=info.pop('friends'), learnmore=info.pop('learnmore'), info=info)
>   File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/templating.py", line 128, in render_template
>     context, ctx.app)
>   File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/templating.py", line 110, in _render
>     rv = template.render(context)
>   File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 989, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 754, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/number_fields/templates/number_field.html", line 1, in top-level template code
>     {% extends 'homepage.html' %}
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/templates/homepage.html", line 11, in top-level template code
>     <div class="{{ [L,'nodisplay','code','codebox'] | join(' ')}}">{% for line in lines %}{{prompt}}:&nbsp;{{line}}<br>{% endfor %}</div>
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/templates/base.html", line 120, in top-level template code
>     {% block body -%}{%- endblock body %}
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/templates/homepage.html", line 254, in block "body"
>     {% block content -%}
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/number_fields/templates/number_field.html", line 191, in block "content"
>     {% for artin in info["tim_number_field"].artin_representations()%}
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/math_classes.py", line 714, in artin_representations
>     return [ArtinRepresentation(z['Baselabel'],z['GalConj']) for z in self.ArtinReps()]
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/math_classes.py", line 96, in __init__
>     self._data = self.__class__.collection().find_and_convert_one({'Baselabel':str(base)})
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/databases/bind_collection.py", line 40, in find_and_convert_one
>     y = self._type_conversion(x)
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/databases/type_generation.py", line 113, in initVariableValueTypes
>     tmp = dict([(k, (f[0][k])(v)) for (k, v) in x.items()])
> AttributeError: 'NoneType' object has no attribute 'items'
> 

There is also a server error on  http://www.lmfdb.org/NumberField/10.10.138420300533025695415730492558689.1, but the traceback indicates that it may be for a different reason (its failing to convert a large number to a 64-bit integer):

> Exception on /NumberField/10.10.138420300533025695415730492558689.1 [GET]
> Traceback (most recent call last):
>   File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/number_fields/number_field.py", line 411, in by_label
>     return render_field_webpage({'label': nf_string_to_label(label)})
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/number_fields/number_field.py", line 379, in render_field_webpage
>     v = nf.factor_perm_repn(info["tim_number_field"])
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/WebNumberField.py", line 491, in factor_perm_repn
>     cc = nfgg.conjugacy_classes()
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/math_classes.py", line 705, in conjugacy_classes
>     return [ConjugacyClass(self.G_name(), item) for item in self._data["ConjClasses"]]
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/math_classes.py", line 660, in G_name
>     wnf = WebNumberField.from_polredabs(self.polredabs())
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/math_classes.py", line 612, in polredabs
>     pol = PolynomialRing(QQ, 'x')(map(str,self.polynomial()))
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/math_classes.py", line 601, in polynomial
>     return PolynomialAsSequenceInt([int(a) for a in polstring.split(",")])
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/databases/type_generation.py", line 68, in initOneFunction
>     tmp = (map(f[0], x[:n]))
>   File "/home/lmfdb/lmfdb-git-prod/lmfdb/databases/type_generation.py", line 38, in __new__
>     return super(ImmutableExtensionClass, cls).__new__(cls, x)
> OverflowError: Python int too large to convert to C long
>

**Comment by jwj61** [comment]
The second case was fixed yesterday.

The first one traced to an error in the data in the artin database.  It has been corrected in the warwick database and the field now works.  I searched for any other examples in the warwick database with this error and this was the only one.  There is more work to do to determine how the erroneous value got in there (there is a fixed placeholder used for representations which are not faithful which then get replaced at a later stage of processing -- this one was not replaced).

To correct the issue on the production server, copy the collection field_data from the artin database from Warwick to the cloud.

**Comment by AndrewVSutherland** [comment]
Done, and the problem is fixed.  The pages

http://www.lmfdb.org/NumberField/10.10.1107649855354064.1
http://www.lmfdb.org/NumberField/10.10.138420300533025695415730492558689.1

now both work.

**Comment by AndrewVSutherland** [comment]
@jwj61 The page http://beta.lmfdb.org/NumberField/10.10.1107649855354064.1 is showing a server error again (but http://www.lmfdb.org/NumberField/10.10.1107649855354064.1 is fine).  It looks like the data in the artin database has changed -- is it possible that the problem that you fixed before was reintroduced with this change?

**Comment by jwj61** [comment]
I have been adding data, which includes reimporting it all.  So yes, that is a likely cause.  I will look into it.

**Comment by jwj61** [comment]
I fixed the bug in the data stored outside lmfdb which is used for uploads and re-uploaded.  Now this page and issue #1906 are fixed on beta, and uploading the data to the cloud should have both fixed on www.lmfdb.org.  I did regenerate the random collection.

**Comment by AndrewVSutherland** [comment]
Should I copy the artin database to the cloud now, or do you have more changes coming?

**Comment by jwj61** [comment]
Copy now.  There will be yet more data later, but you get both bug fixes and more data now!

**Comment by AndrewVSutherland** [comment]
Done.
