### ISSUE TITLE
Remove quadratic_twists.py

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1679]
The page www.lmfdb.org/quadratic_twists does not appear to do anything useful (every link simply says "no such curves" and the underlying code https://github.com/LMFDB/lmfdb/blob/master/lmfdb/quadratic_twists.py appears to not have been touched in a meaningful way for more than 5 years.

The page http://www.lmfdb.org/quadratic_twists/download_Rub_data (presumably discovered by a robot) raises internal server errors that are showing up in the flasklog.

I believe this page is obsolete and should be removed.

**Comment by JohnCremona** [comment]
I agree -- Gagan Sekhon has not been involved with LMFDB since 2011 at MSRI, and no-one else apart has edited this file apart from trivial changes.  But @mrubinst should perhaps comment since I think she was doing this under his guidance (and one of the functions is called "download_Rub_data()").

**Comment by AndrewVSutherland** [comment]
@JohnCremona Shall I submit a PR to remove this?

**Comment by JohnCremona** [comment]
I was hoping for a response from Mike R but I don't know if he gets these notifications.  As usual, the file is always retrievable.  Woud it be sufficient in the first instance to comment oute the  route /quadratic_twists ?

**Comment by AndrewVSutherland** [comment]
Sure, let's do that first.

**Comment by AndrewVSutherland** [comment]
#1754 removes quadratic_twists from website.py

**Comment by mrubinst** [comment]
Sorry for overlooking this. Only noticed today. I'm okay with removing the
stuff Gagan worked on. Thanks, Mike

**Comment by JohnCremona** [comment]
Thanks @mrubinst we'll do it now.

**Comment by AndrewVSutherland** [comment]
Closed via #1754 and #1761.
