### ISSUE TITLE
Resource intensive L-function zeros pages for classical modular forms

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1680]
Several L-function zeros pages for classical modular forms are extremely resource intensive and result in timeouts after 60 seconds (not 30, which is strange).

These are getting hit regularly (possibly by robots) and showing up in the flasklog; they could cause the webserver to become unresponsive if many are requested simultaneously, which is why I am labeling it as a production problem (even though it is not obvious to me how a user would access these pages).

Examples include:

http://www.lmfdb.org/L/Zeros/ModularForm/GL2/Q/holomorphic/10/12/9/a/0/
http://www.lmfdb.org/L/Zeros/ModularForm/GL2/Q/holomorphic/13/11/2/a/0/
http://www.lmfdb.org/L/Zeros/ModularForm/GL2/Q/holomorphic/19/5/18/a/0/
http://www.lmfdb.org//L/Zeros/ModularForm/GL2/Q/holomorphic/29/3/2/a/1/
http://www.lmfdb.org/L/Zeros/ModularForm/GL2/Q/holomorphic/52/3/27/a/3/
http://www.lmfdb.org/L/Zeros/ModularForm/GL2/Q/holomorphic/75/8/32/a/0/
http://www.lmfdb.org/L/Zeros/ModularForm/GL2/Q/holomorphic/75/8/32/a/1/
http://www.lmfdb.org/L/Zeros/ModularForm/GL2/Q/holomorphic/79/12/1/a/0/

I note that the last example has trivial character and has been accessed many times (dozens).

**Comment by edgarcosta** [comment]
I think the reason why it took 60s for you to get an error message has something to do with the timeout of the loadbalancer and the timeout for gunicorn being the same, both were set at 30s.
I you access them directly on beta or www-centraln, you get to see the gunicorn issuing a timeout and you get an LMFDB error message, instead of of the generic error message from google, saying to try again in 30s.

I have now reduced the gunicorn timeout to 25s, this way, if a webpage timesout the users get's an error message from LMFDB instead of the generic one from google.

ps: I can also  easily increase the loadbalancer timeout.

**Comment by AndrewVSutherland** [comment]
@edgarcosta Now the pages give "internal server errors", which is less helpful, it would be good to tell the user that the query timed out (and ideally it would be better to give some indication that the LMFDB is actually up and running, it's just this particular page that has a problem and give them an option to return to www.lmfdb.org).

**Comment by edgarcosta** [comment]
Hmm, we are getting different things.
I get the 500 error page from lmfdb saying:
"The page you are looking for has produced a server error."

**Comment by AndrewVSutherland** [comment]
@edgarcosta Actually I am getting the same message as you ("server error" not "internal server error"), sorry for the confusion.  So here's a question -- is the only way to get this page a timeout?  If so it would be nice to change the message, if not it would be nice to find a way to distinguish timeout 500's from others.

**Comment by edgarcosta** [comment]
I'm don't know how at the moment.
Perhaps we can try to catch the sigkill or the sigabrt signal and produce a
different error message?
https://github.com/benoitc/gunicorn/blob/master/gunicorn/arbiter.py#L468

**Comment by edgarcosta** [comment]
On the new version of the classical modular forms we only serve L-functions from the database, and this is no longer an issue.

**Comment by AndrewVSutherland** [comment]
Addressed by #2717.  All CMF L-functions are now precomputed and stored in the database.
