### ISSUE TITLE
Bad labels for many degree 4 number fields on beta

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1697]
If you go to http://beta.lmfdb.org/NumberField/?discriminant=1944468 (for example) you will see 6 results

http://beta.lmfdb.org/NumberField/4.4.1944468.1
http://beta.lmfdb.org/NumberField/4.1944468.0.1
http://beta.lmfdb.org/NumberField/4.1944468.0.2
http://beta.lmfdb.org/NumberField/4.1944468.0.3
http://beta.lmfdb.org/NumberField/4.1944468.0.4
http://beta.lmfdb.org/NumberField/4.1944468.0.5

Only the first of these has a label of the form d.r.D.i where the second part r is the number of real embeddings (see http://beta.lmfdb.org/NumberField/FieldLabels) and the third part D is the absolute discriminant (it looks like r and D may have been inadvertently swapped).

This appears to affect more than a million recently added quartic fields (there are 2109331 degree 4 fields on beta, but only 618536 on prod, the problems all appear in the fields that are new on beta).

**Comment by jwj61** [comment]
A byproduct of making a new import script.  Luckily, it appears it won't be too hard to fix.

**Comment by jwj61** [comment]
The recently imported fields now have their labels fixed as can be seen from the search mentioned above.

This might be a good time to copy fields to the cloud -- it has many more fields than the cloud version, both a big import in degree 4, and some higher degree fields from Kluners-Malle.

I should do something about updating the random field database, but I forget what I am supposed to do.

**Comment by AndrewVSutherland** [comment]
Use create_random_object_index in lmfdb/data_mgt/utilities/rewrite.py.  It will automatically drop the existing fields.rand collection when you run it.  You want to do

create_random_object_index (db, "fields")

where db is a pointer to the numberfields database on which you have authenticated as editor.

**Comment by jwj61** [comment]
Done, and I will make a note of what to do.

**Comment by AndrewVSutherland** [comment]
@jwj61 Do you want me to update the fields collection on the cloud now?

**Comment by jwj61** [comment]
Yes, please.

**Comment by AndrewVSutherland** [comment]
@jwj61 I'm confused, it looks to me like there are still 736,753 degree 4 fields with bad labels in the warwick database, starting with [4.1000016.4.1](http://beta.lmfdb.org/api/numberfields/fields/ObjectId%28%275744e149769754d119f35e09%27%29) and ending with [4.266098702171302000.2.32](http://beta.lmfdb.org/api/numberfields/fields/ObjectId%28%275744e4bf769754d1190a1b02%27%29)

**Comment by jwj61** [comment]
You are right.  In fixing them, I was too focused on labels with a 0, so the totally real cases.  Since there are no quartic fields with absolute discriminant 2 or 4, swapping those should be easy as well, although it will be another day or so.

**Comment by jwj61** [comment]
The fields and fields and fields.rand collections should be ready now.

**Comment by AndrewVSutherland** [comment]
Thanks, looking at it now.

**Comment by AndrewVSutherland** [comment]
Looks good, copying now.

**Comment by jwj61** [comment]
Closing since the issue only ever existed on beta and that is fixed, and is now being copied to the cloud

**Comment by AndrewVSutherland** [comment]
@jwj61 The new fields collection is now on the cloud with 6941393 records, of which 2109331 have degree 4.  I will leave the old_fields collection around for a few days just in case anything goes wrong.
