### ISSUE TITLE
attribution of zeta zeros data

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#17]
The attribution information in a knowl at the top of

http://www.lmfdb.org/zeros/zeta/

should the rewritten as a "cite this as" at the bottom of the page.

**Comment by alinabucur** [comment]
Write data quality source knowl.

**Comment by AndrewVSutherland** [comment]
The data quality source knowl is now present

http://www.lmfdb.org/knowledge/show/dq.zeros.zeta.howcomputed

I updated it to cite the MR# and DOI of Platt's paper, which has now been published.
