### ISSUE TITLE
Server error on many GL3 and GL4 Maass form lcalc files

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1733]
Several examples from flasklog

http://www.lmfdb.org/L/ModularForm/GL3/Q/Maass/1/1/16.40312_0.171121/-0.4216864/?download=lcalcfile
http://www.lmfdb.org/L/ModularForm/GL3/Q/Maass/4/1/9.632444_1.374060/0.15012282/?download=lcalcfile
http://www.lmfdb.org/L/ModularForm/GL3/Q/Maass/4/1/8.954662_2.936591/0.36025530/?download=lcalcfile
http://www.lmfdb.org/L/ModularForm/GL4/Q/Maass/1/1/16.89972_2.272587_-6.03583/0.55659019/?download=lcalcfile
http://www.lmfdb.org/L/ModularForm/GL3/Q/Maass/1/1/-16.4031_-0.17112/-0.4216864/?download=lcalcfile
http://www.lmfdb.org/L/ModularForm/GL3/Q/Maass/4/1/-9.63244_-1.37406/0.15012282/?download=lcalcfile
http://www.lmfdb.org/L/ModularForm/GL3/Q/Maass/4/1/-8.95466_-2.93659/0.36025530/?download=lcalcfile
http://www.lmfdb.org/L/ModularForm/GL4/Q/Maass/1/1/-16.8997_-2.27258_6.035835/0.55659019/?download=lcalcfile
http://www.lmfdb.org/L/ModularForm/GL3/Q/Maass/1/1/16.40312_0.171121/-0.4216864/?download=lcalcfile

Failures occur in parse_complex_number (in LfunctionLcalc.py)

**Comment by JohnCremona** [comment]
I do not know why we have to write such a function in the first place, since Sage is good at construction numbers from a variety of different strings.

sage: x,y = CC('3+4*i'); (x,y)
(3.00000000000000, 4.00000000000000)

That parse function does not actually specify what forms of in put are expected and catered for.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Do you want to take a stab at removing it?  It not I can look at it.

**Comment by JohnCremona** [comment]
In one of the above the string being parsed is u'(1.0)' and the code I pasted above handles that fine.

I will therefore make a patch for this myself.

**Comment by JohnCremona** [comment]
Testing my patch now.

**Comment by JohnCremona** [comment]
OK -- 1 minute to write better code and 15 minutes to realise that it was unicode strings which were making it fail.

**Comment by AndrewVSutherland** [comment]
Checking now.
