### ISSUE TITLE
Bad bread on Hecke character pages

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1753]
Go to http://beta.lmfdb.org/Character/Hecke/2.2.8.1/8.4a1/1 and click on the last bread crumb to get a server error.  This affects essentially all the Hecke character pages and is causing a lot of exceptions to show up in the flasklog for beta.lmfdb.org (web crawlers will click on all these breadcrumbs).

**Comment by JohnCremona** [comment]
Should be quite easy if the only problem is the extraneous [ ] in the URL?  I can take a look.

**Comment by AndrewVSutherland** [comment]
Fixed in #1755 (I'm confused by the number labels in WebCharacter.py, where "number" is a list of numbers that I think always has length 1, but in any case number2label encodes it as '.'.join(number) which will work regardless and I just changed the last breadcrumb URL to '' (i.e. the current page), which is always going to work).

**Comment by JohnCremona** [comment]
Thanks.  I was about to ask if this "number" was always a list of length 1 or not.  I'll check out #1755.

**Comment by AndrewVSutherland** [comment]
Fixed via #1755
