### ISSUE TITLE
remove calls to eval from all lmfdb website code

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1832]
This is a followup to the recently closed issue #1539, which removed all calls to sage_eval.  There are only a few calls to eval left, and most appear in import or verification scripts that are not part of the website.  Running following command in the top level lmfdb directory will list all calls to a naked "eval" function or method (this excludes calls to ast.literal_eval, which are safe):

```
 find | grep "\.py$" | xargs grep  "[^_a-zA-Z]eval[\s]*(" -c | grep -v ":0"

./lmfdb/lfunctions/Lfunction.py:2
./lmfdb/modular_forms/elliptic_modular_forms/backend/plot_dom.py:1
./lmfdb/elliptic_curves/import_ec_lfunction_data.py:1
./lmfdb/hilbert_modular_forms/recompute_AL.py:19
./lmfdb/hilbert_modular_forms/recompute_Galois_squarefull_forms.py:3
./lmfdb/hilbert_modular_forms/recompute_AL_modp.py:29
./lmfdb/hilbert_modular_forms/q_expansion.py:16
./lmfdb/hilbert_modular_forms/import_hmf_data.py:29
./lmfdb/hilbert_modular_forms/import_hmf_data_new_Galois_squarefull_forms.py:27
./lmfdb/ecnf/hmf_check_find.py:16
./lmfdb/transitive_group.py:1
./lmfdb/databases/standard_types.py:2
```

The filenames beginning with "import" and "recompute" are not used in the website code, nor is ecnf/hmf_check_find.py or hilbert_modular_Forms/q_expansion.py (and most of the evals therein are calls to magma.eval).  That leaves only

```
./lmfdb/lfunctions/Lfunction.py:2
./lmfdb/modular_forms/elliptic_modular_forms/backend/plot_dom.py:1
./lmfdb/transitive_group.py:1
./lmfdb/databases/standard_types.py:2
```

A total of 6 occurrences.

**Comment by JohnCremona** [comment]
Your regexp is not perfect!  In *my* file hmf_check_find.py, every instance of "eval" is in "mag.eval" and these are all in a function which is sending magma commands to an inferior process.

Anyway, I strongly agree with the proposal to remove all genuine eval() calls from all "live" code.

**Comment by AndrewVSutherland** [comment]
@JohnCremona The regex was not meant to ignore mag.eval (or gap.eval, which is present in transitive_group.py), I was actually interested in finding those too.  To also ignore occurrences of eval in ".eval" instead use:

 find | grep "\.py$" | xargs grep  "[^_\.a-zA-Z]eval[\s]*(" -c | grep -v ":0"

**Comment by JohnCremona** [comment]
OK!  Your regexpertise is certainly better than mine.  I was just definding myself since I think these mag.eval()s are harmless.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Given that magma is not installed on the servers running www.lmfdb.org, I agree :)  And these all occur in python code that isn't part of the website anyway (which is what I really wanted to check).

The use of gap.eval in transitive_group.py is probably also harmless but at least bears thinking about (e.g. does the gap shell give you access to the os shell, like sage does?).  I'd ask @jwj61 to comment on this.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Right, which is why it probably is a good thing to check for mag.eval calls to be sure they only occur in code that is not part of the website (otherwise lmfdb.warwick.ac.uk might be at risk -- or does it also not have magma installed on it?).

It would be good to find out what the situation is with GAP.

**Comment by JohnCremona** [comment]
Let's divide up the remaining files with eval() in them: I am now looking at databases/standard_types.py

**Comment by AndrewVSutherland** [comment]
@JohnCremona Sounds good, I can tackle modular_forms/elliptic_modular_forms/backend/plot_dom.py (which I was looking at recently anway). But I won't get to it for a few hours.

**Comment by jwj61** [comment]
On the gap.eval call, the input is pretty tightly controlled (it all comes from a pair of integers (n,t), then you have gap contruct a transitive group, have gap construct its character table, and then this call captures the string when gap displays it.  I did not find a way to have sage do that without gap.eval.  I think it is a sage mismatch in syntax, in that pari( string ) or gp( string ) is the analogue of gap.eval( string ), although there may be a subtle difference (with gap.eval we want to capture the string gap prints, not an object).

In the short term, I would not worry about it.  In the medium term, we can precompute them in gap and store them in the database.  In the longer term, we precompute them in magma and store them in the database.  Maybe we skip storing the gap version, but the magma solution will be a little more complicated since we will do more processing on the information (converting character values into nicely displayed algebraic numbers, and producing the lines on power conjugacy classes).

**Comment by AndrewVSutherland** [comment]
@jwj61 I agree it is safe, but I think in line 463 of transitive_group.py if you simply replace

`ctable = gap.eval("Display(%s)" %CT.name())`

with 

`str(CT.Display())`

the code will work exactly as it does now (at least this worked when I tried it in sage).

**Comment by jwj61** [comment]
Excellent.  Pull request coming

**Comment by jwj61** [comment]
Both transitive_group and standard_types are fixed

**Comment by AndrewVSutherland** [comment]
@jwj61, @JohnCremona Thanks!  As of commit 1b477b312c3006adea960c9d2d56dd58aaa19f2a the only remaining occurences of eval are in the following files, all of which are not part of the website (and should be migrated to new directories as part of #1837)

```
./lmfdb/elliptic_curves/import_ec_lfunction_data.py:1
./lmfdb/hilbert_modular_forms/recompute_AL.py:19
./lmfdb/hilbert_modular_forms/recompute_Galois_squarefull_forms.py:3
./lmfdb/hilbert_modular_forms/recompute_AL_modp.py:29
./lmfdb/hilbert_modular_forms/q_expansion.py:16
./lmfdb/hilbert_modular_forms/import_hmf_data.py:30
./lmfdb/hilbert_modular_forms/import_hmf_data_new_Galois_squarefull_forms.py:28
./lmfdb/ecnf/hmf_check_find.py:16
```

Closing.

**Comment by JohnCremona** [comment]
The first one in that list is now gone too, see #1843 (already merged just now).
