### ISSUE TITLE
Proxy error for some higher genus w/autos download

### ISSUE THREAD

**Issue by jenpaulhus** [LMFDB/lmfdb#1866]
(possibly related to #1079)

If I go here:
http://beta.lmfdb.org/HigherGenus/C/Aut/10.6-1.0.2-2-2-2-2-2-2-2-2-2.1
and click on the "Download Magma Code" or "Download Gap Code" buttons, I get a proxy error. I suspect the issue is that the download is creating a file with about 3280 generating vectors (and each vector creates about 10 lines of text in the download file).  I can modify the code to not allow downloads quite that big, but I wasn't sure what the cutoff should be, i.e. what "too many generating vectors" means.

A page like this:
http://beta.lmfdb.org/HigherGenus/C/Aut/10.10-1.0.2-2-2-2-2-2-5
downloads just fine (and that would be 1250 generating vectors between the two passports).

**Comment by AndrewVSutherland** [comment]
@jenpaulhus I can fix this for you (3280*10 lines is not that big and should be fine), your download code just needs a little tweaking to make it faster; I'll submit a PR for this shortly.
