### ISSUE TITLE
Data pull-request

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1878]
Please update the cloud version of transitivegroups.groups .  The changes here are in the "pretty" names of groups.  It fixes one typo (for 17T6), and adds names for half a dozen other groups.

Also please update the cloud version of artin.representations.  This fixes data errors for entries from about 60 fields.  The only visible change to users is in the displayed character values.  (It would affect L-functions, but these are hidden because they are high dimensional representations.  If we display algebraic L-function information, like Euler factors, those would be affected too.)

**Comment by AndrewVSutherland** [comment]
@jwj61 Both have been done.  I can see that http://www.lmfdb.org/GaloisGroup/17T6 changed, but can you take a look at artin.representations and make sure it has the changes you want?  Once I get confirmation I will delete the .old versions and close this.

**Comment by jwj61** [comment]
Yes, the artin representations have been updated.  Thanks.

**Comment by AndrewVSutherland** [comment]
@jwj61 BTW, I also updated the .rand index for artin.representations to include the new records you added.

**Comment by jwj61** [comment]
Thanks, although there were no new records.

**Comment by AndrewVSutherland** [comment]
@jwj61 Sorry, I should have said deleted not added -- the new version of the representations collection has 90940 records, but the old version had 90945 -- I hope that was intentional?

**Comment by jwj61** [comment]
Yes, one field was removed.  Fixing it in place was too complicated, but it could be redone on the next round of additions (which are waiting for a bug fix to make its way into magma).
