### ISSUE TITLE
ECNF magma and sage commands when a-invariants are in ZZ

### ISSUE THREAD

**Issue by danyasaki** [LMFDB/lmfdb#1885]
@JohnCremona 
On an ECNF page, when the elliptic curve has Weierstrass coefficients in ZZ, the magma and sage commands given to construct the elliptic curve will instead create the elliptic curve over QQ.  See
http://www.lmfdb.org/EllipticCurve/2.0.8.1/%5B121%2C0%2C11%5D/a/1
and click to see the magma and sage math commands.

In magma, the correct code for that example would be something like
E := EllipticCurve([K | 0, -1, 1, -7820, -263580]);
The quadratic field K is defined in the previous command, and pipe coerces the elements into K. I am sure something analogous should be available in sage.

**Comment by AndrewVSutherland** [comment]
@JohnCremona This is an easy change to code.yaml, I'll take care of it.

**Comment by JohnCremona** [comment]
Well spotted, thanks.
