### ISSUE TITLE
Wrong L-function for elliptic curves over number fields

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1896]
Bill Allombert reports
"LMFDB gives the L-function of E as
L(s,f)  = 1− 4^-s − 0.447·5^-s − 0.832·13^-s + 16^-s + 0.485·17^-s +...
but I do not think this is correct: it should be
L(s,f)  = 1− 0.447·5^-s − 0.832·13^-s + 0.485·17^-s +...
The true L-function of E have a trivial Euler factor at 2."
in relation to http://www.lmfdb.org/L/ModularForm/GL2/TotallyReal/3.3.148.1/holomorphic/3.3.148.1-356.1-a/0/0/ which is the L-function of http://www.lmfdb.org/EllipticCurve/3.3.148.1/356.1/a/1

**Comment by davidfarmer** [comment]
From the plot of the Z-function you can also see that something is wrong.

**Comment by JohnCremona** [comment]
I know that the plan is to precompute the L-functions of all ec/nf at some point.  We'll need to have code to do that incrementally since we are still expanding the collection.  It would be good to try to fix the bug in the on-the-fly computation sooner.

**Comment by AndrewVSutherland** [comment]
The wrong L-function is now hidden so I am closing this.
