### ISSUE TITLE
limit for the number of zeros of riemann zeta function

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1899]
Hello,

At the moment if someone tries to download a bunch of zeros, we run this code:
`lmfdb/lmfdb/zeros/zeta/zetazeros.py:69`

```
    if limit > 100000:
        # limit = 100000
        return """hello downloader. you hurt the server :(
                  get the data here: http://www.lmfdb.org/data/zeros/zeta/ --
                  code how to read it is here: http://code.google.com/p/lmfdb/source/browse/#hg%2Fzeros%2Fzeta"""
```

If we want people to have direct access to this data, we should rewrite this error message.
Perhaps, raise a 503 error, point users to github and http://lmfdb.warwick.ac.uk/data/zeros/zeta/.

If not, we should still rewrite the error message, and once again raise a 503 error with an error message explaining the problem.

**Comment by JohnCremona** [comment]
I thought we already had an Issue for this but I could not find it.  I did already make a branch to improve this page and the code behind it: https://github.com/JohnCremona/lmfdb/tree/zeros (needs work!)

**Comment by AndrewVSutherland** [comment]
It looks like this was fixed, see

http://www.lmfdb.org/zeros/zeta/?limit=1000000&N=1
