### ISSUE TITLE
Server error on degree 17 number field page

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1906]
http://www.lmfdb.org/NumberField/17.1.861526607800060221948166144.1 generates a server error.

Traceback is similar to one of the problematic pages listed in #1661 (which now works on prod but is not working on beta).

**Comment by jwj61** [comment]
This one seems to work on beta, so will definitely be fixed when the artin data on the cloud gets updated.  Of course, that should wait until the other bug gets fixed.

**Comment by AndrewVSutherland** [comment]
artin data update fixed this problem
