### ISSUE TITLE
Server error on degree 6 artin rep page

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1907]
http://www.lmfdb.org/ArtinRepresentation/6.2e6_3e11_43e6_607e3.9t10.1c1 throws a server error similar to the one that was occuring for the second problematic page listed in #1661 (integer too long).

**Comment by jwj61** [comment]
I think this is only superficially similar to #1661.  This time the error comes from deep in sage rather than at the level of lmfdb code.

**Comment by JohnCremona** [comment]
Test with a newer sage version?   7.3 released today.

**Comment by JohnCremona** [comment]
Just to confirm that the error still happens now, using 7.3

**Comment by jwj61** [comment]
I went to look at this more closely, running off of lehner, and the page worked.  This invokes sage 7.4, so it looks like that is the first version of sage which fixes the underlying bug.

**Comment by JohnCremona** [comment]
I think I have 7.4 ready to go on beta if we want to switch.

**Comment by JohnCremona** [comment]
Confirming: both master and beta branches run all tests fine with Sage 7.4.  Once master is pushed to beta the same will be true of prod.
