### ISSUE TITLE
Root number of classical modular form error

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1914]
From the feedback page:

On the page http://www.lmfdb.org/L/ModularForm/GL2/Q/holomorphic/1/18/1/a/0/
there may be an error on this page (or maybe I'm just misunderstanding notation).  This form has weight $k \geq 2 \bmod 4$, so the sign in the functional equation is $(-1){k/2} = -1$, so $\epsilon$ should equal $-1$ and the central value $L(1/2, f)$ should be zero.

Please send feedback (like that it is being worked on, if it has been resolved, etc.) to martin.dickson34@gmail.com

**Comment by jvoight** [comment]
Definitely an issue here.  Magma confirms:

> S := CuspidalSubspace(ModularForms(1, 18));
> f := Newforms(S)[1][1];
> Lf := LSeries(f);
> CentralValue(Lf);
0.000000000000000000000000000000
> LTaylor(Lf, 9, 1);
0.649604896356279588838547646141*$.1 + O($.1^2)

**Comment by davidfarmer** [comment]
Has been fixed, and I replied to the person who brought it to our attention.
