### ISSUE TITLE
Search by polynomials for hyperelliptic curves

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#1930]
Preparing the slides for a talk, I wanted to give the LMFDB label for the genus 2 curve
y^2=x^5-x+1
and I noticed that there is no way to search by polynomials on the genus 2 browse page.
In this case the label is 45904.d.734464.1 and I could only obtain it after computing the conductor of the Jacobian in magma.

I think that searching by polynomials should be something to think about (model y^2+g (x)y=f (x), search on f and g as list of coefficients) since it is avaliable for elliptic curves.

**Comment by JohnCremona** [comment]
Good idea.  What if the polynomials enteted define a curve not in the database but only isomorphic to a db curve?  For number fields we apply polredabs and for ec/Q we also normalise before searching.

**Comment by nmascot** [comment]
I agree with Samuele !

**Comment by AndrewVSutherland** [comment]
Magma has a ReducedMinimalWeierstrassModel function (implemented by Stoll), but as far as I know Sage does not support this.  Having said that, it would be easy to identify twists by computing Igusa invariants and then check for isomorphism locally.

**Comment by nmascot** [comment]
@JohnCremona : If the user inputs [g(x),f(x)], we could first complete the square to get a model y^2=F(x), do the same for curves in the database (cf. #1522), and then we only have to tell when polynomials are equivalent modulo PGL2.

**Comment by AndrewVSutherland** [comment]
@nmascot That is not enough in general (think of curves with lots of automorphisms), and to efficiently do this you would need to pick a unique representative and store it.  But I think the Igusa invariants are already enough to reduce to just a handful of curves to check.

**Comment by edgarcosta** [comment]
I also think computing Igusa invariants is a better approach.

Further, users should be able to input:
* f(x)
* [g(x), f(x)]
* equation
the last one might be tricky, but seems the most natural

**Comment by AndrewVSutherland** [comment]
@edgarcosta You can forget about the last one, which we don't even support for elliptic curves (try showing that the polynomial returned by ClassicalModularPolynomial(23) (which takes several pages to print) defines the same curve as y^2= (x^3 − x + 1)(x^3 − 8x^2 + 3x − 7); both are models for X0(23)).

**Comment by edgarcosta** [comment]
I agree, but at the same time we have that for number fields.

If you put some random polynomial of degree 100 obviously will timeout
before telling you anything, but that didn't stop us.

**Comment by JohnCremona** [comment]
I suggesyed Igusa invariants to Samuele in person and Tim D told me of Stoll 's reduction.  If it is not hard to implement and the output is canonical that might work as well as polredabs. 
Of course Sage is missing much more genus 2 stuff than this.

**Comment by AndrewVSutherland** [comment]
@JohnCremona, @edgarcosta If we have a hyperelliptic model then I agree it wouldn't be hard to do this (modulo adding some missing functionality to Sage).  But if we want to be able to handle arbitrary equations defining genus 2 curves (or even genus 1 curves) as Edgar suggests there is more work to do, and at least in the genus 2 case I'm not sure its something we could feasibly do on the fly, even when the equations is reasonably small.

**Comment by JohnCremona** [comment]
I absolutely do not think we should offer anything like arbitrary equations for genus 2, or elliptic curves, or anything else!

**Comment by edgarcosta** [comment]
This is working partially, as our check for magma starting up still fails on www.lmfdb.org once in a while.
Perhaps is worthwhile to remove the check, given that we expect every machine to have magma

**Comment by AndrewVSutherland** [comment]
Addressed by #4935.
