### ISSUE TITLE
SSL module not available

### ISSUE THREAD

**Issue by JRSijsling** [LMFDB/lmfdb#1941]
Hello,

Recently I got an actual desktop for use in my office. I installed a Linux distribution on it (elementary 0.4, based on Ubuntu). One of the first things I did was to try and install Sage after installing all needed dependencies. To my amazement, that actually worked without any hitch whatsoever. The problems arose when I tried to go further so as to be able to work on the LMFDB.

Developing the LMFDB has a number of prerequisites. Among them is extending Sage by

sage -pip install --upgrade pip
sage -pip install --upgrade pymongo

This fails. I get

jrsijsling@JRS-ThinkCentre-M800z:~/Programs/sage-7.4$ ./sage -pip install --upgrade pip
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
Requirement already up-to-date: pip in ./local/lib/python2.7/site-packages
jrsijsling@JRS-ThinkCentre-M800z:~/Programs/sage-7.4$ ./sage -pip install --upgrade pymongo
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting pymongo
  Could not fetch URL https://pypi.python.org/simple/pymongo/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement pymongo (from versions: )
No matching distribution found for pymongo

I do have OpenSSL, and the notebook version of Sage works for me. And my version of Python 2.7 did in fact have the ssl module. So I do not know what causes this. The following attempts at a solution have failed:

* Fully upgrading Python (pip, pymongo, setuptools) and rebuilding Sage;
* Using Sage 7.3 instead;
* Running ./sage -i openssl and trying again;
* Using the Sage shell.

Running Python (2.7.10, which should have ssl installed internally) inside the Sage shell gives

(sage-sh) jrsijsling@JRS-ThinkCentre-M800z:sage-7.4$ python
Python 2.7.10 (default, Oct 28 2016, 09:09:23) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jrsijsling/Programs/sage-7.4/local/lib/python/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl

Any ideas?

Thanks in advance,
Jeroen

**Comment by JohnCremona** [comment]
That's a Sage issue and you should ask on sage-support.

John

**Comment by JRSijsling** [comment]
Thanks John, I did that. I think that I found a solution in the meantime, namely to use pyopenssl instead:

./sage -i pyopenssl
./sage -f python2
make ssl

I could add this as a remark to the "Getting Started" if you think that this is useful, since more people could encounter this problem. It is not a Sage bug; the gist of all of this is that for my current operating system "Getting Started" simply misses a needed dependency. Why that should case things to fail on the new system whereas on the old one things were fine I do not know; but certainly this is in fact an LMFDB issue, not a Sage issue.

Best,
Jeroen

**Comment by JohnCremona** [comment]
On 28 October 2016 at 17:09, Jeroen Sijsling <notifications@github.com>
wrote:

> Thanks John, I did that. I think that I found a solution in the meantime,
> namely to use pyopenssl instead:
>
> ./sage -i pyopenssl
> ./sage -f python2
> make ssl
>
> I could add this as a remark to the "Getting Started" if you think that
> this is useful, since more people could encounter this problem. It is not a
> Sage bug; the gist of all of this is that for my current operating system
> "Getting Started" simply misses a needed dependency. Why that should case
> things to fail on the new system whereas on the old one things were fine I
> do not know; but certainly this is in fact an LMFDB issue, not a Sage issue.
>

The reason is probably that if you have certain packages onstalled on your
system then you don't need to install them via Sage; and the reason that
Sage does not do that automatically on build is because of licensing issues.

I agree that mentioning this in GettingStarted would be helpful -- feel
free to do so and make pull request!

John

**Comment by JRSijsling** [comment]
Will do!

Best,
Jeroen
