### ISSUE TITLE
Bug in parsing user input

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1946]
There seems to be a problem with parsing the input field for discriminants of number fields.  It shows up if the range spans 0 (e.g., -10-1 for -10 to 1).

**Comment by AndrewVSutherland** [comment]
Fixed in #1947

**Comment by JohnCremona** [comment]
Pushed to beta, can be closed in 11 mins if it works OK at beta.lmfdb.org (or do we keep issues open until pushed to master?)

**Comment by jwj61** [comment]
I think it could have been closed once fixed.
