### ISSUE TITLE
"search again" placement

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1951]
It seems that there is not a default placement for "search again"/"refine search".

Perhaps we should stick to one.

Some concrete suggestions:
In genus 2 curves, the placement is quite counter-intuitive:

<img width="913" alt="screen shot 2016-12-06 at 16 44 21" src="https://cloud.githubusercontent.com/assets/322822/20945094/e1bdedb4-bbd3-11e6-92f7-d1a7b02f15b3.png">

In elliptic curves over a number field, perhaps should resemble a bit more elliptic curves over QQ, and it needs some vertical space:

<img width="1198" alt="screen shot 2016-12-06 at 16 45 35" src="https://cloud.githubusercontent.com/assets/322822/20945100/e7188198-bbd3-11e6-91b2-1b02c73393eb.png">

Cheers,
Edgar

**Comment by AndrewVSutherland** [comment]
Other than that I agree that the search again button on the ECNF page should be slightly lower down, I'm not sure I see the difference here.  In both cases the button is at the bottom on the left.  What exactly is your concrete suggestion?  Where do you think the button should be?

**Comment by edgarcosta** [comment]
In my opinion, it should be below the all the options, not next to qbar simble, as in global Number Fields search results (which perhaps should be the role model):

<img width="450" alt="screen shot 2016-12-08 at 10 06 32" src="https://cloud.githubusercontent.com/assets/322822/21015049/6c51a366-bd2e-11e6-9257-589a4315d98f.png">

For example, Elliptic curves over QQ also places the button on the left, and with a different text:

<img width="458" alt="screen shot 2016-12-08 at 10 06 13" src="https://cloud.githubusercontent.com/assets/322822/21015107/a8418b84-bd2e-11e6-9b8e-f14d22b963c3.png">
