### ISSUE TITLE
Missing L-function data for elliptic curves of conductor > 380000

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1956]
Since L-function information for elliptic curves /Q was precomputed in March 2016, the database has been extended from conductor bound 380000 to 400000.  Now, if you go to a page such as http://www.lmfdb.org/EllipticCurve/Q/380002/a/1 and click on the L-function link you get a server error.

I propose to deal with this in two steps: (1) change the code so that the L-function link only appears when the data exists.  This will stop the server crashing.  (2) Upload the extra L-function data once Andy Booker has computed it.

**Comment by AndrewVSutherland** [comment]
Sounds like a good plan.

**Comment by JohnCremona** [comment]
Part (2) is under way, data currently being updated.  As of right now http://www.lmfdb.org/L/EllipticCurve/Q/380002.a/ does show an error but it is a clean one not a server crash, so (1) has either been done or is no longer necessary.  I will close this once the upload is complete and the updated database collections are copied from beta to cloud.

**Comment by JohnCremona** [comment]
The data upload is complete to beta.  The new data is in the collections Lfunctions and Instances.

**Comment by AndrewVSutherland** [comment]
Do you want the data copied to the cloud now?

**Comment by JohnCremona** [comment]
Yes please.  Just those 2 collections.

**Comment by AndrewVSutherland** [comment]
OK, the new Lfunction data is now up on the cloud and looks good, closing.
