### ISSUE TITLE
Check arithmetically equivalent values

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1961]
A data error was found in which transitive groups admit arithmetically equivalent fields.  Data through degree 15 has been checked -- higher degrees should also be checked.

**Comment by jwj61** [comment]
I forget if this is the right place for a data pull request, but the transitive group database just had errors corrected, so should be copied to the cloud.

**Comment by AndrewVSutherland2** [comment]
I can take care of this.

**Comment by AndrewVSutherland** [comment]
@jwj61 The production database has been updated, the 8T32 fields now look correct.  I'll leave the issue open until you finish checking the higher degrees.

**Comment by jwj61** [comment]
The values have now been checked through degree 23, and I found the entry-error which led to the wrong values in degree 8.
