### ISSUE TITLE
Selberg data doesn't always match the functional equation

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1971]
For example, 
http://www.lmfdb.org/L/EllipticCurve/Q/102861.b/
and
http://www.lmfdb.org/L/Genus2Curve/Q/838854/a/
From the functional equation we have \nu_i = 0, but when I look into the Selberg data I see \nu_i = 1/2.

**Comment by davidfarmer** [comment]
To find the Selberg parameters, look at the functional equation in the
analytic normalization, which relates s to 1-s.

So, the 1/2 is correct for elliptic curves.

**Comment by edgarcosta** [comment]
Thank you! That makes sense.

I find it a bit confusing having data displayed on the page using different conventions.
Perhaps in http://www.lmfdb.org/knowledge/show/lfunction.selbergdata one should mention that these parameters are for the normalization s <--> 1 - s.

**Comment by davidfarmer** [comment]
I added the words "analytically normalized" in front of
"functional equation" in that knowl.  (I did this on beta,
so I guess it will migrate to production, assuming I remember
the current procedure.)

**Comment by edgarcosta** [comment]
Thank you!

**Comment by edgarcosta** [comment]
Yes, it will be pushed to the cloud automatically.
