### ISSUE TITLE
"Pull request" for number field data to be copied to the cloud

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1981]
I updated the number field database with a smattering of high degree fields from Kluners-Malle, and added some siblings for sextic S6,A6,S5,A5 fields.  Updated the collection for picking a random field as well.  When copied to the cloud.

**Comment by AndrewVSutherland** [comment]
Copying now...

**Comment by AndrewVSutherland** [comment]
OK the data is there now.  Can you take a look and let me know if everything is as it should be?  I will then delete the old copy and close this issue.

BTW, with this update do we now have at least one example of a field with every transitive group of degree < 20 (the range covered by the Kluners-Malle database)?  If so, it might be worth updating the completeness knowl to mention this.

**Comment by jwj61** [comment]
Looks good.

I will double check on the Galois examples coverage.  Kluners provided examples through degree 23.  The problem is getting them processed (at least polredabs and nfinit if not bnfinit).
