### ISSUE TITLE
missing isogeny class data for elliptic curves over Q

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1985]
The collection of elliptic curves over Q is supposed to include for each curve the "isogeny matrix" of degrees which are used to populate pages such as http://beta.lmfdb.org/EllipticCurve/Q/300027/l/.  However I just discovered that only half of the isogeny classes have this stored; this is invisible on the website since the code recomputes when it is missing.

I am currently filling in the missing data, which will speed up the display of isogeny class pages for conductors over 230000.  When that is done on the beta database, I will copy it to the cloud.  At the same time there will be some minor code changes, since when I adapted the code to not have to do any computation on the fly I did so systematically for individual curves but not for isogeny classes.

**Comment by JohnCremona** [comment]
The newcurves collection (in the elliptic_curves databse) is a now copy of curves with the isogeny_matrix fields filled in for every curve (though it is the same for each curve in the class), together with a new field isogeny_degrees giving a sorted list of the distinct degrees of cyclic isogenies.

There will soon be a new branch which uses this, and no longer uses the EllipticCurve() constructor in displaying an isogeny class, saving time.

The new isogeny_degrees field will allow searching for elliptic curves with a given isogeny degree, as requested by Elkies.  These degrees should probably then be listed on an individual curve's web page.

**Comment by JohnCremona** [comment]
The branch isogs at https://github.com/JohnCremona/lmfdb uses the newcurves collection and eliminates all use of the EllipticCurve constructor for isogeny classes over Q.  It also shows isogeny degrees on an elliptic curve's home page.

Next steps after testing that branch:

1. Merge that branch to master and beta, not prod;
2. Copy newcurves collection to cloud;
3. Merge branch into prod.

Then in due course the newcurves collection should be renamed curves and the code changed again to change the name newcurves --> curves (in one place).

**Comment by edgarcosta** [comment]
Sounds good to me.

**Comment by JohnCremona** [comment]
The new collection is in fact called curves.new (now).

**Comment by JohnCremona** [comment]
There was a glitch in permuting the isogeny matrices when uploading from the source data (which uses Cremona labels) .  For an example, see class 14a.  I am fixing this; and the revised new collection will not have a new name, i.e. the previous collection curves will be renamed 'curves.old' while the new one will be just 'curves'.  Since the old code works fine with the new data there was no need for a new collection name.

**Comment by JohnCremona** [comment]
This can be closed once #1986 is merged.  The new data is already on the beta database.

**Comment by AndrewVSutherland** [comment]
The PR has been merged, and both the code and the new data are now in production -- closing.
