### ISSUE TITLE
Classical modular forms Gamma1(49) weight 3

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#1991]
This space returns an error
http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/49/3/3/

**Comment by AndrewVSutherland** [comment]
This is possibly related to #1533, but it may just be a timeout on an operation that takes more than 30 seconds, have you tried running it in debug mode?

**Comment by sanni85** [comment]
In debug mode it works, after waiting for some (long) time. I think the problem is the display of the q-expansion.

**Comment by AndrewVSutherland** [comment]
I don't think this is a new issue then, it should probably be merged with either #1248 or #1533.

**Comment by edgarcosta** [comment]
It works in the new version: http://cmfs.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/49/3/h/

**Comment by AndrewVSutherland** [comment]
Addressed by #2717, see http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/49/3/h/.
