### ISSUE TITLE
Artin representations, Dirichlet characters and links

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#1994]
Looking at 1 - dimensional Artin representations we (@pjbruin, @nmascot  and me) noticed that:

- the related objects box contains a link to "Corresponding Dirichlet character" while it should be "Dirichlet character $\chi_q(n,\dot)$" for consistency with other pages;
- in the body of the page the Dirichlet character should be given with a link to the Dirichlet character page;
- there is no link back from the L-function page to the Artin representation;
- there is no link from Dirichlet characters to Artin characters (related object box).

For higher dimensional Artin representations, the determinant should be linked to a 1-dimensional Artin representation first.

**Comment by nmascot** [comment]
The first two points are fixed by pull request #1995 **for representations of dimension 1 only** (because for higher dimension, the determinant link should be to the **Galois character**, not the **Dirichlet character**, and I do not know how to do that)

**Comment by jwj61** [comment]
What do you mean by the Galois character.  Do you mean the corresponding 1-dimensional Artin representation?

**Comment by nmascot** [comment]
@jwj61 : Yes, exactly.

**Comment by pjbruin** [comment]
As far as I can see, the current status is as follows: a higher-dimensional Artin representation now has a link to its determinant as a 1-dimensional Artin representation.  Between 1-dimensional Artin representations, Dirichlet characters and L-functions, the following links exist:
- from 1-dim. Artin rep. to Dirichlet char.
- from 1-dim. Artin rep. to L-function
- from Dirichlet char. to L-function
- from L-function to Dirichlet char.

The following links still seem to be missing (points 3 and 4 from the first comment on this page):
- from Dirichlet char. to 1-dim. Artin rep.
- from L-function to 1-dim. Artin rep.

For example, a link to http://localhost:37777/ArtinRepresentation/1.7.3t1.1c1 should be added on both http://localhost:37777/Character/Dirichlet/7/2 and http://localhost:37777/L/Character/Dirichlet/7/2/.

**Comment by jvoight** [comment]
Also, there's a link from the Artin representation to the number field in the friends but not vice versa, e.g. http://beta.lmfdb.org/ArtinRepresentation/3.229.4t5.1c1 has a friend link to http://beta.lmfdb.org/NumberField/4.0.229.1, but only at the bottom of the page are there Artin links.  It's OK to have it in two places, but for consistency across pages I think the Artin L-functions should be solidly in the friends zone.

**Comment by AndrewVSutherland** [comment]
We should plan to address this in the Artin reps workshop in August 2019.

**Comment by AndrewVSutherland** [comment]
Fixed by #3258, which I will push to beta momentarily.
