### ISSUE TITLE
non-existing Sage command displayed for Dirichlet characters

### ISSUE THREAD

**Issue by pjbruin** [LMFDB/lmfdb#1997]
When clicking "Show commands for SageMath" on the page for a Dirichlet character (e.g. http://www.lmfdb.org/Character/Dirichlet/65/14 or the corresponding page on beta.lmfdb.org), the resulting command is

sage: ['H = DirichletGroup_conrey(65)', 'chi = H[14]']

However, there is no command DirichletGroup_conrey in Sage.

**Comment by JohnCremona** [comment]
That function does exist in the lmfdb code but perhaps needs an explocit import statement.

**Comment by JohnCremona** [comment]
But of course you are right that this should not be displayed as if it were standard Sage.

**Comment by JohnCremona** [comment]
See  https://trac.sagemath.org/ticket/12494 for an old Sage trac ticket for this.  To be revived perhaps?

**Comment by JohnCremona** [comment]
I am making a correction to this (and some other code on the same page).  I will add a comment that a non-standard Sage package needs to be installed, if I can, by editing lmfdb/WebCharacter.py.

**Comment by JohnCremona** [comment]
PR #1999 fixes this and a bit more.

**Comment by davidfarmer** [comment]
Fixed by #2083
