### ISSUE TITLE
Variable on siegel page not defined

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2019]
From the feedback page (submitted by Brian conrey@aimath.org):

I clicked on Siegel modular forms; then ""random page"" and got to

http://www.lmfdb.org/ModularForm/GSp/Q/Sp8Z.16_Ikeda/

It is clear that ""a"" stands for something important on this page but it doesn't seem to be defined anywhere on the page.
----------------
I assume a is a root of the field equation, but don't see where it says that.

**Comment by AndrewVSutherland** [comment]
Yes, I believe a is meant to be a root of the field equation, I will confirm and fix this.

**Comment by AndrewVSutherland** [comment]
Fixed by PR #2020
