### ISSUE TITLE
Wrong dirichlet coefficients

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2045]
Hello, 

I'm aware that one of our major goals is to serve these L-functions from the DB.
However, at the moment, I believe that we are displaying some wrong Dirichlet coefficients
precisely, the ones coming from bad primes.
And if that is the case, then we should fix it meanwhile.
e.g.:

http://www.lmfdb.org/L/ModularForm/GL2/TotallyReal/2.2.5.1/holomorphic/2.2.5.1-1724.2-d/0/0/

take p = (2), it is a bad prime, it's eigenvalue is  -1, thus
```1/ (1 - 4^(-s)) = 1 + 4^(-s) + 16^(-s) + 64^(-s) +...```
under the analytic normalization, 
```1/ (1 - 4^(-s) / 2)  = 1 + 0.5 * 4^(-s) + 0.25*16^(-s) + 0.125* 64^(-s) + ..```

However, the Dirichlet coefficients that we present for 16 and 64 are respectively − 0.750 and − 0.875.

Cheers,
Edgar

**Comment by davidfarmer** [comment]
Closing, because this will be addressed by this week's work on putting these L-functions into the database.

**Comment by edgarcosta** [comment]
@danyasaki noticed that the root of the issue is related how primes are stored in different formats in the DB

**Comment by edgarcosta** [comment]
@davidfarmer  can you reopen the issue?

**Comment by jvoight** [comment]
Fixed by #2108
