### ISSUE TITLE
Add sage command for L-series to elliptic curve page

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#205]
I think item 43 in the feedback spreadsheet is pointing out that on the home page of an elliptic curve, there are links at the top to show for example sage commands.  If you do that, you get sage commands for many things, but not for L(E,1), and there is a sage command for that, so it could be put in.

**Comment by JohnCremona** [comment]
Pull request coming up:  added this plus several new Sage/Pari/Magma commands, fixed a bug (the number displayed is L^{r}(E,1)/r! but the r! was not shown) and replaced the Magma logo with a link which works.

**Comment by JohnCremona** [comment]
Fixed in pull request #238 so closing.
