### ISSUE TITLE
Artin data "pull request"

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2050]
Please copy data from artin (collections representations, representations.rand, field_data) to the cloud.  There is a substantial amount of new data.  Once done, I will update the data-extent knowl.

**Comment by AndrewVSutherland** [comment]
Done.  Let me know once you are satisfied that everything looks OK and I will delete the old versions.

**Comment by jwj61** [comment]
Looks good.  Thanks.
