### ISSUE TITLE
local field data pull request

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2051]
Can you pull collections newfields and newfields.rand to the cloud from the localfields database.  There is no effect right now, but then they will be there when the current code makes it to the main server.

**Comment by AndrewVSutherland** [comment]
Are these collection names permanent or just temporary ones to be used during the transition to the new code?  (in the former case I will add them to the db-collections.txt file used by update-cloud-db.sh).

**Comment by jwj61** [comment]
Temporary

**Comment by AndrewVSutherland** [comment]
Done.
