### ISSUE TITLE
API whitelist

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2053]
Hello,

Should we restrict the API queries to indexed keys?
Not many people use the API, but a bad script with a misspelled key on a big collection, might bring the mongodb server to halt.
For example, just like in #1599 or https://jira.mongodb.org/browse/SERVER-24833

Cheers,
Edgar

**Comment by JohnCremona** [comment]
That sounds sensible -- but it would be useful to see a log of such failed requests, since some might be sensible (not typos) and a hint that a new index is worth adding.

**Comment by edgarcosta** [comment]
Great. Could you label it as a feature request?

I think this would be Step 0 for a possible interface for Sage.
