### ISSUE TITLE
Problem with delta function home page

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#206]
From Kevin Buzzard through feedback form:

http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/

and then to to the bottom text box on the page (under "Find a specific cusp form from the database") and type the suggested example ("1.12") then I get taken to the URL mentioned above, but the q-expansion I see definitely isn't the Delta function (which starts q-24q^2+...; I see q-2q^2+18q^3...), the Satake parameters look very fishy, and if I try and download Fourier coefficients then I get a server error, which led me to this feedback page.

Preferably, reply to Kevin that we are working on it, and again when it is fixed.

**Comment by JohnCremona** [comment]
As of now (2015-07-20) the web page for Delta is fine but downloading the Fourier coeffs gives an almost blank file.  This should be checked again after Fredik's refactoring is finished.

**Comment by JohnCremona** [comment]
This is fixed (even the download of coefficients).
