### ISSUE TITLE
hmf: large eigenvalue display when asking for more

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#2073]
In HMF pages, the large eigenvalues are not displayed. However, when one changes the number of eigenvalues to display (for instance to check for which primes there are Hecke eigenvalues in the DB), all the eigenvalues get displayed and the page takes a long time to render. Maybe we should also hide them in this case?

Example: /ModularForm/GL2/TotallyReal/3.3.321.1/holomorphic/3.3.321.1-293.1-b

**Comment by AurelPage** [comment]
This should be labelled hmf.

**Comment by SallyKoutsoliotas** [comment]
Also, defining polynomial should be able to wrap or, if there is a slider, then the slider should be made more obvious.

**Comment by AurelPage** [comment]
@SallyKoutsoliotas Ok, but that seems to be a different issue to me. Open a new one?
