### ISSUE TITLE
Document nfideals numbering scheme

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2081]
For example, adding knowls to
/Character/Hecke/3.3.81.1

**Comment by JohnCremona** [comment]
OK, I will write the knowl, after the next push from master to beta.  @pascalmolin will do more work on his character recoding before it is ready to be pushed to beta.

**Comment by JohnCremona** [comment]
A first draft is at http://beta.lmfdb.org/knowledge/show/nf.ideal_labels.  It will necessarily refer to the preprint we have written which will be posted to ArXiV after some editing.

**Comment by JohnCremona** [comment]
The knowl can be edited further but now that it exists I think we can close this.
