### ISSUE TITLE
List of LMFDB principles

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2082]
The LMFDB is based on some fundamental principles which should be documented
and made visible on a public part of the website (or maybe on GitHub).  Some of
those principles are:

1. All mathematical objects have a home page.
2. Home pages should have basic information at the top, with successively specialized information in the lower portion of the page.  Home pages should contain a meaningful picture (if possible),
links to related objects, links to background information, and appropriate credit to those who
contributed to generating the data.
3. Each home page lives at a mathematically meaningful, permanent URL.  The URL does not have to be unique.
4. Home page URLs should prioritize objects, then groups, then fields, then parameters.  If necessary, objects with the same parameters are given a letter string indicating (if possible) a
canonical ordering.
5. The URL of the home page of the L-function of an object is obtained by prepending "L/" to the URL of the object.
6. Knowls on every page allow non-experts to learn about technical terms.
7. Each class of objects has a browse and search page.  The upper portion of that page affords browsing, and the search form should be visible without scrolling.

David Farmer will create that page, after a comment period on this issue.

Good comments include: additional principles and improved wording of the listed principles.

**Comment by AurelPage** [comment]
Minor wording question: is "all mathematical objects" too generic? We obviously don't want homepages for elementary objects such as polynomials or, as mentioned yesterday, finite fields. If there is a short formulation of which mathematical objects have a homepage in the LMFDB it would be nice to add it. Principle 5 suggests that an object has a homepage if and only if it has an L-function (possibly a local one, i.e. a single Euler factor, e.g. Abelian varieties over finite fields or Local fields). Is this too restrictive?

**Comment by sanni85** [comment]
Maybe in 5, say something like "whenever it exists"... mod l representations do not have any L-function.

**Comment by alinabucur** [comment]
Do we have a principle for dealing with the same L-function arising in two different ways?

**Comment by kedlaya** [comment]
Re 3: the requirements that the URL be permanent *and* mathematically meaningful do not necessarily have to be correlated. For example, in the Stacks Project every piece of text has a permanent URL, but these are assigned purely serially. That said, in that context (a large piece of mathematical writing) the concept of "mathematically meaningful" doesn't have any natural analogue.

**Comment by roed314** [comment]
Now that the guidelines have been merged, can this issue be closed?

**Comment by AndrewVSutherland** [comment]
Yes.
