### ISSUE TITLE
Consistent colors in headings

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2085]
Knowls in section headings are green, while the rest of the heading is black.

It would be better if the headings had one consistent color.
(It was that way before some CSS refactoring.  I seem to recall this color change was
an unintended consequence.)

**Comment by roed314** [comment]
I believe that this is not an issue with the new color scheme, and can be closed.

**Comment by AndrewVSutherland** [comment]
Agreed!
