### ISSUE TITLE
L-function of Trivial Artin representation

### ISSUE THREAD

**Issue by SallyKoutsoliotas** [LMFDB/lmfdb#2088]
Linking to the L-function friend from the Artin representation:
/ArtinRepresentation/1.1.1t1.1c1
gives
/L/Riemann/
However, adding a /L in front gives a different homepage:
/L/ArtinRepresentation/1.1.1t1.1c1/

Shouldn't this redirect to the /L/Riemann/ ?

**Comment by AndrewVSutherland** [comment]
Closed via #3115.
