### ISSUE TITLE
Typo in three knowl names

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2091]
There are three knowls of the form charcter.* which should be character.* .
They are referred to once each, in ./lmfdb/characters/templates/CharGroup.html .
These should be copied to new knowls, then the references changed, and finally the old knowls deleted.

**Comment by SallyKoutsoliotas** [comment]
I will try to do this.

**Comment by pascalmolin** [comment]
I already fixed the wrong calls (in a character template), this will be in
a next pull request.

However I do not know how to change the db entries.

Pascal

2017-06-14 20:52 GMT+01:00 SallyKoutsoliotas <notifications@github.com>:

**Comment by JohnCremona** [comment]
@pascalmolin I'm afraid you'll have to make 3 new knowls and then delete the originals.  I do that by having 2 tabs open so I can cut and paste the text.

**Comment by pascalmolin** [comment]
Ok, no problem, I'm doing this.

Pascal

2017-06-14 21:48 GMT+01:00 John Cremona <notifications@github.com>:

**Comment by alinabucur** [comment]
@pascalmolin, did you do this? can we close the issue?

**Comment by christellevincent** [comment]
Everything is done except deleting the knowls with typos

**Comment by AndrewVSutherland** [comment]
We should wait until the code is on prod before deleting the knowls, I can take care of this.
