### ISSUE TITLE
test_ecnf fails

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#2093]
test_ecnf currently (commit d36a99b73a5a66be3ced949d87a40, 13/06/2017) fails on master. This was not the case yesterday (12/06/2017).

**Comment by JohnCremona** [comment]
It may just be the usual test for a missing curve which fails when the curve is found and uploaded.   Ill take a look.

**Comment by JohnCremona** [comment]
Fixed by PR #2114
