### ISSUE TITLE
nearby objects

### ISSUE THREAD

**Issue by pascalmolin** [LMFDB/lmfdb#2095]
Currently the website provides a "Nearby objects" lady gaga box in exactly two situations:
- L functions of Dirichlet characters http://beta.lmfdb.org/L/Character/Dirichlet/27/5/
- L functions of GL2 Maass forms http://beta.lmfdb.org/ModularForm/GL2/Q/Maass/4f56985288aece2afe000045
which are coded in the function set_navi in lfunctions/main.py

In the case of Maass form, the labels are not very informative (fnext/fprev).

I think there are two reasonable options:
- completely remove this box
- try to extend this notion of "nearby" to other families of objects.
I would favor the first one (and just in case I have the commit doing it).

**Comment by AndrewVSutherland** [comment]
I would argue for removing it.  As you note it is implemented in very few places, and for many objects in the LMFDB I'm not sure there is really a mathematically meaningful/useful notion of "nearby objects" (certainly not at the level of relevance that would warrant highlighting them in properties box).

**Comment by davidlowryduda** [comment]
I would also say that we remove it.

**Comment by AndrewVSutherland** [comment]
I can see utility for this feature on the Maass form pages, but I agree the f_next, f_prev labels are not very helpful (showing the next/prev spectral parameter would be more meaningful).  In any case I have submitted a PR to hide these boxes so we can close this issue.  If someone wants to create a feature request with an explicit proposal for how these boxes should work across the LMFDB, please do so.

In the context of the L-function pages, any notion of nearby object needs to be origin independent (i.e. intrinsic to the L-function), which is not true of the current (very limited) implementation of nearby objects in the two special cases noted above.

**Comment by AndrewVSutherland** [comment]
Closed via #3116
