### ISSUE TITLE
Some permuted Hecke eigenvalues for HMFs over certain fields

### ISSUE THREAD

**Issue by danyasaki** [LMFDB/lmfdb#2105]
Certain Hecke eigenvalues were permuted for HMFs over certain fields.  There are issues with the HMFs over the following fields:
4.4.1600.1
4.4.2304.1
4.4.4225.1
4.4.7056.1
4.4.7168.1
4.4.7225.1
4.4.9248.1
4.4.11025.1
4.4.12400.1
4.4.12544.1
4.4.13824.1
4.4.14336.1
4.4.17424.1
5.5.180769.1
6.6.1134389.1
4.4.19600.1
6.6.1528713.1
6.6.905177.1
The issue was in an upload script.  The a_pp s were reordered, but not the list of primes.

**Comment by jvoight** [comment]
The scripts we used to fix the issue are in #2106.  The data should now be correct on beta, which means @JohnCremona you should be able to find all remaining elliptic curves.  :)

Presumably we'll move the MongoDB from beta to master at the end of the week?  If so, this issue can be closed.

**Comment by JohnCremona** [comment]
We can copy the collection to the cloud at any time -- but it is a large collections so best done after the workshop ends, and in the middle of the night.

**Comment by JohnCremona** [comment]
This was done soon after the last post.
