### ISSUE TITLE
.context deprecated in jQuery

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2124]
.context is deprecated in jQuery 1.10.  It is used in the animation of hiding the properties box,
so that needs to be changed if we wish to use jquery-latest (or a specific recent version).

**Comment by AndrewVSutherland** [comment]
At this point there do not appear to be any references to .context in any of our code or templates, the search grep -R  "\.context[^_u]" finds no matches (the [^_u] excludes matches to .context_processor  and .contextualize which are fine).
