### ISSUE TITLE
Refactoring utilities

### ISSUE THREAD

**Issue by davidlowryduda** [LMFDB/lmfdb#2128]
In #2112, I tried to import a `truncatenumber` from lmfdb.lfunctions.Lfunctionsutilities.py to use to display Maass form coefficients with a correction factor. However, due to the imports within Lfunctionsutilities.py and within the Maass form files, this causes a circular import and cannot be done well.

The `truncatenumber` function is useful for database collections and python modules outside of L-functions. Similarly, there are other utility functions and utility files throughout the site. Often, these were created for a local purpose, but contain utilities that would be useful on a wider scale.

It would be a good idea to organize and refactor the utilities into a way that lets them be used and checked easier. I am beginning to work on this now.

**Comment by AndrewVSutherland** [comment]
@davidlowryduda Is there more you want to do or can this be closed now?

**Comment by davidlowryduda** [comment]
I intend on revisiting the utilities, but I think it is not worth keeping the issue open just for my memory. I'm closing this issue.
