### ISSUE TITLE
Decorate the cursor with max_time_ms

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2158]
I believe we should decorate the cursors associated with the API (and perhaps others) with max_time_ms (see: http://api.mongodb.com/python/current/api/pymongo/cursor.html#pymongo.cursor.Cursor.max_time_ms), as certain queries might be painful on the DB side, and even if the client dies after 30s, the mongodb server will keep processing the query.

**Comment by AndrewVSutherland** [comment]
This is an excellent idea.

**Comment by JohnCremona** [comment]
+1
