### ISSUE TITLE
Use javascript to help select typeset math in a form for pasting

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2171]
A long-standing issue is that things like polynomials appear in the lmfdb in typeset form, and it is not easy to copy and paste them to sage/magma/pari/etc.  Our solution has been to tell people to click on "show sage commands" where the object may appear in "input form".  But, in many cases, the thing may not be appear, or there is no "show sage commands", and this is not obvious to the user.

On Kluners-Malle number field web site, if you click on a typeset polynomial, they use javascript to switch it to input form and select it.  If you click somewhere else on the page, it goes back to typeset form.  I suggest we ask Kluners for permission to use this javascript, and start using it all over the lmfdb.

**Comment by edgarcosta** [comment]
Kluners-Malle number field web site: http://galoisdb.math.upb.de/home

**Comment by JohnCremona** [comment]
I like that idea for places where it does not make sense to have code snippets providing the same feature (and more).

**Comment by AndrewVSutherland** [comment]
See the discussion on #4394, if we implemented this in a way that could also handle polynomials that are too large to render in katex at all, it would address that issue as well.  I think doing implementing along the lines of what is proposed here would be a very good solution and solve a lot of problems in one stroke.

**Comment by jwj61** [comment]
I think the original issue is settled.  For example, the defining polynomial for a number field can be toggled to raw form for copy/paste, and this has been put in other places.  Any reason not to close this?

**Comment by AndrewVSutherland** [comment]
There is still work to do on the CMF pages, including in the integral basis, q-expansions, and Hecke cutters, see http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/1/118/a/a/, but I think that is covered by #4394.  Edgar is working on this now (using some of the code you wrote).  Our plan is to get rid of the bigint knowls in polynomials and make them all cut-and-pastable.

But I agree this issue can be closed.
