### ISSUE TITLE
flask-login version

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#2173]
We use a fixed version of flask-login, should we now allow to update it? 
If we do this, everybody would need to update their version of flask-login

**Comment by JohnCremona** [comment]
There would have been a reason for setting the fixed version number in requirements.txt, probably that at the time, the most recent version broke our code.  Have you tested the most recent version?  Were any code changes needed?

**Comment by jwj61** [comment]
Yes, there will be some minor changes (for user objects, user.is_anonymous used to be a method, but is now a value, so we currently have user.is_anonymous() and would change it to user.is_anonymous -- there are one or two similar changes to the code).  I think at the time, there was concern about making people update their version of flask login.  If we do it now, everyone will have to update.  But, updating it is easy, so forcing an old version seems odd.

**Comment by JohnCremona** [comment]
I suggest wrapping the small number (I think) of places where the interface has changed with a test for the version number.  We have done this before.  That way we can have code which works with new installations using the newest flask_login without breaking existing ones.
The relevant functions are (as I just tried out):
sage: import flask_login
sage: flask_login.__version__
'0.2.11'
sage: flask_login.__version_info__
('0', '2', '11')

**Comment by jwj61** [comment]
I just tried the commands above with sage on lehner and even after importing flask_login, flask_login.version and flask_login.version_info both give errors.

**Comment by sanni85** [comment]
try   flask_login.__version__
this is the only one working for me

**Comment by JohnCremona** [comment]
@jwj61 we are the victim of github's markup!  After "import flask_version" you type flask_login DOT DOUBLE-UNDESCORE version DOUBLE-UNDERSCORE.  In my and @sanni85 's posts that was converted into a bold face....

**Comment by jwj61** [comment]
Thanks.  That helps, but the newest version of flask_login does not seem to have this either.
