### ISSUE TITLE
Sage download of elliptic curves over number fields

### ISSUE THREAD

**Issue by adeines** [LMFDB/lmfdb#2187]
When you click the sage download button, the file produced is not properly formatted for Sage.
Ex:

x = polygen(QQ) 
data = [ \
[[x^2 - x - 1], 0,0;1,0;0,1;31,-47;-803,560],\
[[x^2 - x - 1], 0,0;1,0;1,1;-16,47;-243,-561],\
[[x^2 - x - 1], 0,0;-1,-1;1,1;-54162,-3916;-1711331,4630255],\
[[x^2 - x - 1], 0,0;1,1;0,1;-58079,3918;2860846,-4626339],\
[[x^2 - x - 1], 0,0;0,-1;0,1;-1744,-587;-549,-32401],\
[[x^2 - x - 1], 0,0;-1,1;1,1;-2331,587;-32950,32400],\
[[x^2 - x - 1], 0,0;1,-1;0,1;1,-2;-2,2],\
[[x^2 - x - 1], 0,0;0,1;1,1;-1,2;0,-3]]

This should be a list of lists and not contain any semicolons.

**Comment by edgarcosta** [comment]
This is true for any format, not only for sage. 
I will close #2059, as you at least gave an example :)

**Comment by JohnCremona** [comment]
At some point the internal data format changed and the download was not chamged to match.

**Comment by sanni85** [comment]
I will fix this later, just finished another download function, so it should be easy.

**Comment by edgarcosta** [comment]
@sanni85 Would you mind if @bhutz takes care of this one? It would be a great way for him to learn a bit about LMFDB.

**Comment by edgarcosta** [comment]
This issue should be closed
