### ISSUE TITLE
Add Bober's modular form data

### ISSUE THREAD

**Issue by jwbober** [LMFDB/lmfdb#2196]
I've made some first steps at https://github.com/jwbober/lmfdb/tree/modforms

**Comment by edgarcosta** [comment]
@jwbober, your data is being added. Shall we close this?

**Comment by edgarcosta** [comment]
please reopen if you disagree

**Comment by AndrewVSutherland** [comment]
When the data is actually available (at least on beta.lmfdb.org) we can close this.

**Comment by AndrewVSutherland** [comment]
This has been done and the data is now available on www.lmfdb.org for all newforms satisfying Nk^2 <= 4000.
