### ISSUE TITLE
Abelian varieties Gaga box

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2213]
I suggest shortening the last line in the properties box of Abelian/Fq/
to

Labels for abelian varieties
or
Labels for isogeny classes

because the current line is very long and makes the box unacceptably wide.

**Comment by JohnCremona** [comment]
Good point.  I would vote for "Labels for abelian varieties".  The full title will still be there on the page you get to by clicking this.

**Comment by sanni85** [comment]
why not just "Labels" or "Labels description"?

**Comment by roed314** [comment]
I like just labels.  I've added this change to https://github.com/LMFDB/lmfdb/pull/2211
