### ISSUE TITLE
API example results in "Error: no key in the query is indexed."

### ISSUE THREAD

**Issue by tkw1536** [LMFDB/lmfdb#2224]
When I try to click the example [hgm/families?gal3=O(5,3)](http://www.lmfdb.org/api/hgm/families/?gal3=O%285%2C3%29) on the [API page](http://www.lmfdb.org/api/), I get an error stating that 

    no key in the query {'gal3': u'O(5,3)'} is indexed

<img width="396" alt="no key in the query {'gal3': u'O(5,3)'} is indexed" src="https://user-images.githubusercontent.com/2923242/29254343-afe75f84-8061-11e7-935f-e16772436607.png">

I have also encountered the same error when using different queries that were working a few months ago. 
Have searchable fields been limited? Or is there something wrong with the backend?

**Comment by davidlowryduda** [comment]
This was changed in #2174 in order to sanitize some of the API calls. Perhaps the examples should be updated.

**Comment by tkw1536** [comment]
In that case, is there some reasoning behind which fields are indexed and which ones are not? Is there some documentation?

I can see how it makes sense to prohibit specific API calls, but it no longer seems to be possible to retrieve all [abelian transitive groups](http://www.lmfdb.org/api/transitivegroups/groups/?ab=i1&_offset=0).

**Comment by jwj61** [comment]
In addition, hypergeometric motives are not in a usable state yet.

**Comment by edgarcosta** [comment]
For most collections, you can find its indexes here:
https://github.com/LMFDB/lmfdb-inventory
or here
https://github.com/csbrady-warwick/DocTesting
The latter were automatically generated 3 months ago and should be quite up to date. However perhaps a bit more cryptic.

**Comment by edgarcosta** [comment]
Perhaps, we should index every main key, i.e., the ones that are supposed to be present for every object.

#2174 was mostly avoiding searches for non existent (or mistyped) keys on big collections.

**Comment by edgarcosta** [comment]
Should we close this issue?

**Comment by AndrewVSutherland** [comment]
I just fixed the offending example, so I think we can close.
