### ISSUE TITLE
GL2-type knowl possibly misleading

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2227]
Ari Shnidman	(shnidman@bc.edu ) reported:

This is a very minor comment about the description/definition of "GL_2
type" in the genus 2 curve page (after clicking the "GL_2 type" link).
The last sentence is a bit misleading. Perhaps it should say "the
endomorphism algebra is 2-dimensional over Q" as opposed to "the
endomorphism algebra is isomorphic to Q \oplus Q". The notation in the
latter makes it seem like the endomorphism algebra is isomorphic *as
an algebra* to Q \oplus Q, which it need not be. The first sentence of
the paragraph points this out, but the (current) last sentence makes
it sound like the split quadratic algebra is the only one that can
occur among GL_2-type, genus 2 Jacobians. (And this is not the case.)

Best,

This refers to the knowl http://beta.lmfdb.org/knowledge/show/g2c.gl2type

**Comment by AndrewVSutherland** [comment]
Fixed.

**Comment by JohnCremona** [comment]
Thanks -- could you email Ari?

**Comment by AndrewVSutherland** [comment]
Done.
