### ISSUE TITLE
Lattices pages broken at www.lmfdb.org

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2232]
As reported on the web bug system.

Lattices are not in beta (I think) and do appear in the production sidebar, clicking on that link produces a server error.   There is a collection Lattices.lat on the cloud, according to http://www.lmfdb.org/api/, with the same number of records as in the beta database.
Since prod and beta are right now running the exact same code my guess is that the cloud database needs to be updated.  If @sanni85 could confirm that someone will deal with it.

**Comment by AndrewVSutherland** [comment]
Looks to me like lat, lat.rand, and lat.stats should be copied over, but I'm not sure about lat_nf.  But as soon as someone tells me which collections should be copied/updated, I'm happy to do so.

**Comment by sanni85** [comment]
The collections needed are lat, lat.rand, and lat.stats. The code on bets uses lat.stats and the old code on production did not. So once the collections are copied over there should be no error.

**Comment by JohnCremona** [comment]
Thanks -- @AndrewVSutherland will you do the honours?

**Comment by AndrewVSutherland** [comment]
Done!

**Comment by sanni85** [comment]
thanks! and sorry again!
