### ISSUE TITLE
Some  L-functions for elliptic curves over number fields crash

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2236]
Some  L-functions for elliptic curves over number fields crash, though most  are fine.

For example http://www.lmfdb.org/EllipticCurve/6.6.1528713.1/53.1/a/1
 (click on the L-function link)

causes a catastrophic failure -- Sage crashes completely with a message about the lcalc library.

While
http://www.lmfdb.org/EllipticCurve/6.6.1528713.1/1.1/a/11
(for example) is fine.

**Comment by edgarcosta** [comment]
1- did it work before HMF fixing? 

2- Both crash the client. The 2nd and 3rd calls of lcalc never end up happening in for the second example (there are no zeroes or plot).
try: http://www.lmfdb.org/L/Zeros/ModularForm/GL2/TotallyReal/6.6.1528713.1/holomorphic/6.6.1528713.1-1.1-a/0/0/
http://www.lmfdb.org/L/Plot/ModularForm/GL2/TotallyReal/6.6.1528713.1/holomorphic/6.6.1528713.1-1.1-a/0/0/

3- I did some digging and it seems to be either a bug in lcalc or we are passing something wrong to lcalc and it just aborts. Everything goes fine until: https://github.com/LMFDB/lmfdb/blob/8b7cd9408a08d9a98231a62f569f4aad81544bb0/lmfdb/lfunctions/Lfunction.py#L233

4- Those L-functions were disabled from the HMF side

**Comment by JohnCremona** [comment]
If it is only curves over this specific field which crash this can be explained by HMF fixing.  Since that is nearly done, let's come back to this after.  (The HMFs for this field were re-uploaded in June and some of their labels changed.  The curves have now also been relabelled to match and the data in the collections forms.search and heck is correct but the data in forms is the old permutation.)
On the other hand when testing this locally (and using the code in #2235 ) I still got a crash.
Nevertheless let's finish of #2235 first.

**Comment by JohnCremona** [comment]
Right now the L-function for this curve fails to display but in a more graceful way:

Unable to render L-function page due to the following problem(s):
No L-function instance data for "EllipticCurve/6.6.1528713.1/53.1/a" was found in the database.

I think this can be closed.

**Comment by edgarcosta** [comment]
I agree. However, this is a side effect of having code for L-functions of ecnfs on the database, explicitly, it we have not added the L-function to the database, then the user will see that error.

**Comment by AndrewVSutherland** [comment]
Given that the relevant pages all now show "L-function not available" I am closing this issue.  If someone wants to create a new issue requesting that these L-functions be made available, feel free to do so.
