### ISSUE TITLE
Number field 6.0.7200000.1 very slow to load

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#2253]
The page http://www.lmfdb.org/NumberField/6.0.7200000.1 times out.  It will sometimes load in beta (http://beta.lmfdb.org/NumberField/6.0.7200000.1), but is very slow there as well.

**Comment by edgarcosta** [comment]
I believe that is same issue that I reported last night: https://github.com/LMFDB/lmfdb-inventory/issues/69
> I believe there is a typo in one of the indices.
> We have indexed 'oldpolredabscoeffshash' and I believe we meant to hash 'oldpolredabscoeffhash' (no s).


```
2017-09-05T16:37:52.748+0000 I COMMAND  [conn198753] command numberfields.fields command: 
find { find: "fields", filter: { oldpolredabscoeffs: "-1011,3531,-6417,6935,-3036,-1626,2701,-849,-384,282,-3,-21,-7,3,-3,1", oldpolredabscoeffhash: "12781c3f7679cb4549eb8eb9e26c7070" }, limit: 1, singleBatch: true } 
planSummary: COLLSCAN keysExamined:0 docsExamined:7669894 cursorExhausted:1 keyUpdates:0 writeConflicts:0 numYields:59923 nreturned:0 reslen:125 locks:{ Global: { acquireCount: { r: 119848 } }, Database: { acquireCount: { r: 59924 } }, Collection: { acquireCount: { r: 59924 } } } 
protocol:op_query 30169ms
```

**Comment by edgarcosta** [comment]
I will create the index now. Hold tight.

**Comment by jwj61** [comment]
OK (I was about to do it as well).

**Comment by edgarcosta** [comment]
Index added on production and development.

However, as admin I can't drop indexes...
```
2017-09-05T16:55:17.310+0000 I ACCESS   [conn198939] Unauthorized: not authorized on numberfields to execute command { dropIndexes: "fields", index: "oldpolredabscoeffshash" }
```

@jwj61, could you do that for me?

**Comment by jwj61** [comment]
Done on beta.

**Comment by JohnCremona** [comment]
@edgarcosta if you need any permissions you don't currently have, you can have them.

**Comment by jwj61** [comment]
I don't think I have permission for the cloud version.  At worst, this will be cleaned up the next time we update the number field database on the cloud, right?

**Comment by AndrewVSutherland** [comment]
Thanks for fixing this promptly (this page is actually relevant to a talk John Voight is giving tomorrow morning in Trieste).  I went ahead and dropped the oldpolredabscoeffshash index on the cloud (but you are correct @jwj61, it would automatically get cleaned up the next time the collection was copied from beta).
