### ISSUE TITLE
Don't hard code width of coefficient table

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2260]
The width of the coefficient table of Maass forms coefficients is set inline at 400px.

This forces the table below the properties box if the screen is narrow.
For example:

/ModularForm/GL2/Q/Maass/4f5556fe88aece241f000006

Unless there is some other cases where the fixed width is needed, it should be eliminated
or done properly with sitewide CSS.

I think this just involves deleting line 41
$('#coeffs').css('width','400px')
of
modular_forms/maass_forms/maass_waveforms/views/templates/mwf_one_form.html

Making an issue as a reminder to look into this later, or something
easy for someone to do.

**Comment by JohnCremona** [comment]
I merged the fix at #2267, and hope that it does what David F wanted.
