### ISSUE TITLE
Target: factorization of the L-function of a Q-curve

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2263]
Something I wanted to do in the LMFDB was not quite possible, so I want to suggest
it as a target.

The Q-curve /EllipticCurve/2.2.28.1/25.1/a/1 associated to the HMF
/ModularForm/GL2/TotallyReal/2.2.28.1/holomorphic/2.2.28.1-25.1-a
has an L-function which (if I understand what Ralf Schmidt was telling me)
should factor.

Unlike base change elliptic curves, the factors are not from elliptic curves/Q.
So by process of elimination, the factors should come from S_2(Gamma_0(140), chi)
with chi quadratic.  That space is available for some chi, but apparently not the
one I wanted.

**Comment by edgarcosta** [comment]
Looking at the second moment (using all the primes up to a million) I get that the second moment is `0.9910360400996727`.
Thus, we have very strong numerical evidence that the L-function is primitive, and I have indeed marked as primitive in: http://localhost:37777/L/EllipticCurve/2.2.28.1/25.1/a/ (using #2246)

For comparison, if you do the same for http://www.lmfdb.org/EllipticCurve/2.2.5.1/80.1/a/1, then you get `1.9926173482566916`

**Comment by davidfarmer** [comment]
Thanks.  I'll track down why I thought it would not be primitive.
