### ISSUE TITLE
Cloud DB contains publically readable users table

### ISSUE THREAD

**Issue by hratcliffe** [LMFDB/lmfdb#2281]
The new cloud mirror on m0(dot)lmfdb(dot)xyz appears to contain the users table with publicly accessible emails and password hashes of everybody signed up for the webpage. For example using nothing but a new clone of the project:

```from lmfdb import base 
users = base.getDBConnection().userdb.users
a = users.find()
#Print emails for all records
for el in a:                               
    print(el['email']) 
```
This table should either not be included, should be locked down or should be fully encrypted.

**Comment by edgarcosta** [comment]
Thanks!

I agree we should not have those public. We should do this within the useradmin of MongoDB.

I closed down the port temporarily, until someone edits the permissions of the default user.

However, no one should expect their passwords and emails to be secret. At the end of the day, we do not even use SSL when authenticating....

**Comment by edgarcosta** [comment]
I created a new role with the following code:
```
roles = []
for db in C.database_names():
    if db not in ["local", "config", "userdb", "admin", "contrib", "upload","test"]:
        roles += [{u'role':u'read', u'db': db }]
privileges = [{ u'resource': { u'db': u"", u'collection': u"" }, u'actions': [ u"listDatabases" ] }]
role_dict = {u"role" : u"ReadUncensoredDatabases", u"privileges" : privileges, u"roles" : roles}
```
which gives:
```
{u'privileges': [{u'actions': [u'listDatabases'],
   u'resource': {u'collection': u'', u'db': u''}}],
 u'role': u'ReadUncensoredDatabases',
 u'roles': [{u'db': u'HTPicard', u'role': u'read'},
  {u'db': u'Lattices', u'role': u'read'},
  {u'db': u'Lfunction', u'role': u'read'},
  {u'db': u'Lfunctions', u'role': u'read'},
  {u'db': u'MaassWaveForms', u'role': u'read'},
  {u'db': u'SL2Zsubgroups', u'role': u'read'},
  {u'db': u'abvar', u'role': u'read'},
  {u'db': u'artin', u'role': u'read'},
  {u'db': u'bmfs', u'role': u'read'},
  {u'db': u'curve_automorphisms', u'role': u'read'},
  {u'db': u'elliptic_curves', u'role': u'read'},
  {u'db': u'genus2_curves', u'role': u'read'},
  {u'db': u'halfintegralmf', u'role': u'read'},
  {u'db': u'hgm', u'role': u'read'},
  {u'db': u'hmfs', u'role': u'read'},
  {u'db': u'knowledge', u'role': u'read'},
  {u'db': u'localfields', u'role': u'read'},
  {u'db': u'mod_l_eigenvalues', u'role': u'read'},
  {u'db': u'mod_l_galois', u'role': u'read'},
  {u'db': u'modularforms2', u'role': u'read'},
  {u'db': u'numberfields', u'role': u'read'},
  {u'db': u'sato_tate_groups', u'role': u'read'},
  {u'db': u'siegel_modular_forms', u'role': u'read'},
  {u'db': u'transitivegroups', u'role': u'read'},
  {u'db': u'ellcurves', u'role': u'read'},
  {u'db': u'characters', u'role': u'read'},
  {u'db': u'finite_fields', u'role': u'read'},
  {u'db': u'hecke_algebras', u'role': u'read'},
  {u'db': u'embedded_mfs', u'role': u'read'},
  {u'db': u'inventory', u'role': u'read'}]}
```

At the moment the public user `lmfdb` has two roles: 
```
roles [{u'db': u'admin', u'role': u'index_and_list_collections'}, {u'db': u'admin', u'role': u'readAnyDatabase'}]
```
I plan to replace those by the above role. 
@AndrewVSutherland, @JohnCremona does this sound okay to you?

ps: I don't really get the `u'index_and_list_collections` which gives permission to create indexes (we don't want this!) and list collections on any database (already given by the `readAnyDatabase`).

pps: pymongo doesn't support the createRole command, even if one tries `db.command('createRole',str(role_dict).replace("u'","'"))`, I only managed to create the role through a mongo shell.

**Comment by edgarcosta** [comment]
I just did:

```
 db.grantRolesToUser("lmfdb",["ReadUncensoredDatabases"])
db.revokeRolesFromUser("lmfdb",["readAnyDatabase", "index_and_list_collections"])
```

I will now see  what I have broken with these two changes.

**Comment by AndrewVSutherland** [comment]
I suddenly can't access mongodb on atkin (connection attempt failed: not authorized on userdb...) so you broke that :)

**Comment by edgarcosta** [comment]
Yeah, I noticed that.
I have just reverted it.

Not sure how we should handle this...

**Comment by hratcliffe** [comment]
Is it because makeDBConnection authenticates against the admin database, which isn't included in your role?

I know this seems irrelevant, but EU laws are quite strict about data protection, even if the hosting is in the US. The HTTP issue does mean emails etc would be vulnerable, so we should consider fixing that ASAP, but actively publishing details is a different matter unless it was made very clear at signup that it would happen.

**Comment by edgarcosta** [comment]
I believe is this line:
https://github.com/LMFDB/lmfdb/blob/cb7f1ea67bbd16d7e5334a2a9930930b358b9443/lmfdb/base.py#L120

I will try again the switch, and see what happens.

**Comment by edgarcosta** [comment]
@hratcliffe  I agree with you that we should not be publishing anything like that. The server access has been disabled. 

#2285 did not fix the issue completely. and I have reverted the lmfdb permissions to the original ones.

Knowl relies heavily of userdb, I'm not sure how to work around that.

**Comment by edgarcosta** [comment]
An alternative is to create a collection where we strip down the critical information, but that requires us to modify code that deals with user management. (I won't have time for that for a while)

On similar note, we already say: "Don't use your usual password due to security concerns!"

**Comment by edgarcosta** [comment]
A quick update, we are planning to purge all the emails (as we don't really use them), and edit the user scripts accordingly.

**Comment by JohnCremona** [comment]
Good -- I don't think I commented before but I agree with this move.

**Comment by edgarcosta** [comment]
Port opened and all emails set to email@example.org, just in case I forgot something stupid in #2301 .
I saved the old emails, but I don't plan to use them for anything.

Whenever #2301 is merged I will close this.
