### ISSUE TITLE
Update acknowledgments to reflect Simons collaboration grant

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2291]
Update http://www.lmfdb.org/acknowledgment to reflect that 
https://icerm.brown.edu/simonscollaboration/ is paying for the google cloud servers.

**Comment by edgarcosta** [comment]
@AndrewVSutherland Thanks

**Comment by edgarcosta** [comment]
There is `:` misplaced inside the href after `Awarded to the`

and we also need to update the Hosting section

**Comment by AndrewVSutherland** [comment]
Fixed (and hosting section updated).
