### ISSUE TITLE
In lfunctions, what is Lkey?

### ISSUE THREAD

**Issue by davidlowryduda** [LMFDB/lmfdb#2298]
I see that many (not all) of the L-functions have implemented a method called Lkey(), but that none of these are ever used. I wonder --- is this a previous attempt at making something like the Lhash we now have? Or is there a deeper, longer plan in the works that hasn't yet been realized?

**Comment by edgarcosta** [comment]
I only know that it should be a dictionary. No idea what it is used for.
And indeed it is never used.
Here is the result of `grep -n -A3 -B1 -r Lkey .  `
https://gist.github.com/37b977801b650849286642e13ff1577d

**Comment by davidlowryduda** [comment]
I think that the original intent of Lkey has been lost to time. So I think that I'll remove the remnants soon.
