### ISSUE TITLE
Take Bianchi forms out of beta

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2303]
This will mainly require a change to the sidebar since Bianchi forms are already in the production database and viewable at www.lmfdb.org.

**Comment by davidlowryduda** [comment]
This is done in the now-merged #2304, right? I think this can be closed.

I see that Bianchi forms don't yet appear on the live site. Perhaps you were keeping this issue as a reminder to do the necessary merge there.

**Comment by JohnCremona** [comment]
@AndrewVSutherland and I just agreed to push the latest master to beta, after which this will be live on www.lmfdb.org, and the issue closed.

**Comment by AndrewVSutherland** [comment]
This is now live on www.lmdfb.org.
