### ISSUE TITLE
Same L-function, different pages display different fields of data

### ISSUE THREAD

**Issue by davidlowryduda** [LMFDB/lmfdb#2316]
The cuspidal newform of weight 2 and level 14 corresponds to an elliptic curve with label 14.a6, and so they have the same L-function. The two pages for these two L-functions are at

    http://www.lmfdb.org//L/ModularForm/GL2/Q/holomorphic/14/2/1/a/0/
    http://www.lmfdb.org/L/EllipticCurve/Q/14/a/

The data displayed for each L-function is different. It appears that the elliptic curve version displays strictly more information. The elliptic curve version also allows both the display of the analytic and arithmetic expansions, whereas the modular form only allows display of the analytic expansion.

The names of the links in the "Origins" box are similar but different. The modular form L-function page links to `Modular Form 14.2.1a` while the elliptic curve L-function page links to `Modular Form 14.2.1a. Perhaps our labeling convention changed in the middle? I believe that we now use the longer version.

This example is really a stand-in for the more general problem of what to do when the same L-function arises in many different ways.

I was thinking about this when I was thinking about which versions of an L-function one would display if one displays the factors (as described in #2269), and about what data  to include on a cannonical home page of an L-function (if such a homepage were to exist. If it were, it would have url /L/<lhash> or /L/lhash/<lhash>, using the `lhash` standard).

Do we care if different pages of the same L-function display different data? In particular, it would be unfortunate if someone didn't think to go to other pages of the same L-function.

I think we should chat a bit more about what to do when the same L-function appears in different places. We can think of this as sharpening our principles #2082.

- If we expect users to maybe look at other instances of the same L-function for other data, then we should link to other instances of the same L-function. (This is already done in the experimental lhash page code, #2299, and is easy to adapt).

- If we want each L-function to have a canonical homepage, then we should come up with a standard choice of what data to include, and ways of displaying that data. As an example of display differences, a modular form L-function is called L(s,f), while the elliptic curve L-function is called L(s), and the Euler products are displayed differently, etc. This seems hard, but it also seems to me like it would be a good idea, if possible.

**Comment by davidfarmer** [comment]
Some L-functions are displayed from data in a database.  Those are
usually done reasonably well, and they have an option to toggle between
arithmetic and analytic normalizations.

Others are not.  For example, L-functions of classical modular forms.
For these, the existing code is a mess, and the page itself is just a
placeholder.  For those, the best thing to do is ignore any
inconsistencies that are not actual errors.  And also do not try to
fix that code.  The bad old code will be deleted once the L-function
data is taken from the database.

Feel free to work on/fix/improve the code for L-functions taken from
the L-functions database.

Do not waste your time on the L-functions are are generated on the
fly, unless your efforts are to get those L-functions rigorously
calculated and put into the database.  Once that happens, there will
only be minor differences between the home pages of those L-functions,
in those cases where the user is expecting to see the L-function "of"
something.
