### ISSUE TITLE
Points on X_0(31)

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2320]
From the feedback form for the page http://www.lmfdb.org/Genus2Curve/Q/961/a/923521/1 :

Dear the Administration, 

I am sorry if I misunderstood you notation; but it seems to me that the rational points of X_0(31) listed on your website are not correct. My understanding of your notation is that 
[x:y:z]=(1 : -1 : 0), (1 : 0 : 0)  are all rational points of X_0(31) (which correspond the the 0 and the infinity cusps of X_0(31)). 

Simple calculations show that these are not rational points.  Indeed, I tried all combinations of (x,y) but they also did not work.  I think the rational point corresponding to the infinity cusp is [1:-5:0].  However, I has not been able to find the rational point corresponding to 0.

Thank you for your consideration.

Best wishes, Tung
tungnt@uchicago.edu

**Comment by AndrewVSutherland** [comment]
There is no problem here, the confusion stems from the fact that the displayed curve equation is written in affine notation, but really denotes a smooth projective curve in weighted projective space, where y has weight 3, x and z have weight 1, given by a homogenous equation of degree 6.  For the curve at http://www.lmfdb.org/Genus2Curve/Q/961/a/923521/1 this equation is:

    y^2 + (x^3+x^2*z+z^3)*y = -5x^4z^2 + 4x^3z^3 + 3x^2z^4 - 2xz^5 - 3z^6

and one can easily see that (1:-1:0) and (1:0:0) are solutions.

I will update the knowls for Minimal Equation and Rational Points to explain this and then follow up with and e-mail to Tung.
