### ISSUE TITLE
Number field stats page on main server

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2321]
From the feedback page: the number field stats page

  http://www.lmfdb.org/NumberField/stats

causes a server error.  

I believe it works on beta.  Coincidentally, we are rebuilding the number field stat database because new fields were added, and if you check while it is rebuilding, the page will fail.

**Comment by AndrewVSutherland** [comment]
I get a server error on beta.

**Comment by JohnCremona** [comment]
The server error can probably be explained by the stats database not being
complete yet.  Running locally to get the traceback it chokes on line 211
of statistics:

n = statdb().find_one({'_id': 'degree'})['counts']

TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by jwj61** [comment]
The server error on beta was because the new stats were being recomputed at the time.  It has finished computing, and the page works on beta.

But, it is still broken on the production server.  Soon, like maybe later today, I will be ready for a data pull request from beta to the main server.  Presumably, that will fix the problem on the main server.

**Comment by jwj61** [comment]
OK, the number field database is ready for uploading to the cloud.  There are three parts

  numberfields.fields
  numberfields.fields.rand
  numberfields.stats

This upload restores class number, class group, unit computations for a large number of fields in degrees 8 and 10, and adds the remaining fields from the Jones-Roberts database.

**Comment by AndrewVSutherland** [comment]
OK, I will start the update shortly.  Expect number fields to be unavailable on www.lmfdb.org for a half hour or so when it rebuilds the indexes (and stackdriver will no doubt complain, as it should).

**Comment by AndrewVSutherland** [comment]
The update finished.  @jwj61 can you take a look and let me know if everything looks good, I will then delete the old versions.

But it looks like we still get a server error on http://www.lmfdb.org/NumberField/stats.

**Comment by AndrewVSutherland** [comment]
The update finished.  @jwj61 can you take a look and let me know if everything looks good, I will then delete the old versions.

I found and fixed the problem with the stats page, the collection numberfields.stats did not exist on the cloud, there was just a numberfields.fields.stats.

Is the collection numberfields.fields.stats used at all?  If not, can it be deleted?

**Comment by jwj61** [comment]
It looks good now.

numberfields.fields.stats is not being used, so that can be deleted.

**Comment by JohnCremona** [comment]
A comment concerning the naming of collections and the current work we are doing on the inventory (which is almost ready for a pull request):  it would be nice to have an automatic way to tell which collections should not be included in the inventory, currently everything with a dot in its name, which covers .rand, .old, .new and .stats (and we could make it more specific to those specific suffixes).  The collection called stats in numberfields is one of several which break the convention (others being Lattices/lat_new, and there's also a plain stats collection in hecke_algebras).  I am not saying that any collections should change their names now, but the conventions we use should perhaps be written down.

Related: to find out the exact collections which are currently on the cloud database (the main one not the beta replica) I can look at www.lmfdb.org/api/all, or in https://github.com/edgarcosta/lmfdb-gce/blob/master/db_scripts/db-collections.txt  but perhaps this list could be kept somewhere more visible?

**Comment by AndrewVSutherland** [comment]
@JohnCremona I think https://github.com/LMFDB/lmfdb-inventory is the right place for this.  In principal, the README.md should let you see at a glance which collections are supposed to be there, but it probably needs to be updated.
