### ISSUE TITLE
Add torsion growth data for elliptic curves over Q

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2324]
Enrique Gonzalez has provided data for torsion growth of elliptic curves over Q in number fields of degree up to 7 (so far).  This week (beginning 13 Nov) we are uploading this data and will display it on each curve's home page, with a link to the number field over which the torsion grows when we have it.  In many cases we do not, even for cubic fields where we appear to only have fields of discriminant up to 1 or 2 million (depending on the signature).

**Comment by davidlowryduda** [comment]
I think this can be closed too.

**Comment by JohnCremona** [comment]
The code has not yet been pushed to prod, that's the only reason it is still open.  But the data is on prod so that could happen soon.

**Comment by JohnCremona** [comment]
Closing after the push to prod.  Enrique is still working on the degree 8 data.
