### ISSUE TITLE
bib link on citations page broken

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2332]
As reported on the Bug Report spreadsheet:  On the page 
http://beta.lmfdb.org/citation/citations (also on www.lmfdb.org) clicking on the bib links does not work.

I will fix this.

**Comment by JohnCremona** [comment]
It was a triviality: bibtex processing left a line in an html file like this:
`  title = {{R}iemann's hypothesis},
`
and the double { confused jinja.  Inserting a space fixes it.

**Comment by davidlowryduda** [comment]
I believe that this can be closed now.

But I wonder: how are citations added? I see that there is some automatic generation. The header in `citations_content.html` indicates that one uses bibtex2html on a citations.bib file. But I don't see a citations.bib file anywhere.

The reason why I ask is that I wonder if the automatic processing will always course doubled `{{` in cases like this one.

**Comment by JohnCremona** [comment]
See the lmfdb/citations repository.  I'm open to better ways of doing this.  When we add new things by cutting and pasting from Google Scholar into the .bib file we have to be on the lookout for things like this, and up to now my testing has picked up on them.  This time I did not test properly.

One good thing to do would be to add a couple of unit tests, since that would have caught this problem.
