### ISSUE TITLE
Upgrade to Sage-8.1

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2338]
I have been testing our code with Sage-8.1 which was released a few days ago.  All works, with some deprecation warnings (not all new) when running the test suite:

   1. There has been a change in p-adics which leads to this (@roed314 ?)

/home/jec/lmfdb/lmfdb/nfutils/psort.py:47: DeprecationWarning: list is deprecated. Please use expansion instead.
See http://trac.sagemath.org/14825 for details.
  return lambda f: [f.degree()] + flatten(zip(*[padded_list(c,k) for c in f.list()]))

   2. This has been around for longer.  It appears a few times but all seem to arise from line 164 of lmfdb/genus2_curves/web_g2c.py

/home/jec/lmfdb/lmfdb/lfunctions/Lfunctionutilities.py:465: DeprecationWarning: the _pari_ method is deprecated, use __pari__ instead 
See http://trac.sagemath.org/22470 for details.
  thispolygal = list_to_factored_poly_otherorder(lf[1], galois=True)

**Comment by JohnCremona** [comment]
PS Users of the Warwick machines atkin and lehner will find that 8.1 is now the default.

**Comment by roed314** [comment]
On Mon, Dec 11, 2017 at 5:38 AM, John Cremona <notifications@github.com>
wrote:

> I have been testing our code with Sage-8.1 which was released a few days
> ago. All works, with some deprecation warnings (not all new) when running
> the test suite:
>
>    1. There has been a change in p-adics which leads to this (@roed314
>    <https://github.com/roed314> ?)
>
> /home/jec/lmfdb/lmfdb/nfutils/psort.py:47: DeprecationWarning: list is
> deprecated. Please use expansion instead.
> See http://trac.sagemath.org/14825 for details.
> return lambda f: [f.degree()] + flatten(zip(*[padded_list(c,k) for c in
> f.list()]))
>
Yep.  I can take a look after finals (this week).

**Comment by JohnCremona** [comment]
@roed314 ping?

**Comment by edgarcosta** [comment]
@JohnCremona, this might need to wait until early February, I believe that until then @roed314 will be away from a keyboard.

**Comment by JohnCremona** [comment]
1. I'm going to deal wit this myself since the although the underlying reason is some change in p-adic polynomials, the function which calls the deprecated method is mine.
2. PR#2359 deals with this.

**Comment by JohnCremona** [comment]
PR #2361 fixes the first point.  To get rid of the deprecation warning when running under 8.1 you have to use x.expansion() instead of x.list() for a p-adic number, and that does not work on 8.0, so I put in a try/except block which works on both.  When #2361 is merged this can be closed, though perhaps it should stay open until we have 8.1 running on the servers.

**Comment by JohnCremona** [comment]
8.1 is now running on both Warwick servers but not yet on www.lmfdb.org

**Comment by edgarcosta** [comment]
I'm currently building 8.1, and I plan to switch www.lmfdb.org to 8.1 next
Tuesday.

**Comment by edgarcosta** [comment]
http://www.lmfdb.org/ is now running Sage 8.1 as promised.
