### ISSUE TITLE
no data  for level = 100, k 7, chi = 99

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#2340]
The only space available, which is the last one, should have dimension 52:

http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/100/7/?group=1
 
but clicking on the link, it says that it is empty...

**Comment by edgarcosta** [comment]
@JohnCremona, should we close this?
This now sits outside our goal range of Nk^2 <= 4000

**Comment by AndrewVSutherland** [comment]
We should not close any outstanding CMF issues until the updated version is merged.

**Comment by AndrewVSutherland** [comment]
Addressed by #2717, see http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/100/7/d/.
