### ISSUE TITLE
The page icms.org.uk/workshops/onlinedatabases no longer exists, causing tests to fail

### ISSUE THREAD

**Issue by davidlowryduda** [LMFDB/lmfdb#2356]
In our testing of the acknowledgements page, we check that the LMFDB is noted on some external pages. It appears there used to be a page at https://info.maths.ed.ac.uk/workshops/onlinedatabases which referenced the LMFDB, but this page has either moved or been removed.

I looked to see if I could find where it moved within their site, but I think it has instead been taken down.

I suppose we should remove this test?

**Comment by JohnCremona** [comment]
Before we do that, let's try to find out if the ICMS (in Edinburgh) has
done this on purpose or by mistake.  The previous ICMS director has an
office down the hall from me (and you DLD) now, so he might know the policy!

Right now the website http://www.icms.org.uk is down anyway.

John

**Comment by davidfarmer** [comment]
That workshop was joint with AIM, so you could instead (or also)
use this link (which also mentions the LMFDB):

    https://aimath.org/pastworkshops/onlinedata.html

It is not easy to maintain permanent links to things like
past activities, especially when you update your website.
