### ISSUE TITLE
rename hmfs.forms.search --> hmfs.forms

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2374]
For historical reasons in the hmfs (Hilbert modular forms) database the collection containing everything except the Hecke eigenvalues is called "forms.search", and there is not collection called "forms".  I want to rename "forms.search" to "forms", not only for aesthetic reasons, also because we are very close to satisfying a useful convention that the only collections with a "." in their name are those using ".old" or ".new" (both temporary, used when copying collections) and ".rand", ".stats".  (I know there are good counterexamples to this, but that is not relevant here.)

Here's a plan to make this happen:
   1. change code so that it reads from forms if that exists, else from forms.search (only a minor change required, in just one function).
   2. Use rewrite_collection to copy forms.search to forms, on both beta and cloud..
   3. Push the changes in 1 to beta and prod.
   4. Drop the forms.search collections on beta and prod respectively.

All trivial but I think worth doing.

**Comment by JohnCremona** [comment]
Update: the new code is live on beta and prod; the old *search* collections are dropped on beta.

Remaining tasks: drop the redundant collections on prod (cloud database), namely forms.search, forms.search.rand and forms.search.stats.  I would prefer to do this in 2 stages, first to rename them to something such as fs.bak, fs.rand.bak, fs.stats.bak, then wait a few days and then drop them.  Volunteers who can do this?
Then we'll do a (minor) tidy up of the code to remove manetions to forms.search*

**Comment by AndrewVSutherland** [comment]
The rename is done.  Let me know when you are happy to remove them.

**Comment by JohnCremona** [comment]
Thanks @AndrewVSutherland , good to go.

**Comment by AndrewVSutherland** [comment]
The .bak collections have been droppped.

**Comment by JohnCremona** [comment]
Thanks -- all now done except the minor code tidy up while I will get around to at some point.
