### ISSUE TITLE
Update travis script to use Sage-8.1

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2377]
All the servers are now running version 8.1 of Sage so the travis script needs updating (lines 36 and 41) to use that.  I don't know how to get an appropriate bundle to replace https://storage.googleapis.com/sage-lmfdb/sage-8.0-Ubuntu_14.04-x86_64.tar.bz2 but someone here must.

**Comment by edgarcosta** [comment]
I need to build the bundle myself. I will also try to take the opportunity to document how to do it. This might need to wait a bit, as the process might require some babysitting.

**Comment by edgarcosta** [comment]
1- spinoff a VM
 * n1-highcpu-4 (4 vCPUs, 3.6 GB memory)
 * 25 GB SSD
 * Ubuntu 14.04 LTS

2- `sudo apt-get install git make gcc g++`
3- `git clone https://github.com/edgarcosta/binary-pkg.git`
4-  `cd binary-pkg`
5- edit sage.yaml line 4 accordingly
6- In a screen `cd binary-pkg && make bdist-sage-linux` and wait `??` hours

I will keep editing this comment...

**Comment by edgarcosta** [comment]
I have updated: https://github.com/edgarcosta/binary-pkg/ with this text
