### ISSUE TITLE
Missing Data on Prod for Higher Genus Curves

### ISSUE THREAD

**Issue by jenpaulhus** [LMFDB/lmfdb#2378]
On the production pages for /HigherGenus/C/Aut/  the search by Group Order is returning no search values.  This is different than the behavior on beta.  For example:
http://beta.lmfdb.org/HigherGenus/C/Aut/?genus=&signature=&groupsize=2..5&group=&dim=&inc_hyper=include&inc_cyc_trig=include&inc_full=include&count=20&Submit=Search
vs
http://www.lmfdb.org/HigherGenus/C/Aut/?genus=&signature=&groupsize=2..5&group=&dim=&inc_hyper=include&inc_cyc_trig=include&inc_full=include&count=20&Submit=Search

The search by Group Order uses a field in the database called "group_order" which we added this fall. I mention it in #2355 but forgot to mention it with the pull request #2341 (which is what is now on the production pages).  Is there something particular I need to do to get that new field working?

**Comment by jenpaulhus** [comment]
Ummm... I may have typed too soon.  Everything looks like it's running fine now!

**Comment by AndrewVSutherland** [comment]
When you make changes to the data on beta, they will not be copied to the production database unless you explicitly ask for this to be done (e.g. by opening on issue on lmfdb-inventory).  You can see what data is actually there using the api pages, e.g. compare

http://beta.lmfdb.org/api/curve_automorphisms/passports/
vs.
http://www.lmfdb.org/api/curve_automorphisms/passports/

Right now they are different, the production copy does not contain the group_order attribute.  I will go ahead and update the production database now (once this is finished the two pages above should look the same).

**Comment by AndrewVSutherland** [comment]
OK, the updated passports collection has been copied to the production database and the two queries above now return the same results.

**Comment by jenpaulhus** [comment]
Thanks, Drew!  In the future, I'll be sure to explicitly request updates to the production data.
