### ISSUE TITLE
google search issue

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2389]
From the feedback page:

"Dear the Administration, 

My name is Tung Nguyen and I am a graduate student at UChicago. 

Recently I tried to search for some databases on your website. However, for some unknown reasons, I was not able to do so. The website said 

""Unauthorized access to internal API. Please refer to https://support.google.com/customsearch/answer/4542055
"" 

I tried on different computers but this problem resisted. The google page seemed to indicate that there were some incompatibilities between google search site and your site. Can you please help me with this issue? 

Thank you very much for your consideration. 

Best wishes, Tung"

Email: tungnt@uchicago.edu

**Comment by edgarcosta** [comment]
I am not sure the API label is appropriate.

This is related to the search bar at the top, e.g.,
http://www.lmfdb.org/search?q=foo

**Comment by JohnCremona** [comment]
I don't think I have ever used that box and it seems not to have been tested recently.  Shall we just remove (hide) it until we can work out how to make it useful?  For example I just put Elliptic Curve into the box and got nothing but some ads for amazon and the like (including one for some fitness gadget!).

**Comment by AndrewVSutherland** [comment]
I think we should remove definitely remove it.  If/when someone wants to figure out how to make it work, we can put it back.

**Comment by JohnCremona** [comment]
For future reference the code is at https://github.com/LMFDB/lmfdb/blob/master/lmfdb/templates/search.html
and has not been touched for 6 years.

**Comment by edgarcosta** [comment]
I agree with removing it

**Comment by JohnCremona** [comment]
OK, I'll merge my PR then,
