### ISSUE TITLE
Elliptic curve records missing from inventory

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2394]
http://www.lmfdb.org/inventory/elliptic_curves/curves/records/ shows nothing (same on beta).  This used to be populated OK.  I have done some rewrite_collection operations since it was last scanned in case that is relevant.

**Comment by hratcliffe** [comment]
I think there are some bugs in the record uploading. This is why the counts are also wrong. Hoping to fix it today.

**Comment by hratcliffe** [comment]
The elliptic curves records should now display and all the counts should be correct again.

**Comment by JohnCremona** [comment]
Good!
