### ISSUE TITLE
Inventory Display bugs

### ISSUE THREAD

**Issue by hratcliffe** [LMFDB/lmfdb#2399]
New inventory has some bugs in the display logic. Any small ones can go in this thread for fixing.

* edit of inventory has collapsible sections: in some cases the wrong part is collapsed/expanded
* edit of records has similar but separate issue with collapsible sections
* button styling is not all consistent in some browsers

**Comment by AndrewVSutherland** [comment]
@JohnCremona can we close this issue?

**Comment by JohnCremona** [comment]
@AndrewVSutherland Yes.  I think the sections expand and contract OK and I am not bothered about the 3rd point.
