### ISSUE TITLE
Number field polynomial input crashes on non-integral input

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2420]
I was looking for the field defined by the polynomial x^3-8*x^2-x+8/9 which is mentioned in Lemma 4.13 of https://arxiv.org/abs/1804.06777 but entering that into the search box causes a crash.  This is different from the better (not perfect) message which appears if you enter an integral polynomial defining a field not in the database.
It would not be hard to extend the parsing of that box to allow for this.  Perhaps a job for @koffie ;) unless he wants to change the Lemma instead.

**Comment by JohnCremona** [comment]
Thanks @edgarcosta I managed to find it using Sage's optimzed_representation() method for number fields.
Thanks @jwj61 for offering to fix it.

**Comment by koffie** [comment]
Thanks for fixing the lookup of the troublesome polynomial already on the same day that it appeared in an article on arxiv!

**Comment by JohnCremona** [comment]
I just merged the fix so am closing this.
