### ISSUE TITLE
Search for number fields by signature times out

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2422]
From the bug report system: "Global Number Field search results did not work for signature for [0,3], [0,4]..."
I confirmed this on prod and beta.  It times out, even if you include the degree too (e.g. degree 6 and signature [0,3]).
The existing indices are viewable at http://beta.lmfdb.org/inventory/numberfields/fields/indices/ showing that there is an index on signature and a joint index on signature and degree, so it is not that.  And the signature is stored as a string like '0,3' so I do not know what is wrong, unless something is not right with the code which turns the search box entries into an actual search.  From the command line in Sage,
`fields.find({'signature':'0,3'})`
works fine right away.

**Comment by edgarcosta** [comment]
I'm not sure what is going on. It looks like a database issue, and some mismatch between m0 and ms.

On the ms.lmfdb.xyz (where www.lmfdb.org reads from) the timings are very painful, 30 mins to do the find command and 2.4s for the count.
```
2018-04-20T12:43:27.745+0000 I COMMAND  [conn49589] command numberfields.fields command: count { count: "fields", query: { degree: 6, signature: "0,3" } } planSummary: COUNT_SCAN { signature: 1, degree: 1 } keyUpdates:0 writeConflicts:0 numYields:16968 reslen:62 locks:{ Global: { acquireCount: { r: 33938 } }, Database: { acquireCount: { r: 16969 } }, Collection: { acquireCount: { r: 16969 } } } protocol:op_query 2415ms
2018-04-20T12:52:29.123+0000 I COMMAND  [conn49541] command numberfields.fields command: find { find: "fields", filter: { degree: 6, signature: "0,3" }, sort: { degree: 1, disc_abs_key: 1, disc_sign: 1 }, limit: 20 } planSummary: IXSCAN { signature: 1, ramps_all: 1, degree: 1 } keysExamined:2170099 docsExamined:2170098 hasSortStage:1 cursorExhausted:1 keyUpdates:0 writeConflicts:0 numYields:84402 nreturned:20 reslen:22429 locks:{ Global: { acquireCount: { r: 168806 } }, Database: { acquireCount: { r: 84403 } }, Collection: { acquireCount: { r: 84403 } } } protocol:op_query 1842030ms
```

While from m0.lmfdb.xyz things are way faster, the count takes 0.6s and the find 1.4s.
```
2018-04-20T12:21:05.998+0000 I COMMAND  [conn351636] command numberfields.fields command: count { count: "fields", query: { degree: 6, signature: "0,3" } } planSummary: COUNT_SCAN { signature: 1, degree: 1 } keyUpdates:0 writeConflicts:0 numYields:16954 reslen:62 locks:{ Global: { acquireCount: { r: 33910 } }, Database: { acquireCount: { r: 16955 } }, Collection: { acquireCount: { r: 16955 } } } protocol:op_query 694ms
2018-04-20T12:21:07.848+0000 I COMMAND  [conn351636] command numberfields.fields command: find { find: "fields", filter: { degree: 6, signature: "0,3" }, sort: { degree: 1, disc_abs_key: 1, disc_sign: 1 }, limit: 20 } planSummary: IXSCAN { degree: 1, disc_abs_key: 1, disc_sign: 1 } keysExamined:20 docsExamined:20 fromMultiPlanner:1 cursorExhausted:1 keyUpdates:0 writeConflicts:0 numYields:36 nreturned:20 reslen:21247 locks:{ Global: { acquireCount: { r: 74 } }, Database: { acquireCount: { r: 37 } }, Collection: { acquireCount: { r: 37 } } } protocol:op_query 1416ms
```

if you drop the degree field, then on m0 it takes forever again ~20 mins.
```
2018-04-20T12:42:42.110+0000 I COMMAND  [conn351636] command numberfields.fields command: find { find: "fields", filter: { signature: "0,3" }, sort: { degree: 1, disc_abs_key: 1, disc_sign: 1 }, limit: 20 } planSummary: IXSCAN { signature: 1, class_group: 1, degree: 1 } keysExamined:2170098 docsExamined:2170098 hasSortStage:1 fromMultiPlanner:1 cursorExhausted:1 keyUpdates:0 writeConflicts:0 numYields:137438 nreturned:20 reslen:21247 locks:{ Global: { acquireCount: { r: 274878 } }, Database: { acquireCount: { r: 137439 } }, Collection: { acquireCount: { r: 137439 } } } protocol:op_query 1185700ms
```


In general, perhaps we should decorate any query with max timeout (at least for the live versions), as in for the API queries, see:
https://github.com/LMFDB/lmfdb/blob/master/lmfdb/api/api.py#L263

**Comment by edgarcosta** [comment]
@AndrewVSutherland, do you recall what was the fix? (I'm quite sure you were involved in this)

I should also note that I don't see this as high priority, until we move away from mongo, there will always be queries on the numberfields collections that will take forever.

If desired, I could try to decorate the search queries with a max timeout, just to avoid having the servers spinning around for no good reason.

**Comment by JohnCremona** [comment]
We cannot just give up on this since we know that the search is fast when we can see what is happening (from the command line).  Are we certain that ms has the same indices as m0 and beta?
Do we already add degree to any search which specifies signature?  That couldn't hurt.
Splitting the collection into subcollections by degree sounds very painful, since in many cases one would have to repeat the search 22 times (for degrees from 2 to 23).  We should not have to do that given (again) that mongo can do the search perfectly well.

**Comment by AndrewVSutherland** [comment]
I'm not sure what is going on either, unlike Edgar, I find that direct queries from the mongo command line on ms.lmfdb.xyz to do lookups on signature are fast.  I verified that there is an index on signature+degree, which mongo should (and apparently is, from the command line) be able to use to efficiently handle queries on signature alone.  In the past problems like this have tended to be related to the order of the indexes (just having the same set of indexes is not the same), but given that the searches are fast from the command line, I don't think that is the problem.

I just switched www.lmfdb.org to read from m0, and the queries seem to work reasonably, so this is at least a temporary fix, but it means www.lmfdb.org will be showing whatever data is currently on beta (I don't think this is a problem but if someone knows that it is tell me and I will switch it back).

**Comment by edgarcosta** [comment]
@JohnCremona, wasn't giving up. Just saying that there is an bigger underlying issue that we shouldn't try to fix now.

@AndrewVSutherland, I restarted the mongodb server on ms, and now the queries on degree + signature are quite fast. On just signature are quite slow on both servers (now a bit faster on ms).

In either case, the queries for signature are using the index:
```
{ signature: 1, class_group: 1, degree: 1 }
```
while the ones for degree+signature use:
```
{ degree: 1, disc_abs_key: 1, disc_sign: 1 }
```

Note that the `count` query are much faster, thus I think the main issue here is the sorting of the results, and I think has to do with the fact that it tries to sort by degree first, and the query used doesn't help with that in any way.

I'm quite sure if we had an index:
```
{ signature: 1, degree: 1, disc_abs_key: 1, disc_sign: 1}
```
then most likely both queries will become faster.

and I would also suggest replacing:
```
{ signature: 1, class_group: 1, degree: 1 }
```
by
```
{ signature: 1, class_group: 1, degree: 1, disc_abs_key: 1, disc_sign: 1}
```

**Comment by edgarcosta** [comment]
I'll do it shortly

**Comment by edgarcosta** [comment]
Indexes built on both servers.
lmfdb.org reading again from the production server.

I think the issue is fixed, try it out:
http://www.lmfdb.org/NumberField/?start=0&signature=[0%2C3]&count=20
http://beta.lmfdb.org/NumberField/?signature=%5B0%2C3%5D&ram_quantifier=exactly&count=20

**Comment by edgarcosta** [comment]
That is tricky, as we shouldn't wait forever to see if the query returns something. I see three possibilities:
1- we test it on the local lmfdb with a timeout_decorator (that we would need add to install)
2- test the links above
3- try: `fields.find({'signature':'0,3'}).limit(10).max_time_ms(10000)` and compare it with a given list of labels. (we also need to add the sorting, for consistency and to be realistic)

Note, before, when @JohnCremona  mentioned that `fields.find({'signature':'0,3'})` works fine right away, the issue was that the queries were not sorted, so the cursor was ready to give you the fields with the right signature, by the order that they found them.

**Comment by jwj61** [comment]
I am tempted to make a similar change for other indeces, i.e., add disc_abs_key and disc_sign to all of the indices (for searches returning more than one field).  This would also mean we should increase the number of indices since we would no longer be able to use prefix parts for compound indeces.  Thoughts?

**Comment by edgarcosta** [comment]
> I am tempted to make a similar change for other indeces, i.e., add disc_abs_key and disc_sign to all of the indices (for searches returning more than one field).

That makes sense to me. Indeed that is what I did to abvar.fq_isog, I started by adding their "sorting" fields to the end of every index.
(However, later on  @roed314 noticed that was just easier and more efficient to add a "sort" field, to each entry. I don't think we need to do that, here. )

>  This would also mean we should increase the number of indices since we would no longer be able to use prefix parts for compound indeces. 

I don't follow the last part. Could you please give me an example? That should help me understand what you are referring to.

**Comment by jwj61** [comment]
I did add disc_abs_key and disc_sign to all indices (which return more than one field).  So, consider this a pull request for numberfields.fields, numberfields.fields.rand, numberfields.stats .  I added a few PGL(2,7) fields to keep in sync with the hobbes database.

I considered adding a special sort field.  It would make the indices use less memory, but probably not enough to worry about.

Here is what I meant on compound indeces.  If you have an index for (A, B) (where A and B are individually things like class number, or list of ramifying primes), then it can be used for a user search for A or for the combination A and B.  In this case, you probably also have an index for B.

If we add a sort field to the index to make it (A, B, sort) (and (B, sort)), then the first can be used for A and B together, but it no longer functions for searches on just A because the results are first sorted for B, so you need (A, B, sort), (B, sort), and (A, sort).

**Comment by edgarcosta** [comment]
Thanks for the clarification, and I totally agree with you, that we shouldn't worry about that at the moment.

I'm copying the DBs right now.

**Comment by edgarcosta** [comment]
@jwj61, please double check that everything is in order before I drop the old collections

**Comment by jwj61** [comment]
Looks good.  Thanks

**Comment by edgarcosta** [comment]
done!
