### ISSUE TITLE
Genus 2 template, spacing before "Decomposition"

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2438]
Hello,

I have noticed that there is some weird spacing before the "Decomposition" of a genus 2 curve.
A possible solution is to ecampsolutate the Sato-Tate table with ```<p> </p>.```

See if you agree New (left) vs Old (right):
<img width="643" alt="screen shot 2018-05-09 at 15 14 04" src="https://user-images.githubusercontent.com/322822/39834673-b7c288ec-539b-11e8-8a55-e43be9c9e9f4.png">

**Comment by AndrewVSutherland** [comment]
I agree, new looks better than old

**Comment by davidlowryduda** [comment]
I'm closing this issue now that your update has been merged.
