### ISSUE TITLE
Sage 8.2

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2449]
Upgrade Sage to 8.2 and at the same time upgrade flask-login.

(this is so I don't forget to upgrade flask-login)

**Comment by JohnCremona** [comment]
I have built 8.2 on the beta machine and tested on current master.  I'll upgrade flask-login on that install and run the test again, and if all is well I'll restart beta and lmfdb.warwick.ac.uk's prod server with 8.2, so see how that goes.

**Comment by JohnCremona** [comment]
OK: 8.2 with the old flask_login works fine; with the current master branch and the new flask_login it also works fine.  I'll not do any restarting until tomorrow.

**Comment by edgarcosta** [comment]
Sage 8.2 has been compiled in the prod servers (with the new flask_login).
and we can switch whenever it's appropriate.

**Comment by JohnCremona** [comment]
OK, let me do a push to both beta and prod right now, then I'll upgrade the Sage on beta.  I won't have time for the second stage until tomorrow morning though.

**Comment by JohnCremona** [comment]
I made both PRs but will not merge until the tests pass -- someone else is welcome to do both those merges.

**Comment by JohnCremona** [comment]
Both Warwick servers are now running Sage 8.2: that is, both beta (beta.lmfdb.org) and the prod server lmfdb.warwick.ac.uk.

**Comment by edgarcosta** [comment]
lmfdb.org is now running on sage 8.2
