### ISSUE TITLE
Weil polynomial issues

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2451]
From the feedback page from Stefano Marseglia (stefanom@math.su.se):

I think there is a problem with the search function when setting the initial coefficient to 0 (and eventually something else). It seems that the 0's are ignored.

I believe that the Weil polynomials with real roots are missing from the database.
For example the polynomial (p*x^2-1) does not correspond to an isogeny class of elliptic curves over F_p, but it's square defines an isogeny class of surfaces (over F_p), see (1971, Milne, Waterhouse - Abelian Varieties over Finite Fields, Theorem 8).
I think that polynomials of this form and their multiples are missing.

**Comment by kedlaya** [comment]
For p = 2, I'm not seeing (1-2x^2)^2 in dimension 2 nor (1-2x^2)^4 in dimension 4.

I just checked my original code that generates Weil polynomials and it does pick up this polynomial; so the issue is probably with the code that filters for the Milne-Waterhouse condition.
