### ISSUE TITLE
Gp code for q-series of modular form of elliptic curve

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2454]
From the feedback page (reply to ms639@georgetown.edu):

On http://www.lmfdb.org/EllipticCurve/Q/576/a/1/download/gp?label=576.a1  I used the link to "Download GP code" to get more info. The lines:

\\ q-expansion of modular form:
xy = elltaniyama(E);
deriv(xy[1])/(2*xy[2]+E.a1*xy[1]+E.a3)

are almost correct. The last line is missing an "x*" in front
as the q-expansion begins with "q - 4q^5 ...".

**Comment by JohnCremona** [comment]
That's right, probably my mistake. The identity needed is 2\pi i f(z)dz = dq/q and the "/q" has been forgotten.  I'll fix it...done.
Fixed in #2455

**Comment by JohnCremona** [comment]
I will email ms639 once this is on beta (in a few minutes).
