### ISSUE TITLE
Inventory Editor - sometimes can't change types

### ISSUE THREAD

**Issue by davidlowryduda** [LMFDB/lmfdb#2456]
On some of the inventory pages, it doesn't seem possible to change the types. For example, I cannot change the types on the Hilbert Modular Form `forms` collection (http://beta.lmfdb.org/inventory/hmfs/forms/) through the online interface (http://beta.lmfdb.org/inventory/hmfs/forms/edit/). But I can alter other types sometimes without any problem.

The interface appears to work as expected and displays the `Submitted edits successfully` page and redirect, but the types don't actually change.

**Comment by hratcliffe** [comment]
Immediate bug should be fixed now, I'm not entirely sure whether the proximate cause is already fixed so I'll have to do some more checking.

**Comment by JohnCremona** [comment]
@hratcliffe -- is there a PR or was this fixed by tweaking the database contents?

**Comment by hratcliffe** [comment]
Just the contents. If there is a deeper problem there may be code.

**Comment by JohnCremona** [comment]
OK -- so if @davidlowryduda can confirm that what used not to work now works, we can close this issue.

**Comment by davidlowryduda** [comment]
I still can't seem to change the types on that page.

**Comment by hratcliffe** [comment]
Might have missed some entries, I'll have another look

**Comment by davidlowryduda** [comment]
Thanks --- I have no problems now.
