### ISSUE TITLE
Kloosterman sum compute button on Dirichlet characters not working

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#2465]
If you go to a Dirichlet character page, e.g. http://www.lmfdb.org/Character/Dirichlet/7/3 and enter a pair of numbers in the Kloosterman sum box (e.g. 1,2) and click the compute button nothing happens.  The compute buttons for Gauss and Jacobi sums do seem to work, and the slider for Kloosterman sums does work (but also see #71).

**Comment by JohnCremona** [comment]
PR #2468 fixes this.  However there is more discussion at #71 suggesting that (1) the sliders are unnecessary and (2) we should display the default values when the page loads.  Hence I will keep this issue open even though I will merge #2468 on the grounds that having something working beats it not working, while we decide.

**Comment by davidlowryduda** [comment]
Yes, I was just figuring out how to display default values. (I'm still a javascript neophyte, but I think this is fine).

I haven't removed the sliders. I was unsure whether opinions have changed on their utility. But if we do want to remove them, I know how.

**Comment by AndrewVSutherland** [comment]
I vote that we remove them, I don't think they add any particular value and make the U/I different from the rest of the LMFDB.  If you want to go ahead and add this to your outstanding PR (or a new PR if you prefer), I will review it and then we can close both this issue and #71.

**Comment by davidlowryduda** [comment]
Ok. I've updated my PR to remove the sliders as well.

**Comment by AndrewVSutherland** [comment]
@davidlowryduda, I am reopening this issue, as the character sums are not being hidden for very large modulus characters as they should be, see

http://www.lmfdb.org/Character/Dirichlet/19265902/13392695

for example.

**Comment by AndrewVSutherland** [comment]
Fixed via #2548
