### ISSUE TITLE
Inventory editor wont submit blank string

### ISSUE THREAD

**Issue by hratcliffe** [LMFDB/lmfdb#2467]
Both the page and block submit options for the inventory editing fail to submit a blank box, so it is impossible to remove descriptions etc without leaving a 'space' character or some other placeholder.

**Comment by JohnCremona** [comment]
@hratcliffe this was fixed, right?

**Comment by hratcliffe** [comment]
As far as I can tell it was something to do with having multiple tabs open and the way I implemented persistence. Can close for now with a note that if something like this crops up, the reset button on the inventory editing pages will clear things up and probably fix it.

**Comment by JohnCremona** [comment]
OK, thanks.
