### ISSUE TITLE
Strip self-link from top knowls

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#2514]
Certain objects in LMFDB have "top knowls" that are included into the text of their home pages (e.g., the Leech lattice). Since knowls are context-free, such a top knowl could appear elsewhere.

In general, it would make sense for a top knowl to include a link to its originating page: it is a natural use pattern to learn about an LMFDB object via a knowl and then follow the link to that object's home page. However, when a top knowl for an object is included in the text of that object's home page, it makes no sense to still have a link to that same page. Would it be possible to modify the code that interpolates the top knowl so as to strip out any link to the current page?

**Comment by davidfarmer** [comment]
The updated knows code includes many new tools for making sure knowls are
working properly.  For example, a list of code and other knowls that reference
a given knowl.

I think it would be bad to have knowl content automatically modified in this way.
Such knowls should have their content updated by a person.

Closing this.  If the new tools are somehow inadequate, that can be another issue.
