### ISSUE TITLE
Placement of code blurbs

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#2518]
When you click the Magma code to appear on the genus 2 pages, it awkwardly justifies the data below it:
<img width="713" alt="screen shot 2018-06-27 at 4 03 59 pm" src="https://user-images.githubusercontent.com/4120797/42004220-c7bedb3e-7a23-11e8-87a3-cc84c3391835.png">

(It seems better behaved on other pages, e.g. elliptic curves over number fields.)

**Comment by AndrewVSutherland** [comment]
This is annoyingly not so easy to fix -- the problem is caused by the fast that we are displaying code snippets inside a table.  One option would be to put both code snippets above the table (and perhaps combine them into one code snippet) as on the geometric invariants section.
