### ISSUE TITLE
Incorrect information about Riemann zeta function

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2519]
From the issue tracker from kconrad@math.uconn.edu regarding http://www.lmfdb.org/L/history :

You write that Riemann introduced "the convention that σ is the real part and t the imaginary part of s, i.e. s=σ+it." He did use s and t in the paper, but nowhere in the paper did Riemann ever use a variable for the real part. The σ came from someone else, maybe Landau? I'm not sure, but definitely *not* Riemann. Please don't perpetuate the false story that Riemann used σ.

**Comment by AndrewVSutherland** [comment]
I edited the knowl to address Keith's concern.
