### ISSUE TITLE
Document \cite

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2525]
Maybe I missed it, but \cite does not seem to be documented.  It should give examples of the different ways it can used to illustrate its syntax.

**Comment by AndrewVSutherland** [comment]
The use of \cite is documented in the knowl guidelines, a link to which appears any time someone tries to edit a knowl, See

http://beta.lmfdb.org/knowledge/show/doc.knowl.guidelines

I added this just a few weeks, so it might not have been there when you last looked.

I think this addresses your issue, but I'll leave it to you to review what I wrote and close this issue if you are satisfied (feel free to expand on what I wrote if you think more examples are needed).

**Comment by jwj61** [comment]
I did not see that, and that helps some.  Thanks.

\cite is supposed to do something with href, but I couldn't get that to work, so an example of that would be helpful.  I think I saw someplace that it can take more than one argument, as in \cite{a}{b}, but I am unclear on how that works or when to use it. Finally, the knowl mentions doi, and should give an example.

**Comment by AndrewVSutherland** [comment]
OK, I added examples of citing by doi and using href (FYI the syntax for href is \cite{href{a}{b}}), which I'm guessing is what you were thinking of when you wrote \cite{a}{b}

**Comment by jwj61** [comment]
Thanks
