### ISSUE TITLE
Submitting data

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#2533]
The site still says that to submit data you should request an account  (http://www.lmfdb.org/intro/features).  I don't see a place to submit data when I log in, are we still supporting this?

**Comment by AndrewVSutherland** [comment]
I removed the accounts link from the features knowl -- direct uploading through the website is not supported (there is no longer an upload link anywhere), and there is no way to request an account by simply clicking on the login link.

**Comment by jvoight** [comment]
Perfect, that's what I thought was happening.  Thanks Drew!
