### ISSUE TITLE
Incorrect Galois group data for some local fields

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#2556]
If you go to the local field

   http://www.lmfdb.org/LocalNumberField/101.14.12.1

The Galois group is listed as A7, which is not correct (for example, it is not solvable), and it has the wrong transitive degree.  Searching for Galois group A7 yields 31 local fields with a similar problem:

    http://www.lmfdb.org/LocalNumberField/?gal=A7&count=20

**Comment by jwj61** [comment]
I tracked down the error -- these Galois groups were only partially computed on the JR site, and the upload script was not taught how to deal with that situation.  The data on beta has now been fixed (the collection localfields.fields).

**Comment by AndrewVSutherland** [comment]
Great, I will copy localfields.fields to the cloud shortly.

**Comment by AndrewVSutherland** [comment]
Done.
