### ISSUE TITLE
/L/NumberField/3.1.23.1 files on Travis and locally

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2564]
When testing #2563 I find that my local version running on legendre, even with the master branch, filas 3 L-function tests.   While http://web.lmfdb.xyz/L/NumberField/3.1.23.1/ is fine, when run locally I get an error page showing "Unable to render L-function page due to the following problem(s):
can't multiply sequence by non-int of type 'LmfdbRealLiteral'"

It's not just me since Travis also has the same 3 failures.  We need to track this down as it makes merging pull requests impossible to do with any confidence since Travis fails.

**Comment by JohnCremona** [comment]
10 minutes later and these are working normally so I will probably close this.  Strange.

**Comment by edgarcosta** [comment]
What do you think it could be? 
@roed314, any insight?

**Comment by roed314** [comment]
Where can I find a traceback?  LmfdbRealLiteral is a type I added....

**Comment by edgarcosta** [comment]
I believe this was fixed in #2563. @jwj61 and @JohnCremona, could you confirm that?

**Comment by jwj61** [comment]
Yes

**Comment by JohnCremona** [comment]
... and yes from me.
