### ISSUE TITLE
Downloads for higher genus curves not working

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2577]
On dev.lmfdb.xyz, click on Higher genus, then click on genus 5.

If you then click on "Magma" to download the results in Magma code,
all it seems to do is reload the page.

**Comment by AndrewVSutherland** [comment]
This works correctly on prod.lmfdb.xyz

**Comment by AndrewVSutherland** [comment]
None of the download links (for either magma or gap) on the search results pages for higher genus curves appear to be working properly on beta.lmfdb.org or www.lmfdb.org (but as noted above, they used to work in the mongo db version, as can sill be seen on prod.lmfdb.xyz, so something changed with the switch to postgres).  This is not specific to genus 5.

I also note that the download links at the top and bottom behave differently; neither work but the ones at the top refresh the current page, whereas the ones at the bottom take you to the search results page for an empty query.

@edgarcosta I notice that you self-assigned this PR back in August, any thoughts on what is going on here?

**Comment by jenpaulhus** [comment]
I am on airport wireless atm but I might have a fix for this in my code.  I'll check tomorrow and report back.

**Comment by jenpaulhus** [comment]
I do not have a fix for this.  I'm going to make a pull request shortly which fixes some magma/gap download issues on the higher genus pages, but not from the search result pages.  I don't actually know what's happened with the switch from Mongo to Postgres.  Did you have any thoughts, @edgarcosta?

**Comment by edgarcosta** [comment]
I'm looking into it
