### ISSUE TITLE
Something's wrong with this GL3 Maass form

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#2580]
For http://beta.lmfdb.org/L/ModularForm/GL3/Q/Maass/4/1/18.96015_1.761017/-0.8780527/
the Z-function apparently has zeros off the half-line (and are not explained by the Gamma-factors).

**Comment by edgarcosta** [comment]
This one is served from the db.

Here is the data:
http://beta.lmfdb.org/api/Lfunctions/Lfunctions/?Lhash=s/ModularForm/GL3/Q/Maass/4/1/18.96015_1.761017/-0.8780527/

**Comment by davidfarmer** [comment]
The graph is wrong, probably due to not having enough coefficients.

We need to hide the zeros and graph for this one (and presumably others)

**Comment by AndrewVSutherland** [comment]
The degree 3 conductor 4 L-function plot has been disabled, so this page is no longer reachable (but the data is still in the database and needs to be corrected, all the conductor 4 L-functions need to be reviewed before the plot is re-enabled, I will create a separate (non-critical) issue for this).
