### ISSUE TITLE
Grayed out input on search pages

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#2582]
On search pages, we often put example input into search fields in gray.  We have been given feedback that this is dark enough of a gray that it looks like it's part of the search, and anyway this information is listed to the side of a search box anyway.  

<img width="528" alt="screen shot 2018-08-18 at 9 48 21 pm" src="https://user-images.githubusercontent.com/4120797/44304665-787cc280-a330-11e8-9a57-fc13b4da1189.png">

I happen to like the gray, but I am passing along this issue for discussion.

**Comment by davidfarmer** [comment]
I think this can be made light enough so that it does not distract,
while still being useful.  Assigning myself to look into this.
Note: placeholder, example, and maybe other things, are used as attributes

**Comment by roed314** [comment]
We lightened the gray at some point in the last six months, so I think this issue can be closed.

**Comment by AndrewVSutherland** [comment]
Agreed, I think this issue has been addressed, but let's give @davidfarmer  a chance to comment before closing.
