### ISSUE TITLE
Convert statistics file for higher genus curves with automorphisms

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#2595]
@jenpaulhus 

The file `hgcwa_stats.py` is still using Mongo.  It should be ported to Postgres.

**Comment by jenpaulhus** [comment]
Finally had a chance to look at this file.  It will indeed need to be ported. It plays a similar role as the ec_stats.py file plays for elliptic curves.  

Related to this issue, it looks like there is still a find_one call on line 156 of the lmfdb/higher_genus_w_automorphisms/main.py file,  which I think explains why we didn't notice that the stats were still running with mongo.

For continuity with other pages, I'm happy to have you make these changes, but I can also do it if that would be preferable.

**Comment by AndrewVSutherland** [comment]
It looks like this has been done.
