### ISSUE TITLE
Statistics UI

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#2599]
Currently, statistics pages are static, with a small set of statistics displayed for each collection.  As we add more, we should think about how to display them.  For example, we may want to add searches on statistics.

**Comment by alexjbest** [comment]
I think it would be helpful to be able to limit some of the statistics page as a first step, maybe with sliders like on the old Sage interacts. This would allow one to see if percentages (say of ranks) are increasing or decreasing as the measure used (say discriminant) grows.

**Comment by AndrewVSutherland** [comment]
I think the dynamic stats facility (e.g. http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/dynamic_stats) partially addresses this.  If there are specific features you would like to see added I suggest creating a new issue (tagged as a feature request).
