### ISSUE TITLE
Breadcrumbs on some genus 2 pages are incorrect

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#2607]
For example on <http://postgres.lmfdb.xyz/Genus2Curve/Source> clicking the link to \QQ in the breadcrumb takes you to the same page again (there are other instances like this too).

**Comment by alexjbest** [comment]
This includes the genus 2 search page, which is the most broken of all. I'm not sure what the correct breadcrumb for a search page should be though.

**Comment by AndrewVSutherland** [comment]
Fixed by #2668
