### ISSUE TITLE
Search results should include Nones

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#2615]
To conform to the mongo model that supported records with different sets of keys, the `search` and `lucky` methods in `db_backend.py` do not include columns with NULL value in the results.  We should change this so that the returned dictionaries have the same set of keys.  In order to do so, we'll need to track down places in the LMFDB that rely on raising an `AttributeError` when the column does not exist.

**Comment by rbommel** [comment]
There are currently 44 places where AttributeErrors are detected. It should be possible to change these all with if-constructions instead. Is that what you are proposing?

Is there some particular reason why we want this? Another option could be to have optional parameters for `search` and `lucky` to get also empty fields returned.

**Comment by AndrewVSutherland** [comment]
@roed314 Is this something you still want to see addressed in 1.1.1?  If so we should converge on an agreed solution soon.
