### ISSUE TITLE
Enforce a convention for knowl ids

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#2617]
Priority: Minor.

Currently knowl ids use either - or _ for a placeholder for space, e.g. mf.elliptic.hecke-orbit vs mf.elliptic.cm_form, having to look up which is annoying.

**Comment by alexjbest** [comment]
I guess we could now do this as the rename feature seems good now, I think this is the right list, note that things like q-expansion, atkin-lehner are ok as is.

- cmf.trace-expansion
- cmf.hecke-operator
- cmf.petersson-scalar-product
- cmf.galois-orbits
- ec.q.rouse-classification
- cmf.hecke-orbit    (#2898)
- content.edit-board
- mf.upper-half-plane

**Comment by JohnCremona** [comment]
Warning -- do this with care!  There are knowls whose IDs differ *only* in thhe replacement of - with _.

e.g. ec.mordell-weil: The Mordell-Weil Theorem
ec.mordell_weil: The Mordell-Weil Group

In this example I would rename the first ec.mordell_weil_theorem and the second ec.mordell_weil_group.

**Comment by alexjbest** [comment]
@JohnCremona Wow thanks for the heads up. Hopefully these are the only two like this?! I wasn't proposing changing mordell-weil as like atkin-lehner its a genuine "-" dash in the title not a space. But I think those two should both be changed to mordell-weil_theorem and mordell-weil_group respectively of course!

(I should add that as I'm not an admin I can't do any of this, so its up to a sufficiently motivated person with admin rights for anything to happen here.)

**Comment by roed314** [comment]
Bugs to the rename feature are still waiting for review (#2892).  Once that's merged, I can start the rename process for each of these.  At that point, if you wanted to fix the code references that would be great!

Note that some of these have a distinct version with the non-hyphenated name (e.g. http://beta.lmfdb.org/knowledge/show/cmf.galois_orbit vs http://beta.lmfdb.org/knowledge/show/cmf.galois-orbits) and we need to figure out what to do.

@JohnCremona Note that the rename won't work if there's already a knowl with that name.

**Comment by alexjbest** [comment]
@roed314 it looks like there are no hardcoded references to these knowls anymore! A couple were already done so if the rename script automatically changes references from other knowls this should be doable with just rename now.

The one exception is cmf.galois-orbits duplicating cmf.galois_orbit, the former is still referred to twice in the stats code on lmfdb/classical_modular_forms/main.py, see http://beta.lmfdb.org/knowledge/show/cmf.galois-orbits

**Comment by alexjbest** [comment]
Looks like these are all done now
