### ISSUE TITLE
The page g2c_browse.html is not valid html

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#2618]
Browsers are smart enough to figure most of this out so it is an invisible problem for now. But the table for searching has many unclosed html tags,  g2c_browse.html line 52 for example, there are unclosed td's and span's.

**Comment by alexjbest** [comment]
This more generally runs the question of whether we should run generated HTML through a validator as part of testing, this would help prevent bugs from being introduced (but only if we get a clean state to start from).

**Comment by AndrewVSutherland** [comment]
This problem has been fixed, I will open a separate issue for automated html testing.
