### ISSUE TITLE
When searching from a search results page both the new query and the original (but garbled) show up in the url

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#2621]
On <http://postgres.lmfdb.xyz/Genus2Curve/Q/> for example, searching by conductor (e.g. 169), then changing the parameters on the refine search page sends you to an address like <http://postgres.lmfdb.xyz/Genus2Curve/Q/?start=0&count=50&cond=175&query=%7B%27cond%27%3A+169%7D> which has the junk 169 in from the original query.

**Comment by AndrewVSutherland** [comment]
I am not able to reproduce this problem on www.lmfdb.org, so I'm closing it but please feel free to reopen or create a new issue if you think there is still a problem here (be sure to include explicit instructions on how to reproduce the problem).

**Comment by alexjbest** [comment]
@AndrewVSutherland  Yes it looks like this is now fixed to me.
