### ISSUE TITLE
Lfunctions don't plot when z-function data has spurious imaginary part in

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#2623]
For the new modular forms code on roed314/master plotting some L-functions is broken, for example /L/Plot/ModularForm/GL2/Q/holomorphic/31/4/1/a/1/ , the reason for this is that some of the lfunction data in the database looks like 12.21321313 + 1.1532e^-30*I (for example) and this cannot be automatically converted to a real number.

There are two possible fixes for this:
- Fix the data upload to take real_part() before entering data (better for the database, code complexity)
- Change line 854 of lfunctions/main.py to do something like this, slightly annoying as some elements are correctly read as reals so we have to check whether or not that already happened  (but we won't have to worry in the future about similar bugs)

Thoughts @edgarcosta  ?

**Comment by edgarcosta** [comment]
I will fix this on the upload script.
