### ISSUE TITLE
Reduce header height

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2629]
I think we should reduce the height of the header. 

Below there is a mockup of me doing this by reducing the size of the logo, img and header to about 76px.

What do you think?

<img width="1427" alt="screen shot 2018-09-14 at 17 45 50" src="https://user-images.githubusercontent.com/322822/45577163-a1697800-b848-11e8-8f84-92069d85b5aa.png">

**Comment by AndrewVSutherland** [comment]
I like this idea a lot (although I might tweak the positioning of the logo about, e.g. put a bit more padding on the left).  The current layout wastes vertical space a the top of the page, which is arguably the most valuable real-estate on any web page.

**Comment by davidfarmer** [comment]
I like the smaller logo (hence smaller header) and also think that the 
margins around the logo need some tweaking.

**Comment by AndrewVSutherland** [comment]
One small point (that is already an issue with the current logo but will get worse with a shorter one): if you go to a page where the title is long and make your browser window narrow enough to force the title to span multiple lines, the header does not change size and the title will overwrite other elements on the page.  The vertical height of the header should expand when necessary to accommodate long titles.

**Comment by roed314** [comment]
Another option would be to have the size of the text shrink for long titles.
