### ISSUE TITLE
Request for documentation on modular form web pages

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2630]
From the issue tracker:

An explanation of what the notation for the nebentype characters in the eigenform database would help.  What is \chi(n,_) exactly?

There was no e-mail to respond to

**Comment by edgarcosta** [comment]
I believe this is currently fixed on the new version, see:
http://cmfs.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/334/2/a/b/

We have a knowl for 'Character of a modular form' all throughout and links for the Dirichlet character.

**Comment by edgarcosta** [comment]
When  this is in beta we can close it

**Comment by AndrewVSutherland** [comment]
Addressed by #2717.
