### ISSUE TITLE
Hecke operators, cosets in subset not subgroup

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2631]
From the feedback page (acx01c@gmail.com):

$\Gamma_n(N)$ and $M_2(\mathbb{Z})$ aren't groups.

Also it is worth mentioning how $(n,N) \ne 1$ makes the cosets a little different.

http://www.lmfdb.org/knowledge/show/group.gammann

**Comment by AndrewVSutherland** [comment]
This is fixed in #2717.  The knowl in question is no longer referenced.
