### ISSUE TITLE
Add rename for knowls

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#2634]
It would be nice to not have to delete and rename if you decide to change the name.  Also useful would be a feature to rename a category (e.g. `mf.elliptic` -> `mf.classical`).

**Comment by davidfarmer** [comment]
Is renaming working to the point where we can close this?

**Comment by roed314** [comment]
Not yet.  See #2892.

We also haven't added the feature to rename a whole category.  I think that this action is sufficiently rare that we can do it manually if needed.

**Comment by AndrewVSutherland** [comment]
Closing. This feature has been added and works pretty much as designed.  Specific bugs and/or usability problems should be recorded in separate issues.
