### ISSUE TITLE
Sidebar style on local field pages is a little weird

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#2638]
See the sidebar on <http://www.lmfdb.xyz/LocalNumberField/2.12.32.480> hovering over classical modular forms (say) looks funny on my laptop (pretty average size screen).

This is due to the lines
```
<style>
table,td {  border-right:solid 30px transparent;
} </style>
````
in `local_fields/templates/lf-show-field.html`. These only serve to change the table on the page a little bit.

I would delete them unless someone has an objection, in which case they should be rewritten to more specifically do what they were intended to do.

**Comment by davidfarmer** [comment]
Definitely delete the locally defined style.
If the table on the page needs some new styling,
it can be put back properly.
