### ISSUE TITLE
Reset offset when refining a search.

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#2641]
When re-searching after clicking the "next" button a few times, the new search will start at the same offset rather than 0.

**Comment by alexjbest** [comment]
The somewhat related ticket I hinted at earlier was #2621

**Comment by AndrewVSutherland** [comment]
Just to bump this issue, this really is a bug, and it can lead to some seriously confusing results e.g.

http://www.lmfdb.org/EllipticCurve/Q/?start=50&conductor=11&surj_quantifier=include

which to the unwary makes it look as if either there are no elliptic curves of conductor 11 in the LMFDB, or there are 50 of them but they are not being displayed (note the the download links will all give the correct answer, it is only the screen display that is broken).

(to reproduce, go to the http://www.lmfdb.org/EllipticCurve/Q/, click search, then click next, then enter 11 into the conductor input box, then click search again)

**Comment by JohnCremona** [comment]
I note that if you click on "search again" a second time then start is reset and you see the 3 curves you should.  I agree (of course) that that should be what you see the first time, but this this might help debug.

**Comment by roed314** [comment]
This has been resolved by #3233.
