### ISSUE TITLE
stop switching style of the L-function title according to the normalization?

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2644]
At the moment, we switch math font styles between roman and italic style according to the normalization, e.g:
http://www.lmfdb.org/L/Genus2Curve/Q/535296/a/
http://www.lmfdb.org/L/Character/Dirichlet/2037/104/
http://cmfs.lmfdb.xyz/L/ModularForm/GL2/Q/holomorphic/375/2/32/b/1/

to me, this looks very funky.

If the character is trivial, this isn't an issue, as we can avoid writing $L(s)$ in the title (as we should), as in:
http://www.lmfdb.org/L/EllipticCurve/Q/383040/os/
http://www.lmfdb.org/L/EllipticCurve/2.2.89.1/4.1/b/

However, if the character is nontrivial, the character really looks weird in analytic normalization (roman style)

**Comment by davidfarmer** [comment]
That seems to just have been an oversight, and the math part should
always be italic.

I suspect it was my oversight: in Firefox they look almost
identical.  You must be using Chrome?  My fault for not
checking multiple browsers.

**Comment by edgarcosta** [comment]
Yes, I'm using chrome.

Do you know where is this switch happening?

**Comment by davidfarmer** [comment]
Sorry, no memory.  Feel free to assign this issue to me
and I'll track it down.

**Comment by edgarcosta** [comment]
tks

**Comment by davidfarmer** [comment]
I checked all the listed examples in Firefox, Chrome, and Safari,
and all are fine (and only the Dirichlet L-functions have the title
change with the normalization).  I also checked a few other random
examples.  So, apparently this has already been done.
