### ISSUE TITLE
Unlikely duplication of Maass eigenvalues

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2645]
Three of the four eigenvalues of the level 2 row of this picture
   http://beta.lmfdb.org/ModularForm/GL2/Q/Maass/BrowseGraph/1/10/0/10/
also occur on the level 6 row.

Since those have trivial character in both cases, they are not twists of each other,
so the likely explanation is that one of those is real and one is an error.

Based on the L-functions for R approximately 8.92, the level 2 one is correct and the level 6 is not:
http://beta.lmfdb.org/L/ModularForm/GL2/Q/Maass/4f5556da88aece241f000001/
http://beta.lmfdb.org/L/ModularForm/GL2/Q/Maass/4f5692d788aece2afe000004/

Also, the available prime coefficients different than 2 and 3 appear identical, which
violates multiplicity one.  So the problem is probably due to the source data.

**Comment by davidfarmer** [comment]
There is a similar problem on levels 5 and 10, with R approximately 4.89:
http://beta.lmfdb.org/ModularForm/GL2/Q/Maass/4f55591e88aece264600002f
http://beta.lmfdb.org/ModularForm/GL2/Q/Maass/4f4bf31e88aece438d00000a

Again the coefficients prime to 10 appear identical.  The level 5 forms looks correct.

**Comment by davidfarmer** [comment]
Also, the 8.92... eigenvalue also appears in level 10:
http://beta.lmfdb.org/ModularForm/GL2/Q/Maass/4f4bf31f88aece438d00000f

**Comment by AndrewVSutherland** [comment]
Comment from Toby Gee copied from #2688 related to the same issue:

> 
> From feedback for the page http://www.lmfdb.org/L/ModularForm/GL2/Q/Maass/4f5692c588aece2afe000001/
> 
> I'm not sure this is an error, but it is a confusion to me.
> 
> The above link to the $L$-function of the Maass form of level 6 and $R=5.09874190873$ seems strange, as this Maass form is actually comes from level 3 (with same $R$) linked below, and the $L$-function given just modifies the Euler factor at 2 (and I'm not sure the functional equation is then as stated).
> 
> http://www.lmfdb.org/L/ModularForm/GL2/Q/Maass/4f55571b88aece241f000013/
> 
> On the holomorphic side, you require newforms. For Dirichlet characters you take primitive ones. Why is the Maass case different? Maybe I missed the pulldown window where it was explained.
> 

We need to remember to let Toby know once this problem has been fixed (David Farmer is working on this now, the plan is to remove the duplicates once we have correctly identified them all).

**Comment by AndrewVSutherland** [comment]
The 525 duplicate forms identified by @davidfarmer have been removed (both on beta and production)

**Comment by davidfarmer** [comment]
Whoever wrote to Toby Gee should reply again, saying words to the effect of:
Those values were incorrect due to a problem with the database.  We believe
those errors have been corrected.

If nobody ever wrote to him, then I guess someone should now!  (and then reclose this issue)

**Comment by AndrewVSutherland** [comment]
I just wrote to Toby Gee.
