### ISSUE TITLE
Provide intrinsic labels for Maass forms

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2646]
The URL of a Maass form on Gamma_0(N) looks like this:
       ModularForm/GL2/Q/Maass/4f55591e88aece264600002f/   .
It is possible to give that object a meaningful label by replacing the
hash-like string by slash-separated numbers indicating that the level
is 5, the character is trivial, the form is odd, and when such forms are
ordered by Laplace eigenvalue, it is the 3rd such form.

**Comment by davidfarmer** [comment]
I assigned myself and added the L-functions label because I think that the planned scheme for
labeling L-functions (which I am in the midst of doing for degree 3 and 4 Maass-type L-functions)
can/should be an exact parallel for the Maass form labeling scheme mentioned above.

**Comment by davidfarmer** [comment]
Pointing out that this is related to #2876

**Comment by AndrewVSutherland** [comment]
Just to clarify what I wrote above, there is L-function data for GL3 and GL4 maass forms in the LMFDB, see https://www.lmfdb.org/L/?origin=MaassGL3, for example, and these have intrinsic labels; the Maass forms themselves do not have pages (but if/when they do, I would expect them to be given intrinsic labels and I don't think we need to keep this issue open to ensure that).
