### ISSUE TITLE
EC/Q: show surjectivity of 3-adic Galois representation

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2659]
Enrique Gonzalez Jimenez writes:
```I was thinking that it will be interesting to add the following to LMFDB.

For any non-CM elliptic curve over Q at the database the primes such 
that the p-adic Galois representation is non-surjective:
* If p>3 is equivalent to the non-surjectivite of the mod p Galois 
representation. Then that info is already at LMFDB.
* If p=2 is already too. In fact there is more info, since Rouse and 
Zureick-Brown have added the imagen of the 2-adic Gal.rep.
* p=3 is the remaining case. But it is very easy to check if the 3-adic 
Gal. rep is non-surjective. See the Elkies's paper 
https://arxiv.org/abs/math/0612734. I have already computed this if you 
want to add to LMFDB.

**Comment by roed314** [comment]
I think this has been done, with the adelic image data that's now present.  Perhaps the one missing piece would be the ability to search for non-maximal p-adic image for a given p.  This would just be searching for curves where the adelic level was divisible by p, so it's not hard to implement.

**Comment by JohnCremona** [comment]
I agree that the original request for more data to be displayed is now met (and a lot more than met), so let's close this.  Adding further things to search on is a different feature request  -- but @roed314 we do already have (in the Advanced Search) a box to ask for non-maximal mod ell image, I think?

**Comment by AndrewVSutherland** [comment]
@JohnCremona is right, and not just non-maximal mod ell, non-maximal ell-adic (a distinction that is relevant for 3, one can maximal mod-3 image but non-maximal 3-adic image).  This was already available even before we added the adelic image/level data (the ell-adic image data is based on RSZB), I think we could have closed this a while ago.
