### ISSUE TITLE
Change use of "p" tags in TOC

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2661]
If pull request #2660 is accepted, then the "GL(3)" and "Other" in the beta TOC will
not be rotated.

It is not that simple to fix the problem because the class to rotate is on an HTML "p",
and the class for beta is on a "div" inside that "p".  But an HTML p is not allowed to
contain a div, so the browser closes the p when it sees the div, so the contents of
the div do not get rotated.

One possibility is to change the "p" to a "div" and update the CSS so that the appropriate
style now applies to that div.  Before doing that, I want to look if there are other structural
changes that should be made to the TOC.  (With the goal of not actually changing what
it looks like, but maybe making it easier when the time comes to discuss changes.)

**Comment by JohnCremona** [comment]
+1 to having a new look at the TOC (AKA sidebar).  When we redid this a 2 or 3 years ago we ended up with a very simple yaml config file + simple code to read and process that, but at the bottom is a horrendous template where all the logic really happens.  And that template is rendered on every single page, despite the fact that it is the same on all pages.  I am partly to blame for the current setup, I know.
