### ISSUE TITLE
Some Hilbert/Bianchi modular form L-functions incorrectly marked not available

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#2662]
L-functions of elliptic curves over quadratic fields are now available in the LMFDB, and while the elliptic curve and L-function pages both list the corresponding Hilbert/Bianchi modular form as friends, the home page of the Hilbert/Bianchi modular form still says the L-function is not available.  For Hilbert/Bianchi modular forms over quadratic fields, this is no longer true.

Examples:

http://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.8.1/98.1/a/
http://www.lmfdb.org/EllipticCurve/2.0.8.1/98.1/a/
http://www.lmfdb.org/L/EllipticCurve/2.0.8.1/98.1/a/

http://www.lmfdb.org/ModularForm/GL2/TotallyReal/2.2.497.1/holomorphic/2.2.497.1-4.1-d
http://www.lmfdb.org/EllipticCurve/2.2.497.1/4.1/d/
http://www.lmfdb.org/L/EllipticCurve/2.2.497.1/4.1/d/

**Comment by edgarcosta** [comment]
Duplicate with #2262?

I know how to fix, but not on my priority list.

**Comment by AndrewVSutherland** [comment]
I don't think this is a duplicate of #2262, it's simpler (at one point none of the Hilbert/Bianchi modular forms had L-functions in the LMFDB, now those over quadratic fields do, they just don't know it).

**Comment by AndrewVSutherland** [comment]
Addressed by #2957
