### ISSUE TITLE
Incomplete documentation in db_backend.py

### ISSUE THREAD

**Issue by csbrady-warwick** [LMFDB/lmfdb#2663]
Currently the functions in db_backend.py have docstrings but only some of them include full interface documentation.  In particular several public (non underscored, such as delete) methods of classes do not include interface docs. Several other docstrings are not consistent with their actual implementation (e.g. upsert has optional Parameter commit that is not documented, as does _swap_in_tmp but reload_revert does document the same parameter, cleanup_from_reload documents a commit parameter that is not present in the interface).

Attributes of classes are not documented, even nominally public ones such as PostgresTable.search_table, which would also be helpful.

**Comment by AndrewVSutherland** [comment]
Resolved by #3525.
