### ISSUE TITLE
Hypergeometric motives monodromy latex escaped too much?

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#2679]
See <http://cmfs.lmfdb.xyz/Motive/Hypergeometric/Q/A10.10.2_B12.4.1.1.1> under monodromy there is "operatorname" as in the database the monodromy data has latex \ escaped as "\\\\\\\\", which comes out as "\\\\" in the html.

**Comment by jwj61** [comment]
I will take care of it.  We have seen other cases like this where the extra backslashes were introduced in the switch from mongo to postgres.

**Comment by AndrewVSutherland** [comment]
Fixed by PR #2681
