### ISSUE TITLE
y instead of sqrt(y) in Maass-Fourier expansion?

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2689]
From the feedback page for http://www.lmfdb.org/knowledge/show/mf.maass.mwf.fourierexpansion :  

In the definition of Fourier expansion of a Maass form, the sources I read have $sqrt(y)$ instead of $y$. Is the LMFDB renormalization intentional?

No name or e-mail address was given with the feedback, but it was one of three left in succession, the last listed tobygee@fastmail.com

**Comment by davidfarmer** [comment]
It should be \sqrt{y}.  I corrected the knowl.
