### ISSUE TITLE
search option to filter CM number fields fields

### ISSUE THREAD

**Issue by tscholl2** [LMFDB/lmfdb#2697]
It would be nice if there was an option to filter global number fields by whether they are CM.

**Comment by jwj61** [comment]
Sure.  We are not displaying it now because the CM field was introduced in the postgres conversion.  If it is used, then we need to be sure to not push it to the main server until that uses postgres.

**Comment by edgarcosta** [comment]
@jwj61 Okidoki, we have not yet started to use prod.lmfdb.xyz, before we do, most likely we will copy the nfields table.

@tscholl2, Given your shown interest in doing it yourself.
Here is how I would do it:
1- Display if a field is CM or under the invariants and properties box 
Under invariants the knowl to use is`ag.cm_field`
This would be done by editing:
- the template: https://github.com/LMFDB/lmfdb/blob/master/lmfdb/number_fields/templates/number_field.html
- and the function that calls the template https://github.com/LMFDB/lmfdb/blob/master/lmfdb/number_fields/number_field.py#L335

2- Add the search by CM
This amounts to edit the 3 files:
- https://github.com/LMFDB/lmfdb/blob/master/lmfdb/number_fields/templates/number_field_search.html
- https://github.com/LMFDB/lmfdb/blob/master/lmfdb/number_fields/templates/number_field_all.html
- https://github.com/LMFDB/lmfdb/blob/master/lmfdb/number_fields/number_field.py#L693

Let me know if you have any questions.
I'm happy to give more details and answer questions.

**Comment by tscholl2** [comment]
Ok I think I am getting pieces of it. My plan for the search is to use a `<select>` with three options: `""`, `"true"`, and `"false"`.

Does the [`WebNumberField`](https://github.com/LMFDB/lmfdb/blob/fa39b0e46b1a5e16c2145641708649141bd892d9/lmfdb/WebNumberField.py) class also need a `is_cm` method?

**Comment by jwj61** [comment]
Yes, add the method to WebNumberField and then use it.

I don't like blank as an option for the select.  See the CM select for elliptic curves.

**Comment by AndrewVSutherland** [comment]
Agreed, blank should be avoided on selects.

**Comment by edgarcosta** [comment]
To be clear, the default value of the select should always be "", what you put on the text is up to you.
Otherwise, clean_submit that cleans up the url by removing superfluous constraints doesn't remove that constraint.

For example, Elliptic curves does that wrong with `surj_quantifier` and even if you don't specify anything your URL always looks like:
http://beta.lmfdb.xyz/EllipticCurve/Q/?surj_quantifier=include&count=100

**Comment by tscholl2** [comment]
Ok I changed the wording of the `<option>` label's to match that of elliptic curve CM search: `"Include"` (value `""`), `"Only"` (value `"True"`), and `"Exclude"` (value `"False"`).

I couldn't find where to add the `KNOWL`s used to "transclude" the definitions and other info. Any tips?

I was also going to add snippets to [code.yaml](https://github.com/LMFDB/lmfdb/blob/master/lmfdb/number_fields/code.yaml) but I couldn't find the right pari command. Does anyone happen to know how to check if a number field is CM in pari? I'm pretty sure `HasComplexConjugate` is the right command for magma.

I also added an `is_cm` method to the `WebNumberField` class. I assumed it was contained in `self._data['is_cm']`, but when I looked up `self._data` and `db_backend` I couldn't check for certain. Will this work or am I missing where the data is stored?

**Comment by jwj61** [comment]
Normally knowls are put directly into the template files.

I don't think there is a single simple command in pari.  If the polynomial is f, then

  (poldegree(f) % 2)==0 && polsturm(f)==0 && #select(u->u==poldegree(f)/2, apply(z->polsturm(z[1]), nfsubfields(f,poldegree(f)/2)))

should do it, but I am not sure how helpful it is to the reader.

As to where things are in the database, see the postgres faq to see how to inspect entries for a given field.

**Comment by AurelPage** [comment]
That's actually a function we were already considering adding. More precisely, we were even considering adding a function that computes the largest CM subfield of a given number field, but we don't know an efficient algorithm for computing this (only one that is exponential in the worst case). Any idea ?

**Comment by jwj61** [comment]
Done by #2970
