### ISSUE TITLE
ECNF labels: missing label knowl link and unclear knowl

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2707]
- [ ] The word `label` in `Find a specific curve by label` on the browse page for ECNFs should point to to the knowl `ec.curve_label`. (this we can leave it open as a first issue for someone)

- [x] The knowl `ec.curve_label` doesn't explain the `CM` in the isogeny class label.

**Comment by JohnCremona** [comment]
I'll handle the second point by editing the knowl.

**Comment by JohnCremona** [comment]
I have expanded the ec.curve_label knowl, and switched its status from Reviewed to Beta.  I'm sure that further improvements are possible, but at least it now explains why there is sometimes CM in the label -- but not for all curves with CM!

**Comment by edgarcosta** [comment]
Thank you!

**Comment by AndrewVSutherland** [comment]
Addressed by #3180.
