### ISSUE TITLE
Top/bottom knowls for abelian varieties

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#2714]
Isogeny classes of abelian varieties over finite fields do not currently support top/bottom knowls. I would like to add some of these during the IAS workshop in March.

**Comment by JohnCremona** [comment]
Lines 58-59 of https://github.com/LMFDB/lmfdb/blob/master/lmfdb/elliptic_curves/templates/ec-curve.html show how to add this for the top knowl, and lines 633-634 for the bottom.

**Comment by davidlowryduda** [comment]
Am I correct to think that this can be closed now that #2715 has been merged in?

**Comment by kedlaya** [comment]
Yes. There will be a separate thread at some point to implement top/bottom knowls for arbitrary objects, which might actually render this redundant, but so be it.
