### ISSUE TITLE
knowl for a Z-function of an L-function

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2716]
Aren't we missing some stuff for the Z-function knowl?
http://beta.lmfdb.org/knowledge/show/lfunction.zfunction
It seems this was written for the Riemann Zeta function, and then adapted for self-dual L-functions.
But for non-self-dual L-functions, we need to involve the root number to make sure that the Z-plot is real.

I ran this by @davidfarmer, and he will addess it in the March workshop.

**Comment by davidfarmer** [comment]
Brian edited the knowl and it seems okay now.
