### ISSUE TITLE
DB backend upsert routine has no way of returning id

### ISSUE THREAD

**Issue by hratcliffe** [LMFDB/lmfdb#2745]
DB backend upsert routine should return the content of the found or created record. (In particular, for tables where it exists, the unique id should be returned.)

Ideally it should also indicate whether an update or an insert was performed.

**Comment by roed314** [comment]
Good idea.  I can try to do this next week or I'm happy to review a change if you want to take a stab.

**Comment by edgarcosta** [comment]
This was resolved by #2914
