### ISSUE TITLE
DB backend equivalent of find_and_modify

### ISSUE THREAD

**Issue by hratcliffe** [LMFDB/lmfdb#2747]
As far as I can tell, there's no analogue of the Mongo find_and_modify (update a record only if it exists) and I'd rather not do a manual combination of find and then an upsert since that is a lot of wasted effort given how the upsert already is doing two ops. 

This is pretty essential for the inventory. 

Sorry if I've missed any recent changes/additions.

**Comment by roed314** [comment]
I don't think it's there at the moment.  I can try to take a look next week while at the workshop at IAS, or you should feel free to write one and I can review it.

**Comment by roed314** [comment]
Does the `update` method not do what you need?

I don't think I'm going to implement this as a new method soon, but I can review something if you want to write it.

**Comment by roed314** [comment]
I'm closing this since I'm not intending to implement it.  I think there are other avenues for changing records, and the inventory is not currently being used.
