### ISSUE TITLE
Related object links from Artin representations to weight 1

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#2754]
Add related objects links from Artin representations back to weight 1 forms.  For example, http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/23/1/b/a/ has a link to http://www.lmfdb.org/ArtinRepresentation/2.23.3t2.1c1 but there is no link back.

**Comment by edgarcosta** [comment]
Perhaps we could achieve this by adding L-functions instances for Artin representations and use that table to figure out additional friends for Artin reps.

**Comment by AndrewVSutherland** [comment]
Given that we just addressed #433, we should address this for release 1.1.  Friendships really should be mutual.

Additionally, the Artin rep has its own (dynamically computed) L-function.  We are planning to address this in the July Bristol workshop, but for Artin reps that correspond to weight 1 modular forms in the database, we could link their L-functions to the CMF L-functions (if the Artin rep knows its friend, it also knows its friend's L-function).

**Comment by edgarcosta** [comment]
Does #2930 address this issue completely?

**Comment by AndrewVSutherland** [comment]
Yes, I think this can be closed (but we still want to change the embedded CMF pages so they link only to the artin rep with the same L-function).
