### ISSUE TITLE
Hecke polynomials for small primes on newform and newspace pages

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#2759]
It would be nice to see the characteristic polynomial of Hecke operators for several small primes (e.g. 2, 3, 5 and 7).  This could be done both for spaces and forms, for dimension up to some bound (e.g. 100).  For forms of dimension up to 20, this information is present in the algebraic q-expansion, but not easily extracted.

**Comment by jvoight** [comment]
Agree with this!  Especially for spaces, this was one of the first things that people tabulated, and it is a nice snapshot of all the forms in a space.

**Comment by edgarcosta** [comment]
FYI, the data is available in the table `mf_hecke_lpolys`, see  http://www.lmfdb.org/api/mf_hecke_lpolys/

**Comment by jvoight** [comment]
@edgarcosta, does that make this a good first issue for tomorrow or another LMFDB Friday?

**Comment by edgarcosta** [comment]
I think so.
Do we agree that we would like the display to look like HGM families at the
end of the page?
eg: https://beta.lmfdb.org/Motive/Hypergeometric/Q/A14.2_B8.3.1

**Comment by assaferan** [comment]
Hi, I'll be taking this one

**Comment by assaferan** [comment]
This is resolved in pull request #3700.

**Comment by assaferan** [comment]
@roed314 - do you agree we can close this issue?

**Comment by roed314** [comment]
I see them on newform pages, but somehow they're no longer present on [newspace](https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/117/6/a/) or [full $$\Gamma_1(N)$$ spaces](https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/117/6/).  I see the changes in #3700, but they seem not to be there anymore, so I'm not sure what happened.

**Comment by assaferan** [comment]
If you look at [Drew's remark](https://github.com/LMFDB/lmfdb/issues/4196#issuecomment-72345993) on issue #4196 you will see that Barinder followed through and removed them from the spaces pages.

**Comment by roed314** [comment]
Great.  Closing.
