### ISSUE TITLE
Analytic conductors for L-functions

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#2761]
[Analytic conductors](http://www.lmfdb.org/knowledge/show/cmf.analytic_conductor) for classical modular forms were motivated by a notion from L-functions, but the homepages for L-functions don't display this quantity.

**Comment by davidfarmer** [comment]
This information should be in the database so it can be easily inserted into the page
(and also searched on).

**Comment by edgarcosta** [comment]
This was done in #4335
