### ISSUE TITLE
Bread for L-functions of Maass Forms

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#2766]
The bread on [this page](http://www.lmfdb.org/L/ModularForm/GSp4/Q/Maass/1/1/12.46875_4.720951/1.34260324/#footer) is pretty ugly.

**Comment by davidfarmer** [comment]
In the next week, let's sort out the labels of Maass-type L-functions.

**Comment by AndrewVSutherland** [comment]
I think this issue is covered by #2827, closing.
