### ISSUE TITLE
Fix L-function links for Bianchi modular forms and Hilbert modular forms

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#2768]
For example, if you go to [this elliptic curve](http://www.lmfdb.org/EllipticCurve/2.0.11.1/11.1/a/1), it has links to its [L-function](http://www.lmfdb.org/L/EllipticCurve/2.0.11.1/11.1/a/) and to the associated [Bianchi modular form](http://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.11.1/11.1/a/), but the Bianchi modular form doesn't have a link to the L-function.

Similarly for [Hilbert modular forms](http://www.lmfdb.org/L/EllipticCurve/2.2.5.1/441.1/d/).

**Comment by edgarcosta** [comment]
and also for Artin L-functions (however, those might be addressed in an upcoming workshop)

**Comment by AndrewVSutherland** [comment]
Duplicates #2662
