### ISSUE TITLE
Remove input boxes for changing count from refine search results

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#2771]
There not be an input box for changing count when refining search results, since this screws up the Prev and Next buttons.  For example, if you go to http://www.lmfdb.org/NumberField/?start=50, change the `number of fields to display` box to 5, then click next, you'll see results 56-60.

**Comment by jwj61** [comment]
I thought this used to work.  Is it unfixable?

**Comment by edgarcosta** [comment]
@roed314 and @jwj61 perhaps you should talk about this in person

**Comment by AndrewVSutherland** [comment]
It has been agreed that the number of results to display input box will be removed from all refine search results pages (it is not really necessary and it takes up valuable screen real estate).

This means we don't have to fix this bug (which really is a bug, it did work at one point), but we do have to fix the somewhat related problem #2641.

**Comment by jwj61** [comment]
This was done for number fields, so removing the nf label

**Comment by roed314** [comment]
Fixed by #3233.
