### ISSUE TITLE
Site potentially blocked by phishing filters

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2775]
From the feedback page:

Dear LMFDB folks,

I just wanted to give you guys a heads up: the url http://lmfdb.org was recently blocked by the Cornell campus network due to suspicion as a phishing site. (Like many universities, Cornell is a big target for such attacks.) From corresponding with the IT Security office, they told me that the reason was that many phishing sites use the .xyz top level domain, and that http://lmfdb.xyz was caught in their their automatic blocking. (I did not know that http://lmfdb.xyz was even an alternative way to access the LMFDB.) This rendered the entire database totally inaccessible (even through the usual domain http://lmfdb.org/) from the campus network, and even a manual override was impossible.

It is now accessible for us due to the domain being whitelisted at my request, but I don't know how prevalent such automatic blocking is. I'm not sure what the best course of action to prevent such things from occurring in the future, but I just wanted the appropriate people to be aware of this. 

Thanks!

- Brian
bwh59@cornell.edu

**Comment by edgarcosta** [comment]
@davidfarmer, would you mind giving us control of the domain name `lmfdb.org` so it is managed through google cloud? 
See: https://console.cloud.google.com/net-services/dns/zones?project=lmfdbmirror

**Comment by edgarcosta** [comment]
We now point directly to ip addresses, and thus this shouldn't be an issue anymore
```
for domain in "" "beta." "www."; do dig +nostats +nocomments +nocm ${domain}lmfdb.org  ; echo ; done
;lmfdb.org.			IN	A
lmfdb.org.		85	IN	A	35.241.19.59

;beta.lmfdb.org.			IN	A
beta.lmfdb.org.		247	IN	A	18.1.37.31

;www.lmfdb.org.			IN	A
www.lmfdb.org.		300	IN	CNAME	lmfdb.org.
lmfdb.org.		300	IN	A	35.241.19.59
```
