### ISSUE TITLE
Formulas knowls not appearing on MF home page

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2783]
Several modular forms have "formulas" knowls, which generally record things
like eta product representations.

These used to have a place on the home page of those modular forms,
but now do not appear.

Search for "formulas" in a knowl label, such as:
mf.11.2.1.a.formulas

**Comment by AndrewVSutherland** [comment]
Yes, these should be annotations (top or bottom knowls).  Something to work on this week...

**Comment by davidfarmer** [comment]
Actually, they are not top or bottom: they go in the middle
of the page (at least, that is where they used to be).  After
the q-expansion if I recall, because they give an alternate
expression for the funciton.

**Comment by alexjbest** [comment]
I talked with @roed314 about this a while ago.

I had some difficulty finding a nice reference for these, possibly you both know more than this off the top of your head?! But this is what I found last time I looked:

In fact the best reference I found was a project of Henri Cohen at a Luxembourg summer school, http://math.uni.lu/nt/summerschool2018/Cohen-MF-project5.pdf which comes with answers: http://math.uni.lu/nt/summerschool2018/projectanswer5.pdf . In exercise 2 he lists all possible eta *products* giving 28 in total (so this does not include quotients like http://www.lmfdb.org/knowledge/show/mf.80.2.1.b.formulas), this (I guess) matches up with the 21 *products* we have as knowls currently, plus 7 new ones for weight 1 that should be added now.

Finally in his answer for exercise 7 he has written a gp function `mfisetaquo` to test whether  a given form is an eta *quotient*, I guess we should be able to run this on some range to check for more quotient formulas.
For instance his example there is http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/16/4/a/a/ which does not appear to have ever had a knowl on the lmfdb (maybe it was outside the range before, now the old ones have gone I have forgotten what was there before). This also appears in Table 1 of <https://arxiv.org/pdf/1805.00544.pdf>.



There is a also a book called Eta Products and Theta Series Identities by Günter Köhler which looks like it may have things of interest in but to me it was quite difficult to read.

**Comment by davidfarmer** [comment]
The point of the formulas knowls was to record interesting formulas.
It was meant to be edited by a person, not generated automatically.
Eta products were just one example of an interesting formula.

It would be good to discuss what to do in general, as one of the 
themes of this week's workshop is to add interesting anomalous
information.

In most cases (in my opinion) the top knowl is not the right place
to record that information:  that location is too prominent.

**Comment by AndrewVSutherland** [comment]
@davidfarmer Agreed.  The top knowl should be short, preferably one sentence (we discussed this last week as part of the annotation guidelines that I believe Kiran is going to review today).  More detailed information and/or discussion should go into the bottom knowl.

In this particular case, I can see an argument for having the modular form home page template displaying a formula knowl in the q-expansion section, although I think it would also be fine to put it in the bottom knowl (which would have the feature of treating it in the same way as other annotations -- this would be useful, for example, in that it would be included in annotation browsing features).  Another option would be to address this kind of situation more generically and have "center knowls" in addition to top/bottom knowls that would be applicable to objects whose home page anticipates them.

@alexjbest Thanks for digging into this!  There are definitely more formulas out there than the ones we currently have knowls for.  Knowls that are claiming a non-trivial mathematical identity need to cite a reference, so if you feel inclined to add these to the formula knowls we have (as well as adding new ones), that would be great!

**Comment by JohnCremona** [comment]
I see that the top and bottom knowls are now handled by the homepage.html
template and will appear automatically if the macro KNOWL_ID is set in the
render_template call.  This would not work for "middle-knowls" since the
placing will depend on the type of object (and wil be absent for most
anyway).  But it would still be very easy to include a knowl in the body of
any page just by including something like
`<h2>{{ KNOWL_INC(KNOWL_ID+'.middle', title='') }}</h2>`
in the template.

**Comment by JohnCremona** [comment]
I see that the top and bottom knowls are now handled by the homepage.html template and will appear automatically if the macro KNOWL_ID is set in the render_template call.  This would not work for "middle-knowls" since the placing will depend on the type of object (and wil be absent for most anyway).  But it would still be very easy to include a knowl in the body of any page just by including something like
`<h2>{{ KNOWL_INC(KNOWL_ID+'.middle', title='') }}</h2>`
in the template.

**Comment by davidfarmer** [comment]
Not sure about "middle" knowls in general.  For classical mf, there was a
request for recording special formulas for various examples.  Hence the
"formula" knowl.

Are there other objects which have similad needs?

**Comment by kedlaya** [comment]
It looks like there already exist knowls for the eta products, e.g., mf.11.2.1.a.formulas. Given that this is a sporadic function (there are a couple dozen of these), I would propose that these appear as bottom annotations.

**Comment by edgarcosta** [comment]
Should we rename all this knowls as bottom?
http://beta.lmfdb.org/knowledge/?search=mf%5C.%5B0-9%5D%2B.%2Bformulas&regex=on

Or should we just make a special case for mf?

**Comment by davidfarmer** [comment]
I like these as a special case, and I would not rule out the possibility
that other objects have some special formula-like knowls in the middle of 
the page.

But I wouldn't mind hiding them when browsing knowls (like the way
we hide bottom knowls by default).

**Comment by AndrewVSutherland** [comment]
I think I prefer Kiran's suggestion that they be bottom knowls; there are 281,219 newforms in the database, of which we have eta formulas for 25 of them.  I don't think its worth adding special code and to display them (it might be a bit tricky to add a "middle knowl link" to the standard template for object pages and it would look a bit weird when browsing on beta while logged into to have unused middle knowl links on almost every page)

They also need citations (or we need to add information about how they were computed to the source page).

**Comment by edgarcosta** [comment]
The knowls have been converted to bottom knowls, and @alexjbest will add the references later

**Comment by edgarcosta** [comment]
Just to be clear we are now only missing the references, and you can find all the knowls here:
https://beta.lmfdb.org/knowledge/?search=%5Emf.%2Bbottom&regex=on

**Comment by edgarcosta** [comment]
Formulas missing from Table 1 https://arxiv.org/pdf/1805.00544.pdf:
[x] 8.4.a.a
[ ] 36.4.a.a
[ ] 16.4.a.a
[ ] 72.4.a.b
[ ] 27.4.a.a
[x] 9.4.a.a
[ ] 108.4.a.a
[ ] 144.4.?
[ ] 216.4.?
[ ] 25.4.a.b
[ ] 128.4.?
[ ] 200.4.?
[ ] 864.4.?

**Comment by edgarcosta** [comment]
Before addressing the weight 4 forms above, we should add references to the forms for which we already have the product:
https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/interesting_newforms
and put the formula in display math mode.

**Comment by edgarcosta** [comment]
Do we need a reference for all the eta products? Can't one simply verify that the eta product and the q-expansion match up to the sturm bound?

**Comment by davidfarmer** [comment]
Lots of people (including me) have found these just by manipulating series.
So, I don't see a need for a reference.

**Comment by AndrewVSutherland** [comment]
If there is a reference, it would be good to cite it.  If not, I think we still need to verify them (to detect typos if nothing else).

**Comment by edgarcosta** [comment]
I'm now searching for all the eta quotients, and there seem to be plenty of them  (still running: https://gist.github.com/edgarcosta/cbf20455a24a7d29db9acf1062b6c2c4)
However, I wonder what is our threshold for stop adding these as bottom knowls, and make it a database column.

**Comment by edgarcosta** [comment]
It seems that https://www.ams.org/tran/1996-348-12/S0002-9947-96-01743-6/ gives the ultimate list.

**Comment by AndrewVSutherland** [comment]
@edgarcosta, @alexjbest  Wonderful!  Now we have a reference.

In answer to you earlier question @edgarcosta, I don't think we should make this a column in mf_newforms (that table is populated by code that is reading external datafiles in the format defined [here](https://github.com/JohnCremona/CMFs/blob/master/README.md).  But I would be fine with making a separate table for it.

**Comment by davidfarmer** [comment]
Not sure what is planned for these references, but putting a reference on
every eta product/quotient knowl does not sound right to me.

1) Someone found the first examples.  Maybe Ramanujan for the Delta 
function?

2) There are some other notable examples, such as the eta product
associated to the elliptic curve of conductor 11.  Not sure who first
observed that.

3) Various other examples are easy to find, and are a natural thing to
look for when you write code to generate modular forms.  Many examples
were found without computers, but probably not all.  Similar to the
legal term "inevitable discovery", it is hard to justify crediting
anyone for these.

4) The research problem is:  prove that the list of known eta expressions
is complete.  There is a paper that does this for eta products.
And then there is a later paper (by Yves Martin, which Edgar referenced)
which does this for eta quotients.  I don't think either of those papers
should get credit for any individual eta products or quotients (except
maybe if some new ones were discovered in the course of the proof).

What strikes me as reasonable, is to expand the eta products knowl to
include a discussion of the history, or make a "history of eta products"
knowl referenced in the eta products knowl.

**Comment by davidfarmer** [comment]
If I recall correctly, every eta product is in a one-dimensional
space.  So there is no issue about the Sturm bound:  you only have
to confirm that it transforms appropiately.

**Comment by edgarcosta** [comment]
I think we are losing track of the point.
There are 43 eta quotients according to Yves Martin's paper.
I can tell you I will not copy those by hand, and indeed I'm running overall dimension one newforms to make sure that there are only 43. I already found 43, so hopefully it matches.
I will also not write 43 knowls by hand. Indeed, is not clear to me that these should be knowls at all. Maybe one can write some knowls for some particular cases, but honestly, the eta quotient formulas should be generated from data stored in a  yaml file or a table.
Here are the 43 quotients, I found so far:
```
{'23.1.b.a': {1: 1, 23: 1},
 '44.1.d.a': {2: 1, 22: 1},
 '63.1.d.a': {3: 1, 21: 1},
 '80.1.h.a': {4: 1, 20: 1},
 '108.1.c.a': {6: 1, 18: 1},
 '128.1.d.a': {8: 1, 16: 1},
 '144.1.g.a': {12: 2},
 '11.2.a.a': {1: 2, 11: 2},
 '176.1.h.a': {2: -1, 4: 3, 8: -1, 22: -1, 44: 3, 88: -1},
 '14.2.a.a': {1: 1, 2: 1, 7: 1, 14: 1},
 '15.2.a.a': {1: 1, 3: 1, 5: 1, 15: 1},
 '256.1.c.a': {8: -1, 16: 4, 32: -1},
 '20.2.a.a': {2: 2, 10: 2},
 '320.1.h.a': {4: -1, 8: 3, 16: -1, 20: -1, 40: 3, 80: -1},
 '7.3.b.a': {1: 3, 7: 3},
 '24.2.a.a': {2: 1, 4: 1, 6: 1, 12: 1},
 '27.2.a.a': {3: 2, 9: 2},
 '432.1.e.a': {6: -1, 12: 3, 18: -1, 24: -1, 36: 3, 72: -1},
 '8.3.d.a': {1: 2, 2: 1, 4: 1, 8: 2},
 '32.2.a.a': {4: 2, 8: 2},
 '36.2.a.a': {6: 4},
 '576.1.g.a': {12: -2, 24: 6, 48: -2},
 '5.4.a.a': {1: 4, 5: 4},
 '12.3.c.a': {2: 3, 6: 3},
 '6.4.a.a': {1: 2, 2: 2, 3: 2, 6: 2},
 '48.2.a.a': {2: -1, 4: 4, 6: -1, 8: -1, 12: 4, 24: -1},
 '4.5.b.a': {1: 4, 2: 2, 4: 4},
 '16.3.c.a': {4: 6},
 '8.4.a.a': {2: 4, 4: 4},
 '3.6.a.a': {1: 6, 3: 6},
 '64.2.a.a': {4: -2, 8: 8, 16: -2},
 '9.4.a.a': {3: 8},
 '2.8.a.a': {1: 8, 2: 8},
 '80.2.a.b': {2: -2, 4: 6, 8: -2, 10: -2, 20: 6, 40: -2},
 '4.6.a.a': {2: 12},
 '1.12.a.a': {1: 24},
 '32.3.d.a': {2: -2, 4: 5, 8: 5, 16: -2},
 '16.4.a.a': {2: -4, 4: 16, 8: -4},
 '144.2.a.a': {6: -4, 12: 12, 24: -4},
 '48.3.e.a': {2: -3, 4: 9, 6: -3, 8: -3, 12: 9, 24: -3},
 '64.3.c.a': {4: -6, 8: 18, 16: -6},
 '16.6.a.b': {2: -12, 4: 36, 8: -12},
 '64.5.c.a': {4: -14, 8: 38, 16: -14}}
```

**Comment by AndrewVSutherland** [comment]
@edgarcosta Now that you have automated this, I think storing the results of your computations in a table and displaying them on the newform pages makes sense.  We can update the source knowl accordingly (and even add a note that this agrees with the results in Yves Martin's paper, which it hopefully does).  Can you do something similar for products?

Another advantage of this approach is that we could then put the formulas higher on the page where they would be more visible than in a bottom knowl.  I might suggest putting them immediately below the q-expansion.

@davidfarmer Would that approach be acceptable to you?  I think you were the one who created this issue.

**Comment by edgarcosta** [comment]
@AndrewVSutherland these already include products.

**Comment by davidfarmer** [comment]
I am good with that plan, and also like the fact that we won't have all of 
those eta product knowls coming up on the list of interesting newforms.

But we are sort-of going back to the way things were long ago, an approach
that I though was rejected:  a place in the middle of the page to put
interesting formulas.

**Comment by AndrewVSutherland** [comment]
@davidfarmer Great, then let's proceed on this basis.

I do think there is a key difference with what we are proposing now and what we had before even if it winds up looking the same on the page.  We are displaying data we computed rather than formulas that were typed in by hand from an unspecified source. And we can now claim completeness (I think we previously only had knowls for only 25 or so of the 43), which to me makes this data more mathematically meaningful -- in particular, it means that when a formula does not appear it is because there isn't one, which was not true before.

**Comment by AndrewVSutherland** [comment]
This is mostly done, just waiting for @davidlowryduda to address a few issues that came up in the review of #4110.  Once that is done and merged we can close this.

**Comment by AndrewVSutherland** [comment]
This is now live on beta.  The eta quotient knowls have been deleted and the completeness knowl for CMFs has been updated to note that the database includes all 43 of the newforms listed in https://www.ams.org/tran/1996-348-12/S0002-9947-96-01743-6/
