### ISSUE TITLE
javascript for editing knowls is broken in firefox

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2786]
Kiran and I managed to recreate this issue

**Comment by AndrewVSutherland** [comment]
if you can tell me how to reproduce the error (which should always be included in any issue) I can review the PR which I assume is meant to fix this.

**Comment by edgarcosta** [comment]
Fixed by #2791.

The issue was that the buttons below weren't working:
<img width="434" alt="Screen Shot 2019-03-18 at 16 57 52" src="https://user-images.githubusercontent.com/322822/54563313-3b98ad00-499f-11e9-8953-b91fe7233a9a.png">
