### ISSUE TITLE
Implicit one-element list works for point counts on curve, but not on AV

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#2790]
On the search page

http://beta.lmfdb.org/Variety/Abelian/Fq/

I can input a single value into the search field "point counts of the curve" and this will be converted into a one-element list. However, this does not work for "point counts of the abelian variety".

**Comment by AndrewVSutherland** [comment]
Just to bump this issue up, I consider this a bug, not just something that is nice to have.  It is totally reasonable to expect that if you type in, say, 1, into this box and are told there are no matches to conclude that the database contains no abelian varieties with one rational point, but this is not true, there are 157 of them.

Displaying an error message would be better than the current behavior.  But I agree that the best solution is to have it convert a single integer into a list of length 1.

I also note that the current error checking on the point count for the abelian variety input box is a bit suspect, e.g. "[1x" is interpreted as [1], but "[1xx" does not work.  Typing in "banana" yields no error message (just zero results), whereas for the point count on the curve input box it will display an error.

**Comment by rbommel** [comment]
@roed314 seems to be working on this part of the website.

**Comment by roed314** [comment]
This will be fixed by #3430
