### ISSUE TITLE
\cite in knowls leaves a space after, even before punctuation

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#2792]
Using \cite{...} in a knowl seems to insert a space afterward. This is fine in case the following character is alphanumeric, but not if it is a punctuation mark. As an alternative, can we simply depend on the author to put the following space in manually when it is appropriate?

**Comment by jvoight** [comment]
I noticed the same thing, which causes some awkward formatting when it comes at the end of a sentence.

**Comment by edgarcosta** [comment]
The issue might be the `+" "+` in https://github.com/LMFDB/lmfdb/blob/master/lmfdb/knowledge/main.py#L198

**Comment by AndrewVSutherland** [comment]
@edgarcosta yup, removing that space fixes the problem, PR #3134 fixes it.
