### ISSUE TITLE
neq macro rendering

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2798]
In Firefox 66 on a MacBook Pro, the formula $p \neq 37$
on this page
http://beta.lmfdb.org/L/Genus2Curve/Q/1369/a/
is rendered with the "slash" going through the p.
(It literally says "p with a slash through it equals 37".)

**Comment by JohnCremona** [comment]
> In Firefox 66 on a MacBook Pro, the formula $p \neq 37$
> on this page
> http://beta.lmfdb.org/L/Genus2Curve/Q/1369/a/
> is rendered with the "slash" going through the p.
> (It literally says "p with a slash through it equals 37".)

Same on ubuntu + chrome

**Comment by alexjbest** [comment]
https://github.com/KaTeX/KaTeX/issues/1842 , looks like we should upgrade to KaTeX to v0.10.1 and see if it helps.

**Comment by edgarcosta** [comment]
It doesn't help http://blue.lmfdb.xyz/L/Genus2Curve/Q/1369/a/

**Comment by alexjbest** [comment]
@edgarcosta it doesn't help _you_! It works fine for me on that branch running chrome 72 on osx. But yes KaTeX/KaTeX#1842 is still an open issue.

**Comment by edgarcosta** [comment]
@alexjbest roger that

**Comment by edgarcosta** [comment]
Correction, the new version seems to fix the issue, I was simply not loading all the katex appropriately, as @alexjbest pointed out on the #2799

**Comment by AndrewVSutherland** [comment]
Fixed by #2799, which has now been pushed to dev and web, see

http://beta.lmfdb.org/L/Genus2Curve/Q/1369/a/
http://www.lmfdb.org/L/Genus2Curve/Q/1369/a/
