### ISSUE TITLE
L-functions have a conductor, not a level

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2800]
The knowl
   lfunction.level
should be deleted and all references to it should be replaced by
   lfunction.conductor
because the parameter usually written as N in the functional equation is
now (and has been for a few years) officially called the "conductor", not the "level".

**Comment by roed314** [comment]
I realized that we need some additional infrastructure to implement renames correctly.  Writing it now....

**Comment by davidfarmer** [comment]
I wasn't suggesting new infrastructure, just fixing this one by hand.

**Comment by AndrewVSutherland** [comment]
This has been done.
