### ISSUE TITLE
Zooming in and explaining the plots of CMF

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2808]
@brianconrey suggested that it would be nice to explore and render a bigger version of the cmf plots.

In my branch [`mf_plots`](https://github.com/LMFDB/lmfdb/compare/master...edgarcosta:mfplots?expand=1), I implemented this to just render the image if you click on the original message.
This has two issues:
-  it takes about 10s
- no explanation for the picture

At the moment, I don't plan to work more on this, as it is not clear to me which direction this should head to and I don't want to create a "homepage" for a picture that is rendered on the fly.

For a short period of time, I'm running it on  http://teal.lmfdb.xyz, see for example http://teal.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/23/1/b/a/

**Comment by assaferan** [comment]
@edgarcosta - is this still hosted on teal? (I couldn't tell from the branch name)

**Comment by edgarcosta** [comment]
I am not sure what happened to that branch, but the pictures have been recomputed, so whatever I had, which used the old code to generate the pictures, is not using the framework used to generate the new pictures.
