### ISSUE TITLE
counts are stored but then recomputed and duplicates stored

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2813]
If you do db.ec_nfcurves.count({'signature': [2,0]}) then the value of the count is stored in the ec_nfcurves.counts table, but if you do the same again it counts again and stores a duplicate in the table.

**Comment by edgarcosta** [comment]
ccing @roed314 
I think this has to do with the encoding of jsonb in the values column

**Comment by roed314** [comment]
This was fixed by #2825

**Comment by JohnCremona** [comment]
Just to confirm that the example I originally reported now works as expected.  Thanks
