### ISSUE TITLE
New URL and bread for degree 3 and 4 L-functions

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2827]
Implement new pure L-functions URLs and corresponding
breadcrumbs for the Maass-type degree 3 and 4 L-functions.

**Comment by jvoight** [comment]
For example
  http://beta.lmfdb.org/L/ModularForm/GL3/Q/Maass/1/1/16.40312_0.171121/-0.4216864/
has ugly bread, right?

**Comment by jvoight** [comment]
Ultimately when we implement the new L-function URL we will need to systematically go through and change the bread, e.g. http://beta.lmfdb.org/L/EllipticCurve/Q/334390/d/

**Comment by edgarcosta** [comment]
I believe this has been addressed for all the L-functions in the database in #4335 
If you click on the links above, you will see the new bread agnostic of L-function origin.
I think we should close this issue, but I won't do it, as we have not done this for the L-functions computed on the fly.
