### ISSUE TITLE
Convert roadmap to issues, then automatically present

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#2839]
It's hard to keep the roadmap updated.  (It's badly out of date now.)  At the same time, we want to show the general mathematical public what things are coming next without needing them to know how to get to our github issues.  

I think the roadmap has been converted into issues (#441), so we need to

1. Curate a list of issues and tag them "future plans", and
2. Either find a way to feed those labelled issues to the page or replace the link with a link to the tagged issues.

**Comment by AndrewVSutherland** [comment]
I think we should discuss this issue, perhaps at today's meeting.  I'm not sure either of your proposals for 2 are the right solution, but I agree that we need to address this issue.

**Comment by JohnCremona** [comment]
A couple of years ago @AurelPage did what is proposed in 1, which is one reason there are lots of issues initiated by him with similar dates.  Since the roadmap is now hidden even on beta (after the editorial discussion alluded to above) we can surely close this?

**Comment by jwj61** [comment]
Yes, closing

**Comment by AndrewVSutherland** [comment]
Agreed.
