### ISSUE TITLE
display issue on small screens

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2840]
@alinabucur and @brianconrey reported the same issue (see screenshot), when displaying q-exp on their MacBooks, I believe Brian was using Safari.

This is also somewhat recreatable on the phone.

<img width="1248" alt="Screen Shot 2019-03-18 at 2 19 46 PM" src="https://user-images.githubusercontent.com/322822/54790664-42c4f280-4c0d-11e9-8c86-faff3c067ee9.png">

**Comment by AndrewVSutherland** [comment]
This is reproducible on Firefox even on a largish screen (e.g. 1920x1440).  It would be useful to know whether this is Firefox specific or not.  As far as I can tell it is fine on Chrome and Safari.

I don't see an easy way to fix this.

**Comment by AndrewVSutherland** [comment]
Fixed by #3158
