### ISSUE TITLE
minor db backend issues in reload_all

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#2848]
1) When db.reload_all is given a folder name that does not exist it should raise an error rather than reporting success (and uploading no files).

2) Any counts/stats cached by the db object should be cleared, since they may have been changed if a counts/stats file was reloaded

**Comment by AndrewVSutherland** [comment]
@edgarcosta has this been addressed, or will it addressed by PR #3098?

**Comment by edgarcosta** [comment]
Now yes

**Comment by edgarcosta** [comment]
Closed via #3098
