### ISSUE TITLE
Fix dimension table display for Bianchi modular forms

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2854]
This did not survive migration to postgres.  For example, 
http://localhost:37777/ModularForm/GL2/ImaginaryQuadratic/gl2dims/2.0.4.1
displays blank data and it should display a lot.

**Comment by jvoight** [comment]
If you display all http://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/gl2dims/2.0.4.1?start=0&count=50&level_flag=all then it looks like something's wrong in the data (conversion to Postgres)?

**Comment by AndrewVSutherland** [comment]
Examples of the problem

http://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/gl2dims/2.0.4.1
http://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/gl2dims/2.0.8.1
http://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/gl2dims/2.0.3.1

There is data in  bmf_dims for these spaces but it does not appear to be getting parsed/processed directly.

**Comment by jvoight** [comment]
From our conversation: could be an issue with strings vs. integers in the keys?

**Comment by JohnCremona** [comment]
The fact that http://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/gl2dims/2.0.4.1 looks so different from  http://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/gl2dims/2.0.4.1?start=0&count=50&level_flag=all  is another clue.

**Comment by AndrewVSutherland** [comment]
If you want to see what I believe the table should look like, the mongo db version is still available at prod.lmfdb.xyz, for example, you can compare the links I gave above with

http://prod.lmfdb.xyz/ModularForm/GL2/ImaginaryQuadratic/gl2dims/2.0.4.1
http://prod.lmfdb.xyz/ModularForm/GL2/ImaginaryQuadratic/gl2dims/2.0.8.1
http://prod.lmfdb.xyz/ModularForm/GL2/ImaginaryQuadratic/gl2dims/2.0.3.1

**Comment by JohnCremona** [comment]
I am reopening this.  If you go to https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/gl2dims/2.0.11.1 (by clicking on the Browse GL2 newforms spaces link for Q(sqrt(-11))) you see the start of the table, the first 50 lines, but clicking next does not show the next 50 rows of the table.

**Comment by JohnCremona** [comment]
I have looked at the code and cannot tell why clicking on Next does not increase the value of start before re-displaying.  Help!

**Comment by roed314** [comment]
I will take a look.

**Comment by edgarcosta** [comment]
Fixed on beta.lmfdb.org I'm not pushing to www.lmfdb.org as it is not clear to me that we can do that.
