### ISSUE TITLE
Knowl for Atkin-Lehner involutions

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#2861]
There does not seem to be a knowl defining Atkin-Lehner involutions. This issue is to first write that knowl, then check that it is linked to by other knowls that should do so (e.g., top knowls for certain elliptic curves and genus 2 curves).

**Comment by edgarcosta** [comment]
@kedlaya, do you know where you noticed the missing knowl?

It shows up on classical modular forms at the bottom
www.lmfdb.org/ModularForm/GL2/Q/holomorphic/11/2/a/a/

**Comment by kedlaya** [comment]
Oh hmm, I guess cmf.atkin-lehner does the trick. Maybe I failed to find it because I was looking for "involution" rather than "operator" in the title.

Anyway, now to the next step, which is linking this from the top knowls of elliptic curves and genus 2 curves that mention Atkin-Lehner involutions.

**Comment by davidfarmer** [comment]
We could not find any top knowls that mention Atkin-Lehner, so this seems to be done.

Please reopen with a link to the problematic top knowl, if it still exists.

**Comment by edgarcosta** [comment]
Here are all the top/bottom knowls that include the word 'Atkin-Lehner'

```
 ec.q.131.a1.top
 ec.q.131.a1.top
 ec.q.101.a1.top
 ec.q.43.a1.top
 g2c.10609.a.10609.1.top
 ec.q.101.a1.top
 ec.q.37.a1.top
 ec.q.53.a1.top
 g2c.36481.a.36481.1.top
 g2c.4489.a.4489.1.top
 ec.q.131.a1.top
 ec.q.83.a1.top
 ec.q.43.a1.top
 ec.q.43.a1.top
 ec.q.131.a1.top
 ec.q.61.a1.top
 ec.q.37.a1.top
 ec.q.61.a1.top
 g2c.10609.a.10609.1.top
 ec.q.79.a1.top
 ec.q.131.a1.top
 ec.q.79.a1.top
 g2c.5329.b.5329.1.top
 g2c.27889.a.27889.1.top
 ec.q.53.a1.top
 ec.q.83.a1.top
 ec.q.101.a1.top
 ec.q.79.a1.top
 g2c.36481.a.36481.1.top
 g2c.27889.a.27889.1.top
 g2c.4489.a.4489.1.top
 g2c.5329.b.5329.1.top
 g2c.5329.b.5329.1.top
 g2c.15625.a.15625.1.top
 g2c.10609.a.10609.1.top
 g2c.36481.a.36481.1.top
 ec.q.83.a1.top
 ec.q.53.a1.top
 g2c.4489.a.4489.1.top
 ec.q.61.a1.top
 ec.q.142.a1.top
 ec.q.58.a1.top
 ec.q.91.a1.top
 ec.q.57.a1.top
 ec.q.77.a1.top
 ec.q.65.a2.top
 ec.q.118.a1.top
 ec.q.123.b1.top
 ec.q.141.d1.top
 ec.q.143.a1.top
 ec.q.155.c1.top
 ec.q.65.a1.bottom
 ec.q.65.a1.bottom
 ec.q.65.a1.bottom
```

**Comment by AndrewVSutherland** [comment]
The knowl https://www.lmfdb.org/knowledge/show/cmf.atkin-lehner now exists and appears on the page that was given as an example, I'll leave this open for the moment in case someone want to scan through the list Edgar posted above and add links.

**Comment by davidfarmer** [comment]
I will scan the list and confirm this issue is resolved.

**Comment by davidfarmer** [comment]
I checked all those knowls.
