### ISSUE TITLE
Imaginary unit shown as capital letter

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2863]
On this page:

http://beta.lmfdb.org/L/Character/Dirichlet/17/4/

the letter I is used instead of lower case i.

**Comment by davidfarmer** [comment]
Also, it has
   +-I
instead of 
   -i

**Comment by davidlowryduda** [comment]
I believe this issue can be closed. The pull request a few weeks ago fixed the bug.
