### ISSUE TITLE
Bug when stopping the renaming of a knowl

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2867]
I started to rename dq.character.dirichlet.source and then changed my mind.

I went to edit the knowl and clicked on "Undo Renaming" and got "Bad request

The browser (or proxy) sent a request that this server could not understand."

**Comment by roed314** [comment]
I believe that this will be fixed by #2892, but we should check.

**Comment by roed314** [comment]
I just checked, and this has been resolved by #2892.
