### ISSUE TITLE
Genus 2 curve missing HMF friend

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#2873]
The genus 2 curve L-function

http://www.lmfdb.org/L/Genus2Curve/Q/3125/a/

and the HMF L-function

http://www.lmfdb.org/L/ModularForm/GL2/TotallyReal/2.2.5.1/holomorphic/2.2.5.1-125.1-a/0/0/ 

are the same, but the genus 2 curve and the HMF do not know they are friends.

We should fix this and search for any other missing HMF or BMF friends of genus 2 curves.

**Comment by jvoight** [comment]
As we discussed at IAS, I think the time to be systematic is when we're finishing up our many author paper.  If I were to do this, I would go over each row of the giant table and make sure all matches are there--but it will be more efficient if we do this while writing, especially if any mathematical issues come up.  

It would be more reliable if there was a source-independent way (e.g., hash) on the L-functions in the database--or perhaps equivalently the relevant CMFs, HMFs, and BMFs--and these friends were generated automatically.  Then the humans could check the computations and hopefully we agree.  

I'm not sure this is worth holding up v1.1: the links to CMFs seem to be there, we never promised that all friends will be there, and there's no way we will forget to do this.

**Comment by AndrewVSutherland** [comment]
I agree this is not worth holding up v1.1, but I believe we already have enough data to completely automate this (which I agree is absolutely necessary).  I'll take a stab at this today.  I don't think it will be hard to generate a list of potential friends that is provably complete, and I think this will be a short list (tens not hundreds).

**Comment by AndrewVSutherland** [comment]
There is a related and perhaps more pressing issue.  The genus 2 curve

http://www.lmfdb.org/Genus2Curve/Q/12500/a/12500/1

knows its HMF friend, and the L-function lists both the genus 2 curve and the HMF as related objects

http://www.lmfdb.org/L/Genus2Curve/Q/12500/a/

because both are listed in lfunc_instances.  But If you click the HMF link on the L-function page, and then click the L-function link on the HMF page, you return to a different version of the same L-function

http://www.lmfdb.org/L/ModularForm/GL2/TotallyReal/2.2.5.1/holomorphic/2.2.5.1-500.1-a/0/0/

which no longer knows that it is the L-function of a genus 2 curve.  So you can navigate  genus 2 curve -> L-function -> HMF -> L-function but then cannot get back to the genus 2 curve you started with, and along the way you see the same L-function presented in two different ways (one has no arithmetic normalization or Euler factors available, and the Z-plots are scaled differently).  This is surely not the "Langlands experience" we are looking for :)

There is an easy fix: the L-function display code should check its instances table when given an HMF URL, just as it does for genus 2 curves and CMFS,  and only compute the L-function on the fly when it doesn't find a record.  I will submit a PR that does this and also has the HMF display code check lfunc_instances for genus 2 friends (which is how genus 2 curves find their HMF friends, there is nothing in the genus 2 tables that makes this happen, and I can copy the code to do this from the genus 2 code).

Once this has been done, addressing the initial problem mentioned in this issue is simply a matter of adding more HMF records to the lfunc_instances table, which we can do as and when we wish.

**Comment by edgarcosta** [comment]
The problem with 
- http://www.lmfdb.org/L/Genus2Curve/Q/3125/a/ and
- http://www.lmfdb.org/L/ModularForm/GL2/TotallyReal/2.2.5.1/holomorphic/2.2.5.1-125.1-a/0/0/
Is that the L-fun for the G2C is served from the DB, while the HMF is computed on the fly.
To make them show in both sides we would need to add the corresponding instance for the HMF for both **embeddings**, as the G2C matches either L-function of an embedding, but not the orbit. However, before doing this we should perhaps discuss labels for HMF embedded forms, so they match CMFs.

I will address the other issues in an upcoming PR
