### ISSUE TITLE
Details of L-function  labels

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2876]
Opening this issue to have a place to discuss the remaining issues about
L-function labels.

I propose a change in how the Gamma factors are ordered.

a) First list the Gamma_R in increasing order of real shift (i.e., the 0s and then the 1s), then list the Gamma_C in increasing order of real shift.

b) Break ties by sorting according to increasing *absolute value* of the imaginary parts.

c) Break any remaining ties by writing the *positive* number first.

The final step is more natural (to me) because the weighted imaginary parts
add to be 0, and for GL(2) and GL(3) I tend to think of the positive imaginary
parts as the parameters, and the negative one as containing no information
and is just there for balance.

This proposal has the feature that (except for the final component)
the label of the conjugate L-function is obtained by changing signs
without rearranging the Gamma factors.

**Comment by davidfarmer** [comment]
What would be the URL of the set of L-functions that satisfy a particular type of
functional equation?  For example, the functional equation that is satisfied by the
L-function of a genus 2 curve.  (I don't mean only the set of L-functions of genus 2
curves, I mean the set that satisfy that functional equation.)

I note that the tilde character is allowed in a url but not currently used.  So one
option might be (I think I am writing the parameters in the correct order)

/L/~/1.1/c1c1    (of one wants only trivial character)

or, if one wants to allow any even character,

/L/~/~/c1c1

**Comment by roed314** [comment]
Would this be a page of search results, or a separately constructed homepage for this set of L-functions?  What information would be included beyond what you would see in the (not yet existing) list of search results?

**Comment by davidfarmer** [comment]
I see the c1c1 L-function page as selected by the user, for browsing.  Analogous
to browsing elliptic curves/Q or genus 2 curves/Q.

The following link is not quite what I imagine for the design of that page, but it shows
the first 200 or so such examples with trivial character (Sally constructed it by
hand a couple years ago, so there may be some omissions or other errors).
It gives an idea of the interesting information available for that seemingly restricted
set of L-functions:

https://aimath.org/~farmer/print/d4integer.html

Highlighted are the first time various things occur (mouse over to see what is special
about it).  One sees patterns (why are most of them non-primitive?) and non-patterns
(what determines what type of automorphic and geometric objects have the same
L-function?) and things the experts understand but are not obvious initially (if +1 and -1
should occur equally often as the sign of the functional equation, why are most of those +1?)

Other information I would like to see on that page:  Sato-Tate group, rank, a more clear
indication of which L-functions are primitive.

That is the type of browsing experience we want people to have when they explore
L-functions as L-functions, organized the way L-functions people think about it.

**Comment by roed314** [comment]
I like the idea of using a tilde as a wildcard placeholder.

The page you referred to looks a lot like a list of search results.  Can we choose the columns in the search results appropriately so that it provides the information that you're looking for?

**Comment by davidfarmer** [comment]
When you browse genus 2 curves and then click Conductor 1-499,
then technically what you are looking at is the results of a
search.

I think that model would work here.  It is not clear to me if
clicking "browse c1c1 L-functions" is analogous to clicking
"browse genus 2 curves" or to clicking "1-499" after that first click.
That can be discussed when we are ready to implement it.

Either way, more columns would be good, and we would not use
the awkward styling of the link I posted.

For now I just wanted to bring attention to the fact that such
pages will exists, so that we can be sure the L-function url
scheme would accommodate it.

**Comment by edgarcosta** [comment]
We talked a bit about this today, and we decided that a representation perspective we prefer r0r1 vs c0, thus #2885 should be closed.

**Comment by edgarcosta** [comment]
We set the separator to be `-`
there are 3 blocks:
1-
- degree
- conductor
- inducing primitive character

2- 
- real parts of Gamma_R \in [0,1]
- 2*real parts of Gamma_C \in ZZ

the gammas are sorted by real part and then the absolute value of the imaginary part, with positive imaginary first, when you break a tie.

3- 
the imaginary parts of the Gammas, in the samer oder

**Comment by edgarcosta** [comment]
Next thing, I will make a PR where we add labels to beta.lmfdb.org, with the last block being `?`.

**Comment by AurelPage** [comment]
Hi,

I am a bit confused. What is the representation-theoretic reason for always prefering r0r1 over c0?
Maybe I am confused, but I would have thought that there is a good representation-theoretic reason for sometimes prefering c0.
Namely, the gamma factors (in analytic normalisation below) are supposed to match a tempered representation of the Weil group of $\mathbb{R}$: the irreducible ones are of two types (notations from Tate's Number theoretic background), one-dimensional $\chi_{N,\alpha}$ for $N\in\{0,1\}$ and $\alpha\in\mathbb{C}$ satisfying $N=\text{Re}(\alpha)$ with gamma factor $\Gamma_\mathbb{R}(s+\alpha)$ and two-dimensional $\rho_{N,\alpha}$ for $N\in\mathbb{Z}_{>0}$ and $\alpha\in\mathbb{C}$ satisfying $N/2 = \text{Re}(\alpha)$ with gamma factor $\Gamma_\mathbb{C}(s+\alpha)$. Then from a product of $\Gamma_\mathbb{R}(s+\beta_i)$, there is only one way to group them to match a tempered representation: each $\beta_i$ with $\text{Re}(\beta_i)>1$ should be part of a $\Gamma_\mathbb{C}$.
Using this would make the decomposition of the gamma factors reflect the dimensions of the irreps appearing in the Weil representation. On the other hand, it produces some awkward choices from an intuitive point of view, for instance I think for modular forms it will choose $\Gamma_\mathbb{C}$ in weight $k>1$ and two $\Gamma_\mathbb{R}$ in weight $k=1$.

**Comment by davidfarmer** [comment]
I am not sure of your notation, but the way I write it, for the two dimensional representation
the "N" has to be positive because when N=0 the representation is not irreducible.  So that
is why you never get a GammaC(s), not directly from the irreducible representation of the real Weil group.  You have to package together two one-dim representations GammaR(s) GammaR(s+1) to get  GammaC(s).

I agree that there are other situations where GammaC(s) seems natural.  It is our intention to use GammaC(s) on the home page of the L-function of a weight 1 holomorphic cusp form, when the user arrives there from the home page of the cusp form.

**Comment by AurelPage** [comment]
Yes, that's the same as I wrote. Oh I see, I think I simply misunderstood the proposed convention and was proposing the same thing.

**Comment by edgarcosta** [comment]
Please check red.lmfdb.xyz where we display the labels, except the last block.
Here are some examples:
https://red.lmfdb.xyz/L/ModularForm/GL2/Q/holomorphic/404/1/o/a/
https://red.lmfdb.xyz/L/ModularForm/GL2/Q/holomorphic/404/1/o/a/19/1/
https://red.lmfdb.xyz/L/ModularForm/GSp4/Q/Maass/1/1/12.46875_4.720951/1.34260324/
https://red.lmfdb.xyz/L/ModularForm/GL2/Q/holomorphic/71/1/b/a/
https://red.lmfdb.xyz/L/ModularForm/GL2/Q/holomorphic/65/2/o/a/

On #2885 I said 
> @davidfarmer and I agree that we should never use c0 for the label, however, when it comes to displaying the functional equation, we might consider using Gamma_C, if more natural.

But now I disagree with the last part. When displaying the L-function we should be agnostic from where it came from, thus I propose we start to display the Gamma factors to be consistent with the label.

For example:
https://red.lmfdb.xyz/L/ModularForm/GL2/Q/holomorphic/404/1/o/a/
will become 
https://red.lmfdb.xyz/L/40/404e20/1.1/r0r1e20/0/?
and on that page, the only indication that it comes from a weight 1 modular form will be on origins.

**Comment by roed314** [comment]
So you're suggesting changing the Gamma_C to two Gamma_R's on https://red.lmfdb.xyz/L/ModularForm/GL2/Q/holomorphic/404/1/o/a/19/1/?

How often do spectral parameters come in complex conjugate pairs (I was looking at the Maass form example Edgar posted).  If that's common, we could change m4.72p4.72m12.47p12.47 to c4.72c12.47 to shorten the label.

**Comment by AndrewVSutherland** [comment]
@edgarcosta The URL https://red.lmfdb.xyz/L/40/404e20/1.1/r0r1e20/0/ you posted is throwing a 404.

**Comment by edgarcosta** [comment]
- Yes, I'm suggesting the  Gamma_C to two Gamma_R's on https://red.lmfdb.xyz/L/ModularForm/GL2/Q/holomorphic/404/1/o/a/19/1.

- The url `https://red.lmfdb.xyz/L/40/404e20/1.1/r0r1e20/0/?` is just an example. (I have edited the previous comment).
We first need to add labels to the database to be able to support this.

- I think it happens often enough that is why our sorting order is: `(real, abs imag, imag)` to get the conjugates next to each other, but what you propose makes sense.

- Even without going with the pairing conjugates route, should we independently treat multiplicities for the real and imaginary parts on the gamma label independently.
Should we display `r0e4` instead of `r0r0r0r0` for https://red.lmfdb.xyz/L/ModularForm/GSp4/Q/Maass/1/1/12.46875_4.720951/1.34260324/ ?
If so, what is the order for the imaginary parts?
Should `rxcye2` correspond to `rxrxcycy`? (instead of `rxcyrxcy`)

**Comment by davidfarmer** [comment]
I think we talked about GammaRs first,
lexicographic where you first order by real part,
then by absolute value of imaginary part (with positive coming
before negative when there is a tie).

**Comment by edgarcosta** [comment]
@davidfarmer, did you have time to look at the examples?

Also what you think about the other points?
- pairing the conjugates as @roed314 suggested
- making the functional equation match the label, ie, not displaying Gamma_C(s) anywhere

**Comment by davidfarmer** [comment]
I think the Gamma factors on the page should be written in the same order as in the label.

Not sure what you mean by "pairing conjugates".  The order is by increasing absolute value of the
imaginary part, so conjugates will be consecutive.

I am a little confused about the precedence of the "e" operator, where r0r1e20  seems to mean (r0r1)e20 .

I am willing to discuss using Gamma_C(s) on the home page, even though there are two Gamma_R
in the label.  Maybe only when there is no imaginary shift?  L-function of a weight 1 Maass form
(which we don't yet have in the LMFDB -- one of our more glaring gaps) has
Gamma_R(s + i y)Gamma_R(s + 1 - i y) .  That times its conjugate could 

Can we discuss during development time tomorrow?  I probably can be on starting at 2pm.

**Comment by roed314** [comment]
Discussing tomorrow afternoon sounds good.

* By "pairing conjugates" Edgar was referring to my proposal to write `m4.72p4.72m12.47p12.47` instead of `c4.72c12.47` in order to shorten the label.
* I think the precedence of the `e` operator is one of the things we need to discuss tomorrow.  Since it's most useful in the case of non-primitive L-functions, which are going to be a product of a bunch of L-functions of the same signature, I think that it should group together all the real parts at least.  Are there cases with nonzero imaginary parts where `e` would be valuable as well?

**Comment by edgarcosta** [comment]
Yup! See you tomorrow at 2pm

**Comment by davidfarmer** [comment]
Gamma_C(s) = Gamma_R(s) Gamma_R(s + 1).

So m4.72p4.72 does not combine, because both of the real shifts
are 0.  You can have combining in the case I described in my previous
posting, because both 0 and 1 occur as real shifts.

When combining is possible, there are two situations to consider:
the label, and the functional equation as displayed on the home page.

Representation theory says not to combine.  I think that view carries
more weight in the label than on the home page.  And then there is the
issue of consistency.

**Comment by roed314** [comment]
I was intending the combination as just a way of shortening the label, not as something where we should display the functional equation differently.  But we can talk more tomorrow.

**Comment by davidfarmer** [comment]
The definition of analytic conductor I was describing is on pages 5 and 6 of these
slides from Dave Robert:

https://math.mit.edu/~drew/2018Conference/SlidesRoberts.pdf

Those pages are about what he calls the "R" part of the analytic conductor
(which comes from the Gamma-factors), which gets multiplied by the
part from the conductor N.

**Comment by davidfarmer** [comment]
In the knowl describing the functional equation, and in the knowl about
L-function labels, if we refer to the "condensed form" of the FE and the label,
then that explains why we write Gamma_C(s) instead of
Gamma_R(s) Gamma_R(s+1), and that should avoid any complaints.

**Comment by edgarcosta** [comment]
All this has been settled in #4335 

The label description is here: https://beta.lmfdb.org/knowledge/show/lfunction.label
