### ISSUE TITLE
Rewrite is slow for tables with extras

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#2881]
It's not feasible to use `rewrite` for elliptic curves or number fields, since the `rewrite` method uses `search` to get the input for the rewriting function, and search wasn't intended to return large numbers of rows with columns from the extras table (the whole point of the extras table was that these columns aren't used in search results).  The right solution is to change the `search` and `_search_iterator` methods to use a join instead of doing things in an ad-hoc way.

**Comment by JohnCremona** [comment]
@roed314 Do you mean ec_curves (elliptic curves /Q) and not ec_nfcurves?  Since ec_nfcurves has no extra table, and I have rewritten it successfully.  I have not yet tried to rewrite ec_curves but will certainly want to at some point.

**Comment by roed314** [comment]
Yeah, `ec_nfcurves` is fine since it has no extras table but `ec_curves` will be slow.

**Comment by roed314** [comment]
There are still more issues with rewrite, so I'm reopening.

**Comment by AndrewVSutherland** [comment]
Is there still an issue here @edgarcosta and @roed314 ?

**Comment by edgarcosta** [comment]
I don't think so.
I think we agreed that the buffered cursor PR should have taken care of
this, however @jwj61 should confirm.

**Comment by jwj61** [comment]
I think it is now fast enough.  I started a rewrite last night (for #3100) and it was finished by this morning.

**Comment by AndrewVSutherland** [comment]
I think "fast enough" is sufficient for now, we have other more pressing db backend issues to work on.
