### ISSUE TITLE
Determine when/how to choose between r0r1 and c0

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2885]
Since Gamma_C(s) = Gamma_R(s) Gamma_R(s+1), in some cases there is a
choice for how to display a functional equation (and the same choice when
assigning a label).

From the pure L-function/automorphic representation theory perspective,
the answer is to only use Gamma_R(s) Gamma_R(s+1).  When GammaC(s + nu)
appears, nu >= 1/2.  However, other perspectives are important and need to be
given appropriate weight.

The real conundrum is that the natural choice seems to depend on the source
of the L-function.  For example, weight 1 cusp form:  Gamma_C(s).
The associated Artin representation:  GammaR(s) GammaR(s+1), which is
related to the fact that the Dedekind zeta function of a number field
naturally has Gamma_R and Gamma_C encoding the signature of the field.

A related issue is when to use "power" notation to indicate that a Gamma
factor appears multiple times.

I think this case is clear:  when the L-function is primitive and some of the
Gamma factors have a nonzero imaginary part, do not combine to get
GammaC(s).

I think this case not quite as clear, but let's consider:  for primitive L-functions,
do not use power notation.  (Note that we rarely go past degree 5 for
primitive L-functions.)

I think this case is clear, too:  for a nonprimitive L-function, just concatenate
the Gamma factors from the primitive L-functions.  That is, do not combine
a GammR(s) from one L-function with a GammaR(s+1) from another.
And use power notation when possible.

I thought that writing this issue would help clarify my thoughts and I would have
a specific proposal, but it didn't.  :(

See the "0.12639" row of /L/degree2/ for an example:  the table lists two
GammaR's, but the L-function page it links to has a GammaC.

**Comment by edgarcosta** [comment]
My stance is that we should be agnostic to the origin of the L-function.
r0r1 vs c0 or writing conductor as a power should be done solely based on the attributes of the L-function, and nothing else.

**Comment by davidfarmer** [comment]
If it only depends on the L-function then I think the answer is clear:
never use c0.

I think that is a reasonable attitude when you are making the label.

But when you display the L-function on a web page, if you arrived
from a number field, or from a weight 1 holomorphic cusp form,
people will think it funny if they don't see

     Gamma_C(s)

in the functional equation.

I don't have a problem with showing different content on the home
page of an L-function, depending on how the person got there.
Within reason, of course.

**Comment by edgarcosta** [comment]
I think we agree then, by default we do not use c0, and depending under what umbrella we are displaying the L-fcn we should use c0 or not, but that is at the level of rendering, and not at the level of the data or the label.

**Comment by edgarcosta** [comment]
@davidfarmer and I agree that we should never use c0 for the label, however, when it comes to displaying the functional equation, we might consider using Gamma_C, if more natural.

**Comment by edgarcosta** [comment]
Closing this one in virtue #2876
