### ISSUE TITLE
CM, RM, and QM 

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2886]
There are genus 2 curves which (elsewhere in the LMFDB, such as
/L/degree4/)
are referred to as RM, CM, or QM.  But if you go to the home pages of those
curves, a non-expert would find it difficult to understand what RM, etc,
means, or that those curves have those properties. 

If those properties relate to the Sato-Tate group, then that would be
good to point out somewhere.

**Comment by edgarcosta** [comment]
Honestly, we should also be able to search on them.
At the moment you need to use ```Sato-Tate identity component``` to search for those examples, which for me is almost as hard as doing mental arithmetic.

**Comment by AndrewVSutherland** [comment]
Actually, you need to specify both the Sato-Tate identity component and that the Jacobian is Qbar-simple to get an exact correspondence, but it would be trivial to add a search for surfaces that have potential CM, RM, QM over Qbar using this correspondence, in fact you should be able to search on the geometric endomorphism algebra (which would also let you search for Jacobians Qbar-isogenous to products of elliptic curves with/without CM isogenous/non-isogeneous, 9 possbilities in total).

This would be easy to add, and the knowl for this could explain what RM/CM/QM mean and be linked to from the degree 4 L-function page.

**Comment by edgarcosta** [comment]
>  and that the Jacobian is Qbar-simple to get an exact correspondence
I disagree somewhat.
I know what you have in mind, but this perhaps reveals that we first should agree on what we want to search. We want to search on "is" a RM/CM/QM abelian surface or "has"?

For me, an abelian surface "has" RM/CM/QM if we can embed a real field/a CM field/a quaternion algebra in End(A), and for the "is" we expect an isomorphism.

For example, 
* A = (non CM)^2, then is a QM abelian surface with QM by M_2(Q)
* A = (CM)^2, then A has CM
* If End(A) = B, a quaternion algebra where disc B != 1, then A also has CM and RM
* If End(A) = K and K is a quartic CM field, then A is a CM abelian surface, but also has RM.
* etc...

**Comment by AndrewVSutherland** [comment]
I have added the column geom_end_alg to the table g2c_curves, which can take 9 values and I plan to add this as a search field.  Of the 9 values, the 4 that correspond to geometrically simple varieties are Q, RM, CM, QM.  The others are Q x Q, CM x CM, Q X CM, M_2(Q), M_2(CM).

I think this is the most straight-forward thing to do and anything else is asking for confusion.  The knowl for this column will explain exactly what each of the 9 values mean (RM denotes a real quadratic field, CM denotes a CM field that is quartic in the geometrically simple case and quadratic otherwise, and QM denotes a (non-split) quaternion algebra.

**Comment by AndrewVSutherland** [comment]
@edgarcosta: PR #2956 adds the ability to search on geometric endomorphism algebras.  As part of this PR I added the knowl http://beta.lmfdb.org/knowledge/show/g2c.geom_end_alg which explains what RM, CM, and QM mean.  We could add a link to this knowl on the degree-4 L-function browse page, but there is currently now obvious place to put a link; any suggestions @davidfarmer ?

**Comment by davidfarmer** [comment]
I think the original issue has been addressed.  If you follow a link from the degree 4 page,
the properties box lists RM/CM/QM, which was mentioned at the original link.

It is potentially confusing (or a source of information) that $\End(J_{\overline{\Q}}) \otimes \Q$
appears in more than one place, with different information next to it.  But that can be a
separate issue if someone has a suggestion to change it.

I suggested putting the g2c.geom_end_alg  under the "Learn more about" on genus 2 pages,
and still think that would be a worthwhile addition.

**Comment by edgarcosta** [comment]
> It is potentially confusing (or a source of information) that
$\End(J_{\overline{\Q}}) \otimes \Q$
appears in more than one place, with different information next to it. But
that can be a
separate issue if someone has a suggestion to change it.

Could you point to an example?

**Comment by davidfarmer** [comment]
http://beta.lmfdb.org/Genus2Curve/Q/12500/a/12500/1

has "RM" in the properties box, and Qsqrt5 near the bottom
of the page.

"RM by Qsqrt5" in the properties box maybe?
