### ISSUE TITLE
Search elliptic and genus 2 curves by primes of bad reduction

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#2912]
I was just using the database of elliptic curves over Q and would have found it useful to be able to search by primes dividing the conductor (i.e., primes of bad reduction). Ideally this would be an include/exclude/all option, like for maximal primes.

**Comment by JohnCremona** [comment]
That would not be hard.  With one rewrite we could add a column 'bad_primes' to the table.  Right now there is a column 'local_data' (in the extra table) which is a list of local data at each bad prime, so right now one can do (for example)

>[c['label'] for c in db.ec_curves.search(projection=2) if any(ld['p']==101 for ld in c['local_data'])]

but of course that is very slow as it has to look at every record.

**Comment by roed314** [comment]
I've created a column `bad_primes` in `ec_curves` and populated it from `local_data`.

**Comment by rbommel** [comment]
This is the code David ran for me to get the new field in the database:

> from lmfdb import db
> db.g2c_curves.add_column("bad_primes", "integer[]")
> def add_bad_primes(rec):
>     cond = rec['cond']
>     rec['bad_primes'] = sorted([fact[0] for fact in factor(cond)])
>     return rec
> db.g2c_curves.rewrite(add_bad_primes)

**Comment by AndrewVSutherland** [comment]
Sure.

**Comment by edgarcosta** [comment]
Done.

@rbommel, There are two databases serving lmfdb.
- A production database, at proddb.lmfdb.xyz, with the sole purpose of serving www.lmfdb.org
- A development database, at grace.mit.edu, that serves beta.lmfdb.org, and where we play around.

We never do live edits on the production database; we only copy tables from development to production, with editorial permission. Hence, me asking for permission.
