### ISSUE TITLE
Remove browser-specific selectors

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2915]
The CSS selectors which start `-moz`,  `-webkit`, and `-o` are mostly,
and possibly completely, archaic.  Those can be replaced by the standard CSS
selectors.

I can do this, but will wait for comments in case this may cause problems I am not
aware of.

This issue came to my attention when I was investigating why issue #2582 was
not fixed, even though some people said it was.  The problem is that the
selector was specific to webkit, and I was viewing in Firefox.  (I am about to send
a small pull request fixing that other issue.)

It is good to check CSS changes in several browsers.

**Comment by edgarcosta** [comment]
I agree with this, but not all of them are deprecated for example, ```sticky``` is not yet supported, and the hack to make it work is```-webkit-sticky```

**Comment by davidfarmer** [comment]
Addressed by  #2947
