### ISSUE TITLE
Labels for embedding cmf

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2931]
Looking at an embedded CMF and clicking on the link to learn about the labels gives an explanation of a label with 4 parts even though the object I came from had a label with 6 parts.  The knowl should go on to explain the extra parts for an embedded form (or have separate knowls).

**Comment by AndrewVSutherland** [comment]
@jwj61 Good catch.  I just updated the label knowl.  Take a look at http://beta.lmfdb.org/knowledge/show/cmf.label and let me know if you think anything further is required (I'll leave the issue open and let you close it once you are satisfied).

**Comment by jwj61** [comment]
Looks fine
