### ISSUE TITLE
Searching elliptic curves by mod-p Galois image

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#294]
In addition to being able to specify primes p at which the mod-p image is non-surjective, it would be very useful to be able to specify a list of mod-p Galois image group labels (e.g. 3B.1.2 5Nn) and get a list of all elliptic curves with these mod p images, both for elliptic curves over Q and for elliptic curves over number fields.

**Comment by AndrewVSutherland** [comment]
#4957 adds this for number fields

**Comment by JohnCremona** [comment]
I would like to be able to have something in between "non-maximal" and a specific rather technical image code name.  I mean to be able to search for "contained in non-split Cartan at 3" or similar.  For each prime, such terms would translate into a finite (short) list of image labels, so would be easy to do.  The UI would be harder if it was allowed to specify such things at more than one prime -- though these combinations occur rather rarely, when they do they are interesting!  So probably this is a "feature request".

**Comment by AndrewVSutherland** [comment]
@JohnCremona It would be easy to add a list of named keywords (e.g. "contained in non-split Cartan at 3") that translates to a list of subgroup labels (this could even be stored in a table).  We would then need to add a selector that lets the user choose from the list of keywords.  Feel free to raise an issue (which I agree would be a "feature request").  If you give me a list of desired selection criteria I can easily generate a list of corresponding subgroup labels.

**Comment by AndrewVSutherland** [comment]
One other thought (which might be both more general and easier to implement), we could allow strings like "<= 3Cn" or "> 5Cs" in the list of mod-ell image labels.  I think the mod-ell image labels are pretty intuitive, at least at the level of detail people are likely to be interested in (Borel, Cartan (split/non-split), Normalizer of Cartan, S4, ...) and explained in the knowl https://www.lmfdb.org/knowledge/show/ec.galois_rep_modell_image (we could also create another knowl more specific to searching that would explain things in more detail and give instructions on how to search for things like "contained in non-split Cartan at 3", with examples).
