### ISSUE TITLE
Link suggestions do not work on Firefox

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2948]
The link suggestion feature when editing knowls (which I like a lot) does
not work for me in the latest Firefox on my MacBook Pro.

Clicking the "insert" link either does nothing, or it just highlights the words
where the new knowls should go.

I switched to Chrome and it seems to work okay, so I guess this is not a critical
issue.

**Comment by AndrewVSutherland** [comment]
Just confirming that this is also a problem when running Firefox on Ubuntu.

**Comment by edgarcosta** [comment]
FYI, a hack was used to try make this work for Firefox:
```
// the insertText method doesn't work on Firefox, so we have to just replace the val, losing undo capability
// See https://bugzilla.mozilla.org/show_bug.cgi?id=1220696
```
see https://github.com/LMFDB/lmfdb/blob/master/lmfdb/static/knowl_edit.js#L276

I'm not sure why the hack no longer works

**Comment by AndrewVSutherland** [comment]
This is a known acknowledged bug in firefox that we can't do anything about.  If and when Mozilla fixes it, link suggestions should work again, provided we remove the hack (that currently is not helping in any case).  I don't think it is worth spending time and effort trying to find a way to hack around this bug (which may be fruitless in any case).

I'm going to tag this as a feature request just so we don't forget about it.

**Comment by edgarcosta** [comment]
The javascript hack doesn't work anymore and the error is:
```
TypeError: content.substring is not a function
```

**Comment by AndrewVSutherland** [comment]
With #3138 the hack now works again.
