### ISSUE TITLE
Local field data pull request

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2962]
This is a request to upload lf_fields to the main server.

This adds a few remaining Galois splitting models for p=7, n=14, and adds the fields with p=3, n=15.

Once uploaded, I will update the completeness knowl (it will be all fields with n<16 and p<200).

**Comment by AndrewVSutherland** [comment]
The lf_fields table has been copied to proddb, see

   http://www.lmfdb.org/LocalNumberField/?n=15&p=3

for example.
