### ISSUE TITLE
Could not download the elliptic curves of norm conductor 1

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2973]
From the feedback page:

I could not download the elliptic curves of norm conductor 1 into a magma file.

Please respond to brumer@fordham.edu

**Comment by jwj61** [comment]
Has someone e-mailed Brumer?

**Comment by AndrewVSutherland** [comment]
I will email him once the fix is on beta.

**Comment by edgarcosta** [comment]
The fix is on beta.

**Comment by edgarcosta** [comment]
Ups, the issue was closed automatically because of the "Resolves #2973" on the PR text of  #2975

**Comment by AndrewVSutherland** [comment]
The e-mail has been sent, closing.
