### ISSUE TITLE
Confusing text for Galois rep of EC/Q

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2978]
See http://www.lmfdb.org/EllipticCurve/Q/27/a/4

Above the table we say:
```The mod $ p $ Galois representation has maximal image for all primes $ p $ except those listed.```

and below the table we say:

```
For all other primes $p$, the image is the normalizer of a split Cartan subgroup if $\left(\frac{ -3 }{p}\right)=+1$ or the normalizer of a nonsplit Cartan subgroup if $\left(\frac{ -3 }{p}\right)=-1$.
```

**Comment by AndrewVSutherland** [comment]
Did you read the knowl defining what "maximal image" means?  It means that the image is a large as possible.  For CM curves, the normalizer of a Cartan is the largest possible image, and the text below the table is simply telling you which normalizers of a Cartan occur for each prime not in the table.

I'm guessing you were assuming maximal=surjective, and this is the source of your confusion, but if there is another reason, let me know.

**Comment by AndrewVSutherland** [comment]
It's perhaps worth adding that for non-CM elliptic curves  over number fields that contain roots of unity other than +/-1, maximal also does not mean surjective (it means that the image is as large as possible, which in this case means it contains SL2).

**Comment by edgarcosta** [comment]
That was one source of confusion, perhaps we should say "maximal possible image"?

In either case, I still find it confusing having the two sentences separated by the table, as the second sentence is trying to tell me what is indeed the maximal image for almost every p.

Could we perhaps try to follow the model of when the image is surjective
```The mod $ p $ Galois representation has maximal image $\GL(2,\F_p)$ for all primes $ p $ except those listed.```
as in http://www.lmfdb.org/EllipticCurve/Q/26/b/2?

For this particular case would read:
```
The mod $ p $ Galois representation has maximal possible image $H_p$ for all primes $ p $ except those listed.
Where $H_p$ is the normalizer of a split Cartan subgroup if $\left(\frac{ -3 }{p}\right)=+1$ and the normalizer of a nonsplit Cartan subgroup if $\left(\frac{ -3 }{p}\right)=-1$
```

(honestly, I would use cases to define H_p)

**Comment by AndrewVSutherland** [comment]
I'm not necessarily against the idea of using "maximal possible image" on the curve's home page, but mathematically, I think it makes sense to use "maximal image" as a defined term (whose definition is given in the knowl).  In any case, I'd like to discuss this with @JohnCremona before making a decision.

Regarding your second suggestion, note that for elliptic curves over number fields other than Q we currently don't say anything other than that the image is maximal except at the primes listed below, and I don't think we should change this.  In the CM case the text below the table is not meant to tell you what maximal means (that is what the knowl is for!), rather it is giving you additional information about which Cartan (split or non-split) you get the normalizer of for each prime.  I worry that putting this image above the table might be more confusing, not less; the information that really matters is in the table.

But I would welcome opinions from others (and particularly from John Cremona, who designed the current layout).

**Comment by JohnCremona** [comment]
I don't mind putting all the text before the table.  I prefer not to insert
"possible" nor to make a temporary local definition but it could say
soemething like "Here maximal means..." which would be more explicit than
the general knowl defining maximal.

**Comment by edgarcosta** [comment]
I think any clarification would be appreciated. Maybe we could recall the user that the curve has CM?
I'm not the first and most likely I won't be the last to get confused by this.

**Comment by edgarcosta** [comment]
Even though I still find it confusing, I agree that this doesn't have a clear resolution that indeed improves the overall layout.
Maybe at some point, one of us will have an epiphany how to address this, but let's not leave this open while we wait for that.
