### ISSUE TITLE
Confusion regarding searches for Galois extensions with specific groups and degrees

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#2979]
I think I found a few related bugs concerning searching for number fields.
Maybe I'm just missing something huge here about Galois groups and what it means to search by Galois group, in any case this should be explained.

- Synonymous names give different results, all of S3XC3, 6T5, and 9T4 should refer to the same group, according to the naming conventions knowl (this part is correct). But all 3 of http://beta.lmfdb.xyz/NumberField/?galois_group=S3XC3 http://beta.lmfdb.xyz/NumberField/?galois_group=6T5 http://beta.lmfdb.xyz/NumberField/?galois_group=9T4 give different answers, the C3XS3 groups are partitioned into those of degree 9 and those of degree 6 for 9t4 and 6t5.

And then probably the same issue:
- Some degree and Galois group combinations think they are inconsistent, but they are fine, for example a degree 12, galois 6T3 (=D6) extension http://beta.lmfdb.xyz/NumberField/?start=0&degree=12&galois_group=6T3 should be (and is possible) but the search claims it is not
- Some signature and Galois group combinations think they are inconsistent, but they are fine, for example a degree 12, galois 6T3 extension http://beta.lmfdb.xyz/NumberField/?start=0&signature=%5B12%2C0%5D&galois_group=6T3 should be (and is possible) but the search claims it is not

**Comment by jwj61** [comment]
I think we decided that use of nTj implies that specific permutation representation on the roots.  Does that resolve the problems above (provided it is explained)?

**Comment by alexjbest** [comment]
@jwj61 Yes it does. It would help then I guess to not only have this in the galois group labels page and galois group knowl, but also as an error message if someone tries one of the last two searches.

**Comment by alexjbest** [comment]
I guess the only other thing that I think is potentially confusing here is http://beta.lmfdb.xyz/NumberField/?start=0&degree=24&galois_group=S4 , this is a query that should return no results as we only have degrees up to 23, but instead it complains that degree 24 and galois group S4 are incompatible. I guess this is because S4 does not know that it is also 24T10 as it doesn't need to right now?

**Comment by AndrewVSutherland** [comment]
Just to chime in with a few comments:

- As @jwj61 indicated, the search results are exactly what they should be.  A Galois group is a transitive permutation group, not a an isomorphism class of abstract groups (but I agree that this convention should be explicitly stated in the knowl http://beta.lmfdb.xyz/knowledge/show/nf.galois_group).

- I agree that the error message complaining about compatibility of degree and Galois group could be made clearer, for example entering 3T2 and 6 produces  "3T2 is not a valid input for Galois group. Degree inconsistent with Galois group."  I might instead suggest "3T2 denotes a transitive permutation group of degree 3, which cannot arise as the Galois group of a degree 6 extension."

- I agree that it is a bug to complain that degree 24 and S4 are incompatible (for groups whose order is greater than the maximum degree for which we know all the transitive groups we should not try to enforce compatibility).

- When displaying Galois group names and knowls, it might be better to always include the transitive group label and then put a name for its isomorphism class in parentheses.  For example, reading the knowls

http://beta.lmfdb.xyz/knowledge/show/nf.galois_group.data?n=3&t=2
http://beta.lmfdb.xyz/knowledge/show/nf.galois_group.data?n=6&t=2

side by side is a bit confusing as they appear to be giving different definitions of "S3" as a Galois group when in fact they are defining different transitive groups that are isomorphic to S3.

**Comment by davidfarmer** [comment]
"it might be better to always include the transitive group label and then put a name for its isomorphism class in parentheses"

I agree, but in the other direction. I think most viewers of the page (i.e., non-experts) would find
S_3 (6T2)
more natural:  The abstract group is S_3, realized as the permutation group 6T2.

I also think most people will search on the abstract group.  For example, I suspect
that 6T2 is less likely to be searched for directly, and more likely to appear in a search
for S3 and degree 6.  Unless you know a lot (or have interacted with people who do),
you don't even think in terms of  S3 meaning different things.

I suspect even the experts see it that way:  If I search on 6T2, the Galois group
column only says S3.

The suggestion for writing it as S3 (6T2) also applies for the home page of the field,
such as
http://beta.lmfdb.xyz/NumberField/6.0.658503.1
On that page neither the properties box nor the Galois group section mentions 6T2:
you have to click the knowl to find that information.

**Comment by AndrewVSutherland** [comment]
@davidfarmer I like this suggestion, it would also be nice to show this on search results, so that on pages like http://www.lmfdb.org/NumberField/?&galois_group=S3&ram_primes=3%2C5 you could see both S3 (3T2) and S3 (6T2) appearing in the Galois group column (this would help highlight the difference between the cubic S3 fields and their Galois closures).

**Comment by jwj61** [comment]
I updated the knowl on the naming convention to indicate the difference between using nTj and the name of an abstract group.

**Comment by jwj61** [comment]
I will add the nTj information to the number field pages, properties box, and search results (I am thinking "S3 (as 3T2)" would convey that the T notation gives a particular representation of the group).

**Comment by davidfarmer** [comment]
Currently an S3 knowl is either a 3T2 or 6T2 knowl.  Eventually it
would be good to have an S3 knowl that explains the different
realizations of S3.  That way  S3 (3T2) would be two different knowls.

I am not suggesting that needs to be done right now.

**Comment by AndrewVSutherland** [comment]
@davidfarmer as you may know, following the IAS workshop there is work in progress to expose and vastly expand the small groups database in the LMFDB.  This will include information about permutation representations and linear representations of all our small groups, as well as other information from Tim Dokchitser's groupnames database; see https://people.maths.bris.ac.uk/~matyd/GroupNames/1/S3.html for an example of the information  available for S3 (which includes 3T2 and 6T2 as permutation representations).

We have a tentative schema fleshed out for the expanded small groups database, and there is an AIM workshop taking place in May with the goal of populating and refining it.

**Comment by jwj61** [comment]
On one hand, then it would be easy to do.  On the other hand, if someone is looking at a number field page, sees that the Galois group is S_3, I think it might be confusing for them to click on that and get information which is essentially just about S_3 as a group.  As it stands, you get the knowl for 3T2 which does say that this group also appears as 6T2.

**Comment by AndrewVSutherland** [comment]
I think this issue is almost ready to be closed, but I notice that while you can now search using Galois group S3 with degree set to either 3 or 6, or D4 with degree set to 4 or 8, if you try S4 and 24 you still get an error, presumably because transitive groups of degree 24 are not yet in the database.  But even when they are, this issue is still going to crop up for other groups (there are surely always going to be abstract groups that show up as Galois groups of different degrees, one of which is outside the range of our transitive group database).

I would suggest that we should only display an error message in cases where we actually know the complete list of degrees of transitive permutation representations of an abstract group typed in to the search box; to make this check efficient, we probably want to store this information as a list of integers in a single column (which may be null).  In cases where we do not know the complete list we should just run the search (we will get zero results if the degree really is incompatible, which is fine).

This is perhaps something that could be addressed during the AIM workshop on groups in the LMFDB next week.

**Comment by AndrewVSutherland** [comment]
#3289 is now live on www.lmfdb.org, closing.
