### ISSUE TITLE
Field of Kronecker character

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2994]
In the table at the bottom of this page:
    http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/17/3/e/b/
there is a heading "Type".

1) "Type" is not a good name.  Is "Field" an acceptable heading?
(I do not think it is confusing to see "CM by Qsqrt-3" under the "Field" heading.)

2)  I deleted "this column shows" from the knowl for that column heading,
since the knowl was just a definition of what that column contains.

3) It took me a while to understand that the heading of the table was
"Inner twists" but the column heading mentioned above was only
relevant to those rows that are self-twists.   (Which is why there are
blank entries in that table.)  I don't have a suggested fix,
but somehow it should be more clear that the self twist (which does not
always exist) is special and more information is provided about it.

**Comment by edgarcosta** [comment]
Here is a more illustrative example of the type column: http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/120/1/i/a/

**Comment by AndrewVSutherland** [comment]
I think changing for the "Type" column to "Self Twist" might address both 1 and 3 (and is more informative than "Field").  I would then edit the knowl to explain that inner twists which are self twists are either trivial or the Kronecker character of a quadratic file (which may be imaginary (CM) or real (RM)).

Does that sound reasonable to you @davidfarmer?

We could also put "no" in the entries that are currently blank, but personally I think blank is fine (and less busy).

**Comment by davidfarmer** [comment]
I agree that Self twist is better than Field and addresses my concern.

**Comment by AndrewVSutherland** [comment]
Addressed by #2998, closing.
