### ISSUE TITLE
Definition of dual L-function

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#3001]
This refers to the knowl
http://beta.lmfdb.org/knowledge/show/lfunction.dual

I'm not sure if this is the best definition in general, is it?
See my comment there as well.

**Comment by davidfarmer** [comment]
Yes, in complete generality the dual L-function is the L-function with the complex conjugate
Dirichlet coefficients.

The dual of the L-function of an automorphic representation is the L-function of the
dual (contragredient) representation.  But in terms of the L-function as a complex
analytic function, it is the same.

**Comment by sehlen** [comment]
I don't want to bother you with this, but is this a theorem or a definition?

I don't have a good reference at hand but I remember that I've seen people just write down a functional equation where the dual Dirichlet coefficients a^* appear on the other side not defining them to be the complex conjugates.

What I found right now was in the pari documentation (https://pari.math.u-bordeaux.fr/dochtml/html/_L_minusfunctions.html):
"More often than not in number theory we have a^ *= \bar{a} (which forces |ε |= 1), but this needs not be the case." 

And isn't something like the partial completed L-function for a Hecke Grössencharacter for an ideal class (like in Parapgraph 8 of chapter VII Neukirchs book on algebraic number theory) maybe examples, where something like the inverse of the class appears on the rhs of the functional equation?

I guess the point is that these functions are not be L-functions according to your/the LMFDB-definition because the definition of the functional equation of an analytic L-function in the LMFDB apparently already asks for the complex conjugate to be the dual... but this seems almost a bit circular... 

I guess all I'm saying is that maybe it makes sense to add a sentence that depending on the definition, this is the L-function "on the rhs of the functional equation", which for the class of functions appearing in the LMFDB is always the one with complex conjugate Dirichlet coefficients??

**Comment by davidfarmer** [comment]
It is fine to point out that the dual L-function is what appears in the
functional equation.

The only possible exception to my assertion that "dual" means
"conjugate coefficients" is for an object that does not
satisfy a functional equation in the Selberg class, or a Langlands
L-function, or an L-function of an automorphic representation,
does not satisfy the Riemann Hypotheses, etc etc.

The L-functions in the LMFDB are those that appear in the Langlands
program.

Note that the functional equation does not really involve two
L-functions.  It involves one function, and that function has
a symmetry around the line Re(s) = 1/2 .  The mapping from C to C
that fixes the line Re(s) = 1/2 is   s \mapsto conjugate(1 - s) .

It is such a symmetry of the function that leads to any hope of
having a Riemann Hypotheses.

**Comment by sehlen** [comment]
I completely agree.
It's only when you look at such a knowl the definition seems so universal and it could maybe sometimes be misleading. We have to realize that knowls are now appearing out of context.
For instance, for many mathematical terms, if you google them, one of the first results is now a lmfdb knowl, and I think we should also keep this in mind.

Maybe I can prepare a revision of the knowl and you can review it later.
