### ISSUE TITLE
motivic weight

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#3002]
I have been reviewing the L-functions knowls
and I was wondering if there is any reference for the motivic weight of an L-function and if it really makes sense to defines this for any L-function!? @AndrewVSutherland 

See:
http://beta.lmfdb.org/knowledge/show/lfunction.motivic_weight

**Comment by davidfarmer** [comment]
Motivic weight makes sense for algebraic/arithmetic primitive L-function.
If can be defined in terms of the coefficients (as in that knowl) or in terms
of the Gamma-factors.

See page 270:

https://www.ams.org/journals/bull/2019-56-02/S0273-0979-2018-01646-7/S0273-0979-2018-01646-7.pdf

**Comment by AndrewVSutherland** [comment]
@davidfarmer or @nathancryan  can surely give a more complete answer to this question than I can, but you can find the definition for motivic L-functions in Section 4.5 of https://arxiv.org/abs/1711.10375, for example.

**Comment by AndrewVSutherland** [comment]
@davidfarmer @sehlen Are any changes to the motivic weight knowl required or can we close this issue?

**Comment by AndrewVSutherland** [comment]
I added a parenthetical (arithmetic weight) to the knowl (which is the term used in Definition 4.2 which @davidfarmer referred to above).

**Comment by jvoight** [comment]
I'm confused about Definition 4.2 in FPRS.  If you have an elliptic curve E over the rationals with multiplicative reduction at p, then a_p = +/-1.  So if you want a_p p^(w/2) to be an algebraic integer, you have to take w = 0.  So I think you want to look only at a_n with n coprime to the conductor N.  (Indeed, we don't really have control over the Newton polygons at bad factors.)

**Comment by davidfarmer** [comment]
A_p is +- 1 in the arithmetic normalization, so a_p is +- 1/sqrt(p) in the
analytic normalization.

The trick I use to keep it straight is lower case for analytic
normalization and upper case for arithmetic normalization.
So A_p are rational integers, and in general A_p = a_p p^(w/2) .

**Comment by sehlen** [comment]
With the parenthical I'm somewhat happier now and even though I still think there could be some more explanations/notes
I don’t think we need this issue anymore for now.

**Comment by jvoight** [comment]
Ah!  OK, foiled again by normalizations.  I'm happy if we say that the L-series is analytically normalized, like in the current version (even though I still worry about bad factors).

**Comment by davidfarmer** [comment]
Not going to reopen, but I would like to understand the concern about bad 
factors.

Does it make sense that, in fairly wide generality, the arithmetic
normalization has integer coefficients?  That is, integer coefficients
in the Dirichlet series.  Equivalently, in the coefficients of the
denominators of the local factors at all places?

If your mental model has integer coefficients everywhere, then I don't
think it is so bothersome that there are both good and bad factors.

When looking at the analytic normalization and trying to determine the
motivic weight, there are two issues:

1) The parity of the weight.

What I wrote above is supposed to make that a non-issue.

2) Clearing denominators.

Once you know the parity of the weight, you still need to multiply by
a large enough power that you have an integer instead of just a rational
number.  I suppose the finite number of bad factors could somehow
require a larger power, but maybe the restrictions on possible bad
factors says that cannot happen?

**Comment by jvoight** [comment]
Hi David,

I don't think a closed issue on github is the best way to discuss this!

> Does it make sense that, in fairly wide generality, the arithmetic
> normalization has integer coefficients? That is, integer coefficients
> in the Dirichlet series. Equivalently, in the coefficients of the
> denominators of the local factors at all places?

Do you mean algebraic integer coefficients?  

Even if the coefficients are rationals and we want to talk integers, the question of "arithmetic normalization" can vary.  For example, when you take the L-function attached the the Neron-Severi group of an algebraic surface, the motivic weight is zero but it comes naturally from an H^2, so either you immediately remove some extra powers of p or you think they belong, and I don't know if I could say honestly what "widely" is held for the correct normalization--especially when the motives get more complicated.  No matter what you decide, there is always a discussion of "Tate twist" (and the conventions for this twist), and usually the best thing to do is just to be clear at the outset what you are taking to be your normalization (like is now done on this knowl).  

> When looking at the analytic normalization and trying to determine the
> motivic weight, there are two issues:
>
> 1) The parity of the weight.
>
> What I wrote above is supposed to make that a non-issue.
>
> 2) Clearing denominators.
>
> Once you know the parity of the weight, you still need to multiply by
> a large enough power that you have an integer instead of just a rational
> number. I suppose the finite number of bad factors could somehow
> require a larger power, but maybe the restrictions on possible bad
> factors says that cannot happen?

As you know (!), the good factors are supposed to determine the finitely many bad factors.  So if we are assuming conjectures this shouldn't be an issue.  

Do you prefer a "safer" definition (one that makes sense for partial/incomplete L-functions), or a "stronger" one (harder to satisfy) that propagates/leans on a mathematical worldview?  

Or maybe you're asking: what could go wrong?  The answer is supposed to be nothing.  The "motivic weight" is supposed to guide us to the minimal w such that the Galois/automorphic representation giving rise to the L-function occurs in some H^w(X, QQ_ell^al), independent of ell, at least when this makes sense.  So if we want to assume that everything works out, then we should not need to worry about bad or good factors.

**Comment by davidfarmer** [comment]
I agree it is confusing that the definition given is the
minimal weight, and any "extra" powers of p are lost in the
analytic normalization.

In the lfunction.motivic_weight knowl I added a new paragraph.
It might need some tweaking, and I'll let someone else approve it.

-- new paragraph --

If the L-function arises from a motive, then the weight of the motive has 
the same parity as the motivic weight of the L-function, but the weight of 
the motive could be larger.  This apparent discrepancy comes from the fact 
that a Tate twist increases the weight of the motive.  This corresponds to 
the change of variables $s \mapsto s + j$ in the L-function of the motive.

--------

**Comment by jvoight** [comment]
Thanks David!  Sorry for any confusion I caused.
