### ISSUE TITLE
Special values of L-functions

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#3004]
The definition of special L-values seems a bit too vague to me.
The one I know is that in an arithmetic normalization, the values at integer parameters are called special. 
I would like some input on this terminology before I set the status to "reviewed".

http://beta.lmfdb.org/knowledge/show/lfunction.special_values

**Comment by davidfarmer** [comment]
I suggest deleting the Special values knowl and the (one) link to it.

One day we will have special values in the LMFDB.  At that time we can do it properly.
It would take a lot of work to fix this, and then it is still not really used anywhere.

**Comment by pascalmolin** [comment]
Well, I think this is one major set of conjectures about L functions, so the LMFDB should provide some information about it.

I just looked at the paper "periods" of Kontsevitch&Zagier, §3.2. Under "Deligne-Beilinson-Scholl conjecture", it states that the value L^(r)(m) of an L function at any integer m where it vanishes at order r should be a non zero generalized period (that is the integral of a rational function on a rational domain up to powers of pi).
Examples are the class number formula, Birch&SwinnertonDyer conjecture and Deligne critical values at 1..k-1 for modular forms.

The period in question should be related to the underlying object. This is still vague, but an interesting reference in my opinion.

**Comment by AndrewVSutherland** [comment]
It looks like the knowl has been deleted, so I am going to close this issue.  @pascalmolin if you want to take a stab at writing a new version of this knowl (or undeleting and editing the old version), please feel free to do so.  I think the key point is that knowls attached to mathematical terms in the LMFDB need to give a definition of the term that clearly explains its usage in the LMFDB.  Given the limited amount of information we currently have on special values (pretty much none other than central values), it might make sense to wait to do this until we have more information and a plan for how to present/search on it.
