### ISSUE TITLE
Riemann Zeta function knowl

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#3005]
There is a nice knowl about the Riemann zeta function: http://beta.lmfdb.org/knowledge/show/lfunction.riemann

However, all this information is not visible on the website of the Riemann zeta function.
I think this knowl should be inserted into the Riemann zeta function website
or linked (as a knowl) from there at least:
http://beta.lmfdb.org/L/Riemann/

**Comment by davidfarmer** [comment]
This could be linked as a "read more" at the end of the top knowl on the zeta function page
(unless someone has a better idea).

**Comment by roed314** [comment]
Good idea.  I've edited the top knowl; feel free to update it.  I think this issue can now be closed.
