### ISSUE TITLE
factorization of conductor of an L-function

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#3006]
If the conductor of an L-function is equal to 1, the 1 is shown twice like here:

http://beta.lmfdb.org/L/Riemann/

<img width="290" alt="Screenshot 2019-04-30 at 17 42 10" src="https://user-images.githubusercontent.com/2471633/56974509-4a15df00-6b6f-11e9-9bc7-3fce76a8ce45.png">

**Comment by AndrewVSutherland** [comment]
Addressed by #3276
