### ISSUE TITLE
Mention how normalization affects critical line and critical strip

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#3007]
The knowls 

http://beta.lmfdb.org/knowledge/show/lfunction.critical_line 
and
http://beta.lmfdb.org/knowledge/show/lfunction.critical_strip

should mention the normalization of the LMFDB and how this affects the definition.

While the knowl for the critical line does not mention that this is always the line at s=1/2 in the LMFDB, the one for the critical strip only gives the normalized definition.

I reviewed both knowls positively because these are not serious issues and I didn't want to delay the process for the release but if anyone (maybe @davidfarmer?, @AndrewVSutherland? @alinabucur?, @alexjbest?) wants to edit these now on beta, I can review them again before Friday.

**Comment by davidfarmer** [comment]
I edited the critical line and critical strip knowls, and deleted the comments on them.

This issue can be closed once the updated knowls are approved.

**Comment by sehlen** [comment]
Thanks a lot!

I approved the edits, they look perfect to me (I only added a knowl-link to the motivic weight).
