### ISSUE TITLE
Add definition of Hecke eigenvalues

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#3010]
The page http://beta.lmfdb.org/L/degree2/EllipticCurve/ should define the a_p's.

**Comment by davidfarmer** [comment]
I think there should be a knowl specifically about the L-function of an elliptic curve/Q,
and then rearrange the sentence to say
  The L-function of an Elliptic curve E/Q ....,
where "L-function of an Elliptic curve E/Q" is the knowl.

But unless that knowl exists, I don't think this page needs to be changed.
(The $a_p$ are sort-of implicitly defined by the Dirichlet series.)

I suggest addressing this, but not now.

**Comment by sehlen** [comment]
I agree, this does not have to be addressed now.
I'm only making issues right now of anything that I observed or my referees observed while looking at the knowls. If I don't add the issues right now, it will be forgotten./

A knowl could be part of the solution although the page does nothing else than to define the L-function of an elliptic curve.

But while the $a_p$ are defined by the Dirichlet series, the Dirichlet series is of course also not defined ;-) Right now, it is not clear at all, how to obtain such a Dirichlet series from an elliptic curve (looking at this page). That's all I'm saying.

**Comment by JohnCremona** [comment]
In the context of an elliptic curve L function surely the right way to refer to a_p is is the Trace of Frobenius at p?  Suitably modified for bad primes of course.  But there is no knowl for that yet.

**Comment by davidfarmer** [comment]
Closing, because this page will not exist once issue #3945 is addressed.
