### ISSUE TITLE
Make browsing for L-functions by underlying object consistent

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#3011]
L-functions of degree 2,3,4 can also be browsed by underlying object.

Sometimes, there are special pages for these L-functions,
like http://beta.lmfdb.org/L/degree2/CuspForm/

But in many cases, the link really goes to the page for the underlying objects
which then only link to the L-functions as friends.
For instance, click on "Artin representations" on http://beta.lmfdb.org/L/degree2/.

This is inconsistent. My feeling is that the special pages, like for cusp forms, are better.

**Comment by edgarcosta** [comment]
I don't like the incosistency, but honestly, I don't think we should support pages of the type
http://beta.lmfdb.org/L/degreeN/ClassO/
perhaps only
http://beta.lmfdb.org/L/ClassO/ ?

For example, 
we have
http://beta.lmfdb.org/L/degree2/EllipticCurve/
but not
http://beta.lmfdb.org/L/degree4/EllipticCurve/
someone can create the latter page, but it is not clear to me that is worth the effort, I don't really see what is the added value of the first page either.

For cusp forms we kept
http://beta.lmfdb.org/L/degree2/CuspForm/ 
mostly for backward compatibility, in hindsight the graph is cool, but the effort getting it right was way too much, and I don't think many people have looked into it.
and we have a route for 
http://beta.lmfdb.org/L/degreeN/CuspForm/  = http://beta.lmfdb.org/L/degree2/CuspForm/ 

but honestly, it should be http://beta.lmfdb.org/L/CuspForm/

**Comment by sehlen** [comment]
I guess the point is that a page like 
http://beta.lmfdb.org/L/degree2/EllipticCurve/
really catalogs L-functions corresponding to certain underlying objects whereas 
the navigation is a little but weird if you go to L-functions -> degree2 and then click on the link "artin representation" where you just left the L-function pages completely and you could've directly looked at Artin representations. This also now means that selecting an object here does open the page of that object and not of the L-function of that object. but I was looking for L-functions (of degree 2)!

Maybe I'd like to look at all of those of degree 2 coming from Artin representations
and order by (in a non-existing table) the absolute value of L(1/2) or the imaginary part of the first zero.

I somehow just think that you should only jump to a different object by clicking on a friend link.

But I *do* understand your concerns.

I guess I don't want any fancy graphs or anything, just a browsing page
for these "underlying objects" that catalog them like the artin representation page does
but with some facts about the l-functions (like lowest zero or whatnot) in the table and
that link to the l-function directly so that the navigation works as
in the case of degree 2 l-functions coming from elliptic curves.

**Comment by davidfarmer** [comment]
We are moving in the direction of providing a global view of the objects in the LMFDB,
and the /L/degree2/CuspForm/ page is a good example.  I think we will be able to generate
many such pages as we put more L-function data in the database, refine our ideas of
L-functions as pure objects, and have more examples of sources.

Which is to say:  those "underlying objects" pages are not worth looking into right now,
but will be supplanted as we start flexing our L-functions muscles.

@edgarcosta I understand the difficult of making good plots and I appreciate the holomorphic cusp form L-function plot.

**Comment by AndrewVSutherland** [comment]
Closing as these pages have been superseded by the general L-function search https://www.lmfdb.org/L/ (which could certainly still be improved, but requests for improvement should be raised as new issues).
