### ISSUE TITLE
Defining polynomial as an invariant

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#3012]
On the home page of an embedding of a modular form, such as
http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/53/2/b/a/52/1/
there is a subsection called "Embedding invariants".

One of those invariants is "Root", which is a numerical approximation to
one of the roots of the defining polynomial.  But on that page there is no mention
of what the defining polynomial is.  Maybe that should go in the previous
subsection, right after "coefficient field"?  (I assume the defining polynomial
of the form is not necessarily the defining polynomial of the coefficient field?
Either way, see next paragraph.)

The knowl on "Root" is a general knowl about embeddings of number fields.
This should be a knowl about the defining root of the modular form, or about
embeddings of newforms (if that contains the information someone is looking for
when clicking on "root").  If the defining polynomial is the same as the defining
polynomial for the field, then the knowl should say that, and maybe then you don't need
to add that polynomial to the page, because it is implicit in the "field" entry.

**Comment by rbommel** [comment]
Tried to solve this via pull request #3764.

**Comment by edgarcosta** [comment]
@davidfarmer and @rbommel are discussing a solution for this.

**Comment by davidfarmer** [comment]
@rbommel I am ready to resume discussing this.  One mathematical question first:  is the defining polynomial, as shown in the "Root" entry under "Embedding invariants"?
I assume it is, but don't want to assume that if it isn't always the case.

Then what I think should be done is:

a) Add the defining polynomial directly beneath Coefficient field under Newform invariants.

b) In the Root entry under Embedding invariants, replace the defining polynomial by the words "the defining polynomial".

c) Replace the knowl for Root by a new knowl that explains how each embedded newform comes from a root of the defining polynomial.

**Comment by rbommel** [comment]
@davidfarmer 
Yes, the polynomial is supposed to be the polynomial of which we give the numerical approximation to one of its root. Okay, I tried to improve this, see #4022. Please let me know if I understood everything correctly now.

**Comment by edgarcosta** [comment]
The PR is an improvement and now on beta.lmfdb.org

**Comment by davidfarmer** [comment]
I agree, and thank you for saving me the effort to review the PR!

**Comment by edgarcosta** [comment]
@davidfarmer should we close the issue?

**Comment by davidfarmer** [comment]
Good.  Closing and reviewing the new knowls.
