### ISSUE TITLE
remove lfunc instances for non-existent BMFs

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#3039]
I only know of three:
* `ModularForm/GL2/ImaginaryQuadratic/2.0.1879.1/1.0.1/a/`
* `ModularForm/GL2/ImaginaryQuadratic/2.0.643.1/1.0.1/a/`
* `ModularForm/GL2/ImaginaryQuadratic/2.0.10691.1/1.0.1/a/`

that come for the 3 CM-fields (where we only have one EC) where we have L-fcn but not BMFs.

@JohnCremona, can you confirm that for the other fields, D = -1, -2, -3,-7, and -11,  we have a bijection between dim 1 BMFs and EC without `CM` in their label?

**Comment by JohnCremona** [comment]
No.  There are dim 1 bmfs with no elliptic curve.  I have the list of these and for each it it a fact that there is no elliptic curve.  I do plan to show this better than at present on the bmf home pages but for now it says 'No elliptic curve' or similar in the Friends list.

**Comment by edgarcosta** [comment]
But is there a dim 1 BMF for EC without CM in their label? (this is indeed the direction that I care about)

**Comment by JohnCremona** [comment]
Yes in that direction!

**Comment by edgarcosta** [comment]
Ok, then I have removed all the  instances for non-existent BMFs
