### ISSUE TITLE
Next button on number field browse page broken

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3072]
If you do any number field search with more than 50 results there is no way to see results past the first 50 because the next button simply redisplays the first 50 (on both beta and web).  I'm not sure when this happened, but it should be easy to fix.

**Comment by edgarcosta** [comment]
start is being converted to None

@roed314 will look into this later in the afternoon

**Comment by AndrewVSutherland** [comment]
Now fixed on beta and production via #3075.

**Comment by edgarcosta** [comment]
everything has been fixed.

I also fixed the data issue in other instances.
