### ISSUE TITLE
Coloring on sidebar

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3080]
On the sidebar, there are two background colors which alternate for subsections.  Some of these are only on beta, so effect on the main site is that everything has one background color except for abelian varieties over finite fields, which makes it look odd.

**Comment by AndrewVSutherland** [comment]
I'm actually making a sidebar change now (to standardize how top level browse pages are accessed, I'm putting them all in app.py, right now there is a mix).  I'll fix this in that PR.

**Comment by AndrewVSutherland** [comment]
Addressed by #3082.
