### ISSUE TITLE
Statistics pages broken: g2c and cmf

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3085]
On the main site, the stat pages for genus 2 curves and classical modular forms both give server errors.  Both work on beta.

**Comment by AndrewVSutherland** [comment]
I think stats just need to be refreshed.  genus 2 is fixed and I'm refreshing cmf stats now (may take a while).

**Comment by AndrewVSutherland** [comment]
cmf stats are refreshed but the stats are still broken, this will require some more digging.

**Comment by edgarcosta** [comment]
everything has been fixed.

I also fixed the data issue in other instances.
