### ISSUE TITLE
Bianchi newform dimaension pages broken

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#3092]
http://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/gl2dims/2.0.4.1
(which is a link from the BMF front page) crashes.

Something like this happened recently and was fixed.

**Comment by JohnCremona** [comment]
This and similar pages work on beta, so it is a data issue.  Perhaps copying all the bmf* tables to web would be a good idea as a first step.

**Comment by AndrewVSutherland** [comment]
Done and this fixes the problem.
