### ISSUE TITLE
ordering of elementary divisors in class groups

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#3100]
The elementary divisors in class group are sometimes in increasing order, as in
http://www.lmfdb.org/NumberField/4.0.168192.5
and sometimes in decreasing order, as in
http://www.lmfdb.org/NumberField/3.1.11003.1
This is problematic since only the increasing order is accepted in searches, so the second example currently cannot be found by searching by class group structure.

**Comment by JohnCremona** [comment]
pari/GP uses descending order while every one else uses ascending order.  Sage has to make various annoying adjustments after calling Smith Normal Form for this reason.  I suggest always using increasing order (as I do with torsion subgroups for elliptic curves).

**Comment by jwj61** [comment]
I will change them to all be increasing.

**Comment by jwj61** [comment]
This is fixed on beta by changing the entries in the database.  So, nf_fields needs to be uploaded to the cloud to fix it on the main site.

**Comment by AndrewVSutherland** [comment]
OK, I'll take care of this as soon as #3098 is merged (this PR addresses some issues with reloading).

**Comment by JohnCremona** [comment]
#3098 is now merged!  Can we close this?

**Comment by AurelPage** [comment]
It looks to me like this is fixed.

**Comment by JohnCremona** [comment]
@AndrewVSutherland ?

**Comment by AndrewVSutherland** [comment]
Yes, the nf_fields table did get copied over and this issue is resolved, thanks for following up.
