### ISSUE TITLE
Random for the whole database

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#3102]
I really love hitting the random button on the browse/search pages.  Could we have a random button for the whole LMFDB?  :)

**Comment by edgarcosta** [comment]
If you allow me to pick a <class> from the sidebar objects at random, then one could just redirect to <class>/random

**Comment by AndrewVSutherland** [comment]
This would not be hard to implement; we might want to think a bit about how the top-level choice to be distributed (otherwise most random objects will be number fields, or L-functions if we decided to include them (there currently is no L/random link, but we could easily add one).

**Comment by edgarcosta** [comment]
@AndrewVSutherland, that is what I meant, first we pick a sidebar element at random X, e.g. CMFs or G2C, and then use the already builtin route X/random to give a random element.

Where would we place this random button?

**Comment by jvoight** [comment]
Yup, that's exactly what I had in mind.  I guess we'd want to put this on the main page (http://www.lmfdb.org/), maybe in the "Search and Browse" box?  If there's more interest, we could try to make a "I'm Feeling Lucky" button or link more prominent...
