### ISSUE TITLE
Missing results in higher genus aut searches

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3107]
From the feedback page:

> The group [8,3] appears as a subgroup of an automorphism group of a curve of genus 3, such that the signature is [1;2]. It appears in this list.
> http://www.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=3&group_order=8
> 
> Note that the spacing in the [8,3] for this entry is slightly different: [8, 3].
> 
> But this entry fails to appear upon searching directly for [8,3] in genus=3:
> http://www.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=3&group=%5B8%2C+3%5D
> 
> I think it may have something to do with the spacing. The search feature doesn't seem to distinguish whether there is a space there or not, but results seems sensitive to it.
> 
> Thanks for your help!
> Justin Lanier

Reply to jlanier8@gatech.edu

**Comment by jenpaulhus** [comment]
This one too!
http://beta.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=3&group=%5B8%2C+3%5D

(Although this one is related to the updated data which does need to be migrated to production eventually so I guess maybe it's not fully resolved yet.)

**Comment by AndrewVSutherland** [comment]
The updated data is now in production:

http://www.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=3&group=%5B8%2C+3%5D
