### ISSUE TITLE
Unable to search high genus curves for signatures with semicolons, e.g. [1;2]

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3108]
From the issue tracker:

> There is a genus 3 curve whose automorphism group has a subgroup with signature [1;2]
> 
> http://www.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=3&group_order=8
> 
> But when I try to search for a signature of [1;2] with genus 3 (or other genera), the search result turns up empty
> 
> http://www.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=3&signature=%5B1%3B2%5D
> 
> In fact, the page changes the semicolon to a comma on the results page. It appears that in general there is a problem with searching for signatures that involve a semicolon.
> 
> Looking forward to an update. The site is very useful, thanks!
> Justin Lanier

Reply to jlanier8@gatech.edu

**Comment by jenpaulhus** [comment]
I think this can be closed as well.  Notice:
http://beta.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=3&signature=%5B1%3B2%5D

**Comment by AndrewVSutherland** [comment]
And it is now fixed on the production site

http://www.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=3&signature=%5B1%3B2%5D
