### ISSUE TITLE
Server error for a higher auto page

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3111]
From the feedback page:

> server error for this page:
> 
> http://www.lmfdb.org/HigherGenus/C/Aut/3.2-1.2.0.1
> 
> I arrived at it from this search result.
> 
> http://www.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=3&count=200
> 
> It's the search result with signature [2;2]
> 
> Thanks,
> Justin Lanier
> 

Reply to jlanier8@gatech.edu

**Comment by jenpaulhus** [comment]
I think this can now be closed.  Notice:
http://beta.lmfdb.org/HigherGenus/C/Aut/3.2-1.2.0.1
is fixed by last pull.

**Comment by AndrewVSutherland** [comment]
Agreed, but let's wait until the server error is actually fixed in production (http://www.lmfdb.org/HigherGenus/C/Aut/3.2-1.2.0.1 still fails).  I will push the data and the last PR to production momentarily.

**Comment by AndrewVSutherland** [comment]
The fix is now live, thanks Jen!
