### ISSUE TITLE
Server error on knowl regex search

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3132]
Regex knowl searches that being with an asterix throw a server error:

http://www.lmfdb.org/knowledge/?search=*&regex=on

**Comment by edgarcosta** [comment]
That is not a valid regular expression. https://www.postgresql.org/docs/9.3/functions-matching.html

Did you mean http://www.lmfdb.org/knowledge/?search=.*&regex=on ?

**Comment by AndrewVSutherland** [comment]
Agreed, but it should say that, not throw a server error (throwing a server error is a bug, by definition).

**Comment by AndrewVSutherland** [comment]
Fixed by #3134.
