### ISSUE TITLE
Update Galois groups completeness knowl

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3142]
The database now contains over 200,000 transtivie groups, many more than the 4953 of degree up to 23 mentioned on

http://www.lmfdb.org/GaloisGroup/
http://www.lmfdb.org/GaloisGroup/Completeness

This issue is just a reminder that we need to update the completeness knowl to reflect the current content (once we are satisfied with it) prior to Release 1.1.1.

**Comment by jwj61** [comment]
Relevant to this, the gps_transitive table can be copied to the cloud.

**Comment by edgarcosta** [comment]
Done!

**Comment by jwj61** [comment]
The knowls have been updated.

I am leaving this open since maybe they should be reviewed first.
