### ISSUE TITLE
Group C_4 wreath C_2 latex not displaying

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#3146]
See http://www.lmfdb.xyz/knowledge/show/group.small.data?gapid=32.11 , C_4wrC_2 should read C_4\wrC_2 so it renders with  a wreath product symbol, this is a data issue with the pretty field of gps_small: id 96.

**Comment by jwj61** [comment]
Fixed on beta (along with other missing backslashes).  The gps_small database should be uploaded to the cloud.

**Comment by AndrewVSutherland** [comment]
Done, now fixed on www.lmfdb.org.
