### ISSUE TITLE
HGCWA search of group order with genus variable

### ISSUE THREAD

**Issue by jenpaulhus** [LMFDB/lmfdb#3148]
Once upon a time, on /HigherGenus/Aut/C,  one could input an expression like 84(g-1) in the group order search box and a search would be returned that gave any example where the group order was that value for the genera which were searched over. (So in this case it would give all Hurwitz curves in the database.)

That functionality has disappeared somewhere along the line.

**Comment by jenpaulhus** [comment]
You can assign me to this (I don't immediately see how to assign myself to it).

**Comment by jenpaulhus** [comment]
@roed314  Can we close this?  It looks like I implemented this in #3516 however in a less than ideal way.   But to fix it permanently would first require #3580.

**Comment by roed314** [comment]
Sounds good.  If we get #3580 working, we can revisit various things.
