### ISSUE TITLE
Specify number of ramified primes in number field search

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3160]
From the issue tracker:

The online Jones-Robert tables of number fields gave the option of bounding the number of ramified primes. I almost always used this feature, since it's nice to have examples of fields ramified at exactly one prime which is unknown in advance (or possibly ramified at the prime 2 and a single other prime not known in advance). Could that functionality be included here? 

Responded to the reporter by e-mail that I will do this.

**Comment by edgarcosta** [comment]
Addressed by #3170
