### ISSUE TITLE
Some EC/Q pages not showing top knowls

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#3163]
[As reported by Enrique Gonzalez Jimenez]

Pages 
http://www.lmfdb.org/EllipticCurve/Q/121/b/2
and
http://www.lmfdb.org/EllipticCurve/Q/121b1/
are the same curve, shown with LMFDB label primary or with Cremona label primary.  The first shows the top knowl / annotation correctly but the second does not.

I will fix this: it is just a question of assigning KNOWL_ID correctly.

**Comment by edgarcosta** [comment]
Resolved by #3165
