### ISSUE TITLE
Problem with upsert

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3172]
Maybe I don't have the syntax right, but the following gives an error:

db.nf_fields.upsert({'degree':23,'disc_rad':139}, {'regulator': 22066241000437346.10236048207})

**Comment by edgarcosta** [comment]
Can you share the tracebak with us?

**Comment by jwj61** [comment]
SyntaxError                               Traceback (most recent call last)
<ipython-input-14-4cae1d044d77> in <module>()
      1 db.nf_fields.upsert({'degree':Integer(23),'disc_rad':Integer(139)},
----> 2     {'regulator': RealNumber('22066241000437346.10236048207')})

/scratch/home/jj/lmfdb/lmfdb/backend/database.pyc in upsert(self, query, data, commit)
   2821                     dvalues = self._parse_values(dat)
   2822                     dvalues.append(row_id)
-> 2823                     self._execute(updater, dvalues)
   2824                 if not self._out_of_order and any(key in self._sort_keys for key in data):
   2825                     self._break_order()

/scratch/home/jj/lmfdb/lmfdb/backend/database.pyc in _execute(self, query, values, silent, values_list, template, commit, slow_note, reissued, buffered)
    386                     except Exception:
    387                         context = ' happens while executing {} with values {}'.format(query, values)
--> 388                     reraise(type(e), type(e)(str(e) + context), sys.exc_info()[2])
    389             if silent is False or (silent is None and not self._db._silenced):
    390                 t = time.time() - t

/scratch/home/jj/lmfdb/lmfdb/backend/database.pyc in _execute(self, query, values, silent, values_list, template, commit, slow_note, reissued, buffered)
    380             else:
    381                 try:
--> 382                     cur.execute(query, values)
    383                 except (OperationalError, ProgrammingError, NotSupportedError, DataError) as e:
    384                     try:

SyntaxError: syntax error at or near ")"
LINE 1: UPDATE "nf_fields_extras" SET () = () WHERE id = 19799738
                                       ^
 happens while executing UPDATE "nf_fields_extras" SET () = () WHERE id = 19799738

**Comment by jwj61** [comment]
Fixed
