### ISSUE TITLE
Optimality of elliptic curves /Q

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#3181]
The web pages for elliptic curves and isogeny classes over Q claim show which curve in each class is Gamma_0(N)-optimal but this has not been proved in all cases.  A more complete story is told in [these notes](https://github.com/JohnCremona/ecdata/blob/master/doc/manin.txt).  Note that I have in all *optimal* cases shown that the Manin constant is 1, but curve home pages do not say this.

- [x] I will right away add something to both isogeny class and curve home pages to alert users that we do not always know which curve in the class is optimal.  This is only necessary when the class has more than one curve and the conductor is >60000.  At the same time each optimal curve's home page should state that the Manin constant is known rigorously to equal 1.  I have not yet computed all the Manin constants for non-optimal curves -- something else to do. 20190809: optimality verified for all conductors to 250000, with 2 exceptions (see below).

- [ ] I have [data files](https://github.com/JohnCremona/ecdata/tree/master/optimality) listing all the currently ambiguous cases (which isogeny classes, and which are the possible optimal curves).  This data could be uploaded into a new optimality column in the ec_curves table in order to display better information, pending the next action begin completed.

- [ ] For any of the 245299 currently ambiguous classes I can carry out extra computations to remove the ambiguity.  Each one does not take too long but it would take several weeks at least to process all of them. 20190729: optimality verified for all conductors to 250000:  no change in data required in the range 60k-250k except for two classes (235470bb and 235746u) requiring the two curves with Cremona numbers 1 and 2 to be swapped (not yet done).  There are 8 further such classes between 250000 and 400000 which will be switched.

**Comment by JohnCremona** [comment]
I am in the process of computing all the Manin constants --given that the optimal curve has c=1 that is quick, and almost all are 1 anyway (I have yet to see c>3 except for 11a3, 15a8 and 17a4 which have c=5,4,4).  The computations proving that curve#1 is optimal in all cases will take much longer (at least a month, probably longer).

**Comment by JohnCremona** [comment]
I have added new columns 'optimality' and 'manin_constant' to the ec_curves table, currently filled with default values.  The plan is to encode what we know as follows:

   - 'optimality'=1 if proved optimal, 0 if proved not optimal, n>0 if it is one of n curves in its isogeny class which might be optimal.  For conductors up to 250000 (so far) the only values are 0,1 but for larger conductors it can be up to 6.  (For example the class may have 8 curves of which we know that 2 are not optimal, the other 6 have this value set to 6.)  

   - 'manin_constant'=m means that the Manin constant is proved to be m assuming that the curve numbered 1 in its class (Cremona numbering) is optimal.

The web pages will display this data with suitable caveats.  Meanwhile the crossover at 250000 will in time increase but it's a lot of CPU time.

**Comment by JohnCremona** [comment]
Table ec_curves now has correctly filled in values for 'optimality' and 'manin_constant' for all curves in there now (N<410000).

**Comment by AndrewVSutherland** [comment]
Do you want me to copy ec_curves over to the production database now, or should I wait?

**Comment by JohnCremona** [comment]
> Do you want me to copy ec_curves over to the production database now, or should I wait?

Please wait since I'm testing the upload of more curves, and a copy will be needed after that anyway.

**Comment by JohnCremona** [comment]
> > Do you want me to copy ec_curves over to the production database now, or should I wait?
> 
> Please wait since I'm testing the upload of more curves, and a copy will be needed after that anyway.

OK, now would be a good time.  All curves to conductor 500k are now in.  I'm not sure that all the counts are properly on view though (see #3285 )

**Comment by AndrewVSutherland** [comment]
ec_curves has been copied over (I restarted the web servers on prodweb1 and prodweb2, as well as on grace, so the total count of curves is now displaying as 3,064,704, which I believe is correct.

But I think there is a data problem with the curves of conductor above 490k, if you search on curves of conductor 490000-495000, for example, you get a server error

http://beta.lmfdb.org/EllipticCurve/Q/?conductor=490000-495000&surj_quantifier=include

and if you scroll down to the bottom of the flasklog at

http://beta.lmfdb.org/flasklog

you can see that it is hitting an error trying to access lmfdb_iso

**Comment by JohnCremona** [comment]
I'll look into that.

**Comment by JohnCremona** [comment]
> I'll look into that.

Got it.  Two of my data files were missing the subrange 497000-497999 so curves in that range have some (4) missing lmfdb label columns and are also missing 2-adic data columns (4).

I'll report here when it is fixed.

**Comment by JohnCremona** [comment]
It should be fine now.  I deleted all curves with N>490000 and reloaded them from fixed data files.  It was only the range 497000-498000 affected  which makes your specific report puzzling.  The correct number of curves to 500000 is indeed 3064704, see http://johncremona.github.io/ecdata/table.html, and that is the response from db.ec_curves.count().

If I had run my own check_database_consistency() check after each upload I would have spotted this myself, sorry.  It checks OK for 490k-500k and I am now running on all 1-500k.

**Comment by AndrewVSutherland** [comment]
Let me know when your consistency check finishes and I will recopy the file.

**Comment by JohnCremona** [comment]
> Let me know when your consistency check finishes and I will recopy the file.

Ah!  It did finish (successfully) minutes after my last post, but I forgot to report.  Please recopy -thanks.

**Comment by JohnCremona** [comment]
I'm about to implement code changes to display the newly added optimality and Manin constant data, which will require the data copy before pushing to web: it would also be good to have http://www.lmfdb.org/EllipticCurve/Q/?conductor=497000-498000&surj_quantifier=include
not crashing for the workshop this week!  I know it is a holiday in the US today.

**Comment by AndrewVSutherland** [comment]
No problem -- is it safe to copy the data now, or should I wait?

**Comment by JohnCremona** [comment]
Thanks for asking -- hold on, I have to re-re-re-fix the data for class 990h....
I'll tell you when that is done.

**Comment by JohnCremona** [comment]
OK, 990h fixed manually: please copy.

**Comment by AndrewVSutherland** [comment]
Done!  The query 

 http://www.lmfdb.org/EllipticCurve/Q/?conductor=497000-498000&surj_quantifier=include

now works.

**Comment by JohnCremona** [comment]
Thanks a lot.  I have by now pushed the boundary between conductors below which I have determined the optimal curve unambiguously to 260000 and that will increase steadily; but I can handle that by changing the parameter OPTIMALITY_BOUND in the website code without needing to change the data frequently -- though of course I'll update the database at some point.

**Comment by JohnCremona** [comment]
While testing this PR I discovered an unrelated data glitch in the min_quad_twist column of the recently uploaded curves (N>400000), which has now been fixed with a rewrite.  Since this issue has been used for previous recent  requests to copy data from dev to web, I'll make a new such request here.  Thanks!

**Comment by AndrewVSutherland** [comment]
Done.

**Comment by JohnCremona** [comment]
> Done.

Thanks -- hopefully the last for a while!

**Comment by JohnCremona** [comment]
Update: optimality checking has now passed 300000 so the value of OPTIMALITY_BOUND on  line 17 of web_ec.py can be updated (it was 270000).

**Comment by JohnCremona** [comment]
Update: optimality checking has now passed 350000 so the value of OPTIMALITY_BOUND on line 17 of web_ec.py can be updated (it was 300000, though on prod it is still at 270000).

**Comment by JohnCremona** [comment]
Update: optimality checking has now passed 400000 so the value of OPTIMALITY_BOUND on line 17 of web_ec.py can be updated (it is now 300000).  I'll make a PR for this.
