### ISSUE TITLE
Data pull request number fields

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3187]
The data in nf_fields will be stable for a while and should be moved to the cloud.  It contains new fields, especially in higher degrees, and a column for the number of ramified primes.  Because of the latter, the data needs to go to the cloud before the code currently on beta does.

**Comment by AndrewVSutherland** [comment]
I will take care of this today

**Comment by AndrewVSutherland** [comment]
Done, and the number field stats on www.lmfdb.org and beta.lmfdb.org match, so I think we should be all good (but let me know if you spot anything amiss).
