### ISSUE TITLE
L-function of genus 2 curve link back to curve

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#320]
Friend link to underlying genus 2 curve is missing:

http://beta.lmfdb.org/L/Genus2Curve/Q/472/a/

**Comment by davidfarmer** [comment]
Unrelated math question: in the above link, why are so many of the local polynomials not irreducible?
Is that a coincidence, or some property of the curve?

**Comment by jvoight** [comment]
Hi David, I just added that the friend link is missing also to our newly created "Future plans" page, where there's a bunch of genus 2 work to do.  

I don't know that there are really an exceptional number of factors that are reducible in this case--if you go further out, it looks like there are plenty that are irreducible.  The Sato-Tate group is USp(4), so there is no geometric reason for any extra factorization, so this should be analogous to what happens in Galois theory where you take a polynomial and it happens that modulo the primes <= 100 there might be strange patterns (maybe an uncommonly large number of primes where the minimal polynomial splits completely into linear factors) but when you look modulo the primes <= 10^6 you see something more akin to the expected distribution.  

If you're still curious after this thread, we should sit down with Drew or Kiran and ask: given a genus 2 curve with trivial endomorphism ring (Sato-Tate group Sp(4)), for what proportion of primes should we expect the L-polynomial to factor?  I think the answer is 0% asymptotically, but that doesn't mean it will look like 0% until you go far out.

**Comment by JohnCremona** [comment]
http://beta.lmfdb.org/L/Genus2Curve/Q/472/a/ now gives an error!

**Comment by davidfarmer** [comment]
Probably my fault.  Looking into it.

**Comment by jwj61** [comment]
I think I can take care of it.  It can be handled in WebNumberField

**Comment by davidfarmer** [comment]
Fixed in pull request #386
(I has nothing to do with linking back to the curve)

**Comment by jvoight** [comment]
BTW, this shouldn't have as friend the genus 2 curve but rather its isogeny class.

**Comment by davidfarmer** [comment]
fixed
