### ISSUE TITLE
interesting function

### ISSUE THREAD

**Issue by maadim** [LMFDB/lmfdb#3203]
Someone could possibly look at this function: f(z)=(z^k)-(z/z^k) + (z^k)-(z/z^k) + …
The geometry of this function is really interesting to me.
Also this function:f(z)=(z^k)-i(z^k/z) + (z^k)-i(z^k/z) + …
Gives the same geometry.
When the function is in complex space, and K is greater than 2.
I would like to explore this function as a mathematician but I am not, so anything you can tell me will be accepted with joy. 
Thank you

**Comment by davidfarmer** [comment]
That function does not appear to be in the realm of the LMFDB.

You could try asking your question on  https://math.stackexchange.com/
