### ISSUE TITLE
Representations inconsistencies on the sidebar

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#3207]
We are inconsistent on how we show "Artin" on the sidebar in http://www.lmfdb.org vs http://beta.lmfdb.org.

<img width="406" alt="Screen Shot 2019-07-24 at 15 52 26" src="https://user-images.githubusercontent.com/322822/61804056-26d79480-ae2b-11e9-914f-6f80fe6d0081.png">

We can either upgrade `Galois:` or downgrade  `Characters:` to beta. 

On a related note, do we really want `Characters` as a link?

**Comment by davidlowryduda** [comment]
The view on beta looks better. But I suppose it looks silly to have the two lines
```
Characters:    Dirichlet
Galois:        Artin
```
So it seems most natural to me to remove `Characters:` on the main site.

And no, I don't think we want `Characters` as a link, in either beta or main.

**Comment by davidfarmer** [comment]
Could we have "Dirichlet characters" as the link?  Otherwise it will
be confusing to not apparently have Dirichlet characters and instead
have what appears to be Dirichlet representations.

**Comment by davidlowryduda** [comment]
@davidfarmer Yes, that makes a lot of sense.

**Comment by edgarcosta** [comment]
Agree!

**Comment by jwj61** [comment]
This is now on the main site
