### ISSUE TITLE
Artin representation pages

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#3228]
> Is the friendship relation symmetric (unlike real life)?

Searching for a weight 1 modular form corresponding to a given Artin representation is currently hard. The modular form (like http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/23/1/b/a/) has a link to the artin rep in related objects, but there is no reverse link from http://www.lmfdb.org/ArtinRepresentation/2.23.3t2.1c1 to the form, is this intended?

**Comment by edgarcosta** [comment]
The relationship is symmetric.

Looks like we need to push data for L-functions instances to prod, as this works:
- http://beta.lmfdb.org/ArtinRepresentation/2.23.3t2.1c1
- http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/23/1/b/a/

However, I should point out that this is somewhat wrong, as the `23.1.b.a` should point to the  (nonexistent) Galois orbit and not the 1st conjugacy class.

@alexjbest, Modulo my comment above, does beta look alright to you?

**Comment by edgarcosta** [comment]
The data has been updated, and now www.lmfdb.org behaves as beta
