### ISSUE TITLE
Expose fewer methods for tables

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#3262]
At the moment if the number of exposed methods for tables and the database is quite high.
We should go over the list and try to reduce many of those, as they are not meant for the regular user.
And perhaps some methods that are not exposed should be exposed.

**Comment by JohnCremona** [comment]
Does "exposed" just mean "not starting with an underscore"?
This seems sensible to me, so that someone like me has fewer things to look at.

**Comment by edgarcosta** [comment]
Exactly that!

**Comment by roed314** [comment]
Here are some possible things to put underscores in front of.

For db:
* `can_read_write_knowls`
* `can_read_write_userdb`
* `cursor`
* `fetch_userpassword`
* `grant_*` (maybe)
* `is_alive`
* `is_read_only`
* `is_verifying`
* `log_db_change`
* `logger`
* `register_object`

Note that the db namespace is cluttered with all the table names, so finding function names through tab completion is a bit annoying anyway.

For a table:
* `has_id`
* `log_db_change`
* `logger`

Were there others that you thought should be hidden?

**Comment by roed314** [comment]
Closing after recreating [here](https://github.com/roed314/psycodict/issues/25).
