### ISSUE TITLE
switch from pymongo to mongoengine

### ISSUE THREAD

**Issue by haraldschilly** [LMFDB/lmfdb#328]
After the quick and painless upgrade to pymongo 3, I think we should also switch to [mongoengine](http://mongoengine.org/) ... it has pymongo as a dependency, so nothing is lost, and we gain a few additional features to explore, in particular neat ORM mapping.

**Comment by JohnCremona** [comment]
I had to Google what ORM means...
I suggest that people first just replace pymongo with mongoengine in requirements.txt  (or test manually usuing pip install to install mongoengine) and check that everything still works, then we can investigate these mysterious other feautures!

**Comment by haraldschilly** [comment]
yes exactly :+1:

**Comment by JohnCremona** [comment]
I installed mongoengine on my local machine.  If I see no bad effects I will update requirements.txt as above.

**Comment by haraldschilly** [comment]
Before we do that, we have to figure out if we really have to use pymongo 2.8 ...  (which is right now fixed in requests.txt)

**Comment by JohnCremona** [comment]
I have (at last) taken a look at the mongoengine documentation.  Partly
this was prompted by the mini-tutorial which Fredrik and Stephan gave in
Warwick last week on the design principles behind their new classes for
classical newforms and modular form spaces, which do not use mongoengine
but are based on somewhat similar ideas.

It seems to me that we would gain a lot from making the switch, and though
it would be a lot of work, the process itself would be rewarding.  The end
result would see our code and data very much better organused than it is
now; queries and uploading of data much simpler and clearer, and more
uniform across data types;  much simpler for new contributors to get
started provided that they know python; and more.

This can be done incrementally, section by section, as when we moved to
using blueprints.  I look forward to trying it out with elliptic curves in
2016.

John

**Comment by edgarcosta** [comment]
Is it time to touch this subject again?

**Comment by JohnCremona** [comment]
Not right now.  Drew and I are formulating some new git guidelines for Release Managers and other developers, and have some more stuff to merge from last week.   Also I think that part of the afllout from last week will involve more work improving the user interface and that should take priority over refactoring.
One day we will though!

**Comment by fredstro** [comment]
I think it us a good idea to add it as a dependency already now. As we
won't remove pymongo no one is *forced* to refactor anything.
Adding it as a dependency wil simply make it easier to refactor later as
well as adding new stuff using mongoengine ODM structure rather continue to
reinvent new database structures all the time.

**Comment by JohnCremona** [comment]
@fredstro I assume that doing this (adding it to requirements.txt) will at first only affect new installations, and even then only if someone adds "import mongoengine" somewhere in committed code.

Perhaps we should add to the developers guide (under construction) instructions for updating some of these modules sometimes.  For example, many will still have pymongo 2.8 from when we forced that but now they should really do "sage -pip install pymongo --upgrade" (hope that's right) to get 3.2.

**Comment by fredstro** [comment]
yes, it should only affect new installations in that they will have the
mongoengine library installed and until someone commits something
containing 'import mongoengine' then it won't be used and so not have any
consequences at all.
It is probably a good idea to record which versions of various packages we
know are supported/required  and update requirements.txt accordingly.

**Comment by AndrewVSutherland** [comment]
I don't think this is something we should jump into until we understand the performance implications (which also depends on our choice of storage engine).  There are already several mongo db features that we do not or cannot use effectively because of performance limitations (e.g. queries on array fields).

My guess is that, as with the switch to WiredTiger/zlib, there will be advantages and disadvantages.  But unlike switching storage engines, once we start writing code that depends on mongoengine it will be hard to undo the decision to use it.
