### ISSUE TITLE
Add routing to enable admins to restart the beta webserver online

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#3285]
There are a number of caching issues that can prevent changed data from showing up (in statistics, for example, or if there's a schema change to a table).  Currently, only people with admin access to grace.mit.edu can restart the server.  We should consider adding the ability to do so for someone logged in as an admin.

@edgarcosta @JohnCremona @AndrewVSutherland

**Comment by JohnCremona** [comment]
+1

**Comment by edgarcosta** [comment]
https://github.com/LMFDB/lmfdb/blob/c50d477b97761d53f9eac00aa54d994e1ed0e10b/lmfdb/users/main.py#L323
