### ISSUE TITLE
Search number fields by subfield

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3306]
Add a search box for global number fields where the user can specify a subfield.

The plan is to rewrite the database so that subfields will be stored in two parallel arrays, the fields and their multiplicities.  Users can specify the subfield either by label or by polynomial.

**Comment by jwj61** [comment]
This is held up by what seems to be a problem with rewrite.

**Comment by JohnCremona** [comment]
Good to close -- do we wait until master has been nerged into prod?
