### ISSUE TITLE
AbVarFq Isogeny Classes - Galois Groups

### ISSUE THREAD

**Issue by tdupu** [LMFDB/lmfdb#3312]
In 3.9.b_ae_a it reads "Galois group is not in the database". 

There were a number of these where this message was displayed but in the associated number field link the galois group was displayed.

**Comment by AndrewVSutherland** [comment]
This appears to have been fixed, see [3.9.b_ae_a](https://www.lmfdb.org/Variety/Abelian/Fq/3/9/b_ae_a).
