### ISSUE TITLE
AbVarFq Isogeny Classes - Gaga box

### ISSUE THREAD

**Issue by tdupu** [LMFDB/lmfdb#3313]
-The angle rank picture was unclear to people
-ordinary/supersingular; simple not displayed

**Comment by roed314** [comment]
Can you elaborate?  I don't understand what you're suggesting to change here.

**Comment by AndrewVSutherland** [comment]
I think part of the request is to display the simple and ordinary attributes in the properties box (of course not ordinary does not imply supersingular).  The p-rank is already there, but it wouldn't hurt to also list ordinary true/false, and I certainly agree that the property box should say whether the variety is simple or not (this seems like the must fundamental invariant after dimension).

I'm not sure what is meant but the "angle rank" picture, but I assume this refers to the plot showing the roots of the Weil polynomial on the circle.  I'm not sure it makes sense to add anything to the properties box explaining this, but we could link the picture to a knowl (in fact the same issue "what does the picture mean" arises elsewhere, so this part of the issue isn't really about abvar per se and should perhaps be a separate issue).

**Comment by tdupu** [comment]
Drew is right. 

Also the way it is displayed it looks like p-rank has something to do with the picture. 

I guess this fits into a general discussion that was had regarding regarding images in the LMFDB, the lack of explanations for them, and where the most appropriate place to out this information is. 

Also, to clarify, all these posts came from the discussions during the September AIM workshop when we were showing a group of new users the database. David Farmer encourages us to post these comments.

**Comment by AndrewVSutherland** [comment]
It looks like ordinary is now in the properties box, but primitive and supersingular are not.  At a minimum I think primitive should be added.

I think the pictures are fine (whether we should be explaining the pictures in the properties boxes or not is a much broader issue that I don't think should be addressed as part of this one).

**Comment by roed314** [comment]
See #3957
