### ISSUE TITLE
Search error message cannot have html in it

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3314]
If you go to global number fields and search for Galois group 2c2, e.g.,

  http://www.lmfdb.org/NumberField/?galois_group=2c2&ram_quantifier=exactly

you get a search error (which is the right thing to do), and it tries to give a link for the Galois group nicknames (also a good thing to do), but somewhere this has been processed so that you see raw html.  I tried putting | safe in the right place, but that did not help, so it seems the processing is taking place somewhere else.  Maybe it is sanitizing the message in case the user tried to put a link in their label, but then the it should only sanitize that part of the message.

**Comment by edgarcosta** [comment]
This is being raised by the SearchParser in 
```
        except (ValueError, AttributeError, TypeError) as err:
            flash_error("<span style='color:black'>%s</span> is not a valid input for <span style='color:black'>%s</span>. %s", inp, name, str(err))
            info['err'] = ''
            raise
```
which is triggered by the `parse_galgrp`.

one could argue that one shouldn't escape the error string, but many of the exceptions raised the search parser functions include user input, and thus why we escape it.

**Comment by jwj61** [comment]
Right, and what I am saying is that we should only escape the user input and not the rest.

**Comment by edgarcosta** [comment]
But do you agree that doing:
```
flash_error("<span style='color:black'>%s</span> is not a valid input for <span style='color:black'>%s</span>." + str(err), inp, name)
```
might get us in trouble if we include the input from the user?
And it is hard to check all the possible errors to be sure that we never add the input from the user.

One possibility, is to modify `parse_galgrp` to not use the decorator `@search_parser`.

**Comment by jwj61** [comment]
I agree.  As I said above, we should escape the part which is user input, but not the rest.  Sorting that out depends on where the escaping occurs.  I could not figure that out, but it sounds like it comes from a decorator.

**Comment by jwj61** [comment]
I think I see a way to do this.  In SearchParser we may end up calling flash_error with a string plus arguments.  The arguments get escaped.  They are the user input, the name of the field, and an error message.  By doing formatted string substitution before sending something to flash_error (and then having fewer optional arguments), we can control what gets escaped.

Option 1: make it a rule that the error message called err in that function never contain user input.  This is almost always true.

Option 2: add an optional argument called errors_are_safe to be True if we don't need to escape the error raised by a function.  It could be false by default so generally no change, but the galois group name parser is safe and could set it to true.

I would just do option 2, but I am unsure of where/how to add this extra option for SearchParser.

**Comment by AndrewVSutherland** [comment]
It looks like there is now a knowl, but there is html in the knowl that is not being rendered.

**Comment by AndrewVSutherland** [comment]
Fixed (the knowl needed a safe in it that was present in the beta version but had not been reviewed).
