### ISSUE TITLE
Full BSD invariants for genus 2 curves

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#3315]
The section on "Invariants" is similar but not identical to the BSD invariants for elliptic curves. In particular, we do not currently have the determinant of the small period lattice; I gather this is easy to compute.

We should also describe these as "BSD invariants" and have a knowl about BSD for abelian varieties.

**Comment by AndrewVSutherland** [comment]
This is actually in the works (I discussed this with Raymond van Bommel earlier this week -- we want to do this for genus 3 curves as well).

**Comment by AndrewVSutherland** [comment]
All of the <a href="https://www.lmfdb.org/knowledge/show/g2c.bsd_invariants">genus 2 BSD invariants</a> we plan to compute are now available; this includes all the <a href="https://www.lmfdb.org/knowledge/show/ec.q.bsdconjecture">elliptic curve BSD invariants</a> currently shown (in genus 2 the Mordell Weil rank is not rigorously computed in a handful of cases).
