### ISSUE TITLE
Data upload

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3318]
Please copy artin_reps and artin_field_data to the cloud.  The precomputation of determinant representations is complete.

While you are at it, the tables artin_reps_new and artin_field_data_new can be deleted from the cloud.  They are no longer referenced by the code (this has been true for a few weeks).

Also, please copy gps_transitive to the cloud.  This has a new field for nilpotency class which has been filled in, and there will soon be a code pull request which makes use of it.

**Comment by AndrewVSutherland** [comment]
On it.

**Comment by AndrewVSutherland** [comment]
Done, can you take a look just to be sure all is well?

**Comment by jwj61** [comment]
Looks ok
