### ISSUE TITLE
Knowls incompatible with MathJax3?

### ISSUE THREAD

**Issue by tanjz12** [LMFDB/lmfdb#3324]
When I use MathJax3 and knowls on the same page, the knowls would have a border and no content.

- Example with MathJax3 and knowl not working: http://pi.math.cornell.edu/~tanjz/1105/fa19/test.html
- The monic.html page is not blank: http://pi.math.cornell.edu/~tanjz/1105/fa19/monic.html
- This page using KaTeX is working: http://pi.math.cornell.edu/~tanjz/1105/fa19/ipsum.html

(the ipsum page has `<p>` tags properly wrapping paragraphs but the knowl appeared at the wrong place. I'll submit a separate issue for that)

**Comment by davidfarmer** [comment]
Not and LMFDB issue, so closing.
