### ISSUE TITLE
Knowl not showing up at the correct place

### ISSUE THREAD

**Issue by tanjz12** [LMFDB/lmfdb#3329]
Trying to implement knowl here: http://pi.math.cornell.edu/~tanjz/1105/fa19/ipsum.html
But it is not after the correct parent p tag.

**Comment by alexjbest** [comment]
I'm not sure what the official place is for support with knows, but @davidfarmer can probably help?

**Comment by davidfarmer** [comment]
I will look into this.  This is not an LMFDB issue, so I am closing.

**Comment by davidfarmer** [comment]
This line in the  source
`      else if ($el.parent().parent().is("li")) {`
can be modified by removing one of the `.parent()`s.
That probably addresses this issue.
