### ISSUE TITLE
Typo on Completeness of Riemann Zeta Zero Data page

### ISSUE THREAD

**Issue by complexzeta** [LMFDB/lmfdb#3331]
On the page http://www.lmfdb.org/zeros/zeta/Completeness, "Riemann" is misspelled as "Reimann" in the title, and there is an extra $ at the end of the title.

**Comment by cscmnu** [comment]
Its a knowl, correct on beta, not on full page

**Comment by edgarcosta** [comment]
@cscmnu, did you end up taking care of this?

**Comment by cscmnu** [comment]
@edgarcosta Yes this is closed now and is #3402
