### ISSUE TITLE
Refine search page input box hints

### ISSUE THREAD

**Issue by grundman7** [LMFDB/lmfdb#3333]
When on a secondary search page, there are no longer the hints for what form the input should be in, as there is on the primary search page.  I'm guessing that you don't want to take the space for the links, perhaps having an easy link back to the page with the hints would help?   Multiple times I got stuck, before I realized that I needed to go back to get the input hints when I needed to refine a search.

**Comment by AndrewVSutherland** [comment]
On some of the refine search pages (e.g.http://www.lmfdb.org/Genus2Curve/Q/?all=1) the gray example text is still present in the input boxes (even though the "e.g. ...." text to the right is not for reasons of spaces), but on other refine search pages (e.g. http://www.lmfdb.org/EllipticCurve/Q/?surj_quantifier=include) it is not.

I think all the refine search pages should have lightly-shaded example text present in the input boxes.

**Comment by rbommel** [comment]
@edgarcosta Will this problem be solved by your new search box implementation?

**Comment by edgarcosta** [comment]
I think so, see:
https://scratch.lmfdb.xyz/Variety/Abelian/Fq/?search_type=List
https://scratch.lmfdb.xyz/Genus2Curve/Q/?search_type=List&all=1

If you agree, we should create a new issue, asking for the search box implementation

**Comment by AndrewVSutherland** [comment]
This has been done.
