### ISSUE TITLE
Inconsistencies in torsion subgroup notation

### ISSUE THREAD

**Issue by TylerGenao** [LMFDB/lmfdb#3337]
For an elliptic curve E/K, its torsion subgroup seems to be written three (really two) different ways: E(K) _tors, E(K) _tor, and E(K) _{tor, italicized}. For examples: both the 'torsion order of an elliptic curve' knowl and the 'torsion growth in number fields' knowl use E(K) _tors; the 'torsion subgroup of an elliptic curve' knowl uses E(K) _tor; and the 'rank of an elliptic curve over a number field' knowl uses E(K) _{tor, italicized}.

**Comment by vishalarul** [comment]
I searched for all instances of the word "torsion" among the knowls and manually found which of those involve the torsion subgroup of an elliptic curve. These were:

ec.q.torsion_growth
ec.torsion_order
ec.torsion_subgroup
ec.rank
ec.q.bsdconjecture
ec.q.bsd_invariants

For each of these, I changed the notation (if necessary) for the torsion subgroup of E(K) to E(K)_tor.

**Comment by davidfarmer** [comment]
The markup

$E(\Q)_{\rm tor}$

may look right, but that is not considered to be the correct
way to have roman text in math mode.

See

https://tex.stackexchange.com/questions/58098/what-are-all-the-font-styles-i-can-use-in-math-mode

or

https://www.overleaf.com/learn/latex/Mathematical_fonts
