### ISSUE TITLE
Table headers of search results should be knowls

### ISSUE THREAD

**Issue by grundman7** [LMFDB/lmfdb#3338]
After a search in global number fields, a table is returned.  The header "Label" on the first column of the table is not a knowl.  So I don't see a way to easily get a reminder as to what the parts of the field label mean, without leaving the page.  (I did fine a reference for it on the right-hand side bar, but it takes me to another page, rather than being a knowl.  And, in any case, it would be easier to find if the column header was a knowl.)  

Example of search return: http://www.lmfdb.org/NumberField/?ram_quantifier=exactly

Example of different part of lmfdb where a search yields a table with knowl headings: http://www.lmfdb.org/EllipticCurve/Q/?surj_quantifier=include

EDIT: the issue for global number fields has been addressed, but the exact same issue is sill present on the following search result pages:

https://www.lmfdb.org/ModularForm/GL2/TotallyReal/?all=1
(Label column header should link to the knowl mf.hilbert.label)

https://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/?all=1
(Label column header should link to the knowl mf.bianchi.labels and the Field column header should link to the knowl nf, as it does on the HMF search results page)

(the individual field labels in the Field columns on both pages should link to number field home pages, but this is a separate issue, see #3534)

There is a similar issue for the Polynomial column on the local fields search results page:
https://www.lmfdb.org/LocalNumberField/?all=1
(Polynomial column header should link to the knowl lf.defining_polynomial)

**Comment by edgarcosta** [comment]
@grundman7 Thanks!

Here is a good example to follow: http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/?search_type=List&all=1

**Comment by AndrewVSutherland** [comment]
Resolved by #3340.

**Comment by edgarcosta** [comment]
@AndrewVSutherland, #3340 resolved this for number fields, but not the BMF, HMF and local field.

**Comment by AndrewVSutherland** [comment]
@edgarcosta Other than the labels you added, there is nothing in the description of the issue or the comments that makes this clear.  If you are going to mark an issue as a good first issue it should be blindingly obvious exactly what needs to be done, and in general, if you don't think an issue is ready to be closed you should edit the description to make this clear (as I have just done).  Any issue for which the problem described in its description has been resolved is fair game for closing.

**Comment by edgarcosta** [comment]
@AndrewVSutherland, I agree with you. I should have also commented instead of just adding labels.

I still think we should that local fields should have the knowl 
[lf.defining_polynomial](https://www.lmfdb.org/knowledge/show/lf.defining_polynomial) for `polynomial`, see
https://www.lmfdb.org/LocalNumberField/?all=1

**Comment by AndrewVSutherland** [comment]
@edgarcosta Agreed, I just added it to the description.  If your "definition of done" for this issue includes checking all column headers on all search results pages, you should put that in the description as well and indicate the scope (if you are including beta there are a lot more cases, e.g. none of the column headers in the HGM motives and families search results pages currently have knowl links).

**Comment by edgarcosta** [comment]
The only header left without a knowl is $p$ in https://www.lmfdb.org/LocalNumberField/?all=1
Should it have a knowl? This might be the exception to the rule.
If so, we should close this issue, as @apeng16 took care of all the things we listed in #3665, #3668, and #3670

**Comment by jwj61** [comment]
One can use lf.qp
