### ISSUE TITLE
Galois group label(s) 

### ISSUE THREAD

**Issue by grundman7** [LMFDB/lmfdb#3339]
On http://www.lmfdb.org/NumberField/, I can click on either "Galois group labels" on the RHS or on "group labels" by the search box to get a terrific list of the codes for the different groups, translated to names I'm more used to.  This is good!

On http://www.lmfdb.org/GaloisGroup/, I can click on either "Galois group label" at the search box or "Galois group labels" on the RHS, but each just tells me the form of the label.  I can't find any place on this page that does the translations for me in general.

**Comment by jwj61** [comment]
Galois groups have labels (which are all nTt), and then there are nicknames for abstract groups which will typically correspond to several Galois groups (i.e., there are several faithful transitive permutation representations).  Currently, there is no way to search for abstract groups by a nickname.  So a rephrasing of the feature would be to be able to search by nickname, in which case it would make sense to add the knowl with nicknames.

**Comment by jwj61** [comment]
This was done a while ago.
