### ISSUE TITLE
Searching number fields by Galois group and signature simultaneously returns a server error.

### ISSUE THREAD

**Issue by alisonbethmiller** [LMFDB/lmfdb#3341]
I tried to search for S3 cubic fields of signature [1, 1] with the query:

http://www.lmfdb.org/NumberField/?signature=%5B1%2C+1%5D&galois_group=S3

and it returns a server error.

**Comment by jwj61** [comment]
The error is in _split_ors in the search parser.

**Comment by jwj61** [comment]
Looking more, the choice of Galois group produces an or of two pairs of (degree, t-number).  The signature restriction forces the degree, and it claims there is an error when it hits the conflicting combination.  Really, it should not raise an error and accept that branch of the or should be dropped.

**Comment by AndrewVSutherland** [comment]
This is still broken, do you have any thoughts on this @roed314 or @edgarcosta

**Comment by edgarcosta** [comment]
We will take care of it on Friday

**Comment by AndrewVSutherland** [comment]
Fix is now on beta, and will be pushed to web shortly, closing.
