### ISSUE TITLE
Weil Polynomials Knowl, L-Polynomials Display

### ISSUE THREAD

**Issue by tdupu** [LMFDB/lmfdb#3342]
The L-polynomials and Weil polynomials are getting mixed up:
    http://www.lmfdb.org/Variety/Abelian/Fq/2/4/ae_j
The objects that are displayed are for det(1-tF) and the knowls are for det(t-F). Also, it *is* the case that the Weil polynomials are the det(t-F) ones since Weil q-numbers need to be roots of Weil polynomials. 

We should either change the knowls or change the way the data is displayed. Also, I think the information in the database is agnostic about which is displayed since it only outputs an array with the first half of the coefficients which can be interpreted as weil polynomial coefficients or L-polynomial coefficients.

**Comment by edgarcosta** [comment]
I prefer to keep displaying det(1-t Frob).

**Comment by AndrewVSutherland** [comment]
I agree that we should continue to display det(1 - t Frob), since this is what we display elsewhere in the LMFDB, but it would perhaps make more sense to change the caption to L:polynomial and give it its own knowl with a link to the Weil polynomial knowl (and explain that the two are reciprocal).

Alternatively, we could let the user toggle between the two, as we do with Igusa-Clebsch/Igusa/G2 invariants of genus 2 curves, and make L-polynomial the default.

**Comment by kedlaya** [comment]
+1 for having an option to toggle.

**Comment by edgarcosta** [comment]
The (unreviewed) knowls on Beta already recursively mention each other.
What about in the search results? 

Somewhat related to this issue, we should display the polynomials expanded, at least in the abvar page.

**Comment by kedlaya** [comment]
+1 for expanding the polynomials in addition to showing the factorization.

And since I didn't this earlier, if we do have a toggle for L-polynomials vs Weil polynomials, I agree with keeping the L-polynomial as the default.

**Comment by AndrewVSutherland** [comment]
I would keep the search results as they are (L-polynomials) but change the header from Weil Polynomial to L-Polynomial.

**Comment by tdupu** [comment]
Another, minor thing. On the page they are x's but in the knowl they are t's. In the manuscript we landed on T's. 

Best,
Taylor

**Comment by edgarcosta** [comment]
I also prefer t's, but don't have strong opinions.

We have detoured a bit of the initial issue. Here is my attempt to summarize things left to do to close this item:

- fix notation Weil vs L-function: specifically, go through the knowls and fix references from Weil to L-function when appropriate, e.g., https://beta.lmfdb.org/knowledge/show/av.fq.initial_coefficients
- Expand polynomial in the home page and perhaps in the search results
- (optional) toggle between L-polynomial and Weil in home page and search results
- (optional) if we do the above item, we should also have the option to display the polynomial expanded.

**Comment by davidfarmer** [comment]
Should the top line in the table of local factors on an L-funciton
home page, such as this one:

https://www.lmfdb.org/L/ModularForm/GL2/Q/holomorphic/7/3/b/a/

be F_p(T) instead of F_p ?

I understand that in differernt locations we use x, t, and T as
the variable in the polynomial.  That is okay, and in fact important
if different areas have different traditions.  But then we need to
make it clear which variable are bound.

**Comment by AndrewVSutherland** [comment]
@davidfarmer I think it should be F_p(T), especially since F_p(p^{-s}) appears just a few lines above.

**Comment by kedlaya** [comment]
Regarding:
>     * fix notation Weil vs L-function: specifically, go through the knowls and fix references from Weil to L-function when appropriate, e.g., https://beta.lmfdb.org/knowledge/show/av.fq.initial_coefficients

I fixed this one, but do you have a more complete list of instances that need to be changed?

Also, this might be a good time for me to reconfirm that in the LMFDB, we do not put the capital L in math mode in the term "L-function", so we should do likewise for "L-polynomial".

**Comment by AndrewVSutherland** [comment]
@kedlaya Yes, in knowl text on the LMFDB we use L-function and L-polynomial with the L not in math mode (and not italicized), see https://www.lmfdb.org/knowledge/show/g2c.lfunction for example.

@edgarcosta @davidfarmer I think on https://www.lmfdb.org/L/ModularForm/GL2/Q/holomorphic/7/3/b/a/ it would make more sense to use L_p(T) rather than F_p (especially since we are displaying the L-polynomial, not the charpoly of Frobenius).

**Comment by davidfarmer** [comment]
If something were called L_p, presumably that would be the reciprocal of what is
currently called F_p .  That is, L_p would be the actual local factor and not its reciprocal
and we would have

L(s) = \prod_p L_p(p^{-s}) .

If we rename F_p to L_p then L would be the product of the reciprocals of the L_p's,
which would be confusing.  I think it would also be confusing for the header on the
table to be   L_p(T)^{-1} .

So, I suggest it is not helpful to rename the F_p on the L-function home pages.

**Comment by AndrewVSutherland** [comment]
@davidfarmer It is not uncommon in the literature to see L(s) = \prod_p L_p(p^-s)^(-1), especially in the context of L-functions of abelian varieties where L_p(T) is often used to denote the numerator of the zeta function of the reduction mod p (whence the term L-polynomial).

See, for example, the wikipedia page tor the Hasse-Weil zeta function: https://en.wikipedia.org/wiki/Hasse%E2%80%93Weil_zeta_function.

I agree that one also sees L(s) = \prod_p L_p(p^-s), but I don't think this is universal. If we made the change I propose the line immediately above the table would say

Euler Product: L(s) = prod L_p(p^-s)^(-1)

so I don't think there is any risk of confusion, and it would be consistent with our usage of the term L-polynomial in the AV/FF pages.

**Comment by davidfarmer** [comment]
From the representation theory perspective, the local factor is
L_p(p^{-s}), not L_p(p^{-s})^{-1} .  I accept that some areas
have the opposite convention from representation theory, but I suggest
that rep thy should be the convention to follow on the L-function home
pages.

**Comment by AndrewVSutherland** [comment]
@davidfarmer OK, let's just change F_p to F_p(T).

**Comment by AndrewVSutherland** [comment]
Can we close this?

**Comment by AndrewVSutherland** [comment]
Closing this issue to complete milestone 1.1.1.  If there are still changes related to this that people want to make, please create a new issue for it, I think we have completely addressed the problem that was originally raised.
