### ISSUE TITLE
Tamagawa number might be wrong

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3346]
From the feedback page:

On http://www.lmfdb.org/Genus2Curve/Q/529/a/529/1 the Tamagawa number at 23 of J_0(23) is 11, not 1, according to Magma, which also confirms this via LRatio(JZero(23),1) = 1/11 = c_23/#J(\Q)_tors².

Reply to Timo.Keller@uni-bayreuth.de

**Comment by AndrewVSutherland** [comment]
I've asked Raymond van Bommel who computed the genus 2 Tamagawa numbers to take a look at this.

**Comment by AndrewVSutherland** [comment]
Raymond has confirmed that the tamagawa number for this curve is correct.  The key point is that this curve is not X_0(23), and its Jacobian is only isogenous to J_0(23), not isomorphic to it.  The real period for the Jacobian this curve is smaller than that of X_0(23) by a factor of 11, which explains the difference in Tamagaw numbers.  I will email Timo.
