### ISSUE TITLE
EC/Q isogeny class modular form "None"

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#3347]
At http://beta.lmfdb.org/EllipticCurve/Q/495006m/ a section heading read "Modular form None" when it should show a label (but no lonk since this modular form is not in the database.  It's OK on individual curve pages e.g. http://beta.lmfdb.org/EllipticCurve/Q/495006m1/ correctly shows Modular Form 495006.2.a.m.

It's not just an issue for newly added curves, e.g. http://beta.lmfdb.org/EllipticCurve/Q/24460/a/ is the same.

Relevant code is around line 104 in elliptic_curves/isog_class.py where self.newform_label is clearly None, but the flag newform_exists_in_db is getting True, so we see None instead of a label.

**Comment by assaferan** [comment]
I will be solving this

**Comment by assaferan** [comment]
Resolved in pull request #3405
