### ISSUE TITLE
Interesting genus 2 curves

### ISSUE THREAD

**Issue by TylerGenao** [LMFDB/lmfdb#3350]
On the page for genus 2 curves over Q, it would be nice to have short descriptions of the interesting examples instead of just their labels, similar to what the interesting examples of elliptic curves over number fields have.

**Comment by edgarcosta** [comment]
See also #3332 for a discussion regarding style of interesting examples.

**Comment by AndrewVSutherland** [comment]
This was addressed in release 1.2
