### ISSUE TITLE
View more for dirichlet characters of given modulus

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#3358]
Looking at the page for dirichlet characters of a given conductor like: http://lmfdb.xyz/Character/Dirichlet/3329/ only a few characters are displayed for space reasons. In addition there should have a link to view more if someone needs a different character not in those 30, this could just be to the the search page for conductor 3329, or some other way of getting at the 3000 characters not displayed at the end of the page.

**Comment by edgarcosta** [comment]
ps: Depending on how to address this, it might end up to not being such a "good first issue".

**Comment by AndrewVSutherland** [comment]
I think a link to a search is the right way to deal with this.

**Comment by AndrewVSutherland** [comment]
We should add a group knowl to this page as well.

**Comment by BarinderBanwait** [comment]
working on this, can't assign myself
