### ISSUE TITLE
FHGCWA -- for non-specialists

### ISSUE THREAD

**Issue by grundman7** [LMFDB/lmfdb#3361]
Not knowing what this page is really about, I expected to browse families, but instead I am browsing automorphisms.   Either something in the naming here should change or a knowl should be added that explains to novices why the section is called one thing but the objects we're looking at are called something else.

With luck this is clear.  I've tried to express why I think this page is confusing for non-specialists. http://www.lmfdb.org/HigherGenus/C/Aut/

**Comment by jenpaulhus** [comment]
Thanks for the suggestion.  I'll work on some clarifications for this page.

**Comment by AndrewVSutherland** [comment]
@jenpaulhus Has this been done or do you have any specific plans to address this?  It seems like an issue we should be able to either address or close for 1.1.2

**Comment by jenpaulhus** [comment]
Honestly, I think this is an issue that will take some time to think about (or at least my interpretation of the PR which is likely broader than what Helen was thinking).  At some point it will be worth thinking about how the higher genus pages are structured and represented, including renaming of some things and more explanation.  I think at some point the higher genus pages could use a sprucing up, including re-running the data from scratch using the soon to be added groups database.  That is likely a summer project for me (or at best a next January project).   I don't know if that should mean closing this ticket now. But I'd really rather not make a couple of cosmetic name changes right now (or haphazardly editing a knowl or two) just to make the v1.1.2 deadline. I would instead like to have a more deliberative conversations (ideally with other people besides me too!) about how to make these pages work best and how best to name objects which are called different names by researchers in different areas.

Even less related to what Helen said, I have WAY more data (or the potential to create that data) than I've put into the database.  Definitely up to genus 48,  and beyond that is possible.  But I want to make sure everything works well up to genus 15 (and get the small groups database in lmfdb so I can connect my groups with that database) before I proceed to add more genera.

**Comment by AndrewVSutherland** [comment]
@jenpaulhus No problem, I'll remove the 1.1.2 milestone.

**Comment by roed314** [comment]
I'm putting this in 1.4, but @jenpaulhus feel free to change it.

**Comment by jenpaulhus** [comment]
Closing this as it is subsumed in a new issue I made: #6264 .  We can think about how to describe these pages during the overhaul.
