### ISSUE TITLE
IsoClassesAbVar Table

### ISSUE THREAD

**Issue by grundman7** [LMFDB/lmfdb#3362]
Two items:

1. Is the "Browse" section of this page really the best place to have the table?

2. The option of changing the range of the Dimension variable of the table does nothing (I'm guessing because we don't have the data).  It's likely to make someone with limited understanding think that their lack of knowledge is why the table doesn't change.

The combination of these two items make the whole Browse section of this page unwelcoming to a novice.

**Comment by roed314** [comment]
This will be addressed by #3430
