### ISSUE TITLE
Maass form searches

### ISSUE THREAD

**Issue by jenpaulhus** [LMFDB/lmfdb#3372]
When I go to the Maass form page to search,
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/

the page tells me that I can enter "1" to represent the trivial character, but when I try to search with a 1 in that box, I get an error message "Error: 1 is not a valid label for a Dirichlet character. It should be of the form q.n, where q and n are coprime positive integers with n < q, or q=n=1."

and in addition, I am now on a page with no breadcrumbs and just the words LMFDB at the top.

Also, the search page for Maass forms doesn't allow for refinement of searches.

**Comment by AndrewVSutherland** [comment]
Addressed by #3372.
