### ISSUE TITLE
Confusing L-function link

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#3383]
When I look at an embedded newform, such as
http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/59/2/a/a/1/5/
I see two L-functions friends links.

The link to 
http://www.lmfdb.org/L/ModularForm/GL2/Q/holomorphic/59/2/a/a/1/5/
makes perfect sense, since that is "the" L-function associated
to that newform:  it is the Dirichlet series which has the same
coefficients as the Fourier coefficients of the newform.

But higher up in the friends box there is another L-function.
It is non-primitive and in this case it has degree 10.

There may be an argument for including that as a friend
(as an L-function person that link does not make much sense to
me, since "the" L-function of this modular form is just one factor
of that non-primitive L-function.  But I accept that other people
may have legitimate reasons for wanting to include it.)

If we don't remove that non-primitive link, we at least need to
put it below the link to the primitive friend.

One additional thing that would satisfy me is to give a name to
the "product of all the Galois conjugates" non-primitive
L-function, and have that be the link.  That is, the link would
be "Galois stable L-function", except that I am not proposing that
as the official name.

Some rearrangement of those links might help.
Any ambiguity would be cleared up by using the order:

The primitive L-function
The Sato-Tate group
The newform
The newform's L-function

That could avoid the need to name the product-of-conjugates
L-function.

And the two newspace links could either be before the 4 links
above, or after the 4 links above.  (Presumably before, since
spaces are more important than objects?)

**Comment by AndrewVSutherland** [comment]
I agree that we should remove the link to the imprimitive L-function, which really isn't any of the embedded newform's business.  It makes sense for the embedded newform to know about its own Galois orbit, but not the Galois orbits of all its friends (which may include an an artin rep, see
https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/124/1/i/a/67/1/, for example).

PR #3528 adds imprimitive L-function links to the Artin rep Galois orbit pages when available, but it does not put imprimitive L-functions links on the individual Artin rep pages, and to be consistent we should not be putting imprimivite L-function links on the embedded CMF pages.

If at some point we decide that primitive arithmetic L-functions should have a link to the Galois stable L-function obtained by taking the product of the conjugates, that should go on the primitive L-function page, but there is no reason to put it on the page of every origin of the primitive L-function.

**Comment by AndrewVSutherland** [comment]
Resolved by #3529
