### ISSUE TITLE
Typo in definition of Manin constant

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3387]
From the feedback page in reference to http://www.lmfdb.org/EllipticCurve/Q/36a3/ 

This is about the pop-up description of what the "Manin constant" is. Namely, in the last display of that pop-up one should have "\omega_{E'}", not "\omega'_E" on the left hand side of the equation.

Please reply to kestutis@math.u-psud.fr

**Comment by edgarcosta** [comment]
I have fixed the typo in the knowl. Should be viewable in www.lmfdb.org in about 10 min

**Comment by edgarcosta** [comment]
I have emailed him
