### ISSUE TITLE
Data pull request for number fields

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3394]
Please upload nf_fields to the cloud.  It contains additional columns which will be used by pull requests coming soon.  No columns have been removed, so it should be a safe change.

**Comment by AndrewVSutherland** [comment]
In process now...

**Comment by AndrewVSutherland** [comment]
Done, can you please take a look and make sure everything is as expected?

**Comment by jwj61** [comment]
Looks fine.
