### ISSUE TITLE
Missing Artin Representation

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#341]
One of the unit tests for Artin Representations fails:
    /ArtinRepresentation/?dimension=3&conductor=1988-2015&group=&ramified=&unramified=&root_number=&frobenius_schur_indicator=&count=15
since the expected object of conductor 2009 is not found.  Either it has been deleted from the database, or the search code is faulty.

**Comment by jwj61** [comment]
Was fixed
