### ISSUE TITLE
Repeated search yields fewer results for Sato-Tate

### ISSUE THREAD

**Issue by rbommel** [LMFDB/lmfdb#3412]
When searching for Sato-Tate groups, the search counts drops by 2 every time you search. To reproduce this, start at http://beta.lmfdb.org/SatoTateGroup/?rational_only=yes&count=25 and click on 'Search again'.

**Comment by AndrewVSutherland** [comment]
It is also not displaying all the results it should (21 of 57 on the first search).  And the default count should be 50 not 25.

**Comment by AndrewVSutherland** [comment]
I'm looking at this now
