### ISSUE TITLE
Searching with n-dash gives unspecified error

### ISSUE THREAD

**Issue by rbommel** [LMFDB/lmfdb#3413]
When you search and enter an n-dash instead of a minus, then the search page gives you an error, but does not tell you what you did wrong. See for example: http://beta.lmfdb.org/Genus2Curve/Q/?geometric_invariants_type=igusa_clebsch_inv&geometric_invariants=%5B%E2%80%931%5D&bad_quantifier=include

**Comment by edgarcosta** [comment]
The culprit of the issue is that no parsing is being done on the expected list of rationals, e.g.,
http://beta.lmfdb.org/Genus2Curve/Q/?geometric_invariants_type=igusa_clebsch_inv&geometric_invariants=adada
