### ISSUE TITLE
CMF coefficient field not explained/displayed

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#3422]
The form
  http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/34/4/b/a/
says its coefficients are written in terms of i = sqrt(-1), but in fact they are written in terms of beta which is not defined.  Reported by Xenia de la Ossa.

**Comment by roed314** [comment]
In fact, beta = -2i in this case.  I assume we still want to write the q-expansion in terms of beta and just make sure that we correctly explain what it is?

**Comment by jvoight** [comment]
I suppose there are arguments both for writing the coefficients in terms of i (since that's immediately recognizable) and in terms of beta = -2*i (because that apparently generates the coefficient ring).  Chef's choice, as long as we actually define the symbols we are using.

**Comment by AndrewVSutherland** [comment]
Given that the short q-expansion listed in the search results uses i (see http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/34/4/b/ for example), we should use i on the page for the form. (the chef(s) already made their choice: the latex for the short q-expansion in the search results is stored in the database and I can remember discussing precisely this situation at the time I wrote the code to generate the latex).

**Comment by assaferan** [comment]
Hi, I would like to take on that one.
Just making sure - what we want is:
"If the number field is Q[i] then write the q-expansion in terms of i"
right?

**Comment by AndrewVSutherland** [comment]
The rule is "if the integer attribute "field_poly_root_of_unity" in the mf_newforms record has nonzero integer value n then write the q-expansion in terms of zeta_n, except when n=4 in which case use i".

You can see that this rule applies to the webpage in question, the corresponding mf_newforms record can be viewed at

    https://www.lmfdb.org/api/mf_newforms/?label=34.4.b.a

field_poly_root_of_unity will be nonzero only when the boolean field_poly_is_cyclotomic is set (in which case the defining polynomial of the field is a cyclotomic polynomial), but the code can/should just look at field_poly_root_of_unit (and I thought it actually already did this, so something weird might be happening).  Thanks for volunteering to take care of this!

**Comment by assaferan** [comment]
Resolved in pull request #3527. Currently resolution converts the coefficients after reading from the database, on initialization of the webform.

**Comment by rbommel** [comment]
From the discussion I seem to get that this issue should be solved, but somehow it has still be marked as v1.2 on 28 January. Is there anything that still needs to be done?

**Comment by AndrewVSutherland** [comment]
LGTM
