### ISSUE TITLE
conrey-Dirichlet-characters is causing tests to fail

### ISSUE THREAD

**Issue by davidlowryduda** [LMFDB/lmfdb#3441]
Johnathan Bober recently accepted a pull request to update the code in his [conrey-dirichlet-character](https://github.com/jwbober/conrey-dirichlet-characters) repository that allows it to work for both python2-sage and python3-sage --- but it has a small bug. (I'm partly responsible, since I looked over the code and tested it a bit and didn't notice the bug).

Travis freshly installs this repository with each test, and this is causing the recent test errors. I've [opened a pull request](https://github.com/jwbober/conrey-dirichlet-characters/pull/5) on his repository with a fix.

With this fix, [the test suite passes](https://travis-ci.com/davidlowryduda/lmfdb/builds/134630632). Note that to have travis run this, I replaced the conrey-dirichlet-character line in requirements.txt with `git+https://github.com/davidlowryduda/conrey-dirichlet-characters.git` (and otherwise have travis running on my repo).

**Comment by JohnCremona** [comment]
The PR to  conrey-dirichlet-character has just been merged.

**Comment by davidlowryduda** [comment]
Thanks John!

**Comment by slel** [comment]
Probably unrelated but does someone know how to fix

- https://github.com/jwbober/conrey-dirichlet-characters/issues/6

which is about a warning one gets when running the following?
```
sage --pip install -r lmfdb/requirements.txt
```
