### ISSUE TITLE
Label problems for Artin representations

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3452]
There are a variety of changes being considered for labels of Artin representations.  Here is what is going on, and an opportunity to give feedback.

Part of the label is the smallest containing permutation representation (smallest (n,t) lexicographically such that the rep'n is a summand of nTt).  The code was not computing this correctly (not always minimizing t).  In all such cases, the resulting label turns out to be "illegal" -- there is no irreducible representation of the given group which has that particular nTt as its smallest container.  So, this can be fixed without disrupting much.

While we are making that change to the data, there are other changes which might be reasonable.
<ul>
<li> if the smallest container has high degree, we just use the degree n instead of nTt (the classification of transitive subgroups of S_n might not exist).  We now have access to a bigger range of this classification, so we can use nTt instead of just n now going to a higher bound.  This would also not conflict with any old labels.
<li> the conductor of a representation is currently included in the label in factored form.  This was an attempt to shorten some labels, but it is different from the convention used everywhere else in the lmfdb.  We could switch them to unfactored form.  This also does not conflict with old labels.
<li> when matching 2-dimensional representations with modular forms, there is a question of ordering the representations in a Galois orbit.  This is also part of the label (as a "c1", "c2", "c3", ...).  The ordering for Artin representations is arbitrary while it is deterministic for modular forms, so the idea would be to use the same ordering for both.
</ul>
The ones where there is no conflict with current labels (all but the last one), we can support the old labels as well with no change to the label format.

If we do the last one and keep the same label format, then we would not be able to distinguish an old label from a new one in some cases.  If we do all of the above, the clash would only occur for representations of prime conductor Galois orbits of size bigger than 1 in which case a label might currently point to one representation, and later point to one of its conjugate representations.

So, the questions are which of these changes to make (probably all of them), and then whether or not we support all old/new label changes or not.  If not, we have the conflicts described in the last paragraph.  If we do want to support all old/new label changes, we need to change something else (e.g., a change in punctuation).

Suggestions?

**Comment by AndrewVSutherland** [comment]
I agree with all of these suggestions.  Regarding the last one, while I'm reasonably confident that there are no references to Artin rep labels in the literature that would be broken by this change (they would have to reference a specific Artin rep in a way that depended on the conjugacy class), it might be worth asking whether anyone knows of any instances of this.  In general I am morally opposed to the idea of changing labels in a way that could create ambiguities like this, but in this case we are switching from an arbitrary scheme to a well-defined one, and it only changes the conjugacy class, which in many/most settings will make no difference.

**Comment by roed314** [comment]
One way to prevent ambiguity would be to change the format slightly.  For example, we could just use another period instead of the c (this would parallel the labels for embedded modular forms).

In general I'm in favor of all of the changes listed.

**Comment by jwj61** [comment]
You are right that changing the c to a period would suffice to distinguish old labels from new ones, I like the c.  It uses the same number of characters and helps to visually parse the label.  Once we add Galois orbits of Artin representations, you can more easily see if you have a Galois orbit vs a specific representation based on the c instead of counting periods.

**Comment by edgarcosta** [comment]
Along with the @roed314 suggestion, we could replace the 'c' by a period and represent the index with a letter instead of a number (then we don't need to count periods)

So something like:
2.2e2_3e2_7e2_11.4t3.3c1
would become
2.1940.4t3.c.1

furthermore, visually, I prefer T instead of t.
2.1940.4T3.c.1

**Comment by jwj61** [comment]
I am leaning toward's Edgar's suggestion.  For the letter which represents the arbitrary counter of representations with given dimension, conductor, container, should I bother with periods before/after it?

**Comment by edgarcosta** [comment]
Yes, I think we should still bother with periods.
This way it would match very closely other labels on LMFDB. For example,
classical modular forms, elliptic curves, genus 2 curves, and almost number
fields, if the index was represented also as a letter

**Comment by jwj61** [comment]
Using periods, computations of new labels has started.

**Comment by jwj61** [comment]
Just an update.  The first stage of this went pretty well, but seems to have hit a new bug in magma's artin representation function.  A bug report has been submitted to magma.
