### ISSUE TITLE
Search parameters after a comma are sometimes ignored

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3468]
From the feedback page:

When searching for number fields, search parameters appearing after a comma are ignored--but only (as far as I can tell) when the Galois group is also specified.  The URL I linked is the simplest case I could find; the search results omit the quadratic fields with discriminants -23, -31, and so on.  The problem does not occur if the Galois group is unspecified, or if "2,3" is changed to "2-3".  If "2,3" is replaced by "3,2", then only the fields with class number 3 appear.  Similar behavior happens if you specify the number of ramified primes instead of the class number.

I first noticed the problem here:  https://www.lmfdb.org/NumberField/?signature=%5B4%2C0%5D&galois_group=C2xC2&class_number=3%2C6.  In that search, there should be a field with class number 6 between the 6th and 7th results.  Strangely, that search works perfectly when I switch "3,6" to "6,3"--but it breaks again when I try "5-6,3".

Respond to fernando@berkeley.edu

**Comment by jwj61** [comment]
I have not looked at this, but my guess is that it involves "splitting ors" in a search query, i.e., what we need to do when there is more than one "or" in a search query.  It may have been introduced in a recent fix which involved handling queries with an or in them (in the previous case it was when a branch of the or was impossible).

**Comment by roed314** [comment]
I will take a look.

**Comment by roed314** [comment]
See #3470.

**Comment by edgarcosta** [comment]
The changes are on www.lmfdb.org and I have emailed Ravi Fernando informing him that we have fixed the bug.
