### ISSUE TITLE
Embeddings table formatting

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#3526]
In [1452.1.m.b](https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/1452/1/m/b/) for example, the embeddings table is missing the bottom border on part of the table.  This is a consequence of a weird way that the corresponding columns are created (there's a subtable in the first row inside a td spanning multiple rows).

**Comment by edgarcosta** [comment]
Fixed via #3549
