### ISSUE TITLE
Change in raw html in knowls?

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3546]
The following knowl when run on master,

http://127.0.0.1:37777/knowledge/show/nf.galois_group.name

is currently broken (the html inside of it is quoted verbatim) but 

https://beta.lmfdb.org/knowledge/show/nf.galois_group.name

works

**Comment by AndrewVSutherland** [comment]
It looks like all the angle brackets are getting converted to &lt; and &gt; (I have no idea way, but perhaps one of @alexjbest or @edgarcosta or @roed314 does).

**Comment by alexjbest** [comment]
I added `| safe`  to the template function call, looks to have done the trick.
