### ISSUE TITLE
Table header border disappears after clicking on knowl link

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#3550]
Go to any table of search results (e.g. https://beta.lmfdb.org/NumberField/?all=1), click on a knowl in the header row then hide it.  The blue border at the bottom of the header disappears.  This is caused by the fact that there are now hidden rows holding the knowl, and the dark blue border is on the last row not the last visible row.

**Comment by AndrewVSutherland** [comment]
This has been fixed by Alex Best's clever css tweak (including in the latest g2c changes but the fix applies to everything).
