### ISSUE TITLE
Error reporting mistake

### ISSUE THREAD

**Issue by SamSchiavone** [LMFDB/lmfdb#3559]
On an error page, the link supplied for error reporting is wrong.

An example: if you start at https://www.lmfdb.org/EllipticCurve/, then search for elliptic curves over number fields with j-invariant 0 you get an error (as mentioned in https://github.com/LMFDB/lmfdb/issues/3558), with the error page says "If you want to help improving the page behind "https://www.lmfdb.org/EllipticCurve/", please report that page's URL!" This is the URL of the page I came from, not the one producing the error, which is https://www.lmfdb.org/EllipticCurve/?jinv=0.

![Screen Shot 2019-12-17 at 7 16 35 PM](https://user-images.githubusercontent.com/26484407/71045191-1db0d200-2102-11ea-980c-a4e6cfa6bd97.jpg)

**Comment by rbommel** [comment]
See also pull request #3765. This should make it a bit clearer. Now both the page and the page you are coming from are displayed. Also when there is no referrer, I still display something, as I believe that a 500 error should not occur randomly.

**Comment by AndrewVSutherland** [comment]
Server error when searching on j-invariant 0 on ECNF, looks like you based off an older version of the code.
