### ISSUE TITLE
Parsing problem for Galois groups

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3565]
If you search for number fields with Galois group S4 in degrees 6..12

https://beta.lmfdb.org/NumberField/?degree=6..12&galois_group=S4

you get an error message saying that the degree is inconsistent with the group (which is not true).  There are really two problems
<ol>
<li> the code which tries to form queries by combining degrees and t-numbers implicitly assumes that the user specified at most one degree, which is why the search above gives an erroneous error message.  Bear in mind that the user may give multiple degrees and multiple groups.  The current approach with degree and t-number separate in the database would produce complicated queries if programmed right.  The whole thing would be simpler if (n,t) pairs were stored for the Galois group.
<li> we will never be fully accurate in saying when a group is incompatible with a degree.  For example, searching for S5 in degree 120 gets a similar error message even though they are compatible.  We just don't store enough information to always get the message right.  So, that error message should be removed and just return empty search results.
</ol>

**Comment by AndrewVSutherland** [comment]
Agreed, I suggested this in my comment https://github.com/LMFDB/lmfdb/issues/2979#issuecomment-493677157 on issue #2979.  Unless we are certain (e.g. if the degree does not divide the order of the group) we should just run the search, and I see no problem with always just running the search.

**Comment by jwj61** [comment]
Yes.  Unfortunately, it isn't so easy with the search code.  It tries to mesh the Galois group information (with n and t separate) with specifications on n.  This will be easy to fix if we reconnect n and t in the database, but I wanted to see if there was a good reason to not do that first.

**Comment by AndrewVSutherland** [comment]
Resolved by #3587
