### ISSUE TITLE
broken reference link

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#3581]
On the [source page](https://www.lmfdb.org/Variety/Abelian/Fq/Source) for abelian varieties over F_q, the arxiv link to the first Kedlaya paper leads to a page "Article identifier '0608104' not recognized".

**Comment by AurelPage** [comment]
The correct link should be [this](https://arxiv.org/abs/math/0608104).

**Comment by AndrewVSutherland** [comment]
Fixed by editing the completeness knowl (https://beta.lmfdb.org/Variety/Abelian/Fq/Source)

The problem arose because with older dotless arXiv id's you need to include the subject area prefix, i.e. arxiv:math/0608104 works, as does arXiv:1511.06945, but arxiv:0608104 does not.
