### ISSUE TITLE
Local and global number field data upload

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3582]
Please copy db.nf_fields and db.lf_fields to the cloud.  I assume this includes indexes.

For both, there is a new column to make Galois group searching go better.  There will be a pull request soon which makes use of it.

Also global number fields has an additional 300,000 fields in degree 18 (coming from torsion on elliptic curves), and a small discriminant field in degree 8.

Local number fields has some data altered (some Eisenstein polynomials for unramified fields).  It was not wrong before, but we had to do a trivial computation with it before displaying, and when I ran lmfdb off of legendre, that computation made pages crash with a core dump (although they work on beta and the main site).  This data change just avoids the problem.

**Comment by AndrewVSutherland** [comment]
I ran into a problem with the copy, I'll need to take a close look tomorrow.

**Comment by AndrewVSutherland** [comment]
@jwj61  The tables have been copied over and I restarted the production webservers.  The counts and stats now look the same as on beta, but can you take a look to confirm that everything is OK (and then close this issue)?

**Comment by jwj61** [comment]
Thanks
