### ISSUE TITLE
reload_all does not work with non-default separator

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3586]
PR #3583 fixed the problem when using a default separator, but with a specified separator reload_all no longer works correctly (it did work prior to #3572).

**Comment by edgarcosta** [comment]
@AndrewVSutherland, the PR #3588 should address this issue. 
Could you try again the copy_to or reload_all using  ":" as a separator?

**Comment by AndrewVSutherland** [comment]
I think there is still an issue (reload_all hit a problem on counts):

> `sage: db.reload_all("/scratch/ar_Dec29",adjust_schema=True,sep=":")
Reloading artin_field_data, artin_reps
Reloading artin_field_data...
	Loaded data into artin_field_data in 94.432 secs from /scratch/ar_Dec29/artin_field_data.txt
---------------------------------------------------------------------------
InvalidTextRepresentation                 Traceback (most recent call last)
<ipython-input-4-002fae6d22f4> in <module>()
----> 1 db.reload_all("/scratch/ar_Dec29",adjust_schema=True,sep=":")

/home/drew/github/lmfdb/lmfdb/backend/database.py in reload_all(self, data_folder, halt_on_errors, resort, reindex, restat, adjust_schema, commit, **kwds)
   6825             for table, filedata, included in file_list:
   6826                 try:
-> 6827                     table.reload(*filedata, resort=resort, reindex=reindex, restat=restat, final_swap=False, silence_meta=True, adjust_schema=adjust_schema, **kwds)
   6828                 except DatabaseError:
   6829                     if halt_on_errors or non_existent_tables:

/home/drew/github/lmfdb/lmfdb/backend/database.py in reload(self, searchfile, extrafile, countsfile, statsfile, indexesfile, constraintsfile, metafile, resort, reindex, restat, final_swap, silence_meta, adjust_schema, commit, log_change, **kwds)
   3714                 else:
   3715                     self._clone(table, tmp_table)
-> 3716                 addid, counts[table] = self._copy_from(filename, tmp_table, cols, header, kwds)
   3717                 # Raise error if exactly one of search and extra contains ids
   3718                 if header:

/home/drew/github/lmfdb/lmfdb/backend/database.py in _copy_from(self, filename, table, columns, header, kwds)
    903 
    904                 cur = self._db.cursor()
--> 905                 cur.copy_from(F, table, columns=columns, sep=sep, **kwds)
    906 
    907                 if addid:

InvalidTextRepresentation: invalid input syntax for type json
DETAIL:  Expected end of input, but found ":".
CONTEXT:  JSON data, line 1: []:...
COPY artin_field_data_counts_tmp, line 1, column cols: "[]:[]:527642:f:f"
`

**Comment by edgarcosta** [comment]
I will try to look into this tomorrow night.

**Comment by AndrewVSutherland** [comment]
Now that the default separator works again (and a specified separator 
works with reload), this is not urgent.
