### ISSUE TITLE
Top/bottom knowl links for hypergeometric families have malformed IDs

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#3592]
This error message (minus the highlighting) arises from trying to create a top/bottom knowl for a hypergeometric family:

> Error: Oops, knowl id 'hgm.A30_B5.3.2.1.bottom' is not allowed. It must consist of **lowercase characters**, no spaces, numbers or '.', '_' and '-'.

This issue has of course come up before in other parts of the LMFDB: see #1140.

**Comment by edgarcosta** [comment]
Closed via #3664
