### ISSUE TITLE
EC/Q: show all integral points not just half

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#3618]
We currently only show one of a pair \pm P, but we should show both (when they are not equal).  In case of a curve with a_1=a_3=0 these should be displayed as (x,\pm y), otherwise as (x,y_1), (x,y_2).

**Comment by davidfarmer** [comment]
Glad to see this suggestion.  It had been argued for this
before (possibly by me), but unsuccessfully.  I have been bitten
by this more than once.

An edge case is this one:

https://www.lmfdb.org/EllipticCurve/Q/106/c/2

There are two integral points:  (0,1) and 0,-1) ,
but would those be shown as (0, \pm 1) even though a_1 \not= 0 ?

**Comment by JohnCremona** [comment]
My intention (which was actually @jvoight 's suggestion) was only to use the \pm notation in the case I stated.  In general the two y's add up to -(a1*x+a3) which can of course be 0 even when a1, a3 are not both zero as in your example (a3=x=0).

What convinced me (at last) to do this was to be consistent with hyperelliptic curve points, though there the \pm abbreviation is not used in the analogous cases (see https://beta.lmfdb.org/Genus2Curve/Q/400/a/409600/1 for example).

The current record is 84 integral ponts on https://beta.lmfdb.org/EllipticCurve/Q/232050/gy/1 where we only show 42 currently.  In this case the new display would show all 84.  As for hyperelliptic points, the display would be a list if under a certain length, otherwise a table to look neater.
