### ISSUE TITLE
Bianchi newforms: more a_p

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#3619]
The database currently stores 25 a_p (Hecke eigenvalues) for each Bianchi newform, and displays all of them.  I recently computed at least 200 a_p for each (this is more than enough to have a_p for primes p of norm<1000) and will upload them, at which point the code needs to display only the first 25 (say) by default with the option of showing more.

At the same time we should implement a data download capability for BMFs.

**Comment by JohnCremona** [comment]
ALso, the web page for an individual BMF should explain what the eigenvalues displayed for bad primes are and also indicate which are the bad primes.  For example, https://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.4.1/520.1/a/  where the bad primes are 1+i, 2+i and 2+3i but this is not easy to determine from the page currently (you have to scroll to the bottom to see that Atkin-Lehner eigenvalues).

**Comment by JohnCremona** [comment]
I am starting with the code changes.  Currently the number of ap stored varies from form to form, with this distribution of nap:count:  {100: 65562, 1000: 1, 15: 219, 25: 119979, 500: 37, 1236: 2}  so most have 25 or 100 but a few have 1000 or more.  Currently the code just silently truncates to 50 as you can see from (e.g.) https://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.4.1/65.3/a/ which shows 50 though there are 1000 stored.

So I would like to have a button for the user to press so that by default it shows 25 ap with a button "show all", if you click that you see all but the button says "show first 25".  (After the data update we should have 200 ap throughout.)  I don't know how to write such a thing.

**Comment by AndrewVSutherland** [comment]
@JohnCremona If you can take care of the data update I can find someone to implement the button you want to add (we have a couple of new people interested in contributing to the LMFDB, this would be a good first project for one of them).  The CMF pages already provide a good model for doing something like this.

**Comment by JohnCremona** [comment]
@AndrewVSutherland Thanks -- I was going to consult CMF pages first.  I have made a few changes to the current display (prompted by my comment above), which displays a fixed number of ap capped at 25 and I'll let someone else do the optiona switching.

I have done no data upload for BMFs since  mongo so will be proceeding rather carefully!

**Comment by JohnCremona** [comment]
For the record: my data files (I have not yet uploaded anything) contain at least 200 a_P for every newform (of dimension 1);  for level norm <=1000 they contains 1000 a_P;  and for a few select levels (probably those for which something unusual meant that I wanted to look at them more closely) there are 500.  When the time comes I think we'll be able to say that we have at least 200 a_P and 1000 for form of level norm up to 1000, and not mention the extras.

**Comment by JohnCremona** [comment]
I have uploaded the extra a_P into a copy of the bmf_forms table called bmf_test.  I'll also make a PR with some modifications to the code to display them -- still only displaying 50 but saying how many are in the database, pending a cleverer solution.

**Comment by JohnCremona** [comment]
@roed314 Feel free to replace bmf_forms with bmf_test.  Everything should still work, and random BMFs will then (after PR #4047 is merged) show that there are more aP in the database (but will not show them all yet).

**Comment by JohnCremona** [comment]
Still to do on this:  (1) copy bmf_forms to prod database (no code change needed); (2) merge master to prod and beta to see references to the extra ap on BMF home pages; (3) implement buttons as in the comments above.  Probably this issue should be closed only after all three have been done.

**Comment by edgarcosta** [comment]
bmf_forms has been copied

**Comment by AndrewVSutherland** [comment]
Closing, the remaining todo items are now separate issues #4053 #4054 .
