### ISSUE TITLE
Artin representations now working on production server

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3640]
From the feedback page:

I get 'The page you are looking for has produced a server error' when trying to access any data regarding Artin representations. I have no trouble accessing any other data.
Screen reader support enabled.

I have verified that this is true on the main server, but beta seems fine.  Maybe the main server just needs to be restarted.

**Comment by AndrewVSutherland** [comment]
This is failing because the artin reps scheme changed on beta but this change has not been pushed to the cloud, I am doing this now.

**Comment by AndrewVSutherland** [comment]
Fixed.
