### ISSUE TITLE
Display automorphism group for non-Galois number fields

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#3648]
Feature request:

For example, https://beta.lmfdb.org/NumberField/6.6.1397493.1 is not Galois and has 2 automorphisms (over Q of course) but this fact is not immediately available on the home page.  You can click on the knowl for the Galois group 6T6 and then get to 6T6's home page https://beta.lmfdb.org/GaloisGroup/6T6 where the size of the automorphism group is shown.

A simple version of what I am suggesting would be to display something like "it has ... autmorphisms" right after "This field is not Galois over Q".  I think this makes more sense than adding to the Galois Group section.

A fuller version would list the automorphisms (possibly in a new section) by listing the images of the generator a under each.  I guess we would not want to compute these on the fly though ([s(K.gen()) for s in K.automorphisms()] should do it) so that would require precomputation.

**Comment by jwj61** [comment]
Addressed by #3654

**Comment by JohnCremona** [comment]
Thanks!
