### ISSUE TITLE
Bad formatting on EC/Q stats page

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#3652]
Look at https://beta.lmfdb.org/EllipticCurve/Q/stats and the torsion structure has some column headings like C_2 X c_2  where X is latex \times.  But in the current master, on http://localhost:37777/EllipticCurve/Q/stats I see the word "times" instead and the html has a double backslash.

I think this was introduced by a recent PR from @AndrewVSutherland but I apologise if I am pointing in the wrong direction!

**Comment by AndrewVSutherland** [comment]
Fixed by #3653 (thanks @roed314)  For the record, this problem was not cause by any of my recent PR's but it was entirely reasonable to have assumed this :)
