### ISSUE TITLE
AV/FF Isogeny Classes: wrong "ordinary" = "no" in box "Properties"

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3656]
From the feedback page:

On https://www.lmfdb.org/Variety/Abelian/Fq/2/11/ae_g and also on other LMFDB pages on isogeny classes of AVs over finite fields, the box "Properties" says "ordinary" = "no" while it should read as "yes". I'd be happy to see the correct value. Thanks a lot, Christian

Respond to chr.cl.guenther@web.de

**Comment by roed314** [comment]
I've emailed Christian, and this is resolved.
