### ISSUE TITLE
knowl popups on cocalc don't show up

### ISSUE THREAD

**Issue by apeng16** [LMFDB/lmfdb#3666]
When clicking the Knowl it looks like we are trying to render 
https://cocalc.com/knowledge/render/lf.defining_polynomial?

instead of perhaps the right url, something like

https://cocalc.com/32aa118f-085c-49f7-ac86-b575c334f469/server/37777/knowledge/render/lf.defining_polynomial?

**Comment by roed314** [comment]
This was fixed by #3711.
