### ISSUE TITLE
Geometric endomorphism ring of elliptic curves

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#3683]
The knowl (ec.endomorphism_ring) defines the endomorphism ring of an elliptic curve over a number field to be the ring of endomorphisms defined over the algebraic closure.  It also says this is a special case of the endomorphism ring of an abelian variety, where the knowl (ag.endomorphism_ring) does not make it clear over what field the endomorphisms are defined over.  For genus 2 Jacobians (g2c.jac_endomorphisms), a distinction is made between the endomorphism ring (and algebra) and the *geometric* endomorphism ring.  

We need to be consistent, as this can and does frequently cause confusion.

The first minimal change I propose is to replace "endomorphism ring" by "geometric endomorphism ring" or if that's too long "QQbar-endomorphism ring" (which is slightly ambiguous, but easily clarified by looking at the knowl, and consistent with a choice made already for genus 2 (g2c.geom_end_alg).  
[It's much too common for folks to use the phrase "CM" to mean "geometric endomorphism algebra a CM field", so I do not think we should redefine this.  (In private, when necessary I find it helpful to distinguish between CM and potential CM, or PCM, but it seems unlikely that this will catch on.)]

Second, I propose that the knowl ag.endomorphism_ring makes it clear that these are defined over the base field of the abelian variety.  This is then consistent with what is done for genus 2 Jacobians and abelian varieties over finite fields.  

After that, it would be nice if for elliptic curves over number fields we listed both, which means just flagging those elliptic curves with CM by K by if K is a subfield of the field of definition of E (something we surely do not want to do on the fly).  We probably also want to search on this, with the options being "yes", "no", and "potentially" (in the case where the CM is defined over an extension).  Arguably we should do this for elliptic curves over QQ as well: although it would add some consistency, it will only ever be ZZ, so this would just involve adding a constant text value to the template--probably pointless.  For elliptic curves over number fields, it's still the case that most of the time the endomorphism ring will be ZZ, but not always--as for genus 2 Jacobians.

**Comment by samuel-rice** [comment]
Hello, just commenting as a way to attach myself to this issue. Is the suggestion that we would prefer to search by D directly, or would we still be exposing the options as "yes"/"no"/"potentially"?

**Comment by JohnCremona** [comment]
I think the suggestion in this issue is about how the endomorphism ring is displayed on the curve's home page, not about searching.  Once we have that then we can add potential/actual options to the search, though as I said the only actual CM ones are a few curves over imaginary quadratic fields, simply because all the other base fields for which we have curves have real embeddings.

**Comment by jvoight** [comment]
I'm OK to implement this without the search feature; I'll work on the knowl.

**Comment by jvoight** [comment]
I started changing knowls containing the word "endomorphism" and it seems like there are many conventions.  Before I wholesale start overriding things, I will want to discuss on Friday.

**Comment by jvoight** [comment]
Newly blessed, I'll get back now to editing knowls.

**Comment by AndrewVSutherland** [comment]
@jvoight I can review the knowls. We still need to make changes to the elliptic curve pages.  Currently we display the geometric endomorphism ring with the caption "Endomorphism ring".  I would suggest displaying both the endomorphism ring and the geometric endomorphism ring (as we do for genus 2 curves).

**Comment by JohnCremona** [comment]
As I will soon upload extra ecnf data including several new columns please tell me if it is worthwhile to include a second CM column indicating whether the CM is actual and not just potential, given that the former is very rare in the existing data and trivial to determine at the point of displaying a curve.

**Comment by AndrewVSutherland** [comment]
@JohnCremona I think you had proposed to change the sign of the CM discriminant in this case?  As you noted earlier, this could be useful for searching (and also for statistics).  I think this (or something equivalent) would be worth doing.

**Comment by JohnCremona** [comment]
You are right and that is what I 'll do.

(Reading these threads in gmail you only see what others have posted, not
your own, but I can see that my suggestion was to store |D| for actual CM
and D for potential.)

**Comment by JohnCremona** [comment]
By the way, the elliptic curves we have (all over imaginary quadratic fields) with actual CM are characterized by the *numerical* version of the isogeny class label being *negative*.  In all other cases the elliptic curve isogeny class label is taken from that of the associated Bianchi *cusp form* which has a letter code a,b,...,z,ba,...  and this is made numeric using the base 26 conversion, but the actual CM curves have no associated cusp form (there is an associated automorphic form, of course, but it is not cuspidal).    So the letter version of the isogeny class label has a prefix 'CM' followed by a,b,... and the numerical version of it is -1-n where n is the numerified base 26 conversion of the label without the 'CM'.  (e.g. CMa=-1, CMb=-2, etc).

This explains:
`sage: nfcurves.distinct('iso_nlabel') == [-12..58]`
`True`

and as a side-effect means that you can detect these rational CM curves by their isogeny class number being negative:
`sage: nfcurves.count({'iso_nlabel':{'$lt':0}})`
`1127`
`sage: nfcurves.distinct('field_label', {'iso_nlabel':{'$lt':0}})`
`['2.0.11.1', '2.0.3.1', '2.0.4.1', '2.0.7.1', '2.0.8.1']`

**Comment by AndrewVSutherland** [comment]
This has been done and will be on beta shortly.
