### ISSUE TITLE
Allow different output in search results

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#3715]
Generalizing issue #3388, as a feature request, users should be able to configure the output of their search results (showing certain output fields and hiding others).  I don't see any technical obstruction to doing this at least to some extent, but we should be savvy in making it user friendly.  

Separating this issue from #3388 because it got taken over with some other concerns, and perhaps it can be closed by just listing absolute discriminant in output and the possibly harder problem of configuring output can be put here.

I think this would be really useful to folks!  But requires some investment of time.

**Comment by AndrewVSutherland** [comment]
#3388 is related to this.

**Comment by AndrewVSutherland** [comment]
This has been done!
