### ISSUE TITLE
Computing L-functions on the fly for simple number fields

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#3722]
A user asked me why they couldn't access the L-function of the number field https://www.lmfdb.org/NumberField/4.0.400.1 from the sidebar, as I understand it the answer is that we don't want people to visit those pages too often (when `discriminant ^ degree` is large) as computing these L-values on the fly can take a while, but of course adding`/L/` to the web address functions.

Can we do anything better here; when the field has medium discriminant and degree but is nevertheless quite reasonable? More specifically 4.0.400.1 is abelian for instance, so computing the L-series should be somewhat easy given its factorization into known artin reps $L$-series? Can we take use this data to reduce the time to compute L-functions on the fly and "unlock" more L-functions.

**Comment by jwj61** [comment]
For abelian fields, it is even easier since the L-function is a product of Dirichlet L-functions, and those should definitely be in the database.  It is just a matter of having the code to look for and use the factorization which has been the plan for a long time.

**Comment by edgarcosta** [comment]
What would you like to see in such a case?

Many things can be extracted from the factorization, but not everything, e.g. the local factors, if it is not already a product of Galois orbits, or more generically the plot.

**Comment by alexjbest** [comment]
I was thinking specifically of the L-value at 1/2 which is the product of those already known and stored (please correct me if I'm missing something here! It's quite probable I am..) this seems to be one time consuming thing to recompute on the fly and the reason these pages are "disabled". As for the plot, that does also seem like it requires some on the fly computation, even if a factorization is known, maybe our L-function code is already doing something cleverer though here, I'm not sure.

Is there already a ticket or some description for the plans to use the factorization @jwj61 ?

**Comment by jwj61** [comment]
There is issue #1700 (not sure why it is not producing a link), but I don't know if there is a formal issue for other imprimitive L-functions.

**Comment by alexjbest** [comment]
Great thanks (it produced a link for me), feel free to close this as a duplicate then if you like.
