### ISSUE TITLE
Search for CM elliptic curves by CM field

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3724]
From the feedback page:

Given a quadratic imaginary extension k/Q, find all elliptic curves in the database whose endomorphism ring is an order in k. Thank you.

See feedback spreadsheet for e-mail to respond to.

**Comment by AndrewVSutherland** [comment]
This is essentially addressed by #3792 except when the CM field has more than one order of class number one (the fields of discriminant -3, -4, -7).  An easy way to handle this would be add 3 more options to the CM discriminant drop down that will let you search on [-3,-12,-27], [-4,-16], and [-7,-28].

**Comment by AndrewVSutherland** [comment]
Resolkved via #3961
