### ISSUE TITLE
Number field queries by root discriminant return false fields

### ISSUE THREAD

**Issue by bmatschke** [LMFDB/lmfdb#3748]
For example, https://beta.lmfdb.org/NumberField/?hst=List&rd=0.0-0.0 yields 92132 fields (correct would be 0).
This is possibly related to https://github.com/LMFDB/lmfdb/issues/3234.

**Comment by jwj61** [comment]
Looks like this is a data error, that some entries do not have their root discriminants filled in.

**Comment by jwj61** [comment]
This is now fixed on beta.

To fix it on the web, the table nf_fields needs to be copied to the cloud.

**Comment by AndrewVSutherland** [comment]
@jwj61 I'll copy nf_fields over now.

**Comment by jwj61** [comment]
Seems like the copy finished since the bug is no longer there on the main server.

**Comment by AndrewVSutherland** [comment]
Yes, it finished around noon EDT.
