### ISSUE TITLE
Error in euler factors of Artin representations under sage-9.0

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#3760]
After seeing this appear in travis test runs, @edgarcosta has found a way to reliably reproduce the problem.  While running the LMFDB under sage-9.0, go to 
[localhost/2.2e3_17.4t3.4c1](http://localhost:37777/L/ArtinRepresentation/2.2e3_17.4t3.4c1/)
This will
* take a very long time to load compared to [beta/2.2e3_17.4t3.4c1](beta.lmfdb.org/L/ArtinRepresentation/2.2e3_17.4t3.4c1/),
* the zeros on the critical line will never appear,
* and you will see the following error on the command line:
```
Traceback (most recent call last):
...
  File ".../lmfdb/artin_representations/math_classes.py", line 550, in good_factor
    return self.from_conjugacy_class_index_to_polynomial(self.nf().from_prime_to_conjugacy_class_index(p))
  File ".../lmfdb/artin_representations/math_classes.py", line 868, in from_prime_to_conjugacy_class_index
    return self.from_cycle_type_to_conjugacy_class_index(self.frobenius_cycle_type(p), p)
  File ".../lmfdb/artin_representations/math_classes.py", line 865, in from_cycle_type_to_conjugacy_class_index
    return fn_to_use(p)
  File ".../lmfdb/artin_representations/cyc_alt_res_engine.py", line 191, in RES_from_cycle_type_to_conjugacy_class_index
    return polynomial_conjugacy_class_matcher(alpha)
  File ".../lmfdb/artin_representations/cyc_alt_res_engine.py", line 62, in polynomial_conjugacy_class_matcher
    raise AssertionError("alpha = %s is supposed to be root of one of %s" % (alpha, input))
AssertionError: alpha = 8*a + 36 is supposed to be root of one of [{'RootOf': ['-2', '1'], 'ConjugacyClass': 2}, {'RootOf': ['14', '8', '1'], 'ConjugacyClass': 3}]
```

**Comment by jwj61** [comment]
I traced this to where we call sage to get roots of a polynomial over a finite field, and sometimes sage is producing something which is not a root.

This sometimes happens for p=29 over F_{29^2} for x^4 + 28*x^3 + 27*x^2 + 28*x + 1.  Sometimes it returns 20 as a root, and it isn't.

**Comment by jwj61** [comment]
A little more information.  If I just repeatedly call the roots function, I don't get an error.   I have to call it rotating through different primes.

Here is a small bit of code to generate an error:

def tst(p):
  Fq= FiniteField(p**2,"a")
  Fq_X = PolynomialRing(Fq, "x")
  pol = Fq_X([1, -1, -2, -1, 1])
  roots = pol.roots(multiplicities=False)
  print(p, " ", roots)
  for r in roots:
    try:
      assert pol(r) == 0
    except:
      print("Caught ", p, " and ", r)
      raise ValueError 

def domany(cnt=500):
  for j in range(cnt):
    [tst(5), tst(13), tst(29)]

Then call domany()

The three primes are chosen because the polynomial factors as a product of two quadratics for each, so they will have their roots in F_{p^2}.

**Comment by roed314** [comment]
Thanks, that's very helpful.  I will try to debug this in Sage.

**Comment by edgarcosta** [comment]
I'm building 9.1 beta6 to see if the error is still present

**Comment by roed314** [comment]
This is a bug in pari, which Sage is using to do the factorization:

```python
def tst(p):
     Fq= FiniteField(p**2,"a")
     Fq_X = PolynomialRing(Fq, "x")
     pol = Fq_X([1, -1, -2, -1, 1])
     v = [z.__pari__("a") for z in pol.list()]
     f = pari(v).Polrev()
     G = list(f.factor())
     roots = [-Fq_X(F)[0] for F in G[0]]
     print(p, " ", roots)
     for r in roots:
         assert pol(r) == 0
```
also causes the error.  @jwj61 do you want to submit a gp/pari bug report, or should I?

**Comment by edgarcosta** [comment]
This seems to be fixed in 9.1beta6.

**Comment by jwj61** [comment]
I assume this means it is already fixed in a more recent version of gp

**Comment by edgarcosta** [comment]
I'm building a new sage for travis.

**Comment by roed314** [comment]
> I assume this means it is already fixed in a more recent version of gp

Yes, I would expect so.  So there's no need to submit a bug report to pari.
