### ISSUE TITLE
Bug in code generation of Modular Form to Magma

### ISSUE THREAD

**Issue by assaferan** [LMFDB/lmfdb#3769]
The code generated ultimately uses the default precision of the function Basis, instead of the user defined precision.
e.g.
> MakeNewformModFrm_7_7_b_b(: prec := 100);
q - 8*q^2 + 2*nu*q^3 - 2*nu*q^5 - 16*nu*q^6 + (14*nu + 133)*q^7 + 512*q^8 - 
1311*q^9 + 16*nu*q^10 + 874*q^11 + O(q^12)

Reason is the generated line f := &+[f_lincom[i]*Basis(S)[i] : i in [1..#Basis(S)]];, 
which should be f := &+[f_lincom[i]*B[i] : i in [1..#B]];

**Comment by edgarcosta** [comment]
That code is just writing it in terms of basis computed by Magma.
Once you have the form, you can use get as many terms as you want:
```
> qExpansion(MakeNewformModFrm_7_7_b_b(), 30);
q - 8*q^2 + 2*nu*q^3 - 2*nu*q^5 - 16*nu*q^6 + (14*nu + 133)*q^7 + 512*q^8 -
    1311*q^9 + 16*nu*q^10 + 874*q^11 + 98*nu*q^13 + (-112*nu - 1064)*q^14 +
    2040*q^15 - 4096*q^16 - 264*nu*q^17 + 10488*q^18 + 138*nu*q^19 + (266*nu -
    14280)*q^21 - 6992*q^22 + 4738*q^23 + 1024*nu*q^24 + 13585*q^25 -
    784*nu*q^26 - 1164*nu*q^27 + 11146*q^29 + O(q^30)
```

**Comment by assaferan** [comment]
Oops, this is what remote learning does to my brain =-)

**Comment by edgarcosta** [comment]
It's alright, the documentation doesn't say anything about what does `prec` mean. We just use it as a parameter to control how many terms of the q-exp of we need to pinpoint f uniquely.
