### ISSUE TITLE
Knowl identifier link

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#3780]
When editing a knowl, the Identifier link leads to the rendered version of the knowl; it would be better to have it lead back to the show page.

**Comment by roed314** [comment]
@AndrewVSutherland This is an easy fix, but I think it might actually be better not to be a link at all.  If you follow the link and go back to the show page, it won't cancel the edit and will leave you with a lock on that knowl.  And there's already a link to the show page on the edit bar up above.

**Comment by AndrewVSutherland** [comment]
I think I agree, no link is better (the link isn't necessary and just creates the potential for confusion).
