### ISSUE TITLE
Maass form server error and wrong data

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3781]
From the feedback page:

trying to see data for the Maass Form:
level 1
weight: 0
character: 1 (trivial)
Spectral parameter: 27.333

Only 13 Fourier coefficients are shown, although the database claims to know 5000

Also, when going to the URL above, a server error is reported (no details given).
This server error also happens for smaller values of R, where 5000 coefficients are shown
https://www.lmfdb.org/ModularForm/GL2/Q/Maass/4cb8503a58bca9145800000a

See feedback spreadsheet lines 173 and 174 for whom to respond to.

-------------------------------------------------------
Here is another page reported by the same person through the feedback page:

The problem I reported yesterday is related, but different.  

We are looking at Maass Forms
Level: 1
Spectral Parameter Range 20..30
Weight: 0
Character: 1 (trivial)

The list off Fourier coefficients for the spectral value R = 27.333 starts with c[0]=1.  This doesn't make sense for a cusp form.  I think that the index of the coefficient must be shifted by 1, i.e., c[1]=1, c[2]=-0.209 etc.    

At least, with the shifted values, the Fourier series seems to be invariant under zz -> -1/z near i.  Other values cannot be checked because not enough coefficients are given.

The spectral values R=28.531 and 28.863 have the same problem.  These three eigenfunctions are even.  Even eigenfunctions above 30 look okay again.  (Odd eigenfunctions above 30 seem to be missing.  That's okay, as no claim of completeness is made.)

**Comment by davidfarmer** [comment]
Seems to be the same as issue #2647 , which has been closed.

**Comment by davidfarmer** [comment]
Fixed in blue.  Close after merging.

**Comment by AndrewVSutherland** [comment]
Fixed via #3929 and now live on www.lmfdb.org.
