### ISSUE TITLE
Mass Spectral parameter range input error

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3782]
If you enter 27.3..27.4 or 27.3-27.4 (indicating the interval [27.3,27.4]) into the Spectral parameter range input on https://www.lmfdb.org/ModularForm/GL2/Q/Maass/, the search works as expected.  but if you use more precision, eg. 27.32..27.34 or 27.32-27.34 it will display an error indicating that this is a invalid input (but it is a valid input).

**Comment by davidfarmer** [comment]
Fixed in blue.  Close after Drew merges.

**Comment by AndrewVSutherland** [comment]
Fixed via #3929
