### ISSUE TITLE
Dynamic stats for cmfs looks broken

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#3806]
Clicking on create your own under statistics for cmfs leads to the page https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/dynamic_stats  which currently returns a server error

**Comment by AndrewVSutherland** [comment]
Also true on beta.

**Comment by alexjbest** [comment]
Abvar dynamic stats page will load but doesn't appear to do anything, it looks like this is all due to the search box changes, so I'll leave this fo @roed314 I think.

**Comment by AndrewVSutherland** [comment]
Traceback:

`Exception on /ModularForm/GL2/Q/holomorphic/dynamic_stats [GET] Traceback (most recent call last): File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise raise value File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/home/lmfdb/lmfdb-git-dev/lmfdb/classical_modular_forms/main.py", line 1250, in dynamic_statistics return render_template("dynamic_stats.html", info=info, credit=credit(), title=title, bread=get_bread(other='Dynamic Statistics'), learnmore=learnmore_list()) File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template ctx.app, File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render rv = template.render(context) File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render self.environment.handle_exception() File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception reraise(*rewrite_traceback_stack(source=source)) File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise raise value.with_traceback(tb) File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/dynamic_stats.html", line 1, in top-level template code {% extends info.stats.dynamic_parent_page %} File "/home/lmfdb/lmfdb-git-dev/lmfdb/classical_modular_forms/templates/cmf_refine_search.html", line 1, in top-level template code {% extends 'homepage.html' %} File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/homepage.html", line 19, in top-level template code <div class="{{ [L,'nodisplay','code','codebox'] | join(' ')}}">{% for line in lines %}{{prompt}}:&nbsp;{{line}}<br /><div style="margin: 0; padding: 0; height: 0;">&nbsp;</div>{# this div is a workaround for a copy-tex bug where if a code block followed a hidden code block followed by math was selected and copied the hidden block would be also it is important that it has display: block #}{% endfor %}</div> File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/base.html", line 135, in top-level template code {% block body -%}{%- endblock body %} File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/homepage.html", line 244, in block "body" {% block content -%} File "/home/lmfdb/lmfdb-git-dev/lmfdb/classical_modular_forms/templates/cmf_refine_search.html", line 5, in block "content" {% include 'refine_search_form.html' %} File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/refine_search_form.html", line 20, in top-level template code {% if info.search_array.has_advanced_inputs(info) %} File "/home/lmfdb/lmfdb-git-dev/lmfdb/utils/search_boxes.py", line 650, in has_advanced_inputs for row in self.main_array(info): File "/home/lmfdb/lmfdb-git-dev/lmfdb/classical_modular_forms/main.py", line 1547, in main_array raise ValueError ValueError [2020-07-12 21:14:38 UTC] 500 error on URL http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/dynamic_stats ()`

**Comment by roed314** [comment]
I'll look into this in a couple of hours.
David
