### ISSUE TITLE
Incorrect ECNF data over Q(sqrt(-11)), conductor 9900.5

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#3815]
Mattia Sanna discovered a problem with the elliptic curves of conductor 9900.5 over Q(sqrt(-11)).  To see the most glaring case, look at https://beta.lmfdb.org/EllipticCurve/2.0.11.1/9900.5/?start=50&hst=List&field=2.0.11.1&conductor_norm=9900&one=yes which is supposed to show one curve in each of the 13 isogeny classes, and note that curves m1 and k1 are the same.

I will fix this by deleting all the curves with this conductor and uoploading a new set.   For the 13 associated BMFs, all have incrrect curves with the same label.  Two have no matching curves, two have a pair each, and the remaining ones are permuted.  So it's a mess.

Thanks to Mattia I am pretty sure that there are no other examples (but will not stake money on it).  He is systematically proving that the BMFs and isogeny classes of ECs over IQFs match in the sense that they have isomorphic Galois representations, so that all the curves are modular.

I have checked that the 13 BMFs at this level are correctly labelled, so the problem lies with the curves.

**Comment by JohnCremona** [comment]
@roed314 Help!  I am in the process of uploading corrected data for the field (2.0.11.1) and conductor (9900.5).   The new data has 64 curves in 13 isgeny classes.  After the first upload, using upsert, I realized that I should have deleted the existing data first (some isogeny class labels now have fewer curves than before, after the permutation, and some old rows were therefore not being deleted).  But when I do
nfcurves.delete({'field_label':'2.0.11.1', 'conductor_label':'9900.5'})
I get the error 
ProgrammingError: can't adapt type 'LmfdbRealLiteral'
raised at line 1278 of psycopg2/extras.pyc called by line 304 of lmfdb/backend/base.pyc.
That comes after 15 lines of messages about adding stats/statistics.
According to 
nfcurves.count({'field_label':'2.0.11.1', 'conductor_label':'9900.5'})
there are 68 curves in there.  I tried using "restat=False" and "resort=False" and then there is no error message, but there still appear to be 68 curves matching the search.  But they are not really there, as the beta website revealed.  So I uploaded the curves again (64 of them) and now the actual data looks right (http://localhost:37777/EllipticCurve/2.0.11.1/9900.5/?hst=List&field=2.0.11.1&conductor_norm=9900&search_type=List shows 64 curves) but the nfcurves.count() is still showing 68 .  I tried nfcurves.stats.refresh_stats() and got the error message about 'LmfdbRealLiteral' again.

**Comment by edgarcosta** [comment]
@roed314, the issue is the conductor norm average, which is converted into a LmfdbRealLiteral

**Comment by edgarcosta** [comment]
@JohnCremona, I have temporarily fixed the issue, by forcing floats instead of arbitrary precision type.
@roed314, I did this by adding the following lines ~835 of statstable.py
```
                for st, val in zip(["avg", "min", "max"], colstats):
                    from .encoding import LmfdbRealLiteral
                    if isinstance(val, LmfdbRealLiteral):
                        val = float(val)
                    stats_to_add.append((jcol, st, val, jcgcols, jcgvals, threshold))
```

**Comment by JohnCremona** [comment]
Thanks Edgar.  I cannot think of any conceivable reason for computing the average conductor norm. I certainly don't want it ever displayed anywhere.

Might it be a good idea to run the refresh_stats function on every table now in case there are other issues?

**Comment by JohnCremona** [comment]
The data for this conductor has been corrected. There are still 13 isogeny classes but now 64 curves instead of 62.  This issue can be closed once ec_nfcurves has been copied to prod. I  assume that the relevant counts will be automatically updated when that happens?

Please could someone do that copying. Thanks.

**Comment by JohnCremona** [comment]
Ping!

**Comment by edgarcosta** [comment]
Ping registered. I will do it today

**Comment by JohnCremona** [comment]
> Ping registered. I will do it today
Thanks Edgar.   I had been hoping for more data requiring a copy to be uploaded first, but let's get this done now as it corrects something which is actually wrong.

I'm about to make a new Issue for the other thing.

**Comment by edgarcosta** [comment]
@JohnCremona, please check that everything looks okay.

**Comment by JohnCremona** [comment]
> @JohnCremona, please check that everything looks okay.

Looks good -- thanks!
