### ISSUE TITLE
Data pull request for number fields and artin representations

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3820]
These were mentioned in code pull requests, but I want to make sure they get done.  Upload

nf_fields
artin_field_data
artin_reps

to prod.  The last two are particularly important since there is code in master which relies on these tables being updated.

**Comment by JohnCremona** [comment]
Not everyone who merges code PRs has  the ability to copy data!
We should have a place where we record that master should not be merged to prod until certain data has been copied.

**Comment by jwj61** [comment]
Right.  I should have made the data pull request an issue separate from the code pull request.

**Comment by AndrewVSutherland** [comment]
@jwj61 I will start this shortly.  It will take a while.

**Comment by AndrewVSutherland** [comment]
Starting nf_fields now (artin_field_data and artin_reps are done)

**Comment by jwj61** [comment]
Thanks.

**Comment by AndrewVSutherland** [comment]
@jwj61 The nf_fields update has finished -- can you take a look and make sure everything is copacetic?

**Comment by jwj61** [comment]
Looks fine.  I could tell it was done last night which is why I closed the issue.
