### ISSUE TITLE
Fricke and Atkin-Lehner eigenvalues

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#3838]
This is an edit of the original issue, summarizing the results of discussions with @edgarcosta .

On this page:
https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/6/4/a/a/

The Atkin-Lehner signs table should appear before the two twists tables
and before "Inner twists".

~And the two twists tables should show only 5 or 6 rows by default, with a
"show more" .~

It is no longer necessary to read the other comments on this issue.

**Comment by edgarcosta** [comment]
Don't we do that already?
https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/30/2/a/

**Comment by davidfarmer** [comment]
I see the source of my confusion.

If I go to the main "classical" page and click on "2-10" in the level row,
and then click on the 6th entry (which has level 6 and trivial character),
then I stop scrolling when I get to the long "twists" tables, because
it seems all the interesting invariants have already been shown.

So, can I change this issue into a suggestion that the long list of
twists be relegated to the absolute bottom of the page?

And maybe also elevate the Atkin-Lehner eigenvalues (when they exist)
to the section on "Newform invariants" (immediately after Fricke sign
would be a natural place)?

Note that I think in terms of individual (embedded) forms and not in
terms of spaces, because it is individual forms that correspond to
(primitive) L-functions.

**Comment by davidfarmer** [comment]
And I just discovered another source of my confusion.

If I go to the main classical page and search on 6 for the level,
I get back a list that only shows the Fricke eigenvalue.

But if I search on level 6 and weight 4, then I get a list that shows the
A-L eigenvalues.

It is worth thinking about the possibility of showing the A-L eigenvalues in all cases.
I realize that makes the table wider.

**Comment by edgarcosta** [comment]
along these lines, it also might worth it to expose the search on Fricke eigenvalues, as at the moment is a hidden feature, for example:
https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/?fricke_eigenval=1&char_order=1&weight=2

**Comment by edgarcosta** [comment]
@davidfarmer could you elaborate more on what you want?

**Comment by davidfarmer** [comment]
One issue is inconsistent display of information.  The 6th row of this page:

https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/?level=2-10

concerns the same object as the row on this page:

https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/?level=6&weight=4&search_type=List

The second shows A-L signs, which I think is good, and I would like to see that on the
first page.

Then on this page (which you reach by clicking on either of the entries mentioned above):

https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/6/4/a/a/

As you scroll down you encounter a long list of twists.  At that point I give us scrolling,
because that long table is not of great interest, so it looks like filler at the bottom of the page.
But, it turns out that the A-L eigenvalues are there, further down the bottom.  So, I suggest
moving the long twists table to be after the A-L and other small tables.

**Comment by edgarcosta** [comment]
I'm not sure how I feel about the first point.
I agree with the second point that the AL-signs should be moved above the "Inner twists".
Furthermore, the Inner twists table should have a show less/more button.

**Comment by samuel-rice** [comment]
At the rate this is going, we should end up with a nice new data table class that could unify a lot of code eventually. Still a work in progress but getting close!

**Comment by AndrewVSutherland** [comment]
I completely agree with putting the Atkin-Lehner table above the twist tables.  I'm not sure I agree with adding show more/less to the twist tables (if I scroll down far enough to see this, I almost certainly want to see the entire table, and there is an issue with the fact that the tables use a different sort order and showing more/less would mean different things for each of the tables and possibly be confusing (some times the same newform would appear in both tables, other times only one of them, and it would not be obvious why).

The number of inner twists is very rarely more than 8, so I'm not sure it's important to have a more/less option here (but I wouldn't object to it).

For 1.1.2 I think we should just move the Atkin-Lehner table.

Having a new data table is a good/useful thing to have regardless, but is really orthogonal to this issue.

**Comment by davidfarmer** [comment]
I'm okay with having the whole twist list visible, but I'll repeat my concern
that if anything is below the twist list (other than the footer), people will
not see it because of the long twist list table.  That is what happened to me,
so I suggest putting the twist list last.

**Comment by AndrewVSutherland** [comment]
@davidfarmer The Atkin-Lehner table now appears above the twist tables.  The twist tables are the last thing on the page except for the Hecke cutters, which I'm not sure even need to be on the pages at all (they are mostly used in downloads), but I think it's OK to leave them there below the twist table (I checked with @jvoight on this and he agreed).  Most people will never see them and that is fine.

I think this issue is ready to close, but let me know if there is more you would like to see done here.

**Comment by davidfarmer** [comment]
I still think it is funny to have the table of Hecke polynomials at the bottom:  either people will want to see it and it should be where people can see it, of they won't, in which case why is it there.

But, I'll close this and open another issue if later it still seems wrong to me.

**Comment by samuel-rice** [comment]
I apologise for dragging my feet on this one - I've been aiming for a general solution for tables with a "show more/less" option that would be more broadly applicable. The end result is a bit of a mess though, and I think the nicest approach would involve using jQuery (though I've struggled to get anything like that to work).
