### ISSUE TITLE
Theta series for lattice problem

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3844]
From the feedback page:

Z^2 seems to have the wrong theta series. https://beta.lmfdb.org/Lattice/2.1.2.1.1 

Same issue for A2. https://beta.lmfdb.org/Lattice/2.3.3.1.1

**Comment by jvoight** [comment]
There is very similar to #2821, there's a bug but we shouldn't track it in two places.

**Comment by colt-browning** [comment]
Hi @jvoight, in https://github.com/LMFDB/lmfdb/issues/2821#issuecomment-1555309189, you said:
> Happy to reopen the issue, accept a patch, and close it.

The problem is, how do I submit a patch to the database content? I can see the raw data, including the places that should be corrected, at https://www.lmfdb.org/api/lat_lattices/, but the source is apparently neither in this repository, nor in https://github.com/annahaensch/lattice_data (which is claimed to be the source of some data at https://beta.lmfdb.org/Lattice/Source), nor anywhere else. I would submit a patch if I could find the repository with the data.

**Comment by roed314** [comment]
The data is stored in a PostgreSQL database, to which LMFDB editors have write access.  If you can provide a file with the corrected data in the right format, we can upload it.  Here's the format needed:

The first line should give the label, plus the columns to be changed (presumably just `theta_series` in this case, but could include more column names in other cases).  The second line should give the types of the columns.  Then a blank line, followed by data lines for the lattices that need to be changed.  For example, the data currently there would be achieved with

```
label|theta_series
text|jsonb

2.1.2.1.1|[1,0,2,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
```

Of course, there are problems with other lattices as well as Z^2.  If you're interested in helping fix them, or improving the lattice database in other ways, we'd be happy to have a conversation with you and get you up to speed.

**Comment by colt-browning** [comment]
Thanks!
The patch:
```
label|theta_series
text|jsonb

2.1.2.1.1|[1,4,4,0,4,8,0,0,4,4,8,0,0,8,0,0,4,8,4,0,8,0,0,0,0,12,8,0,0,8,0,0,4,0,8,0,4,8,0,0,8,8,0,0,0,8,0,0,0,4,12,0,8,8,0,0,0,0,8,0,0,8,0,0,4,16,0,0,8,0,0,0,4,8,8,0,0,0,0,0,8,4,8,0,0,16,0,0,0,8,8,0,0,0,0,0,0,8,4,0,12,8,0,0,8,0,8,0,0,8,0,0,0,8,0,0,8,8,0,0,0,4,8,0,0,16,0,0,4,0,16,0,0,0,0,0,8,8,0,0,0,0,0,0,4,16,8,0,8,8,0]
2.3.3.1.1|[1,0,6,0,0,0,6,0,6,0,0,0,0,0,12,0,0,0,6,0,0,0,0,0,6,0,12,0,0,0,0,0,6,0,0,0,0,0,12,0,0,0,12,0,0,0,0,0,0,0,6,0,0,0,6,0,12,0,0,0,0,0,12,0,0,0,0,0,0,0,0,0,6,0,12,0,0,0,12,0,0,0,0,0,0,0,12,0,0,0,0,0,0,0,0,0,6,0,18,0,0,0,0,0,12,0,0,0,0,0,0,0,0,0,12,0,0,0,0,0,0,0,12,0,0,0,12,0,6,0,0,0,0,0,12,0,0,0,0,0,0,0,0,0,0,0,12,0,0,0,6]
```
Regarding further support of the lattice database, I wrote you an email.
