### ISSUE TITLE
Error message issues

### ISSUE THREAD

**Issue by jenpaulhus** [LMFDB/lmfdb#3845]
I was using Safari when this error happened and cannot get it to reproduce in Chrome so the issue may well be Safari.

For many pages, when I type the word "junk" in the "label" search box and hit "Find", it will sometimes just reload the same search page without the error.  If I enter "junk" again, it will sometimes then give the error message twice at the top of the page.  Or you can see on the attached picture: I had  typed "junk" once on the Bianchi Modular Forms label search, it reloaded the search page without an error message, but when I navigated away to the Hilbert Modular Forms page, it the posted the error message from the old page.
![Screen Shot 2020-05-26 at 11 23 56 AM](https://user-images.githubusercontent.com/18049927/82925620-9171c900-9f43-11ea-8440-55bbca0b30ef.png)

**Comment by AndrewVSutherland** [comment]
This is not just Safari, I can recreate this for BMFs and HMFs on Firefox, Brave, and Chrome (it sometimes takes several tries to get it to happen).

**Comment by AndrewVSutherland** [comment]
If you type "junk" into the number fields or genus 2 jump boxes on www.lmfdb.org you will often not get an error message at all and occasionally get several (happens on safari, chrome/brave and firefox).  This does not seem to happen on beta.(which is currently running exactly the same code as in production).  It is pretty easy to reproduce this.

**Comment by edgarcosta** [comment]
Can you please check that this is now fixed on beta.lmfdb.org ?

**Comment by AndrewVSutherland** [comment]
Looks good!

**Comment by jenpaulhus** [comment]
Works on my Safari too!

**Comment by edgarcosta** [comment]
I think merging #3693 will fix address this problem everywhere

**Comment by edgarcosta** [comment]
It got even worse... We may need to avoid redirects on the jump.

**Comment by AndrewVSutherland** [comment]
@edgarcosta Did you change the affinity on www.lmfdb.org?  I no longer seem to be able to break it on (chrome or firefox).

Unless someone else can reproduce the problem, I'm be very happy to close this :)

**Comment by edgarcosta** [comment]
I turned on affinity, it seems that it solved the problem.
