### ISSUE TITLE
AbVar: Error message issue

### ISSUE THREAD

**Issue by jenpaulhus** [LMFDB/lmfdb#3846]
On the abelian varieties pages, if I enter "junk" into the label search I get a server error instead of the typical "this is not an ok label" error message.

**Comment by jwj61** [comment]
No longer a server error, although the message it gives now, "Polynomial degree must be even" sounds a bit clueless on the part of the web page.

**Comment by roed314** [comment]
See #3919

**Comment by AndrewVSutherland** [comment]
Fixed by #3919
