### ISSUE TITLE
Redirect and url_for generate http links rather than https

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#3859]
While investigating #3845 I noticed that when a user tries to visit a jump link the user is redirected to a http:// page rather than https:// seeing as the whole site is https now this automatically redirects to the same page with the right protocol so this is invisible to the user, however redirecting to the wrong address first is a bit weird and should be avoided imo. At the very least it makes debugging headers have more spam than it should.

To see this, go to a page like https://beta.lmfdb.org/ModularForm/Q/holomorphic/ (ok the exact page isn't important but for clarity lets use this one) open developer tools (in Chrome) click the network tab, and click record. Type "junk" in the label box and press enter,
a bunch of things should show up in the list, but "holomorphic/" should appear twice, once as a 301 permanent redirect from http to https then https as 200 OK.

Some googling suggests https://stackoverflow.com/a/37842465/2105639 or the other answers may be relevant.

I'm not sure how to debug this as the only way I connected to a debug version is via http only anyway.

**Comment by edgarcosta** [comment]
I believe this is fixed on beta.lmfdb.org, could someone double check?

Trying to fix it now on lmfdb.org

**Comment by alexjbest** [comment]
Yes this looks better to me on beta

**Comment by edgarcosta** [comment]
I might have to write some code for `www.lmfdb.org`, as google cloud doesn't give me the option to set the header x-forwarded-proto on the load balancer

**Comment by edgarcosta** [comment]
This has been fixed.
