### ISSUE TITLE
CMF search/browse drop-down qualifiers slightly too narrow

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3863]
On Chrome the drop down boxes for the parity of the weight and character and for the include/exclude bad primes are not quite wide enough, they need another 10-20 pixels to display the entire default option without cutting off the last character ("any parity" would look nicer than "any parit").

**Comment by tomgrubbmath** [comment]
I'm not sure how the workflow with LMFDB usually works but to try and avoid redundant work I thought I'd comment to say I have created a new local branch to address this issue
