### ISSUE TITLE
knowls for dirichlet characters are broken on beta

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#3864]
https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/768/2/f/a/
![Screen Shot 2020-06-04 at 21 25 08](https://user-images.githubusercontent.com/322822/83826429-e03d0280-a6a9-11ea-8101-3cebdf57ea6e.png)

**Comment by jwj61** [comment]
At some point there was a change so that html in dynamic knowls needed to have "| safe" put in.  I just tried to do that with this knowl, but kept getting an error when trying to save it.

**Comment by jwj61** [comment]
Looking at flasklog, this looks like it is caused by the shift to python3 (byte vs str).

**Comment by AndrewVSutherland** [comment]
Once #3867 is fixed we can edit the knowl to fix this.
