### ISSUE TITLE
roots of unity display wrongly

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#389]
At `ModularForm/GL2/Q/holomorphic/13/4/4/` there's a q-expansion in terms of \(\zeta_6\) but under it it says that \(\zeta_12=aexp(2api i7/n)\) which has the wrong definition of the wrong root of unity (and also omits {} around the 12 in the subscript!).

**Comment by JohnCremona** [comment]
My branch roots-of-unity fixes 2 of the 3 problems: the brackets round the subscripts and the correct denominator.  However in the example page, the q-expansion is in terms of zeta_6 yet the thing defined is zeta_12 (sorry, zeta_{12}!) and I have not yet worked out how to fix that.

https://github.com/JohnCremona/lmfdb/tree/roots-of-unity

**Comment by nmascot** [comment]
Seems to work fine now (on Fredrik's refactor branch)

**Comment by JohnCremona** [comment]
The remaining issue is that the expansion is in terms of zreta_6 but the definition below is of zeta_12.

**Comment by nmascot** [comment]
For me, it says "ζ6 is a primitive 6-th root of unity.", which is all right. Which branch are you on, John ?

**Comment by JohnCremona** [comment]
My mistake, I did not llok at the refactor branch.  I will withdraw...

**Comment by davidfarmer** [comment]
Fixed in Fredrik's refactor branch
