### ISSUE TITLE
Normalization of E/Q symmetric square bad factors

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#3891]
On the home page for the symmetric square of an elliptic curve/Q, such as:
    https://beta.lmfdb.org/L/SymmetricPower/2/EllipticCurve/Q/20/a/
the bad Euler factors are not shown in the correct normalization.

In that particular example, the bad factors in the analytic normalization should be
(1 + 2^{-s})(1 - \frac15 5^{-s}) .

The Dirichlet coefficients at the top of the page are correct.

**Comment by roed314** [comment]
It looks like the LMFDB no longer has symmetric square L-functions (at least the link referred to in this issue no longer works).  @edgarcosta, can this be closed?
