### ISSUE TITLE
Extra row below p=71 in local information of Hypergeometric Motive?

### ISSUE THREAD

**Issue by tomgrubbmath** [LMFDB/lmfdb#3893]
In the "Local Information" table of a Hypergeometric Motive there seems to be an extra, partially filled in row beneath the data for p=71. See, for instance, https://beta.lmfdb.org/Motive/Hypergeometric/Q/A8_B2.2.2.1/t4.1 , where the partial information is 1 4 24 48. This extra row has appeared on every "random HGM" that I have checked. 

If this is supposed to an entry for p=73, then perhaps more data needs to be uploaded. Alternatively, the partial row should just be deleted.

**Comment by edgarcosta** [comment]
I think that row has some other meaning. I'm not aware of its meaning.
I should also point out that motives have not been improved in many ways for many years, you are starting to focus on families.

**Comment by tomgrubbmath** [comment]
Just for closure on this issue, the extra row is the least common multiple of the data in the corresponding column.

**Comment by AndrewVSutherland** [comment]
Given that this is just one of many UI issues on this page (e.g. what is |D| and why is it often negative?), I am going to close this issue.  We know that these pages need work and that they will all need to be carefully reviewed before hypergeometric motives are moved into production.
