### ISSUE TITLE
Add BSD data for EC/NF

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#3900]
For elliptic curves over number fields I have mostly completed the job of computing Mordell-Weil rank (or lower and upper bounds), generators, analytic ranks, special L-value and analytic order of Sha.  Currently this is complete for number fields of degree 2, 3, 4 and partially complete in degrees 5 and 6.  I plan to upload the data which I have (which wil involve adding several new columns to the table in the database) and then work on displaying this on individual curve pages and isogeny class pages.

Note that when I say that the data is complete I include the possibility that the lower and upper bounds on the rank are different, in which case the number of generators is equal to the lower bound.  If the analytic rank is the same as the lower bound then we can still compute analytic Sha, otherwise not. For example, here is the rank distribution (by isogeny class) for 2.0.4.1:

0: 13696
1: 22063
2: 4461
3: 17
[0,1]: 18 (all have a.r.=1)
[0,2]: 20 (all have a.r.=0)

So there are 18 classes where the rank must be 1 but we are missing a generator, and 20 for which the rank must be 0 but Magma could not prove it.  For the last set we compute analytic Sha on the assumption that the rank is 0, but for the first set we cannot (though we can guess that Sha is trivial and then deduce the height of the missing generator).

**Comment by AndrewVSutherland** [comment]
@JohnCremona Any update on this?

**Comment by JohnCremona** [comment]
I will be doing the upload early next week.

**Comment by JohnCremona** [comment]
Somewhere @roed314 asked me about searching by rank but I cannot remember where.  This will make sense after I have updated the data here, after which we'll have ranks for the vast majority of curves and rank bounds for all.  We'll also have analytic ranks for: all curves over fields of degree <=4,  most over degree 5 (23 out of 34 fields are complete) but not over degree 6 (where Magma is taking days or weeks per curve).

Usually, lower bound = upper bound = analytic rank (= number of generators stored).  The exceptions are as follows (for degrees up to 5 incomplete in degree 5):

[lb,ub]  ar  ngens
[0,1]     1      0   (so the rank is expected to be 1 but we have no generator)
[0,2]     0      0   (so the rank is expected to be 0)
[0,3]      0     0   (" " ")  only in degree 4&5, 5 cases
[1,2]     2      1   (so the rank is expected to be 2 but we have only one generator) 3 cases, in degrees 4&5
[1,3]     1       1 (so the rank is expected to be 1)  4 cases, degrees 4&5

What this suggests is that it would make a lot of sense for the search on rank to actually search on the analytic rank.  Provided that we make clear that this includes the above special cases.  Except that this would leave all the degree 6 curves out.

I'll add to this in a few minutes with some degree 6 information.

**Comment by JohnCremona** [comment]
Here are the counts, rank-bounds, analytic rank (and ngens) for all curves over sextic fields for which the lower and uppoer bounds are different:
   150 [0,1] ? 0
     58 [0,1] 1 0
     36 [0,2] ? 0
     20 [0,2] 0 0
      4 [0,2] 2 0
      6 [0,3] ? 0
     18 [0,4] ? 0
      6 [0,5] ? 0

Despite what I said before I do seem to have analytic ranks for some of these fields.

**Comment by JohnCremona** [comment]
I have made a new table db.ec_nfcurves_test which (1) contains 10 new columns and (2) fills in data previously missing in existing columns.  No code changes are needed to use the new table, which can therefore replace the existing db.ec_nfcurves on beta and web.  Details follow:

   - The old columns which are now filled in almost all cases are rank and rank_bounds, with updated ngens,  gens, heights, reg.  These are now filled except for (a) the field 6.6.453789.1 which is still running, and (b) 8 curves with everywhere good reduction over rather large imaginary quadratic fields.  I will update (a) when that run has finished, but we are unlikely to be able to compute ranks for most of the curves in (b) -- I only did the first three.
  
The new columns are:
   - reducible_primes    integer[] (list of prime isogeny degrees)
   - n_bad_primes        integer (number of primes of bad reduction)
   - bad_primes          jsonb   (list of primes of bad reduction, each as a string)
   - semistable           boolean (global semistable flag)
   - * tamagawa_product    bigint  (product of Tamagawa numbers)
   - potential_good_reduction boolean (is j-invariant integral?)
   - torsion_primes integer[] (list of prime torsion orders)
   - * omega numeric real  (normalised global period)
   - * Lvalue numeric real  (leading coeffient of L-series at s=1)
   - * sha integer  (rounded analytic sha)

of which only those marked are actually involved in the BSD conjecture, the others have come up in discussion as potantially useful.  At present the last 3 of these are not computed for any curves over *sextic* fields (where magma is taking about one month per curve and we have 6097 up to isogeny), and are incomplete for 10 of the 34 quintic fields.  The quintic data will be added when that is done.

**Comment by JohnCremona** [comment]
So there is still some work to be done with the gaps in the data.   But I can progress now with the code changes needed to display the additional BSD data, which will of course have to allow for the absence of some data (the analytic rank, L-value and sha) for sextic fields and the 5 'large' IQF curves.

**Comment by JohnCremona** [comment]
I have been making good progress with the template.  There are several special cases when we only have bounds on the rank and may or may not have the analytic rank, and may have fewer generators than the analytic rank, etc , etc.  I have also been writing and editing several knowls: getting the BSD formula exactly right over any number field, when there may not be a global minimal model, is quite tricky.  I expect to finish this and ask for some reviewing tomorrow.

Among the knowls I did not find (but was expecting) are:  
   - under nf,  "infinite places", "real places" and "complex places" (we have knowls for real and complex embeddings, but nothing which includes both without having to say "up to conjugation" or similar.
   - under ec, "period lattice"
   - under lfunction, we have "leading_coeff" but the value is referred to also as a "special value" (for example, see the knowl ec.q.special_value which could, but does not, refer to lfunction.leading_coeff).    As far as I know the leading coefficient and the special value are the same?  (Please let us not fight over a factor of r!, though I did once give a talk about the BSD conjecture with both Birch and Swinnerton-Dyer in the front row, and left the r! out of the formula, and SD interrupted me to correct it...)

**Comment by JohnCremona** [comment]
My branch ecnf-bsd is ready for trying out, but I have not made a PR yet since it will only work using the table ec_nfcurves_test instead of ec_nfcurves.

There are many slightly different cases to be dealt with depending on whether we have missing data (e.g. over sextic fields) or when the lower and upper bounds on the rank are different.  I tried to be very systematic about this, and display all useful information.  Here are examples to look at:

http://localhost:37777/EllipticCurve/2.0.3.1/111972.3/d/3  rank 0 known
http://localhost:37777/EllipticCurve/3.3.1509.1/54.2/c/1  rank 1 known
http://localhost:37777/EllipticCurve/2.2.97.1/100.2/b/1  rank 2 known
http://localhost:37777/EllipticCurve/2.2.93.1/197.2/b/1  rank 3 known
http://localhost:37777/EllipticCurve/3.3.1101.1/64.4/c/1  bounds 0,2; analytic rank 0
http://localhost:37777/EllipticCurve/2.0.11.1/3100.5/c/1  bounds 0,1; analytic rank 1
http://localhost:37777/EllipticCurve/4.4.15317.1/94.3/c/1  bounds 0,3; analytic rank 1
http://localhost:37777/EllipticCurve/4.4.2225.1/1216.5/h/1  bounds 1,3; analytic rank 1
http://localhost:37777/EllipticCurve/6.6.592661.1/409.1/a/1  bounds 0,2; analytic rank 2
http://localhost:37777/EllipticCurve/6.6.453789.1/43.1/a/1  no rank bounds or analytic rank

**Comment by JohnCremona** [comment]
The data has been updated on beta.  Still missing are rank bounds for one sextic field, but there are only 10 curves left and I'll update the table when that is finished.  And for quintics there are 10 *fields* still running (out of 34 fields), where we have ranks or rank bounds but not all analytic ranks/special values/analyic sha yet.  These will take longer and I'll update the datta when done but nothing should wait for that.

**Comment by AndrewVSutherland** [comment]
The data has been copied to the cloud.  Let me know if/when you update data for any of the 10 remaining curves and I can copy again.  Your PR has been merged but I'll hold off pushing it to web until later today.

**Comment by JohnCremona** [comment]
OK -- should be tomorrow.

**Comment by JohnCremona** [comment]
> The data has been copied to the cloud. Let me know if/when you update data for any of the 10 remaining curves and I can copy again. Your PR has been merged but I'll hold off pushing it to web until later today.

I just uploaded data for the last sextic field.  As with all the other sextics fields, and 10 quintic fields still running, the BSD data is incomplete but still displays OK.  Now we have rank bounds for all curves except the 5 rogue ones over imaginary quadratic fields with large discriminant (which are always an annoying exception):

sage: [(B, db.ec_nfcurves.count({"rank_bounds":B})) for B in db.ec_nfcurves.distinct("rank_bounds")]
[([0, 0], 293933),
 ([0, 1], 2815),
 ([0, 2], 1095),
 ([0, 3], 36),
 ([0, 4], 18),
 ([0, 5], 6),
 ([1, 1], 329145),
 ([1, 2], 6),
 ([1, 3], 24),
 ([2, 2], 33890),
 ([3, 3], 106),
 (None, 5)]

Please copy ec_nfcurves (again).  The rest of the data for te last 10 quintic fields will take a while, though I will probably reschedule them to run on more cpus as there are ~1400 curves left and so far I have just split them up by base field.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Done!

**Comment by JohnCremona** [comment]
@AndrewVSutherland Thanks -- now there is no reasone (that I know of) not to push master to web.

**Comment by AndrewVSutherland** [comment]
The only thing I think that remains to be done for 1.1.2 is updating the source/completeness/reliability knowls to address the new BSD invariants that have been added.

**Comment by JohnCremona** [comment]
I'll do that today.  I don't think that we need to keep the issue open while I finish off the remaining degree 5 fields

**Comment by AndrewVSutherland** [comment]
It looks like the knowls have been updated.  They still need to be reviewed but that is no reason to keep this issue open (I'll try to review them later today)
