### ISSUE TITLE
api2 search examples return API errors

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3911]
None of the example searches on https://www.lmfdb.org/api2/ are currently working (this is also true on beta).  In particular, the links

https://www.lmfdb.org/api2/description/elliptic_curves_q
https://www.lmfdb.org/api2/inventory/elliptic_curves_q
https://www.lmfdb.org/api2/data/elliptic_curve_q?label=%22100a3%22&_fields=%222adic_index%22

all return API errors.

**Comment by davidlowryduda** [comment]
I have a partial fix in the pull request #3918. On my branch, I fix the first two pages not resolving, and the page http://localhost:37777/api2/data/elliptic_curves_q?label=%22100a3%22.

But the last example on the api2 page, restricting fields, still doesn't work. This is the example

https://www.lmfdb.org/api2/data/elliptic_curve_q?label=%22100a3%22&_fields=%222adic_index%22

The reasons this one doesn't work seem to be deeper problems.

**Comment by AndrewVSutherland** [comment]
closing, since api2 is no longer available
