### ISSUE TITLE
CMF coefficient ring index being displayed when it should not be shown

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3914]
If you go to a cmf homepage like

   https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/983/2/c/a/

where the coefficient ring has not actually been computed (in this example it lies in a number field of degree 39690 and we are never going to compute it), the hecke_ring_index is set to None in the database and the coefficient ring index should not be displayed, but it is being displayed as "Multiple of None"

**Comment by tomgrubbmath** [comment]
@AndrewVSutherland Do you prefer telling the reader that the value is not computed, or skipping that line entirely (or some other option)? Photos for comparison below
![newforms](https://user-images.githubusercontent.com/53013402/88472036-15085180-cec4-11ea-97bb-bfc51fd429a2.png)

**Comment by AndrewVSutherland** [comment]
Given that we are not showing any information about the coefficient ring (we don't even know generators for it, let alone its index), I think its better to omit it completely.
