### ISSUE TITLE
Link for zeta zeros not working

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3922]
From the feedback page:

If you try to download a huge number of zeros, you get a message displaying the knowl dq.zeros.zeta.toomany which directs the user to get them from http://lmfdb.warwick.ac.uk/data/zeros/zeta/ .  That link is currently not working.

**Comment by edgarcosta** [comment]
It is not clear to me what to do.
We can make the bucket public, but we risk that to pay a high price for people downloading it.
Alternatively, we can store them locally at MIT if needed, but we will need to buy a disk for it.
A similar question applies to the class groups data for quadratic imaginary fields.

**Comment by AndrewVSutherland** [comment]
I think we should host it ourselves, the cost of doing so is negligible.

**Comment by AndrewVSutherland** [comment]
The disk has been ordered, it will take a few weeks for it to arrive and be installed.  Once it does we will host both the class group data and the zeta zero data  on the server hosting beta.lmfdb.org

**Comment by JohnCremona** [comment]
Obviously this should be hosted in the same place as the main database. Same for the class mumber tables. Possibly not noticed before as lmfdb.warwick.ac.uk went  offline just a couple of weeks ago and I (for one) was unaware that we still had links to it. I hope to get that server back online soon after the Warwick campus reopens (no date set for that yet) but that may be irrelevant. I may have copied these datasets to  newer fileserver.  I will report back.

**Comment by AndrewVSutherland** [comment]
@JohnCremona No worries, we have the data, it's just a question of making it available for public download -- Google charges us network egress charges that are fine to pay once but if lots of people start download 1TB file will eventually add up.  Once the new disk arrives we can make the zeros and imaginary quadratic class groups available for download from the MIT server that hosts beta.

**Comment by AndrewVSutherland** [comment]
This disk has arrived we are just waiting on getting it installed, which will hopefully happen next week.

**Comment by edgarcosta** [comment]
Is there an optimal time during the week to bring all the websites down?

**Comment by AndrewVSutherland** [comment]
@edgarcosta I was just thinking about that.  Let's talk about it.

**Comment by AndrewVSutherland** [comment]
Update: We attempted to install the new drive today but ran into a compatibility issue.  We have ordered replacement that will hopefully arrive by next Friday.

**Comment by AndrewVSutherland** [comment]
Further update: the hardware is unfortunately not going to arrive until October 10, so this will have to wait until next week.

**Comment by AndrewVSutherland** [comment]
We ran into yet another hardware issue (a missing cable).  We will try again on October 23 (hopefully the third time will be the charm).

**Comment by edgarcosta** [comment]
dumping the google storage into our new disk.
I hope to get the process done by the end of the weekend

**Comment by AndrewVSutherland** [comment]
@edgarcosta It looks like the files are now in place --  I can see 1.3T of zeta zeros and 2.1T of class group data sitting on the new disk.  What else do we need to do to close this issue?

**Comment by edgarcosta** [comment]
Please review https://beta.lmfdb.org/knowledge/show/dq.zeros.zeta.toomany

**Comment by edgarcosta** [comment]
also, should we delete: https://beta.lmfdb.org/knowledge/show/zeros.zeta.contents ?

**Comment by AndrewVSutherland** [comment]
@edgarcosta Done (reviewed one and deleted the other).
