### ISSUE TITLE
ECNF include degree of field in search criteria

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#3944]
Sometimes I just want the ECs over quadratic fields.

**Comment by JohnCremona** [comment]
Good idea -- me too!  Easy to do since the degree is a column in the db.

**Comment by AndrewVSutherland** [comment]
And the range 2- would exclude curves over Q once #3837 is addressed.

**Comment by AndrewVSutherland** [comment]
Closed vi #3980
