### ISSUE TITLE
Acknowledgements/citation knowl

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#3946]
Create a new "Acknowledgements/Citations" knowl which deletes the "data computed by" at the bottom of pages.  This new knowl can overlap the "Source" knowls, but it would be intended to describe contributions made that aren't really about the "data source" (to include e.g. student contributions).  Perhaps each section of the LMFDB could say how to cite it, rather than citing the whole database?  The Magma handbook gives a possible example of how to be more detailed/specific in how we give acknowledgements.

**Comment by AndrewVSutherland** [comment]
We added acknowledgments knowls, but I think we should also add an optional "how to cite" knowl for each section that would be displayed after the acknowledgments in the source pages and also be listed on https://www.lmfdb.org/citation (with the section identified).

Also, we should add a prominent "How to cite" link to the front page (in addition to the citation link that appears in the footer on every page but is easy for people to miss).

**Comment by BarinderBanwait** [comment]
I'm working on this ... as discussed with Drew I'll add a `multi.html` template which takes a list of kids, and replace instances of `double.html` with `multi.html`; and create lots of placeholder knowls.
