### ISSUE TITLE
Make download buttons links

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#3949]
Currently, the download links on search results pages are buttons and can't be shared by sending someone a link.  We should make them links.

**Comment by bmatschke** [comment]
That would certainly be useful, however one risk to consider is that some users might write scripts to read out large parts of the database this way.

**Comment by roed314** [comment]
It's already possible to write scripts to download things if you want to (Python's mechanize library, for example, would let you submit forms).

**Comment by roed314** [comment]
Any opinions on whether the download links should still look like buttons or like links?  I can style them to look very similar to the current version using CSS if we want to.

<img width="855" alt="Screen Shot 2020-09-20 at 9 26 02 PM" src="https://user-images.githubusercontent.com/22795/93727187-036fbd00-fb88-11ea-9216-190602dbf0de.png">
<img width="864" alt="Screen Shot 2020-09-20 at 9 27 31 PM" src="https://user-images.githubusercontent.com/22795/93727202-1bdfd780-fb88-11ea-9f10-79b28001563a.png">

**Comment by edgarcosta** [comment]
Links would be my default choice, as buttons emphasize the software package, while what we want is to emphasize the word "Download"

**Comment by roed314** [comment]
Links also require less additional CSS, which is nice.

**Comment by jwj61** [comment]
A link that says say Magma makes me think (at first) that it will take me to Magma.  It is only by process of the context and process of elimination that I deduce that it is the download.  But a button that says Magma (or something which looks like a button) makes me think right away that it will do some action, in this case download.

**Comment by JohnCremona** [comment]
I prefer the buttons.  As JJ says, the click causes an action to be taken and to me that's what buttons do while links are links to other pages.

**Comment by roed314** [comment]
Thanks for the feedback everyone.  See #4045
