### ISSUE TITLE
Number of search results

### ISSUE THREAD

**Issue by bmatschke** [LMFDB/lmfdb#3969]
Two minor issues:
1. There's a bug with download_limit: If there are too many search results, the user can obtain their count in two different ways, by clicking on either "determine the number of results" or on "at least 1000". Whether the download limit is exceeded depends so far on which link the user takes.
2. If one clicks on "determine the number of results", one needs to scroll to find the number of search results. It would be more convenient if it was shown also close to the download, such as "Download all 314 search results for...".

**Comment by AndrewVSutherland** [comment]
Addressed by #3970
