### ISSUE TITLE
Javascript in knowls

### ISSUE THREAD

**Issue by bmatschke** [LMFDB/lmfdb#3973]
I recently put javascript into a knowl, and it works nicely (all the dates and years in https://www.lmfdb.org/citation/citing are now updated to the current date (according to the user's computer), with a fallback date in case javascript is disabled).

However, it breaks knowl-show and knowl-edit, see the bottoms of https://beta.lmfdb.org/knowledge/show/content.how_to_cite and of https://beta.lmfdb.org/knowledge/edit/content.how_to_cite. 
The reason seems to be that the closing "</script>"-tag in the knowl is part of a string in the javascript variable edit_history, however browsers interpret this as a closing tag of the script that defines this variable.

A solution would be to server-side cut js-strings "<script" and "</script>" into pieces before they appear in the resulting html or js code, e.g. write "<sci"+"pt" instead of "<script".

**Comment by edgarcosta** [comment]
I would avoid having javascript in knowls.
You are trying to have a string with the current date, which is easy to do in python and use it in jinja.
Moreover, I think we are about to change the whole "how to cite".

**Comment by bmatschke** [comment]
Ok. About the current date, there's a subtlety of whether one wants a server- or client-generated answer, which might differ by a day. There are arguments for both sides...

**Comment by edgarcosta** [comment]
I agree, but one can still have a template that does the job of the knowl where we write javascript.
But I don't think having javascript makes sense at all, indeed at some point, we planned on disabling it, but we realized that would be too hard.

**Comment by edgarcosta** [comment]
@bmatschke  talked this out and reached a consensus that we don't want javascript in knowls.
