### ISSUE TITLE
The knowl  ec.q.47775be1.bottom does not appear

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#3974]
This seems to be because it uses a Cremona label in its id instead of an lmfdb label.
This could be fixed by someone with admin super powers running:
`UPDATE kwl_knowls SET id ='ec.q.47775.d1.bottom' WHERE id ='ec.q.47775be1.bottom'`

alternatively we could have  a separate system to refer to ec's in knowls by both labels, but this would require additional work as there is already a fallback to the isogeny class, so the existing mechanism for having two knows with different labels cannot be used.

The more general issue is that it would be nice to have a check that all top and bottom knowls have a valid id (so that they are referenced somewhere).

**Comment by AndrewVSutherland** [comment]
Fixed.  I agree it would be useful to have a way to search for unreferenced knowls (we do have a search for broken links, but it won't find a problem like this).
