### ISSUE TITLE
Galois Groups Search on AbVarFF_q

### ISSUE THREAD

**Issue by tdupu** [LMFDB/lmfdb#3978]
Here is a query that freaked out on me:
http://lmfdb.xyz/Variety/Abelian/Fq/?simple=yes&angle_rank=1&newton_polygon=%5B1%2F4%2C1%2F4%2C1%2F4%2C1%2F4%2C3%2F4%2C3%2F4%2C3%2F4%2C3%2F4%5D&galois_group=8T3&search_type=List

**Comment by tdupu** [comment]
If you add the dimension it stops freaking out:
http://lmfdb.xyz/Variety/Abelian/Fq/?hst=List&g=4&newton_polygon=%5B1%2F4%2C1%2F4%2C1%2F4%2C1%2F4%2C3%2F4%2C3%2F4%2C3%2F4%2C3%2F4%5D&angle_rank=1&simple=yes&galois_group=8T3&search_type=List

**Comment by roed314** [comment]
What do you mean by freak out?  Your first link seems to work for me.

**Comment by tdupu** [comment]
Oh yeah? I will try it again in a bit. It gave me an error a couple times. I will see if I can reproduce it tomorrow. Maybe it was just a one time thing and we can delete this issue. 

Best,
Taylor

**Comment by tdupu** [comment]
Ok yeah it is working. Weird. My bad. That is weird.

I was trying to get these examples of isogeny classes which were simple, angle rank 1, group 8T3 (without specifying the dimension) it was throwing an error (maybe it was taking too long or something? maybe the browser was running the search or something and I had too much going on? Is that possible?). Anyway, after I put in the dimension it started working. 

I think you should close this issue. If it happens again I will be careful to document it and I will put a new issue up with better details and make sure I can reproduce it.

**Comment by roed314** [comment]
It could have been a timeout, but that would likely have been a problem server-side rather than your browser being overused.  I'll close this, but let me know if you see it again.
