### ISSUE TITLE
Error checking in genus 2 search

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#398]
If you search for torsion structure [2,3,4], you should either find nothing,
or be told that there is nothing because that is not a valid torsion structure.

**Comment by jvoight** [comment]
I think this is still broken right now (when I search for torsion structure [2,3,4], I get curves with torsion ZZ/19*ZZ, as in the conversation on #383).  

@sanni85 was working on a more uniform and robust parsing for the search fields.  Was any progress made there, or was that for different fields?

**Comment by JohnCremona** [comment]
That is annoying!  I'm sure that the function I wrote would have caught
that as it checked then format and then that the integers were positive and
each divides the next.  I am tempted to do "git blame"....

**Comment by JohnCremona** [comment]
Drew has fixed this, no pull request yet,

**Comment by sanni85** [comment]
David Roe pull request put the parsing in (#865), some of those need fixing still, and I am looking around for problems like this. The more feedback the better.

**Comment by davidfarmer** [comment]
fixed in Drew's pull request
