### ISSUE TITLE
Use search object in Dirichlet browse page

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3983]
Except for Dirichlet characters, every section of the LMFDB on www.lmfdb.org now uses the standard search interface object so that one can, for example, do random searches within a set of search criteria, and all the browse pages have the same look and feel.  The Dirichlet browse page should be modified to use the same interface.

**Comment by alexjbest** [comment]
I started on this, my progress will be at https://github.com/alexjbest/lmfdb/tree/dirich-search when i push
