### ISSUE TITLE
Kernel fields for Dirichlet characters

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3994]
It would be useful (and consistent with the knowl heading for [related fields](https://www.lmfdb.org/knowledge/show/character.dirichlet.related_fields)) to store the kernel fields for Dirichlet characters of small order (say order up to 24, where we would expect them to be in the number fields database).

These fields need to be computed and stored for the Dirichlet characters of small order for modulus up to 10,000.  For Dirichlet chaacters of larger modulus that have very small order (e.g. 2), we might want to compute them on the fly.

**Comment by alexjbest** [comment]
There is a 10 year old Sage ticket to add this functionality https://trac.sagemath.org/ticket/9407 which has some okay looking code. I'll try and brush that up and go from there.

**Comment by jwj61** [comment]
I have not looked at the sage code.  In gp I would use polsubcyclo to get the candidates of a given degree in Q(zeta_n), then use primes where the character is trivial to eliminate all but one.

**Comment by JohnCremona** [comment]
Alex, you should not hesitate to contact Chris Wuthrich about this, I'm sure he would be very happy to work with you.

**Comment by alexjbest** [comment]
Thank you everyone for the suggestions (and code)! I'll try and compare the pari code with whats in that Sage ticket and see what works best on Friday.

**Comment by jwj61** [comment]
Given the age of the sage ticket, I doubt it will be as good as Aurel's suggestion.

**Comment by JohnCremona** [comment]
> Given the age of the sage ticket, I doubt it will be as good as Aurel's suggestion.

Agreed -- probably Withrich would never have written that code if the possibility of calling a libpari function had been available then.

**Comment by AurelPage** [comment]
Yes, I doubt that an old Sage code beats Bill's implementation.

Here is better code:
> ? conreytofield(chi) = my(G,K); [G,chi] = znchar(chi); K=charker(G,chi); galoissubcyclo(G,K);

**Comment by alexjbest** [comment]
Ok thanks everyone, I've changed the Sage ticket https://trac.sagemath.org/ticket/9407 to use Aurel's code, so thank you for that!

That is slightly orthogonal to getting these in lmfdb of course, but I think it would be sad if Sage didn't get this functionality as a by-product.

**Comment by AndrewVSutherland** [comment]
@alexjbest It looks like there are now kernel_field_poly's in the database?  Are these all polredabsed? (I doubt it, some of the are huge)  Are you planning to add field labels for the fields in the LMFDB or to just look them up by field poly at run time (that will require polredabsing the ones with degree small enough to conceivably be in the LMFDB).

**Comment by alexjbest** [comment]
Hi @AndrewVSutherland yes they are unpolredabs (some are degree >9000 😲) I'm currently on a run doing polredabs those of degree <= 47 (so may be in the db) and trying to find labels for those, its taking a little time but is maybe 30% of the way through after starting a day or so back.

**Comment by jwj61** [comment]
I don't think you should worry about getting labels.  Store them as lists of coefficients which can be looked up.  In fact, there is a function which will look it up for you and display produce a number field knowl if the field is in the database, and a description otherwise.  After you are done with polredabs, I can download those and see what fields would need to be added to the number field database (if we want to add them).

**Comment by AndrewVSutherland** [comment]
@jwj61 Agreed!  In hindsight it would have been better not to store field labels in the cmf database and in fact we could simplify our lives by changing the code to always do a lookup by polredabsed coeffs and dropping the column for the Hecke field label.  Currently the upload scripts go lookup labels for number fields, which not only wastes time, it means the links won't be there if you add number fields later.

**Comment by alexjbest** [comment]
The polredabs polynomials are now all there for kernel fields of degree <= 47, along with labels for those ones, no attempt has been made to reduce larger field polynomials.

The only thing that bothers me about dropping the labels is how fast looking up a number field in the database given the polredabs coeffs is, I assume, but do not know that, looking up by label can be much faster. At least when I was finding the labels querying the coeffs themselves felt quite slow.

**Comment by jwj61** [comment]
It should be pretty fast since the search has just one criterion and we have an index for that.

I just put in a pull request so that when you call the function formatfield from webnumberfield (which takes coefficients and produces the knowl), if you set show_poly=True as an optional argument, it will return the polynomial in latex.  Without this optional argument, it would return a knowl with a title like "Deg 12" and you have to click on the knowl to see the polynomial.

**Comment by AndrewVSutherland** [comment]
Now live on beta
