### ISSUE TITLE
citation in knowl attached to column heading displayed incorrectly

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4001]
If you click on the "cluster picture" column heading in the local information table for a genus 2 curve, e.g.

   [ https://beta.lmfdb.org/Genus2Curve/Q/1116/a/214272/1](https://beta.lmfdb.org/Genus2Curve/Q/1116/a/214272/1)

the citation reference to arXiv is formatted incorrectly (unnecessary line breaks around the brackets).  It displays find when rendered in a page where it is not inside a column header, e.g.

   [https://beta.lmfdb.org/knowledge/show/ag.cluster_picture](https://beta.lmfdb.org/knowledge/show/ag.cluster_picture)

so there is some particular interaction between how \cite is being rendered when in a table column heading.

**Comment by alexjbest** [comment]
The culprit is
```
table.ntdata a {
  display: block;
}
``
`
in style.css
