### ISSUE TITLE
Search for number fields on Galois / Abelian

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#4004]
I was surprised that I couldn't see a way to search only for Galois or only abelian number fields.
This seems like a useful feature that would probably be easiest to implement by adding a couple of columns to `nf_fields` or `nf_fields_extras` as currently it looks like these properties are computed on the fly given the Galois group.
Implementing this as a fancy query is probably also not too bad.

**Comment by jwj61** [comment]
You would not want to put it in extras.  Part of the reason for separating it into two tables is that we search on one, but then can pull data for pages from the other.

**Comment by jwj61** [comment]
I should also say that one can search for several Galois groups by listing them in the Galois group box.  If you specify say 6T2, then it only matches sextic S3 fields, not the cubic ones.  So, one could enter C2,C3,C4,C5,C6,6T2 and get all of those Galois groups.

**Comment by roed314** [comment]
I've added the relevant data on beta (columns `is_galois`, `gal_is_cyclic`, `gal_is_abelian` and `gal_is_solvable` of `nf_fields`).  Things to do:
* Add search fields to the number field page to search on these
* Push the data to prod.
* @jwj61 should update his number field scripts to include these columns when he adds new fields.

**Comment by jwj61** [comment]
I updated the prep/import files.  Of course it is untested until we have some new fields to add.

**Comment by bebr117** [comment]
I'm gonna take a look at this.

**Comment by bebr117** [comment]
I noticed that in the database, Galois groups are defined and given for non-Galois extensions (as the Galois group of the Galois closure). Should searches for extensions with Abelian/Solvable Galois groups include non-Galois extensions?

**Comment by alexjbest** [comment]
I would say no, normally abelian number field in books/papers refers to Galois + abelian galois group only so I think people might get confused if we break with that convention.

**Comment by roed314** [comment]
If the Galois closure L of a field K has abelian Galois group then L=K (since K corresponds to a subgroup with trivial core (intersection of all conjugates), implying that it's just the trivial group).  So the question about abelian groups is moot.

I think that it's reasonable to have any quartic number field show up as having solvable Galois group, so I would say that searches for solvable extensions should include non-Galois ones.

**Comment by JohnCremona** [comment]
Nice observation!  If L is Galois abelian then all subfields are also Galois so L isn't the Galois closure of any proper subfield.

**Comment by roed314** [comment]
Yes, that's probably an easier way to see it. :-)

**Comment by alexjbest** [comment]
Looks like I misread and answered a different question with my comment, sorry!

**Comment by jwj61** [comment]
The data is there, and there is currently a search for Galois fields.  The question is whether we want to push this further.

One idea is to change the yes/no selector for "Is Galois" to a dropdown with options of Cyclic, Abelian, Galois, Solvable, Any.  Until we have extensions of degree 60, the results of one are always included in the results of the next so one would not need to search for these things independently.  Maybe the label next to the dropdown could be "Field is ...", or something like that.
