### ISSUE TITLE
Knowl link suggestions should check singular form of plurals

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4041]
The link suggestion feature of the knowl editor could easily be made more useful if it checked not only for exact terms that appear in the text, but also the the terms that appear when you remove the trailing s from words (I think it would be safe to just do this blindly, I'm not asking the code to identify plural nouns).

For example, if you write a knowl containing the phrase "elliptic curves" it would be great if it would give the same link suggestion that it currently does for "elliptic curve".

**Comment by JohnCremona** [comment]
+1  I sometimes mistype on purpose to get the link put in automatically, then correct it later.  I hope.

**Comment by alexjbest** [comment]
There are some pluralizer libraries on pip already like pluralize and inflect, so adding a lightweight dependency should get us things like isogeny -> isognies for free.

**Comment by AndrewVSutherland** [comment]
@alexjbest even better (but not essential).

**Comment by AndrewVSutherland** [comment]
Addressed by #6232
