### ISSUE TITLE
Missing Maass forms

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#4048]
The odd partner of this Maass form:

https://beta.lmfdb.org/ModularForm/GL2/Q/Maass/5411a4a9acf7560ce8a6f65e

and the odd partner for this one:

https://beta.lmfdb.org/ModularForm/GL2/Q/Maass/5411a4abacf7560ce8a6f665

are missing from the database.

I am basing that on an assumption that the Maass forms on level 63 occur in pairs,
just like all the other multiples of 9.

I can check the odd partners after I make them, so we will not end up with wrong
data.

There also appear to be 8 missing partners in Level 72, one in level 81, one in level 90,
and one in level 99.

The missing forms can be seen by scanning across the rows in this picture:

https://beta.lmfdb.org/ModularForm/GL2/Q/Maass/BrowseGraph/1/100/0/4/

**Comment by davidfarmer** [comment]
Levels 49 and 98 also appear to occur in pairs.  But if that is always true,
then there are 3 missing in level 49 and 2 missing in level 98.

96 seems okay.

**Comment by AndrewVSutherland** [comment]
Are you planning to compute the missing forms?

**Comment by davidfarmer** [comment]
Yes.  Is there time pressure to do that?

**Comment by AndrewVSutherland** [comment]
@davidfarmer I don't think so; we make no claims about completeness, if there was data that was actually wrong (as opposed to missing)  I would regard that as more urgent.

**Comment by AndrewVSutherland** [comment]
I'm going to close this issue, as we no longer have data for the non-squarefree levels where this is relevant (and we do now make claims about completeness, so if any data appears to be missing, an issue should be raised).
