### ISSUE TITLE
Do not make L-function friend link for non-primitive Dirichlet characters

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#405]
For example:

/Character/Dirichlet/68/35

**Comment by nmascot** [comment]
Working on it

**Comment by nmascot** [comment]
Submitted pull request #529.

I'm surprised it cannot be merged automatically as I have changed almost nothing.

**Comment by davidfarmer** [comment]
I already did this in a pending pull request.

**Comment by davidfarmer** [comment]
Conflict because I fixed it in a different pull request.
