### ISSUE TITLE
Download Bianchi modular form data

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4053]
We need to provide a download option for Bianchi modular forms.

**Comment by AndrewVSutherland** [comment]
Hilbert modular forms already provides this capability and might be a good model to follow.  I think it would be enough to just provide a download eigenvalues option, since I don't think these is a built-in Bianchi modular form object in Magma or sage (but @JohnCremona should correct me if I am wrong about this).

**Comment by BarinderBanwait** [comment]
@AndrewVSutherland It looks like there is a ['ModFrmBianchi'](https://magma.maths.usyd.edu.au/magma/handbook/modular_forms_over_imaginary_quadratic_fields) object in Magma. From the introduction there, "Technically, ModFrmBianchi is implemented as a subtype of ModFrmHil", so a 'Modular form to Magma' option may also be feasible. I couldn't find it in sage however. (If nobody else is looking into this, I'd be happy to take it on as my first issue.)

**Comment by AndrewVSutherland** [comment]
@BarinderBanwait I think there has been some work started on implementing a download option for the eigenvalues, but I don't where that stands and it won't address the question of a download to magma option, so I would say please go ahead.  If you are available to join us for part of our LMFDB Friday session tomorrow we could coordinate there (I'll send you an email with the Zoom link and an invitation to the Zulip cha).

**Comment by BarinderBanwait** [comment]
Sure, I'd be happy to join tomorrow (received the zulip+zoom links, thanks!)

**Comment by BarinderBanwait** [comment]
PR opened - #4123
