### ISSUE TITLE
Provide option to display more a_p for Bianchi modular forms

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4054]
By default only 25 a_p are shown, but there are more in the database.  We should provide the user the option to see more (as in classical modular forms, for example).

**Comment by AndrewVSutherland** [comment]
I believe Brian Reinhart is planning to implement this (but if not I will take care of it on Friday).

**Comment by bebr117** [comment]
Now that my PR has been approved, this issue should be closed.
