### ISSUE TITLE
Add search option for elliptic curves with potentially good reduction everywhere

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4055]
It would be nice to have a search option for elliptic curves over number fields (including Q) that have potentially good reduction everywhere (equivalently, integral j-invariants).  The easiest way to accomplish this would be to add a boolean flag which could easily be populated using the local data we already store that includes the valuation of the denominator of the j-invariant.

One could also ask for the same thing for genus 2 curves over Q and/or their Jacobians.

**Comment by JohnCremona** [comment]
I have already added this to my ecnf data upload script and so it will be there as soon as I have uploaded the data for issue #3900. I have called the new column 'potgr', so if you want to be called something else, say so now!

Doing this or EC/Q is separate.  A script to do this would be trivial to write, after adding a column called 'potgr' of type boolean, fill it like using this hint:

sage: c = db.ec_curves.lucky()
sage: all([ld['ord_den_j']==0 for ld in c['local_data']])
False

**Comment by roed314** [comment]
It took me about 15 seconds to figure out what `potgr` stood for; maybe `pot_good` would be clearer and not too long?  Or we could go all the way to `potentially_good_reduction`.

**Comment by edgarcosta** [comment]
We no longer pay for long field names, thus I would go for `potentially_good_reduction`

**Comment by JohnCremona** [comment]
> We no longer pay for long field names, thus I would go for `potentially_good_reduction`

Done (in my scripts, no new columns yet).  I'll use the same approach for the other new columns, e.g. instead of "ss" I'll have "supersingular" and so on.

**Comment by JohnCremona** [comment]
I suggest implementing this now, as well as #1483 (search by size of isogeny class) and maybe more.  The relevant new columns for possible new search options are:
    - semistable (boolean)
    - potential_good_reduction (boolean) 
    - class_size (int)
    - sha (int) (analytic sha, exists for most curves)
    - analytic_rank (int) (exists for most curves)

**Comment by JohnCremona** [comment]
I had forgotten this in my new ECQ schema, so I am adding it now and then I'll add the search option to the relevant branch.

**Comment by JohnCremona** [comment]
This is already available over Q, and the ec_nfcurves tables has a column 'potential_good_reduction', so I'll implement the option for ECNF too now.
