### ISSUE TITLE
Rewrite does not accept sep

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#4063]
In backend/table.py, rewrite hard codes | as the separator, but there is at least one transitive group name which contains that character, so rewrite cannot be used on that table.

**Comment by edgarcosta** [comment]
Do you think the tab (for rewrite) would work for every table on LMFDB?

**Comment by jwj61** [comment]
Probably, but why not just make it an option like it is for related functions?

**Comment by roed314** [comment]
I think it's easy to just change the rewrite method to extract a separator character.

**Comment by edgarcosta** [comment]
Agree

**Comment by jwj61** [comment]
Do you mean from arguments it is passed?  That would be easy.  If you mean from somewhere else, then it does not seem possible -- you don't know what the modification function is going to do to the entries.

**Comment by roed314** [comment]
See #4064.
