### ISSUE TITLE
Level of a newspace is malformed

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#4065]
On  https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/13/2/ I see 
<img width="363" alt="Screen Shot 2020-09-28 at 18 07 22" src="https://user-images.githubusercontent.com/1688533/94491083-83fc7200-01b5-11eb-9b2f-2a096eb77569.png">
instead of Level: N = 13

**Comment by edgarcosta** [comment]
https://github.com/LMFDB/lmfdb/blob/master/lmfdb/utils/utilities.py#L581 ?

**Comment by AndrewVSutherland** [comment]
@edgarcosta That line should not be causing a problem (it only adds math mode parens if enclose is set to true and it should not even be reached in this case because x is prime).  And the level displays fine on the newform page.  My guess is the newspace page is adding an extra pare of parens.

**Comment by edgarcosta** [comment]
Indeed,
https://github.com/LMFDB/lmfdb/blob/master/lmfdb/classical_modular_forms/templates/cmf_full_gamma1_space.html#L12

**Comment by AndrewVSutherland** [comment]
Fixed in PR #4066
