### ISSUE TITLE
Show inducing primitive character

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#4072]
When a Dirichlet character is not primitive, for example:
     https://beta.lmfdb.org/Character/Dirichlet/6/5
in addition to saying it is not primitive, it would be good to link to the inducing character.

This may be partly what was meant by issue #968

**Comment by AndrewVSutherland** [comment]
This should be easy to do, the label of the orbit of the inducing primitive character is stored in the database and for individual characters this is not hard to compute (in fact knowing the orbit would reduce it to checking values on generators).
