### ISSUE TITLE
ECNF browse page broken

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#4085]
The URL https://www.lmfdb.org/EllipticCurve/browse/ causes an error.  This is reached by the link "all available fields" on the top page https://www.lmfdb.org/EllipticCurve/ and worked until some recent changes.

**Comment by JohnCremona** [comment]
It just needs the parenthese removing from ecnf_summary on line 5 of the template ecnf-stats.html.  I'll fix this right away.

**Comment by AndrewVSutherland** [comment]
The fix is now live.

**Comment by JohnCremona** [comment]
Thanks!
