### ISSUE TITLE
Dirichlet character breadcrumbs

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#410]
The breadcrumbs on this page tend to overlap the "Feedback" link.
It is worse if you are logged in.

http://beta.lmfdb.org/Character/Dirichlet/5/4

Things would be slightly improved if the text in the breadcrumbs were shortened to
"mod 5" and "#4".

**Comment by nmascot** [comment]
Working on it

**Comment by nmascot** [comment]
Submitted pull request #487.

**Comment by AndrewVSutherland** [comment]
This appears to have been fixed by pull request #487.
