### ISSUE TITLE
Extra parentheses

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#4117]
Trivial matter, but still: look at
  http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/81/2/c/
and scroll down to the Hecke polynomial at 7.  Why the extra parentheses?  (It's harder to read as written.)

**Comment by tomgrubbmath** [comment]
It seems like this is maybe just an oversight in the interaction between the "display_hecke_polys" function in lmfdb/lmfdb/classical_modular_forms/web_space.py and the "list_factored_to_factored_poly_otherorder" function from lmfdb/lmfdb/utils/utilities.py .  I can try to fix it.

**Comment by AndrewVSutherland** [comment]
This was addressed in #4217 (and we no longer show Hecke charpolys for spaces, only for newforms)
