### ISSUE TITLE
p-adic fields statistics broken

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#4136]
Just what the title says.

I saw a mention of it in a pull request, but it there does not seem to be an issue for it.

As far as I can tell, it happened when there were changes to statstable.py for Bianchi modular form statistics.  Now in a list of headers which is supposed to be just values of "n" or "e" it is picking up Galois groups.

**Comment by AndrewVSutherland** [comment]
David Roe is aware of the issue and is working on it.  We are holding off pushing to web until this is fixed.

**Comment by roed314** [comment]
Yep, I'm looking at this now.
