### ISSUE TITLE
Level and level norm of Bianchi modular form

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#4144]
On this page

https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.8.1/48816.5/a/

near the top in the middle it has
     Level          48816.5 = $ \left(-156 a + 12\right) $
The 48816.5 looks not right to me, or it is in some notation that is not
explained in the Level knowl.

Also, 48816 is the level norm, which is mentioned in the properties box
but not in the body of the page.

**Comment by AndrewVSutherland** [comment]
I believe 48816.5 is the label of the ideal as defined in https://arxiv.org/abs/2005.09491 and explained in the knowl https://beta.lmfdb.org/knowledge/show/nf.ideal_labels, so I don't think there is an error here, we just need to update the level knowl to include a link to nf_ideal_labels, but @JohnCremona can confirm.

**Comment by AndrewVSutherland** [comment]
I have confirmed that the ideal label is correct.  I will add the level norm to the page and move the label of the BMF to the top of the properties box where it should be (I'll just add this to #4143 now).  I can also edit the level knowl.

**Comment by AndrewVSutherland** [comment]
@davidfarmer This has now been addressed on https://blue.lmfdb.xyz/ModularForm/GL2/ImaginaryQuadratic/2.0.8.1/48816.5/a/ as part of #4143.  If you would be willing to review the knowl 

https://beta.lmfdb.org/knowledge/show/mf.bianchi.level

which I just edited, that would be great!

**Comment by JohnCremona** [comment]
The knowl was reviewed, so closing.
