### ISSUE TITLE
Lattice page typos

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#4145]
From the feedback page:

Hi, 
the second line on the URL  https://beta.lmfdb.org/Lattice/ reads as: "The largest class_number is 56, the largest dimension is 24, and the largest dimension is 191,102,976." The second "dimension" should be replaced by "determinant". 

In the source code, the only thing to do, I think, is to replace 
"... and the largest <a title="Determinant of an integral lattice [lattice.determinant]" knowl="lattice.determinant" kwargs="">dimension</a> is 191,102,976" 
by 
"... and the largest <a title="Determinant of an integral lattice [lattice.determinant]" knowl="lattice.determinant" kwargs="">determinant</a> is 191,102,976".

By the way, it is "unattractive" to read "class_number" (with underscore) instead of "class number". 
Thanks a lot

**Comment by AndrewVSutherland** [comment]
These typos were introduced when stats were added.  I just added a commit to #4143 that fixes them (as can be seen at https://blue.lmfdb.xyz/Lattice)

**Comment by roed314** [comment]
Thanks Drew.
