### ISSUE TITLE
http://lmfdb.org/ModularForm/ produces a page not found

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#4162]
The url http://lmfdb.org/ModularForm/ produces a page not found, whereas the same url without the trailing /  i.e. http://lmfdb.org/ModularForm does not.

**Comment by edgarcosta** [comment]
https://stackoverflow.com/questions/33241050/trailing-slash-triggers-404-in-flask-path-rule

**Comment by jwj61** [comment]
Can we do the global app.url_map.strict_slashes = False ?  There may be other places where this is an issue.

**Comment by edgarcosta** [comment]
I think so

**Comment by AndrewVSutherland** [comment]
Fixed in #4174
