### ISSUE TITLE
No links in EC/Q stats tables

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4166]
Unlike all other stats pages in the LMFDB, the stats page

    https://beta.lmfdb.org/EllipticCurve/Q/stats

has no links to search results in any of the tables (even though it does appear to be using the new stats framework).

**Comment by roed314** [comment]
It's using the count functionality from the backend, but it's not using any of the front end statistics infrastructure (the `StatsDisplay` object from `lmfdb.utils.display_stats` or the `display_stats.html` template).  We could convert it to do so (though the general infrastructure doesn't support the cool layout of the torsion structure table), or manually add the links to the `lmfdb/elliptic_curves/templates/ec-stats.html` template.
