### ISSUE TITLE
Refine search box knowls open in weird places

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#4179]
On
https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/?hst=List&level=67&weight=2&search_type=List

clicking on bad p. or char causes a knowl to open that misformats the entire table of refine search boxes, this does not happen for  primitive character or Nk^2 so I believe it is the presence of a dropdown box next to the knowl that breaks it.

**Comment by edgarcosta** [comment]
yup, it is inside of a div, hence doesn't try to open it in the next row of the table :(

**Comment by alexjbest** [comment]
Just removing the div and setting  style="display: flex; justify-content: space-between;" on the td instead seems to work and not require complicating the knowl javascript further.
