### ISSUE TITLE
Torsion growth for elliptic curves / Q garbled

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#4186]
The table for elliptic curve torsion growth over Q is malformatted (checked on chrome and safari)
on the page

https://www.lmfdb.org/EllipticCurve/Q/27/a/4
i see 
<img width="707" alt="Screen Shot 2020-10-26 at 21 56 18" src="https://user-images.githubusercontent.com/1688533/97247476-253b1000-17d6-11eb-9a2f-9cecf0e97c3b.png">

**Comment by AndrewVSutherland** [comment]
Now fixed on beta (and will shortly be fixed on prod)
