### ISSUE TITLE
Compute and verify functional equation for L-functions

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#419]

**Comment by davidfarmer** [comment]
Can I close this, because L-function data will be computed rigorously before inserting into the database?

**Comment by JohnCremona** [comment]
On 28 March 2016 at 17:45, davidfarmer <notifications@github.com> wrote:

> Can I close this, because L-function data will be computed rigorously
> before inserting into the database?
>

Ask Andy as he is the one doing those computations.
