### ISSUE TITLE
EllipticCurve URL fails the banana test

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4190]
Malformed URLs with the prefix https://www.lmfdb.org/EllipticCurve/ cause server errors when they should give 404 errors.

For example  https://www.lmfdb.org/EllipticCurve/banana/ causes a server error, whereas https://www.lmfdb.org/ModularForm/GL2/banana and https:/www.lmfdb.org/Genus2Curve/banana give 404s (on beta, which I'm not sure is what we want but is better than a server error).

The main reason to fix this is so we don't get cruft showing up in the flasklog.

**Comment by edgarcosta** [comment]
See also #4019

**Comment by AndrewVSutherland** [comment]
Fixing #4019 will fix this, working on it now
