### ISSUE TITLE
Limit download_qexp requests for elliptic curves

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4194]
Requests like

https://www.lmfdb.org/EllipticCurve/Q/download_qexp/37.a1/9000000

(which showed up in the flasklog) put a heavy CPU load on the server and eventually lead to a 502.  I suggest capping these at 10^5.

**Comment by JohnCremona** [comment]
I would be even harsher. This is *not* a download of stored data (we only store ap for p<100) but a request to compute ap.  It should probably be disabled.  Anyone in a position to use these ap would easily be able to compute them.

**Comment by AndrewVSutherland** [comment]
@JohnCremona I think we want to keep the download q-exp link, which gives the first 1000 an.  We could just remove the bound and always make it give 1000, but this would be less than the number we provide for the corresponding modular forms for N up to 10000 (we provide 3000), which seems a little weird.  For CMFs we always provide at least 30*sqrt(N), which matches the number of a_n we use when computing the L-function.  Allowing up to 10^5 would be well above this and still takes less time than it takes to render the page.

**Comment by JohnCremona** [comment]
OK fair enough -- but then can we open a new issue to increase the number if ap and an stored?

**Comment by AndrewVSutherland** [comment]
I think this is the rare case where I would argue that its OK to compute them on the fly, since we are never searching on them and it can be done quickly and reliably.  @edgarcosta do you have an opinion about this?

**Comment by edgarcosta** [comment]
I agree with you.
Indeed, is impressive how fast we return
https://www.lmfdb.org/EllipticCurve/Q/download_qexp/37.a1/10000

**Comment by JohnCremona** [comment]
I submit! With the sensible cap of course.
