### ISSUE TITLE
Add charpolys of Hecke operators

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4196]
The "Hecke characteristic polynomials" tables that appear on the newform and newspace pages currently display L-polynomials, but they should be displaying charpolys of T_p (acting on V_f), which is N_{K_f/\mathbb Q)(T-a_p), or equivalently, minpoly(a_p)^[K_f:Q(a_p)].  It probably makes sense to only do this for newforms of dimension <= 20 where we have exact a_p's.  

The charpolys could be computed on the fly, but (especially in the larger weight cases) it probably makes sense to precompute them.

**Comment by BarinderBanwait** [comment]
so they can be computed from the existing a_p values, and added as a new column in the appropriate table (`db.mf_newforms` or `db.mf_hecke_nf`)? I haven't worked with the backend so far, so i'd be happy to try this

**Comment by BarinderBanwait** [comment]
I've got the data file ready, but I'm having issues loading it.

I first tried reloading it to the table we created on Friday (`db.mf_hecke_charpolys`), but it complained that the types are invalid:

```
ValueError: Invalid types: p should be integer instead of smallint, charpoly_factorization should be numeric[] 
instead of jsonb
```

The first five lines of the file I have are:

```
hecke_orbit_code|p|charpoly_factorization
bigint|smallint|jsonb

201326593|2|{{{24,1},1}}
201326593|3|{{{-252,1},1}}
```

So I changed the second line of the file to `bigint|integer|numeric[], and tried reloading again, but this gave the following error:

```
DataError: malformed array literal: "{{{24,1},1}}"
DETAIL:  Unexpected array element.
CONTEXT:  COPY mf_hecke_charpolys_tmp, line 1, column charpoly_factorization: "{{{24,1},1}}"
```

At this point I created a new table with differently declared types, thinking this might be relevant:

```
db.create_table('mf_hecke_charpolys_again', search_columns={"bigint":"hecke_orbit_code", "smallint": "p",
"jsonb":"charpoly_factorization"},label_col=None)
```

However, reloading this new table with the original datafile also gave a DataError:

```
DataError: invalid input syntax for type json
DETAIL:  Expected string or "}", but found "{".
CONTEXT:  JSON data, line 1: {{...
COPY mf_hecke_charpolys_again_tmp, line 1, column charpoly_factorization: "{{{24,1},1}}"
```

(I tried to head the existing `mf_hecke_lpolys` files to see how it's done there, but I don't have read permissions for them.)

**Comment by AndrewVSutherland** [comment]
@BarinderBanwait I think I gave you bad advice, the column charpoly_factorization does need to be jsonb because postgres wants array types to n-dimensional arrays (for some value of n), not nexted lists.  So as in mf_hecke_lpolys.txt (which you should now be able to read) charpoly_factorization needs to be jsonb and the data then needs to use square brackets rather than curly brackets to denote lists.

I just changed the schema for mf_hecke_charpolys and the file mf_hecke_charpolys.txt accordingly and was able to reload.  Sorry for the confusion!

The next step is to change the code to display these (everything you need to do this should already be there, it's just a matter of renaming things from hecke_lpolys to hecke_charpolys and uncommenting the lines in the various templates that are meant to display tables of charpolys on the newform and newspace pages).

**Comment by BarinderBanwait** [comment]
Aah, yes I see the lpolys file now - thanks for the explanation @AndrewVSutherland !

I'll get onto displaying these polynomials.

**Comment by AndrewVSutherland** [comment]
Following up on my comment on #4217, I think we should just show these on the newform pages, the added value to showing them on the newspace pages is negligible (and they would be unavailable in any spaces where there is a newform of dim > 20 anyway)

**Comment by BarinderBanwait** [comment]
I can update the PR to do this - it should just be a quick change to `display_hecke_polys` in `web_space.py`.

I did however stumble upon [the following comment](https://github.com/LMFDB/lmfdb/issues/2759#issuecomment-547691732) of @jvoight from over a year ago, suggesting that the absence of Hecke charpolys for newspaces will be missed:

> Agree with this!  Especially for spaces, this was one of the first things that people tabulated, and it is a nice snapshot of all the forms in a space.
