### ISSUE TITLE
In search results, sort by degree, then discriminant, then conductor norm

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#421]
- Sort by degree, discriminant, then conductor norm.

**Comment by jwbober** [comment]
What search results are these? Hilbert modular forms?

**Comment by JohnCremona** [comment]
On 31 October 2015 at 20:35, Jonathan Bober <notifications@github.com>
wrote:

> What search results are these? Hilbert modular forms?
>
Yes -- but I did implement what is suggested here 2 weeks ago and that was
merged quite recently, so the issue can be closed.  See pull request #401
(which has a lot of other stuff in it so it is not so surprising that this
point was not noticed).
