### ISSUE TITLE
ec_nfcurves needs copying to web

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#4213]
I just uploaded the BSD data for the 10 quintic fields for which it was missing.  We now have complete BSD data over all dfields of degree <=5 (apart from a small number of imaginary quadratics fields with large discriminant where it is not going to happen, and with the usual proviso that in some cases we only have rank bounds).

Please can we copy the table ec_nfcurves to web?  Thanks.

**Comment by AndrewVSutherland** [comment]
Copying now.

**Comment by AndrewVSutherland** [comment]
Done..  @JohnCremona can you take a look and make sure the data looks correct on www.lmfdb.org and close this issue if it does?

**Comment by JohnCremona** [comment]
Will do.

**Comment by JohnCremona** [comment]
Looks good -- stats are also updated, good.
