### ISSUE TITLE
Need to catch errors better for intermediate fields

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#4224]
From the feedback page:

When in the `Intermediate fields' entry of the `Number fields' database I entered multiple polynomials (namely `x^2-3,x^2-7') I got a server error.

**Comment by jwj61** [comment]
It is set up to only search for a single intermediate field, so the parsing should catch this and give an error message instead of a server error.

**Comment by jwj61** [comment]
Fix is merged into master

**Comment by edgarcosta** [comment]
The fix is live: https://www.lmfdb.org/NumberField/?subfield=x%5E2-3%2Cx%5E2-7&search_type=List

I'm not sure if we need to email someone

**Comment by jwj61** [comment]
Now when something comes in through the feedback page, I give them a link to the corresponding issue.  It is up to them to see if they want to follow it or not.
