### ISSUE TITLE
Malformed latex equations for elliptic curves over number fields

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#4235]
Example:  https://www.lmfdb.org/EllipticCurve/2.2.5.1/2581.2/a/1 has malformed latex equation. In this case it is because the generator \phi is concatenated with x, and this error is in the database entry so it is not a code problem. 

I think this was introduced during my most recent database upload.  To save space I removed spaces in the latex string (see line 925 of https://github.com/JohnCremona/ecnf-data/blob/master/sage/files.py) which in some cases causes problems.  In this case the stored string is

"y^2+xy+\\left(\\phi+1\\right)y=x^{3}+\\phix^{2}-9\\phix-4\\phi-10"

while Sage's latex(E) actually gives

y^2 + x y + \left(\phi + 1\right) y = x^{3} + \phi x^{2} - 9 \phi x - 4 \phi - 10

This will be tedious but trivial to fix (in the database).  Meanwhile I think that a code fix replacing each 'x' by '{x}' and similarly for 'y' should fix it at least temporarily, and probably faster.

**Comment by JohnCremona** [comment]
OK, that does work.  Compare the above link with http://localhost:37777/EllipticCurve/2.2.5.1/2581.2/a/1.  For an example to show that braces around y are also needed, look at https://www.lmfdb.org/EllipticCurve/2.2.5.1/31.1/a/5 and http://localhost:37777/EllipticCurve/2.2.5.1/31.1/a/5 .  (This is not specific to field 2.2.5.1.)  PR coming up.

**Comment by JohnCremona** [comment]
I have corrected the data one beta for 2.2.5.1 and also realised that this *is* the only field affected, since it's the only one for which the generator has a name which is a macro (\phi). Almost all other fields use a as generator (and i for 2.0.4.1) which don't cause problems when concatenated with x.

Please copy ec_nfcurves to prod, and them close this issue.  Thanks (and apologies for the error).

**Comment by AndrewVSutherland** [comment]
Copying now.

**Comment by AndrewVSutherland** [comment]
Done.
