### ISSUE TITLE
Elliptic curve completeness information bug

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#4239]
From the feedback page:

I tried to go to the page 

https://www.lmfdb.org/EllipticCurve/Q/Completeness

 and it gave the error "This information can only be displayed with a more recent version of the LMFDB."

(This error comes up if the summary function is not available, so it looks like a coding bug.)

**Comment by JohnCremona** [comment]
I'm looking at this now

**Comment by alexjbest** [comment]
Looks like this is happening because the function elliptic_curve_summary was deleted in #4178 
the knowl content is just 
```
{% if elliptic_curve_summary is defined %}
  {{elliptic_curve_summary()| safe}}
{% else %}
  This information can only be displayed with a more recent version of the LMFDB.
{% endif %}
```
upon edit after all

**Comment by JohnCremona** [comment]
Well spotted, Alex!  Can you fix this then?

This absolutely should not have happened.  How can we delete a function which is needed and not notice? There should be a test for this specific page as part of the fix, and we should also collect a list of the functions called in knowls in this way and have tests for every one of them.  

The relevant deleted lines from the (completely deleted) file ec_stats.py are

def elliptic_curve_summary():
    counts = get_stats().counts()
    return r'The database currently contains the complete Cremona database.  This contains all %s <a title="Elliptic curves [ec]" knowl="ec" kwargs="">elliptic curves</a> defined over $\Q$ with <a title="Conductor of an elliptic curve over $\Q$ [ec.q.conductor]" knowl="ec.q.conductor" kwargs="">conductor</a> at most %s.' % (str(counts['ncurves_c']), str(counts['max_N_c']))


@app.context_processor
def ctx_elliptic_curve_summary():
    return {'elliptic_curve_summary': elliptic_curve_summary}

and the correct text will be returned by ECStats.summary().  It's also necessary to have the function registered using the context_processor stuff.

**Comment by alexjbest** [comment]
Yeah I tried, but I can't get it to work and I have no idea why. I'm trying to pass the ECStats().summary through to the page via `info` but nothing I did made the knowl appear correctly.

**Comment by JohnCremona** [comment]
OK, I think I know how to do this so let me try.
