### ISSUE TITLE
Mismatch on L-function rank

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#4246]
https://beta.lmfdb.org/L/EllipticCurve/2.0.3.1/120000.1/b/ has the smallest first zero in the database.  It is shown as having analytic rank 0, but one of its factors, https://beta.lmfdb.org/L/EllipticCurve/Q/600/b/, has analytic rank 1.  Similarly, https://beta.lmfdb.org/L/EllipticCurve/2.2.92.1/98.1/f/ is shown as having analytic rank 0 but its factor https://beta.lmfdb.org/L/EllipticCurve/Q/7406/a/ has analytic rank 2.

**Comment by JohnCremona** [comment]
That is worrying. Can someone rerun Magma's analytic rank on those two curves?  That might help decide if the problem is in (my) data processing or Magma's computation. NB I did find a bug in magma's a.r. function but for curves with rational cm where the L function is a square but they forgot to double the rank after computing it for the lower degree one.

**Comment by AndrewVSutherland** [comment]
In both cases there are zeros suspiciously close to the critical point (withing 10^-20), so I expect that this is just a precision issue in the L-function computations for the elliptic curves over quadratic fields.  Note that in the first example both factors have analytic rank 1, so the analytic rank should be 2, which agrees with the sign of the functional equation.

I'm sure the analytic ranks for the factors are correct (they were computed twice, both for the elliptic curves and for the modular forms, in two different ways, and if they are wrong then BSD is false).

**Comment by edgarcosta** [comment]
Without a doubt, the issue is on the L-functions of the elliptic curves over the number fields.

**Comment by AndrewVSutherland** [comment]
@roed314 @edgarcosta we should check for any other zeros that are suspiciously close to the critical point, if there was a precision issue in the L-function computations for the elliptic curves over quadratic fields there may well be other problematic cases.

**Comment by edgarcosta** [comment]
That is how we find them: https://teal.lmfdb.xyz/L/?hst=List&z1=0.-0.000001&search_type=List

**Comment by AndrewVSutherland** [comment]
@edgarcosta Thanks, the others all look plausible to me.

**Comment by JohnCremona** [comment]
The last one in that list is attached to BMF https://teal.lmfdb.xyz/ModularForm/GL2/ImaginaryQuadratic/2.0.3.1/120000.1/b, on whose web page you can see that the analytic rank is "\ge2, even" becuase I *proved* that the central L-value is 0 *exactly* (no floating point computation involved whatsoever), and the sign of the functional equation is +1.

I thought it worth pointing this out since I do not know how rigorous Magma is when you ask for the analytic rank of an elliptic curve.  In the case of those attached to BMFs we know whether the analytic rank is or is not 0 without any further computation.  The column 'Lratio' in bmf_forms holds a rational number (as a string, sorry) which is '0' if and only if the analytic rank is positive, and the column 'sfe' (sign of functional equation) holds an integer, +1 or -1.

**Comment by edgarcosta** [comment]
I have finally managed to recompute both L-functions (without using the data on LMFDB), and the new computations agree with the ecnf data and the primitive factors:
```
Date:   	2020-11-25 00:49:30
Starting:	2.2.92.1-98.1-f
	using p <= 126443
	Rank = 2
	Epsilon = (1 + 0j)  +/-  (8.06e-109, 1.27e-54j)
	First non-zero Taylor coeff = 4.0886578422409049272 +/- 6.6316e-49
	First zero = 1.6634064405646445988 +/- 3.9443e-31
Done:   	2.2.92.1-98.1-f	took   2.54s
Date:   	2020-11-25 00:49:33

Date:   	2020-11-25 00:49:33
Starting:	2.0.3.1-120000.1.b
	using p <= 144280
	Rank = 2
	Epsilon = (1 + 0j)  +/-  (8.66e-109, 1.32e-54j)
	First non-zero Taylor coeff = 4.9663700474099135208 +/- 7.8269e-49
	First zero = 1.6300445649643069145 +/- 3.9443e-31
Done:   	2.0.3.1-120000.1.b	took   2.62s
Date:   	2020-11-25 00:49:36
```

Tomorrow I will manually fix these rows, but now I wonder what other rows might be messed up, as I don't really know what triggered this bug. We have rewritten and fixed several bugs in the past year, that might or might not have been present in the original version.
The only thing I can confirm is that it seems to be fixed unless it is a once in blue moon kind of bug.

**Comment by edgarcosta** [comment]
I have fixed the data on both databases.

Here is the code for posteriority, in case I ever wonder what I did:
```
default_prec = 300
CCC = ComplexBallField(default_prec)
RRR = RealIntervalField(default_prec)
def from_arb2(lower, upper, exp):
    return from_acb2(lower, upper, exp, 0, 0, 1).real()

def from_acb2(lower_real, upper_real, exp_real, lower_imag, upper_imag, exp_imag):
    return CCC(RRR(lower_real, upper_real)*2**exp_real, RRR(lower_imag, upper_imag)*2**exp_imag)

# we should store middle point as numeric
# and the radius as a float (originally 30 bits)
def arb_to_numeric(elt):
    u = str(elt.upper())
    l = str(elt.lower())
    out = ""
    for i, d in enumerate(u):
        if d == l[i]:
            out += d
        else:
            break
    return out

def read_zero(elt):
    l, u, a = elt
    assert u - l <= 2
    arb_zero = from_arb2(*elt).real()
    two_power = 2**(-a-1)
    int_zero = ZZ(arb_zero*two_power)
    zero = RealNumber(int_zero.str()+".")/two_power;
    zero_after_string = (RealNumber(zero.str()) * two_power).round()
    assert zero_after_string  == int_zero, "zero_after_field = %s\nint_zero = %s" % (zero_after_string, int_zero,)
    return zero

newdata = """EllipticCurve/2.2.92.1/98.1/f:2:[6416230309233186486042607697764920410731141461731307044441, 6416230309233186486042607697764920410731141461733388416047, -190]:[[4217236345610548641764373200719, 4217236345610548641764373200721, -101], [6205360396983364399865563101777, 6205360396983364399865563101779, -101], [6300583031153860258205330339031, 6300583031153860258205330339033, -101], [8911579544189791818948109513521, 8911579544189791818948109513523, -101], [9695467048940029745365798262931, 9695467048940029745365798262933, -101], [11542850118566310777858278573543, 11542850118566310777858278573545, -101], [13076890123869265431324539125559, 13076890123869265431324539125561, -101], [14252654591682873502472100199465, 14252654591682873502472100199467, -101], [15263168850109951797020886985513, 15263168850109951797020886985515, -101], [16433865610612299577828553416679, 16433865610612299577828553416681, -101]]
EllipticCurve/2.0.3.1/120000.1/b:2:[1948400627698075011320939290111972325548072933784658949921, 1948400627698075011320939290111972325548072933785273080771, -188]:[[4132653942351533468540676643963, 4132653942351533468540676643965, -101], [5127894418771415365807434284535, 5127894418771415365807434284537, -101], [7830666359568560148326333980863, 7830666359568560148326333980865, -101], [9007343657714815932836673488003, 9007343657714815932836673488005, -101], [9258205651213490394054685159757, 9258205651213490394054685159759, -101], [11258059869917200785900134810441, 11258059869917200785900134810443, -101], [12300843799473812553662415587577, 12300843799473812553662415587579, -101], [14453464265127790896754767104001, 14453464265127790896754767104003, -101], [15360135175643421567111250618525, 15360135175643421567111250618527, -101], [16007210136756347329463816296011, 16007210136756347329463816296013, -101]]"""

for line in newdata.split('\n'):
    origin, rank, lt, zeros_raw = line.split(':')
    zeros_raw = sage_eval(zeros_raw)
    out = {}
    out['order_of_vanishing'] = int(rank)
    out['leading_term'] = arb_to_numeric(from_arb2(*sage_eval(lt)))
    # we keep the tradition of storing extra digits, so we can recover the original data
    out['positive_zeros'] = [read_zero(elt).str() for elt in zeros_raw]
    for i in range(1,4):
        out['z' + str(i)] = arb_to_numeric(from_arb2(*zeros_raw[i-1]))
    db.lfunc_lfunctions.update({'origin':origin}, out, restat=False)
```

**Comment by AndrewVSutherland** [comment]
Thank you for fixing this @edgarcosta!
