### ISSUE TITLE
Possible error in q-expansion of a CMF

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#4247]
From the feedback page:

On
  https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/35/10/a/b/

the newform 35.10.a.b, I think the q-expansion is correct for beta=sqrt2, not the given 2sqrt2 -- It disagrees with Magma, unless beta is sqrt2.

**Comment by JohnCremona** [comment]
The embedded values are also consistent with beta=sqrt2.

**Comment by AndrewVSutherland** [comment]
Yes, it looks like the Q-expansion is written in terms of the power basis rather than [1,beta].  This looks like a data issue to me, not a bug in the code.  I'll look into it.

**Comment by AndrewVSutherland** [comment]
Actually this is not a data error, the data is correct, see https://www.lmfdb.org/api/mf_hecke_nf/?label=35.10.a.b.  The hecke_ring_bases is 1, 2*sqrt(2) and the coefficient of a_2 in this basis is written as [-12,1] which should be displaying as (-12+beta) not (-12+2beta).  And hecke_power_ring_basis is set to false.

I think this is a bug in the display code.  Possibly coming from it trying to do something clever for quadratic fields (if it had replaced beta with sqrt(2) it would be correct)?  @edgarcosta and @roed314 can one of you take a look at this?

**Comment by edgarcosta** [comment]
I will look into this.
