### ISSUE TITLE
Search by isogeny degree is slow

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4250]
We have been getting timeouts in the flasklog on searches by isogeny degree.  This isn't happening at the moment (presumably because the data is mostly cached right now as a result of the tests I just ran), but it is still much slower than it should be, e.g. searches with no results take several seconds, e.g.

https://beta.lmfdb.org/EllipticCurve/Q/?isodeg=123456789

should be instantaneous (typing 123456789 into any of conductor/j-invariant/rank/torsion-order is).

**Comment by JohnCremona** [comment]
It may be a side-effect to my currently uploading a lot of ECQ data (into new tables)  which could be slowing down beta response time?

**Comment by JohnCremona** [comment]
Alternatively:  each row of the search table has a column containing a list of isogeny degrees and this search (which was not implemented by me) is testing whether the number entered by the user is in that list for all 3m records.  Since none of the degrees present will ever be >163 perhaps the search can be simplified.

**Comment by JohnCremona** [comment]
Please do not edit the code in lmfdb/elliptic_curves right now as I will soon be making a large PR changing all that a lot.  But any suggestions for making this search more efficient can be implemented by me at the same time (i.e. now).

**Comment by JohnCremona** [comment]
In fact the isogeny_degrees column always contains one of the following lists (and that's a theorem):
[1]
[1,11]
[1,13]
[1,163]
[1,17]
[1,19]
[1,2]
[1,2,3,4,6,12]
[1,2,3,6]
[1,2,3,6,9,18]
[1,2,4]
[1,2,4,8]
[1,2,4,8,16]
[1,2,5,10]
[1,2,7,14]
[1,3]
[1,3,5,15]
[1,37]
[1,3,7,21]
[1,3,9]
[1,3,9,27]
[1,43]
[1,5]
[1,5,25]
[1,67]
[1,7]

so the only degrees which will ever be seen are 1-19, 21, 25, 27, 37, 43, 67, 163.

**Comment by JohnCremona** [comment]
That list is what is returned by the cached method isogeny_degrees() of class ECstats, so one thing I will do is remove that function and replace it with the hard-wired list.

**Comment by edgarcosta** [comment]
I have added the missing index on `isodeg` on both databases. I think this addresses the issue, and I would not invest my time in improving the search as suggested above, as with the index Postgres is now aware of what are possible values in the `isodeg` array.

**Comment by JohnCremona** [comment]
So the conclusion is that when someone implemented this search (not that long ago) they should have thought to add the index? 

 Perhaps we should be stricter about insisting adding a new test for any new search that is added.

**Comment by edgarcosta** [comment]
Yes to both.

In general, we should try to increase our test coverage in a thoughtful way, with aid of some coverage tool, see what functions/features are not tested, and do a todo list to add such tests.
