### ISSUE TITLE
Rewrite EC/Q tables with new schemas

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#4255]
Since the migration from mongo to postgres there has been just one table for elliptic curves over Q, ec_curves, with both a search and extra component.  (Strictly there has always also been the table ec_padic.)  This division made some data updates awkward, especially when amending the extra table.  Also, the column types were converted in a way which was not always optimal.

I have completely rewritten my scripts for handling the raw data files behind this collection, in the repository ecdata, with  a view both to streamline the data upload (no more computing stuff on the fly during upload) and to make it possible to add new collections of curves from other sources.  I have created 8 tables to replace ec_curves search&extra, of which one (only) holds all search columns, while the others hold other data components which are used to fill in the WebEC and ECisog_class objects.  Documentation for these, with their schemas and the commands used to create the new tables and all their indexes are in the scripts directory of the ecdata repository.  The new table names are ec_curvedata, ec_classdata, ec_mwbsd, ec_localdata, ec_galrep, ec_iwasawa, ec_2adic and ec_torsion_growth.

The content of the new tables is not very different from the old apart from some changes on data types.  There are no more curves!  But there are some more columns in the search table, and in addition the following data revisions:

   - real number (heights, regulator, real period, special value, analytic sha) have all been recomputed to 100 bits precision.  It would be very easy to make that greater.  Currently the code displays exactly what it has, so comparing new and old you'll see more decimals.
   - generators:  I replaced the generators of infinite order by new generators which are Minkowski-reduced (i.e. of smallest possible canonical height) and then reduced them further (as measured by the number of characters in the affine coordinate strings displayed) by replacing each P by the shortest point among all {P+T, -P+T: T torsion}.  Torsion generators have also been similarly reduced.  This was a suggestion of Randall Rathbun.
   - torsion growth: now we have all data on torsion growth in fields of degree<24 (it used to be <8).  This represents the bulk of the increase in table size.  In all cases the polynomials defining the extension fields have been fully polredabs-ed, which was a lot of work (there are millions of them of composite degree where polredabs has to work harder).  John Jones has added a lot of these fields to the number fields database. The data upload files for the table ec_torsion_growth are 1.3G, about double that of ec_mwbsd.  You'll see the longer lists of torsion growth fields at the bottom of all curve home pages.

My branch ECQ-revision contains all the code changes needed to use these new tables.   I will make a PR for this branch soon -- it passes all tests.  It will work on beta (dev) as is but before it is pushed to web the 8 new tables will need to be copied.  As well as updating the interface to the tables there are some new features:

   - new searches by isogeny class size and degree, and by potential good reduction, and by prime factors of sha.  These have all been feature requests.
   - the isogeny class home pages for CM curves nwo show the actual CM discriminant for each curve in the class (they all have the same CM field, but the endomorphim rings are in general different orders in that field).  I think that more can be done to improve what we see on these isogeny class pages.

**Comment by edgarcosta** [comment]
FYI, the [numeric](https://www.postgresql.org/docs/current/datatype-numeric.html)* type is a bit weird, it has various advantages over strings, as one can search on ranges and so on, but internally the values are stored in something isomorphic to its decimal string, thus when uploading the data, you should use the string representation that you would like to see on the pages, as when we load it, we use the class [`LmfdbRealLiteral`](https://github.com/LMFDB/lmfdb/blob/master/lmfdb/backend/encoding.py#L41), which by default will use that string to display it.

If you computed the real number as an interval, you could store the middle value and the radius. We are not doing that anywhere, but that is the plan for L-functions.

*: "The type numeric can store numbers with a very large number of digits and perform calculations exactly. It is especially recommended for storing monetary amounts and other quantities where exactness is required."

**Comment by JohnCremona** [comment]
Interesting.   I home I am doing the right thing.  For example for curve 11a1 the value I computed for the real period was 1.2692093042795534216887946168 -- that is the string I have stored in my data files.  Then the script which prepares the data for upload using the correct schema does not change that string.  The column type is 'numeric' and the curve's web page displays that same string.  The same is true for regulator, special_value, heights (numeric[]), area, and sha_an (for which we also store the rounded value which is always a postive integer square). That's all the floating point values I deal with here.

**Comment by edgarcosta** [comment]
Perhaps my question is how to do you arrive to string `1.2692093042795534216887946168` from its binary representation?

If you are getting to it via sage then I see two options:
-  use '.str()' method, then on load convert it back to `RealField(100)` and then use `.str(truncate=True)` or `.str(digits=?)` when displaying it. This way the stored value can be converted to the same bit representation before you converted it to a string.
- use '.str(truncate=True)' when computing the data file, then we have potentially lost some bits of precision, but no digits.

```
sage: RR(2/3).str()
'0.66666666666666663'
sage: RR(2/3).str(truncate=True)
'0.666666666666667'
sage: RR(RR(2/3).str(truncate=True)) == RR(2/3)
False
```

**Comment by JohnCremona** [comment]
I am just using str(x) to convert to a string from a sage RealField() element.  On input (uploading from a text file to the postgres table), it's whatever postgres and your interface does when filling a column of type numeric.  If we knew that we never wanted to do arithmetic on the values then we could just make the column type text, but that's not sufficient -- for example, we have a search on the value of the regulator being in some interval, so that needs to know it is a number.  I am not planning on doing anything different now, but could change these representations later without problem.

**Comment by JohnCremona** [comment]
This can be closed after the next push of master to dev/prod.  I have updated https://beta.lmfdb.org/knowledge/show/dq.ec.source already.
