### ISSUE TITLE
Error in data set : Class groups of quadratic imaginary fields

### ISSUE THREAD

**Issue by saroad** [LMFDB/lmfdb#4260]
In the file cl4mod16.0, the first which corresponds to the number field with discriminant -4, the class number is given as 2.

**Comment by AndrewVSutherland** [comment]
I agree that this looks wrong, but possibly I am misunderstanding the notation, which is inconsistent and should be fixed: d_i is initially declared to be a positive integer (the negation of the discriminant), but d_0 is then defined to be negative and in the example at the bottom the d_i are negative (I think they should all be positive and the minus signs removed except in h(-d_i)).

@jwj61, @edgarcosta Any idea what happened here?  I have downloaded these files myself and used them in the past without any trouble, so I'm suspicious that something changed (although the first lines of the file cl4mod16.1 look OK).

**Comment by edgarcosta** [comment]
I agree with the inconsistency in the notation and the suggested fix.

I didn't modify the files at all when I downloaded them from Warwick. 
@JohnCremona, @jwbober by any chance do one of you have these files stored in some UK server? If so could you share some kind of hash with me?

I checked the first couple of lines and only the first one seems to be wrong. See below.


Here are the first lines of `cl4mod16.0`
```
0	2	2
1	2	2
2	2	2
1	4	4
1	4	2 2
2	6	6
1	4	2 2
```
so, the file claims:
Cl(-4) = Z/2Z (wrong)
Cl(-20) = Cl(-52) = Z/2Z 
Cl(-68) = Z/4Z
CL(-84) = Z/2Z + Z/2Z
Cl(-116) = Z/6Z
Cl(-132) = Z/2Z + Z/2Z

**Comment by jwj61** [comment]
I just transferred the files and included, what I think is the accompanying documentation.  If only one entry seems wrong, then the documentation as to how to read the files and matching which file is which is probably right.

**Comment by saroad** [comment]
Sorry but having an error on one line, is the dataset reliable?

**Comment by jwj61** [comment]
I was saying that the things we did seem ok. So, we should check with the source.  Maybe I can look into it tomorrow.

**Comment by jwj61** [comment]
I e-mailed one of the authors of the source of the data.

I agree that the explanation of how to interpret the data with respect to d and -d needs to be fixed.

**Comment by edgarcosta** [comment]
@JohnCremona, @jwbober you can ignore my request. I found the md5 hash file that I got when I downloaded this from Warwick https://beta.lmfdb.org/data/class-groups-quadratic-imaginary-fields/md5.txt

I have checked all the md5 hashes and they all agree.

**Comment by JohnCremona** [comment]
Some time ago (a few years, I have not checked) after a previous complaint about the confusing data format of this collection of data, I worked out what it really was an completely rewrote what you can now see at https://beta.lmfdb.org/NumberField/QuadraticImaginaryClassGroups .

This was reviewed at the time, but if it is wrong then of course I would welcome someone correcting it.  This is not my data, I was just trying to interpret the documentation which cam with the data to be comprehensible.  In particular, if this page has got something wrong in its explanation, then this is *not* an indication that the data as supplied to us is wrong.

**Comment by jwj61** [comment]
Here is the email response from the source of the data:

It seems to me that there is a mistake only on this particular line, as the other lines contain the right information:

0       2       2
1       2       2 <- h(-20) = 2
2       2       2 <- h(-52)  = 2
1       4       4 <- h(-68) = 4
1       4       2 2 <- h(-84) = 2
2       6       6 <- h(-116) = 6

I'd be grateful if we could fix this by replacing 0     2       2 with 0        1       1.

If I could guess why this happened, I bet this is related to the fact that we were computing (multiples of) Hurtwitz class numbers H(n). In cl3mod8.zip I seem to have fixed the first line manually, but may have forgotten to do the same thing for cl4mod16.

**Comment by edgarcosta** [comment]
Thanks, @jwj61

I will try to fix the data this weekend.

someday we should perhaps compare the data in `nf_fields` against this data, to be sure there aren't any more surprises.
On the other hand, I wouldn't put this as a priority, as these pages are very seldomly visited.

**Comment by jwj61** [comment]
I agree.  I won't do this today, but I will try to keep this in the back of my mind.

**Comment by AndrewVSutherland** [comment]
@edgarcosta It looks like this is still broken?

**Comment by edgarcosta** [comment]
This is now fixed on https://beta.lmfdb.org and https://www.lmfdb.org

**Comment by AndrewVSutherland** [comment]
Thanks @edgarcosta!
