### ISSUE TITLE
Allow multiplication and exponentiation in input boxes

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#4268]
For integer search boxes, it would be nice if we allowed expressions like `2^5*17` in integer inputs.  This can be achieved by editing line `344` of `lmfdb/utils/search_parsing.py` to change
```
def parse_ints(inp, query, qfield, parse_singleton=int):
```
to 
```
def parse_ints(inp, query, qfield, parse_singleton=my_parser):
```
and write a function that can parse multiplication and exponentiation.  If you use `sage_eval`, make sure you run the input through a regular expression (eg. only allow digits, * and ^) first so that it's safe.

**Comment by jwj61** [comment]
Making that one change should come with a basic arithmetic parser, or regex test with sage_eval (which I assume is essentially the same as taking ZZ(input)?).  We certainly don't want a bunch of people writing their own parsers.

**Comment by AndrewVSutherland** [comment]
@jwj61 Agreed, the implementation should do a regex match that only allows digits and multiplicative operators and then call sage eval (we don't want to support additive operators to avoid bad interactions with ranges, but almost all of our integer inputs are multiplicative (conductor, discriminant, order, ....)

**Comment by AndrewVSutherland** [comment]
Addressed by #4268 and now live.

**Comment by AndrewVSutherland** [comment]
Reopening this issue because there is a problem in the way malformed expressions are handled, typing "3*" into an integer input now throws a server error, but it should be handled the same way as "banana" or any other invalid input.  I'm guessing the regex match is not requiring a full match (which it should).

**Comment by roed314** [comment]
I think it's easier to just catch the error than to write a regex that handles all the right syntax.

**Comment by edgarcosta** [comment]
Yeah, I would also go for the catch syntax error
