### ISSUE TITLE
Hecke cutters display

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#4270]
There is something weird going on with the display of the Hecke cutters for https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/8449/2/a/h/

**Comment by AndrewVSutherland** [comment]
I think this will be addressed by #4394, but let's leave this issue open for them moment.

**Comment by roed314** [comment]
This is resolved by Edgar's changes in #4394.  Assigning this issue to Edgar since that isn't yet merged.
