### ISSUE TITLE
Some Dirichlet character pages are failing to load

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4275]
The page https://www.lmfdb.org/Character/Dirichlet/947/934 is timing out.  Some similar pages such as https://www.lmfdb.org/Character/Dirichlet/947/933 and https://www.lmfdb.org/Character/Dirichlet/947/935 work but are slow too load and the knowl for the fixed field does not work.  I believe this is due to some of the recent changes that were made #4231 -- @BarinderBanwait can you take a look at this?

Below is the trace back from the page that is failing to load.  the failure is inside the call to "zeta_order" on line 156 of https://github.com/LMFDB/lmfdb/blob/master/lmfdb/characters/TinyConrey.py.  I don't think that call should be taking any time, but if Sage is doing something silly we should just compute zeta_order directly.  I confess it's not clear to me why we are using Sage DirichletGroup and Sage characters at all (it appears they are being used in just 2 places).

```
Traceback (most recent call last):
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/main.py", line 367, in render_Dirichletwebpage
    webchar = make_webchar(args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/main.py", line 313, in make_webchar
    return WebDBDirichletCharacter(**args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 925, in __init__
    WebDBDirichlet.__init__(self, **kwargs)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 568, in __init__
    self._compute()
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 575, in _compute
    self._populate_from_db()
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 589, in _populate_from_db
    self._set_generators_and_genvalues(values_data)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 615, in _set_generators_and_genvalues
    self._genvalues_for_code = get_sage_genvalues(self.modulus, self.order, vals, self.chi.sage_zeta_order(self.order))
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/TinyConrey.py", line 156, in sage_zeta_order
    return DirichletGroup(self.modulus, base_ring=CyclotomicField(order)).zeta_order()
  File "sage/misc/cachefunc.pyx", line 2310, in sage.misc.cachefunc.CachedMethodCallerNoArgs.__call__ (build/cythonized/sage/misc/cachefunc.c:12712)
    self.cache = f(self._instance)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/sage/modular/dirichlet.py", line 2880, in zeta_order
    order = self.zeta().multiplicative_order()
  File "sage/rings/number_field/number_field_element.pyx", line 3229, in sage.rings.number_field.number_field_element.NumberFieldElement.multiplicative_order (build/cythonized/sage/rings/number_field/number_field_element.cpp:27976)
    elif not (self.is_integral() and self.norm().is_one()):
  File "sage/rings/number_field/number_field_element.pyx", line 3576, in sage.rings.number_field.number_field_element.NumberFieldElement.is_integral (build/cythonized/sage/rings/number_field/number_field_element.cpp:30234)
    return all(a in ZZ for a in self.absolute_minpoly())
  File "sage/rings/number_field/number_field_element.pyx", line 3576, in genexpr (build/cythonized/sage/rings/number_field/number_field_element.cpp:30109)
    return all(a in ZZ for a in self.absolute_minpoly())
  File "sage/rings/number_field/number_field_element.pyx", line 4488, in sage.rings.number_field.number_field_element.NumberFieldElement_absolute.absolute_minpoly (build/cythonized/sage/rings/number_field/number_field_element.cpp:37507)
    return self.minpoly(var)
  File "sage/rings/number_field/number_field_element.pyx", line 4576, in sage.rings.number_field.number_field_element.NumberFieldElement_absolute.minpoly (build/cythonized/sage/rings/number_field/number_field_element.cpp:38144)
    return self.charpoly(var, algorithm).radical() # square free part of charpoly
  File "sage/rings/number_field/number_field_element.pyx", line 4543, in sage.rings.number_field.number_field_element.NumberFieldElement_absolute.charpoly (build/cythonized/sage/rings/number_field/number_field_element.cpp:37945)
    return R(self.matrix().charpoly())
  File "sage/matrix/matrix_rational_dense.pyx", line 1034, in sage.matrix.matrix_rational_dense.Matrix_rational_dense.charpoly (build/cythonized/sage/matrix/matrix_rational_dense.c:10660)
    f = A.charpoly(var, algorithm=algorithm)
  File "sage/matrix/matrix_integer_dense.pyx", line 1336, in sage.matrix.matrix_integer_dense.Matrix_integer_dense.charpoly (build/cythonized/sage/matrix/matrix_integer_dense.c:12941)
    sig_on()
```

**Comment by AndrewVSutherland** [comment]
Just to clarify, the problem is that Sage is for some reason very slow to compute

`DirichletGroup(947,base_ring=CyclotomicField(473)).zeta_order()`

but I believe we can safely change line 156 of TinyConrey.py from

    ` return DirichletGroup(self.modulus, base_ring=CyclotomicField(order)).zeta_order()`

to

    `return 1 if self.modulus <= 2 else lcm(2,order)`

At least I have verified that this works in all cases where the modulus is less than 800.  I'm pretty sure Sage always uses roots of unity with even order except for the first and second cyclotomic fields.

But I'm still not certain that we need to or should be using sage characters at all, in which case we could just get rid of this method.  The only place they seem to be used outside of web_character.py is one place in the CMF verification code.

**Comment by AndrewVSutherland** [comment]
This doesn't fix the problem, it just moves it elsewhere.  It is not enough to avoid calling zeta_order, I think we need to avoid using Sage's Dirichlet character implementation entirely.

**Comment by BarinderBanwait** [comment]
Oh dear, yep that call to zeta_order is something I put in; I'll look into it.

The sage characters are also used crucially to compute the kloosterman and jacobi sums, both when loading a dirichlet character of modulus < 1000, and when pressing the 'Compute' button (see e.g. [here](https://github.com/LMFDB/lmfdb/blob/6d6f0504a75196f9dc3896d2813401e4e491fd18/lmfdb/characters/web_character.py#L329)). They were also being used to compute the Gauss sums, but I recently changed that to use pari directly.

**Comment by AndrewVSutherland** [comment]
@BarinderBanwait The calls to zeta_order have been removed and this has yielded some improvement (e.g. https://beta.lmfdb.org/Character/Dirichlet/947/933 now loads but it is still a bit sluggish).  

The pages for characters in the range 1000 to 9999 also seem more sluggish than they should be, but I'm wondering if that is because we are wasting time formatting kernel fields that are too large to display anyway, e.g. the pags https://beta.lmfdb.org/Character/Dirichlet/9901/2 and https://beta.lmfdb.org/Character/Dirichlet/9901/9900 really shouldn't differ in their load times (both are displaying only information that is coming from the database), but the first is much slower, possibly because it is creating a field knowl for a degree 9900 polynomial (which then won't display anyway).  Perhaps we should not try to display defining polynomials for kernel fields with degree above 100.

**Comment by AndrewVSutherland** [comment]
Correction to what I wrote above, https://www.lmfdb.org/Character/Dirichlet/947/934 is still timing out (in my message above I gave a link to a different character page that actually has larger order by the defining polynomial for its kernel field is simpler).

**Comment by edgarcosta** [comment]
Here is some profile data:
- 10.3s [947.934](https://gist.github.com/edgarcosta/b0bf58aac946c07abdf8f788950dc1ae)
- 1.7s [947.933](https://gist.github.com/edgarcosta/2f701cd8d373b1432b6f1750dfd1317f)
- 1.6s [9901.9900](https://gist.github.com/edgarcosta/f13c7b829eebf087b6ff43ddc8f28d75)
- 1.4s [9901.2](https://gist.github.com/edgarcosta/e158d22a5c293d5844a032843ee65044)

You can reproduce similar data by adding `--enable-profiler` when you run locally.

**Comment by BarinderBanwait** [comment]
I locally removed the call to `formatfield(kerpoly, ...)` and tried 947.934 again, but it still loads just as slowly; I'll keep looking for the major bottleneck.

Not displaying kernel polynomials for degree > 100 could be quickly achieved with an extra condition on `self.order` in the kerfield lazy attribute of `WebChar`.

**Comment by BarinderBanwait** [comment]
Woah @edgarcosta that profiling tool is aweSome! It shows that 947.934 takes 27 seconds to load, and spends 18 seconds in `method 'multiplicative_order' of 'sage.rings.number_field.number_field_elem
ent.NumberFieldElement' objects`

**Comment by BarinderBanwait** [comment]
OK so I think I've found the [culprit](https://github.com/LMFDB/lmfdb/blob/b0f6d0a28e834797eca8e9ecebbaddcf8da45bc3/lmfdb/characters/TinyConrey.py#L160):

```
sage: H = DirichletGroup(947, base_ring=CyclotomicField(473))
sage: %time M = H._module
CPU times: user 20.6 s, sys: 383 ms, total: 21 s
Wall time: 21 s
```

This is called to create the sage character, which is used to compute the Kloosterman and Jacobi sums.

I've just noticed that removing the optional `base_ring=CyclotomicField(473)` is much faster - Wall time: 16 ms. I put that base_ring in due to an issue I noticed with the sage generating code; for example in [91.3](https://www.lmfdb.org/Character/Dirichlet/91/3), the previous sage code stub yielded the following:

`ValueError: values (= (1, 2) modulo 12) must have additive orders dividing (6, 12), respectively`

I'll think about a way of creating the sage character without an explicit `base_ring` parameter.

**Comment by JohnCremona** [comment]
As far as I can see, if you don't put the base ring in then it will use base ring CyclotomcField(946) (since 947 is prime, in general it would use the exponent of (Z/NZ)^*).

It seems to me that there is a silly bug in the multiplicative_order() method in Sage and -- apart from what we are doing here -- it would be a good thing to fix that.  Asking for H._module causes H.zeta().multiplicative_order() to be asked for, H.zeta() displays as -zeta473^237 and obviously in a cyclotomic field computing the order of a power of the generator should be instant.  And it would be if not for the bug.

**Comment by JohnCremona** [comment]
Here's what is happending: as we all know, for odd n we have Q(zeta_n)=Q(zeta_{2n}). When you construct CyclotomicField(n) in Sage it caches a table of the orders of all the powers of its generator zeta_n but *not* the negative powers -- not exactly a bug, but not good either.  In Barinder's example, n=473 and so H.zeta() is minus a power of the generator, so computing its order involves more than a table lookup.  Bug 2 is a real bug, namely that if you ask for the order of an element not in the cached list it assumes that it is not a root of unity, hence has infinite order.  This is not the whole story but it is quite hard to test as things get cached.  But in 
{{{
sage: K.<z> = CyclotomicField(473)
sage: z.multiplicative_order()
473
sage: w = K.zeta()
sage: w
-z^237
sage: w.multiplicative_order()
946
}}}
the last line takes ages (>21s) which is crazy, especially as w^946 evaluated to 1 very quickly and 946 is not too hard to factor.

**Comment by JohnCremona** [comment]
I know that what I just wrote is not quite correct, but the upshot is that we should not use an odd n in the base_ring.

**Comment by BarinderBanwait** [comment]
Thanks for digging into this @JohnCremona and for identifying odd `n` as the issue! So it seems that the solution to this is a one-line code change: namely that [this line](https://github.com/LMFDB/lmfdb/blob/b0f6d0a28e834797eca8e9ecebbaddcf8da45bc3/lmfdb/characters/TinyConrey.py#L159) should be changed from

`H = DirichletGroup(self.modulus, base_ring=CyclotomicField(order))`

to

`H = DirichletGroup(self.modulus, base_ring=CyclotomicField(self.sage_zeta_order(order)))`

This ensures that the `n` in the base ring is always even (or 1). 

Drew's example 947.934 then runs in 1.6 seconds rather than 27 seconds. 

A legitimate concern is that this may be choosing the wrong Dirichlet character. However, I have kicked off the verification check `check_Skchi_dim_formula` with ratio 0.0005, and although it's still going after about 10 minutes, it's successfully checked 400 characters, which is about four times more cases than checked previously, so it provides confidence that we're getting the right character.

I'll tie up the loose ends (some unit tests might need to change, change the sage code stub the user sees) and open a PR for this.

**Comment by AndrewVSutherland** [comment]
This is now fixed, thanks @BarinderBanwait!

There is still a problem with using any of the buttons to evaluate or compute sums on production (works fine on beta), but that is unrelated to this problem so I will make a separate issue for it.
