### ISSUE TITLE
Add prime/prime-power/square-free/divides search options for conductor

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4301]
A number of people have requested that we make the search options that are currently available for the level of a modular form also available for conductors of elliptic curves (and one could ask for the same for genus 2 curves).  Probably it makes sense to do EC/Q first.  This should be easy to add.

**Comment by JohnCremona** [comment]
Squarefree is already in my PR (as semistable) and #bad primes is in the database so prime power will be easy. Hence also prime. I cannot think of a reason fir searching for square conductor but squarefull=potential goid reduction is there already.

**Comment by AndrewVSutherland** [comment]
@JohnCremona I don't actually know of anyone asking for square conductor, happy to leave that out.

**Comment by AndrewVSutherland** [comment]
This mostly duplicates #2625, closing.
