### ISSUE TITLE
Modular form search timeout

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#4312]
From the feedback page:

I was looking for a classical modular form of weight 2 with a13=4 and a17=6. The search gave me an error because it took too long.
https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/?hst=Traces&weight=2&search_type=Traces&an_constraints=a13%3D4

**Comment by roed314** [comment]
I'm not seeing a timeout when I try this search.

**Comment by edgarcosta** [comment]
I also don't observe a timeout on https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/?count=None&hst=Traces&weight=2&search_type=Traces&an_constraints=a13%3D4%2Ca17%3D6

**Comment by AndrewVSutherland** [comment]
I also don't get a timeout (it takes 3-4 seconds).  While intermittent timeouts can certainly happen, I'm not sure it's worth trying to track the cause of this one down.
