### ISSUE TITLE
Don't use magma_free in tests

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#4326]
The test_download_magma() test in classical_modular_forms/test_cmf.py uses Sage's magma_free() function to run the code on the free online Magma service, but we should not be doing this.  Instead we shold do something closer to what similar test functions do in  test_bmf and test_hmf.

Secondly, rather than having several almost identical test functions which fetch some Magma code (or Sage of gp) from a URL, and run them to make sure that they run without errors and that some string appears i the output, it would be better to have a single function for each language which these test functions would just call.  Then we can easily add similar tests for other code download URLs -- being careful, of course, that the examples used i nthe test all run quickly.

**Comment by JohnCremona** [comment]
@BarinderBanwait do you have time to deal with the first part of this (at least)?

**Comment by edgarcosta** [comment]
Here is the place where one can add such functions: https://github.com/LMFDB/lmfdb/blob/master/lmfdb/tests/__init__.py

Calling magma_free is quite useful when magma is not available.
For example, we can't have magma on Travis, and not everyone has access to magma when submitting PRs.


In general, automatic testing would be much better if we replaced Travis by doing testing on our own virtual servers.
For example, with a webhook system (https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhooks) or via Google Cloud Build (https://github.com/marketplace/google-cloud-build).
At the moment, the time investment setup for these things is too high in comparison to its benefits.

**Comment by AndrewVSutherland** [comment]
@edgarcosta As we discussed, while I agree that Magma's online calculator is a very handy tool that is a great way to try out Magma or do a quick calculation, it really isn't appropriate for us to take advantage of Magma's generosity by incorporating it into our automated CI process.

Any LMFDB developers who do not have access to Magma and need it for work they are doing on the LMFDB should feel free to contact me and we can setup an account for them on one of our development machines (all of which have Magma installed).

**Comment by BarinderBanwait** [comment]
right, so if i understand correctly, the tasks here are:

1. Deprecate magma_free (and replace with what `test_download_magma` in test_bmf is doing);

2. Create `{x}_code_getter_and_executor` for x in {Sage, Magma, PARI/GP} functions, place them in the file @edgarcosta  points to, and have the various `test_download_{x}` tests call the respective getter_and_executor?

sure, i think i can take that on

**Comment by edgarcosta** [comment]
Yup and yup.

Thanks

**Comment by JohnCremona** [comment]
Thanks @BarinderBanwait .  I suggest doing 1 by itself first (we had some recent issues where the magma server was not responding, causing that one test to fail and hence delaying the merging of PRs).  For 2, first convert the two tests you wrote for bmf and hmf.  Then we can start to systematicall add tests for all code-download options, not necessarily all at once.

**Comment by edgarcosta** [comment]
Item 1 has been addressed by #4334

**Comment by JohnCremona** [comment]
There are no more mentions to magma_free.  Good!
