### ISSUE TITLE
get rid of Deprecation warnings

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#4327]
When running tests I see several warnings like this:

lmfdb/characters/main.py:70
  /scratch/home/jcremona/lmfdb/lmfdb/characters/main.py:70: DeprecationWarning: invalid escape sequence \(
    jump_egspan = "e.g. 13.2 for the Dirichlet character \(\displaystyle\chi_{13}(2,·)\),or 13.f for its Galois orbit."

wihc are harmless now but one day will be fatal.  All that is needed, I think, is to put an r infront of the opening quote for such strings.

**Comment by JohnCremona** [comment]
I'm fixing these where possible.  Some appear to be in python packages, e.g.
lmfdb/siegel_modular_forms/test_siegel_modular_forms.py::HomePageTest::test_browse_page
  /scratch/sage/sage-9.2/local/lib/python3.6/site-packages/jinja2/lexer.py:648: DeprecationWarning: invalid escape sequence '\m'
    .decode("unicode-escape")
and perhaps can be fixed by upgrading these (using sage -pip perhaps).

**Comment by edgarcosta** [comment]
Is this on Legendre? If so the packages were freshly installed a couple of weeks ago.

**Comment by JohnCremona** [comment]
> Is this on Legendre? If so the packages were freshly installed a couple of weeks ago.

Yes, on legendre.   See the PR#4328.

We still see Deprecation Warnings from /scratch/sage/sage-9.2/local/lib/python3.6/site-packages/jinja2/lexer.py:648 and /scratch/sage/sage-9.2/local/lib/python3.6/site-packages/markdown/treeprocessors.py:285
both triggered (I think) by lmfdb/lfunctions/test_lfunction_degree_2.py::LfunctionTest

**Comment by edgarcosta** [comment]
The packages are up to date, I think the issues might be in our templates.

Here are the remaining warnings:
```
  /home/edgarcosta/LMFDB/lmfdb/lmfdb/knowledge/__init__.py:10: DeprecationWarning: 'etree' is deprecated. Use 'xml.etree.ElementTree' instead.
    from . import main
--
  /home/sage/sage-9.2/local/lib/python3.6/site-packages/jinja2/lexer.py:648: DeprecationWarning: invalid escape sequence '\('
    .decode("unicode-escape")
--
  /home/sage/sage-9.2/local/lib/python3.6/site-packages/jinja2/lexer.py:648: DeprecationWarning: invalid escape sequence '\c'
    .decode("unicode-escape")
--
  /home/sage/sage-9.2/local/lib/python3.6/site-packages/jinja2/lexer.py:648: DeprecationWarning: invalid escape sequence '\l'
    .decode("unicode-escape")
--
  /home/sage/sage-9.2/local/lib/python3.6/site-packages/jinja2/lexer.py:648: DeprecationWarning: invalid escape sequence '\m'
    .decode("unicode-escape")
--
  /home/sage/sage-9.2/local/lib/python3.6/site-packages/jinja2/lexer.py:648: DeprecationWarning: invalid escape sequence '\G'
    .decode("unicode-escape")
--
  /home/sage/sage-9.2/local/lib/python3.6/site-packages/jinja2/lexer.py:648: DeprecationWarning: invalid escape sequence '\A'
    .decode("unicode-escape")
--
  /home/sage/sage-9.2/local/lib/python3.6/site-packages/jinja2/lexer.py:648: DeprecationWarning: invalid escape sequence '\#'
    .decode("unicode-escape")
--
  /home/sage/sage-9.2/local/lib/python3.6/site-packages/jinja2/lexer.py:648: DeprecationWarning: invalid escape sequence '\D'
    .decode("unicode-escape")
--
  /home/sage/sage-9.2/local/lib/python3.6/site-packages/markdown/treeprocessors.py:285: DeprecationWarning: 'etree' is deprecated. Use 'xml.etree.ElementTree' instead.
    node = pattern.handleMatch(match)
```

**Comment by JohnCremona** [comment]
OK.  I suggest merging my PR already anyway.  "etree" is in our code in lmfdb/knowledge/main.py (twice) so that should be easy but I'll let someone else take over.

**Comment by edgarcosta** [comment]
I will merge once Travis is happy.
