### ISSUE TITLE
Compute mod 2 galois representation, link to associated field explicitly

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#434]

**Comment by AndrewVSutherland** [comment]
The 2-torsion field of the Jacobian of a genus 2 curve is typically going to have degree well beyond the range of the LMFDB (as high as 720).  It would be possible to instead identify the 2-torsion field as the Galois closure of an etale algebra of degree <= 6, which could be identified by a list of number field labels in some agreed ordering.  But this would have the unfortunate disadvantage that non-isomorphic etale algebras may have the same splitting field, and one would really like to know when two genus 2 Jacobians have isomorphic 2-torsion fields.

John Jones points out that for any etale Q-algebra of degree <= 6 we can always construct a number field of degree at most 9 with the same splitting field K (worst case is two S3-cubics with a common quadratic subfield).  We could then sort the subfields of K with Galois closure K and pick a minimal representative (e.g. apply polredabs to a defining polynomial and sort lexicographically).  Most (possibly all) of these degree <= 9 fields are already in the LMFDB, and John says it would not be difficult to add any that are not.

One possibly confusing aspect of this approach is that even when we have a generic genus 2 curve y^2=f(x) with f an irreducible sextic, it might happen that the 2-torsion field of its Jacobian would be identified as the splitting field of an irreducible sextic g that does not define the same field as f.  I could live with this, but in the long term I'd love to see Galois closures of etale Q-algebras as bonafide LMFDB objects in their own right (with their own labels) that we might store up to some reasonably low degree bound (e.g. 6) and discriminant bound (e.g. 10^6).

I'll note that we don't do this for elliptic curves -- presumably we would also want this here.

**Comment by AndrewVSutherland** [comment]
The two torsion fields have all been computed, what remains to be done is to add the image of the representation, as a subgroup of GSp4(Z/2Z)

**Comment by jvoight** [comment]
Move the mod 2 Galois representation from Mordell-Weil to the Galois representations section.

**Comment by shiva-chid** [comment]
I am working on it
