### ISSUE TITLE
Artin representations only display 20 results, no way to go forward and backward

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#435]
http://www.lmfdb.org/ArtinRepresentation/?dimension=2

**Comment by jwj61** [comment]
working on this

**Comment by jvoight** [comment]
We need the same thing for HMFs, BTW.

**Comment by JohnCremona** [comment]
I did that a few weeks ago and it is in beta!

**Comment by jwj61** [comment]
Paging was done this fall
