### ISSUE TITLE
Elliptic curve link and data (for newly added curves)

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#4352]
From the feedback page:

On
http://www.lmfdb.org/EllipticCurve/Q/?jinv=1728&rank=2&torsion_structure=%5B2%2C2%5D&search_type=List

the link with text "705600.vn2" incorrectly links to 705600.vn3 when clicked. The correct curve is 705600.vn2.

Then, on

https://www.lmfdb.org/EllipticCurve/Q/705600/vn/2

For the Mordell-Weil generators and heights of the elliptic curve 705600.vn2: the correct heights are given, but the points are wrong.

I have confirmed using the Magma online calculator <http://magma.maths.usyd.edu.au/calc> that
-- The given number 1.770210... is the height of (-90,1800), and
-- The given number 1.863669... is the height of (1260,-44100).
(The URL currently gives the points (1369/4,-39997/8) = [2](1260,-44100) and (841/4,-1189/8) = [2](-90,1800).)

**Comment by JohnCremona** [comment]
I'll check this out on Monday .  It's probably just a mix up in the numbers.

**Comment by JohnCremona** [comment]
The immediate problem is this inconsistency in the data for this isogeny class:

sage: CC = [C for C in db.ec_curvedata.search({'lmfdb_iso':'705600.vn'})]
sage: [[C['lmfdb_number'],C['lmfdb_label']] for C in CC]
[[1, '705600.vn3'], [2, '705600.vn4'], [3, '705600.vn2'], [4, '705600.vn1']]

Whatever data processing error caused will possibly have affected all the new data (N>500000) and I'll corrtec it as soon as I can.

**Comment by JohnCremona** [comment]
I want to make it easier to select rows in all the new ec_* tables according to the conductor (or range of conductors), for example in order to delete all rows for conductors over 500000 -- which I think is necessary in fixing this issue, since the column which needs changing is the label column.  To this end I plan to add a conductor column to the 7 relevant tables and to fill it befre fixing this data glitch.  But I will not do that until after Wednesday in case I mess things up.

**Comment by JohnCremona** [comment]
This should now be fixed on beta.lmfdb.org.  I would be grateful if someone could check.

In more detail, I made the following changes to the ec tables:
   - added a column 'conductor' to the 7 tables other than ec_curvedata which did not have it already, and filled in wit hthe correct conductor value.  This was just to make the next step (and similar housekeeping) easier in future.
   - deleted the 32082 curves in all tables with conductor > 500000, which had the problem (for isogeny classes of size>1 the numbering was mixed up)
   - revised my scripts to make data upload files to (1) correct the value of 'lmfdb_label' (which was the problem) and to include the 'conductor' column in all 8 tables, all rows.
   - Re-uploaded the 32082 curves.

All that was really needed has to change the value of the 'lmfdb_label' for these rows, but as this is the key label column in all cases that could not be done in place.

Once someone else has taken a look and is happy, the 8 tables need to be copied to the production database.

**Comment by JohnCremona** [comment]
There are more problems with this new data still, requiring more work.

**Comment by JohnCremona** [comment]
After an update of all the curves of conductor over 500k I think this is now OK.

**Comment by AndrewVSutherland** [comment]
Shall I copy the ec_nfcurves to the cloud?  Are there other any tables that need to be copied?

**Comment by JohnCremona** [comment]
> Shall I copy the ec_nfcurves to the cloud? Are there other any tables that need to be copied?

Thanks: yes, ec_nfcurves is ready to go and closes #4323 and #4332.  For this issue the tables are ec_curvedata, ec_classdata, ec_localdata, ec_mwbsd, ec_galrep (no need for ec_iwasawa or ec_torsion_growth as no data in tere has changed).

**Comment by AndrewVSutherland** [comment]
@JohnCremona Done!

**Comment by JohnCremona** [comment]
> @JohnCremona Done!

Thanks -- I am keeping my fingers crossed,
