### ISSUE TITLE
Weight 1 cusp forms

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#437]

**Comment by jvoight** [comment]
The data is available at http://people.maths.ox.ac.uk/lauder/weight1/

**Comment by sehlen** [comment]
I'm working with George Schaeffer on integrating this data already + mod p
data that he computed.
We also received permission from Alan Lauder to use the data.
Coming soon to an lmfdb webpage near you.

**Comment by jvoight** [comment]
When it's ready and stable (this time next year?), we should be sure to contact Kevin Buzzard, Alan Lauder, and Frank Calegari so they can paw through it.

**Comment by sehlen** [comment]
That should go much faster (I'm rather thinking about a few weeks, but
we'll see).

Several checks will be run and we'll contact anyone who's interested.

Moreover, George has independently calculated data that we first meant to
use but then Alan Lauder published his data which is a) more complete and
b) gives already the eigenforms which George was about to compute.

**Comment by sehlen** [comment]
Let me add (and maybe that's what you meant) that maybe mod p might take a
little longer.

**Comment by JohnCremona** [comment]
Just making sure that all on this ticket are aware of my recent email to the shoe group concerning branches.  Should not be too much longer now...

**Comment by sehlen** [comment]
Ack.

**Comment by jvoight** [comment]
Comment from Alan Lauder about his data:

=====
Just to clarify a little the point I made to you on the representation of weight one newforms:

Each form is given as a pair [f,eps_data] where f is the q-expansion of the form over some field K to an "optimally chosen" precision q^m, and eps_data describes the character eps of the form via its image on generators for (Z/N)^* (N the level).

My point was that the field K is chosen to accommodate *all* the eigenforms for the character eps, not just f itself. So for example if f has rational Fourier coefficients, but S_1(N,eps) contains another eigenform defined over a bigger field, the parent of f will (I think) be given as this bigger field. (Also, eps of the generators for (Z/N)^* will be given as lying in this bigger field K, not Q(eps) itself.)

Thinking about this again, I don't suppose there is anything wrong with that: but it's worth being aware of.

A second point is that for some fields K it might be that O_K is not Z[a] for any element a in K. So here the Fourier coefficients of the form may look a bit ugly, and indeed it could be that there are better representations of the field K which make them look less ugly. But I haven't tried to find a "least ugly" representation of the field.

Thinking about this again, I don't suppose there is anything too wrong with that either.

Anyway, I think it is definitely worth bearing these two points in mind when preparing the lists of newforms for the database.
=====

**Comment by sehlen** [comment]
Thanks for the info @jvoight

**Comment by jvoight** [comment]
See also #59.  There wasn't much of a discussion there, but it should be taken into consideration when this is done.

**Comment by edgarcosta** [comment]
merging two other tickets: #59 , #436
- Since weight 1 cusp forms are both holomorphic cusp forms and eigenvalue 1/4
Maass forms, they should have their own special home pages, showing things like
"icosahedral". The new home page of a weight 1 cusp form would be a more natural friend
link from an Artin representation or a Hecke character, than the would the current holomorphic cusp
form or Maass form pages.
- On classical cusp forms top page, refer to Artin L-functions for weight 1

**Comment by AndrewVSutherland** [comment]
Addressed by #2717
