### ISSUE TITLE
L-functions for modular forms should be in database

### ISSUE THREAD

**Issue by jwbober** [LMFDB/lmfdb#439]

**Comment by sehlen** [comment]
Can you describe a more accurate description?

**Comment by edgarcosta** [comment]
Done

eg: 
* http://cmfs.lmfdb.xyz/L/ModularForm/GL2/Q/holomorphic/11/2/1/a/1/
* http://cmfs.lmfdb.xyz/L/ModularForm/GL2/Q/holomorphic/185/2/2/a/1/

**Comment by AndrewVSutherland** [comment]
Addressed by #2717.
