### ISSUE TITLE
L-function links on www redirecting to beta and download_zeros links causing server errors.

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4398]
Currently L-function links like https://www.lmfdb.org/L/EllipticCurve/Q/11/a/ are redirecting to beta pages like https://beta.lmfdb.org/L/2/11/1.1/c1/0/0.  We need to update the whitelist so this does not happen.

In addition, some of the old style download_zeros L-function links like

https://www.lmfdb.org/L/download_zeros/ModularForm/GL2/TotallyReal/2.2.12.1/holomorphic/2.2.12.1-47.1-b/0/0/

are throwing server errors when they should really redirect to https://www.lmfdb.org/L/download_zeros/4/6768/1.1/c1e2/0/0

**Comment by edgarcosta** [comment]
I have PR coming up finishing the first item.


I started to work on the second item, but then I realized that we should not redirect
https://www.lmfdb.org/L/download_zeros/ModularForm/GL2/TotallyReal/2.2.12.1/holomorphic/2.2.12.1-47.1-b/0/0/
to
https://www.lmfdb.org/L/download_zeros/4/6768/1.1/c1e2/0/0.
I think we should only support
`L/download*/<label>`,
as it will be quite painful to track down all the redirects in the L-functions code twice.
For example, the logic regarding old labels of classical modular forms and so on.
I also don't think, apart from bots, no one has saved these links download links.

I already wrote something that redirects `L/download_zeros/ModularForm/GL2/TotallyReal/2.2.12.1/holomorphic/2.2.12.1-47.1-b/`
to `L/download_zeros/4-6768-1.1-c1e2-0-0` (which will soon be supported), as the URL `ModularForm/GL2/TotallyReal/2.2.12.1/holomorphic/2.2.12.1-47.1-b` is in `lfunc_instances` try: https://teal.lmfdb.xyz/L/download_zeros/ModularForm/GL2/TotallyReal/2.2.12.1/holomorphic/2.2.12.1-47.1-b/.
However, I would like to scrape that, and I think we should only support `L/download*/<label>`

**Comment by AndrewVSutherland** [comment]
@edgarcosta I think what you propose is okay as long as we throw a 404 rather than a server error.
