### ISSUE TITLE
Integrate roadmap into issues/tickets, clean up for the public

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#441]
http://www.lmfdb.org/roadmap

David Farmer says the idea of the roadmap is to have a place for people to see what feature requests have been made.

**Comment by jvoight** [comment]
(I also don't think we should have the "completeness of data" sections here, since we have a new data quality scheme.)

**Comment by AurelPage** [comment]
working on it.

**Comment by AurelPage** [comment]
All the items of the roadmap have been deleted and/or turned into tickets. This can probably be closed now.
