### ISSUE TITLE
Weird parsing when searching for the 2nd moment in ST groups

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#4411]
It seems it doesn't support an open ended search.
`
Error: Error: 8- is not a valid input for second trace moment. It needs to be an integer (such as 25), a range of integers (such as 2-10 or 2..10), or a comma-separated list of these (such as 4,9,16 or 4-25, 81-121).
`

this should be an easy to fix

**Comment by AndrewVSutherland** [comment]
It's using a standard search array so I don't understand why this wouldn''t work.

**Comment by roed314** [comment]
I think it comes from the code that uses the second trace moment to refine the component group.  I'll fix it.

**Comment by AndrewVSutherland** [comment]
Fixed by #4412 and now live on www.lmfdb..org
