### ISSUE TITLE
Artin number field, Galois closure

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#4435]
On an Artin representation page, under Basic invariants the
Artin number field is always listed as the Galois closure of some field.
Even when that field is Galois.

But when the field is not Galois, the link to "Artin field" under Related
Objects still links to that field, not to its Galois closure.

The Projective field is sometimes listed as "Galois closure of..." and
sometimes not.   But on this one, it is Galois but doesn't realize that:
https://beta.lmfdb.org/ArtinRepresentation/2.2323.4t3.a.a
But when it is not Galois, the Related objects link goes to the non-Galois
field, for example:
https://beta.lmfdb.org/ArtinRepresentation/2.280853.3t2.a.a

It also is confusing (to me) that what are called "Artin number field" and
"Projective field" under Basic invariants, are called "Artin field" and
"Projective Artin field" under Related objects.

**Comment by jwj61** [comment]
I will leave it to @davidfarmer to close if the new version is ok

**Comment by davidfarmer** [comment]
I was going to close, because all items I mentioned seem to be addressed.  But I have a comment and a question.

It seems like something maybe has been lost.  Previously it might say "the Galois closure of X",
but now it says "Y", where Y is the Galois closure of X .  In the case where X = Y , i.e., X already
was Galois, then everything is fine.  But if X != Y, then X is no longer mentioned on the page. 
Is X still interesting in some way?  If it is, then should it have a name and get a mention?
(I don't know the answer to those questions, because I do not have a good enough understanding
of this topic.)

If I go here ( I just chose a non-Galois field, thank you for making that
easy with the new non-Galois search!)
    https://beta.lmfdb.org/NumberField/3.1.59.1
And then I follow the friend link to this Artin representation
    https://beta.lmfdb.org/ArtinRepresentation/2.59.3t2.a.a
then the links to the Artin stem field and Projective stem field are to the non-Galois field
I started with.  If I go to pink:
    https://pink.lmfdb.xyz/ArtinRepresentation/2.59.3t2.a.a
then it refers to the Galois closure of that field.

So, I am asking whether the version on beta is the intended result, or if those
links should be to the Galois closure.  (And if to the Galois closure, then my
questions in the 2nd paragraph above apply.)

One more thing:  it only says "Field" in the related objects box, and only has one line, when the
Artin stem field and Projective stem field are the same.  But it says "Field" twice
when they are different.  I realize there is not much space, but it does look odd.  For example:
   https://beta.lmfdb.org/ArtinRepresentation/1.875947.2t1.a.a
I don't have a suggestion for how to handle it.  Is "A-field" and "P-field" too cryptic?

**Comment by jwj61** [comment]
On the removal of "Galois closure of", that is matched by a change in knowl on the line preceding the field.  If it is Galois, then it says "Artin field"; if it is not Galois, then it says "Artin stem field", which is a different knowl.

On the labels in related objects, it is matching how things are done in other cases where there might just name the type of object and then (possibly) give its label, without detailing what the connection is.
