### ISSUE TITLE
Make available 10,000 coefficients of Delta

### ISSUE THREAD

**Issue by swisherh** [LMFDB/lmfdb#445]

**Comment by sehlen** [comment]
Fixed. We currently have 100001 and can easily increase this number of course.

**Comment by fredstro** [comment]
why does the webpage of 1.12.1a say 10005 instead of 100001? don’t we show the maximum?

**Comment by sehlen** [comment]
I see 100001. On beta and on my own copy.

**Comment by fredstro** [comment]
sorry, I was looking at 11.2.1a…

**Comment by JohnCremona** [comment]
Fantastic -- and one clock away from our home page we can see that they are available: http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/1/12/1/a/

Issue to be closed!
