### ISSUE TITLE
load balancing

### ISSUE THREAD

**Issue by alinabucur** [LMFDB/lmfdb#447]
Research more ip addresses, cloudflare and report.

**Comment by haraldschilly** [comment]
and discuss DNS setup with @davidfarmer …

**Comment by edgarcosta** [comment]
Close this issue?

This is the current setup:
<a href="https://raw.githubusercontent.com/edgarcosta/lmfdb-gce/master/setup/images/webserver.png"><img src="https://raw.githubusercontent.com/edgarcosta/lmfdb-gce/master/setup/images/webserver.png"  height="300"  ></a>

Where ms has 4 CPUs, 26 GB memory
and www-central* have 2 CPUs, 7.5 GB memory

**Comment by AndrewVSutherland** [comment]
Agreed, I think we are good (and have the ability to scale up in the future if needed).
