### ISSUE TITLE
Knowl with unallowed id

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#4473]
I wanted to make a comment on this knowl:

https://beta.lmfdb.org/knowledge/show/hgm.A2.2_B1.1.top

But when I tried, I got the error
Error: Oops, knowl id 'hgm.A2.2_B1.1.top.1614908298950735.comment' is not allowed. It must consist of lowercase characters, no spaces, numbers or '.', '_' and '-'.

The comment was going to be:
Either this knowl should have the formula for the Legendre family, or the words
"Legendre family" should be a knowl with that information.  And either way,
'Legendre family' might not be a sufficiently descriptive title for this knowl.

**Comment by roed314** [comment]
Resolved by #4486.
