### ISSUE TITLE
Order of torsion generators for ECNF

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#4481]
On https://www.lmfdb.org/EllipticCurve/2.2.17.1/17.1/a/4 I see something like
```
Torsion structure: | Z/2Z×Z/4Z
Torsion generators: | (0:−1:1) | (1/4a−1/4:−1/8a−3/8:1)
```
but the point (0,-1) is 4-torsion and the other listed generator is 2-torsion, so the generators are in the reverse order to the factors of the group `Z/2Z×Z/4Z`.

This would be more intuitive to the user if they always agreed, so it was easy to pick the right torsion generator just by looking at the LMFDB, it also seems that for EC/Q this is always the case.

Another approach would be to instead list the orders of the given generators next to each generator

**Comment by JohnCremona** [comment]
They are supposed to be in the same order so this is just some trivial bug in my data processing.  I will fix it. More time wasted.

**Comment by JohnCremona** [comment]
I am working on this now.  The number of curves affected should not be too great, as most have cyclic torsion and most of the non-cyclic ones are [2,2].  Overall, these are the non-cyclic torsion groups with frequencies:
    42 [2,10]
      3 [2,12]
      4 [2,14]
      1 [2,16]
      1 [2,18]
  52397 [2,2]
   5101 [2,4]
   1172 [2,6]
     95 [2,8]
    216 [3,3]
     10 [3,6]
     14 [4,4]
After ignoring the [n,n] cases that leaves 6429 curves which might be wrong.  Watch this space...

**Comment by JohnCremona** [comment]
Incidentally, here is how it happens -- something I and many other Sage users have been hit by many times, so I should not still be falling for it:
sage: R.<x> = PolynomialRing(QQ);  K.<a> = NumberField(R([-4, -1, 1]))                                                                                
sage: E = EllipticCurve([K([1,0]),K([-1,0]),K([1,0]),K([-1,0]),K([0,0])])                                                                             
sage: T = E.torsion_subgroup()                                                                                                                        
sage: [P.order() for P in T.gens()]                                                                                                                   
[4, 2]
sage: T.generator_orders()                                                                                                                            
(4, 2)
sage: T.invariants()                                                                                                                                  
(2, 4)

To get the order consistent you have to ask for T.generator_orders(), not T.invariants().  But if you want the orders in increasing order (by divisibility) then T.invariants() is right, so you may have to swap the gens over.

Over Q I work harder, making sure that the torsion generator(s) are minimal in string length (making sure that they are generators, with the order of the first dividng the order of the second when there are two), and then I compute the structure constant list as the list of orders of the generators.  But not over number fields...

**Comment by JohnCremona** [comment]
I have fixed the data on beta.  @alexjbest could you check to see if it looks OK to you?  Certainly the curve you mentioned is now good.  If so we can ask @edgarcosta to copy ec_nfcurves (just one table) to prod.

While I am thinking about generators I may apply the same transformation as I did over Q, first Minkowski-reducing the generators mod torsion and then adding torsion pints to minimise the string length.

**Comment by JohnCremona** [comment]
Also @edgarcosta please coul you copy over the 3 tables ec_curvedata, ec_classdata, ec_mwbsd since I have corrected generators, heights, regulator and sha for three curves of large conductor (the generator was not 3-saturated).  They are

**Comment by alexjbest** [comment]
Hi @johncremona, this looks great to me on beta, thank you!

**Comment by edgarcosta** [comment]
I will copy the tables now.

**Comment by edgarcosta** [comment]
The following 4 table have been copied to proddb: 'ec_curvedata',
'ec_classdata', 'ec_mwbsd', 'ec_nfcurves'

**Comment by JohnCremona** [comment]
Thanks!
