### ISSUE TITLE
CHM Label, 12T250

### ISSUE THREAD

**Issue by tdupu** [LMFDB/lmfdb#4499]
So I think the group label is off here in 12T250. 

    https://www.lmfdb.org/GaloisGroup/12T250

I think it should be [D(4)^3]S(3) not [D(4)^4]S(3). There is no action of S_3 on 4 elements. 

The order 3072 of the group on the right hand side is correct and the label D(4) wr S(3) seems correct.

**Comment by jwj61** [comment]
I agree that this does not make sense.  But, it is sticky since that is what GAP has as the name of the group.  As for the names in the paper, I can only get my hands on a preprint from Hulpke's home page and what we have matches what is in the paper.  If we change it, it is no longer the CHM label.

**Comment by jwj61** [comment]
Having looked at it for a few more moments, I think we will just correct the 4 to a 3 and email Hulpke since he may want to make the corresponding change in gap.

**Comment by tdupu** [comment]
Yeah, I'm not sure what to say. I have to work out a bunch of these so I will tell you if anything else comes up.   

How are the two labels on the page different? If these are automatically generated by gap shouldn't they both have this issue? Also, if it is a bug there has to be more, right?

**Comment by jwj61** [comment]
The two labels in that spot come from gap exactly as you see it.  It is also that way in a preprint of the paper (I can't access the final version).  I assume it is simply a typo of a 4 should be a 3.

**Comment by jwj61** [comment]
Fixed on beta.  Hulpke will update it in gap.
