### ISSUE TITLE
Knowl info does not match lmfdb data presentation

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#4506]
From the feedback page:

The explanation of the class group type doesn't match the input specs for searches in the number field database. The description states "a_{i+1} | a_i" whereas inputs to the class group structure require "a_i | a_{i+1}" (the example given is [2,4]).

**Comment by AndrewVSutherland** [comment]
This is just a typo in the know, which is now fixed on beta (the fix should propagate to the cloud automatically in a few minutes).
