### ISSUE TITLE
Port inventory descriptions into the API

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#4545]
The inventory (https://beta.lmfdb.org/inventory/) was very useful for porting from Mongo to Postgres, but it's now increasingly difficult to keep up to date.

I propose the following to merge useful functionality into the API:
1. Edit `meta_tables` to add two columns (`table_description:text` and `col_description:jsonb`), and update the backend code to handle this schema change
2. Update `create_table` and `add_column` to require a description argument, add `update_description` methods, etc.
3. Scrape the `inv_tables` and `inv_fields_humans` tables and add the descriptions into `meta_tables`
4. Update the API code to show this information in a useful way (a link at an annotated schema at the top of a table?)
5. Change the sidebar on beta to link to API instead of inventory

**Comment by AndrewVSutherland** [comment]
Can we close this now that the schema is shown in the api?

**Comment by edgarcosta** [comment]
@roed314, reopen if there is anything missing
