### ISSUE TITLE
Maass forms coefficients

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#456]
Under displaying coefficients for a form, there is a search box without any explanation of what an acceptable entry is or submit button

http://beta.lmfdb.org/ModularForm/GL2/Q/Maass/4f5558cb88aece2646000014

**Comment by lemurell** [comment]
This has been fixed. No search button is needed since it's filtering automatically. An explanation has been added, but it would be good if the explanation was reviewed so that it's informative enough. This is the same as #497 .
