### ISSUE TITLE
Deprecation warning from sage-9.3

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#4571]
I noticed that one line in lmfdb/nfutils/psort.py (which is a copy of a file in https://github.com/JohnCremona/sorting) needs a minor change to avoid a DeprecationWarning from the recently released Sage-9.3: just changed ``K.galois_group('gap').group()`` to ``K.galois_group()``.  But the changed code would not work with 9.2, so I'll fix this in a way which checks the current Sage version and adjusts if necessary -- unless there's a better way?

@roed314 will recognise this, as the author of https://trac.sagemath.org/28782.

**Comment by roed314** [comment]
I don't think there's a way that will work well in both 9.2 and 9.3.  I would use `K.galois_group(algorithm='gap')` in 9.3 if the field could ever have degree at least 12 (when Pari stops being able to compute Galois groups).

**Comment by JohnCremona** [comment]
Definitely not.  In fact right now it's only used for degree 2 where the line which uses this is completely trivial, but the code in psort is more general.

The use for BMFs is (1) to generate a list of prime ideals for displaying eigenvalues; (2) to construct an ideal from its label and vice versa for display.  This is only for imaginary quadratic fields of class number 1.

I'll do a special case for degree 2 for the line I just changed (which computes the set {1,2}).
