### ISSUE TITLE
Add BMFs for non-Euclidean imagainary quadratic fields of class number 1

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#4573]
We currently have Bianchi modular forms of dimension 1 only for the five Euclidean IQFs (for which modular symbol computations are simpler).  I will extend the data aset to include the four non-Euclidean fields of class number 1 (discriminants -19, -43, -67, -163) using a re-implementation of the theory developed in Elise Whitley's 1990 thesis being developed at https://github.com/JohnCremona/bianchi-progs with data in https://github.com/JohnCremona/bianchi-data.

Right now I had 2597 newforms over Q(sqrt(-19)) with level norm up to 10000, with associated elliptic curves, and will upload these soon, once I have modernised by Bianchi data upload scripts.  43 should not be far behind.

**Comment by JohnCremona** [comment]
Update 2021-06-02:  all ecnf and bmf data for 2.0.19.1 is uploaded and copied to production together with small code changes.  Now all ecnf and bmf data for 2.0.43.1 is also uploaded, so the tables ec_nfcurves, bmf_forms and bmf_dims also need copying.  There will also be another minor code change (PR imminent) but nothing breaks with the new data and current beta/prod branches.

**Comment by JohnCremona** [comment]
Update 2021-06-16: 2.0.19.1 now uploaded (both BMFs and elliptic curves) up to level/conductor norm 15000, 43 ditto up to 10000, 67 is still running and will go up to 10000 when finished, and 2.0.163.1 is finished and uploaded up to 1000 (that's only 10^3, not 10^4: this field is slower!).  I'll close this issue when I have uploaded data for 2.0.67.1 as then we'll have something for all the class number one fields.

**Comment by JohnCremona** [comment]
OK, there is now data on beta for all four of these fields, both rational BMFs of weight 2 and elliptic curves, with a norm bound of 15000, 10000, 10000, 1000.    I have updated the knowls regarding extent and origin, and tomorrow I'll add the remaining two fields to the search pages https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/ and https://beta.lmfdb.org/EllipticCurve/.

**Comment by JohnCremona** [comment]
I just uploaded more data for -163 (i.e. 2.0.163.1) for level norms 1001-5000, also elliptic curves to match.

Please could the tables ec_nfcurves, bmf_forms, bmf_dims be copied to prod?  Then this can be closed.  No code changes needed.

**Comment by AndrewVSutherland** [comment]
These tables have been copied over.  I think the completeness knowl also needs to be updated -- @JohnCremona if you want to take care of that I can review it and then close this issue.

**Comment by JohnCremona** [comment]
> These tables have been copied over. I think the completeness knowl also needs to be updated -- @JohnCremona if you want to take care of that I can review it and then close this issue.

Thanks for remembering, I'm on it now...

**Comment by JohnCremona** [comment]
https://beta.lmfdb.org/knowledge/show/rcs.cande.mf.bianchi
https://beta.lmfdb.org/knowledge/show/rcs.cande.ec
now have the updated bound for -163.

**Comment by AndrewVSutherland** [comment]
Reviewed and closed!
