### ISSUE TITLE
Use ~ to negate a search condition

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#4579]
In some settings, the negation of a supported search condition is not itself a supported search condition. One easy way to address this issue would be to impose the global convention that typing "~" at the beginning of the entry to any search box stands for the negation of whatever condition is defined by the rest of the text.

**Comment by JohnCremona** [comment]
Example? 

My own use cases would include searching on nontrivial Sha where now I put 2- (which I think does work) but with this suggestion would be ~1.

I have not thought through the implications or difficulties of implementation.

**Comment by kedlaya** [comment]
The example I had in mind is: for abelian varieties over finite fields, under certain conditions there is a "generic" answer for what the Galois group is, and I would like to exclude that one to see what exceptional cases occur.

**Comment by kedlaya** [comment]
And I was imagining a totally uniform mechanism for this across the LMFDB: in any search box, on any page, starting the entry with ~ means negate the condition defined by the rest of the text. This should be both easy for the user to understand/remember and easy to implement on the back end (just flip a switch in the underlying database query).

One question is what symbol to use for this. I reflexively used ~ in my original post, but ! is also a logical option given its meaning in C and other programming languages. But as long as it is a uniform behavior across LMFDB (and this use of the chosen symbol doesn't interfere with any specific query formats), it shouldn't matter too much which symbol it is.

**Comment by edgarcosta** [comment]
To be clear, you propose searching on `key=~2,5` means 'key not in {2,5}'?

**Comment by roed314** [comment]
In terms of implementation, there's a convenient place to put the parsing code (in the `__call__` method for `SearchParser`), but negating just part of a query can get tricky.  For example, we have a `collapse_ors` method that tries to FOIL out ors, and some optimizations (see the `_split_ors` method in `lmfdb/backend/search_table.py`).  It should be doable, but I don't think it's completely trivial.

**Comment by kedlaya** [comment]
> To be clear, you propose searching on `key=~2,5` means `key not in {2,5}`?

Correct.

**Comment by edgarcosta** [comment]
Checkout red.lmfdb.xyz and the PR #4607

**Comment by kedlaya** [comment]
That behaves as expected on the example that I originally had in mind (see above).

**Comment by jwj61** [comment]
I tried a variety of inputs on number fields and they worked.

**Comment by AndrewVSutherland** [comment]
This is now live on beta

**Comment by roed314** [comment]
It would be great if people could look at https://beta.lmfdb.org/knowledge/show/intro.search, which has some instructions for searching.  I'm sure it can be improved.
