### ISSUE TITLE
Allow users to view all curves (when available)

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4582]
For isogeny classes of abelian varieties like

https://www.lmfdb.org/Variety/Abelian/Fq/2/19/ae_w

where we know all the curves whose Jacobians lie in this isogeny class, we only show the first 20 (which is fine), but there seems to be no way for a user to view the other 26, even though they are stored in the database, as you can see here:

https://beta.lmfdb.org/api/av_fq_isog/?label=2.19.ae_w

We should provide an option for the user to see a list of all the curves stored in the database, either by expanding the list in place, or by providing a link to another page, or providing a download link.

There also are no download options, which would provide another way to get all the curves (and surely the best way when there are thousands of them), but I will raise a separate issue for this.

**Comment by AndrewVSutherland** [comment]
In cases where we know there are both hyperelliptic and non-hyperelliptic Jacobians I think it would be nice to show examples of both in the list of 20 that appears.  https://www.lmfdb.org/Variety/Abelian/Fq/3/5/a_e_g is an example of a case where this does not happen.  Only 23 of the 62 Jacobians in this isogeny class are hyperelliptic, but there is no way to know that from looking on the page (it might also be nice to say how many Jacobians are hyperelliptic, e.g. on the line that lists the number of Jacobians add a parenthetical (of which n are hyperelliptic).

**Comment by roed314** [comment]
#4604 allows the user to see all the curves and displays how many hyperelliptic/nonhyperelliptic there are, though it doesn't change the order to display some of each in the first 20 (I don't think that feature is worth the trouble given the counts).  Aside from the download requested in #4583, is there anything else that needs to be addressed here?

**Comment by edgarcosta** [comment]
@poonen, please take a look and let us know if you see something else that needs to be addressed.
