### ISSUE TITLE
Download option for abelian varieties over finite fields

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4583]
There should be a Downloads box on the home page of each isogeny class of abelian varieties over a finite field that, at a minimum, provides a "Download all data to text" option.

**Comment by AndrewVSutherland** [comment]
There should also be an option to download all curves whose Jacobians lie in this isogeny class, whenever that information is available.

**Comment by BarinderBanwait** [comment]
I've added the minimum "All stored data to text" option, viewable on pink, e.g. :

https://pink.lmfdb.xyz/Variety/Abelian/Fq/5/3/ac_f_ac_ab_p

Which other options can be added? In particular, what about options like "X to Magma"/"Y to Sage"?

**Comment by edgarcosta** [comment]
Allowing the user to only download the curves, one per line, might be useful.
I don't see anything useful that one would want to download to Magma or Sage.

ps: there is a linting error: `lmfdb/abvar/fq/download.py:12:20 undefined name 'abort'`

**Comment by BarinderBanwait** [comment]
I think this issue can be closed now?
