### ISSUE TITLE
Download link for curves in a finite field abelian variety isogeny class when too many to display

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#4584]
On https://www.lmfdb.org/Variety/Abelian/Fq/2/19/ae_w it gives 20 curves whose Jacobians lie in this isogeny class and notes that there are 26 more.  We have the data, but there's currently no way to access it from the LMFDB.  There should be a link to download all of them somewhere.

**Comment by AndrewVSutherland** [comment]
I think this is already covered by #4582 and #4583.
