### ISSUE TITLE
Search for squarefree AVs over finite fields

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#4587]
In the (big) search box for abelian varieties over finite fields, we have options to specify that the AV is simple (or not) or geometrically simple (or not). It would also be natural to add squarefree (or not), and possibly also geometrically squarefree (or not).

As an interface matter, it might make sense to put all of these into a single selector menu rather than having separate choices for each; but let's not consider that part of this issue since there is already a backend matter here (I don't think "squarefree" is a field in the database at present).

**Comment by BarinderBanwait** [comment]
Hi @edgarcosta thanks for putting the field `squarefree` into `db.av_fq_isog`.

If it's OK, I'd like to rename this to `is_squarefree` to reflect the existing dichotomy `is_simple`/`is_geometrically_simple`. 

I'd also like to add `is_geometrically_squarefree` as a column to this table. I'd like to learn how to do this in general, so would you be able to help me do this? Here's what I thought of doing (but I won't do it without any guidance for fear of breaking the table!):

```
from lmfdb import db
db.av_fq_isog.add_column('is_geometrically_squarefree','jsonb')

R.<x> = QQ[]

def add_is_geometrically_squarefree(rec):

    f = R(rec['poly'])
    # not sure this is correct, just a guess!
    L.<a> = NumberField(R(rec['geometric_splitting_polynomials']))
    rec['is_geometrically_squarefree'] = f.base_extend(L).is_squarefree()
    return rec

db.av_fq_isog.rewrite(add_is_geometrically_squarefree)
```

**Comment by edgarcosta** [comment]
it looks good to me with the exception that column type should be `bool` instead of `jsonb`.

**Comment by edgarcosta** [comment]
Given that you will be running a rewrite, you can also use that opportunity to add the column `is_squarefree` and copy the data from `squarefree`, and then delete the old column.

Also, when adding columns you must provide a description, e.g., for `squarefree` at the moment we have `True iff there are no repeated factors in the isogeny class decomposition, i.e., simple_factors == simple_distinct`

**Comment by roed314** [comment]
For `av_fq_isog`, it's also good to update the code that generates the data (see https://github.com/roed314/abvar-fq/blob/master/isogeny_classes.sage#L2452 for example).

**Comment by BarinderBanwait** [comment]
Thanks David and Edgar for your comments; @roed314 I'll update that code on your github when I've worked on this issue.

@edgarcosta While copying over the data from `squarefree` to the new `is_squarefree` I hit an `OSError: [Errno 28] No space left on device` at this point: `430000 of 2945722 records (14.6 percent) dumped in 633.765 secs`, this is on legendre.

Also, I've been thinking about the code in my previous comment to determine `is_geometrically_squarefree`:

```
def add_is_geometrically_squarefree(rec):

    f = R(rec['poly'])
    # not sure this is correct, just a guess!
    L.<a> = NumberField(R(rec['geometric_splitting_polynomials']))
    rec['is_geometrically_squarefree'] = f.base_extend(L).is_squarefree()
    return rec
```

After playing with some examples, this doesn't seem correct; for example, [this abelian variety](https://www.lmfdb.org/Variety/Abelian/Fq/2/2/ad_f) becomes isogenous to a square geometrically, but the code above - viewing the L-polynomial over the "geometric splitting polynomial" and seeing whether that's squarefree - would conclude that this variety is geometrically squarefree. The geometric splitting data presented on that page seems to be coming from `db.av_fq_endalg_factors`, so the following should be correct:

```
def add_is_geometrically_squarefree(rec):
    return 2 in {factor['multiplicity'] for factor in list(db.av_fq_endalg_factors.search({"base_label": rec['label'],
                                                      "extension_degree" : rec['geometric_extension_degree']}))}
```

But perhaps there's a more direct/faster way which doesn't involve a db lookup in another table?

**Comment by JohnCremona** [comment]
I should probably not chime in as I have not followed this, but the square-free-ness of a polynomial is not affected by base-change (at least over perfect fields).

**Comment by edgarcosta** [comment]
I will chime on this later on, but I'm really confused about how you
managed to trigger running out of space.

**Comment by AndrewVSutherland** [comment]
@edgarcosta We have plenty of free space on /scratch on both grace and legendre (and on the database disks on grace), so I think this must have been something internal to Postgres or a temporary file on another disk.

**Comment by BarinderBanwait** [comment]
@JohnCremona thanks for chiming in and pointing out my mistake --  yes indeed, this follows from Galois theory, so that first approach above won't work, and the second one above is also currently incorrect, I think it should be

```
def add_is_geometrically_squarefree(rec):
    return {1} == {factor['multiplicity'] for factor in list(db.av_fq_endalg_factors.search({"base_label": rec['label'],
                                                      "extension_degree" : rec['geometric_extension_degree']}))}
```

@edgarcosta All I ran was:

```
from lmfdb import db
desc = "True iff there are no repeated factors in the isogeny class decomposition, i.e., simple_factors == simple_distinct"
db.av_fq_isog.add_column('is_squarefree','bool', description=desc)


def add_is_squarefree(rec):
    rec['is_squarefree'] = rec['squarefree']
    return rec

db.av_fq_isog.rewrite(add_is_squarefree)
```

I'll try it again.

**Comment by edgarcosta** [comment]
Ok, I figure it out.

1- on rewrite please specify a `searchfile` in your home directory, otherwise tries to write to `/tmp` which only has a couple of GB free.

2- please do the add `is_squarefree` before the other one

3- For `is_geometrically_squarefree` you first should check if it is geometrically simple, that tackles 86% of the abelian varieties. Then you can do something similar to what  you are proposing, in particular, I would do:
```
return db.av_fq_endalg_factors.lucky({"base_label": rec['label'],
    "extension_degree" : rec['geometric_extension_degree'],
    "multiplicity": {"$gte": 2}}) is None
```

4- the reason why the older code was giving wrong out out, as you needed to check if 
`det(1 - t Frob^m)` was squarefree with `m = rec['geometric_extension_degree']`.

**Comment by BarinderBanwait** [comment]
Thanks Edgar for the pointers and correction -- i'll run `is_squarefree` again with a `searchfile`

**Comment by BarinderBanwait** [comment]
I've copied `squarefree` into `is_squarefree`, removed the old `squarefree`, and added `is_geometrically_squarefree`. Corresponding knowls have been added.

I've added the two new 'Yes/No' search options to the browse and refine search tables, which you can see on [pink](https://pink.lmfdb.xyz/Variety/Abelian/Fq/). I wasn't quite sure how to present these options; the easiest thing to do was just add them to the advanced options.

However, in an attempt to have all of the 'Yes/No' boxes appear together in the second column of the browse search array, I promoted two of the advanced search options to normal search options; these are 'Angle rank' and 'p-rank deficit', and the new 'Squarefree/Geometrically squarefree' options are paired with 'p rank/p rank deficit'. This has added four new 'normal' search options which one could argue is too much.

This has an effect in the ['refine search'](https://pink.lmfdb.xyz/Variety/Abelian/Fq/?search_type=List) array, where the lists are now 7 columns long rather than the previous 5. This could be considered too long.

I also reordered some of the search options here so that all of the advanced options appear below the normal ones.

Anyway do let me know how you think it looks and/or how it should be done.

**Comment by edgarcosta** [comment]
I strongly dislike using 7 columns in refine search.

One way to not add more entries to the table would be to search on: Decomposition and Geometric Decomposition.
And the options would be: squarefree, not squarefree, simple, not simple
However, this is much more cryptic...

Maybe @AndrewVSutherland @roed314   have a better suggestion?

**Comment by kedlaya** [comment]
Although this is not a common use case, that would rule out the possibliity of searching for "squarefree but not simple".

**Comment by edgarcosta** [comment]
good point, we could just add that, but I still wonder if "Decomposition" might be too cryptic.

**Comment by JohnCremona** [comment]
> good point, we could just add that, but I still wonder if "Decomposition" might be too cryptic.

Surely it is clear enough what Decomposition and Geometric Decomposition mean, and anyway these can have knowls?  (I'm assuming that they mean decomposition up to isogeny over the base field and over the algebraic closure.)

**Comment by edgarcosta** [comment]
Correct

**Comment by BarinderBanwait** [comment]
"Decomposition and Geometric Decomposition" seem to suggest rather more options than just "is/is not simple" and "is/is not squarefree"; and indeed in the "advanced search options" there is an area where the user can specify Decomposition, or even Geometric Decomposition if they tick that box.

Using fewer columns in the refine search is easy; it'll just mean more rows (which admittedly is also objectionable - I can see a case to be made for having only two rows of normal options, so a maximum of 10 such options; although I note that the ECQ refine search table has 5 rows ...).

**Comment by edgarcosta** [comment]
Yes, one can associate more things with those fields, but a simple select box indicates a limited and reasonable amount of options and doesn't contradict the more advanced searches.
More rows also sounds fine.
The reason why I strongly dislike using more columns, is that it makes the website quite wide (min width 1780px), and it is quite hard to scroll horizontally without a touchpad.

I have also realized that I misled you in the definition of squarefree as forgot to account for the nonordinary cases, and that is reflected in the knowls that you wrote. Squarefreeness is defined in terms of decomposition https://beta.lmfdb.org/knowledge/show/av.decomposition, and not simply in terms of the polynomial factorization, as not every minimal polynomial of q-Weil number arises as an isogeny class, sometimes one needs to take powers to achieve the minimal dimension prescribed by the q-Weil number.  Perhaps the easiest example is that (1 +- px)^2 over F_{p^2} is the Frobenius polynomial of a geometrically simple (and squarefree) abelian variety.

**Comment by edgarcosta** [comment]
While discussing this with @roed314 we noticed that "Angle rank" and "p-rank deficit" got promoted and they should still stay in the advanced search only.
Furthermore, what about a single select box (in advanced search) that has the following options:
```
<blank>
 yes
 yes; and geom. 
 yes; not geom. 
 no 
 not geom.
 ```

**Comment by kedlaya** [comment]
Something like that would work, sure.

**Comment by BarinderBanwait** [comment]
The latest commit on [pink](https://pink.lmfdb.xyz/) has done the following:

1. Corrected the knowls by removing the stuff about squarefree polynomials in them;
2. Reverted 'Angle rank' and 'p-rank deficit' to advanced;
3. Removed the 'Squarefree/Geometrically squarefree' options, and replaced with an advanced '(Geometric) Decomposition' box with the options @edgarcosta listed above

I'll open a PR with these changes

**Comment by edgarcosta** [comment]
The rest of the discussion can be moved to the PR #4708
