### ISSUE TITLE
Tests broken with flask 2

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#4592]
https://github.com/pallets/werkzeug/issues/2148 seems to cause issues with global random search, the double redirect causes the test https://github.com/LMFDB/lmfdb/blob/master/lmfdb/tests/test_homepage.py#L64 to fail.
Currently CI is working fine on lmfdb as the conda environment is cached and still using flask 1.1.4, but on forks which didn't have an existing cache the latest pypi release >2.0 is installed (https://pypi.org/project/Flask/#history) and the tests fail e.g. https://github.com/alexjbest/lmfdb/runs/2732245524.
For now we can just wait and see if the flask issue gets resolved soon, otherwise we can specify the flask version in the environment.yml or requirements.txt ?
I guess if someone ends up with flask version 2 locally the tests will also fail for them which will be confusing, but I can't think of any workaround, maybe updating requirements is the way to go?.

**Comment by edgarcosta** [comment]
We should update environment.yml or requirements.txt  immediately.
