### ISSUE TITLE
Data quality for L-functions of genus 2 curves

### ISSUE THREAD

**Issue by alinabucur** [LMFDB/lmfdb#461]
Ask Andy Booker and Drew Sutherland.

**Comment by jvoight** [comment]
@AndrewVSutherland Should we do something about this before 1.0?  We already provide a link to the paper, where each issue is discussed.  I can't find an example where data quality is dealt with explicitly in the LMFDB right now.

**Comment by AndrewVSutherland** [comment]
I don't have time to do anything about it right now, but I think this 
can wait until after the code freeze in any case.

**Comment by davidfarmer** [comment]
Subsumed by #426
