### ISSUE TITLE
feature request : search option "twist-minimal" in modular forms

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#4627]
HI!

It would be great to be able to search with a twist-minimality criterion. I am guessing that this should be easy as the information is already in the database. Maybe the only problem would be to avoid cluttering the modular forms search form.

Thanks!

**Comment by edgarcosta** [comment]
Yes, restricting the search to only twist-minimal modular forms should be fairly easy.
The hard part is to what should we pair it with? Can you think of something else useful to search regarding the twist class?

**Comment by AurelPage** [comment]
Maybe it would be merged with self-twists? A "Twists" section with 3 selectors : CM, RM, minimality ?

**Comment by AndrewVSutherland** [comment]
It would also be useful to be able to restrict to forms that are their own minimal twists (meaning they are the representative of their twist class with minimal label -- in general there may be more than one twist minimal form in a twist class but only one of them is the designated "minimal twist" for the class) -- doing this effectively allows you to search twist classes, which would also be relevant for stats.

Squeezing 3 selectors into a single "twists" section won't really fit (and being twist minimal or the minimal twist is really independing of having CM or RM, whether you have non-trivial self twists or not doesn't really play a role in deciding whether you are twist minimal).

I could see getting rid of the search filter on number of coefficient ring generators (does anyone actually use this?).  I think it is there only to support stats, but I think we are getting to the point where requiring stats options to correspond to search options is overly constraining, it would be nice to decouple this (either by not providing a link on the stats page, or providing a search results page that is customized for stats, e.g. only show the options that were actually used to create the stats, which might include options that are not there by default).

But I'd be curious to know what @jvoight and @roed314 think.

**Comment by roed314** [comment]
Why not just copy what was done for abelian varieties and have "Advanced Search" options?

**Comment by assaferan** [comment]
@AurelPage, @roed314, @AndrewVSutherland - the feature seems to have been added by now, so I'm closing this issue.
