### ISSUE TITLE
Newly added discriminants of EWNF display badly

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#4641]
See https://www.lmfdb.org/EllipticCurve/2.0.163.1/289.1/a/4 where the discriminant ideal (17) displays as (17.0000).

It's in the data, for many of the curves recently added over 2.0.d.1 for d in {19,43,67,163}.  I'll fix it.

**Comment by JohnCremona** [comment]
Data fixed on beta.

@AndrewVSutherland please could you copy ec_nfcurves again?  Sorry for the extra work.

**Comment by edgarcosta** [comment]
I will take care of it.

**Comment by AndrewVSutherland** [comment]
already done

**Comment by JohnCremona** [comment]
> already done

Fantastic, thanks -- and again sorry
