### ISSUE TITLE
Links to the corresponding API page

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#4662]
Most (all?) object pages in the LMFDB have a main corresponding entry in some database table (though some of them also draw data from auxiliary tables).  It would be nice to have a link to the corresponding API page(s) in the Downloads section.  So, for example, the number field page [8.0.568002355840000.24](https://beta.lmfdb.org/NumberField/8.0.568002355840000.24) would have a link to the corresponding [API result](https://beta.lmfdb.org/api/nf_fields/?label=8.0.568002355840000.24).  When there are auxiliary tables, I think we would ideally have links there as well.  So, for example, the elliptic curve page [11.a3](https://beta.lmfdb.org/EllipticCurve/Q/11/a/3) would link not just to the [curvedata record](https://beta.lmfdb.org/api/ec_curvedata/?lmfdb_label=11.a3) but also to the [localdata record](https://beta.lmfdb.org/api/ec_localdata/?lmfdb_label=11.a3), the [classdata record](https://beta.lmfdb.org/api/ec_classdata/?lmfdb_iso=11.a), the [galrep records](https://beta.lmfdb.org/api/ec_galrep/?lmfdb_label=11.a3), the [mwbsd record](https://beta.lmfdb.org/api/ec_mwbsd/?lmfdb_label=11.a3), the [2-adic record](https://beta.lmfdb.org/api/ec_2adic/?lmfdb_label=11.a3), the [Iwasawa record](https://beta.lmfdb.org/api/ec_iwasawa/?lmfdb_label=11.a3), and the [torsion growth records](https://beta.lmfdb.org/api/ec_torsion_growth/?lmfdb_label=11.a3).

**Comment by AndrewVSutherland** [comment]
I think this is a good idea, but in your second example I don't think we want to have a separate link for each record.  It would be better to have a single "data" link (e.g. in the downloads box) that takes you to a page where all of these records are shown. I realize it would take a bit more work to do this, but it wouldn't be that hard to implement a page that takes a variable length list of table/key pairs, and in this particular example it would actually be really handy to be able to see all the records on the same page.

**Comment by roed314** [comment]
This is now live in production.
