### ISSUE TITLE
Knowl listing the Sato-Tate groups for genus 2 curves.

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#467]
It would be good to give details about the possible groups, similar to how Galois groups are handled.

**Comment by kedlaya** [comment]
I edited the general "Sato-Tate group of a genus 2 curve over Q" knowl, but I don't think this answers your concern. Can you link to a specific example illustrating the Galois group case?

**Comment by jvoight** [comment]
Kiran's edits to the knowl are pretty good.  David, what did you have in mind for this?  I really would rather farm this out to the paper itself, where the tables and meaning are quite clear.

**Comment by jvoight** [comment]
This has received no further comments, so I am closing it.  (David, if you disagree, you can reopen it, but issues of the form "it would be good to" do not deserve a 1.0 milestone.)

**Comment by davidfarmer** [comment]
I'd like to see something similar to the Galois group knowls, which tell you specific information
about that group.  I realize it will be tedious to implement that, so I am reopening,
removing the milestone, and adding "feature request", which is code for "yes it would
be nice to do that but it isn't going to happen soon."

**Comment by jvoight** [comment]
I'm not sure how to do this in a "nice" way, and more fundamentally I don't know why everything has to be knowlified.  Papers are the currency of mathematics, and having the LMFDB interact with the literature in a meaningful way seems completely natural.  In particular, certain complicated things--like this list--need explanation and reference.  

So dude, it's fine as a 'feature request' whatever that means: I see it as incredibly low priority.

**Comment by AndrewVSutherland** [comment]
As discussed with David and John, the plan is to make Sato-Tate groups bonafide LMFDB objects with their own home pages that we can link to.  I am planning to work on this over the weekend.

**Comment by AndrewVSutherland** [comment]
Closing this now that Sato-Tate groups are objects in the database.
