### ISSUE TITLE
Page Not Found redirects to beta

### ISSUE THREAD

**Issue by jenpaulhus** [LMFDB/lmfdb#4700]
It is possible this is working as intended, but if I go to www.lmfdb.org and try to go to a link that doesn't exist like www.lmfdb.org/junk,  it redirects me to beta to tell me that the page was not found.  This doesn't seem to happen if I type a nonsense urls for the individual sections (like EC or HGCWA).

**Comment by AndrewVSutherland** [comment]
This is working as designed (whether that design is optimal is a separate question, I'm just noting that this is not a bug).  Do you think it should behave differently?

**Comment by jenpaulhus** [comment]
It was a little strange that the sidebar changed. I'm not sure if it's better or worse, just unexpected for me. It made me wonder whether I had typed the 2nd part of the URL wrong  or if I had accidentally been in beta from the start.

**Comment by AndrewVSutherland** [comment]
The tricky part here is that we want to redirect routes like https://www.lmfdb.org/Motive/Hypergeometric/Q/ which are not yet in production to beta, but it is a pain (and high maintenance) to keep track of all the routes that are not valid in production but might be valid on beta, so we just redirect anything that we know is not valid on production.

I agree that it would be a better user-experience to just throw a 404 on URLs like https://www.lmfdb.org/junk, and if there is an easy way to do that, I would be in favor.  Do you have any thoughts on this @edgarcosta?

**Comment by AndrewVSutherland** [comment]
I discussed this issue with @edgarcosta and I think he has a plan to address it, is that correct @edgarcosta ?

**Comment by edgarcosta** [comment]
I think this now works as expected. Please reopen if you disagree.
