### ISSUE TITLE
Formatting q-expansions

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#4722]
<img width="469" alt="Screen Shot 2021-08-27 at 3 14 36 PM" src="https://user-images.githubusercontent.com/4120797/131193882-889b76f8-21c2-4565-b92f-df930756dbc7.png">

What's up with the drop from the equals sign to the q-expansion on
  http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/510/2/a/a/
? 

I'm getting the issue on Safari and Firefox (on a Mac).

**Comment by alexjbest** [comment]
It was on our side, the katex version is pinned actually, so the only breakage there will come from browser compatlibility changes.
