### ISSUE TITLE
Correct links for 17-congruent curves of conductor 47775

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#4729]
From the Bugreport on 2021/8/31:

The elliptic curve 47775.d1 is listed as a curve having a minimal 17-congruence, whereas the description links to the elliptic curve 47775.be1 as the curve of interest. Notice that the Cremona label of 47775.d1 is 47775be1. The descriptions on www.lmfdb.org/EllipticCurve/Q/interesting for both 47775.d1 and 47775.be1 are duplicates.

**Comment by AndrewVSutherland** [comment]
I can confirm that the elliptic https://www.lmfdb.org/EllipticCurve/Q/47775/d/1 with Cremona label 47775be1 is **not** 17-congruent to the elliptic curves https://www.lmfdb.org/EllipticCurve/Q/47775/be/1 (Cremona label 47775cq1) and https://www.lmfdb.org/EllipticCurve/Q/3675/g/1 (Cremona label 3675k1), which do appear to be 17-congruent to eachother.

The knowl https://beta.lmfdb.org/knowledge/edit/ec.q.47775.d1.bottom should be deleted (click the delete link at the top of the edit screen to do this).

p.s. "47775.be1" is not a Cremona label, you meant to type "4777be1" :)

**Comment by JohnCremona** [comment]
I'm onto it

**Comment by JohnCremona** [comment]
The paper of Tom Fisher cited in the knowl is to a paper on 7- and 11-congruences, not the newer one on 17-congruences.  In in that older paper he gives incorrect labels for the pair of 17-congruent curves (he gives 3675b1 and 47775b1, which are wrong even with a dot inserted).  The correct labels are (LMFDB) 3675.g1 and 47775.be1 (or Cremona 3675k1 and 47775cq1).

The knowls are on the correct curve home pages.  It is intentional that both have the same text.

There are two correct knowls (ec.q.3675.g1.bottom and ec.1.47775.be1.bottom) but also a wrong one (ec.q.47775.d1.bottom) which I just deleted.

I think that's all that was required.  This can be closed once the deletion has migrated to prod.
