### ISSUE TITLE
Zeta zero might be wrong

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#4785]
From the feedback page:

I have checked many zeros using a new method but find an issue with the 26th zero. 92.......

**Comment by davidfarmer** [comment]
Well, their method has a problem, because

92.4918992705584842962597252418105

is indeed the imaginary part of a zero of the zeta function.

**Comment by edgarcosta** [comment]
The table http://www.dtc.umn.edu/~odlyzko/zeta_tables/zeros2

gives us an approximation of the 26th zero

92.491899270558484296259725241810684878721794027730646175096750489181

Which matches ours until the last digit

92.4918992705584842962597252418105


And the difference is 1.8x10^-31, which is within our accuracy window.

**Comment by JohnCremona** [comment]
I think that if I computed a zeta zero and my result differed from Odlyzko's, I would get debugging rather than doubt Odlyzko!

**Comment by davidfarmer** [comment]
I will write to the person.
