### ISSUE TITLE
History of Modular Forms

### ISSUE THREAD

**Issue by brianconrey** [LMFDB/lmfdb#479]
We need a gentle introduction to modular forms, with a historical emphasis (Klein, Fricke, Poincare?)
together with subsequent developments. At what point did these meet up with number theory/ L-functions? etc. Written to keep Bill Browser reading for as long as possible.

**Comment by jvoight** [comment]
How about http://gerard.vdgeer.net/schier06.pdf?  This seems to cover a lot of bases; we could summarize and link to it?  Or ask to repost part of it?

**Comment by davidfarmer** [comment]
In the past we have always decided not to link to outside sources
for background material.  But in whatever material we eventually have
in the LMFDB, there should be references, and those references can
have links to the outside.

**Comment by davidfarmer** [comment]
Closing because of issue #1022 
(although it only covers classical modular forms.  one could submit separate issues for each
type of modular form history)
