### ISSUE TITLE
Group pages take too long to load

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4791]
https://beta.lmfdb.org/Groups/Abstract/1.1 typically takes 3-5 seconds to load.  It needs to be a lot faster than this  (its okay if some of the more complicated  pages take longer, but a simple page like this should not take more than 400-500 ms, compare to number fields, for example).  I don't think we can put groups into production until this issue is addressed.

**Comment by roed314** [comment]
There were no indexes for `gps_char` and `gps_qchar`.  I added a few, and now pages are faster to load.

**Comment by AndrewVSutherland** [comment]
Page load times are back up to 3-4 seconds (even for the trivial group) since the recent data update.  Is there an index that needs to be added/rebuilt?

**Comment by roed314** [comment]
I added an index to `gps_groups_cc` (which became more important now that we have a lot more conjugacy classes overall).  That brings the load times down to something more reasonable.  I'm going to leave this issue open for now.

**Comment by AndrewVSutherland** [comment]
I think this is in pretty good shape now, I'll plan to review and either close or identify specific areas for improvement soon.

**Comment by AndrewVSutherland** [comment]
The times to load random groups now seem on par with other sections of the LMFDB (e.g. number fields, elliptic curves), typically 1-2s on beta.  Of course they could always be faster but I think this is good enough to consider it production ready as far as page load times go (some queries may need further optimization, but if so that should be a separate issue).
