### ISSUE TITLE
Merge siegelfix branch after ensuring no functional regressions

### ISSUE THREAD

**Issue by wbl** [LMFDB/lmfdb#480]
This branch https://github.com/wbl/lmfdb/tree/siegelfix contains some high level UI changes and code redesign. It needs to be made into a mergable state with no functionality regressions before much work on Siegel forms can continue.

**Comment by davidfarmer** [comment]
Are you going to submit a pull request?

**Comment by wbl** [comment]
See https://github.com/LMFDB/lmfdb/pull/518
