### ISSUE TITLE
Varieties

### ISSUE THREAD

**Issue by brianconrey** [LMFDB/lmfdb#481]
Currently Varieties on the LHS is NOT a link. It should be. Once it is we need an introduction to varieties
written. When did we first get the idea of the importance of varieties to number theory and L-functions. 
What are the Weil conjectures? What did Dwork do? What is the Hasse-Weil zeta-function? What
progress has been made? Where does Fermat's Last Theorem fit into this story? A gent;e introduction designed to entice Bill Browser to read well into it (all of it?).

**Comment by davidfarmer** [comment]
Please submit a pull request for each of the missing top-level categories 
which are not currently links..

**Comment by jvoight** [comment]
A concise description of each of the subcategories would also be helpful to orient the new visitor to the LMFDB to give an indication of how the various types of objects play, what they are, etc.

**Comment by AndrewVSutherland** [comment]
Varieties now does have a link that gives a brief description, see www.lmfdb.org.  Like all headings (except L-functions) there is no "history of" link.   I will create a new issue for this (with a 2.0 milestone) but I am going to close this one.
