### ISSUE TITLE
A few more annotations for genus 2 curves

### ISSUE THREAD

**Issue by jbalakrishnan** [LMFDB/lmfdb#4849]
@jbalakrishnan Thanks!  I marked the knowl as reviewed, so I think we are good to go.  Please feel free to add annotations as and when you think they make sense.  In cases like this where we need to update the rat_pts_v flag to show that the set of rational points is provably complete, you can raise an issue as you did here and we can update it.

_Originally posted by @AndrewVSutherland in https://github.com/LMFDB/lmfdb/issues/4813#issuecomment-947103802_

Thanks @AndrewVSutherland ! I added annotations for the following curves:

https://beta.lmfdb.org/Genus2Curve/Q/4489/a/4489/1   (67)
https://beta.lmfdb.org/Genus2Curve/Q/5329/b/5329/1   (73)
https://beta.lmfdb.org/Genus2Curve/Q/10609/a/10609/1 (103)
https://beta.lmfdb.org/Genus2Curve/Q/11449/a/11449/1 (107)
https://beta.lmfdb.org/Genus2Curve/Q/27889/a/27889/1 (167)
https://beta.lmfdb.org/Genus2Curve/Q/36481/a/36481/1 (191)
https://beta.lmfdb.org/Genus2Curve/Q/35344/a/565504/1 (C188)
https://beta.lmfdb.org/Genus2Curve/Q/8281/a/8281/1 (91)

where various people have computed rational points. So if it'd be possible to update the rat_pts_v flag for these, that'd be great!

**Comment by AndrewVSutherland** [comment]
Thanks Jen!  I've updated the relevant records and updated the production database as well (see https://www.lmfdb.org/Genus2Curve/Q/4489/a/4489/1, for example).
