### ISSUE TITLE
Fields

### ISSUE THREAD

**Issue by brianconrey** [LMFDB/lmfdb#485]
Currently Fields is not a link. It needs to be one. Once it is a link it needs to have an article written.
Historical as well as informative. Who came up with the idea of a field? What dod the early theroy look like? What is the difference between a local field and a global field and who thought of that? Which ones are of interest to which number theorists?Where do L-functions have to do with fields? Written in a style
that encourages Bill Browser to read (all of) it.

**Comment by JohnCremona** [comment]
Fields is now a link so I am closing this.
