### ISSUE TITLE
Latex not rendering for group name of several finite groups

### ISSUE THREAD

**Issue by tomgrubbmath** [LMFDB/lmfdb#4862]
See this page: https://beta.lmfdb.org/Groups/Abstract/?start=100&hst=List&order=1-63 of search results, or specific pages, such as
https://beta.lmfdb.org/Groups/Abstract/32.8 or https://beta.lmfdb.org/Groups/Abstract/32.37

Seems to be limited to groups OD, SD, and He; I think a possible suspect could be that \OD, \SD, and \He are missing from a tex style file somewhere, although I'm not certain..

**Comment by roed314** [comment]
This should be fixed by #4865.

**Comment by tomgrubbmath** [comment]
Whoops cool, didn't see that. Sorry!

**Comment by roed314** [comment]
That's because I finished the PR a few minutes after you created this issue. ;-)

I'm glad someone is using the groups pages!
