### ISSUE TITLE
Consistency in indicating cardinality

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4867]
In some places we use #S to denote the cardinality of S (e.g. on the abstract groups pages), and in other places we use |S| (e.g. on number field and p-adic field pages).  We  should be consistent.

**Comment by AndrewVSutherland** [comment]
@roed314 I think that makes sense, as far as I can tell we use |G| everywhere else (Galois groups, local fields, and number fields).  If we decide want to switch to #G we should update the style guide and then make the change everywhere.

**Comment by davidfarmer** [comment]
Can we use `\card{G}` everywhere so that the source is semantic and the macro definition
encodes the choice you are making?

**Comment by JohnCremona** [comment]
On Wed, 17 Nov 2021, 12:35 David W. Farmer, ***@***.***>
wrote:

> Can we use \card{G} everywhere so that the source is semantic and the
> macro definition
> encodes the choice you are making?
>

That exactly what I would suggest though it would be more work to change
all the old occurrences.
