### ISSUE TITLE
Download data for individual genus 2 curves

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4870]
We should add download options to the genus 2 curves comparable to what we have for elliptic curves (at a minimum, download code and download all data to text options should be provided).

**Comment by TimoKellerMath** [comment]
I'm working on this (and also on the issue to be able to download Magma/Sage/PARI code to reproduce parts of the data computed).

**Comment by TimoKellerMath** [comment]
My pull request has been merged into master: https://github.com/LMFDB/lmfdb/pull/4974#event-5975485039

**Comment by edgarcosta** [comment]
did you think about sage? if you think is unreasonable, as sage might not provide enough functionality then we should close the issue.

**Comment by AndrewVSutherland** [comment]
Unless something has been added recently, I don't think Sage has enough functionality to bother with (I think creating the curve and computing Igusa-Clebsch invariants are the only code fragments we could provide, you can't even compute the discriminant).  I'm going to go ahead and close this (but if anyone disagrees I'm happy to reopen it).
