### ISSUE TITLE
Functional dimension input pages

### ISSUE THREAD

**Issue by wbl** [LMFDB/lmfdb#488]
Inputing ranges of dimensions into the current Siegel modular forms page is different from other pages on the site. It also involves some server side problems. We should have separate form fields for each of weight and level, and k and j, each which accepts the usual range convention. There is a website wide range input issue, but this can be done better without waiting on it.  The severside code needs to be gutted and not use eval. Depends on https://github.com/LMFDB/lmfdb/issues/480.

**Comment by AndrewVSutherland** [comment]
Addressed by PR #1577 (including the server side "gutting" and removal of eval).
