### ISSUE TITLE
Server error in BMF

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#4885]
A trailing space in [gl2dims](https://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/gl2dims/%20) and [sl2dims](https://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/sl2dims/%20) gives a server error, rather than being ignored.

**Comment by JohnCremona** [comment]
I'll look into this today

**Comment by JohnCremona** [comment]
@roed314  Is there a link from somewhere else which leads to this problem?  The URL you give is not valid even with no trainling space.

**Comment by JohnCremona** [comment]
Since I did not understand the problem I cannot tell whether this fixes it, so I'll let @roed314 review this.

**Comment by edgarcosta** [comment]
Sounds good

**Comment by AndrewVSutherland** [comment]
fixed by #4934

**Comment by roed314** [comment]
This issue was created because of some server errors found in the flasklog.  I think Drew's PR should fix it.
