### ISSUE TITLE
Dirichlet group page display more characters

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#4892]
On the Dirichlet group page, e.g., https://beta.lmfdb.org/Character/Dirichlet/132/, which can reach via the bread of a character, we only display a limited number of characters without an option of seeing more.

**Comment by AndrewVSutherland** [comment]
I think the table should also be changed to group  the characters into Galois orbits (sort on Galois orbit then character label).

**Comment by AndrewVSutherland** [comment]
We should  also link  the group structure to the corresponding abstract  group.

**Comment by AndrewVSutherland** [comment]
Duplicate of #3358.
