### ISSUE TITLE
Better copy on Siegel forms landing page

### ISSUE THREAD

**Issue by wbl** [LMFDB/lmfdb#490]
'Browse Dimensions' and 'Browse Samples' are completely terrible sentences. We did have a meeting that produced better ones, but they were lost due to terrible handwriting. As usual depends on https://github.com/LMFDB/lmfdb/issues/480.

**Comment by JohnCremona** [comment]
At http://www.lmfdb.org/ModularForm/GSp/Q/ I now see the headings "Browse examples" and "Browse dimension formulas" which is better.

Pending som em uch larger changes in the future, I do not see how that page is still a "critical" issue.  It seems (git blame) that David improved the text soon afte rmarking it as critical, so I am going to close this now.
