### ISSUE TITLE
Genus 2 curve inconsistent group name

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#4910]
According to http://lmfdb.xyz/Genus2Curve/Q/2916/b/11664/1 this genus 2 curve has Qbar automorphism group C3:D4, but the additional information knowl at the bottom says D3:C4.
I believe this is a simple typo and the knowl should say C3:D4 as well, but I don't know the naming convention so well so I figured I'd jsut report it here and let @roed314 or someone fix it if it is indeed a mistake.

**Comment by AndrewVSutherland** [comment]
This has to be a typo (both the LMFDB and groupnames.org agree that 24.8 should be called C3:D4 and there is no group called D3:C4 unless this means S3xC4 but  that is group 24.5 not 24.8), which I just fixed.

**Comment by alexjbest** [comment]
Thanks!
