### ISSUE TITLE
Breads broken for L-functions

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#4918]
e.g. https://beta.lmfdb.org/L/rational/1/5/5.4/r0-0
from https://beta.lmfdb.org/L/1/5/5.4/r0/0/0

**Comment by assaferan** [comment]
Hi, now it seems to work.

**Comment by edgarcosta** [comment]
still fails for me

**Comment by edgarcosta** [comment]
ooo, you made a PR
