### ISSUE TITLE
Projective field is Galois closure

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4919]
On Artin rep pages where we show the projective field the template should say "Galois closure of ...", as it does on the weight-1 CMF pages, e.g. compare

https://www.lmfdb.org/ArtinRepresentation/2.3_19.6t5.1
https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/57/1/h/a/

**Comment by jwj61** [comment]
This is for a Galois orbit of an Artin representation.  Another option is to make it like the page for a single Artin representation where it says "stem field" in the label for the line instead of field when the field is not Galois.

**Comment by AndrewVSutherland** [comment]
Unless the stem field is somehow distinguished from its siblings (in way that is intrinsic to the Artin representation), I think it makes more sense to say Galois closure (in both cases).

**Comment by jwj61** [comment]
To me it is six of one ... .  I will leave it since it is marked as a good first issue.  For whoever does it, the individual artin rep page shows the test of whether the field is Galois or not.

**Comment by AndrewVSutherland** [comment]
@jwj61 I don't think this behavior is new, see the Artin field on https://www.lmfdb.org/ArtinRepresentation/1.1.1t1.a for example (which is still running a version that does not include #4940) which refers to the Galois closure of Q.

But I agree with you that for both the projective and Artin fields we should show the prefix "Galois closure of" only in cases where the field is not Galois, and this should be an easy change.

**Comment by jwj61** [comment]
It is new (for pages for reps).  On beta, it says "Projective field" if the field is Galois over Q, and "Projective stem field" if it is not.  There is a similar switch made on beta for Artin field and Artin stem field.

**Comment by AndrewVSutherland** [comment]
But are you saying the Artin field should say "Galois closure over Q"?  Shouldn't they both just say Q?

**Comment by jwj61** [comment]
They should both say Q.  
On the rep pages, the toggle before was on the knowl.  Now it will be on whether or not to add the phrase "Galois closure of".

**Comment by AndrewVSutherland** [comment]
Got it, either I or @BarinderBanwait will implement this tomorrow (before we push to web).

**Comment by BarinderBanwait** [comment]
I'll do it :hammer_and_pick:
