### ISSUE TITLE
Column selector in search results

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4921]
Now that we have a standard search results template that is used throughout the LMFDB we are in a position to implement column selection generically.  A crude first draft of this can be seen at https://purple.lmfdb.xyz/EllipticCurve/Q/?search_type=List&all=1 (you can also see it in action on any of the other search results pages but we still need to add more column options elsewhere).

**Comment by roed314** [comment]
With #4927 merged, let's use this issue to track requests for columns to be added to the various search results tables across the LMFDB.  As a first approximation, anything that you can enter in the search boxes is a good candidate for adding as a column.  If you request a column, make sure to specify whether you think it should be shown by default (it's possible for this to depend on the results: for example, the projective image of classical modular forms is shown by default only when there's some weight 1 form listed).

**Comment by roed314** [comment]
In #3388, there were requests for additional columns on elliptic curves over Q.  Discriminant (which is now an optional column, but should maybe be shown factored and we should perhaps take the absolute value) and the curve equation (rather than a list of Weierstrass coefficients).

**Comment by roed314** [comment]
For hgcwa, it's easy to add Quotient genus and three check columns for the three select boxes.

**Comment by rbommel** [comment]
Maybe I will try adding some columns to number fields now.

**Comment by rbommel** [comment]
Done, see #4951.

**Comment by AndrewVSutherland** [comment]
I'm working on elliptic curves (over Q and number fields).
