### ISSUE TITLE
For abelian varieties, not all invariants in the properties box are listed under invariants.

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#4923]
At the moment we have sentences listing some of the positive properties, but not the negative ones.

For example, if you land here:
https://beta.lmfdb.org/Variety/Abelian/Fq/4/4/ae_h_aj_s
from the properties box, you will know that is neither Ordinary nor Supersingular, but you will not have a knowl to describe those.

This could be a potential first issue after some guidance.

**Comment by davidfarmer** [comment]
I will do this, and follow the model on "group" pages where one long sentence lists all the yes/no properties:

https://beta.lmfdb.org/Groups/Abstract/256.15467

**Comment by AndrewVSutherland** [comment]
Can we close this now?
