### ISSUE TITLE
Extend Dirichlet character orbit data

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4924]
Currently searches for Dirichlet characters of modulus > 10000 yield no results.  You can access individual pages by label, e.g. https://teal.lmfdb.xyz/Character/Dirichlet/10001/17, but you get less information than on pages like https://teal.lmfdb.xyz/Character/Dirichlet/10000/17 where the modulus is <= 10000.

Dirichlet character orbit data for all characters up to modulus 100000 has been computed and is available in the table [char_orbits](https://beta.lmfdb.org/api/char_orbits/).  The Dirichlet pages need to be updated to use this and use pari/gp to compute character specific data on the fly (which can now be done very efficiently via the interface in [TinyConrey.py](https://github.com/LMFDB/lmfdb/blob/master/lmfdb/characters/TinyConrey.py).  This would allow us to eliminate the tables [char_dir_orbits](https://beta.lmfdb.org/api/char_dir_orbits/) and [char_dir_values](https://beta.lmfdb.org/api/char_dir_values/).

This is a necessary precursor to extending the CMF pages beyond level 10000 (which is planned at least in weight 2).

**Comment by BarinderBanwait** [comment]
@AndrewVSutherland just a clarification: your first reference to "char_dir_orbits" above should have been to [char_orbits](https://beta.lmfdb.org/api/char_orbits/) which you showed us yesterday?

Also, could I just check the requirements of this issue: the work here is essentially "just" a refactor of the code in the characters folder, and mostly in `web_character.py` and `main.py`? The user will still be able to compute character pages with less information for huge modulus like https://lmfdb.org/Character/Dirichlet/100000000000001/17 ? In particular, there should be no user-facing changes beyond the following?

1. the 10,000 cut-off above being increased to 100,000
2. possible performance increase

**Comment by AndrewVSutherland** [comment]
@BarinderBanwait Yes, I should have written "char_orbits" above (now fixed), and yes, for characters of modulus > 100,000 there would be no change in the UI.  Also, I confirmed yesterday that it is feasible to go to 1,000,000 and plan to do this (but 100,000 is enough for now).

One key change for characters of modulus <= 100,000 (or 1,000,000) is that in order to determine the Galois orbit of a given Conrey character like chi=100000.39873, you will need to search the char_orbits table on the first_label column, which means you need to compute the minimal Conrey index in the orbit of chi (in this case, it is 33, so the first_lablel is 100000.33 which tells you that the character orbit is [100000.eu](https://beta.lmfdb.org/api/char_orbits/?first_label=100000.33).  This computation is very fast and can be done on the fly.  Here is Magma code to do it that you will need to convert to Sage:

```
intrinsic MinimalConreyConjugate(q::RngIntElt, n::RngIntElt) -> RngIntElt
{ The minimal Conrey index among all conjugates of q.n. }
    if n eq 1 then return 1; end if;
    R := Integers(q); U, pi := MultiplicativeGroup(R); x := Inverse(pi)(n);
    return i where i :=Min([Integers()|pi(n*x):n in [1..m]|GCD(m,n) eq 1]) where m := Order(R!n);
end intrinsic;
```
For modulus <= 10^6 this takes less than 10 milliseconds, so its fine to do this on the fly.

**Comment by AndrewVSutherland** [comment]
This is now live on beta, see https://beta.lmfdb.org/Character/Dirichlet/.

One thing I noticed when clicking around is that for kernel fields of degree <= 12 that are not in the number field database, the user is given the option to lookup the field, even though the lookup has already been done (and failed).

See https://beta.lmfdb.org/Character/Dirichlet/93513/so for an example.  This seems less than ideal.

**Comment by edgarcosta** [comment]
also the lookup is done with the polynomial texed

<img width="1773" alt="Screen Shot 2023-05-06 at 11 09 34" src="https://user-images.githubusercontent.com/322822/236632426-906ba7e5-184d-42e3-b17f-a085f5680f96.png">

**Comment by AndrewVSutherland** [comment]
That's okay I think.

**Comment by BarinderBanwait** [comment]
> This is now live on beta, see https://beta.lmfdb.org/Character/Dirichlet/.
> 
> One thing I noticed when clicking around is that for kernel fields of degree <= 12 that are not in the number field database, the user is given the option to lookup the field, even though the lookup has already been done (and failed).
> 
> See https://beta.lmfdb.org/Character/Dirichlet/93513/so for an example. This seems less than ideal.

Fair point; I can change the behaviour so that if the degree is <= 12, then the option to lookup is not presented, that should be quick.

> I think we might want to make the error message displayed by number fields a bit friendlier in the failed lookup case (there is no reason to say the input is invalid, it is valid, it's just not in the database).

Yep I agree, and I can look to change this. This is a current issue with the production site as well; asking for eg 'x^50 + 311' also says that it is not a valid input for 'Label'.

**Comment by BarinderBanwait** [comment]
Latest PR addresses the first point above.

The second one, about making the error message a bit friendlier, is a bit more gnarly; the jump box first checks for a "Label" match, which is why it reports that a polynomial doesn't match label, and subsequently returns the error message returned by another function; so technically the error message is not incorrect, but indeed it is confusing. I think this would be a good first issue for someone to take on, and I'll raise this as a follow-up issue along with the several other ones I said I would (implementing John's abelian search idea, keeping track of the verify functions removed, more general cleanup of `web_character.py`)

**Comment by AndrewVSutherland** [comment]
I think the extension to modulus 100000 can be declared done!  There are still some minor issues on Dirichlet character pages (e.g. #5651 and #5570), but they are not specific to this feature request.  Thanks Barinder!
