### ISSUE TITLE
Minor problem when entering genus 2 curve coefficients in the jump box

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4968]
Running master locally the input "[[1,1,0,0,0,1],[]]" works in the genus 2 jump box, taking you to the page http://127.0.0.1:37777/Genus2Curve/Q/123648/e/865536/1 as it should, but on https://beta.lmfdb.org this does not work (but [x^5+x+1,0] does).

 I don't understand the difference in behavior, they are running the same code (I even tried running my own copy of master on blue with the same result).

**Comment by edgarcosta** [comment]
this is a regex issue, your original regex assumed nonempty lists. I will fix it.

**Comment by edgarcosta** [comment]
something is off, my changes on master have been lost

**Comment by edgarcosta** [comment]
Neither @roed314  or I understand what happened, but it happened in the commit a09ab89 
However, github doesn't show it, but if you run
```
git diff 7e54750 a09ab89 genus2_curves/main.py
```
you will see the changes being reversed.

**Comment by AndrewVSutherland** [comment]
What is really strange is that it works when I run my master branch, and Github does not think my master is ahead of the LMFDB.

**Comment by edgarcosta** [comment]
@roed314 and I are exploring what is going on...

**Comment by AndrewVSutherland** [comment]
What is even stranger is that I am running code with a ZLIST_RE that looks like it should should not work (empty list not allowed), but it is working.

**Comment by edgarcosta** [comment]
The changes were undone here: https://github.com/LMFDB/lmfdb/pull/4957/files#diff-bae38784bed1720930872ce012b1b023c4acf70a68ddc4a4a5135d3b3f24e83e

**Comment by edgarcosta** [comment]
looks like only my changes were done, thus I will resubmit them later on today

**Comment by AndrewVSutherland** [comment]
I don't understand why this happened, since I did not touch those lines, and git did not highlight them as a merge conflict (there was a merge conflict at the top of the file that I fixed).  I guess git got confused.

But I'm still intrigued by the behavior on my local branch. If I type "[[1,1,0,0,0,1],[]]" into the jump box it does not call genus2_jump, even though it is registered, and yet it somehow magically does the right thing.

**Comment by edgarcosta** [comment]
Got it, `\[\d+(,\d+)*\]` matches the the substring `[1,1,0,0,0,1]` in `[[1,1,0,0,0,1],[]]`

**Comment by AndrewVSutherland** [comment]
But apparently not on https://beta.lmfdb.org/Genus2Curve/Q/ ?

In any case, I recommend using .fullmatch to avoid this kind of confusion.  I should get an error if I type [1,2,3,4,5]banana

**Comment by edgarcosta** [comment]
agree

**Comment by JohnCremona** [comment]
Perhaps there are different version of the python re module in play which could accout for different behaviour of the same code?
