### ISSUE TITLE
Duplicate rows in bmf_dims table

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#4972]
I noticed that for the fields 2.0.23.1 and 2.0.31.1 the entries in the bmf_dims table for level norms <=1000 are duplicated (see https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/gl2dims/2.0.23.1?level_flag=all and also https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/gl2dims/2.0.23.1?start=3900&level_flag=all to see the change-over.  I must have done something wrong when updating the range of levels from the original 1-1000 to what it is now (1-2000 and 1-3000 respectively).

I will be uploading more BMF dims & forms soon, including extending the range for 2.0.23.1 up to 3000,  so will fix this then.

**Comment by AndrewVSutherland** [comment]
Has this been fixed @JohnCremona ?

**Comment by JohnCremona** [comment]
> Has this been fixed @JohnCremona ?

Not yet, but not for very good reason.  I have now have much more BMF data nearly ready to upload, including at least all fields of absolute discriminant up to 100 and level norm to 1000, with associated elliptic curves and ECNF data, but the last three fields are still in progress and I'll do everything in one go.   See https://github.com/JohnCremona/bianchi-data/commits/master

**Comment by JohnCremona** [comment]
I have now updated bmf_dims for fields 2.0.23.1 and 2.0.31.1 which had the duplicates.  (Explanation: the upload files I used for the ranges 1001-2000 for 23 and 1001-5000 for 31 also had the lines for 1-1000 in them, so for both fields we ended up with duplicate lines for level norms up to 1000.  This was only for bmf_dims, not bmf_forms).

At the same time I increased the range for field 23 to 3000 (was 2000) for dims and forms,  also uploaded elliptic curves over this field with conductor norm 2001-3000.  So the three updated tables are: bmf_dims, bmf_forms, ec_nfcurves.

If quick and easy, we could copy these 3 tables to prod now.  However I also have data for level/conductor norms up to 1000 for 18 more fields, with 3 more nearly finished, taking the number of imaginary quadratic fields up to 32 (all those of abs disc less than 100, and 163) for these three tables.  So it could wait for that.

**Comment by AndrewVSutherland** [comment]
The tables `bmf_ims`, `bmf_forms`, `ec_nfcurves` have been copied to proddb.

**Comment by JohnCremona** [comment]
Thanks, @AndrewVSutherland .  By the way, one reason I have been holding back on the extra data I have is that I am still using your old code for the mod-ell Galois images, which I know you recomputed in some cases for ECNF.  So the curves over 2.0.23.1 with conductor norm 2001-3000 might have incorrect Galois image data, ditto for all the new fields which are not yet uploaded (but the upload files are in my ~/ecnf-upload/ on legendre).  I think this only affects curves with CM (which is potential CM for these fields).
