### ISSUE TITLE
Consistent handling of cyclic and abelian groups of large order

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4976]
Entering "C1234" into the jump box on https://beta.lmfdb.org/Groups/Abstract/ works, but "C12345" does not (nor does "ab/12345"), despite the fact that there is a home page for the cyclic group of order 12345: https://beta.lmfdb.org/Groups/Abstract/ab/12345.

Both the jump box should handle cyclic groups that are not stored in the database, as should `abstract_group_display_knowl`, as well as abelian groups like C65537 x C65537 that also have home pages: https://beta.lmfdb.org/Groups/Abstract/ab/65537.65537.

It would be nice if we had similar pages for dihedral groups outside the range of the small groups database (but happy to make that a separate issue which would be a feature request).

**Comment by roed314** [comment]
I created a followup issue for the feature request.
