### ISSUE TITLE
Some imaginary quadratic fields not always marked as CM fields

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4977]
There are 918 imaginary quadratic fields of large discriminant that have the column `cm` incorrectly set to `False`:

   https://www.lmfdb.org/NumberField/?hst=List&degree=2&signature=%5B0%2C1%5D&cm_field=no&search_type=List

This is easy to fix in the data, but I'm raising an issue to make sure @jwj61 is aware of it in case this is caused by a problem somewhere upstream or in the load scripts.

**Comment by jwj61** [comment]
There was a bug in the preparation scripts.  They look at the signature of the field and of index 2 subfields, but the subfield function does not include Q in its list, so it was not seeing a totally real subfield.  The script is now fixed (need to update the version in the lmfdb repository).  Also, the data is fixed on beta.

Right now on beta, if you do the search above it lists no fields, but says that there are 918 of them, so the statistics or counts need to be refreshed.  I tried to do this myself per the FAQ with 

 db.nf_fields._clear_stats_counts()

but that produced an error.

**Comment by roed314** [comment]
I'll take care of the stats.

**Comment by jwj61** [comment]
Then nf_fields should be copied to the cloud.

In addition to this change, there are some new degree 10 fields ramified at only 2 and 5 courtesy of Eric Driver.

**Comment by roed314** [comment]
There was a typo in the Postgres FAQ, which I've now fixed in #4971 (just since it was convenient to include there).  It should be
```
db.nf_fields.stats._clear_stats_counts()
```
rather than just `db.nf_fields._clear_stats_counts()`.

**Comment by AndrewVSutherland** [comment]
I'll take care of the copy, thanks @jwj61 and @roed314 (poor Q always seems to be a second class citizen in the world of number fields).  @jwj61 I'll leave this issue open until the data is copied and the scripts are updated.

**Comment by AndrewVSutherland** [comment]
nf_fields is now updated on proddb
