### ISSUE TITLE
Coefficients of the q-expansion not properly defined

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#4998]
For this weight 1 modular form
https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/1487/1/b/a/
we say
```Coefficients of the $q$-expansion are expressed in terms of a basis $1,\beta_1,\ldots,\beta_{17}$ for the coefficient ring described below.``` 
but we never end up saying what $\beta_i$ are.

**Comment by AndrewVSutherland** [comment]
I don't understand why the basis is not being displayed, it is in the [data](https://beta.lmfdb.org/api/mf_hecke_nf/79440), with power_basis set to False, so it should be getting displayed.
