### ISSUE TITLE
Indicate when search results are out of date

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5003]
A suggestion of @AndrewVSutherland in the discussion on #4991: 

"I think we should change the appearance of the search again button when the results don't reflect the current settings (if you change the sort order but don't click search again it's easy to get confused, especially if you switch to another tab and then back). I would suggest making the default color of the search button the same color as the selectors (lighter blue) when it is in an inactive state (i.e. pressing it will just reload the search results currently shown) and then making the search button the color it is now (darker blue) whenever it is in an active state (pressing it will apply new search/sort criteria)."

**Comment by roed314** [comment]
There are two kinds of behavior we might have for this feature:
1. As soon as a search box changes we make the button darker blue, and it stays darker blue even if the search box changes back to its original value
2. As soon as a search box changes we make the button darker blue, but it becomes light blue again if all inputs are changed back to their original value.

Option 1 is easier (since we don't need to store their original values somewhere and write code for comparing them).  Option 2 is slightly nicer from a UI perspective.

Either way, the sort order would affect the color of the search again button, but the "search columns displayed" will not (even though searching again will add the search columns to the url which is a change of a sort).

**Comment by AndrewVSutherland** [comment]
I think 1 already provides most of the benefit, and would suggest that we not use the fact that 2 is a pain to implement as a reason to delay adding this useful feature (I occasionally get confused by this myself).  If someone still wants 2 they can make another feature request after 1 is implemented.
