### ISSUE TITLE
Change the way potential/actual CM are stored for ECNF

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#5004]
Currently th ECNF table (ec_nfcurves) has one column 'cm' which holds 0 for non-cm curves, a negative integer -D for curves with potential CM by the order of discriminant -D, and a positive integer +D for curves with actual CM by the order with discriminant -D.  For the last possibility to occur, the base field must contain the class field associated to discriminant -D and in particular contain sqrt{-D}, so we only see it over imaginary quadratic fields of class number 1 and one of the 13 possible D's (since all the other fields over which we have elliptic curves are totally real, or 3.1.23.1).

This makes sorting search results by CM discrimimnant problematic (see #4991).  We should change the convention:
   1. add a new column with values 0,+1,-1 for no CM, actual CM, potential CM
   2.  change the 'cm' column back to always being 0 or negative
   3. adapt the code to deal with this properly.

I think that it will be possible to do these in the order 1,3,2, and starting with 1 is certainly easy as the new column is just the sign of the 'cm' column.

**Comment by JohnCremona** [comment]
Item 1 has been done, on beta there is now a new column 'cm_type' with values 0,1,-1 equial to the current sign of the 'cm' column.

**Comment by AndrewVSutherland** [comment]
Let me know when the data is ready to be copied to prod.

**Comment by JohnCremona** [comment]
> Let me know when the data is ready to be copied to prod.

OK -- it will not be until after a PR.  I hope I can get the code working both with the data as it is now and and as it will be (with no positive entries in the 'cm' column).

I'm also ready to add more rows to this table, as soon as I can get the correct Galois images for them :) (I also need to add the 'cm_type' column and root analytic conductor columns).

**Comment by AndrewVSutherland** [comment]
Sorry for being slow on the Galois images (we had our Simons collaboration meeting Friday so I didn't have much time to work on it).  I will get it done this week (today if I can).

**Comment by JohnCremona** [comment]
After #5005 is reviewed and merged and on beta (step 3), I can implement step 2. Then a second small PR to remove two redundant lines of code before pushing to prod.  It would be OK to copy ec_nfcurves to prod now, but we might as well wait until all these steps are completed.

**Comment by AndrewVSutherland** [comment]
ec_nfcurves has been copied and #5005 has been merged.

**Comment by JohnCremona** [comment]
Good!  I'll now do the second stage of data adjustment, putting back the - signs in the 'cm' column.

**Comment by AndrewVSutherland** [comment]
@roed314 Can you take a look at this to understand what went wrong with the rewrite?

**Comment by JohnCremona** [comment]
> @JohnCremona I can copy back the file I just copied to proddb

Thanks -- yes please, unless you can tell which if the existing backups on beta is the one made by the most recent rewrite.

**Comment by JohnCremona** [comment]
From the backup, I can of course do another rewrite without using the query parameter. Of course this second rewrite was very fast, but given that it deleted all but about 1000 rows perhaps that is not surprising...

**Comment by AndrewVSutherland** [comment]
ec_nfcurves has been reloaded on beta

**Comment by JohnCremona** [comment]
> ec_nfcurves has been reloaded on beta

Thanks for the quick response.  I'll redo the second rewrite without using the query parameter.

**Comment by JohnCremona** [comment]
When I re-did the rewrite I got error messages:
"DuplicateTable: relation "ec_nfcurves_old5" already exists"
happens while executing b'ALTER TABLE "ec_nfcurves" RENAME TO "ec_nfcurves_old5"'

This happened after the dump when it tried to reload the transformed data, at which point it presumably wnatewd to take a copy of the untransformed table but got confused.

Any ideas as to what to do next?

**Comment by roed314** [comment]
Oops, that's a pretty serious bug in `rewrite`.  I'm sorry about that @JohnCremona!  I've created #5008.

For future reference, another solution to recovering from such a problem (if Drew hadn't just copied the data to prod for example), is the `reload_revert` function.  After the catastrophe, if you'd run `db.ec_nfcurves.reload_revert()` you should have gotten back to the original state before you'd run `rewrite`.  The backups that make this possible are things like `ec_nfcurves_old5` that you're now running into.  The first thing I would do (assuming that everything is in a good state at the moment and you don't need backups) is call `db.ec_nfcurves.cleanup_from_reload()`.  This drops the backup tables.  They shouldn't be getting in the way, but I'm not sure exactly what command Drew executed to restore the table.

**Comment by JohnCremona** [comment]
OK thanks for the explanation. I'll finish sorting it out tomorrow.

**Comment by JohnCremona** [comment]
I did the rewrite properly and at #5020 there are two minor code changes removing lines which are now redundant.

This can be closed after #5020 is merged, ec_nfcurves copied to prod, and the code pushed to prod.

**Comment by JohnCremona** [comment]
But I allowed for exactly this by doing it in two stages.  Yesterday's code (after the first PR) works with old data (with the 'cm_type' column filled but some 'cm' entries positive) and with the current data.  So it will be fine to push the table to prod as long as prod has my first PR from yesterday, and then push the latest code to prod after that.  If that is possible, I have lost track of which commits are now on prod!

**Comment by AndrewVSutherland** [comment]
Excellent, in fact web is running code that includes #5005, so we should be good.  I'll copy the table over now.

**Comment by AndrewVSutherland** [comment]
Ah but it doesn't include the search fix I just made, so I still need to do the two together.

**Comment by AndrewVSutherland** [comment]
Done.

**Comment by JohnCremona** [comment]
> Done.

Phew!  Yes, in my analysis just now I did not take into account the imperfection in what I did to the code yesterday.  Well, I was right in principle...
