### ISSUE TITLE
Bug in rewrite

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5008]
As discovered in #5004, if you include a query in the arguments to `rewrite`, it deletes everything not satisfying the query!  Instead, it should either use the query as a test to determine whether to apply the transformation function, or run a second query with the negation of the query and write the other rows out unchanged.

**Comment by JohnCremona** [comment]
Surely this is critical!  At the least as a stop-gap should we not raise an error when rewrite is called with a query?  After 7 months I would not have been surprised if I had forgotten this.

**Comment by AndrewVSutherland** [comment]
Fixed via #5199
