### ISSUE TITLE
Uniformize raw/typeset view for large numbers and polynomials

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5011]
We now have two different ways of allowing the user to cut and paste numbers and polynomials on LMFDB object pages, compare

[CMF page](https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/1/118/a/a/)
[NF page](https://www.lmfdb.org/NumberField/17.17.13202363705223218603863184487755024630582383374680032800435939704158233027841788543229812635151072074455438626669432759450899735549243294921243306854586939663055181335880903211540683502950935087551803286773305471032026037990460071805978402769130092019752634101527352693814943791414905342572852579428180829030727661698750961477408713596845181881409326113271279701186934711912924535979375368089471422837282452421683506180048924876364820225210846226099372878635447796099920054239935070472348193791925328690838569369798938742618818040823435236370214291386195573062935332270993039421387687573397220106241394348907347636983408333263308765625.1)

We should uniformize these.  I think it makes sense to use the new control used on the CMF pages everywhere, both because it improves the page layout, and because it allows you to copy the data to the clipboard with one click.  But I know @jwj61 expressed some reservations about earlier versions of the control used on the CMF pages, so we should discuss this before making any changes.

There are also many pages where the numbers or polynomials are not unreasonably large but it would still be useful to have the typeset/raw button available just for the ability to cut-and-paste numbers and polynomials. It's unobtrusive enough that I could see an argument for putting it on every object's home page (but this will require updating a bunch of templates).

**Comment by jwj61** [comment]
Looking at the CMF page, there seem to be two styles there.  One works like the number field page (e.g., for \nu^2), and others have a different behavior.  Just so I know what is being proposed, is it that the two behaviors are both kept, but are determined by the length of the string?

**Comment by AndrewVSutherland** [comment]
@jwj61 Yes, if the number/polynomial is short enough (the definition of which we can tweak) the raw mode displays without a text area around it and with no copy-to-clipboard button :( this happens in the first three lines of the Hecke ring basis on the CMF page.  And now that I look at it again, I'm not sure I like this, I think it would be better if raw mode always looked the same and always had a copy-to-clipboard button.  What do you think @edgarcosta ?

**Comment by edgarcosta** [comment]
I should point out, that the function to use is `raw_typeset_poly` in https://github.com/LMFDB/lmfdb/blob/master/lmfdb/utils/web_display.py#L434 and only uses the textarea box if we tried to compress the polynomial.
This happens in the length of the `raw` text is too long.
One way to prevent this is to put the threshold long enough or perhaps have an optional flag to prevent doing this.

**Comment by edgarcosta** [comment]
Ups, I sent the previous message before seeing the new messages.

@AndrewVSutherland I'm not sure what are you proposing. That we have a uniform behavior for the whole page or for the basis?

An improved version of this, which I hope to some time soon, is to make the whole basis into a large text area, as no one really wants to copy element by element. However, the `$x$->x` will be shown at the bottom.

**Comment by jwj61** [comment]
Previously, double-clicking on the typeset math on a number field page toggled it to raw mode with it selected.  That does not seem to be working on math.  Was this disabled on purpose?

Aside from that, I am on board with what I think is being proposed:
 - if the math stuff is not way to long, show it in full as typeset with the toggle for raw mode if we think the user might want to copy/paste it
 - if the math stuff passes the threshold, then we show an abbreviated version and the toggle puts the full raw version in a text area with the copy button

It would be nice if there was also a way for the user to be able to see the full typeset version of the math if they want (when the raw math is long enough), but can't think of a way to allow that option without making the interface too complicated/clunky.

**Comment by AndrewVSutherland** [comment]
@edgarcosta I meant uniform behavior across different sections of the LMFDB (e.g. the the two pages I linked to in the OP currently work quite differently).

In addition, I think it is slightly confusing that sometimes the $x$->x creates a text area and other times it does not (especially when you click the $x$->x button at the top).  This is really independent of the basis issue (where I agree it would be nice to be able to copy them all at once, but I think this is lower priority than uniformizing the interface).

I would have the same concern if there were three unrelated polynomials some of which were too long and some of which were not.  With the the current interface, sometimes you can copy to the clipboard with a single click but other times you need to double click (or click and drag) and then type ctrl-c, and this can vary from one item to the next on the same page.

I agree with @jwj61 that double-click toggling would be nice (and if there was always a copy-to-clipboard button, it would not interfere with copying).

I don't feel dogmatic about any of this, and I'm not sure there is a perfect solution (e.g. I agree with @jwj61 that it would also be nice to be able to see large objects typeset in some cases but I don't see a good way to do that).  But I think we should settle on the best set of compromises we can and then apply them uniformly everywhere (including places where there is currently no way to copy a polynomial at all).

**Comment by edgarcosta** [comment]
> Previously, double-clicking on the typeset math on a number field page toggled it to raw mode with it selected. That does not seem to be working on math. Was this disabled on purpose?

I will fix that on Friday. But I will only select when there is no textarea, otherwise, it scrolls the textarea to the end, and it becomes unlcear what is in the textarea.

We can easily add the copy button everywhere if it is desired.

I agree that the textarea is uggly and should be avoided, but honestly for pages like this:
[CMF 5.126.a.a](https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/5/126/a/a/)
[NF](https://www.lmfdb.org/NumberField/17.17.13202363705223218603863184487755024630582383374680032800435939704158233027841788543229812635151072074455438626669432759450899735549243294921243306854586939663055181335880903211540683502950935087551803286773305471032026037990460071805978402769130092019752634101527352693814943791414905342572852579428180829030727661698750961477408713596845181881409326113271279701186934711912924535979375368089471422837282452421683506180048924876364820225210846226099372878635447796099920054239935070472348193791925328690838569369798938742618818040823435236370214291386195573062935332270993039421387687573397220106241394348907347636983408333263308765625.1)
I don't see another solution.

**Comment by roed314** [comment]
> But I will only select when there is no textarea, otherwise, it scrolls the textarea to the end, and it becomes unlcear what is in the textarea.

Would it be possible to scroll back to the beginning in javascript after selecting?

**Comment by edgarcosta** [comment]
Let's talk Friday.

**Comment by AndrewVSutherland** [comment]
@jwj61 I just wanted to note that in cases where the typeset information is provided in its entirety, the raw-copy interface would also show it in its entirety, even if a textarea is used (the interface Edgar implemented sizes the text area so it takes the same space as the typeset text and the font is sized so that the user should see everything they could see when it was typeset).  In other words, nothing should ever be hidden when you switch to raw mode.

**Comment by jwj61** [comment]
I see.  Then go ahead and make them all textboxes.

**Comment by edgarcosta** [comment]
@AndrewVSutherland, now that we agreed on the underlying infrastructure we should just have a ticket for all the things where we want that infrastructure applied

**Comment by AndrewVSutherland** [comment]
As noted by @edgarcosta PR #5032 is only the first step in addressing this issue.  The next step is to use the raw/typeset option consistently across the LMFDB.  In particular, the two bases on [CMF page](https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/1/118/a/a/) and [NF page](https://www.lmfdb.org/NumberField/17.17.13202363705223218603863184487755024630582383374680032800435939704158233027841788543229812635151072074455438626669432759450899735549243294921243306854586939663055181335880903211540683502950935087551803286773305471032026037990460071805978402769130092019752634101527352693814943791414905342572852579428180829030727661698750961477408713596845181881409326113271279701186934711912924535979375368089471422837282452421683506180048924876364820225210846226099372878635447796099920054239935070472348193791925328690838569369798938742618818040823435236370214291386195573062935332270993039421387687573397220106241394348907347636983408333263308765625.1)
should be displayed consistently, ideally with each basis element compressed, but only a single copy/paste and show for the entire text area.

And on the [NF page](https://www.lmfdb.org/NumberField/17.17.13202363705223218603863184487755024630582383374680032800435939704158233027841788543229812635151072074455438626669432759450899735549243294921243306854586939663055181335880903211540683502950935087551803286773305471032026037990460071805978402769130092019752634101527352693814943791414905342572852579428180829030727661698750961477408713596845181881409326113271279701186934711912924535979375368089471422837282452421683506180048924876364820225210846226099372878635447796099920054239935070472348193791925328690838569369798938742618818040823435236370214291386195573062935332270993039421387687573397220106241394348907347636983408333263308765625.1) several entries that are not currently displayed using the raw/typeset selector should be, including the discriminant (rather than a bignum knowl) and the largest prime factor of the discriminant (in all 3 places where it appears: in the prime factorization of the discriminant, the list of ramified primes, and in the local algebra table at the bottom).

In our editorial meeting we agreed that all information that is too large to be easily displayed should be initially displayed in compressed mode, including the defining polynomial and the basis for the ring of integers on the [NF page](https://www.lmfdb.org/NumberField/17.17.13202363705223218603863184487755024630582383374680032800435939704158233027841788543229812635151072074455438626669432759450899735549243294921243306854586939663055181335880903211540683502950935087551803286773305471032026037990460071805978402769130092019752634101527352693814943791414905342572852579428180829030727661698750961477408713596845181881409326113271279701186934711912924535979375368089471422837282452421683506180048924876364820225210846226099372878635447796099920054239935070472348193791925328690838569369798938742618818040823435236370214291386195573062935332270993039421387687573397220106241394348907347636983408333263308765625.1).

We also agreed that it would be nice to add an option that would show the full latex version of an item that has been compressed, e.g. by single-clicking on the "..." (and single-click again to undo) -- you should still be able to double-click elsewhere to enter raw mode.

**Comment by AndrewVSutherland** [comment]
@edgarcosta I wrote the comment above before seeing yours.  Feel free to create a new issue and close this one if you would prefer that.

**Comment by JohnCremona** [comment]
If you're making a list, there are some large generators of mordell Weil groups which are currently displaying in an ugly (and not easily copiable) way.

**Comment by edgarcosta** [comment]
The missing tasks are now in #5037
