### ISSUE TITLE
Isogeny graph 

### ISSUE THREAD

**Issue by swisherh** [LMFDB/lmfdb#503]
The isogeny graph picture should be smaller and the numbers should be off of the edges.  I believe @JohnCremona is already working on this.

http://beta.lmfdb.org/EllipticCurve/Q/102/b/

**Comment by JohnCremona** [comment]
Working on it yes, I spent an afternoon on it but hit some problems I could
not solve so put it aside for much more important stuff.

See my isograph branch if interested.

**Comment by davidfarmer** [comment]
Closing because not worth the effort.
