### ISSUE TITLE
Two things on a big number field page

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#5034]
https://www.lmfdb.org/NumberField/17.17.13202363705223218603863184487755024630582383374680032800435939704158233027841788543229812635151072074455438626669432759450899735549243294921243306854586939663055181335880903211540683502950935087551803286773305471032026037990460071805978402769130092019752634101527352693814943791414905342572852579428180829030727661698750961477408713596845181881409326113271279701186934711912924535979375368089471422837282452421683506180048924876364820225210846226099372878635447796099920054239935070472348193791925328690838569369798938742618818040823435236370214291386195573062935332270993039421387687573397220106241394348907347636983408333263308765625.1

* The root discriminant shouldn't have commas.  We propose writing in scientific notation whenever it's so big that commas would be needed.
* The Galois group is listed as 177843714048000.0, but the knowl doesn't work--presumably we haven't computed all groups of that order, and we never will?  It's probably better not to try to give a label in this case, and just describe the group.

**Comment by roed314** [comment]
There will soon be abstract group homepages for groups like 17T9, though that shouldn't prevent us from improving the situation in the short term.

**Comment by jwj61** [comment]
I am going to work on this today
