### ISSUE TITLE
Mongenicity and index divisors for number fields

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5044]
It would be nice if the LMFDB could tell you for a given number field whether or not it is monogenic (meaning its ring of integers admits an integral power basis), and in the nonmonogenic cases, the index divisor i(K) = GCD({[O_K:Z[a]]: a in O_K}) (which may be 1 even when K is not monogenic).  In particular, it would be nice to be able to search  on these quantities.

It almost certainly won't be feasible to do this for all  number fields in the LMFDB (or even most of them), but I think we could do enough to provide a rich set of examples that would be really useful for people who are thinking about these questions (and there seem to be quite a few of them these days -- its a problem that has been around since Dedekind but never really goes away, perhaps because it is one of the simplest invariants of a number field that we don't really know how to compute, at least not comprehensively).

We could start by marking as monogenic all the fields for which our standard generator (root of the poldredabs polynomial)  already gives an integral power basis, then compute the monogenicity and index divisors for low degree fields (I think this is completely doable for degree 3 and 4, and there are now quite a few results for degrees 5 and 6), and we could apply some known results for producing families of non-mongenic fields and mark those that show up in the LMFDB.  Computing index divisors (or at least their prime divisors)  is probably easier than testing monogenicity (primes dividing the index divisor are bounded by the degree and there a number of [standard tests](https://www.ams.org/journals/proc/1952-003-05/S0002-9939-1952-0050627-4/S0002-9939-1952-0050627-4.pdf) one can apply, as well as some [new ones](https://arxiv.org/abs/2202.09342)), and that will already yield a lot of non-monogenic fields.

I'll note that developing an efficient algorithm for computing these quantities, even just for a subset of the fields in the LMFDB could make for an interesting [LuCANT](https://beta.lmfdb.org/LuCaNT) paper.  But even without inventing anything new there are quite a few existing results in the literature that could be applied.

I should note that I am not an expert on this topic.  I invite those who are to chime in with pointers to the literature and ideas on how to go about computing these quantities.  I'd be very happy for someone to tell me that this is actually easy to do!  But if it isn't that's all the more reason to try to do as much as we can easily do, since it then leaves a target for others to aim at (e.g. the number field of least absolute discriminant whose monogenicity is unknown should be marked as interesting number field).

**Comment by jwj61** [comment]
This looks like a good general reference too:  https://www.ams.org/journals/tran/1985-289-01/S0002-9947-1985-0779058-2/

**Comment by jwj61** [comment]
There is now a pull request for the code side.

The easy cases of monogenic are in the database.  A rewrite is underway to fill in inessential primes.  After that, more rewrites will take place to fill in many values of the index when greater than 1.

In the end, not all data will be computed.  It makes me wonder whether there should be an indicator on search fields where we do not have complete data.  For number fields, this would apply to several search boxes (e.g., class number and regulator).  For example, one can currently (with this pull request) search for number fields with index=1 but not monogenic and get no results, even though such fields almost certainly exist in the database.  Should users be warned?

**Comment by AndrewVSutherland** [comment]
I think there should be an indicator on the search box.  We already put an asterix in cases where we are searching on a heuristically computed value (e.g. number of rational points, analytic rank, order of sha for genus 2 curves).  The situation here is more serious in that we don't know even a heuristic value for many cases, which is comparable to searching for isogeny classes of abelian varieties over finite fields based on whether they contain a Jacobian or not -- in that case we make things clear to the user with options for including unknown values or not, and I would suggest we do the same for the monogenic boolean (yes, yes or unknown, no, no or unknown).  Things are tricking for numeric values like the index and I'm open to suggestions (but I think we should definitely do something).

**Comment by jwj61** [comment]
I changed the data type of monogenic to fit the YesNoMaybe boxes and am recomputing data.

Since the asterisk is defined on the page, we could use it on the number field search page to indicate fields where the data may not have been computed.

Another alternative is to use index=0 to mean not computed yet, and alert the user that they can use that in the search box.  I suppose the same could be done with class number, although doing something like that for class group structure would be more difficult.

**Comment by jwj61** [comment]
How many firsts of non-monogenic should get top knowls:

 - first when ordered by (degree, |D|)?  (I just did this one)
 - first by just |D|?  It turns out to be degree 4
 - first which has index 1?

Then there is the first example of a field which is monogenic, but the polredabs generator does not do it?

**Comment by AndrewVSutherland** [comment]
I would say first by |D| and first of index 1 are definitely top-knowls, and I might vote for historically first as well.

Monogenic fields whose rings of integers are not generated by the polredabs generator do not strike me as "top-knowl material".

**Comment by JohnCremona** [comment]
I agree with @AndrewVSutherland

**Comment by jwj61** [comment]
The first 2 now have top knowls.  I went to do the historic one in as a bottom knowl and found it was already there as such.

**Comment by AndrewVSutherland** [comment]
While there is obviously more to do (and likely always will be), I think it makes sense to close this PR as the requested functionality has now been added.
