### ISSUE TITLE
show more coefficients (only 57 coefficients of Delta)

### ISSUE THREAD

**Issue by swisherh** [LMFDB/lmfdb#505]
"Show more coefficients" is maxed at 87 even though 100 coefficients are stored. Crash when trying to download more than 100 coefficients.
http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/1/12/1/a/

**Comment by davidfarmer** [comment]
Seems to be maxed at 57

**Comment by sehlen** [comment]
No, this is individual depending on the form and will change soon. The issue (crash when pressing the button for showing more or downloading) is certainly fixed now.

**Comment by sehlen** [comment]
But I agree that we should be able to show more coefficients than that.
Fredrik and me are working on this.
