### ISSUE TITLE
Root of Unity

### ISSUE THREAD

**Issue by swisherh** [LMFDB/lmfdb#506]
Wrong root of unity is defined:
http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/13/4/4/

I'm not sure what this is about, but I'm copying it from the wiki (HS)

**Comment by alinabucur** [comment]
The q-expansion is all about \zeta_6, but under the table the text 

Here \zeta_12 = exp(2\pi i 7/n). 

appears. First, $\zeta_{12}$ is not relevant, second it is defined wrong, and third it should be $\zeta_{12}$ not $\zeta_12$

**Comment by christellevincent** [comment]
I was able to fix the underscore issue. Still working on other bits.

**Comment by JohnCremona** [comment]
On 28 October 2015 at 14:12, christellevincent <notifications@github.com>
wrote:

> I was able to fix the underscore issue. Still working on other bits.
>

I also fixed the {} round the subscripts and the un-evaluated n but could
not see you to extract the correct zeta from the power series so never got
as far as a pull request.  Looks like my branch is redundant.  Still it
might be of interest to look at the last commit of
 https://github.com/JohnCremona/lmfdb/commits/roots-of-unity

**Comment by christellevincent** [comment]
Would the code I suggested work? If the character is of order 6, say, wouldn't a primitive sixth root of unity always appear? (see my edited comment)

**Comment by AurelPage** [comment]
It is now working in the refactor branch.
