### ISSUE TITLE
Rendering of arXiv links in knowls has extra space

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5086]
When arXiv papers are cited in knowls (such as [this one](https://beta.lmfdb.org/knowledge/show/rcs.rigor.cmf)), there is an extra space at the end before the close bracket that should not be there.

**Comment by fchapoton** [comment]
same with doi and mr links, see for example

https://beta.lmfdb.org/knowledge/show/gl2.borel

**Comment by AndrewVSutherland** [comment]
This has now been fixed on both the beta and production sites.
