### ISSUE TITLE
Wrong q-expansions in the search result table for classical modular forms

### ISSUE THREAD

**Issue by assaferan** [LMFDB/lmfdb#5092]
Encountered it several times - here is an example
Going to 
https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/?hst=List&level_type=divides&level=64&weight=4&char_order=2&search_type=List
the q-expansion of 64.4.b.b is wrong, as can be seen when opening its page, i.e. compare
https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/64/4/b/b/

I suspect we are simply pulling the wrong basis for the field.

**Comment by edgarcosta** [comment]
Duplicate #4787
