### ISSUE TITLE
Jump for elliptic curves by polynomial

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5093]
For genus 2 curves, we support typing a univariate polynomial into the jump box.  It would be nice to support a similar convenience for genus 1 curves (possibly with long Weierstrass form as well).

**Comment by jwj61** [comment]
We do support giving [a1,...,a6] or [A,B], so we already do this in principle.  It is just a question of parsing an equation.

If you do parse equations, you need to decide if you will support things like x^3+y^3=2 too (i.e., general cubics).  Presumably sage has functions which can convert to standard form for that.

**Comment by JohnCremona** [comment]
> We do support giving [a1,...,a6] or [A,B], so we already do this in principle. It is just a question of parsing an equation.
> 
> If you do parse equations, you need to decide if you will support things like x^3+y^3=2 too (i.e., general cubics). Presumably sage has functions which can convert to standard form for that.

Sage does: I wrote such functions.

But I am not enthusiastic at all about allowing algebraic expressions to be input.

**Comment by AndrewVSutherland** [comment]
I think you should at least be able to type in a cubic f(x), or a pair f(x), h(x) defining y^2+h(x)y = f(x), as you can on the genus 2 pages.  I also think you should be able to type Weierstrass equations of the form y^2=f(x) or y^2+h(x)y = f(x) on both the genus 1 and 2 pages.  I don't think you should be able to do anything else (i.e. its up to you to put your elliptic curve in standard Weierstrass form which for elliptic curves means there should be a unique rational point at infinity, no y^2=quartic)

**Comment by BarinderBanwait** [comment]
I've got the Weierstrass equations functionality for genus 2 working over at [pink](https://pink.lmfdb.xyz/Genus2Curve/Q/). Some remarks:

1. It doesn't insist on 'x' and 'y'; so the user *can* insert e.g. b^2 = a^5+1, which is the same as y^2 = x^5 + 1. 
2. Variables are limited to only one letter, so the user *can't* do `banana^2 = x^5+1`.
3. If the RHS has more than one variable, it gives an error message; e.g. y^2=a+b fails.
4. For the long Weierstrass form y^2+h(x)y = f(x), the equation **must** start with `(a letter)^2+`; in particular the user can't insert h(x)y + y^2 = f(x); so in particular, the input `y^2 + x*y = x^5 - 9*x^4 + 21*x^3 - 4*x^2 + x` works, but `x*y + y^2 = x^5 - 9*x^4 + 21*x^3 - 4*x^2 + x` does not.
5. `*` is not insisted upon between numbers and letters; so for example `y^2 + x*y = x^5 - 9x^4 + 21x^3 - 4x^2 + x` works, but `y^2 + xy = x^5 - 9x^4 + 21x^3 - 4x^2 + x` does not; however,  `y^2 + (x)y = x^5 - 9x^4 + 21x^3 - 4x^2 + x` does work.

Are people happy with the above behaviour? Should there be any changes to it?

When there's agreement I'll use the same behaviour for elliptic curves, and update the `search_input` knowls accordingly.

**Comment by AndrewVSutherland** [comment]
LGTM

**Comment by AndrewVSutherland** [comment]
I was about to close this issue, but noticed that typing `4x^3+4x+1` into the ECQ jump box gives the error message "The equation defined by $y^{2} = 4 x^{3} + 4 x + 4$ does not define an elliptic curve", whereas typing `4x^5+4x+1` into the G2C jump box works as expected.

**Comment by BarinderBanwait** [comment]
Oh dear -- I'll take a look at this later today, should be a quick fix

**Comment by BarinderBanwait** [comment]
The PR #5245 fixes this. The issue was that the sage function `EllipticCurve_from_Weierstrass_polynomial` insists on the coefficients of `y^2` and `-x^3` to be the same, so that was raising an error. However, the sage in-built constructor `Jacobian` is more flexible, so the fix here was to use `Jacobian` when the coefficient of `x^3` is not `-1`. (One could just always use `Jacobian`, but it seems to take slightly longer to run, so only doing that if necessary.)

Test added with original failure `4x^3+4x+1`

**Comment by JohnCremona** [comment]
Can this be closed?

**Comment by edgarcosta** [comment]
I think so, but I will let @BarinderBanwait and @roed314  comment
