### ISSUE TITLE
Monogenic search column for number fields is not working

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5100]
On

https://beta.lmfdb.org/NumberField/?hst=List&degree=2&search_type=List&showcol=monogenic

we have selected to show a column for whether or not the field is monogenic, but the column does not display anything (even though all quadratic fields are and the database knows it).  I think the problem is that the code expects the column to be boolean but it is really an integer with values -1, 0, or 1 with 0 meaning not computed.  Is there a SearchColumn type for yes/no/maybe information?

**Comment by roed314** [comment]
There isn't one at the moment, but I think this would be a good class to add to `lmfdb/utils/search_columns.py`.
