### ISSUE TITLE
Wrong fields of coefficients, and too large display. 

### ISSUE THREAD

**Issue by swisherh** [LMFDB/lmfdb#511]
On http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/9/12/1/ , the coefficents of form c are defined in terms of a2, which is not defined clearly - all that is clear is that it lies in Qsqrt70. Besdies, clicking on form c reveals that a2 is actually 6sqrt70, and not sqrt70 as one might think. This is extremely confusing.
Maybe it would be good to have a script looking at the modular forms in the database, searching for the field of coefficients in the database of number fields and replacing the coefficients with a new expression in terms of the generator that is in the database?

**Comment by davidfarmer** [comment]
\alpha_j would be less confusing than a_j

**Comment by JohnCremona** [comment]
See #669 also.

**Comment by fredstro** [comment]
This looks nice now. Stephan agrees...
