### ISSUE TITLE
Global field/p-adic field data pull request

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5120]
Please upload lf_fields and nf_fields (and the nf extra table to be safe) to the cloud.

The p-adic fields now has degree 18 extensions of Q_2.

The global fields have updates to local algebras to include ones which are the new p-adic fields, and some updates on monogenic fields.

**Comment by edgarcosta** [comment]
on it

**Comment by edgarcosta** [comment]
Done

@jwj61 please check that everything is there, and if so, close the issue.
