### ISSUE TITLE
Slow number field search

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5121]
From the feedback page:

Tried searching for non-Galois totally complex sextic fields with Galois group D6, and "the search took longer than expected". Searching without restriction on Galois group is fine, and the fields with Galois group D6 do show up in the results. Did not actually cause me any problems but I figured I'd report the error anyway!

https://www.lmfdb.org/NumberField/?hst=List&degree=6&signature=%5B0%2C3%5D&galois_group=D6&is_galois=no&search_type=List

-------------------
I tried it and the first time it was a little slow, but did come up.  I am not sure if there is anything to be done.

**Comment by AndrewVSutherland** [comment]
Seems to have been intermittent, closing.
