### ISSUE TITLE
Page loading problem

### ISSUE THREAD

**Issue by swisherh** [LMFDB/lmfdb#513]
Page does not load (it only does once in a while):
http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/23/10/1/

**Comment by davidfarmer** [comment]
The page partially loaded on my local copy, and then waited for a minute or two before completely loading.  The delay was due to the long time it took to render the coefficients in a number field.

**Comment by sehlen** [comment]
This is fixed in refactor (my clone). I issued a pull request to @fredstro's clone.

**Comment by davidfarmer** [comment]
Fixed in Fredrik's refactor branch
