### ISSUE TITLE
Wrong results in group search

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5146]
From the feedback page:

On the abstract groups search results, when setting the field Direct Product to “no”, the group 32.51 should not show up, but it seems to be listed as a group that is a non-direct product. (Of course, by definition, it is the direct product C_2 x C_2 x C_2 x C_2 x C_2.)  Love this new feature by the way — hope this is helpful and thank you!

https://beta.lmfdb.org/Groups/Abstract/?hst=List&order=32&cyclic=no&direct_product=no&semidirect_product=no&search_type=List

**Comment by SamSchiavone** [comment]
I think I've fixed the bugs in the code that were causing this bad data. So once we recompute the data, this should now be correct.

**Comment by ytrepus** [comment]
Hi @SamSchiavone I was the person who raised the original feedback, and can confirm it's all fixed in case anyone would like to close this?  (@jwj61 )

Thank you both and sorry for the almost year delay in checking in!
