### ISSUE TITLE
"raw_typeset undefined" error on sibling fields that have a polynomial but no label

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5159]
The number field knowls in the sibling data do not work properly in cases where a defining polynomial for the sibling field is known but the sibling field itself is not in the LMFDB,

Click on the "Deg 12" link in the list of sibling fields on https://www.lmfdb.org/NumberField/5.5.106588382947225.1 to reproduce: you will see a knowl with the error message

`ERROR in the template: 'raw_typeset' is undefined. Please edit it to resolve the problem.`

I'm sure this is easy to fix, I'm just not sure exactly where the fix needs to be made.

**Comment by edgarcosta** [comment]
I think we are forgetting to make raw_typeset exposed to Jinja, as we other
functions that we use in knowls
