### ISSUE TITLE
Search Crash

### ISSUE THREAD

**Issue by swisherh** [LMFDB/lmfdb#516]
Search for a weight >=26 crashes:
http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/ranges?level=&weight=26&character=0&Submit=Search
produces AttributeError: 'str' object has no attribute 'get'

**Comment by JohnCremona** [comment]
The above link gives no errors now, though nothing appears for weights >  12.  OK to close?

**Comment by davidfarmer** [comment]
fixed in Fredrik's refactor branch
