### ISSUE TITLE
Genus 2 search by curve equation not working

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5185]
For some reason the search https://www.lmfdb.org/Genus2Curve/Q/?jump=x%5E5%2B1 is not working, although I believe it was in the past and the same search on beta does work: https://beta.lmfdb.org/Genus2Curve/Q/?jump=x%5E5%2B1.

Magma is installed and available on prodweb1 and prodweb2, so there is no reason this search should fail.

**Comment by roed314** [comment]
This worked for me when I just tried it.  Drew, is it still failing for you?  Did anyone do anything to fix the issue, or did it just resolve itself?

**Comment by AndrewVSutherland** [comment]
Yes, I am getting the error right now (on both chrome and firefox, running on Ubuntu).

**Comment by roed314** [comment]
Weird.  It works for me on all of chrome, firefox and safari running on OS X.  What's the error you're seeing?

**Comment by AndrewVSutherland** [comment]
![image](https://user-images.githubusercontent.com/11425002/185965741-6c569977-4c15-45a3-9326-4a2a21973ec1.png)

**Comment by roed314** [comment]
I'm very confused how this can fail on production with ubuntu but succeed on beta with ubuntu and succeed on production with OS X.  Here's the relevant code that produces that error:

```
R = PolynomialRing(QQ, "x")
fg = [R(list(coeff_to_poly(elt))) for elt in input_str.split(",")]
if len(fg) == 1:
    fg.append(R(0))
C_str_latex = fr"\({latex(y**2 + y*fg[1])} = {latex(fg[0])}\)"
try:
    C = magma.HyperellipticCurve(fg)
    g2 = magma.G2Invariants(C)
except TypeError:
    raise ValueError(f'{C_str_latex} invalid genus 2 curve')
```

**Comment by AndrewVSutherland** [comment]
I've tried on three different computers running ubuntu (well, Pop/OS actually) and hit the same problem on all of them.  I also hit the problem on my iPad (in both safari and chrome), but not on my iPhone.

Can someone else try this and report the results?  The link is https://www.lmfdb.org/Genus2Curve/Q/?jump=x%5E5%2B1.

**Comment by edgarcosta** [comment]
One of the servers prodweb1.lmfdb.xyz is having issues starting sage inside
magma while the other prodweb2 is fine starting magma and thus succeeding.
Don't ask me why...
This is why the code quits magma after a successful run, it was my attempt
to fix this issue.


But I'm also quite sure that a restart fixes it temporarily.

**Comment by JohnCremona** [comment]
Is it really necessary to be calling magma on the fly at all?

**Comment by AndrewVSutherland** [comment]
@edgarcosta I find your explanation slightly suspect given that I have tried this query many times on many different machines in the last few days, and it has never worked on an Ubuntu machine -- wouldn't I occasionally be hitting prodweb1?  Moreover, it always works on my iPhone, even when it is using the exact same network as a linux machine next to it where it does not work -- I don't see why one of them would be consistently directed to prodweb1 and the other to prodweb2.

**Comment by roed314** [comment]
It's possible to test directly: I just visited http://prodweb1.lmfdb.xyz/Genus2Curve/Q/?jump=x%5E5%2B1 and had no problems on OS X with chrome.

**Comment by AndrewVSutherland** [comment]
So

http://prodweb1.lmfdb.xyz/Genus2Curve/Q/?jump=x%5E5%2B1

works for me on linux/chrome but

http://prodweb2.lmfdb.xyz/Genus2Curve/Q/?jump=x%5E5%2B1

does not.  @roed314 does the second link work for you?

**Comment by roed314** [comment]
The second link is broken for me as well.

**Comment by AndrewVSutherland** [comment]
@edgarcosta so I will modify my criticism of your explanation to say that I think you are correct in that it is simply a matter of whether one is accessing prodweb1 or prodweb2 and has nothing to do with the client os/browser (which never made any sense), but I think you have it exactly backwards, prodweb1 is working fine, it is prodweb2 that is having problems.

**Comment by roed314** [comment]
I just tried directly on prodweb2 and both magma and sage successfully find G2 invariants when first started.  So Edgar's hypothesis that the problem is around magma restarting while running for a long time seems reasonable.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Things are a bit more complicated for genus 2 curves because there are many more types of twists to consider and there are not invariants like c4 and c6 that will let you easily pin down the Q-isomorphism class within a Qbar-isomorphism class.  The code uses G2 invariants to get the correct Qbar isomorphism class, but then checks for Q-isomorphism against each curve in the database in this Qbar isomorphism class (when there is more than one).

I have actually posed the problem of coming up with a set of easily computable invariants that would pin down the Q-isomorphism class of a genus 2 curve to a number of people (and in various problem sessions) over the years, but to my knowledge this is still an open problem, even though it should be easy to solve in principle (modulo the "easily computable" part).

As far as I know this is the only place where we currently run Magma on the website.  I'm generally in favor of not using anything we don't need to, and in an ideal world the website would not depend on either Magma or Sage  (you may recall the discussion a while back about whether we would remove the dependence on Sage as a way to get around the problems we were having with the debugger).  But providing a way for people to find the object they are looking for in the LMFDB is a use case I think we should try to accommodate whenever possible.  The same sort of issue will likely arise in the future when we add genus 3 curves.

**Comment by roed314** [comment]
The Magma code for `IsIsomorphic` and `G2Invariants` was written by Lercier, Ritzenthaler and Sijsling and is released under the LGPL.  I don't think there are any legal issues in porting this to Sage.  It would certainly be nice for the LMFDB to not rely on magma at runtime.

**Comment by edgarcosta** [comment]
The `G2Invariants` is trivial to port.
`IsIsomorphic` was not implemented by them, and relies on checking if the two degree even models are in the same GL2 orbit.

**Comment by roed314** [comment]
The copyright header on `Magma/package/Geometry/CrvHyp/G3Invs/toolbox/isgl2equiv.m` has their names on it.  I'm not sure if that file is self contained though, so I don't quite know how big the porting job is (and whether all the code involved is LGPL).

**Comment by edgarcosta** [comment]
but it still calls `IsGL2Equivalent` in `Magma/package/Geometry/CrvHyp/transform.m`

**Comment by edgarcosta** [comment]
I will investigate this more on Tuesday, as despite both servers getting rebooted only one of them succeeds at the query...

**Comment by edgarcosta** [comment]
I realized that the best way to do this in Sage (and even Magma) is just to test for isomorphism via the period matrix.
That should be easier to implement.
Anyhow, looking now into what is wrong with prodweb2 calling magma.

**Comment by AndrewVSutherland** [comment]
Thanks!  It would be really nice to get this fixed...

**Comment by edgarcosta** [comment]
it is fixed at the moment, but still unclear why it breaks.

I'm upgrading sage on both machines with the hope that it will fix it permanently.

**Comment by edgarcosta** [comment]
I cloned prodweb1 to prodweb2, and hopefully, this is a permanent fix.
