### ISSUE TITLE
Bianchi forms twist-of-base-change data errors

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#5187]
For Bianchi forms which are not themselves base-change, but which are twists of base-change, the column 'bc' in the table bmf_forms stores a negative integer -d which is supposed to indicate that the form is a twist of the base-change of a form over Q with coefficients in Q(sqrt(d)).  (In partcular, with coefficients in Q when the entry is -1.)    But these values are incorrect in some cases, because of incorrect assumptions in the code which computed them.

For example:   https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.31.1/324.2/a/?numeigs=100  which says that it is twist of b.c. of a form with coefficients in Q(sqrt(3)).  This BMF certainly is twist of b.c., but it is more complicated than as described.  I have not yet worked out the details in this example, but I think that it cannot be a *quadratic* twist of base-change at all, but a more complicated example (as in https://arxiv.org/abs/1907.12103, though here we do have an elliptic curve).

The simplest short-term fix is a small code change so that for all BMFs which are twist of base-change say just that, without specifying the Hecke field downstairs.

Incidentally, `db.bmf_forms.column_description('bc')` returns "Base change flag: d>0 if form is base change from Q with eigs in Q(sqrt(d)), 0 if not base-change" which is incomplete as it does not document what a negative value indicates (or was supposed to).

**Comment by JohnCremona** [comment]
The upshot is this:  a total of 8 BMFs will have their bc column changed, 2 over field -19 and 6 over -43:

2.0.19.1-6400.2-d,g: change from -1 to -5 (i.e. these are marked as twist of base-change, but not that the underlying form has coefficients in Q(sqrt(5))).

2.0.43.1-10609.[1,3]-a and 2.0.43.1-11449.[1,3]-a: change from 0 to -6 (i.e. these are not marked as b.c. or twist of b.c., but they are twist of b.c. of a form with coefficients in Q(sqrt(6))).

2.0.43.1-12427.[1,3]-a: change from 0 to -1 (i.e. these are not marked as b.c. or twist, but are twist of b.c. of a form qith coefficients in Q).

For the record, the issue is this:  to test for b.c. or twist of b.c. one looks at pairs of *split* conjugate good primes P, P' and checks whether a_P=a_P' always (for b.c.) or |a_P|=|a_P'| always (for twist of b.c.).  This is not problematical since we have plenty of a_P.  But to determine the coefficient field of the underlying form one needs to look at the a_P for *inert* P, and since we order primes by norm, we have very few of these, not always enough to reach an unambiguous conclusion.   I have upgraded my code to do a better job of this, and there were several dozen forms for which I had to compute more a_P (500 not just 100) in order to determine the correct value.  In most of these cases the result was to confirm the value I already had, but there were these 8 exceptions.

Some of what I wrote in the original issue description was incorrect but I'll leave it as is.

I'll close this once I have updated the 8 values on beta and copied the table bmf_forms to prod.

**Comment by JohnCremona** [comment]
Data correct on beta.  The affected pages are:

https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.19.1/6400.2/d/
https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.19.1/6400.2/g/
https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.43.1/10609.1/a/
https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.43.1/10609.3/a/
https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.43.1/11449.1/a/
https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.43.1/11449.3/a/
https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.43.1/12427.1/a/
https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.43.1/12427.3/a/

e.g. compare the last one of these with https://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.43.1/12427.3/a/

Please could someone copy bmf_forms to prod?

**Comment by AndrewVSutherland** [comment]
bmf_forms has been copied to production, can you please take a look and confirm that everything looks okay?

**Comment by JohnCremona** [comment]
> bmf_forms has been copied to production, can you please take a look and confirm that everything looks okay?

yes, all looks good.  Thanks!

**Comment by JohnCremona** [comment]
I missed some more when I did this 2 weeks ago, so am reopening this until fixed.

**Comment by JohnCremona** [comment]
OK, this time I am confident that I caught all the missing cases (fields -43, -23, -31 only, a total of 40 newforms).  In all cases the form was displaying as "base change: no" which was strictly correct but now displays as "no, but is a twist of the base change of a form over $\mathbb{Q}$" or "no, but is a twist of the base change of a form over $\mathbb{Q}$ with coefficients in $\mathbb{Q}(\sqrt{10})$" or similar.  For example,
  
https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.31.1/4900.16/h/

Please could someone again copy bmf_forms to prod?  Thanks again.

**Comment by AndrewVSutherland** [comment]
bmf_forms has been copied over to prod, for example, see

https://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.31.1/4900.16/h/

**Comment by JohnCremona** [comment]
Many thanks @AndrewVSutherland I sincerely hope this is the last  such correction (though I will have a lot of new data quite soon).
