### ISSUE TITLE
download data for ECs does not match search

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#5195]
As reported via sage-support:

"For some reason when I download Sage data from the following search:

http://www.lmfdb.org/EllipticCurve/Q/?hst=List&conductor_type=prime&conductor=1-10000000&rank=0%2C2%2C4%2C6%2C8%2C10&optimal=on&search_type=List

I get all curves in the isogeny class, even though on the search page I only get one curve per isogeny class."

**Comment by roed314** [comment]
This seems to be a duplicate of #5091.

**Comment by JohnCremona** [comment]
> This seems to be a duplicate of #5091.

Agreed

**Comment by JohnCremona** [comment]
My debugging has reached the following conclusions so far.  I noted that (when running in debug mode so that the query is shown at the bottom of the page), on http://localhost:37777/EllipticCurve/Q/?conductor=11&optimal=on&search_type=List the quesry is only {'conductor': 11}.  The effect of "optimal=on" is to add query["__one_per__"] = "lmfdb_iso" to the query, but then the search wrapper *removes* this as it handles the condition of showing only one search result per value in a column (here the lmfdb_iso column identifies the isogeny class).  So by the time the Download button is pressed, the query has changed.

So this is a bug in the implementation of the one_per mechanism -- which I see is not used anywhere else than EC/Q.

I note that for ECNF this is handled in a simpler way, namely instead of "optimal=on" we have "number=1" which means that only the first curve in each class is returned.  This is not actually adequate (and that's why something more complicated was done for EC/Q),  since it does not work properly when search fields specify something which is not an isogeny invariant.  SO, while I quick fix would apparently be to use the same mechanism for EC/Q as we used to and we still do for ECNF,  it woul be better to fix the one_per code, and then also use it for ECNF.

**Comment by JohnCremona** [comment]
I should have written the comment above at #5091, as this is closed as a duplicate -- so I will copy the comment there now.
