### ISSUE TITLE
Download L-function search results needed

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5204]
You should be able to download L-function search results from pages

    https://www.lmfdb.org/L/rational?hst=List&analytic_conductor=0.1-0.11&search_type=List

the way you can from all other search result pages, including

    https://www.lmfdb.org/EllipticCurve/Q/?conductor=1-100&search_type=List

**Comment by roed314** [comment]
Will be fixed by #5702.

**Comment by davidfarmer** [comment]
Was fixed by #5702
