### ISSUE TITLE
Title for L-function of genus 2 curve

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#521]
We say "L(A,s), where A is a genus 2 curve of conductor N", which is funny; we probably mean A is an abelian surface or C is a genus 2 curve.

**Comment by kedlaya** [comment]
Not just funny, but also mathematically inaccurate: the conductor we are reporting is the conductor of the Jacobian = the conductor of the L-function, whereas the "conductor of the curve" (which I don't actually know how to define) would be divisible by possibly a larger set of primes. (The difference would be the primes where the reduction of the Jacobian leaves the Torelli locus, by degenerating to a product of elliptic curves.)

**Comment by nmascot** [comment]
Working on it

**Comment by nmascot** [comment]
I suggest "L(A,s), where A is the Jacobian of a genus 2 curve and has conductor N".
I do realise it is a bit long, so please make suggestions :)

**Comment by nmascot** [comment]
Submitted pull request #528.

**Comment by davidfarmer** [comment]
This will be changed again as a result of changing how the L-function page titles are specified.
Work in progress.

**Comment by davidfarmer** [comment]
In the next pull request it is changed to 
"...where $A$ is the Jacobian of a genus 2 curve with label..."
