### ISSUE TITLE
Genus 2 curve missing elliptic curve friends?

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#522]
For the curve
  http://www.lmfdb.org/Genus2Curve/Q/720/b/116640/1
it says it is not simple over QQ, but it has no elliptic curve friends.

**Comment by jvoight** [comment]
Same for http://www.lmfdb.org/Genus2Curve/Q/614656/a/614656/1

**Comment by davidfarmer** [comment]
That information doesn't seem to be in the database.

**Comment by JohnCremona** [comment]
Do you know what the conductors of the elliptic curves would be?

John

**Comment by steffenmueller** [comment]
For 720.b.116640.1 the curves are 24.a4 and 30.a6.

Steffen Mueller

**Comment by steffenmueller** [comment]
For 614656/a/614656/1 it's the square of 784.g2.

**Comment by steffenmueller** [comment]
Whoops, apparently that information has already been added...

**Comment by JohnCremona** [comment]
On 25 March 2016 at 15:24, Steffen Müller <notifications@github.com> wrote:

> Whoops, apparently that information has already been added...
>

I seem to remember there was an issue with Cremona / LMFDB labels, and we
fixed it.  So perhaps this issue can be closed.

**Comment by jvoight** [comment]
This is not ready to be closed yet: although the elliptic curves appear in the main body, they are not listed in the "Friends" tab on the right-hand side.  This should be quick to add, and they belong there.

**Comment by AurelPage** [comment]
working on it.

**Comment by AurelPage** [comment]
Fixed by PR #895. Ready to be closed?
