### ISSUE TITLE
Extra linting options when merging into dev/web?

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#5224]
When merging from master->{dev, web} we should perhaps take the opportunity to check for extra linting options that we want our code to satisfy but don't want to bother contributors with it.
In particular, several of @fchapoton contributions that fixed:
- E251 : unexpected spaces around keyword / parameter equals
- E241: multiple spaces after ‘,’
- E203: whitespace before ‘,’, ‘;’, or ‘:’
- E304: blank lines found after function decorator
- E702: multiple statements on one line (semicolon)

**Comment by fchapoton** [comment]
after #5225, the pep code E301 will also be fixed

**Comment by fchapoton** [comment]
after #5230, also E222 will be fixed
