### ISSUE TITLE
Z-function is totally negative

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#524]
http://www.lmfdb.org/L/Genus2Curve/Q/614656/a/

The L-function is the square of an elliptic curve.  I'm surprised that after analytic continuation, you end up with a function which takes only nonpositive values.  (For all I know, this comes from the functional equation and could be correct!)

**Comment by jvoight** [comment]
This is correct!  The normalization of the Z-function involves taking a square root of the sign, which in this case is -1.  (It's still a bit weird, so maybe some day we should explain this--in the knowl maybe?)  JV

**Comment by davidfarmer** [comment]
It is the square of something which has sign -1, so it is the
square of something purely imaginary.

Note that it would be reasonable to use a different normalization.
