### ISSUE TITLE
Improve character tables

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#525]
Character tables are poorly displayed when they are very large, e.g. for 20T1030.  They are also not connected with other things like Artin representations, and the columns may not match the ordering of the conjugacy classes.

**Comment by jwj61** [comment]
Also, they should be more clear as to what special symbols are, and what the data above the table means.

This will likely be handled through the finite groups project.

**Comment by jenpaulhus** [comment]
Ok to remove the finite groups label now that we have a new beta with improved character tables and this is more about the other pages? (I'm trying to clean up old issues since we'll be adding new issues with the revamped beta pages.)

**Comment by jwj61** [comment]
No
