### ISSUE TITLE
Upload number field database

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5250]
There are new number fields in nf_fields

  - complete lists in degrees 8 and 9 of small discriminant
  - degree 16 fields unramified outside {2,3} or {2,5} with Galois group being a 2-group (of interest because they are connected to 2-adic fields

**Comment by edgarcosta** [comment]
on it

**Comment by edgarcosta** [comment]
done. please close the issue if everything looks good.

**Comment by jwj61** [comment]
Search for degree 16 number fields has more results on beta than on the production server.

**Comment by jwj61** [comment]
It looks like the fields are there, but the counts table needs to be updated.

**Comment by edgarcosta** [comment]
Please check again if everything looks good.

**Comment by jwj61** [comment]
The count for search results for

https://www.lmfdb.org/NumberField/?hst=List&degree=16&search_type=List

is too low.  The fields are there, because if I add a criteria like "unramified at 8675309" (the "Jenny prime"), the number of results goes up.  I tried it in a different browser and got the same result, so I don't think it is caching on my end (unless chrome and brave share a cache).  Anyway, that is why I think the counts table needs to be updated.

**Comment by edgarcosta** [comment]
I think it is fixed now.
