### ISSUE TITLE
Upload p-adic field database

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5251]
There are new p-adic fields in lf_fields in degree 16 with p=2.  The list is far from complete, but it gives a substantial number which arise from global 2-3 fields (and the unramified extension).

**Comment by edgarcosta** [comment]
on it

**Comment by edgarcosta** [comment]
done. please close the issue if everything looks good.

**Comment by jwj61** [comment]
The new fields don't seem to be there

https://beta.lmfdb.org/padicField/?n=16&p=2&search_type=List
http://www.lmfdb.org/padicField/?n=16&p=2&search_type=List
