### ISSUE TITLE
Additional Bianchi data and ECNF data over imaginary quadratic fields

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#5268]
I now have BMF data for all imaginary quadratic fields with absolute discriminant up to 100, which is 21 more fields than the 11 in the database at present (9 with class number 1 and 2 with class number 3).   As for the existing fields, the data consists of dimensions of cusp form spaces and new subspaces, and details for all rational newforms; for all the additional fields this goes  up to level norm 1000, with 100 aP for each.

Secdonly, for all these rational newforms with a few exceptions, I have elliptic curves, hence (subject to the standard modularity conjectures) all elliptic curves of conductor norm up to 1000 for all these fields.  There are some more rational newforms with no curve (as listed in #3058 which I will update): 6 for 2.0.56.1, 2 for 2.0.68.1 and 2 for 2.0.95.1.

When I have uploaded the data there will be a small PR  (to handle the known missing curves and to add some of the new fields to the top browse page), and some knowl editing (e.g. http://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/Completeness).

**Comment by JohnCremona** [comment]
I noticed that the ecnf stats page was not updated even though the data upload using copy_from does refresh stats.

No more data to be uploaded today. Tomorrow I will finish the upload with 2.0.95.1, that's the only one I couldn't do today.

**Comment by roed314** [comment]
Alright, I think the browse pages are at least not producing errors: https://beta.lmfdb.org/EllipticCurve/browse/2/

**Comment by JohnCremona** [comment]
NB The extra data causes one BMF test to fail now which will be fixed in the PR.

**Comment by JohnCremona** [comment]
To complete this, the following tasks are needed to be done in the right order:
   1. update code on beta (which already sees the new data and the new extent (etc) knowls)
   2. copy data (ec_nfcurves, bmf_forms, bmf_dims) to prod
   3. update code on prod
   4. positively review relevant knowls on beta so they appear on prod.

1 is first (only affecting beta), then 2 and lastly 3+4 preferably at the same time.  prod should work fine with new data only though some search results could look inconsistent with the extent knowls.  I'll liist the relevant knowls here:

rcs.source.mf.bianchi
rcs.cande.mf.bianchi
rcs.source.ec
rcs.cande.ec

**Comment by edgarcosta** [comment]
FYI, `ec_nfcurves` was pushed last night to prod to fix some broken `galois_images`

**Comment by JohnCremona** [comment]
> FYI, `ec_nfcurves` was pushed last night to prod to fix some broken `galois_images`

OK thanks, so no need to copy that again.  I just checked (with a random curve over 2.0.95.1) that the curve displays fine, though with no link to a BMF.

**Comment by JohnCremona** [comment]
Please someone review the updated knowls, as right now the completeness info does not match the new data on prod

**Comment by AndrewVSutherland** [comment]
I reviewed the Bianchi completeness knowl, but https://beta.lmfdb.xyz/EllipticCurve/Completeness looks out of date to me on beta.

**Comment by AndrewVSutherland** [comment]
Never mind, its fine (I just marked it as reviewed).

**Comment by JohnCremona** [comment]
Thanks
