### ISSUE TITLE
Number field data pull request

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5278]
This is for both nf_fields and lf_fields .  Changes are

- new Q_8 fields
- local algebras have been recomputed for fields of degree >= 16 to capture completions which hit recently added 2-adic fields in degree 16
- updating the flag in lf_fields for when a p-adic field is the completion of a global field (to account for the new Q_8 global fields, and older high degree fields which now have a degree 16 completion in the p-adic database)

The number field completeness and acknowledgments knowls have been updated (so should be reviewed when the data is uploaded to the main server).

**Comment by AndrewVSutherland** [comment]
This is in progress now.

**Comment by AndrewVSutherland** [comment]
This has been done.  Thank you @edgarcosta for helping to sort out the deadlock I ran into while trying to do this yesterday!
