### ISSUE TITLE
Better handling of large search result downloads

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5293]
We should make search result downloads use streams rather than creating the entire payload in memory, and the user should be able to continue browsing the LMFDB while the download is in progress.  There are various ways to do this in Flask (see this [repo](https://github.com/izmailoff/python_flask_file_streaming) for an example).

With a streaming approach I think we could efficiently handle arbitrary size downloads that would be limited only by the user's patience without putting too much burden on the server (the user's network connection will effectively throttle the load).

This issue will become more urgent when #4933 is addressed, as the downloads will become larger once users have the ability to request additional columns.

**Comment by AndrewVSutherland** [comment]
PR #5702 will address this issue.

**Comment by jvoight** [comment]
@AndrewVSutherland, @roed314 : Hey, did we fix this, or is it entangled in some other issues?

**Comment by roed314** [comment]
I do think that this is worth closing, but there were issues with generators that never got resolved.  In particular, if the estimated size for the download is larger than 100MB, we point users to the API or postgres interface.  It would be nice if we could stream very large downloads, but @edgarcosta and I couldn't get this to work with gunicorn's timeout.

**Comment by edgarcosta** [comment]
Did we try this https://github.com/benoitc/gunicorn/issues/1736?

**Comment by roed314** [comment]
I'm not sure what you mean by that issue, but we did try various async worker options.

**Comment by jvoight** [comment]
If you'd like to add an issue as a feature request to handle large downloads, that makes sense to me.  (But at least from my point of view, it sounds like a "it would be nice if", and not sure where that fits into our priorities!)

**Comment by AndrewVSutherland** [comment]
The main problem this issue was concerned with (making downloads asynchronous) has been addressed, which is why I closed the issue.  I do notice that for large downloads like

https://www.lmfdb.org/NumberField/?discriminant=-900000-900000

will typically fail before finishing.  Possibly that is an issue with my internet connection, but I'd be curious to know if any one else is able to complete the download above.

**Comment by roed314** [comment]
I failed as well: it left a 48MB fragment in my Download folder containing 963767 rows, which is just barely shy of the 967877 total.  So if I try a few times I might get lucky.  Surprisingly, beta was slower and only got through 649750 rows.

I'll add an issue for dealing with this, but I agree that it's not high priority.
