### ISSUE TITLE
Link goes to to wrong knowl

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5299]
From the feedback page:

On http://www.lmfdb.org/Character/Dirichlet/?modulus=442

Click the Parity column head shows definition of Primitive (not parity). Other heads are not affected.

**Comment by Rishav1707** [comment]
https://user-images.githubusercontent.com/97666287/210219970-a3750672-3752-4a80-85ac-d7313ffb51a1.mp4

I think it shows the correct definition @jwj61

**Comment by maddy020** [comment]
Hey @jwj61 
I would like to work on this issue
I have seen the error but unable to find the file in the code base
Can you guide by telling the file name

**Comment by AndrewVSutherland** [comment]
@maddy020 Thanks for the offer!  But actually this has already been fixed (the change is at https://github.com/LMFDB/lmfdb/blob/master/lmfdb/characters/main.py#L217).
