### ISSUE TITLE
Add "flash" for error messages in searching

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#530]
Need this in several places.

**Comment by sanni85** [comment]
working on this

**Comment by sanni85** [comment]
After April I have no clue if this is still an issue and where.

For example, here: http://beta.lmfdb.org/ModularForm/GSp/Q/Kp.2_PY2_389/
if you fill in any box with stupid input, javascript is used to validate the input, no flash message is returned.

**Comment by jvoight** [comment]
@davidfarmer I also am not clear if this is still a critical issue or not.  Can you give a specific example where this is needed?

**Comment by davidfarmer** [comment]
I removed the "critical"

**Comment by jvoight** [comment]
I'm just closing this until we have an idea what it means.  (Next time, let's keep a minimal nonworking example.)
