### ISSUE TITLE
List of papers mentioning LMFDB

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#532]

**Comment by jvoight** [comment]
This is a really good idea!  I think it should be a milestone 1.0.

**Comment by alinabucur** [comment]
ok, i assigned the milestone and jv to this.

**Comment by JohnCremona** [comment]
See also #533

**Comment by JohnCremona** [comment]
Pull request #1932 implements this, using the separate citations repository to make the 2 html files needed.

**Comment by davidlowryduda** [comment]
I believe pull request #1932 was merged and this can be closed. Unless perhaps I'm missing something?

**Comment by JohnCremona** [comment]
No, this can be closed.  Thanks
