### ISSUE TITLE
Incorrect q-expansion blurb

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#5327]
The modular form
  https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/37/2/b/a/
advertises that the q-expansion is in terms of i = sqrt(-1), but in fact it is given in terms of beta which is not defined.

**Comment by BarinderBanwait** [comment]
i'll look into it ...

**Comment by BarinderBanwait** [comment]
i believe the above PR addresses this

**Comment by AndrewVSutherland** [comment]
The fix has been pushed to production, thanks @BarinderBanwait !
