### ISSUE TITLE
Server errors

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#5329]
We should fix the following servers errors:
- https://blue.lmfdb.xyz/L/1675701001-ror_session_fixation.nasl

and that we trigger download it makes sense, e.g., not allow:
- https://blue.lmfdb.xyz/EllipticCurve/Q/5077/a/1/download/magma.old 
- https://blue.lmfdb.xyz/EllipticCurve/Q/5077/a/1/download/.gp.swp
- https://blue.lmfdb.xyz/EllipticCurve/Q/5077/a/1/download/.magma.swp
- https://blue.lmfdb.xyz/EllipticCurve/Q/5077/a/1/download/.sage.swp
- https://blue.lmfdb.xyz/EllipticCurve/Q/5077/a/1/download/gp.1
- https://blue.lmfdb.xyz/EllipticCurve/Q/5077/a/1/download/gp.bak

**Comment by edgarcosta** [comment]
I used blue, to not get warned again about these errors.

**Comment by AndrewVSutherland** [comment]
Fixed via #5332 and #5333
