### ISSUE TITLE
Repository of bibliographic references

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#533]
So that we can refer to them in knowls and expository material.

**Comment by JohnCremona** [comment]
See also #532

**Comment by AndrewVSutherland** [comment]
This could be accomplished in an automated way by providing a page that is populated by finding all occurrences of \cite in knowls, and using doi/arxiv/mr links to extract metadata -- this would have the advantage of also allowing one to see a list of the knowls that cite each reference, and also help us to uniformize citations (the same paper may be cited in different ways).

**Comment by jvoight** [comment]
Current citation in knowls satisfies the original request; we're not clear on how useful it would be to dump all of these into one place.
