### ISSUE TITLE
Knowl opened from a table header appears centered

### ISSUE THREAD

**Issue by sibilant** [LMFDB/lmfdb#534]
From the Dirichlet character main page, you can search for characters with specified modulus, conductor and order. The result is a displayed table of characters with header titles such as "character", "conductor", etc. If you click on a header to open the knowl, the knowl text appears centered (presumably because the table headers are). 

Example: 
http://www.lmfdb.org/Character/Dirichlet/?modulus=1&conductor=1&order=1
Click on "character" in the table header for a particularly striking example.

**Comment by alinabucur** [comment]
This was a problem with a lot of pages, Anna Haensch and I fixed a bunch in Corvallis. It is basically an issue with redefining table styles in various homepage templates.

**Comment by AndrewVSutherland** [comment]
After the recent round of cleanup to the Dirichlet character pages this problem no longer occurs.
