### ISSUE TITLE
Number field ramified primes

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#5345]
In the properties box, does it always just say "see page"?  Even
  http://www.lmfdb.org/NumberField/2.0.4.1
says this.  If so, why do we bother saying anything there at all?

**Comment by jwj61** [comment]
I had no idea we did that at all!  I am sure it was put in to save space when there are really large primes

**Comment by jvoight** [comment]
Sorry for picking on such a small thing, I just thought it was funny.  :)

**Comment by jwj61** [comment]
It should be changed.  It is kind of ridiculous now.
