### ISSUE TITLE
Uneditable knowls

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5348]
If you go to https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.7.1/10000.1/b/ when you are logged in and try to edit the top knowl you will receive the error message
```
Label 'bianchi.2.0.7.1-10000.1-b' contains characters not allowed by knowl database; updated allowed_id function or change label scheme
```
If you go directly to https://beta.lmfdb.org/knowledge/show/mf.bianchi.2.0.7.1-10000.1-b.top, and try to edit the knowl, the same error appears.

**Comment by roed314** [comment]
This was fixed by #5355.
