### ISSUE TITLE
Incorrect data in mod ell images of Galois representations

### ISSUE THREAD

**Issue by davidlowryduda** [LMFDB/lmfdb#5364]
I am reporting something noted to me by Abbey Bourdon.

Look at a page like https://www.lmfdb.org/EllipticCurve/Q/338/b/1. Under `Galois representations`, in the table indicating primes where the mod ell Galois representations, the data for 5B (at https://www.lmfdb.org/knowledge/show/gl2.subgroup_data?label=5B) indicates that -1 is not in this subgroup. But this is the whole Borel subgroup, which certainly contains -1.

**Comment by AndrewVSutherland** [comment]
Thanks! I will fix this.

**Comment by JohnCremona** [comment]
> Thanks! I will fix this.

Is the knowl for 5B incorrect, or is 5B the wrong label for the image for that curve?  If the latter, there may be more incorrect entries.

**Comment by davidlowryduda** [comment]
It's the knowl that's incorrect here. There are couple of other knowls where this happens too, like [5B.4.1](https://www.lmfdb.org/knowledge/show/gl2.subgroup_data?label=5B.4.1).

**Comment by AndrewVSutherland** [comment]
The fix is now live, see https://www.lmfdb.org/knowledge/show/gl2.subgroup_data?label=5B
