### ISSUE TITLE
insert newlines before equations and eqarrays

### ISSUE THREAD

**Issue by haraldschilly** [LMFDB/lmfdb#538]
in knowledge/main.py in about line 108 `render_me = render_me % {'content': md.convert(knowl_content)}` write a function befor this render step that inserts a new line right before `\begin{eqarray}` and similar environments -- unless there is already an empty line.

that causes markdown to close a `<p>`-tag environment.

**Comment by alinabucur** [comment]
Great, Harald, if you know how to solve it, please go ahead and do it.

**Comment by davidfarmer** [comment]
I will do it.

**Comment by davidfarmer** [comment]
This is handled by the md_preprocess(txt) function.
