### ISSUE TITLE
number field monogenic flag

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#5380]
Looking at NumberField/6.0.309123.1 I noticed that for "monogenic" it has "not computed", despiteue the index being displayed as 1.  Surely index 1 implies monogenic (but not conversely: if Z[a] has index >1 the ring of integers may still be monogenic, with a different generator).

It would be easy to (re)set the monogenic flag to True whenever the index is 1.

**Comment by jwj61** [comment]
In "monogenic world", the index is the gcd of all possible indices, so index 1 does not imply monogenic.

**Comment by JohnCremona** [comment]
> In "monogenic world", the index is the gcd of all possible indices, so index 1 does not imply monogenic.

Sorry for the misunderstanding, @jwj61
