### ISSUE TITLE
Fake small-but-not-zero central L-values from motives

### ISSUE THREAD

**Issue by a234** [LMFDB/lmfdb#5422]
The motivic L-function [A8_B4.1.1_t-1.1](https://beta.lmfdb.org/L/Motive/Hypergeometric/Q/A8_B4.1.1/t-1.1) has its L-value $L(1/2) \approx 4.743837834 \times 10^{-10}$ displayed on its page.

However, the motive is from (the Jacobian of) a genus-2 curve, i.e. [131072.c.262144.1](https://beta.lmfdb.org/Genus2Curve/Q/131072/c/262144/1) with Mordell-Weil rank 2, so $L(1/2)$ should be a zero with multiplicity 2, assuming BSD.

**Comment by edgarcosta** [comment]
we no longer display the L-function
