### ISSUE TITLE
Some BMF dimensions are wrong

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#5463]
Over imaginary quadratic fields with even class number, some of the dimensions of the spaces of BMFs are wrong due to a mistake I made, which only affects spaces where there are oldforms which are self-twist by an unramified quadratic character.

This was spotted by Kalani Thalagoda who has independently computed the dimensions for the field Q(sqrt(-17)) and levels of norm up to 200: there was just one discrepancy in this range.

I have corrected my code and reuploaded the dimensions for the affected fields.  You can compare https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.68.1/192.1 which shows the correct dimension of 92 with https://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.68.1/192.1 which shows the wrong dimension of 91.

The issue was only with the dimension of the full space -- the new dimensions are unchanged, and none of the data about individual newforms is affected.

This is purely a data issue.   Please could someone copt just one table bmf_dims from beta to prod.  After that the issue can be closed.

**Comment by edgarcosta** [comment]
done

**Comment by JohnCremona** [comment]
Thanks
