### ISSUE TITLE
Typo in "Sato-Tate group identity component" knowl

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5464]
From the feedback page:

I think there's a typo in the fifth bullet point of the "Sato-Tate group identity component" knowl; i.e. the description of when ST^0 is SU(2) x SU(2).  I think "a product of non-isogenous CM elliptic curves" should be replaced with "a product of non-isogenous *non-CM* elliptic curves".   e.g. for the Jacobian of the genus 2 curve C : y^2 = x^6 - 2x^2 - 1  (1600.a.409600.1), we have ST^0 = SU(2) x SU(2), where J(C) is isogenous to the product of the elliptic curves 20.a and 80.a. but neither elliptic curves have CM.

**Comment by AndrewVSutherland** [comment]
This is indeed a typo, now fixed (thank you to whoever noticed this!).
