### ISSUE TITLE
Number field jump returns a confusing error message

### ISSUE THREAD

**Issue by BarinderBanwait** [LMFDB/lmfdb#5469]
When searching for a number field via the jump box, the error message returned if the number field is not in the database is confusing. For example, asking for `x^50 + 311`, returns "Error: x^50+311 is not a valid input for Label. x^50+311 does not define a number field in the database." While this is technically correct, it would be clearer if the first part of this error message was removed

The done criterion for this issue is that the error simply reports: "Error: x^50+311 is not a valid input for Label. x^50+311 does not define a number field in the database."

This would be a good first issue for someone looking to get into the codebase.

**Comment by sarangop1728** [comment]
I will fix this!

**Comment by rbommel** [comment]
But the jump box also takes a label, right? So the error should say something along these lines...

**Comment by BarinderBanwait** [comment]
@rbommel  Well the text next to the jump box says 'Label, name, or polynomial' so it's clear that a Label can be inserted. The error saying "Error: x^50+311 does not define a number field in the database" is concise, and in line with what happens elsewhere, e.g. if you type `x^7 + 9` into the genus 2 curve jump, it tells you it doesn't define a genus 2 curve, it doesn't say "you can also put in a label here, you know"

**Comment by rbommel** [comment]
It would also say "Error: unable to find equation $y^{2} = x^{6} + 4000 x + 1$ (interpreted from x^6+4000*x+1) in the genus 2 curve database". So there is some feedback saying that it did realise what you were trying to do, but the object was not there.

**Comment by roed314** [comment]
Fixed by #5849
