### ISSUE TITLE
HMF range search

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#547]
On

http://beta.lmfdb.org/ModularForm/GL2/TotallyReal/

if I search for 1..10 on field discriminant, I get an error.
1-10 works.

**Comment by sanni85** [comment]
I am working on general error parsing with flask flash error messages, this should solve all the problems for these search boxes (try to input "hello" in any of the search boxes and you will see problems). I will show a demo tomorrow, before implementing the whole thing.

**Comment by jvoight** [comment]
@sanni85: Did you make any progress on this?

**Comment by sanni85** [comment]
I am going to fix the html and more after David Roe's pull request which was merged today.

**Comment by jwj61** [comment]
The Roe patch, already merged, fixed the issue.

**Comment by sanni85** [comment]
The html needs still fixing, type hello into the input for field and you will see a server error
http://beta.lmfdb.org/ModularForm/GL2/TotallyReal/?field_label=hello&deg=&disc=&weight=&level_norm=&dimension=&count=100

**Comment by sanni85** [comment]
Fixed in pull request #901
