### ISSUE TITLE
Verify conrey indexes in mf_subspaces (or decide that we don't need this)

### ISSUE THREAD

**Issue by BarinderBanwait** [LMFDB/lmfdb#5470]
In PR #5454, the code shown below was removed. This code checked that the conrey indexes in `mf_subspaces` agreed with the conrey indexes in `char_dir_orbits`. This was removed because we removed this latter table (and replaced it with the leaner `char_orbits`. This issue is to decide what to do about this: either figure out a way of verifying the conrey indexes in mf_subspaces (e.g. by computing these indexes on the fly in these functions), or deciding that we don't need this verification.

```
    @overall
    def check_conrey_indexes(self):
        """
        check that conrey_indexes matches galois_orbit for char_orbit_label in char_dir_orbits
        """
        # TIME about 10s
        return self.check_crosstable('char_dir_orbits', 'conrey_indexes', ['level', 'char_orbit_index'], 'galois_orbit', ['modulus', 'orbit_index'])

    @overall
    def check_sub_conrey_indexes(self):
        """
        check that sub_conrey_indexes matches galois_orbit for sub_char_orbit_label in char_dir_orbits
        """
        # TIME about 10s
        return self.check_crosstable('char_dir_orbits', 'sub_conrey_indexes', ['sub_level', 'sub_char_orbit_index'], 'galois_orbit', ['modulus', 'orbit_index'])
```

**Comment by AndrewVSutherland** [comment]
I think it is safe to remove this check.

**Comment by BarinderBanwait** [comment]
> I think it is safe to remove this check.

In that case we can close this issue.
