### ISSUE TITLE
Character orbit knowls on newforms are broken

### ISSUE THREAD

**Issue by davidlowryduda** [LMFDB/lmfdb#5491]
After clicking for a random classical newform, we might find ourselves at a page like https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/5908/2/a/c/

This has character orbit `5908.a`. Clicking on that knowl shows a knowl stating "Invalid label for Dirichlet character: 5908.a". This is true, I suppose, as this should be a Dirichlet orbit (and `5908.a` is a valid orbit label). I suspect that we call the wrong knowl builder.

I think I should be able to examine this tomorrow.

**Comment by AndrewVSutherland** [comment]
The right knowl builder was being called but the knowl builder hadn't been updated to reflect the recent changes to the Dirichlet character database.  This should be fixed by PR #5492
