### ISSUE TITLE
Right clicking on (some) formulas should open new page

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#550]
We modified MathJax so that in the main menu, right clicking opens a new browser window.
We had that feature on all of the LMFDB, but recently (pull request #412 ) we reverted to the default
case (right-clicking reveals the LaTeX source) outside the main menu.

I suggest that we switch back again because there are many cases where it is useful to
open a new page, and the link is math.  For example, browsing HMF over \Q(\sqrt{5}):

http://beta.lmfdb.org/ModularForm/GL2/TotallyReal/

Or finding out which character is \chi_{17}(2,\cdot):

http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/17/2/

Both of those happened to me today!

If there are pages that contain formulas that one is likely to want the LaTeX source, then
we can restore the default behavior on those pages.

**Comment by haraldschilly** [comment]
Has anyone every tried to play around with the `showContext` setting of mathjax in [`MathMenu`](http://mathjax.readthedocs.org/en/latest/options/MathMenu.html#configure-mathmenu)?

**Comment by jwj61** [comment]
I have not looked at showContext, that may work.

On linux and macs, one can always shift-click to open the link in a new window, and do a special click to open in a new tab (control-click on linux, command-click on mac).  I have not tried this on a variety of browsers, but it worked with firefox on linux and both chrome and safari on macs.  I don't have a windows machine to test there.  Does this cover the desired use cases?

The current behavior is controlled by css.  It for now uses the class sidebar, but that can easily be changed.  Then one could control for individual bits of mathjax whether right-click brings up the mathjax menu or the browser menu.

**Comment by davidfarmer** [comment]
I'd be interested to see what pages actually have formulas
which one may wish to see the TeX source.  I don't recall the
example which led us to change the behavior.

**Comment by davidfarmer** [comment]
Closing, because users can shift-click
