### ISSUE TITLE
Friendly square roots in HMF browse page

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#552]
It looks odd to me to see \Q(\sqrt{8}) and \Q(\sqrt{12}) near the top of
http://beta.lmfdb.org/ModularForm/GL2/TotallyReal/
especially since the page switches to the naive name by the time you get to a home
page of a HMF.

If the audience for browsing is nonexperts, then the naive names could be better.

**Comment by JohnCremona** [comment]
On 3 November 2015 at 20:21, davidfarmer <notifications@github.com> wrote:

> It looks odd to me to see \Q(\sqrt{8}) and \Q(\sqrt{12}) near the top of
> http://beta.lmfdb.org/ModularForm/GL2/TotallyReal/
> especially since the page switches to the naive name by the time you get
> to a home
>

By "naive name" do you mean the label, e.g. 2.2.8.1 from Q(sqrt(2))?

In the browse & search page I use the function pretty_label() -- if I
remember the name correctly -- which does nothing if there is not special
name, i.e. for all fields of degree >2 not cyclotomic.

I would prefer to systematically use the pretty label in the search results
page, just as in the page for an individual HMF (not only pretty, it is a
NF knowl).  Thta was just a small omission.

John

page of a HMF.

**Comment by davidfarmer** [comment]
By "naive" I mean  \Q(\sqrt{2}) instead of \Q(\sqrt{8}), and  \Q(i) instead of \Q(\sqrt{-4}).

**Comment by JohnCremona** [comment]
Sorry, I misunderstood.  And I see that the offending Q(sqrt8)) etc are
hard-coded into the file templates/hilbert_modular_form_all.html so the
simple solution is to change that.

A fancier solution is more like what you see at
http://www.lmfdb.org/EllipticCurve/ where the fields to be displayed are
set up in python complete with appropriate URLS and the html template loops
through that list.

**Comment by jvoight** [comment]
Pull request https://github.com/LMFDB/lmfdb/pull/553
