### ISSUE TITLE
David Platt's L-function zeros

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#557]
Get 'em in the LMFDB!

**Comment by edgarcosta** [comment]
@jvoight, Could you elaborate a bit more?
Are you asking that we have all zeros of the L-functions computationally rigorous with Dave's code, or are you referring to some data set that I'm not aware of?

**Comment by AndrewVSutherland** [comment]
Closing this (if someone wants to create a new issue with a more specific feature request, please do!).
