### ISSUE TITLE
L-function of Dirichlet character does not link to Dirichlet character page

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5570]

**Comment by edgarcosta** [comment]
The data is there...
https://beta.lmfdb.org/L/data/1-12-12.11-r0-0-0

this is very confusing

**Comment by edgarcosta** [comment]
To expand the issue, the L-function, e.g., https://beta.lmfdb.org/L/1/12/12.11/r0/0/0, does not point to its own source.
