### ISSUE TITLE
Missing results in number field search

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5585]
I do not understand why the field [4.4.2048.1](https://www.lmfdb.org/NumberField/4.4.2048.1) is not included in the search

https://www.lmfdb.org/NumberField/?hst=List&degree=4&ram_quantifier=exactly&ram_primes=2&search_type=List

If I add the signature [4,0] to the search, it suddenly is included:

https://www.lmfdb.org/NumberField/?hst=List&degree=4&signature=%5B4%2C0%5D&ram_quantifier=exactly&ram_primes=2&search_type=List

And it is also included if I add the Galois groups C4:

https://www.lmfdb.org/NumberField/?hst=List&degree=4&ram_quantifier=exactly&ram_primes=2&galois_group=C4&search_type=List

Something very strange seems to be happening here.  Any ideas @jwj61 ? If this is not a bug, possibly there is an issue with the postgres index.  Can you take a look at this @edgarcosta or @roed314 ?

**Comment by jwj61** [comment]
I just clicked on the link and it showed up.

**Comment by edgarcosta** [comment]
The sorting is confusing, but it is there...
![Screen Shot 2023-07-17 at 14 55 39](https://github.com/LMFDB/lmfdb/assets/322822/0f3b4514-67bb-40f5-b621-2567f150f5d4)

**Comment by AndrewVSutherland** [comment]
Now it is showing up for me too. I swear it wasn't there, but maybe it was, I should have posted a screen shot like Edgar.

Sorry for the false alarm!
