### ISSUE TITLE
Browsing GL(2, Q) Maass forms of weight zero is broken

### ISSUE THREAD

**Issue by jwbober** [LMFDB/lmfdb#561]
e.g. http://beta.lmfdb.org/ModularForm/GL2/Q/Maass/BrowseGraph/1/10/0/10/

The error looks something like

    Exception on /ModularForm/GL2/Q/Maass/BrowseGraph/1/10/0/10/ [GET]
    [...]
    File "/home/lmfdb/lmfdb-git-beta/lmfdb/modular_forms/maass_forms/maass_waveforms/views/mwf_plot.py", line 41, in paintSvgMaass
    if pymongo.version_tuple[0] < 3:
    NameError: global name 'pymongo' is not defined

I'm guessing that Harald broke this during the database upgrade, so I'm assigning this to him for now. It is probably an easy fix.

**Comment by haraldschilly** [comment]
that's an easy fix, although in general fixing this is a bit harder. they wrap the database backend in a generalized MaassDB class, which might have more than only one backend. Currently there is just mongodb, though. Also, that class should simply have a "connection" argument, where the connection can be passed in without having to specify host, port, db_type, etc.
