### ISSUE TITLE
Issue with 'Galois representations' section for some genus 2 curves

### ISSUE THREAD

**Issue by maylejacobj** [LMFDB/lmfdb#5612]
The [page](https://www.lmfdb.org/Genus2Curve/Q/587/a/587/1) associated with the genus 2 curve '587.a.587.1' displays incorrect information in the 'Galois representations' section.

The Jacobian of this curve has trivial geometric endomorphism ring, yet the page displays:

> For primes $\ell \ge 5$ the Galois representation data has not been computed for this curve since it is not generic.

The Jacobian of this curve has no nonsurjective primes. This bug seems to affect other curves with no nonsurjective primes (e.g., 743.a.743.1, 893.a.893.1, 1253.b.1253.1).

**Comment by BarinderBanwait** [comment]
This is my fault, I put that line in; it looks like the logic for what to do when the list of nonsurj primes is empty in the db needs to be fixed, which i'll get onto asap 🔨

**Comment by AndrewVSutherland** [comment]
This bug was fixed by https://github.com/LMFDB/lmfdb/pull/5608, which should be on beta and prod soon (I'll close this issue as soon as it is).

**Comment by AndrewVSutherland** [comment]
The fix is now live at https://www.lmfdb.org/Genus2Curve/Q/587/a/587/1
