### ISSUE TITLE
Label for ECNF isogeny class is incorrect (gives label of an ECNF) 

### ISSUE THREAD

**Issue by sibilant** [LMFDB/lmfdb#562]
The label of isogeny classes of ECNFs is incorrect, at least in certain places: instead of the label of the isogeny class, we get the label of the first elliptic curve in this isogeny class.

Example: http://beta.lmfdb.org/EllipticCurve/2.2.5.1/31.1/a/
First header on the page should say "Elliptic curves in class 31.1-a" rather than "Elliptic curves in class 31.1-a1". Same for the label in the properties box. 

Note that this apparently never happens for elliptic curves over Q (Example: http://www.lmfdb.org/EllipticCurve/Q/11/a/).

**Comment by JohnCremona** [comment]
You are right, my fault.  The naming of the data fields is different for
ec/Q.   Will be a trivial thing to fix.

**Comment by JohnCremona** [comment]
Working on this now.

**Comment by JohnCremona** [comment]
Fixed by pull request #582
