### ISSUE TITLE
Dirichlet character server error

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5626]
The page https://www.lmfdb.org/Character/Dirichlet/68800/66667 is throwing a server error

**Comment by roed314** [comment]
Hm, I thought that #5621 fixed these kind of issues, but I guess there's another problem.

**Comment by roed314** [comment]
The problem is that, in the `galois_orbit` method
```
if order == 1:
    return [1]
elif order < limit or order * order < limit * self.modulus:
    return self.galois_orbit_all(limit)
elif limit == 1 or self.modulus < 30 * order:
    return self.galois_orbit_search(limit)
else:
    logger.debug(f"galois orbit of size {order} too expansive, give up")
    return []
```
we fall into the last case and give up (`modulus=68800` and `order=1680`), but we need to have at least one thing in the orbit in order to be able to look up from the database.

**Comment by AndrewVSutherland** [comment]
The first cahracter in the orbit is 68800.83.  It takes less than 60 ms to compute this in Magma using https://github.com/AndrewVSutherland/Magma/blob/main/chars.m#L393.  Are we sure this is still slow in the python+gp implementation?  If so, I'm sure @pascalmolin could figure out a way to speed it up, I would expect gp to be faster at this than my (somewhat hacky) magma implementation.

**Comment by AndrewVSutherland** [comment]
We could alternatively modify `tiny_conrey` to use the magma code I linked to above, but like I said, I really would expect the built-in gp functions to be faster than the code I wrote on top of Magma.

**Comment by AndrewVSutherland** [comment]
Actually the function `MinimalConreyConjugate` in https://github.com/AndrewVSutherland/Magma/blob/main/chars.m#L320 does exactly what is needed here, and `MinimalConreyConjugate(68800,66667)` takes less than 10 milliseconds.  It is just 3 lines of code that I'm sure could be implemented in Sage or a call to gp (doing it in Sage might be faster due to the overhead of calling gp).

**Comment by roed314** [comment]
Yeah, this is basically what `galois_orbit_all(1)` does (defined [here](https://github.com/LMFDB/lmfdb/blob/master/lmfdb/characters/TinyConrey.py#L223)).  It takes 6ms in this case, so changing the cutoffs would certainly be helpful.  But we probably do want some cutoffs...
