### ISSUE TITLE
Knowl for 'bad primes' (for genus 2)

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#5628]
From Frank:

> I think there’s still a ambiguity — the knoll makes clear there is a subtlety, but it’s
> not 100% clear then whether “Bad primes” means bad for
> X = curve or
> X = Jacobian of curve
> I think if you would guess you would guess correctly, but being even more explicit,
> perhaps “Bad primes for the curve” or what have you would be clearer.
> 
> One reason you *might* doubt for a moment that it is X= curve is that curves are labelled by the conductor
> of the Jacobian, so the good or otherwise reduction of the jacobian is given primacy in some other aspect.

**Comment by jvoight** [comment]
We have a database of genus 2 curves, so we should assume that "bad primes" apply to the objects tabulated (especially given the explicit caveat); but since the Jacobian is never far from the discussion (as you say, it's in the label), folks will still wonder unless we're explicit about it.

"Bad primes for the curve" will ruin formatting, so we may have to go a click or two before this is fixed.

**Comment by edgarcosta** [comment]
what about adding the option "curve/jacobian"?

**Comment by jvoight** [comment]
Can we cram that in?  Maybe, for classical modular curves we say "Bad $p$".  That'd be a quick fix (trying to be responsive to the confusion).  

Medium term: once we get the larger dataset, we probably want two separate fields so the user could search for curves with bad reduction at a prime whose Jacobian has good reduction.  

Longer term: I think we should be able to search on essentially every attribute which is stored.  This is going to get out of hand (IMHO, it's starting to get there already), so I think we're gonna have to add some dropdown menus (keeping a few fixed standard search boxes, but not creating fixed boxes for every attribute).
