### ISSUE TITLE
p-adic field search bug

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5646]
From the issue tracker:

I encountered a server error when searching for local fields with Galois group and inertia subgroup isomorphic to Q8, the webpage asked that I report with the following message:  
To help us improve the website, please report this page's URL "https://www.lmfdb.org/padicField/?hst=List&n=8&p=2&gal=Q8&inertia_gap=Q8&search_type=List" as well as the URL of the page you are coming from "http://www.lmfdb.org/padicField/?hst=List&n=8&p=2&gal=Q8&search_type=List".

**Comment by jwj61** [comment]
Inertia_gap stores the group as a pair of integers, but current code expects an abstract group id.  Down the road, we should probably change the database to use abstract group ids, but I will put in a fix for now.

**Comment by roed314** [comment]
This was fixed.
