### ISSUE TITLE
Missing Maass form

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5659]
From the feedback page:

In 2022, Seymour-Howell, A. published a paper "Rigorous computation of Maass cusp forms of squarefree level" on Res. Number Theory and provided a dataset of Laplace eigenvalues and Maass Fourier coefficients. When searching among this dataset (result in URL attached above), for level 2 Maass forms (https://www.lmfdb.org/ModularForm/GL2/Q/Maass/?level=2), I find an eigenvalue 10.9203920029(error: 1e-10) which is in the dataset but not in LMFDB. This corresponding to a even Maass form on level 2 with Fricke sign 1. 

https://github.com/qihangsun98/searching-Maass-eigenvalues

**Comment by AndrewVSutherland** [comment]
Also see #4048, which is related.  We are planning to repopulate the entire database of weight 0 Maass forms for GL2 based on rigorous computations by Seymour-Howell and David Lowry-Duda in the not-too-distant future.  The current data set is not expected to be complete within the range it covers, as noted on https://www.lmfdb.org/ModularForm/GL2/Q/Maass/Completeness.

**Comment by AndrewVSutherland** [comment]
@davidlowryduda What's up with the Maass form of level 2 and eigenvalue 10.9203920029?  And more generally, have we compared against the data in https://zenodo.org/records/7105773 to make sure everything that falls within the scope of https://beta.lmfdb.org/ModularForm/GL2/Q/Maass/Completeness is actually present?

**Comment by davidlowryduda** [comment]
@AndrewVSutherland This form had been missing in the previous database. Now the page for this form is at https://beta.lmfdb.org/ModularForm/GL2/Q/Maass/2.0.1.6.1.

All of the forms from the Seymour-Howell dataset are included. That dataset is associated to the paper *Rigorous computation of Maass cusp forms of squarefree level*, which we cite at https://beta.lmfdb.org/ModularForm/GL2/Q/Maass/Source.

This issue can be closed.
