### ISSUE TITLE
L function page for Hilbert modular forms

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#569]
In the L function page for an Hilbert modular form, there is no reference about the totally real number field which is the base field for the form except in the url of the page. For example:

http://beta.lmfdb.org/L/ModularForm/GL2/TotallyReal/2.2.5.1/holomorphic/2.2.5.1-31.1-a/0/0/

The L function is only accessible by looking at the Hilbert modular form, but maybe it will not be in the future.

**Comment by jvoight** [comment]
Are you proposing that we include the base field as a friend?  Or something in the main body?  In the other pages I looked at, we specifically don't provide further data describing where the L-function comes from, but rather, leave that back on the originating page.  Or are you proposing we just put it in the title (which is already too long and probably needs to be shortened)?  

I agree it's a bit weird that we say the level norm and not the base field, so we should do something.

**Comment by davidfarmer** [comment]
The title will be changed as part of an overhaul of L-function titles.

**Comment by jvoight** [comment]
I vote for a title "L(s,f), where f is a holomorphic Hilbert cusp form over Qsqrt5 with parallel weight 2, level norm 31, and trivial character".

**Comment by davidfarmer** [comment]
This will be changed in the next pull request.  Can't wait for the general overhaul because the HMF
L-functions will probably not be served from the database.

**Comment by jvoight** [comment]
Not sure if this can be closed yet.  @sanni85, is the title enough, or do you want the totally real field to be a friend?

**Comment by sanni85** [comment]
I like it, but maybe it can be shorten to 
 "L(s,f), where f is a holomorphic Hilbert cusp form over Qsqrt5"

or to
 "L(s,f), where f is the holomorphic Hilbert cusp form 2.2.5.1-31.1-a"

I can see a use of labels here.

**Comment by JohnCremona** [comment]
I prefer the second suggestion, using the full HMF label.  And at the same time the entry in the Friends (Related Objects) list could say "Hilbert Cusp Form 2.2.5.1-31.1-a" and not just "Hilbert modular form".

**Comment by sanni85** [comment]
and maybe also add the number field (base) and the Hecke eigenvalue field (if it is in the number field database) as related objects

**Comment by davidfarmer** [comment]
I should have closed this issue when pull request #1066 was accepted.  That change added the number
field to the title, so I don't think we should now take it away. Some titles are unavoidably long.

I am opening a separate issue about the friends links.
