### ISSUE TITLE
2-adic RZB labels missing from modular curves data

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5700]
Modular curves of 2-power level that appear in https://users.wfu.edu/rouseja/2adic/ need to be added to `gps_gl2zhat_fine` (there is a column for them but it is not filled in.  Once the data is present it should be shown on the curve home pages with links to the Rouse website (this is already setup in the html template, the data just needs to be added).

**Comment by AndrewVSutherland** [comment]
This is now fixed in the data but there is still a problem in the search results that requires a code change which is in #5702

**Comment by roed314** [comment]
What is the remaining issue here?  Is the problem that the jump box doesn't work in https://beta.lmfdb.org/ModularCurve/Q/?jump=X8c ?  Or something else?

**Comment by roed314** [comment]
The regular expression is wrong:
```
RZB_LABEL_RE = re.compile(r"X\d+")
```
Do you know the correct one?

**Comment by AndrewVSutherland** [comment]
I think `X\d+[a-z]*` should do it
