### ISSUE TITLE
Relabel some BMFs and ECNFs/IQFs over fields with even class number

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#5706]
We have BMF and ECNF data for all Imaginary Quadratic Fields (IQFs) of absolute discriminant  up to 100 (also 163), of which 16 fields have even class number.  The data for these 16 fields is incorrectly labelled: only the isogeny class letter code and corresponding newform letter codes are affected.

The origin for this is an oversight on my part.  Over these even class number fields,  the BMFs come in sets of mutual unramified quadratic twists (the number is usually 2**r where r is the 2-rank of the class group, but it can be half that for self-twist newforms).  The code which computes and labels the BMFs computes one of each of these sets of twists and then fills in the twists.  I was sorting the newforms before the last step rather than after.  On the curve side, each curve's label matches that of the corresponding newform so these were also wrongly ordered and hence wrongly labelled (according to our published labelling convention).

I have finished fixing the data and am in the process of uploading the corrected data to beta.  When I have finished that and am happy that the data looks OK, I will put in a request here for the databases ec_nfcurves and bmf_forms to be copied to prod.  (bmf_dims is not affected.)

Incidentally, I am close to being able to extend this data over IQFs to include all fields of absolute discriminant up to 500 (but level/conductor norms only to 100 not 1000), at least.

**Comment by JohnCremona** [comment]
One example:  compare https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.15.1/15.1/a/ and https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.15.1/15.1/b/  to see that they are ordered correctly (from the list of aP), while https://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.15.1/15.1/a/ and https://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.15.1/15.1/b/ are the wrong way round.

(2.0.15.1 is the only field I have uploaded the corrected data for so far.)

**Comment by JohnCremona** [comment]
Upload done.  I think all is well.

NB for the field 2.0.95.1, level/conductor 624.5, there are 4 BMFs and 4 isogeny classes of curves; 2 of these were previously missing so for that field there are 2 more curves than before, otherwise it's only the letter-code part of the labels which have changed.  (The current Magma was able to find the curves which an earlier version did not.)

**Comment by AndrewVSutherland** [comment]
Are there tables that should now be copied to prod? If you give me a list of them I can take care of this.

**Comment by JohnCremona** [comment]
> Are there tables that should now be copied to prod? If you give me a list of them I can take care of this.

Yes, as listed above (amongst the verbiage): ec_nfcurves and bmf_forms.  Thanks!

**Comment by AndrewVSutherland** [comment]
Done!  Please let me know if everything looks okay.

**Comment by JohnCremona** [comment]
> Done! Please let me know if everything looks okay.

Thanks -- looking mostly good but somehow one curve (class 2.0.68.1-714.2-a) has gone missing, so I'll upload that one...

**Comment by JohnCremona** [comment]
OK, done (check https://beta.lmfdb.org/EllipticCurve/2.0.68.1/714.2/a/).  I don't know how that happened but I did check there was nothing else like that for all ECNF/IQFs.

**Comment by AndrewVSutherland** [comment]
I will recopy ec_nfcurves to prod, I assume bmf_forms has not changed?

**Comment by JohnCremona** [comment]
> I will recopy ec_nfcurves to prod, I assume bmf_forms has not changed?

Corrtec.  Thanks again

**Comment by AndrewVSutherland** [comment]
Done.
