### ISSUE TITLE
Symmetric Cube L-functions

### ISSUE THREAD

**Issue by brianconrey** [LMFDB/lmfdb#571]
In their article "Symmetric Powers of Elliptic Curve L-Functions" Watkins and Martin refer to certain elliptic curves whose symmetric cube L-functions have 4th order zeros at the central point. These include 2379b previously found by Buhler, Schoen, and Top. But the lmfdb Z-plot does not show the central vanishing. I suspect the lmfdb plot is incorrect.

**Comment by davidfarmer** [comment]
We should hide the link when we know we can't compute the L-function.

**Comment by jvoight** [comment]
This ticket is too specific; need to do this for all L-functions.  See ticket #578.  JV

**Comment by davidfarmer** [comment]
Closed because handled in issue #578
