### ISSUE TITLE
Offset bound for downloading data

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5734]
From the feedback page:

When I attempt to change the offset in the url above from '10000' to '10100', I receive an error. I would like to access the entire database of elliptic curves, if possible. Many thanks.

https://www.lmfdb.org/api/ec_curvedata/?_format=json&_offset=10000

**Comment by roed314** [comment]
I think the right solution is to document the use of the LMFDB from Python better, and then add some pointers to the API error (in some cases the download page will also work).

**Comment by macadon** [comment]
FYI, here is the code I used that caused the error in Python:

`frame=pd.DataFrame()
for i in range(0,100):
    offset=i*100
    url=f"https://www.lmfdb.org/api/ec_curvedata/?_format=json&_offset={offset}"
    response=requests.get(url)
    if response.status_code == 200:
        # print("Succesful connection with API.")
        # print('-------------------------------')
        data = response.json()
        # print(data)
    elif response.status_code == 404:
        print("Unable to reach URL.")
    else:
        print("Unable to connect API or retrieve data.")
    df = pd.DataFrame(data)
    colls=[frame,df]
    frame=pd.concat(colls)
    
frame.reset_index(inplace=True)
result=pd.concat([frame.drop(['data'], axis=1), frame['data'].apply(pd.Series)], axis=1)`

**Comment by macadon** [comment]
FYI--Python code I used which caused the offset error is:

`frame=pd.DataFrame()
for i in range(0,100):
    offset=i*100
    url=f"https://www.lmfdb.org/api/ec_curvedata/?_format=json&_offset={offset}"
    response=requests.get(url)
    if response.status_code == 200:
        # print("Succesful connection with API.")
        # print('-------------------------------')
        data = response.json()
        # print(data)
    elif response.status_code == 404:
        print("Unable to reach URL.")
    else:
        print("Unable to connect API or retrieve data.")
    df = pd.DataFrame(data)
    colls=[frame,df]
    frame=pd.concat(colls)
    
frame.reset_index(inplace=True)
result=pd.concat([frame.drop(['data'], axis=1), frame['data'].apply(pd.Series)], axis=1)`

**Comment by roed314** [comment]
I've created #6242 as a followup for improving the documentation of the API, so I'm closing this issue.
