### ISSUE TITLE
Better documentation for downloading large amounts of data

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5736]
There are currently several ways to access large amounts of data from the LMFDB.  In order of preference, they are
* Use the new download options from search result pages
* Use the Python API (`from lmfdb import db`)
* Use our online API pages.

The Python API needs a tutorial and some more documentation; the online API pages need some additional text giving rate limits and suggesting that we prefer the other two options.

**Comment by edgarcosta** [comment]
ps: I don't see an easy way to rate limit the online API pages

**Comment by roed314** [comment]
This was fixed by #6247.
