### ISSUE TITLE
write blurbs for the objects and arrows in new picture

### ISSUE THREAD

**Issue by alinabucur** [LMFDB/lmfdb#575]
The new picture is 
<img width="1031" alt="lmfdbuniverse" src="https://cloud.githubusercontent.com/assets/5437759/11040456/5d845d6e-86da-11e5-9141-dae268b26115.png">

**Comment by JohnCremona** [comment]
See my comments at #535

**Comment by alinabucur** [comment]
I created a pull request that partially solves this problem. But it is not fully functional yet.

**Comment by jvoight** [comment]
@AndrewVSutherland pointed out that we are missing the relevant knowls, e.g. "automorphic form" and "motive".  (He also 'needs' them for his Sato-Tate groups.)  This should be a copy and paste from blurb to knowl, plus delta.
