### ISSUE TITLE
L-functions data

### ISSUE THREAD

**Issue by alinabucur** [LMFDB/lmfdb#576]
Data to be stored for all L-functions in LMFDB (wish list; for v1.0 this regards L-functions for EC/Q, genus 2 curves, Dirichlet characters):

0. Label which will never change
1. conductor
2. degree
3. primitive: true/false
(3.5 List of factors when non-primitive)
4. self-dual: true/false
5. sign of functional equations
6. Selberg data (Gamma factors)
7. central value
8. value at edge of the critical strip
9. imaginary parts of 60 zeros -- same as what you need for #10
10. Z-function graph: enough points and precision to generate a credible graph
11. motivic weight
12. all bad Euler factors
13. L-factors for all primes p < 100 (or up to 101 if you prefer)
14. The first 100 (or 101) Dirichlet coefficients
15. Sato-Tate group
16. central character
17. Satake parameters (as decimals)
18. field of coefficients
19. analytic rank (number of zeros at the critical point)
20. nth derivative at central point when rank is n > 0
21. Descriptive name (for temporary use: eventually we will have a separate table that
contains descriptive names and links to the label of the L-function.)
22. symmetry type (of parameters): orthogonal, symplectic, unitary

(Need to give a label for each of these; some of these might be optional.)

**Comment by alinabucur** [comment]
The list is up for discussion/additions

**Comment by haraldschilly** [comment]
small comment: next to each of them one should also indicate the datatypes. true/false is boolean, the others possibilities are integer, float, string, lists of these three and so on …

**Comment by jvoight** [comment]
We want these for
  - Riemann zeta 
  - Dirichlet characters
  - classical modular forms
  - Maass forms 
  - elliptic curves over QQ
  - Artin L-functions
  - HMFs (especially elliptic curves over quadratic fields, where we can generate a_pp)
  - genus 2 curves (not everything is done yet?)

For example, we just have to take the existing code that produces the things appearing on the L-function page and compute it, storing it, and serving it from the database instead.

Maybe we can distinguish between "reliable" data and "rigorous" data displayed.

**Comment by davidfarmer** [comment]
Closing, because this material is now in the database documentation.
