### ISSUE TITLE
Bug in number field magma download

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5760]
If you go to https://www.lmfdb.org/NumberField/?degree=2&signature=%5B0%2C1%5D&class_number=1 and click the download to Magma button, the resulting file will not compile correctly in Magma because the `create_record` function attempts to set `poly` and `field` attributes that are derived from the downloaded data but not declared as attributes of the record that is being created:
```
function create_record(row)
    out := rec<RecFormat|label:=row[1],coeffs:=row[2],disc:=row[3],galois_label:=row[4],class_group:=row[5]>;
    poly := ZZx!(out`coeffs)
    out`poly := poly;
    field<a> := NumberField(poly);
    out`field := field;
    return out;
end function;
```

**Comment by roed314** [comment]
I think they were declared, but there's a missing semicolon.  See #5761.

**Comment by BarinderBanwait** [comment]
I've tested that #5761 fixed this issue - this issue can be closed.
