### ISSUE TITLE
Links to other databases

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5770]
So far, the LMFDB has tended not to link to external databases that have overlaps with the objects that we enumerate.  Some of this comes from the fact that many of our databases are fairly advanced, and don't have additional content on other sites.  For finite groups (and for number fields), there are other resources that it might make sense to link to (the Klüners Malle number field database, Groupnames, group visualization databases....).  We should discuss what our policy on such links is.

**Comment by jvoight** [comment]
- We're positive on adding links to the top of other relevant databases in like the "Source and acknowledgements" knowl (maybe changing to "Source, acknowledgements, links")
- On object homepages, we should consider adding an icon to indicate an external link (to be added to style guide, like in Source knowl) when we do, and we are generally positive on having our pages link to other pages (like http://galoisdb.math.uni-paderborn.de/groups/view?deg=9&num=17 links to us and to the small groups database).

**Comment by jvoight** [comment]
With seeming no further discussion, let's consider this a preliminary policy and revisit when needed.
