### ISSUE TITLE
L-functions should not display wrong data (when large conductor)

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#578]
For example, 
  http://beta.lmfdb.org/L/SymmetricPower/3/EllipticCurve/Q/2379.b/
and the symmetric cube, of conductor 13464285939 looks like the Z-function is wrong.

**Comment by JohnCremona** [comment]
I just tried the above link at it timed out.

How hard would it be to work out the maximum conductor which it is reasonable to display?  At the moment elliptic curve home pages only offer as Related Objects the square and 4th powrs, but when you go to the symmetric square L-function page it now offers you the symmetric cube (though not the 4th power).  So we also need some consistency here.

**Comment by jvoight** [comment]
See also #1069 for the same problem, but with HMF L-functions.
