### ISSUE TITLE
Change master branch to main

### ISSUE THREAD

**Issue by jenpaulhus** [LMFDB/lmfdb#5804]
Here are some instructions for how to change the master branch to main:

https://gist.github.com/danieldogeanu/739f88ea5312aaa23180e162e3ae89ab

**Comment by AndrewVSutherland** [comment]
This has been done.   PRs should now be submitted to main.  To switch from master to main on a local clone, do
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by roed314** [comment]
@AndrewVSutherland can this issue be closed?
