### ISSUE TITLE
Be able to limit number of objects downloaded

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5812]
A suggestion relayed to me verbally:

On a search results page, one can download the results.  Add the option to specify how many objects to download.  For example, someone searches for all D_4 quartic number fields but really just wants the first 1000 of them.  They want to specify this directly instead to tinkering with discriminant bounds or getting a huge download and having to then pare it down.

**Comment by roed314** [comment]
@jwj61: This was implemented in #5820.  If you're happy with the interface that's live, feel free to close this issue.
