### ISSUE TITLE
Corrupted Maass form coefficient?

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5814]
Coefficient $a_{3213}$ of https://www.lmfdb.org/ModularForm/GL2/Q/Maass/4cb8503a58bca91458000044?edit_rows=500&edit_cols=10 is suspciously 0 (not approximately 0, exactly 0).

To see the underlying data, go to https://www.lmfdb.org/api/maass_newforms/ search for "0.5440403374099241",  and look at the next coefficient (which is not a real literal like all the other coefficients, it is simply "0").

**Comment by edgarcosta** [comment]
Shouldn't it be −0.0000005770353225877174674 ~
0.083864475×−0.000414264×0.016609141?

**Comment by AndrewVSutherland** [comment]
How are you computing this?

**Comment by edgarcosta** [comment]
I multiplied a_7*a_17*a_29

![Screenshot_20240113-170459.png](https://github.com/LMFDB/lmfdb/assets/322822/c34591e3-4b2a-4294-8a7a-6bfd873221a0)

**Comment by AndrewVSutherland** [comment]
Hmm, maybe this just got (incorrectly) rounded to zero.

But maybe it would be useful to do a multiplicative sanity check on all the Maass form coefficient data?

Do you have any thoughts on this @davidfarmer or @davidlowryduda ?

**Comment by davidfarmer** [comment]
I like the idea of setting to exactly 0 those coefficients which really are zero,
but which the computation merely gives as very small.  This example shows that
one should only do that for prime coefficients.  Composite coefficients have a
distribution which is much more concentrated near 0, and so false positives
(in the test to set to 0) are much more likely if the same threshold is used.

I assume that checking multiplicativity will not reveal anything, because that is
how the composite coefficients were created.

**Comment by a234** [comment]
> I like the idea of setting to exactly 0 those coefficients which really are zero, but which the computation merely gives as very small. This example shows that one should only do that for prime coefficients. Composite coefficients have a distribution which is much more concentrated near 0, and so false positives (in the test to set to 0) are much more likely if the same threshold is used.
> 
> I assume that checking multiplicativity will not reveal anything, because that is how the composite coefficients were created.

I would propose the idea that only coefficients that are guaranteed to be zero should be set to zero, like the even coefficients in [a level-4 Maass form](https://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f5558aa88aece2646000008).

**Comment by a234** [comment]
Speaking of Maass form coefficient corruptions, I have found several level-3 Maass forms whose coefficient a₉ is somewhat far from 1/3:
[This](https://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f77894788aece4a3f000007) has a₉=0.333332055, 
[This](https://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f77895688aece4a3f000008) has a₉=0.333331754, and
[This](https://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f77895e88aece4a3f000009) has a₉=0.333333517.
The problem applies to other forms and levels as well.

What's more, the two Maass forms on level 27, [this](https://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f68c41288aece5ab5000010) and [this](https://www.lmfdb.org/ModularForm/GL2/Q/Maass/4f6940c088aece5ab5000013), should have the same spectral parameters and same absolute values of coefficients, but the recorded values differ much.

**Comment by edgarcosta** [comment]
> I assume that checking multiplicativity will not reveal anything, because that is
> how the composite coefficients were created.

Looking at the raw data, and the comment above, I would guess that the data was computed with much less precision, and then stored with superfluous digits.

**Comment by davidlowryduda** [comment]
> Looking at the raw data, and the comment above, I would guess that the data was computed with much less precision, and then stored with superfluous digits.

I think that's probably right. Later this week I'll check all the other current coefficients for multiplicativity and see what I find.

**Comment by AndrewVSutherland** [comment]
@davidlowryduda What is the status of this issue?

**Comment by davidlowryduda** [comment]
@AndrewVSutherland With the new Maass forms on beta, this issue is now out of date. It should be closed.
