### ISSUE TITLE
Downloading from search to gp does not work

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5815]
I found this when trying to use a downloaded file from local fields.  But, I doubt the corresponding gp file works in any section.  I looked at fixing it, but the code is somewhat complicated.

Here is a download file (with some comments removed):

```
columns = ["label", "coeffs", "p", "e", "f", "c", "gal", "slopes"]
data = {[
["7.9.0.1", [4, 6, 0, 1, 6, 0, 0, 0, 0, 1], 7, 1, 9, 0, [9, 1], [[], 1, 9]],
["7.9.6.1", [11915, -756, -2358, 2631, 1944, 396, 249, 108, 18, 1], 7, 3, 3, 6, 
[9, 2], [[], 3, 3]],
["7.9.6.2", [5488, 0, 0, -2352, 0, 0, 252, 0, 0, 1], 7, 3, 3, 6, [9, 1], [[], 3,
 3]],
["7.9.6.3", [-1372, 0, 0, 0, 0, 0, -42, 0, 0, 1], 7, 3, 3, 6, [9, 1], [[], 3, 3]
],
["7.9.8.1", [14, 0, 0, 0, 0, 0, 0, 0, 0, 1], 7, 9, 1, 8, [9, 6], [[], 9, 3]],
["7.9.8.2", [7, 0, 0, 0, 0, 0, 0, 0, 0, 1], 7, 9, 1, 8, [9, 6], [[], 9, 3]],
["7.9.8.3", [21, 0, 0, 0, 0, 0, 0, 0, 0, 1], 7, 9, 1, 8, [9, 6], [[], 9, 3]]
]}

create_record(row) = 
{
    out = Map(label,row[1],coeffs,row[2],p,row[3],e,row[4],f,row[5],c,row[6],gal,row[7],slopes,row[8])
    field = Polrev(mapget(out, "coeffs"))
    mapput(~out, "field", field)
    out
}

make_data() = 
{
    return [create_record(row) | row<-data];
}
```
Here are how it should change:

- the lines in create_record need semicolons at the end, except for the last line "out".  For the last line, it is a little nicer if instead it read "return(out);".
- the first line of create_record, the column names need to be in double quotes, as in Map("label", row[1] ...
- in the same line, the input to Map is a gp-matrix, so every other comma should be a semicolon and the whole input needs to be in square brackets: Map(]"label", row[1]; "coeffs", row[2]; ...]);
- in make_data, there needs to be parentheses around the input to return
- in that same line, it could be simplified: return(apply(create_record, data));

**Comment by roed314** [comment]
Thanks; I can take a look.

**Comment by jwj61** [comment]
I don't know where the question about having a semicolon on a line with return went, but I would say that it is preferred.  The function will behave the same, but without the semicolon the function is echoed to the user when they read in the file (as one long line).

**Comment by roed314** [comment]
Ok, great.  I'll have a PR ready shortly.
