### ISSUE TITLE
Bug on Maass form pages

### ISSUE THREAD

**Issue by a234** [LMFDB/lmfdb#5819]
Take a Maass form page, for example https://www.lmfdb.org/ModularForm/GL2/Q/Maass/53223506acf75610e77d909e.

By clicking the link **Level 199** on the series of links, ⌂→Modular forms→Maass→**Level 199**→Weight 0→Character 199.1, the page leads to https://www.lmfdb.org/ModularForm/GL2/Q/Maass/199/.

The page https://www.lmfdb.org/ModularForm/GL2/Q/Maass/199/ is, for all purposes, same to https://www.lmfdb.org/ModularForm/GL2/Q/Maass/?level=199, but typing in a new level in the Level box in the former link leads to https://www.lmfdb.org/ModularForm/GL2/Q/Maass/199/?level=12, which displays level-199 Maass forms instead of level-12 Maass forms.

**Comment by AndrewVSutherland** [comment]
While level 199 is no longer present, an analogous series of actions (starting from https://beta.lmfdb.org/ModularForm/GL2/Q/Maass/87.0.1.143.1, say) does not cause a problem.
