### ISSUE TITLE
Enable Private Vulnerability Reporting in GitHub

### ISSUE THREAD

**Issue by ZuhairORZaki** [LMFDB/lmfdb#5826]
In your repository, we have found a bug that may require your attention. We do not want to disclose the details. Therefore, we request you to enable private vulnerability reporting in your repository.

### Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed - to improve global software supply chain security.

The bug is found by running the iCR tool by [OpenRefactory, Inc.](https://openrefactory.com/) and then manually triaging the results.

**Comment by roed314** [comment]
Feel free to email details to the LMFDB managing editors, or use the feedback form [here](https://docs.google.com/spreadsheet/viewform?formkey=dDJXYXBleU1BMTFERFFIdjVXVmJqdlE6MQ).

**Comment by roed314** [comment]
@AndrewVSutherland: the documentation for private vulnerability reporting is [here](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability).

**Comment by AndrewVSutherland** [comment]
Done.
