### ISSUE TITLE
av_fq_isog data -> prod

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5841]
Kiran, Steve Huang and Jun Bo Lau have computed curve data for q=2, g=6.  It would be good to get this on www.lmfdb.org.

**Comment by edgarcosta** [comment]
in progress

**Comment by edgarcosta** [comment]
done

**Comment by edgarcosta** [comment]
@roed314 please check if everything looks good

**Comment by roed314** [comment]
Looks good.  Thanks!
