### ISSUE TITLE
Upload number field database to prod

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5845]
The main addition is the 17T7 field from Noam Elkies.  There are also minimal siblings added for a number of fields (plus a few fields added because they are minimal siblings of other fields).  The table is nf_fields (and its stats table).

**Comment by edgarcosta** [comment]
In progress

**Comment by edgarcosta** [comment]
done https://www.lmfdb.org/NumberField/17.5.3534782343021921410482176000000000000.1
