### ISSUE TITLE
Analytic order of Sha is sometimes "exact" when it shouldn't be

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#5872]
For elliptic curves over Q with analytic rank 0, it is in principle possible to compute the analytic order of Sha exactly using modular symbols. However, some discussion with @JohnCremona indicates that this has not *actually* been done in all of the cases where LMFDB reports the value as exact.

**Comment by BarinderBanwait** [comment]
What's stopping one from going ahead and actually carrying out this modular symbols computation on all rank 0 ecqs?

**Comment by kedlaya** [comment]
Nothing as far as I know!

John did mention that Sage can also certify these orders analytically.

**Comment by JohnCremona** [comment]
To clarify: for conductors up to 500k  and rank 0 I did compute the values exactly using modular symbols but the values uploaded were recomputed. I just need to check that all agree, which of course they will unless there was a mess up.

Secondly,  for ranks 0 and 1 Sage can compute certifiably exact values (no modular symbols) and it wouldbe possible, and I do now intend to, run that computation.

**Comment by JohnCremona** [comment]
I can now certify that for all the curves of conductor up to 500k and rank 0, the analytic order of sha in the database is the exact same as the value computed using modular symbols.  I had the ratio L(E,1)/period stored as an exact rational (for the optimal curves) so the only work to be done was to ensure that I had the isogeny classes and newforms ordered consistently -- as a result of which I can say in exact gory detail what the Cremona" ordering of the isogeny classes actually is (not pretty but it should perhaps be stored for posterity).  A little extra work was needed to get the exact L/P value for the other curves in the isogeny class: the L-values are of course the same, and to get the exact ratio of the real periods one is helped by a result of Stevens which says that the real periods are all integer multiples of the smallest one.

I have not yet updated the relaibility knowl in any way.  My plan next is to see if it is practical to run Sage's certified analytic sha value on all curves of conductor 1 (as well as 0, as an extra check), both for these conductors, and also if possible the two collections of curves of larger conductor which we have.

**Comment by JohnCremona** [comment]
Holding off any computation for rank 1 curves while I get a reply from @wstein about the documentation for E.sha().an() which is inconsistent, saying both 

>         Returns the Birch and Swinnerton-Dyer conjectural order of `Sha`
>       as a provably correct integer, unless the analytic rank is > 1,
>        in which case this function returns a numerical value.

and

>         This result is proved correct if the order of vanishing is 0
>        and the Manin constant is <= 2.

**Comment by JohnCremona** [comment]
I have edited https://beta.lmfdb.org/knowledge/show/rcs.rigor.ec.q and https://beta.lmfdb.org/knowledge/show/ec.q.analytic_sha_order to reflect the current status if the analytic Sha values.  The latter knowl is what is displayed when you click on the word "exact" (e.g. https://beta.lmfdb.org/EllipticCurve/Q/37/a/1) or "rounded" (e.g. https://beta.lmfdb.org/EllipticCurve/Q/389/a/1).

Ideally the database itself would store a flag to indicate whether the exact/rounded word is shown (they lead to the same knowl).  Right now the choice of which word to display is determined in the template (lmfdb/elliptic_curves/templates/ec-curve.html) by a conditional which results in "exact" begin displayed if and only if the rank is 0 or 1.

Pending more computations, I will make a PR to change that condition to be if and only if r=0 nd N<500000.

Meanwhile, perhaps someone could review those two knowls so that the revised text gets to production.

**Comment by edgarcosta** [comment]
Didn't we want to replace https://beta.lmfdb.org/knowledge/show/ec.q.analytic_sha_order with https://beta.lmfdb.org/knowledge/show/ec.analytic_sha_order as pointed by your comment in 2020?

**Comment by JohnCremona** [comment]
I have been looking more closely at the Sage code and see that despite the claim at the beginning of the docstring, there is *no* certification for Sha values for curves of positive rank (even though it remains to be possible "in principle" to do this, it has not been implemented as far as I can see).  So my remaining job for now will be to certify the Sha values for rank 0 curves for conductor >500000 having already done so for conductors below that.

I will report here when taht has been done.

**Comment by JohnCremona** [comment]
I can now certify that for all the elliptic curves over Q of rank 0 in the database, the value of (analytic) Sha is proved to be correct.  Writing #Sha = (L/P)*Tam/Tor^2 this relies on having anexact rational value of L/P. For conductors < 500k this exact rational comes from modular symbols (formula (2.8.1 on p. 31 of my book). For arbitrary conductors, the Sage code behind E.sha().an() computes the ratio L/P exactly by computing it to suffient precision and using unconditional lower bound on the denominator (citing William Stein's thesis).

**Comment by JohnCremona** [comment]
This can be closed when #5895 is merged and deployed to production.

**Comment by edgarcosta** [comment]
can I delete https://beta.lmfdb.org/knowledge/show/dq.ec.reliability ?

**Comment by JohnCremona** [comment]
> can I delete https://beta.lmfdb.org/knowledge/show/dq.ec.reliability ?

Sorry I didn't reply before.  I just deleted it (for the record, essentially the same content is at https://beta.lmfdb.org/knowledge/show/rcs.rigor.ec.q).
