### ISSUE TITLE
ABC quality and Spiro ratio for elliptic curves

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5883]
Given a j∈Q one can do the following. Let c=Numerator(j/1728), a=Denominator(j/1728) and b=c-a. Then the quality of the abc triple is defined as q(a,b,c) := log(max(|a|,|b|,|c|))/log(rad(abc)), where rad(abc) is the product of the distinct prime divisors of a,b, and c.

The Spiro ratio is log(Delta_min(E))/log(N(E)).

See [this post](https://mathoverflow.net/questions/416556/szpiro-ratios-of-elliptic-curves-over-mathbbq) for some context (there are plenty of other descriptions of the conjectures about these quantities out there).

We should add both of these quantities for elliptic curves over Q (and maybe for elliptic curves over number fields).

**Comment by roed314** [comment]
This has been done for elliptic curves over Q.

**Comment by AndrewVSutherland** [comment]
Is this something we want to do for ECNF?  The case for that isn't clear to me and unless someone is motivated to do it I would vote to close this.

**Comment by koffie** [comment]
I vote to close as well. If we do find out that the ECNF version is useful, we can just create a new issue. I think it is good to not have to many open issues, and only have open issues for things people actually will be working on.

**Comment by roed314** [comment]
Works for me.
