### ISSUE TITLE
Upload several tables to prod

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5887]
There is a new column in `nf_fields`, `grd`, so it needs to get pushed to production.  Similarly, `belyi_passports` has a new column `group_num` and `ec_curvedata` has new columns `abc_quality` and `szpiro_ratio`.

**Comment by roed314** [comment]
@SamSchiavone Are there also changes to the schema of `belyi_galmaps`?  I'm seeing test failures about missing `group_num`, but I think that's already present on production for `belyi_galmaps`.

**Comment by SamSchiavone** [comment]
Hi David, I don't think so... I added a `group_num` column to the `belyi_passports` table as you mentioned above, but I don't think I changed the galmaps table.

**Comment by edgarcosta** [comment]
I will copy:
- belyi_passports
- nf_fields
- ec_curvedata
