### ISSUE TITLE
Weight 1 cusp forms should be treated as separate objects

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#59]
Since weight 1 cusp forms are both holomorphic cusp forms and eigenvalue 1/4
Maass forms, they should have their own special home pages, showing things like
"icosahedral".  The new home page of a weight 1 cusp form would be a more natural friend
link from an Artin representation or a Hecke character, than the would the current holomorphic cusp
form or Maass form pages.

**Comment by haraldschilly** [comment]
not a must have for v1.0 but a nice to have

**Comment by edgarcosta** [comment]
Merged into #437
