### ISSUE TITLE
Support transitive group label in abstract group jumpbox

### ISSUE THREAD

**Issue by SamSchiavone** [LMFDB/lmfdb#5903]
It would be nice to be able to enter a transitive group label (e.g., 24T138) in the jumpbox on the abstract group search page, and get the abstract group associated to this transitive permutation group. This can be accomplished by first going to the Galois groups page (e.g., https://beta.lmfdb.org/GaloisGroup/24T138) and scrolling down to Label in the Group invariants section (e.g., 96.67), but this is a bit cumbersome.

**Comment by jenpaulhus** [comment]
This has been implemented now so I'm going to close this issue.
