### ISSUE TITLE
[testing] Friends/related objects

### ISSUE THREAD

**Issue by BarinderBanwait** [LMFDB/lmfdb#5915]
Friends and related objects need testing.

Assign to @junbolau, add modcrvs label

**Comment by edgarcosta** [comment]
a thing to test https://github.com/LMFDB/lmfdb/pull/5929

**Comment by BarinderBanwait** [comment]
As written in #5996 this was done by @junbolau in the last workshop; i just added the thing to test above. Closing as complete.
