### ISSUE TITLE
[testing] Downloads

### ISSUE THREAD

**Issue by BarinderBanwait** [LMFDB/lmfdb#5916]
Add tests for downloads to modcurves.

Assign to me, add modcurves label.

**Comment by BarinderBanwait** [comment]
@junbolau has already done this, and is committed to main. it has the same coverage as `test_download` in genus2_curves. 

If anyone knows of any problematic test cases for downloads then please write them here (@rbommel i seem to recall you mentioned something to me during the workshop) , otherwise I think this issue can be closed.

**Comment by rbommel** [comment]
I think this was issue #5911.
