### ISSUE TITLE
Need more data about spectral parameters

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#592]
On the home page of a GL(3) Maass form L-function it should be easy to find the
imaginary parts of the \Gamma_\R-shifts to higher precision.

http://beta.lmfdb.org/L/ModularForm/GL3/Q/Maass/GL3Maass_1_15.3186_4.19173/

**Comment by davidfarmer** [comment]
Maybe put it in the Selberg data?

**Comment by lemurell** [comment]
This has been done (put in Selberg data) so could be closed.
