### ISSUE TITLE
Broken link in genus 2 curves

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#5928]
On this [Genus 2 curve 515339.a.515339.1](https://beta.lmfdb.org/Genus2Curve/Q/515339/a/515339/1) the link to [Modular form 46849.2.a.a](https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/46849/2/a/a/) is added without checking if the modular form is in the database

**Comment by roed314** [comment]
The link for the particular instance in the description now works, so I'm closing.  @edgarcosta, feel free to reopen if you still want to add a check when constructing the friends list.
