### ISSUE TITLE
Weight 4 level 14 newforms with incorrect Atkin-Lehner eigenvalues.

### ISSUE THREAD

**Issue by wbl** [LMFDB/lmfdb#596]
Comparing http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/14/4/1/a/ with http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/14/4/1/b/ and the associated L-function pages we run into the following interesting phenomenon: both forms have the same weight, and same Atkin-Lehner eigenvalue at degree 7, and same sign of the functional equation, but different Atkin-Lehner eigenvalues at 2. This cannot happen as the global epsilon factor is a product of local epsilon factors.

Henri Cohen's tables indicate that both modular forms have the same signs of Atkin-Lehner at 2 and 7, and that these signs are different. I think 14.4.1a is the one that has a problem, by comparing with his table.

**Comment by sanni85** [comment]
Checking now on beta and on Fredrik's refactor branch, this issue looks fixed.
