### ISSUE TITLE
Sorting by label

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#5979]
In 
  http://www.lmfdb.org/padicField/?n=8&p=2&c=18&hidecol=p.c.e.f.gal.slopes
the fields are helpfully sorted by label, but instead of 
  2.8.18.1, 2.8.18.2, ... 
it does
  2.8.18.1, 2.8.18.10, ...
(sorting the strings).  Note that sorting by label is not an option in the dropdown list--perhaps we could add that, since we using it to break ties.  But wouldn't it also make more sense to sort them in the first way?  (It would make my life easier, when I'm grabbing number 18 from the list, it's easier when that's in the 18th place.)  

I have a workaround, so this is low priority.

**Comment by AndrewVSutherland** [comment]
Agreed, the default sort order should be lexicgraphic on the quadruple of integers (p,n,c,num) that make up the label.  We may need to add a column for num to achieve this (analogous to the column iso_num in nf_fields), but this would be easy to do, and once done we can make this the default sort order.

**Comment by roed314** [comment]
This was solved for CMFs, but not for other parts of the LMFDB (including local fields).

**Comment by AndrewVSutherland** [comment]
Sorry my bad, Edgar linked to this issue in his remark about modular curve label sorting and I didn't actually check to see if it was about modular curves!
