### ISSUE TITLE
Typo in knowl "Discriminant root field"

### ISSUE THREAD

**Issue by hyunjongkimmath** [LMFDB/lmfdb#5984]
The knowl has the sentence

> The ** discriminant root field **...

and it looks the intent was to boldface "discriminant root field" but the spaces before and after the double asterisks `**` are preventing this.

**Comment by roed314** [comment]
Can you check to see if the change I just made to https://beta.lmfdb.org/knowledge/show/nf.discriminant_root_field fixed the issue for you?  It was displaying correctly for me beforehand (and still is), but I deleted the extra spaces.

**Comment by hyunjongkimmath** [comment]
It does indeed show the boldface correctly. Thank you, David!

**Comment by roed314** [comment]
Thanks for the report!
