### ISSUE TITLE
Query does not yield expected result

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#6021]
From the feedback page:

Search query does not yield result -- don't think I asked anything too specific

https://www.lmfdb.org/EllipticCurve/Q/?cm=noCM&nonmax_quantifier=exactly&nonmax_primes=5&count=100

**Comment by edgarcosta** [comment]
same

**Comment by roed314** [comment]
I think we should close this issue for now.  If the reporter can clarify what they were expecting, we can always reopen it.
