### ISSUE TITLE
Some CM isogeny classes are incomplete

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#6022]
There was a bug in (my) Sage code for computing isogenies of CM curves, specifically those with j=0 or 1728 which could miss some isogenies.  The bug was fixed (https://github.com/sagemath/sage/pull/36786) but we need to recompute the classes for these j-invariants.

Example:  isogeny class https://beta.lmfdb.org/EllipticCurve/2.2.5.1/2025.1/d/ shows 2 curves but should show 6, as 5-isogenies were missed. With Sage 10.4.beta4:

sage: K.<r> = NumberField(x^2-5)
sage: E = EllipticCurve("225a1").change_ring(K)
sage: [c.ainvs() for c in E.isogeny_class().curves]
[(0, 0, 1, -810*r - 2700, 31050*r + 59231),
 (0, 0, 1, 810*r - 2700, -31050*r + 59231),
 (0, 0, 1, -90*r - 300, -1150*r - 2194),
 (0, 0, 1, 90*r - 300, 1150*r - 2194),
 (0, 0, 1, 0, -34),
 (0, 0, 1, 0, 1)]

**Comment by JohnCremona** [comment]
For j=0  there are 1065 isogeny classes over 89 fields, with a large proportion (496) over the CM field 2.0.3.1.
For j=1728 there are 618 classes over 69 fields, of which 249 are over the CM field 2.0.4.1.

I think it safer to recompute the isogeny classes for all j=0,1728 curves rather than try to determine which are the cases where the bug made a difference. I am working on this.

**Comment by JohnCremona** [comment]
Partial update:  

   - There are no missing curves (due to this bug) over fields of degree 3, 5, 6. 

   - In degree 4, only over 4.4.1125.1 (class 25.1-b) and 4.4.3500.1 (classes 625.1-a and d) in all cases j=0, the class has size 6 but we only have 2 curves.

   - I am still working on the quadratic base fields.

**Comment by JohnCremona** [comment]
I am now preparing a data update...

**Comment by JohnCremona** [comment]
Data fixed.  Here are the 9 isogeny classes which now have 6 curves, not just the two with j=0.

https://beta.lmfdb.org/EllipticCurve/2.2.21.1/1225.2/c/
https://beta.lmfdb.org/EllipticCurve/2.2.21.1/1225.3/c/
https://beta.lmfdb.org/EllipticCurve/2.2.21.1/441.1/d/
https://beta.lmfdb.org/EllipticCurve/2.2.21.1/49.1/a/
https://beta.lmfdb.org/EllipticCurve/2.2.5.1/2025.1/c/
https://beta.lmfdb.org/EllipticCurve/2.2.5.1/2025.1/d/
https://beta.lmfdb.org/EllipticCurve/4.4.1125.1/25.1/b/
https://beta.lmfdb.org/EllipticCurve/4.4.3600.1/625.1/a/
https://beta.lmfdb.org/EllipticCurve/4.4.3600.1/625.1/d/

If these look good then the database ec_nfcurves can be copied to prod and this issue closed.

**Comment by JohnCremona** [comment]
Copying to prod can wait until I have finished with #6110 as well

**Comment by JohnCremona** [comment]
OK, #6110 is done, so please do the copy, and the close both this and #6110.  THanks!

**Comment by AndrewVSutherland** [comment]
Copying is done, and I know see 6 curves on https://www.lmfdb.org/EllipticCurve/2.2.21.1/1225.2/c/
