### ISSUE TITLE
Another slow number field search

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#6039]
From the feedback page:

https://www.lmfdb.org/NumberField/?degree=8&subfield=4.4.2304.1

search first took too long when i searched for all fields with this as a subfield, then when i limited the search to degree 8 fields it still took too long.

**Comment by AndrewVSutherland** [comment]
This search only takes 2.3s right now (of course that could be due to caching).

**Comment by roed314** [comment]
Same behavior now: timeout, then fairly quick due to caching.

See my suggestion on #5970.

**Comment by AndrewVSutherland** [comment]
Closing this, post any further comments on #5970.
