### ISSUE TITLE
Saving svg images for finite groups

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#6050]
#6048 changed the way we show finite group pictures on their own pages.  We now show it in its own html page, but it would be nice to have an actual .svg file that can be downloaded.

**Comment by rbommel** [comment]
I will add a reference to this: https://stackoverflow.com/questions/10737166/chrome-not-rendering-svg-referenced-via-img-element

**Comment by rbommel** [comment]
Proposed solution: change https to http in https://github.com/LMFDB/lmfdb/blob/c43406743fd1579cdd12c1a5bdcea78f04753fc2/lmfdb/groups/abstract/web_groups.py#L2505

**Comment by roed314** [comment]
This has been fixed according to Raymond's suggestion.
