### ISSUE TITLE
Wrong PariGP data for Newform orbit 80.5.h.b

### ISSUE THREAD

**Issue by clashton1** [LMFDB/lmfdb#6059]
The PariGP data on the page  https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/80/5/h/b/
for Newform orbit 80.5.h.b, namely,
[N,k,chi] = [80,5,Mod(79,80)]
is not correct.

It is the same as the data for Newform orbit 80.5.h.a
[N,k,chi] = [80,5,Mod(79,80)]
https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/80/5/h/a/
This data does appear to be correct for Newform orbit 80.5.h.a, when I use it in PariGP.

It would be great if someone could fix the PariGP data for Newform orbit 80.5.h.b, as I would like to work with it in PariGP. 

The data for Magma and SageMath may be wrong also.

**Comment by AndrewVSutherland** [comment]
The data is not incorrect, in all three cases the code snippets split the space, 80.5.h into three newform subspaces, one of which is 80.5.h.a.  Pari/GP, Magma, and Sage do not guarantee any particular ordering of the newform subspaces (which may even vary from one call to the next).  This is why the code snippets/downloads include the comment **Warning: index may be different**, there is no way to know in advance what the index will be.

To find a particular newform you need to compare traces (or in this case, just look at the coefficient field which is Q(i) for 80.5.h.b).

We could automate this by adding a code that does this trace comparison for you.  I will create a separate issue for this.
