### ISSUE TITLE
Add elliptic curve data over real cubic fields

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#607]
For the 61 totally real cubic fields for which we have Hilbert Modular Forms, work is under way to find and upload elliptic curves matching all the dimensions 1 newforms.  I will use this Issue to keep track of how far this has got, and close it when done.

Almost all curves now found and uploaded for all the 61 fields, but there are 17 missing for field 3.3.D.1:

          49:   1681.4,5,6-a,b,c (3*3=9)
          733:  146.1-a  (1)
          1229: 96.2-g,h (2)
          1373: 45.1-b   (1)
          1396: 70.3-d   (1)
          1492: 80.1-n   (1)
          1524: 6.2-a    (1)
          1708: 26.2-a   (1)

**Comment by AndrewVSutherland** [comment]
@JohnCremona I just checked the first 12 in your list above and they all appear to be there; are there still curves that are missing or can this issue be closed?

**Comment by JohnCremona** [comment]
Closing -- all curves over cubic fields were found.
