### ISSUE TITLE
Timeout for Dirichlet character search

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#6084]
From the feedback page:

Other queries are working, but for some strange reason Dirichlet characters of order 7 (and also conductor 49) are stuck (Error: The search query took longer than expected). The problem perists for at least one week. I also tried different browsers. 

https://www.lmfdb.org/Character/Dirichlet/?order=7

**Comment by AndrewVSutherland** [comment]
Fixed by adding an index (now takes 1-2 seconds).
