### ISSUE TITLE
Duplicate Bianchi modular form knowl

### ISSUE THREAD

**Issue by SamSchiavone** [LMFDB/lmfdb#6085]
These two knowls seem to be largely (if not totally) the same:

https://beta.lmfdb.org/knowledge/show/mf.bianchi.bianchimodularforms
https://beta.lmfdb.org/knowledge/show/mf.bianchi

The second one is only used in one place.

Also, Bianchi modular forms have the wrong knowl link on the RCS page: https://beta.lmfdb.org/knowledge/show/rcs

**Comment by JohnCremona** [comment]
Well, I last edited both but some time ago so I cannot remember what operation I was doing which appears to have paused half way through.  I propose that we only have one -- they are only a little different, and one is surely an edited version of the other.  I have a slight preference for the one with the shorter name, though it is references more times so switching over to that one completely is more tedious.

I will start by editing the references from other knowls (those which link to the long name) and report back here before making any changes to the codebase.

**Comment by JohnCremona** [comment]
I have done the knowl link editing.  Next there are 3 python files and one html template to fix.

**Comment by JohnCremona** [comment]
The PR has been merged.  When it is on beta you should see that for the two knowl links in Sam's original posting, the first one is not cited anywhere.

**Comment by roed314** [comment]
I just deleted the first knowl, so this issue has been resolved.
