### ISSUE TITLE
Relative class numbers of CM number fields

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#6098]
For CM number fields, it would be useful to have a field in the database for the relative class number, and to provide that as as search field. (I would suggest storing 0 when the field is not CM.)

**Comment by kedlaya** [comment]
I note for the record that there are efficient algorithms for computing the relative class number, so it is feasible to report it in some cases even when the class number is infeasible to compute. But to begin with, I would be happy to just have it in cases where the class numbers of the CM field and of the totally real subfield have already been computed.

**Comment by jwj61** [comment]
In progress
