### ISSUE TITLE
Add elliptic curve data over real sextic fields

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#610]
For the 34 totally real sextic fields for which we have Hilbert Modular Forms, work is under way to find and upload elliptic curves matching all the dimensions 1 newforms. I will use this Issue to keep track of how far this has got, and close it when done.

Not started yet.

**Comment by JohnCremona** [comment]
For the record:  21 of the 34 fields are complete.  Over the other 13 fields there are a total of 55 missing curves:

6.6.371293.1:  9 missing 337.3-c, 337.4-c, 337.6-c, 571.1-b, 961.1-b, 961.1-f, 961.2-b, 961.3-b, 961.2-f
6.6.434581.1:  5 missing 211.1-a, 211.2-a, 251.1-a, 349.1-a, 349.2-a
6.6.592661.1:  2 missing 469.1-d, 469.1-c
6.6.820125.1:  3 missing 379.2-a, 379.3-a, 379.5-a
6.6.966125.1:  14 missing: 101.1-b, 101.1-c, 169.1-a, 169.1-b, 275.1-o, 275.1-l, 295.1-b, 295.1-e, 341.2-b, 341.2-i, 355.3-a, 355.3-h, 379.1-a, 379.1-b
6.6.980125.1:  8 missing: 209.2-b, 209.2-c, 269.3-b, 269.3-c, 311.1-b, 311.1-c, 319.1-d, 379.1-a
6.6.1416125.1: 2 missing 151.1-c, 151.5-c
6.6.1202933.1: 1 missing 320.1-d
6.6.1312625.1: 2 missing 199.3-d, 199.3-g
6.6.1397493.1: 1 missing 71.2-c
6.6.1922000.1: 2  missing: 121.1-b, 121.3-b
6.6.1995125.1: 3 missing 41.1-a, 109.1-a, 121.6-d
6.6.1292517.1: 3 missing 53.1-c, 53.2-c, 199.1-a

**Comment by JohnCremona** [comment]
It's about time I had another go at finding these, with 3-4 years of Magma development maybe I will be more successful.  I have had to update a couple of scripts ehich had not been used since the sql transfer and which needed some python 3 attention, but the searches are now under way.

**Comment by JohnCremona** [comment]
Update 19 April 2021: I have 42 out of the 55 curves listed as missing, and in particular 5 of the above 13 fields have no gaps.  I am hoping to get the rest before uploading, but may upload the ones I have without waiting.

**Comment by JohnCremona** [comment]
I have uploaded 43 extra isogeny classes (67 curves).  The remaining 12 missing classes are still running:
6.6.1292517.1-53.1-c
6.6.1292517.1-53.2-c
6.6.1922000.1-121.3-b
6.6.1995125.1-41.1-a
6.6.592661.1-469.1-d
6.6.820125.1-379.2-a
6.6.820125.1-379.3-a
6.6.820125.1-379.5-a
6.6.966125.1-341.2-b
6.6.966125.1-341.2-i
6.6.980125.1-209.2-b
6.6.980125.1-209.2-c


Here's an example of a curve which was not there (compare with prod): go to 
https://beta.lmfdb.org/ModularForm/GL2/TotallyReal/6.6.1202933.1/holomorphic/6.6.1202933.1-320.1-d  and you'll see under Related Objects the link to the new isogeny class.  But not on www.lmfdb.org.

**Comment by JohnCremona** [comment]
Update 2/2/22.  As suggested by @jvoight I am taking a new look at these, and have 4 of the 12 already by considering field automorphisms (aka Galois conjugates, though the fields are not all Galois):

- 6.6.1292517.1-53.1-c, 6.6.1292517.1-53.2-c:   conjugate to each other but not to any we have already.

- 6.6.1922000.1-121.3-b: done -- conjugate to 121.1-b

- 6.6.1995125.1-41.1-a: no field automorphisms

- 6.6.592661.1-469.1-d: no field automorphisms

- 6.6.820125.1-379.2-a, 6.6.820125.1-379.3-a, 6.6.820125.1-379.5-a: all done, the field has 6 autos (Galois), these are conjugate and we had the other 3.

- 6.6.966125.1-341.2-b, 6.6.966125.1-341.2-i: no field autos; these are quadratic twists of each other.

- 6.6.980125.1-209.2-b, 6.6.980125.1-209.2-c: no field autos; these are quadratic twists of each other.

For each of the cases remaining I have a magma file to call EllipticCurveSearch() with the right field, conductor and aP (of which we have between 100 and 200 for each), which I am running with successively larger "effort" parameter.

**Comment by JohnCremona** [comment]
Update 21.2.22:  together with @jvoight  and @bmatschke we now have all the remaining curves!  I will upload them as soon as I have computed the extra data for each.

These were all cases where Magma's EllipticCurveSearch() was not successful even with quite large "effort" parameter.  Instead what we did was as follows, using knowledge of the base field K, the conductor N, the set S of primes of bad reduction and the Frobenius traces a_P at many good primes P:
   1. if the a_P are all even for P of odd norm then E has 2-torsion, in which case we can use a_P mod 4 to determine whether there is a curve in the isogeny class with full 2-torsion.  This happened for the curves over 6.6.980125.1.
   2.  if some a_P are odd then we find the 2-division field: we can use a_P and N(P) mod 4 to determine the quadratic subfield L/K and in each case there was only one C3-extension M/L which could be the 2-division field (an S3-extension of K), found using class field theory in Magma (the Kummer theory approach was too slow).  Using the ideas of Black Box Galois representations to find L was @jvoight 's idea and turned out to be a very simple addition to the techniques I worked out with Argaez in our J.Alg. paper.
   3. Given the 2-division field M and the set S, @bmatschke solved the S-unit equation over M to find the possible Legendre lambda-invariants of curves with good reduction outside S and 2-division field M, and hence their j-invariants. (His method improves on that developed by A. Koutsianas in his theseis.) I then found the correct quadratic twists which had conductor exactly N, and checked that all the a_P agreed with the Hilbert modular form.

**Comment by JohnCremona** [comment]
OK, the last 8 isogeny classes of curves are now uploaded to beta, and the table ec_nfcurves can be copied to prod.  To see them you can follow the links from these HMF pages:
https://beta.lmfdb.org/ModularForm/GL2/TotallyReal/6.6.1292517.1/holomorphic/6.6.1292517.1-53.1-c
https://beta.lmfdb.org/ModularForm/GL2/TotallyReal/6.6.1292517.1/holomorphic/6.6.1292517.1-53.2-c
https://beta.lmfdb.org/ModularForm/GL2/TotallyReal/6.6.1995125.1/holomorphic/6.6.1995125.1-41.1-a
https://beta.lmfdb.org/ModularForm/GL2/TotallyReal/6.6.592661.1/holomorphic/6.6.592661.1-469.1-d
https://beta.lmfdb.org/ModularForm/GL2/TotallyReal/6.6.966125.1/holomorphic/6.6.966125.1-341.2-b
https://beta.lmfdb.org/ModularForm/GL2/TotallyReal/6.6.966125.1/holomorphic/6.6.966125.1-341.2-i
https://beta.lmfdb.org/ModularForm/GL2/TotallyReal/6.6.980125.1/holomorphic/6.6.980125.1-209.2-b
https://beta.lmfdb.org/ModularForm/GL2/TotallyReal/6.6.980125.1/holomorphic/6.6.980125.1-209.2-c

**Comment by JohnCremona** [comment]
sage: db.hmf_forms.count({'deg':6, 'dimension':1})                         
6152
sage: db.ec_nfcurves.count({'degree':6, 'number':1})                       
6152

**Comment by AndrewVSutherland** [comment]
The data has been copied to proddb where you now see 6152 isogeny classes in degree 6: https://www.lmfdb.org/EllipticCurve/?bf_deg=6&one=yes&search_type=List

**Comment by JohnCremona** [comment]
Thanks for closing this issue, opened in November 2015 at ICERM!
