### ISSUE TITLE
Data pull request

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#6102]
Currently, www.lmfdb.org/GaloisGroup/5T5 is failing.  Some group tables need to be pushed to production, though I'm not 100% sure which are required.  Certainly `gps_groups` is needed; I don't think any others are, but in decreasing order of likelihood it's `gps_conj_classes`, `gps_char`, `gps_qchar`, `gps_subgroups`.

We will need to push everything to production in a couple weeks, but the data will change before then.

**Comment by edgarcosta** [comment]
Is it okay now? 
I only copied `gps_groups`

**Comment by jwj61** [comment]
Looks ok to me

**Comment by edgarcosta** [comment]
Please reopen, if not okay

**Comment by roed314** [comment]
Thanks!  Looks good to me as well.
