### ISSUE TITLE
Elliptic curve timeout

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#6127]
From the feedback page:

Asking for the elliptic curves with non-max. mod-13 Galois rep. times out.
http://www.lmfdb.org/EllipticCurve/Q/?nonmax_primes=13

**Comment by AndrewVSutherland** [comment]
I'm not able to get this to take more than 5s (even varying the prime), and there is already an index on nomaximal primes.  We have been getting hit hard be a new bot for the last 10 days (now blocked), which was slowing everything down, so my guess is this was do to that.  In any case, I don't think there is any action for us to take now (but please reopen if this is reported again).
