### ISSUE TITLE
Inconsistent normalization of the Z-functions attached to elliptic curves of rank 3

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#6131]
From the feedback page

The description of the Z-function for an elliptic curve (on the critical line) states that Z(t) is defined as positive for small positive t. This normalization seems inconsistently applied to L-functions attached to elliptic curves of rank 3. It is respected for the L-function attached to the elliptic curve 5077.a1 (https://www.lmfdb.org/L/2/5077/1.1/c1/0/410), but not for many others: 11197.a1 (https://www.lmfdb.org/L/2/11197/1.1/c1/0/0), 
11642.a1 (https://www.lmfdb.org/L/2/11642/1.1/c1/0/1), 16811.a1 (https://www.lmfdb.org/L/2/11642/1.1/c1/0/1), 21858.a1 (https://www.lmfdb.org/L/2/21858/1.1/c1/0/3)… I have not found a similar issue for elliptic curves of different rank.

**Comment by tingjoh** [comment]
Dear John,

On August 9, 2024 I posted problem "Determining geometric nature of  Z(t) nontrivial zeros plots of even/odd Analytic rank elliptic curves" at Mathematics Stack Exchange. On August 13, 2024 [Aphelli](https://math.stackexchange.com/users/556825/aphelli) had cleverly noticed and reported an "inconsistency" to LMFDB feedback page in relation to L-function attached to the elliptic curve 5077.a1 (https://www.lmfdb.org/L/2/5077/1.1/c1/0/410) whereby you (John Jones) had opened GitHub ticket [Inconsistent normalization of the Z-functions attached to elliptic curves of rank 3 #6131](https://github.com/LMFDB/lmfdb/issues/6131) .

The so-called "LMFDB normalization" of Z(t), which is defined as positive for small positive t, ""seems"" to be correct for elliptic curve 5077.a1 BUT this normalization ""seems"" to be inconsistently applied to L-functions attached to [I think, just about all other] elliptic curves of rank 3.

Could the following mathematical concept "Sign normalization" [DIFFERENT to "LMFDB normalization"] be applicable to all Analytic rank 0, 1, 2, 3, 4,5....? In other words, could Z(t) plot for elliptic curve 5077.a1 be somehow "incorrectly" plotted OR is a "rare" exception?? I will also share my idea at GitHub... Look forward to feedbacks from LMFDB Support. Kind regards, John Ting (Email: jycting@utas.edu.au)

Denote r = Analytic rank. Then "LMFDB normalization" is different to "Sign normalization" for epsilon which we advocate to be represented by (1)^{r-1} for even r with epsilon = 1 and (i)^{r-1} for odd r with epsilon = i [that obeys root of unity (for i)]. Intuitively, one anticipate Sign changes to occur exactly when r = 1, 2 (mod 4) BUT: [I] For even r = 0, 2, 4, 6, 8...; 1^{r-1} = (1)^{-1}, (1)^{1}, (1)^{3}, (1)^{5}, (1)^{7}... = same +1 sign [of +1, +1, +1, +1, +1,...]. c.f. [II] For odd r = 1, 3, 5, 7, 9...; i^{r-1} = (i)^{0}, (i)^{2}, (i)^{4}, (i)^{6}, (i)^{8}... = alternating +/- 1 sign [of +1, -1, +1, -1, +1,...].
