### ISSUE TITLE
Dual L-function

### ISSUE THREAD

**Issue by SallyKoutsoliotas** [LMFDB/lmfdb#617]
Make a "friend" link to the dual L-function when the L-function is not self-dual.
For example, Dirichlet L-functions.

**Comment by lemurell** [comment]
Has been done for Dirichlet L-functions and Maass forms, but should be done generally once "every" L-function is in the database.

**Comment by AndrewVSutherland** [comment]
Addressed for classical modular forms by #2717.  Are there any other parts of the LMFDB (other than Dirichlet L-functions and Maass forms) where this is still an issue?

**Comment by davidfarmer** [comment]
This seems to have been done.
