### ISSUE TITLE
Notation for the order of the quotient G/N 

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#6170]
at the moment, we use |G/N|, as the table header in "Low degree resolvents",  see: https://beta.lmfdb.org/GaloisGroup/24T2668

We should switch to #G/N, or [G:N].

It also needs to be clarified what is N from that table.

I believe the first item is a good first issue.

**Comment by jwj61** [comment]
It should use the latex macro \card (which we already have).
