### ISSUE TITLE
Some abelian varieties incorrectly marked as primitive

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#6240]
Issue reported by Thomas Geisser. Minimal example: the abelian variety [2.4.d_h](https://www.lmfdb.org/Variety/Abelian/Fq/2/4/d_h) lists [2.16.f_j](https://www.lmfdb.org/Variety/Abelian/Fq/2/16/f_j) as a base change, but the latter claims to be primitive.

**Comment by roed314** [comment]
I'm not sure where the bug came from, but I've recomputed all the relevant base changes and am updating `av_fq_isog` on beta now.  After this is done (in the next hour or so), if everything looks good then we should push `av_fq_isog` to production and this issue can be closed.

**Comment by roed314** [comment]
Updated on beta: you can check that https://beta.lmfdb.org/Variety/Abelian/Fq/2/16/f_j no longer displays as primitive. @AndrewVSutherland or @edgarcosta, can you push `av_fq_isog` to prod?

**Comment by roed314** [comment]
Thanks @edgarcosta.  This has been fixed on both beta and prod, so I'm closing.
