### ISSUE TITLE
Document alternatives to API

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#6242]
There are three reasonable ways to access large amounts of data from the LMFDB:
1. Using the download functionality implemented in #5702, which lets you download search results with custom columns in different formats; limited to roughly 100MB of data per download
2. Using the [API](https://beta.lmfdb.org/api/); doesn't allow an offset larger than 10,000
3. Using a direct connection to the devmirror.lmfdb.xyz postgres server, either via [psycodict](https://github.com/roed314/psycodict) through LMFDB or [LMFDB-lite](https://github.com/roed314/lmfdb-lite), or via any other PostgreSQL front end.

We should decide what guidelines we should offer users on which method to choose and then document them (probably at the top of the [API](https://beta.lmfdb.org/api/)).

**Comment by AndrewVSutherland** [comment]
I like this suggestion, and I might even suggest making the [Database](https://beta.lmfdb.org/api/) link on the sidebar take you to a shorter/friendlier page that just explains these 3 options, with (2) including a link to the API page that is currently linked to.

I think the order you listed the options above is correct, and users should be directed to (1) first, which I would expect to cover most casual needs.  The one use case where (2) might be preferred is in a situation where one wants to dynamically access the LMFDB in a simple automated way.  (3) is for everything else (it requires more effort and sophistication on the part of the user but will let them do whatever they want).

**Comment by roed314** [comment]
This has been resolved by #6247.
