### ISSUE TITLE
Funny slider behavior on Dirichlet character pages.

### ISSUE THREAD

**Issue by wbl** [LMFDB/lmfdb#626]
Go to http://beta.lmfdb.org/Character/Dirichlet/28/23 and drag the slider under Jacobi characters to the right beyond about halfway. As you drag the slider the number 1 appears in the equation at all times, even as the box says something more realistic. For $n=25$ we get an error saying n must be coprime to the modulus.

**Comment by pascalmolin** [comment]
I'll look at it

**Comment by jvoight** [comment]
@pascalmolin : Still broken, any updates?

**Comment by pascalmolin** [comment]
Forgot it: I am taking a look.

2016-05-01 20:47 GMT+02:00 jvoight <notifications@github.com>:
