### ISSUE TITLE
Mathjax linebreaking needed for Fourier coefficients of vector-valued Siegel modular forms

### ISSUE THREAD

**Issue by wbl** [LMFDB/lmfdb#627]
http://beta.lmfdb.org/ModularForm/GSp/Q/Sp4Z_2.18_C/?dets=255 has some layout problems. When we MathJax the formulas, they are too long to fit the table-based layout and so squash other columns to unreadability. @jwj61 has a branch that enables us to tell Mathjax to break lines.

**Comment by AndrewVSutherland** [comment]
With PR #1577 lines that are too long to display or format reasonably are suppressed (I think this is a better solution than having Mathjax break lines, in several cases even a single coefficient is too large to fit on a line and there really is no way to reasonably display these, no matter how you much you fiddle with the Mathjax).
