### ISSUE TITLE
ECQ and ECNF pages: make more consistent

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#6275]
As reported by @AndrewVSutherland at #6273: 

> I notice that the ECQ/ECNF Mordell-Weil Invariants sections use rather different layouts, are there reasons to format them differently? I like that everything is grouped under one heading in the ECNF layout, but I also like the way the structure of the MW group is shown on the ECQ pages (including both the free and torsion parts rather than giving the structure of the torsion subgroup on a separate line). I think it might be worth figuring out the optimal layout (perhaps combining elements of both, but also see (4) below), and then uniformizing them.

I set the milestone to 1.3 rather than 1.2.2 as 1 Dec is only a couple of days away.

**Comment by JohnCremona** [comment]
See #6276:  I am doing both in one PR but will leave this open.

**Comment by roed314** [comment]
@JohnCremona Now that #6279 has been merged and is on beta, can this and #6276 be closed?

**Comment by JohnCremona** [comment]
Yes, I think so. I am still working on replacing the ECNF gens with smaller ones but that will take some time ( and will only affect stored data, not code).

**Comment by roed314** [comment]
Great!

**Comment by roed314** [comment]
For the record, here are some differences that still exist:
* ECNF is missing integral points
* ECNF is missing Faltings height, stable Faltings height, abc quality, and Szpiro ratio.
* For ECNF the period is labeled "Period" while for ECQ it's labeled "Real period."
* There is no displayed BSD formula for ECNF.
* In the local data for ECNF, the symbols for conductor and discriminant do not match those used above, and $$\mathrm{ord}(j)$$ does not match $$v_p(\mathrm{den}(j))$$ on ECQ.  There is also no note when the curve is semistable or count for the number of primes of bad reduction.

@JohnCremona, if any of these are things you think deserve an issue or a PR, feel free to open one!
*

**Comment by roed314** [comment]
Thanks for the explanations!  I was just going through and recording the differences, not saying that they needed to be fixed.

**Comment by JohnCremona** [comment]
I have created a feature request issue for adding Szpiro ratio (easy), Faltings height (not too hard) and possibly stable Faltings height (harder) at #6292 .  Of these, the Szpiro ratio could be done easily on the fly using what is already in the database.

Adding integral points is a lot more work, so not on the horizon and I have not made an issue even as a feature request.

There's now a PR for the BSD formula #6290 .

I still don't know of a number field version of abc-ratio, so have not made that a feature request issue.  If someone knows of a definition, they can!
