### ISSUE TITLE
Listing of elliptic curve generators

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#6276]
As report by @AndrewVSutherland at #6273 :

> I notice that both ECQ/ECNF use a table with a column for each infinite order generator, which is already likely to force horizontal scrolling on pages like https://www.lmfdb.org/EllipticCurve/Q/19047851/a/1 for many users, and I worry things will get worse in the future if/when we add more higher rank curves (we have definitely been getting requests to include the new Elkies-Klagsbrun rank 29 curve, for example!) I wonder if it would make more sense to use a table with a row for each generator (which could also include torsion generators and a column for the order, giving you a complete Z-basis). This table will be very short for most curves, so I don't think screen real estate is a major concern.

**Comment by JohnCremona** [comment]
I have done this, both for ECQ and ECNF, and dealing with #6275 at the same time.  It looks OK when we have all the data, but for ECNF in particular there are issues around not always having computed the rank exactly, so the number of generators we have to display may (for example) be 0 when the rank bounds are 0 and 2.  So I am check lots of representative examples before making a PR, and hope to give several links to those in the PR.

**Comment by JohnCremona** [comment]
Question:  on an ECQ curve page the BSD invariants include "Special value" with knowl ec.q.special_value, while in an ECNF curve page we have instead "Leading coefficient" with knowl lfunction.leading_coeff.  There is no knowl ec.special_value, though there coud be.  Shall we make the ECQ page also show "Leadiing coefficient"?

**Comment by roed314** [comment]
I like the ec.q.special_value knowl more than lfunction.leading_coeff for this purpose.  Maybe change the name of ec.q.special_value to ec.special_value and use it for both ECQ and ECNF?

**Comment by JohnCremona** [comment]
> I like the ec.q.special_value knowl more than lfunction.leading_coeff for this purpose. Maybe change the name of ec.q.special_value to ec.special_value and use it for both ECQ and ECNF?

Can do.  The knowl will need editing of course.  I'll try to finish this tomorrow morning

**Comment by roed314** [comment]
Looks good.
