### ISSUE TITLE
wrong 'geometrically simple' data for isogeny classes of abelian varieties over finite fields

### ISSUE THREAD

**Issue by stmar89** [LMFDB/lmfdb#6291]
I look at the isogeny class
https://www.lmfdb.org/Variety/Abelian/Fq/4/2/a_a_a_ag
It says that it is geometrically simple.
If we extend the characteristic polynomial to FF8, we get
x^8 - 24*x^7 + 280*x^6 - 2016*x^5 + 9744*x^4 - 32256*x^3 + 71680*x^2 - 98304*x + 65536
which equals
(x^2 - 6*x + 16)^4.
This is a 4th power of a supersingular elliptic curve.

**Comment by roed314** [comment]
I'm confused.  The isogeny class you link to has L-polynomial $$1-6x^4+16x^8$$.  When I base change that to $$\mathbb{F}_8$$, I get $$1 + 72x^4 + 4096x^8$$, which is irreducible.  Indeed, if you look at the Newton polygon for this isogeny class it has slopes $$\frac14, \frac34$$, so it can't be a 4th power of an elliptic curve.

Did you link to the wrong isogeny class?

**Comment by stmar89** [comment]
Sorry I wrote too quickly. I wanted to extend to F16, where the characteristic polynomial becomes (x^2 - 6x + 16)^4.
But you are right: it cannot be a 4th power of an elliptic curve. Computing the invariants shows that it is simple with quaternionic endomorphism algebra. 
My bad!

**Comment by roed314** [comment]
No problem!
