### ISSUE TITLE
Incomplete Weil Polynomials Data for hyperelliptic Jacobians

### ISSUE THREAD

**Issue by assaferan** [LMFDB/lmfdb#6308]
[This page](https://www.lmfdb.org/Variety/Abelian/Fq/Completeness) states that the list of hyperelliptic curves with Jacobian in each isogeny class has been computed in genus $3$ for $q \le 25$. However, querying for either $q=17$ or $q=19$ with a hyperelliptic curve returns no results, contradicting the existence of hyperelliptic curves of genus 3 over these fields.

**Comment by roed314** [comment]
Thanks, I'll fix this.

**Comment by roed314** [comment]
This has been fixed on beta for q=17 and 19; q=13 was also updated based on a bug @everetthowe found in his code for generating hyperelliptic curves.  I'm going to leave this issue open until Everett can confirm whether there's also a problem with q=25.

**Comment by edgarcosta** [comment]
the data has been updated

**Comment by everetthowe** [comment]
Just to explicitly confirm: There was not an issue with the q=25 data.
