### ISSUE TITLE
Formatting issuesfor genus 2 endomorphism data

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#634]
Consider for example the page:

http://beta.lmfdb.org/Genus2Curve/Q/11664/a/11664/1

The minimal polynomials of generators need to have their exponents wrapped in braces, i.e., x^{12} rather than x^12.

**Comment by JohnCremona** [comment]
I will fix that; it is similar to the thing I fixed at pull request #620.

**Comment by JohnCremona** [comment]
Fixed in #639
