### ISSUE TITLE
Decomposition of genus 2 curves show wrong elliptic curve labels

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#635]
Consider the page:

http://beta.lmfdb.org/Genus2Curve/Q/11664/a/11664/1

At the bottom, there are references to elliptic curves "432b1" and "27a3" (Cremona-style labels) but the links are to "432.b1" and "27.a3" (LMFDB labels), which are different curves entirely. Within LMFDB I think we should be consistently using the LMFDB-style labels, but in any case we need to eliminate the confusion about whether we are linking to the correct curve.

**Comment by JohnCremona** [comment]
I'll fix that too,

**Comment by JohnCremona** [comment]
Fixed  in #639
