### ISSUE TITLE
Invalid factors of End x RR

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#636]
Consider the page:

http://beta.lmfdb.org/Genus2Curve/Q/11664/a/11664/1

Some of the endomorphism data includes the line:

End(J_K)⊗R	≃ 	Invalid factors of End x RR... please report this

Duly reported!

**Comment by JRSijsling** [comment]
Will be fixed in an upcoming pull request. The issue was (fortunately!) only that I had forgotten to take into account the obviously possible case where this ring is CC x CC.

**Comment by JohnCremona** [comment]
Fixed in #639
