### ISSUE TITLE
Circle diagram for hypergeometric motives could be redesigned

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#64]
Proposed: while preserving the color distinction, move one set of numbers (say the As) slightly outside the circle and the others (say the Bs) slightly inside. That way, there is less dependence on the color distinction for those who have trouble perceiving it; it is easier to read off the entire set A or B all at once; and the numbers themselves become easier to read because the circle no longer passes through them.

**Comment by JohnCremona** [comment]
Sample URL please?

**Comment by davidfarmer** [comment]
Probably this was already done.  This example appears as requested:

http://beta.lmfdb.org/Motive/Hypergeometric/Q/A2.2.2_B1.3

**Comment by JohnCremona** [comment]
OK.  I have no idea what the diagram is supposed to represent anyway!  We'll ask Kiran if he is now happy and if so, close the issue.

**Comment by JohnCremona** [comment]
kedlaya writes: "Now that I finally managed to remember how to interpret the diagram,
yes, this looks fine. Clearly we need some more knowl-edge to document
these pages..."
