### ISSUE TITLE
Searching modular forms 

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#648]
It is needed to add searching options for modular forms.

**Comment by AurelPage** [comment]
Working on a basic version of this.

**Comment by JohnCremona** [comment]
There are many problems with the search page for classical MFs.  This is *not* ready for release.

**Comment by JohnCremona** [comment]
1. At http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/ there is explanatory text about "n/a" which need not be there unless n/a actually does appear in the table.

    2. Enter level 12 and weight 2 and it says that this space is not in the db, but if you change the weight to the range 2-4 then you get a table clearly showing that the dimension for weight 2 is 0.

    3. If you search levels 1-12 and weight 2 the table you get is fine but in the boxes underneath you see 2-36 in the weight box, where it should be what you entered earlier.

    4. If yo uenter junk into either weight or level search boxes it gives a server error.

**Comment by fredstro** [comment]
I have a fix for 1 and 2 and I will make a pull request for this soon.

I will look at 3 tomorrow (but for 4. I was told in Bristol not to do anything with search parsing since someone else was supposed to make something more general)

**Comment by jwj61** [comment]
It looks like he did not get around the search boxes for modular forms, although the infrastructure is probably there.

**Comment by JohnCremona** [comment]
I am testing #1094 now...

**Comment by JohnCremona** [comment]
All 4 of the specifics I listed are ficed, so I am closing this.
