### ISSUE TITLE
Use n/a when data missing

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#649]
/ModularForm/GL2/Q/holomorphic/ranges?level=&weight=26&character=0&Submit=Search

**Comment by AurelPage** [comment]
I am working on it.

**Comment by AurelPage** [comment]
More interesting test case: /ModularForm/GL2/Q/holomorphic/ranges/?level=1-30&weight=2-26&group=0

**Comment by davidfarmer** [comment]
Fixed in Fredrik's refactor branch
