### ISSUE TITLE
Make user adjust Fourier coefficient embeddings

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#653]
On the page of a newform (like /ModularForm/GL2/Q/holomorphic/23/12/1/a/), we currently only display the first three Fourier coefficients with all of their embeddings. The user should be able to adjust this display. I will be working on this.

**Comment by edgarcosta** [comment]
Done.

eg:
- http://cmfs.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/23/9/d/a/
- http://cmfs.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/380/2/i/b/

**Comment by AndrewVSutherland** [comment]
Addressed by #2717, but also see #2756.
