### ISSUE TITLE
Create separate page for each embedding of a newform

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#659]
When the Fourier coefficients are not rational, there should be a separate page for each embedding where the q-expansion would be displayed as complex numbers (using the precomputed embeddings) with real and imaginary part as decimals.

(For instance, on /ModularForm/GL2/Q/holomorphic/23/12/1/b/)

**Comment by sehlen** [comment]
@jwbober I just thought this might be the natural place where your "numerical modular forms" could live. As long as you know the exact label then appending a number for the embedding would lead to a form with coefficients in "C" and this could either come from embedding the coefficients if known or from numerical computations. If we don't know the exact label, we could have a scheme as proposed in https://github.com/LMFDB/lmfdb/issues/1387.

**Comment by edgarcosta** [comment]
I think we have achieved this: http://cmfs.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/91/3/y/a/

However, we display the embeddings in a single table

**Comment by AndrewVSutherland** [comment]
Addressed by #2717, and in fact we now do give every embedding its own homepage (which you can reach from the table),  See

http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/91/3/y/a/
http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/91/3/y/a/15/7/

for example
