### ISSUE TITLE
data present for gamma_1 but not for gamma_0

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#662]
Some dimensions are known for gamma_1 but not for gamma_0:
compare
http://localhost:37777/ModularForm/GL2/Q/holomorphic/?group=0&&level=2-100&weight=2-100
then switch to Gamma_1.

**Comment by JohnCremona** [comment]
Need to run the script to compute and upload these -- once.

**Comment by JohnCremona** [comment]
Am I right in thinking that Aurel is now running this script on everything?  Can you report here when that is done so the issue can be closed.

At present I see Gamma_0 dimensions for weight <= 20 (all levels to 100) and level <= 6 (all weights).

**Comment by fredstro** [comment]
Well, this is actually me running a script to recompute all WebNewForms

**Comment by JohnCremona** [comment]
Ah OK -- when the dimensions are there for the range in these tables, say so here.

**Comment by JohnCremona** [comment]
Any news on this?

**Comment by fredstro** [comment]
I fixed this now. The problem was the the field 'cchi' (giving the conrey character number) was not set in a lot of the records and this field was used in the search function.

**Comment by JohnCremona** [comment]
Thanks -- I see that this is a data fix rather than a code fix, so this issue can be closed -- the last of the December issues!
