### ISSUE TITLE
Empty spaces should be clickable?

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#664]
In a table of dimensions, such as on the main page:
ModularForm/GL2/Q/holomorphic/
should the "0"s be clickable?

**Comment by AurelPage** [comment]
What would you display when you click on those?

**Comment by davidfarmer** [comment]
You would see the same as you see now if you directly enter that URL.

**Comment by AurelPage** [comment]
Ok. I could easily do it, but I am not sure if this is what we want. Should we discuss it quickly when we are all together?

**Comment by AurelPage** [comment]
Check that it works even without debug mode.

**Comment by fredstro** [comment]
Works for me
