### ISSUE TITLE
Download Fourier coefficients does not work properly.

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#666]
Go to /ModularForm/GL2/Q/holomorphic/23/12/1/a/, try to download >= 100 Fourier coefficients.
After that it's not possible anymore to download <100 Fourier coefficients because the number gets rest to 100. Also, 100 should be possible since we tell the user that 100 are available.

**Comment by sehlen** [comment]
<img width="518" alt="screen shot 2015-12-15 at 15 14 32" src="https://cloud.githubusercontent.com/assets/2471633/11814511/078dda3a-a33f-11e5-9ef5-c044ad135ea2.png">

**Comment by fredstro** [comment]
Fixed this in my refactor branch

**Comment by davidfarmer** [comment]
See Issue #671
