### ISSUE TITLE
Does "100 coefficients" include the coefficient of q^{100}?

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#671]
Download 100 coefficients from here:
ModularForm/GL2/Q/holomorphic/23/12/1/a/

**Comment by sehlen** [comment]
Since we start counting at 0 in the file that you download, 100 coefficients should not include one of q^100.

**Comment by JohnCremona** [comment]
The download worked OK for me, giving me a txt file to save.

**Comment by davidfarmer** [comment]
Change the form to say "Coefficients of $q^n$ for $n\le 100$.

**Comment by davidfarmer** [comment]
Fixed in refactor, but also see issue #683
