### ISSUE TITLE
Table options for old/new/CM

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#674]
on this page:
ModularForm/GL2/Q/holomorphic/

**Comment by fredstro** [comment]
Just to have something more fun to do while waiting for recomputations of data to finish I implemented this in a new branch: "cm_filter" . Please check it out and let me know if you have any suggestions for how it should be displayed. 
(Note that the CM forms are rather sparse so to see anything you have to extend the table)

**Comment by AndrewVSutherland** [comment]
Addressed by #2717.  See http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/?search_type=SpaceDimensions.  The dimension of the old space is also shown on each newspace home page.
