### ISSUE TITLE
Empty space should contain 18 newforms

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#675]
Click on the "18" under character 10
ModularForm/GL2/Q/holomorphic/111/4/10/

**Comment by nmascot** [comment]
Here is another example:
ModularForm/GL2/Q/holomorphic/20/4/?group=1
If you click on the space of dim 7, you get a page with only one (rational) newform.

I suppose it is the same problem and does not deserve a new issue ?

**Comment by sehlen** [comment]
In fact the space is not in the database. I am working on showing an error message and submitted another issue #698 that the number should not be clickable leading to this page.

**Comment by sehlen** [comment]
This should be fixed after https://github.com/fredstro/lmfdb/pull/39 is merged.
