### ISSUE TITLE
Create knowls appearing on modular forms pages 

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#680]
The knowls with identifiers

mf.elliptic.cm_form
mf.elliptic.fouriercoefficients
mf.elliptic.satake_parameters

are to be linked from every modular forms page; see for example http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/1/12/1/a/.  But first, they need to be created!

**Comment by sehlen** [comment]
I created a first version of the CM form knowl.

**Comment by kedlaya** [comment]
Looks good. I should have included mf.elliptic.embeddings, which I guess only appears when the coefficients lie in a field larger than Q.

On the search results page, there are also

mf.elliptic.hecke-orbits
mf.elliptic.q-expansion-of-eigenform

**Comment by am-github** [comment]
I created a version of the Fourier coefficients knowl. I also did one for the width of a cusp, with the tag mf.cusp.width (i wanted to create an id as a child of mf.sl2z.subgroup.cusp, but it didn't allow me to insert digits into the name) and I added the generators of sl2z in the definition.
