### ISSUE TITLE
Create knowls for specific modular forms

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#681]
Individual modular forms have optional knowls that will appear at the top; I created an example for Delta:

http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/1/12/1/a/

Which other modular forms need such special documentation?

**Comment by williamstein** [comment]
Possibly relevant: http://www.math.harvard.edu/~elkies/nature.html

The tables in this paper involving interesting record higher weight forms with certain properties would be good (Ken Ono was asking me for such examples last month): http://wstein.org/papers/motive_visibility/

(I guess it would be nice if while browsing lmfdb one could simply add additional information -- just like I'm adding info in this box -- to lmfdb...)

**Comment by jwj61** [comment]
If you are logged into lmfdb, then you can easily add information to a home page.  There should be placeholder links at the top and bottom of the page to create knowls which would show in the corresponding spot for that home page.  This is how Kiran added information about Delta.

**Comment by williamstein** [comment]
How do you create an account on the lmfdb website?

**Comment by haraldschilly** [comment]
@williamstein I'll email you a token.

**Comment by pdehaye** [comment]
This feature is actually already used for some elliptic curves. See
https://github.com/LMFDB/lmfdb/issues/757
for a list.
Paul
