### ISSUE TITLE
Variable name 'a' replaced everywhere

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#685]
On this page the variable 'a' has been replaced by 'alpha_1',
but the substitution appears to have replaced every occurrence of the
letter 'a', including in \frac and \zeta
ModularForm/GL2/Q/holomorphic/5/9/2/

I think the culprit may be line 116 of
lmfdb/modular_forms/elliptic_modular_forms/backend/web_newforms.py

**Comment by davidfarmer** [comment]
I am working on it

**Comment by sehlen** [comment]
Same problem theoretically affects the conversion of a polynomial in line 783 of web_object.py:

```
   def web_latex_poly(pol, name='x'):
    return web_latex_split_on_pm(latex(pol).replace(latex(pol.parent().gen()),name))
```
In practice, however, it is not affected since this is a polynomial with integer coefficients.

**Comment by davidfarmer** [comment]
Actually, the polynomial could have \zeta_j coefficients, so it needs to be fixed, too.
