### ISSUE TITLE
Show Hecke eigenvalue field 

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#693]
In the page of a newform show the Hecke eigenvalue field and not only the minimal polynomial of \alpha.

**Comment by nmascot** [comment]
I've just sent to Stephan and Fredrik a script which will check if the field is in the number field DB or not, and use the same defining polynomial if it is (only for Gamma0 for now).
Large fields tend not to be in the DB, not much we can do about it.

**Comment by sanni85** [comment]
I have changed the code so that if there is a lmfdb label it is shown. I will make a pull request soon.
