### ISSUE TITLE
spaces pretend to have their Hecke orbit in the database

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#700]
Every space of modular forms with character, like the ones listed at
/ModularForm/GL2/Q/holomorphic/17/4/
(except the last one, changed by hand) pretend to have their Hecke orbits stored in the database ('in_wdb'==1).
See also #698.

**Comment by AurelPage** [comment]
To be assigned to Stephan.

**Comment by davidfarmer** [comment]
Aurel will make a script to correct the in_wdb flag in the database

**Comment by AurelPage** [comment]
I now have a script that can do this, and that can probably be used by the import scripts. Should I run it to fix this issue?

**Comment by JohnCremona** [comment]
The script is now in the refactor branch (in a new separate file lmfdb/modular_forms/elliptic_modular_forms/backend/correct-in_wdb.py)

**Comment by AurelPage** [comment]
I have run the script in the range level <= 10, weight <= 10. You can see the changes for instance at
/ModularForm/GL2/Q/holomorphic/
and
/ModularForm/GL2/Q/holomorphic/10/9/?group=1

**Comment by AurelPage** [comment]
Should I run the script on the whole database of dimensions?

**Comment by sehlen** [comment]
Yes.

**Comment by AurelPage** [comment]
In progress.

**Comment by AurelPage** [comment]
The script has stopped because of a bug. I will work on it.
