### ISSUE TITLE
Distinguish between even and odd characters

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#702]
For a given weight, the space of cusp forms is automatically empty if the character
has the wrong parity.  But there are cases where it is 0 but that 0 is not forced by parity,
for example:
ModularForm/GL2/Q/holomorphic/11/2/

It would be nice to separate the characters by parity, so one could more easily see
the "interesting" empty spaces.

**Comment by AurelPage** [comment]
Other example where a 0 is not forced by parity: (5,4).

**Comment by fredstro** [comment]
I have made an addition to the table in the Gamma1 listing to show the parity of the characters. 
In addition I am running computations which adds this information to the database of dimensions to make it easier to fetch for this page.
See e.g.
ModularForm/GL2/Q/holomorphic/42/2/ 
ModularForm/GL2/Q/holomorphic/42/2/ 
ModularForm/GL2/Q/holomorphic/100/2/
have a look  at my and give me feedback

**Comment by davidfarmer** [comment]
What do you think of this:
then parity forces the dimension to be 0, the entries in the right column are grey instead of black?
(Black means there is nothing to click to, so this gives a bit more information.)

If you like that idea then I could implement it.

**Comment by fredstro** [comment]
I think that sounds good. 
In particular it is good that it makes it clear why some of the dimension 0 spaces can be clicked on and some not. 

Fredrik
