### ISSUE TITLE
Tamagawa numbers

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#703]
In the display of the Tamagawa numbers in 

http://beta.lmfdb.org/EllipticCurve/Q/13800u1

appears a star. This is probably to match the factorization of c_p for each prime p dividing the conductor, but this is not explained anywhere and look confusing. Maybe round brackets and only dots?

**Comment by JohnCremona** [comment]
I guess that is the explanation -- it was not me who wrote that and I have not tried git blame.  Th esuggestion is good, with brackets only when there is more than one bad prime, but we will have to see how something like

(1).(1).(1) 

looks (even with cdots).

**Comment by davidfarmer** [comment]
I think the suggestion was to only bracket when c_p is divisible
by more than one prime.  If N=660 = 2^2 3 5 11 then maybe it would
look like

1.(3.5).7^2.31

(I realize those numbers are unrealistic!)

**Comment by JohnCremona** [comment]
OK -- I have assigned it to myself though it is slightly off-topic for this week.

**Comment by JohnCremona** [comment]
Test cases:
1 bad prime, cp=1: EllipticCurve/Q/11a1
1 bad prime, cp prime: EllipticCurve/Q/121d1
1 bad prime, cp composite: EllipticCurve/Q/289a1
>1 bad prime, general: EllipticCurve/Q/13800u1

So far I have a working version but it puts prentheses around the factors for each bad prime even if that cp is a prime power.

**Comment by JohnCremona** [comment]
Fixed in https://github.com/JohnCremona/lmfdb/tree/tamagawa, no pull request until the next merging of refactor.

**Comment by JohnCremona** [comment]
Merged into master/beta branch
