### ISSUE TITLE
character 0 error message

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#709]
ModularForm/GL2/Q/holomorphic/120/12/0/  shows the error message "Please provide positive integer character number! You gave: 0" but still displays the page ModularForm/GL2/Q/holomorphic/120/12/.  I assume that is not intentional?

**Comment by fredstro** [comment]
This was intentional so that the user can see a list of characters which exist and they should choose from there. I find this more helpful than just an error message.

**Comment by fredstro** [comment]
If you have a better formulation though, feel free to change it.

**Comment by JohnCremona** [comment]
Suggestion:  Have just the error message, but expand it to say "Please provide positive integer character number! You gave: 0.  Valid values are: ..." followed by a list of the residues coprime to the level.  Or, just say "... Valid values are integers coprime to the level."

**Comment by JohnCremona** [comment]
Fixed in refactor branch
