### ISSUE TITLE
Gauss sum should display initially in Dirichlet char home page

### ISSUE THREAD

**Issue by jbalakrishnan** [LMFDB/lmfdb#71]
URL or blueprint/codefile: The home page of any Dirichlet character.

In order to see a Gauss, Jacobi, or Kloosterman sum, I have to click Compute or move a slider.

What should it be?

It would be better if values were displayed when the page first loads.
The default should be a=1 for the Gauss sum.  The default should not be
1,1 for Kloosterman sums, but 1,2 would be ok.

Also, the Jacobi sums are written as sums of roots of unity, but it
probably should be numerical, like the others.

**Comment by AndrewVSutherland** [comment]
I think the sliders should be removed; when the modulus is large they are pretty useless (see http://www.lmfdb.org/Character/Dirichlet/99999/2).  I took a quick look at automatically filling in the values when the page loads but I don't see an easy way to do it (I'm sure it can be done).

**Comment by pascalmolin** [comment]
I can do this. So remove slider (I agree, I used the jacobi sums recently
and never the slider) and place default input: 2 for jacobi and 1,1 for
kloosterman sounds reasonable.

Pascal

2016-07-11 16:14 GMT+02:00 Andrew Sutherland <notifications@github.com>:

**Comment by AndrewVSutherland** [comment]
@pascalmolin Thanks!  But let me merge PR 1703 before you create a new branch, it contains changes to some of the Character/Dirichlet files.
