### ISSUE TITLE
Space generated on click

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#713]
It looks like clicking on 
ModularForm/GL2/Q/holomorphic/11/4/5/
returns an error because the website is trying to compute the space .

**Comment by JohnCremona** [comment]
Same for ModularForm/GL2/Q/holomorphic/120/2/113 which is a direct link from ModularForm/GL2/Q/holomorphic/120/2/

**Comment by JohnCremona** [comment]
Fixed
