### ISSUE TITLE
Tidy up newform coefficients 

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#715]
e.g. ModularForm/GL2/Q/holomorphic/11/3/2/  where alpha_1 = zeta_10

**Comment by davidfarmer** [comment]
Need to do 2 things:  change the polynomial substitution code (I will do that)
and also change the field display on the modular forms page.

**Comment by sehlen** [comment]
I will add a property .only_cyclotomic to the WebModFormSpace class that will be true if all the coefficient fields are cyclotomic fields so that in this case, there should be no table of fields.

**Comment by davidfarmer** [comment]
I think we should also add more information about each form
in the orbit so that we can avoid the logic which is currently done
in the template.

**Comment by JohnCremona** [comment]
Closing but some similar issues remain, to be opened in a new Issue.
