### ISSUE TITLE
Complex embeddings of mf coeffs clash with Deligne bounds

### ISSUE THREAD

**Issue by nmascot** [LMFDB/lmfdb#719]
Accodring to 11/10/4/a/ , the coefficent a2 has complex embeddings with modulus >10^8. Since the weight is 10, this is not possible (should be at most 2^(5.5)<50)

**Comment by nmascot** [comment]
Same problem with 11/7/2/a/ .

**Comment by nmascot** [comment]
11/5/2/a/ is also clearly wrong, albeit in a different way.

**Comment by JohnCremona** [comment]
11/10/4/a/: the a2 values look OK to me now.  So does 11/7/2/a/ (though that one has a bad case of Issue #726).

What is the problem you see with 11/5/2/a/?  Is it possible that this issue could be closed?

**Comment by fredstro** [comment]
There is no problem now. 
The issue came from the fact we accidentally assigned coefficients with wrong index. I.e. it showed c(200) instead of c(2)  etc. some times. 
This issue can be closed now.
