### ISSUE TITLE
Wrong description of complex embeddings

### ISSUE THREAD

**Issue by nmascot** [LMFDB/lmfdb#720]
On the newform page, it says that:
"The different embeddings of the first few Fourier coefficients **that preserve the character** are shown in the table below."

The coefficients lie in an extension of a cyclotomic field; and the phrase "preserve the character" seems to imply that we only list embeddings that induce the identity on the cyclotomic field. In particular, the number of these embeddings should be the relative degree; however, it is the coefficient field.

We should either change the text or only display the embeddings that are compatible with the choice of character. I personally prefer the latter solution.

**Comment by nmascot** [comment]
Cf. /11/7/2/a/ for an example.

**Comment by sehlen** [comment]
I would prefer the latter, as well and you can assign me.
