### ISSUE TITLE
Missing password file

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#721]
For larger weight and level, save_to_db() is called and then fails because of missing file:
lmfdb/modular_forms/elliptic_modular_forms/password

An example what currently shows this behavior is
ModularForm/GL2/Q/holomorphic/120/12/7/

**Comment by davidfarmer** [comment]
See line 124 of lmfdb/modular_forms/elliptic_modular_forms/backend/web_character.py ,
which is disabled so that save_to_db() is not called.  A proper fix is still needed.

**Comment by JohnCremona** [comment]
I think that we should never store data in the database as a result of a one-off computation which happens while someone does a browse/search of an object which is then created on the fly.  Instead, we should run a separate script to create and store objects --offline and with access to the appropriate password.

Perhaps one way to achieve this would be to wrap the save_to_db() call in a try/except block and do nothing when it fails, as it will when run on the live website but not when run locally by someone with the right login credentials.

**Comment by fredstro** [comment]
I have added a try / except to the authentication method so if a .save_to_db() is attempted when you are not authenticated then this fails with a critical error message in the log. 
In normal usage nothing should be saved (and at the moment is isn't as far as I can tell). This should only happen when called by us when we generate new data. I will submit a pull request for this momentarily.

**Comment by davidfarmer** [comment]
When I go to that page it just says:

Unfortunately, we do not have this space in the database, yet.

which seems a reasonable response.
