### ISSUE TITLE
missing Satake parameters

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#723]
Compare this page, which has an empty table:
http://localhost:37777/ModularForm/GL2/Q/holomorphic/12/10/1/a/
to this page, which shows the Satake parameters for the first two good primes
http://localhost:37777/ModularForm/GL2/Q/holomorphic/12/12/1/a/

**Comment by fredstro** [comment]
This issue is fixed (although I don't know when that happened) and can be closed.

**Comment by davidfarmer** [comment]
On
http://localhost:37777/ModularForm/GL2/Q/holomorphic/12/10/1/a/
I get
RuntimeError: 'unicode' object has no attribute 'absolute_degree'

**Comment by fredstro** [comment]
This error is not at all related to the original issue with missing Satake parameters which should still be closed. 
The page works now after I recomputed the form, I don't know why it suddenly stopped working. I just started yet another attempt to re-compute all WebNewforms (and hopefully it manages to complete this time...)

**Comment by davidfarmer** [comment]
Closing (for both reasons)
