### ISSUE TITLE
Missing polynomial over Q

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#724]
For some reason the defining polynomial over Q is missing from this page:
ModularForm/GL2/Q/holomorphic/11/7/2/a/

Also, the knowl for minimal polynomial over Q should not be used for the relative minimal polynomial.

**Comment by sehlen** [comment]
There is a minimal polynomial on that page but it is very long and does not break.
However, the replacement seems to be broken again in this case:
<img width="445" alt="screen shot 2015-12-16 at 00 23 15" src="https://cloud.githubusercontent.com/assets/2471633/11891219/d16f3992-a55c-11e5-993e-fed9cba33c2e.png">

**Comment by davidfarmer** [comment]
The LaTeX problem in that image had been fixed: pull from Cremona's refactor.

But in the "Coefficient field" section it only shows that polynomial.  It is also supposed
to show the minimal polynomial over Q - as in other pages such as
 ModularForm/GL2/Q/holomorphic/11/5/2/a/

Both of the original comments refer to the "Coefficient field" section of the page.

**Comment by sehlen** [comment]
Oh, sorry. I forgot that Fredrik's refactor is not up-to-date.

**Comment by sanni85** [comment]
This issue was resolved in my pull request and it is already merged into beta.
It should be closed.
