### ISSUE TITLE
"No newforms" although space not empty

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#725]
On /ModularForm/GL2/Q/holomorphic/11/7/10/ I get the message "There are no newforms of this weight, level and character." although the dimension is 5, as shown on /ModularForm/GL2/Q/holomorphic/11/7/ (I checked that the dimension is indeed 5).

You can assign me and this is critical.

**Comment by davidfarmer** [comment]
This is supposed to be fixed by @AurelPage 's script.  Yesterday he ran it for weight and level
up to 10.  Maybe he can run it up to 12 to see if it fixes this particular issue?

**Comment by sehlen** [comment]
Oh, yes, I think you're right.

It would be great if he could run the script.
If not, I can have a look at it and also run the script in about an hour.

**Comment by AurelPage** [comment]
Yes, I think running the script would fix this. I am trying to do it, but at the moment the server is refusing my connections for some reason. I can't even run a local version of the website!

**Comment by AurelPage** [comment]
I was being silly. I have now run the script up to (12,12), which should have fixed this instance of #700.

**Comment by sehlen** [comment]
Ok, this makes the link not clickable -- good!

But actually, the issue here is (also) that the page for that space should
still say that it is not in the db and not that it is empty. So please
leave this issue open and assigned to me.

**Comment by AurelPage** [comment]
Oh, yes, that is right. Actually, I seem to remember that some other spaces that are now no longer clickable even produced a server error. I will try to find them and report them.

**Comment by AurelPage** [comment]
Other example: /ModularForm/GL2/Q/holomorphic/8/9/3/

**Comment by JohnCremona** [comment]
We can close this now -- 11/7/10 has dimension 5 but is not in the database; its page says this properly, and the 11/7 page gives the correct dimension and the space is not clickable.

**Comment by sehlen** [comment]
There were many more such cases and almost all of them are fixed now. It was/is a data issue that I fixed where it was possible for me.
I think it was/is fine to close the issue, though.
