### ISSUE TITLE
Allow defining polynomial to wrap

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#726]
When this page narrow, the defining polynomial is forced to be below the properties box:
ModularForm/GL2/Q/holomorphic/11/5/2/a/

**Comment by JohnCremona** [comment]
Currently (21/12/15) ModularForm/GL2/Q/holomorphic/11/5/2/a/ crashed on beta.  Fixing...

**Comment by davidfarmer** [comment]
After pulling upstream master (and John and Fredrik's refactor branches, which gave nothing new)
the page 
ModularForm/GL2/Q/holomorphic/11/5/2/a/
still fails for me.  The error is in
lmfdb/modular_forms/elliptic_modular_forms/backend/web_newforms.py
    line 541, in WebNewForm_cached
return M.hecke_orbits[label]
    KeyError: 'a'

Also, if I make the url shorter (ModularForm/GL2/Q/holomorphic/11/5/2/) then it also fails, with error
lmfdb/modular_forms/elliptic_modular_forms/views/emf_render_web_modform_space.py
    line 106, in set_info_for_modular_form_space
WMFS_rep = WebModFormSpace_cached(level = level, weight = weight, cuspidal=True, character = c.number(),update_from_db=true)
NameError: global name 'true' is not defined

Probably I am just missing some changes made in the past day as I travelled, but I have not been
able to unravel all the emails.

**Comment by JohnCremona** [comment]
Both those URLs work OK on beta (did you try that?) and for my local copy.

On the other hand, "update_from_db=true" should surely be
"update_from_db=True" and will cause trouble some time.

I put in a test (normally skipped) to load all pages of the form

ModularForm/GL2/Q/holomorphic/N/k/?group=i

for i=0, 1; 1<=N<=40; 2<=k<=20 (k even) to make sure those pages all load
without crashing, but without checking the page's contents.  Something
similar to loop over individual newforms spaces
like ModularForm/GL2/Q/holomorphic/11/5/2/a/
but that would take more effort: the character number should be in [1,N]
and coprime, though the others do not cause an error;  the form letter will
cause an error if out of range though (e.g. 11/5/2/b) so such a test would
have to know how far to go with each (N,K,chi) triple.

John

**Comment by davidfarmer** [comment]
They work fine on beta for me. 

It looks like I can't get to any modular forms on my local version.  This is after checking out master
and then pulling upstream master.

Not sure if these logging messages are relevant:
CRITICAL:emf@2015-12-22 09:27:02,380: record with key:{'version': 1.1, 'character': 1, 'weight': 8, 'level': 5} was not found! [web_object.py:611]

CRITICAL:emf@2015-12-22 09:25:06,454: record with key:{'version': 1.1, 'character': 1, 'weight': 12, 'level': 1} was not found! [web_object.py:611]

Could something have changed with the database access? Other objects seem okay.

**Comment by JohnCremona** [comment]
That is a mystery to me.  From my recently rebooted laptop and working from home with no privileged access that I can thing of, things work fine.  But when I open the URL ModularForm/GL2/Q/holomorphic/11/5/2/a/
I get a slightly different log message:

CRITICAL:emf@2015-12-22 14:44:01,116: record with key:{'version': 1.3, 'modulus': 11, 'number': 2} was not found! [web_object.py:611]

Note the different version number.  Fredrik will have to explain this.

On the plus side, the tests all pass when I run them on the lmfdb machine itself so this strangeness is not affecting that at least.

**Comment by davidfarmer** [comment]
I changed line   16   of
lmfdb/modular_forms//elliptic_modular_forms/__init__.py
to
    emf_version = 1.3
(so that I always use 1.3 for  emf_version) 
and it works for me now.

This has something to do with the sage version, but I don't understand what those
switches are doing.

**Comment by JohnCremona** [comment]
Those lines set the value of emf_version differently according to whether your sage version is at least 6.8 or not.   It must have been necessary for some transitional period.  By now we could just insist that we have at least 6.8 (or 6.9, or even 6.10 which was just released and runs our code jyst fine as I checked) .

**Comment by JohnCremona** [comment]
Fixed.
