### ISSUE TITLE
Defining level for Hilbert Modular form?

### ISSUE THREAD

**Issue by jbalakrishnan** [LMFDB/lmfdb#74]
http://www.lmfdb.org/ModularForm/GL2/?field_label=Qsqrt5

Reported by Ralf Schmidt:

Can there be an explanation of the meaning of the triples in the "Level" column? I could not figure out what they mean.

More here: https://code.google.com/p/lmfdb/issues/detail?id=79

**Comment by jvoight** [comment]
Asked Ralf:

With regards to:
  https://github.com/LMFDB/lmfdb/issues/74
what are you asking about?  The link in there no longer works.  Do you mean the labels for the ideals?

There is now a knowl
  http://beta.lmfdb.org/knowledge/show/mf.hilbert.level_norm
describing what a level means, which you can see at an individual form e.g.
  http://beta.lmfdb.org/ModularForm/GL2/TotallyReal/?label=2.2.5.1-31.1-a

JV

**Comment by jvoight** [comment]
The knowl for level was added some time ago; so I'm closing this.
