### ISSUE TITLE
Data spill on modular forms landing page

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#743]
On http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/, under the "Find a specific cusp form from the database" box there is currently the following text visible:

info:{'grouptype': 0, 'weight_range': '2-12', 'row_heads': [2, 4, 6, 8, 10, 12], 'level_range': '1-24', 'label': 'None', 'show_switch': True, 'table': {1: {2: {'in_db': 1, 'dim_new': 0}, 4: {'in_db': 1, 'dim_new': 0}, 6: {'in_db': 1, 'dim_new': 0}, 8: {'in_db': 1, 'dim_new': 0}, 10: {'in_db': 1, 'dim_new': 0}, 12: {'in_db': 1, 'dim_new': 1}}, 2: {2: {'in_db': 1, 'dim_new': 0}, 4: {'in_db': 1, 'dim_new': 0}, 6: {'in_db': 1, 'dim_new': 0}, 8: {'in_db': 1, 'dim_new': 1}, 10: {'in_db': 1, 'dim_new': 1}, 12: {'in_db': 1, 'dim_new': 0}}, 3: {2: {'in_db': 1, 'dim_new': 0}, 4: {'in_db': 1, 'dim_new': 0}, 6: {'in_db': 1, 'dim_new': 1}, 8: {'in_db': 1, 'dim_new': 1}, 10: {'in_db': 1, 'dim_new': 2}, 12: {'in_db': 1, 'dim_new': 1}}, 4: {2: {'in_db': 1, 'dim_new': 0}, 4: {'in_db': 1, 'dim_new': 0}, 6: {'in_db': 1, 'dim_new': 1}, 8: {'in_db': 1, 'dim_new': 0}, 10: {'in_db': 1, 'dim_new': 1}, 12: {'in_db': 1, 'dim_new': 1}}, 5: {2: {'in_db': 1, 'dim_new': 0}, 4: {'in_db': 1, 'dim_new': 1}, 6: {'in_db': 1, 'dim_new': 1}, 8: {'in_db': 1, 'dim_new': 3}, 10: {'in_db': 1, 'dim_new': 3}, 12: {'in_db': 1, 'dim_new': 3}}, 6: {2: {'in_db': 1, 'dim_new': 0}, 4: {'in_db': 1, 'dim_new': 1}, 6: {'in_db': 1, 'dim_new': 1}, 8: {'in_db': 1, 'dim_new': 1}, 10: {'in_db': 1, 'dim_new': 1}, 12: {'in_db': 1, 'dim_new': 3}}, 7: {2: {'in_db': 1, 'dim_new': 0}, 4: {'in_db': 1, 'dim_new': 1}, 6: {'in_db': 1, 'dim_new': 3}, 8: {'in_db': 1, 'dim_new': 3}, 10: {'in_db': 1, 'dim_new': 5}, 12: {'in_db': 1, 'dim_new': 5}}, 8: {2: {'in_db': 1, 'dim_new': 0}, 4: {'in_db': 1, 'dim_new': 1}, 6: {'in_db': 1, 'dim_new': 1}, 8: {'in_db': 1, 'dim_new': 2}, 10: {'in_db': 1, 'dim_new': 2}, 12: {'in_db': 1, 'dim_new': 3}}, 9: {2: {'in_db': 1, 'dim_new': 0}, 4: {'in_db': 1, 'dim_new': 1}, 6: {'in_db': 1, 'dim_new': 1}, 8: {'in_db': 1, 'dim_new': 3}, 10: {'in_db': 1, 'dim_new': 3}, 12: {'in_db': 1, 'dim_new': 4}}, 10: {2: {'in_db': 1, 'dim_new': 0}, 4: {'in_db': 1, 'dim_new': 1}, 6: {'in_db': 1, 'dim_new': 3}, 8: {'in_db': 1, 'dim_new': 1}, 10: {'in_db': 1, 'dim_new': 3}, 12: {'in_db': 1, 'dim_new': 5}}, 11: {2: {'in_db': 1, 'dim_new': 1}, 4: {'in_db': 1, 'dim_new': 2}, 6: {'in_db': 1, 'dim_new': 4}, 8: {'in_db': 1, 'dim_new': 6}, 10: {'in_db': 1, 'dim_new': 8}, 12: {'in_db': 1, 'dim_new': 8}}, 12: {2: {'in_db': 1, 'dim_new': 0}, 4: {'in_db': 1, 'dim_new': 1}, 6: {'in_db': 1, 'dim_new': 0}, 8: {'in_db': 1, 'dim_new': 2}, 10: {'in_db': 1, 'dim_new': 1}, 12: {'in_db': 1, 'dim_new': 2}}, 13: {2: {'in_db': 1, 'dim_new': 0}, 4: {'in_db': 1, 'dim_new': 3}, 6: {'in_db': 1, 'dim_new': 5}, 8: {'in_db': 1, 'dim_new': 7}, 10: {'in_db': 1, 'dim_new': 9}, 12: {'in_db': 1, 'dim_new': 11}}, 14: {2: {'in_db': 1, 'dim_new': 1}, 4: {'in_db': 1, 'dim_new': 2}, 6: {'in_db': 1, 'dim_new': 2}, 8: {'in_db': 1, 'dim_new': 4}, 10: {'in_db': 1, 'dim_new': 4}, 12: {'in_db': 1, 'dim_new': 6}}, 15: {2: {'in_db': 1, 'dim_new': 1}, 4: {'in_db': 1, 'dim_new': 2}, 6: {'in_db': 1, 'dim_new': 4}, 8: {'in_db': 1, 'dim_new': 4}, 10: {'in_db': 1, 'dim_new': 6}, 12: {'in_db': 1, 'dim_new': 8}}, 16: {2: {'in_db': 1, 'dim_new': 0}, 4: {'in_db': 1, 'dim_new': 1}, 6: {'in_db': 1, 'dim_new': 2}, 8: {'in_db': 1, 'dim_new': 3}, 10: {'in_db': 1, 'dim_new': 4}, 12: {'in_db': 1, 'dim_new': 5}}, 17: {2: {'in_db': 1, 'dim_new': 1}, 4: {'in_db': 1, 'dim_new': 4}, 6: {'in_db': 1, 'dim_new': 6}, 8: {'in_db': 1, 'dim_new': 10}, 10: {'in_db': 1, 'dim_new': 12}, 12: {'in_db': 1, 'dim_new': 14}}, 18: {2: {'in_db': 1, 'dim_new': 0}, 4: {'in_db': 1, 'dim_new': 1}, 6: {'in_db': 1, 'dim_new': 3}, 8: {'in_db': 1, 'dim_new': 2}, 10: {'in_db': 1, 'dim_new': 4}, 12: {'in_db': 1, 'dim_new': 5}}, 19: {2: {'in_db': 1, 'dim_new': 1}, 4: {'in_db': 1, 'dim_new': 4}, 6: {'in_db': 1, 'dim_new': 8}, 8: {'in_db': 1, 'dim_new': 10}, 10: {'in_db': 1, 'dim_new': 14}, 12: {'in_db': 1, 'dim_new': 16}}, 20: {2: {'in_db': 1, 'dim_new': 1}, 4: {'in_db': 1, 'dim_new': 1}, 6: {'in_db': 1, 'dim_new': 1}, 8: {'in_db': 1, 'dim_new': 3}, 10: {'in_db': 1, 'dim_new': 3}, 12: {'in_db': 1, 'dim_new': 3}}, 21: {2: {'in_db': 1, 'dim_new': 1}, 4: {'in_db': 1, 'dim_new': 4}, 6: {'in_db': 1, 'dim_new': 4}, 8: {'in_db': 1, 'dim_new': 8}, 10: {'in_db': 1, 'dim_new': 8}, 12: {'in_db': 1, 'dim_new': 12}}, 22: {2: {'in_db': 1, 'dim_new': 0}, 4: {'in_db': 1, 'dim_new': 3}, 6: {'in_db': 1, 'dim_new': 5}, 8: {'in_db': 1, 'dim_new': 5}, 10: {'in_db': 1, 'dim_new': 7}, 12: {'in_db': 1, 'dim_new': 11}}, 23: {2: {'in_db': 1, 'dim_new': 2}, 4: {'in_db': 1, 'dim_new': 5}, 6: {'in_db': 1, 'dim_new': 9}, 8: {'in_db': 1, 'dim_new': 13}, 10: {'in_db': 1, 'dim_new': 17}, 12: {'in_db': 1, 'dim_new': 19}}, 24: {2: {'in_db': 1, 'dim_new': 1}, 4: {'in_db': 1, 'dim_new': 1}, 6: {'in_db': 1, 'dim_new': 3}, 8: {'in_db': 0, 'dim_new': 3}, 10: {'in_db': 0, 'dim_new': 5}, 12: {'in_db': 1, 'dim_new': 5}}}, 'col_heads': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24], 'groupother': 1}

Presumably this is some internals getting rendered by mistake.

**Comment by davidfarmer** [comment]
I am fixing this

**Comment by JohnCremona** [comment]
Fixed.
