### ISSUE TITLE
classical MF properties box

### ISSUE THREAD

**Issue by alinabucur** [LMFDB/lmfdb#744]
http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/13/4/4/b/

The properties box has a "-" for Twist Info, but nothing for "CM":

Twist info	  - Is minimal
CM info	  Is not a CM-form

They should be formatted the same.

**Comment by davidfarmer** [comment]
I am fixing this

**Comment by JohnCremona** [comment]
Fixed.
