### ISSUE TITLE
Role of Fricke involution in functional equation of GL(2) cusp form

### ISSUE THREAD

**Issue by jbalakrishnan** [LMFDB/lmfdb#75]
http://www.lmfdb.org/L/degree2/CuspForm/

Reported by Ralf Schmidt:

On this page, it is implied, but not stated, that f is an eigenfunction. But isn't there a Fricke involution missing on the right side of the functional equation? (See, for example, Corollary 4.3.7 of Miyake's book.) If f is assumed to be an eigenfunction for the Fricke involution, with the \epsilon absorbing the eigenvalue, this should be stated (for example, it would imply that \chi is quadratic).

More here: https://code.google.com/p/lmfdb/issues/detail?id=83

**Comment by nmascot** [comment]
Seems fixed now (on Fredrik's refactor branch). Should this thread be closed ?

**Comment by davidfarmer** [comment]
Need to say that $f$ is a newform, and describe the sign as a function of the weight and the
Fricke involution.

**Comment by davidfarmer** [comment]
Fixed in Fredrik's refactor branch
