### ISSUE TITLE
Broken API

### ISSUE THREAD

**Issue by pdehaye** [LMFDB/lmfdb#754]
One of the guys from Bremen who is part of OpenDreamKit signals the elliptic curve API is broken. We have sort of started relying on the API as we build a prototype for the StAndrews workshop, so this is mildly annoying.

For example, http://www.lmfdb.org/api/elliptic_curves/curves gives an error: 

           The page you are looking for has produced a server error.

**Comment by davidfarmer** [comment]
Try it at beta.lmfdb.org

**Comment by jwj61** [comment]
I just replied to him.  It looks like the api links generally to
www.lmfdb.org are broken, but the ones to beta work.  Until we get it
sorted out, you can use beta.

John

**Comment by pdehaye** [comment]
thanks for the quick response!

**Comment by JohnCremona** [comment]
Please remember that both lmfdb.org websites are in a temporary state at
the moment while Jon B and I sort out some filesystem and backup issues on
the Warwick machine.  I hope to get things back to normal before the odk
workshop starts next Monday.

John

**Comment by JohnCremona** [comment]
It works fine now.
