### ISSUE TITLE
Giving some values of a(p)

### ISSUE THREAD

**Issue by jbalakrishnan** [LMFDB/lmfdb#76]
Reported by Ralf Schmidt:

On a page like this: http://www.lmfdb.org/L/ModularForm/GL2/Q/holomorphic/5/10/0/b/1/ is it true that a(p)=\pm p^{-1/2} for p=2 and p=3? If so, could this be stated somewhere, for the sake of being explicit? I suppose the sign \pm can be read off the Atkin-Lehner eigenvalues from this page: http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/6/6/0/a/, namely a(2)=2^{-1/2} and a(3)=-3^{-1/2}, but it would be nice not to have to think about the relation between AL eigenvalues and the sign of a(p).

**Comment by jvoight** [comment]
The links above no longer work (new indexes), and classical modular forms are greatly enhanced.  I am closing this issue, but I hope Ralf will re-complain.  (I emailed him to make sure.)
