### ISSUE TITLE
Checklist page

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#766]
the checklist page is producing a server error:

http://beta.lmfdb.org/checklist

**Comment by JohnCremona** [comment]
When run locally in debug mode the error is more explicit:
BuildError: Could not build url for endpoint 'artin_representations.by_data' with values ['conductor', 'dim', 'index']. Did you mean 'artin_representations.by_partial_data' instead?

I have fixed the problems, see pull request #774
