### ISSUE TITLE
Weight 24 classical modular form error

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#767]
http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/24/4/1/a/

gives an error.  This is a link from

http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/24/4/1/

which is a link from

http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/24/4

**Comment by JohnCremona** [comment]
Fixed by #768
