### ISSUE TITLE
Some CM forms do not display the CM field

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#769]
This modular form

http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/32/2/1/a/

is reported to be CM (correctly, I believe) but the CM field is not listed anywhere on the page. By contrast, this field

http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/14/4/1/a/

is reported to be CM and also lists the CM field Q(sqrt(-7)).

**Comment by JohnCremona** [comment]
Looking at the code, this would happen if the WNF object created by
WNF = WebNewForm_cached(level=level, weight=weight, character=character, label=label)
has 
WNF._cm_values = {}
WNF.is_cm = 1
WNF.cm_disc = 0
so somewhere it is determined that the form has CM but not what the discriminant is.

**Comment by fredstro** [comment]
This is due to a previous bug in the code which generated the data and checked for cm but forgot to set the .cm_disc property. 
I will start to  rerun the code and update this property...
But for a larger scale rerun (and even first instance run) we still need to resolve the storage issue...

**Comment by fredstro** [comment]
Since this issue was data-related and the mentioned problematic examples are now re-computed and display correctly (see also the already merged pull request nr. 814) I think this issue should be closed.

**Comment by kedlaya** [comment]
Agreed.
