### ISSUE TITLE
Be consistent with GL(2) vs GL_2?

### ISSUE THREAD

**Issue by jbalakrishnan** [LMFDB/lmfdb#77]
Should we consistently use one of GL(2) or GL_2 (and similarly for SL, Sp, etc.)?

More here: https://code.google.com/p/lmfdb/issues/detail?id=85

**Comment by JohnCremona** [comment]
I just searched for GL_ and SL_ and found that there are now 7 instances on GL_2 in the genus 2 curve pages (3 in html and 4 in python files), all in the pahrse "[not ] of GL_2-type".   In this usage I have _never_ seen "of GL(2)-type".
So consistency with this usage does not actually mean that we cannot use both, only that we use them correctly!

**Comment by haraldschilly** [comment]
different communities have different conventions -> would cause confusion … :angry:
