### ISSUE TITLE
Genus 2 curve search ST group dropdown list has typo: C{2,1} should be C_{2,1}

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#770]
The ST group "C_{2,1}" is mislabeled "C{2,1}" in the dropdown list in the genus 2 curve search pages.

There are currently no genus 2 curves in the database with this ST group, but if there were, the search would not be able to find them.

**Comment by JohnCremona** [comment]
Fixed (by editing the file directly on github; no pull request).
