### ISSUE TITLE
Typo on HMF search page

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#771]
Here's an easy one...

On a Hilbert modular form search results page, e.g.,

http://www.lmfdb.org/ModularForm/GL2/TotallyReal/?field_label=2.2.5.1

there is a button labeled "Refine of change search". That "of" should be "or".

**Comment by JohnCremona** [comment]
Oops, one of mine I fear.   I'lltry to fix these HMF issues tomorrow.

**Comment by JohnCremona** [comment]
Fixed (corrected directly on github so no pull request).
