### ISSUE TITLE
Classical MF of odd weight

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#772]
At one point, LMFDB contained data about some modular forms of odd weight (and necessarily nontrivial Nebentype); I tried to reference a few examples in a paper, but the data has since disappeared. Is there any plan to bring it back in some form?

**Comment by fredstro** [comment]
Exactly what data are you referring to? 
We don't really make any difference between odd and even weight (>= 2). 
The only thing is that it is more difficult to browse them since you have to choose Gamma1 instead of Gamma0 in the browsing page.

**Comment by kedlaya** [comment]
I was looking for an example of weight 3 and level 27, but I gather the level cutoff got reduced below this at some point. So I guess this isn't actually a separate issue from the general issues about raising the cutoffs; this ticket can be closed.
