### ISSUE TITLE
Sage / Magma/ pari code for elliptic curves over number fields

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#777]
Just as we have over Q.

**Comment by JohnCremona** [comment]
This is implemented now in my ecnf-code branch (https://github.com/JohnCremona/lmfdb/tree/ecnf-code) but no pull request yet since the formatting needs tweaking.

**Comment by JohnCremona** [comment]
This is Pull Request #835

**Comment by AurelPage** [comment]
The pull request has been merged, should this ticket be closed? Or do we also want gp code (I can do it)?

**Comment by JohnCremona** [comment]
If you can add gp code for some or all, then please do.  I did not know how
much  was possible.  Thanks.

**Comment by AurelPage** [comment]
Ok I will have a look at it.

**Comment by AurelPage** [comment]
This is fixed by #888.
