### ISSUE TITLE
Add friends for Saito-Kurokawa lifts

### ISSUE THREAD

**Issue by jbalakrishnan** [LMFDB/lmfdb#78]
From Ralf Schmidt:

When showing a Maass (=Saito-Kurokawa) lift like http://www.lmfdb.org/ModularForm/GSp/Q/Sp4Z/specimen/22/Maass, it would be natural to link to the elliptic modular form of which this is a Saito-Kurokawa lift. Conversely, elliptic modular forms could link to the SK-lifts they produce.

If this is a good idea and cannot be done right away, maybe add to the roadmap(s)?

**Comment by AndrewVSutherland** [comment]
The URL above no longer works, but I think the page that is being referred to is this one:

    https://beta.lmfdb.org/ModularForm/GSp/Q/Sp4Z.22_Maass/

**Comment by assaferan** [comment]
Seems to me to be the same as issue #960?

**Comment by AndrewVSutherland** [comment]
Agreed
