### ISSUE TITLE
Elliptic curve/modular form mismatch?

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#788]
From the elliptic curve over Q

http://beta.lmfdb.org/EllipticCurve/Q/1147/b/1

the link to the modular form says we don't have that space.  Maybe just missing data, but from the isogeny class

http://beta.lmfdb.org/EllipticCurve/Q/1147/b/

the friend link to the modular form gives an error.

**Comment by JohnCremona** [comment]
The isogeny class link is wrong: http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/1147/2/0/b/ should be http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/1147/2/1/b/.
I'll fix this easily (but not right away).

**Comment by JohnCremona** [comment]
Fixed by PR#789
