### ISSUE TITLE
Speed up loading of isogeny class web pages

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#793]
Currently loading the web page of an isogeny class of elliptic curves (over number fields) is much slower than it need be (reported by William Stein).  Try http://www.lmfdb.org/EllipticCurve/4.4.2304.1/1.1/a/ for example.  It can be sped up by not creating any number field or elliptic curve objects.  Work in progress.

**Comment by JohnCremona** [comment]
Pull request #794 does the job.

**Comment by jwj61** [comment]
pull request merged
