### ISSUE TITLE
Server error 3/6/1/a/

### ISSUE THREAD

**Issue by fredstro** [LMFDB/lmfdb#815]
The page:
ModularForm/GL2/Q/holomorphic/3/6/1/a/
currently gives a server error.
I will try to fix the underlying error as well as see where/if this should have been caught at a higher level...

**Comment by kedlaya** [comment]
I get a similar error for the Delta function: http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/1/12/1/a/

**Comment by am-github** [comment]
Also for ModularForm/GL2/Q/holomorphic/2/8/1/a/

**Comment by fredstro** [comment]
I know now what is wrong but not how it went wrong...
The forms with labels: '1.12.1a', u'2.8.1a', u'3.18.1b', u'3.8.1a', u'7.8.1a' do not have a 'filesystem' record associated with them (the way our modular forms are stored is that they have one part in a normal mongodb dictionary and one part in a gridfs binary file.
For some reason the non-existing file system data makes it so that the coefficient field is not set. 
By simply recomputing this data everything should work but this should be implemented  in a more stable way.

I am also uncertain as to why these records disappeared from the database. The only "reasonable" explanation is that the update procedure "save_to_db" (property of a WebObject) fails after deleting an old record and before inserting a new one. 
Or possibly the actual insertion of the new record fails. This can happen for instance because the record is too large...

**Comment by fredstro** [comment]
The missing forms are now all recomputed. 
It might be good to add a data-check to the testing for modular forms, i.e. add a test of the form:
assert [x for x in F._collection.distinct('hecke_orbit_label') if F._file_collection.find({'hecke_orbit_label':x}).count()==0] == []
Here F is a WebNewForm which has the ._collection and ._file_collection properties set to the appropriate mongodb collections.
