### ISSUE TITLE
Space exists, but can't navigate to it

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#834]
this page, mentioned in issue #719 

ModularForm/GL2/Q/holomorphic/11/10/4/a/

is working properly now, but if I click on level 11 weight 10 on the navigation page

http://localhost:37777/ModularForm/GL2/Q/holomorphic/ranges/?group=1&&level=1-24&weight=2-12

to get to
ModularForm/GL2/Q/holomorphic/11/10/?group=1
then there is no link to that space/form.

**Comment by fredstro** [comment]
The link is there now so this can be closed.
