### ISSUE TITLE
Knowls to replace

### ISSUE THREAD

**Issue by am-github** [LMFDB/lmfdb#841]
[new_identifiers.xlsx](https://github.com/LMFDB/lmfdb/files/187868/new_identifiers.xlsx)

I have changed the identifiers specified in the xlsx file. 

We need to find all the references for the old versions and replace them with the new versions.

**Comment by steffenmueller** [comment]
mf.sl2z.subgroup.ellipticfxpts should also be changed to group.sl2z.subgroup.ellipticfxpts

**Comment by am-github** [comment]
I can't find a knowl with the identifier 'mf.sl2z.subgroup.elliptic' on the page.

**Comment by jenpaulhus** [comment]
The Elliptic Fixed Point knowl is referenced on this file:
/modular_forms/elliptic_modular_forms/views/templates/geometric.html

**Comment by am-github** [comment]
I (think I) replaced all of them in the knowl contents.
