### ISSUE TITLE
knowl content

### ISSUE THREAD

**Issue by am-github** [LMFDB/lmfdb#846]
Do we need to fill in 'riemann.stieltjes.cn', or should it be deleted? @jwbober 

'mf.elliptic.dimension_galois_orbit' and 'mf.elliptic.hecke-orbit-dimension' have the same name and redundant content.

'dq.nf.extent' displays an error. @jwj61 

'ec.minimal_discriminant.order' has no content.

'mf.siegel.yoshida_lift' has no content @alinabucur

**Comment by jwj61** [comment]
dq.nf.extent is fixed
