### ISSUE TITLE
Authorless knowls

### ISSUE THREAD

**Issue by alinabucur** [LMFDB/lmfdb#850]
the knowl content.news should not have any authors. It will get changed often (if kept at all) by different people. 

Please make a special subclass of knowls that do not have authors. If technically feasible, we might want to restrict the power to create such knowls to the people who have higher level of access to the lmfdb. But we want lots of people to be able to edit this specific knowl.

**Comment by roed314** [comment]
Is this still a desired feature?  We didn't add it in the knowls revision.

**Comment by AndrewVSutherland** [comment]
I don't think this is necessary.  Anyone who is logged in can edit this knowl (as has always been the case), and we do not want to allow edits anymore broadly than that.  Any knowl editor who does not want to be listed as an author now has the ability to remove their name.
