### ISSUE TITLE
Downloading all stored data doesn't work for genus 2 curves (and is inconsistent)

### ISSUE THREAD

**Issue by steffenmueller** [LMFDB/lmfdb#856]
Sometimes trying to download all stored data for a genus 2 curves will lead to "The page you are looking for does not exist.", e.g. for [Genus2Curve/Q/169/a/169/1](http://beta.lmfdb.org/Genus2Curve/Q/169/a/169/1). But sometimes you get sent to Genus2Curve/Q/, e.g. for [Genus2Curve/Q/113959.a.113959.1](http://beta.lmfdb.org/Genus2Curve/Q/113959.a.113959.1).

**Comment by jvoight** [comment]
Whoever deals with this should also decide if #428 can be solved at the same time.
