### ISSUE TITLE
Remove datatables from Dirichlet characters?

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#862]
I think Dirichlet characters is the only place which uses datatables, the javascript based tables paging thing.  While it is cool, it is visually inconsistent with the rest of the site, so maybe it should be converted to more conventional lmfdb paging.

**Comment by AndrewVSutherland** [comment]
I presume you mean tables like these?

http://www.lmfdb.org/Character/Dirichlet/?modbrowse=1-20
http://www.lmfdb.org/Character/Dirichlet/?condbrowse=1-20
http://www.lmfdb.org/Character/Dirichlet/?ordbrowse=1-20

They don't strike me as horribly inconsistent.  Or were you referring to something else?

**Comment by pascalmolin** [comment]
I proposed a search result page instead last workshop, but people prefered
these tables.

2016-07-11 16:29 GMT+02:00 Andrew Sutherland <notifications@github.com>:

**Comment by AndrewVSutherland** [comment]
I'm fine with keeping the tables as they are, so unless there is a consensus to change them I would suggest we leave them as is and close this issue.  But I'll give @jwj61 and others a chance to chime in before doing so.

**Comment by davidfarmer** [comment]
I don't think there is any reason to change how those pages appear.

I suspect that the only point of the issue was the use of

/static/jquery.dataTables.js

The point being that those are not used elsewhere.

Us experts need to keep in mind that we are not the audience
for that page.  That is why it would be bad to change to a
search result page.

If there is a problem that experts want to search, and searching
is not working adequately for them, then that is a separate problem.

**Comment by jwj61** [comment]
As stated before, this is a question of design philosophy.  A basic design principle is to make things consistent unless there is a good reason not to.  In effect, if you think these search result pages should be different, you should have some reasons why they should have a different look.  

Alternatively we could decide all search result pages should use this look.  Before putting lots of time into trying that, be aware that the last time we tried it elsewhere, people didn't like how they acted with a large search result (200000 items in the search result table).

**Comment by AndrewVSutherland** [comment]
@jwj61 In the current implementation dataTables are no longer used to render search results, these are rendered in the standard way, see

http://www.lmfdb.org/Character/Dirichlet/?modulus=&conductor=&order=&search=1&limit=25

for example.  Datatables are used only to display tables, and these tables are not all that different looking from those used elsewhere in the LMFDB, for example:

http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/
http://www.lmfdb.org/ModularForm/GSp/Q/Sp4Z_j/

I don't see a major design difference, the only real difference is the style of the table (which doesn't look all that different to me; it does use color to distinguish primitive/imprimitive, but there are other places where we use color similarly, e.g. in L-function plots).

I don't think the debate is DataTables versus search results, rather it is dataTables versus html tables that use the "ntdata" class (as used in the two examples above).

 I don't have a strong opinion about this either way, my only objective in commenting here is too move the discussion along so we can either agree on an action to take or close the issue.

**Comment by davidfarmer** [comment]
Let's close it.  Nothing to be gained for the user, and little
to be gained in code improvements.

**Comment by jwj61** [comment]
I see.  My reply yesterday was made quickly while on the road, so I didn't see which pages were at issue.  I looks like my initial issue was resovled, so I am closing it.
