### ISSUE TITLE
Determine planned extent of classical modular forms

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#873]
Change the ranges in issues #448, #450, and #451 to something reasonable, and make
a similar decision for very small weight and very small level.  Then describe the available data in
a data extent knowl.

**Comment by davidfarmer** [comment]
The "critical" label was removed because we now have a data extent knowl at the top of
/ModularForm/GL2/Q/holomorphic/

**Comment by AndrewVSutherland** [comment]
The critical label has been added back because the data extent knowl (displayed on the top of http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/) does not agree with the data.

Once it does we can close this issue but until it does I think it is crtical.

I don't think we need to keep issues #448, #450, and #451 open; if someone wants to create a new issue labeled as a feature request with a desired range of classical modular forms, that's fine, but it probably makes sense to wait until this issue is addressed.

**Comment by davidfarmer** [comment]
I am okay with closing #448, #450, and #451.

The data extent knowl explains what we have, and later someone may wish
to specifically propose another rectangle (such as a rectangle for
real characters).

**Comment by AndrewVSutherland** [comment]
We have made some good forward progress.  With #1376 closed, we now have complete data for all the spaces with trivial character in the ranges (k,N) in [2,40] x [1,24] and (k,N) in [2,12] x [1,100] (in fact we also have (k,N) in [2,40] x {25}, which is beyond the extent listed in the knowl -- I will update it).  It remains to address the spaces with non-trivial character.  I note that for N=41 both k=5 and k=7 are definitely missing, and the completeness (and correctness) of the remaining data still needs to be verified (this is #1248).

**Comment by sehlen** [comment]
Actually, it is [2, 40] x [2, 25]. It's very easy to extend that but next
week we'll concentrate on fixing non-trivial character data.

**Comment by sehlen** [comment]
I meant  [2, 40] x [1, 25]. Will extend this soon.

**Comment by AndrewVSutherland** [comment]
@sehlen, right I actually updated the knowl earlier to reflect the expanded range.  But I agree that we should focus on completing/fixing the non-trivial character data before extending it further.

**Comment by AndrewVSutherland** [comment]
I extended the range of pages tested by emf_test_pages.py to include (k,N) = [2,12] x [1,100] and found a problem with k=12 and N=83, see https://github.com/LMFDB/lmfdb/issues/1248#issuecomment-220830840.

**Comment by AndrewVSutherland** [comment]
There are still many holes, even for trivial character, e.g. http://www.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/17/6/1/.

Several of these show up in the flasklog on the cloud server, and the pattern suggests that it is people (not robots) clicking on them.

**Comment by AndrewVSutherland** [comment]
Addressed by #2717, see http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/Completeness.
