### ISSUE TITLE
Elliptic curve shows wrong modular form label

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#877]
The elliptic curve page http://beta.lmfdb.org/EllipticCurve/Q/37/a/1 correctly links to the modular form http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/37/2/1/a/, but the text of the link is "Modular form 37.2a" instead of "Modular form 37.2.1a".

**Comment by JohnCremona** [comment]
Ok, I'll fix that when I get back to Bristol

**Comment by JohnCremona** [comment]
OK, I made the MF label by replacing "." by ".2" and it should be ".2.1"
