### ISSUE TITLE
Error in display text for mod p Galois images of CM elliptic curves over Q 

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#878]
When displaying Galois image data for CM elliptic curves over Q the display page currently notes:

"The mod p Galois representations of an elliptic curve with Complex Multiplication are non-surjective for all primes p. We only show the image for primes p≤37."

This is not true for p=2.  Change "primes" to "odd primes"

**Comment by JohnCremona** [comment]
Working on it.
