### ISSUE TITLE
Lattices isometry testing

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#882]
Searching for lattice through the Gram matrix should return results if an isometric lattice is entered.
For example searching for Gram matrices  [1,1,2] or [5,3,2] should return the entry for [1,0,1].

**Comment by jvoight** [comment]
Not isometry testing, but reduction theory, right?  You should assume a (canonical) Minkowski-reduced form of the Gram matrix, and when given input it should probably first reduce it and then search.
