### ISSUE TITLE
rename knowls for subgroups

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#887]
mf.sl2.subgroup.gamma0n
should be
group.sl2z.subgroup.gamma0  (or something like that)

Similarly for
mf.siegel.group.gamma0

This involves making a new knowl with the proper id, and changing all references to the old id.

**Comment by nmascot** [comment]
Working on it

**Comment by JohnCremona** [comment]
I checked that all references to the old knowls were gone.  I found one occurrence of mf.sl2z.subgroup.ellipticfxpts  but could not create a page which showed it.  Was it intended that this one should be changed too?

**Comment by davidfarmer** [comment]
Yes that shoudl be changed, perhaps by eliminating the knowl link
instead of changing the referenced label.

**Comment by davidfarmer** [comment]
fixed
