### ISSUE TITLE
Count

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#893]
Each time that there is a 
_Maximum number of curves to display_ or
_Maximum number of fields to display_
like in http://beta.lmfdb.org/Genus2Curve/Q/ or /EllipticCurve/Q/ or /NumberField/
if a wrong input is given, e.g. hello instead of a positive integer, search results are displayed.

**Comment by davidfarmer** [comment]
Revisit after David Roe's pending pull request.

**Comment by sanni85** [comment]
David's pull request do not solve the issue.

**Comment by adeines** [comment]
As of now this appears to be fixed.  :)
