### ISSUE TITLE
Hilbert modular forms parsing labels

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#902]
Labels for Hilbert modular forms should be handled when given as input.
If you copy paste the one in the example and add a space or write a wrong label, the page displayed is not helpful.

**Comment by jvoight** [comment]
Sorry, what do you mean by this?

**Comment by sanni85** [comment]
This is fixed in pull request #926 

now if you enter a correct label, or a correct label with lots of spaces, or a wrong label you get redirected in the right way.
