### ISSUE TITLE
Tests for HMF

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#927]
There is no test for HMF.

**Comment by jvoight** [comment]
These are just to ensure that certain standard spaces work, right?  Then anyone can do this who has done some tests before, or I will if it lingers.

**Comment by JohnCremona** [comment]
I noticed this just now too.  Perhaps we can ask Nicolas, he knows what to
do.

**Comment by AurelPage** [comment]
Working on it.

**Comment by AurelPage** [comment]
I suppose this can be closed.
