### ISSUE TITLE
Characters of unknown parity

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#936]
This page has characters whose parity is n/a:

http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/42/3/?group=1

**Comment by fredstro** [comment]
At the moment the page above does not display this but the page:
ModularForm/GL2/Q/holomorphic/99/3/?group=1
does. I will see what I can do about this over the weekend... 
But I also think that someone (maybe Pascal) said that it would be possible to write a function which determine if a character is even or odd directly from the number so if someone can do that that would be even better then we could just call that function instead.

**Comment by JohnCremona** [comment]
Agreed!  
I notice that the page for all Dirichlet chars of a given modulus (e.g. http://beta.lmfdb.org/Character/Dirichlet/42) does not show parities as such (they are in the last column!) , but the page for any individual one does.
Sine showing all characters for a given modulus is already computing the value at -1, surely a page such as http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/42/3/?group=1 which shows the same characters could do also?  Perhaps I am missing the point.

**Comment by fredstro** [comment]
I have fixed it now by calling the class ConreyCharacter from WebCharacter.py. I will make a pull request soon.

**Comment by jwj61** [comment]
fixed by pull request #1113
