### ISSUE TITLE
L-function of an elliptic curve over a number field appears as HMF L-function

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#945]
Even though these objects have the same L-function, the information on the page, like the title, should reflect where the person came from.  So, if you click on the friend link from an  elliptic curve over a quadratic field, the page should say it is the L-function of said elliptic curve

**Comment by jvoight** [comment]
Agreed.  As a matter of fact, L-function pages for ecnfs are much easier to generate in the sense that the Hecke eigenvalues can be computed by counting points (much easier than computing them from the HMF).  At some point when the L-function pages are served from the database, there will be two databases (one for ecnfs and one for HMFs)...

**Comment by edgarcosta** [comment]
This can be closed (as this does not occur for higher degrees, as we have disabled them)
