### ISSUE TITLE
Broken links at a Siegel modular forms page

### ISSUE THREAD

**Issue by jshurman** [LMFDB/lmfdb#947]
At the page

 http://beta.lmfdb.org/ModularForm/GSp/Q/Gamma0_2/

(1) The knowl-link for \Gamma_0(2) points to an out-of-date address, twice.
(2) The links to X, Y, Z, K, and \chi_{19} don't work.
(3) Two references to "work of Ibukiyama" must be cut-and-paste artifacts.  The MR link correctly points to the  paper of Igusa:

 Igusa, Jun-ichi On Siegel modular forms of genus two. Amer. J. Math. 84 1962 175–200.

(4) Here and at several other pages (which I will provide separately), it ends with "The ideal of cusp forms is ..??..."

**Comment by davidfarmer** [comment]
I'll take care of (1) and (2), and maybe (4).
