### ISSUE TITLE
crash: Sym^2 L-function of CM curves

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#956]
Sym^2 L-function of CM curves crashes.

/L/SymmetricPower/2/EllipticCurve/Q/32.a/
or click Symmetric square L-function on /EllipticCurve/Q/32/a/3

See also /roadmap: Recognize non-primitive L-functions and provide links to the primitive components. (sym^2 of CM curves, Dedekind zeta-function in the nonabelian case, etc)

**Comment by davidfarmer** [comment]
There is a message given:

This Elliptic curve has complex multiplication and the symmetric power of 
its L-function is then not primitive. This has not yet been implemented

which should be shown, and not crash the page.

**Comment by JohnCremona** [comment]
I will leave out the symmetric power links for CM curves.

**Comment by JohnCremona** [comment]
This is fixed in PR #980
