### ISSUE TITLE
include other databases of elliptic curves

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#963]
From /roadmap: Add the much larger Stein-Watkins database, which includes curves with larger conductor.  This would not be complete.  Currently we do not have as much data about all the Stein-Watkins curves as for those in the Cremona database: for example we do not have generators for all the curve of rank 1.  Also Mike Bennett's 2015 data, Randall Rathbun's data on congruent number curves for parameters up to 1000000.

**Comment by jvoight** [comment]
(There are also more recent databases of curves of bounded height [http://arxiv.org/abs/1602.01894].)

**Comment by JohnCremona** [comment]
We now (Feb 2021) have some of these: prime conductors to 10^6 (with 10^7 or 10^8 to follow) from Stein-Watkins + Bennet-Gherga-Rechnitzer, and 7-smooth from Matschke.  We (managing editors) decided not to include n-smooth for n>7, and not to include Rathbun's congruent number curves up to parameter 10^6 (for which he has generators i all but a small number of cases).

Once I get i the prime conductors to 10^8 I will be inclined to close this issue.

**Comment by roed314** [comment]
What's the status on prime conductors up to 10^8?

**Comment by roed314** [comment]
We may also want to close this in favor of #5041.

**Comment by AndrewVSutherland** [comment]
We have all the data from [Stein-Watkins](https://wstein.org/papers/stein-watkins/), the [BHKSSW](http://arxiv.org/abs/1602.01894) database of curves ordered by height, and the curves of prime conductor up to $$2\times 10^9$$ computed by [Bennett-Gherga-Rechnitzer](https://www.ams.org/journals/mcom/2019-88-317/S0025-5718-2018-03370-1/).  These should be added as auxiliary datasets people can download, as with zeta zeros and class group data (these datasets are quite large, we don't want to add them all to `ec_curvedata`).  We may want to add a subset of them (e.g. prime conductor up to $$10^8$$) to the LMFDB proper, and then it is just a question of computing all the associated data (perhaps @JohnCremona can say something about this).

In terms of adding these auxiliary datasets, the main work to be done is creating a UI to download subsets of them, we don't just want to post a link to a single 100GB+ file, as well as an explanation of the format, along the lines of what we 
 do for [class groups of imaginary quadratic fields](https://www.lmfdb.org/NumberField/QuadraticImaginaryClassGroups).

**Comment by AndrewVSutherland** [comment]
Isn't this issue essentially the same as #5041 ?  Should we close this?

**Comment by roed314** [comment]
I think so, but we might as well wait until @JohnCremona is awake and can comment.

**Comment by JohnCremona** [comment]
> What's the status on prime conductors up to 10^8?

We already have prime conductors up to 3*10^8 (see https://www.lmfdb.org/EllipticCurve/Q/Completeness) so I am closing this and moving on to #5041
