### ISSUE TITLE
show a graph of characters above and below

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#968]
From /roadmap: show a graph of characters above and below (parents and sons).

**Comment by AurelPage** [comment]
(not sure what this means)

**Comment by edgarcosta** [comment]
Maybe the thing we could do is to add a search by primitive character, as we do in CMFs, which would provide a way to search for "parents."

**Comment by AndrewVSutherland** [comment]
This would be very easy to add (just search for matches on `conductor` and `primitive_orbit`).  I think we should just implement this and then close this issue.
