### ISSUE TITLE
Add plots to all Maass form pages

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#983]
From /roadmap: Add plots of the Maass form in the fundamental domain.

**Comment by fredstro** [comment]
Some of the Maass forms already have plots. 
Somehow someone formatted the image wrongly with css and this made all plots except level 1 to display badly (the interesting parts landed outside the page).
I will submit a pull request where I fixe these display problems shortly.

**Comment by JohnCremona** [comment]
The pull request which fixes the issue has been merged.  This could be closed, or left open until all the relevant plots have been computed and added: currently the graph is shown when already computed, otherwise not.

**Comment by davidfarmer** [comment]
This work is underway, and this old issue is not helping, so am closing it.
