### ISSUE TITLE
Maass forms: display all results of search

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#985]
From /roadmap: Fix the search so that it is also done with server-side dataTables so we can remove the limit of 500 records (currently the client crash if we return more records)

**Comment by AurelPage** [comment]
Not sure if this is up-to-date.

**Comment by AndrewVSutherland** [comment]
The Maass form search results pages should be changed to work like other search results pages in the LMFDB (e.g. elliptic curves, number fields, Hilbert modular forms, etc...), with standard next/prev buttons, user specified maximum results to display, and no limit on the total number of results.
