### ISSUE TITLE
Siegel modular forms: improve display of Fourier coefficients

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#989]
From /roadmap: Improve the presentation of many and big Fourier coefficients: the user should be able to ask for a range, reduction modulo arbitrary ideals of the number field generated by the coefficients should be possible (currently one can only reduce modulo rational primes).

**Comment by AndrewVSutherland** [comment]
Reduction modulo arbitrary ideals has been implemented but still has a few bugs (see #1571).

A separate issue is what to do when the Fourier coefficients are too large to conveniently display (yes we can reduce them modulo an ideal, but this is not done by default and if it were there isn't an obvious default choice), and also what to do when there are so many (even for a single determinant value) that we do not want to display them all.

**Comment by AndrewVSutherland** [comment]
Addressed by PR #1577.
