### ISSUE TITLE
Random HMF

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#993]
Sometimes clicking on random HMF returns a time out error.

**Comment by jvoight** [comment]
@JohnCremona implemented this, after my random selection wasn't truly "random".  I don't know how important that latter fact is.  Can we randomly choose N (with N = 100 or 1000) and then choose randomly from there?

**Comment by JohnCremona** [comment]
There was no problem until yesterday's change which #988 will fix; I'll check that the random function is fine again after that,

**Comment by JohnCremona** [comment]
Fixed by PR #988
